### ISSUE TITLE
Using emotion 10 in a project that also has react-select with a dependency on emotion 9

### ISSUE THREAD

**Issue by jfrolich** [emotion-js/emotion#1003]
I get below error. Maybe because the cache is only initialized using the provider, but this calls before react has started rendering:
![image](https://user-images.githubusercontent.com/579279/48250542-a3f7e080-e439-11e8-8c32-996f70c0c9d2.png)

**Comment by jfrolich** [comment]
Yes I will

**Comment by jfrolich** [comment]
https://codesandbox.io/s/yw819110pj

**Comment by jfrolich** [comment]
So I found that it works well if you use emotion 10 without using the `emotion` package (just `@emotion/core` etc). But if you use `emotion` it will fail.

**Comment by jfrolich** [comment]
Ok I had the exact same error in CodeSandbox, until I added the CacheProvider. In CodeSandbox the `cache` export of emotion is always `null` 🤷‍♂️. In create-react-app that is not the case, but then it yields another error. So not sure how to exactly replicate this anymore, however, enough errors that shouldn't happen I guess.

**Comment by mitchellhamilton** [comment]
I've found the problem. It's because of some semver stuff, certain packages resolve to older versions that they shouldn't(because they're on prerelease versions, semver is a bit strange). I'm gonna make the ranges more strict which should fix it.

**Comment by jfrolich** [comment]
Great!
