### ISSUE TITLE
Upgrade to latest hoist-non-react-statics

### ISSUE THREAD

**Issue by piotrblasiak** [emotion-js/emotion#1005]
The usage of the old hoistNonReactStatics in withTheme is causing it to break unless it is the first wrapper for some reason. Works with hoist-non-react-statics 3.1.0 so an upgrade of that dep would be welcome.

**Comment by lipedeitos** [comment]
Same problem. Already solved in new version of hoistNonReactStatics.

Here's the related issue from their github:
https://github.com/mridgway/hoist-non-react-statics/issues/66
