### ISSUE TITLE
TypeScript CreateStyledShorthands only usable when babel plugin is enabled

### ISSUE THREAD

**Issue by wereHamster** [emotion-js/emotion#1009]
The following code passes the TypeScript type checker but throws an error at runtime because the shorthands are only supported when the babel plugin is activated.

```javascript
const Foo = styled.div`
  display: flex;
`;
```

I have that code in a library that I publish on npm. The sources of that library are written in TypeScript and only processed by TS but not babel. So now any consumers of my library need to make sure my code in node_modules is being processed by babel.

I see you're using a Proxy to implement the shorthands. Is there a reason why you have to throw?

If throwing is unavoidable, it would be nice to have accurate types. One option would be by providing two module entry points: one "react-emotion" that provides the accurate types (without the shorthand) and "react-emotion/yes-I-have-set-up-babel-emotion-plugin" that includes the shorthands type definitions.

**Comment by Ailrun** [comment]
Thank you for posting an issue!
IMO, If you write an library, you should pre transpile your code with babel, and do not depends on users setting.

**Comment by wereHamster** [comment]
I agree with not having to force babel on consumers of a library.

But it would be nice for someone to tell me that my code is not safe, before I publish it. For that purpose I use TypeScript–a static type checker–to tell me at compile time if I'm doing something stupid. In this particular case, it failed to warn me.

**Comment by wereHamster** [comment]
I see. I'm looking forward for v10 to be released then.

**Comment by Ailrun** [comment]
Thank you for your understanding! and also thank you for using emotion.

**Comment by wereHamster** [comment]
Now that emotion 10 has been released, this can be closed.
