### ISSUE TITLE
Using Emotion in Widgets and how to prevent third-party styles?

### ISSUE THREAD

**Issue by Pczek** [emotion-js/emotion#1010]
Hi,

I planning on switching to emotion from styled-componets. I'm currently building widgets for third party websites to included. We had an issue where the host website is styling an input in general which overrode some of my styles because it was more specific than my simple class generated by styled-components. There is a babel plugin for sc to double the class names to make it more specific or add an id selector infront of every class selector. This is basically what I needed, however it's not working properly.
So I want to ask if there is a mechanism to prevent a host site from overwriting my emotion styling by making it more specific with an id selector?

https://www.styled-components.com/docs/advanced#avoiding-conflicts-with-thirdparty-styles-and-scripts

**Comment by Andarist** [comment]
https://github.com/emotion-js/emotion/issues/712#issuecomment-395912093
