### ISSUE TITLE
[babel-plugin-emtioin] keyframes is not Pure?

### ISSUE THREAD

**Issue by azizhk** [emotion-js/emotion#1011]
I am not sure if this is a question or a bug. Just looking to investigate if either and looking for solutions to make code completely tree-shakeable. (Idea derived from https://github.com/Rich-Harris/agadoo)
If keyframes can be made pure, will create a PR to fix.
If not would be wondering what can be done to make an animatation tree-shakeable.

- `babel-plugin-emotion` version: 9.2.11

Relevant code.

```javascript
const bounceDelay = keyframes({
  "0%, 80%, 100%": {
    transform: "scale(0)"
  },
  "40%": {
    transform: "scale(1)"
  }
});

export const spinnerStyle = css({
  animation: `${bounceDelay} 1.4s infinite ease-in-out both`,
});
```

What happened:
Expected both `css` and `keyframes` call should be marked as `/*#__PURE__*/`
But only `css` was marked as `/*#__PURE__*/`

**Comment by mxstbr** [comment]
We recently reworked the styled-components `keyframes` constructor to be pure by returning a wrapper object and lazily injecting the CSS when the wrapper object is actually used. Pseudo-code:

```JS
// Before
const keyframes = (...input) => return injectAndGetClass(input);
// After
class Keyframes {
  constructor(...input) {
    this.input = input;
  }
  inject() { 
    return injectAndReturnClass(this.input);
  }
  // for backwards compat also inject when `toString`-ified
  toString() {
    return this.inject();
  }
}

const keyframes = (...input) => new Keyframes(...input);

const css = (...input) => if (input[i] instanceof Keyframes) output += input[i].inject();
```

Maybe helpful?

**Comment by azizhk** [comment]
Sorry this was my bug. `babel-plugin-emotion` does add `/*#__PURE__*/`

**Comment by azizhk** [comment]
Though AFAIK what @mxstbr is suggesting is runtime based non-addition of unused animations to CSSOM, which would delay execution till usage.
Maybe can help speed up start-up times of websites where animations are triggered later.
