### ISSUE TITLE
Using the style defined by CSS () in an object, I want to select it through a sub-selector. What should I do?

### ISSUE THREAD

**Issue by Adherentman** [emotion-js/emotion#1012]
- `emotion` version: 9.2.12
- `react` version: 16.5.2

Relevant code.

```javascript
const generateGutter = () => {
styles[`spacing-${breakpoint}-${spacing}`] = css({
      margin: -spacing / 2,
      width: `calc(100% + ${spacing}px)`,
      '& .row': {
        padding: spacing / 2
      }
    })
}

const boxStyle = {
  row: css({
    display: 'flex',
    flexWrap: 'wrap',
    marginLeft: -(gridGutterWidth / 2),
    marginRight: -(gridGutterWidth / 2)
  }),
  ...generateGutter('xs')
}

```

What you did And Problem description:

Using the style defined by CSS () in an object, I want to select it through a sub-selector.But the above method is useless.
I can only go to `console.log` to get the classname name of row.
example:
```javascript
const generateGutter = () => {
styles[`spacing-${breakpoint}-${spacing}`] = css({
      margin: -spacing / 2,
      width: `calc(100% + ${spacing}px)`,
      '& .css-1jwsg2l': {
        padding: spacing / 2
      }
    })
}
```

Suggested solution:
I don't know what to do.

**Comment by Andarist** [comment]
The cascade is discouraged in emotion and we intentionally don't want to support this. Sorry for not getting to your sooner, hope you understand.
