### ISSUE TITLE
v10 inline <style> tags should get display: none

### ISSUE THREAD

**Issue by piotrblasiak** [emotion-js/emotion#1015]
In my CSS, I often use selectors like `"& > *": {display: "inline-block"}` to style children, and I noticed that the SSR style tags were getting rendered, because of the `display: "inline-block"` so now I do a global `style {display: none !important}` to avoid this, but maybe setting this inline on the style tags, at least when they´re not in <head> would be a good idea? It took me a little while to figure out as the style tags were moved into head client-side as so it was a confusing flash of text which required me to disable client-side js to see.

**Comment by katywings** [comment]
I just also noticed this. Any updated on it? :)

**Comment by piotrblasiak** [comment]
Haven't heard anything yet.

**Comment by Andarist** [comment]
We'll consider this for the upcoming v11. No guarantees though.

**Comment by Andarist** [comment]
This would add bytes to SSRed output and as we in general discourage use of selectors like this we don't feel like implementing this. You should be able to easily add this on your side using Global component.

Sorry that you had to wait for an answer so long. Hope you understand.
