### ISSUE TITLE
cx - order of combined classes is reversed in certain scenarios

### ISSUE THREAD

**Issue by lukaszfiszer** [emotion-js/emotion#1019]
**Problem description**:

When passing more than one emotion-generated class names AND a custom class name to `cx` the returned string contains classes in reversed order

- `emotion` version: 9.1.12
- `react` version: n/a

**Relevant code**:

```javascript
import { cx, css } from "emotion";

const cls1 = css(``);
const cls2 = css(``);

const combinedClass1 = cx(cls1, "custom-class");
const combinedClass2 = cx(cls1, cls2, "custom-class");

console.log("combinedClass1:", combinedClass1)
console.log("combinedClass2:", combinedClass2)
```

**What happens**:

```
combinedClass1: css-0 custom-class
combinedClass2: custom-class css-0
```

**What should happen**:

```
combinedClass1: css-0 custom-class
combinedClass2: css-0 custom-class 
```

**Reproduction:**

See https://codesandbox.io/s/3yn8m9q33q

**Comment by Andarist** [comment]
The class names order doesn't matter - the only thing relevant for CSS is insertion order in stylesheets.

**Comment by lukaszfiszer** [comment]
You're obviously 100% correct! Closing.
