### ISSUE TITLE
Feature suggestion for style Isolation

### ISSUE THREAD

**Issue by carpben** [emotion-js/emotion#1022]
Emotion has significantly improved my experience of styling JavaScript applications. Thanks. 
The main issue I still struggle with is isolating the style of my apps/components from the environment it runs in. In my work I build components which are embedded in different pages of the company's website, and I also build a widget that is added to other websites. It often looks different depending on the environment. 
I believe today almost total isolation is possible even without iframe. This can be done by: 

1. Adding an id to the root element and to the css selector as descreibed in https://github.com/emotion-js/emotion/issues/712. 
2. Resetting all styles of the root element to a common ground, so all inherited properties are the same, and unsetting styles from all elements before adding our own styles. This can be done by adding the following css rules to the root element.  
```
	all: initial;
	* {
		all: unset;
	}
```

The only case this can't solve is the !important value. 

I wonder if it is worth offering such a feature out of the box. Either in a dedicated library, or by allowing users to easily opt in.

**Comment by Andarist** [comment]
https://github.com/emotion-js/emotion/issues/712#issuecomment-395912093

**Comment by carpben** [comment]
My recent challenge was with a widget I am building that should be embedded in various websites. In one of the tests I conducted the body element had an id, and css rules targeted this id to create more specific styling rules. Here is an example for such a rule: 
```
body#${someID} a:hover
```
This rule is quite specific, and presents a challenge - how to build an app isolated from such rules. Here is a copy of my solution https://github.com/carpben/isolated-widget .
The body element has an id and specific css rules are targeting that id (https://github.com/carpben/isolated-widget/blob/master/public/index.html).  
In app.tsx I simply import import { css, IsolatedApp, keyframes } from "./isolatedEmotion" And I wrap my app with the IsolatedApp element.

**Comment by Andarist** [comment]
👍 That's basically what we do too (custom emotion instance) - only for other purposes that isolating the app. The problem with this isolation technique for widgets is that you widget always run in hostile environment (customer's page 😅) - and this is not only about CSS, but also about JS. You can run into patched globals problems very easily and because of that it's nearly always to isolate yourself in an iframe. That way you don't run into those problems.

**Comment by carpben** [comment]
This widget is a bundle of preact. I thought that the builder (typescript's builder in this case) scopes all the code, so unless I save things as globals (to the window object for example) conflicts aren't possible. Am I wrong?

**Comment by Andarist** [comment]
You can't guard yourself against other code messing up with globals that you use. Welcome to the mootools world 😉 

Just a thing I've encountered **recently**
```js
// code on the site
Array.prototype.indexOf = function (item) {
  for (var i = 0; i < this.length; i++) {
    if (this[i] === item) {
      return i
    }
  } 
}

// your lib
if (someArray.indexOf(someItem) === -1) {
  // BROKEN!!! the manipulated global Array.prototype.indexOf won't ever return -1 (although it should), it returns undefined for items which are not in the array
}
```

**Comment by carpben** [comment]
Excellent example. Thanks.

**Comment by Andarist** [comment]
I believe the issue itself can be closed here, feel free to ask more questions though or create a new one.

**Comment by carpben** [comment]
Hi, 
So I fancy style isolation (or independence) also in our own environement. As mentioned in https://github.com/emotion-js/emotion/issues/712 Bootstrap kind of interferes there. Does Emotion 10 provide a new technique/approach for solving this challenge?

**Comment by Andarist** [comment]
@carpben I would try this plugin https://github.com/Andarist/stylis-plugin-extra-scope . Keep in mind that even though I have authored it I have not used it in production.

**Comment by carpben** [comment]
@Andarist , Thx. I tried it for a small widget project, and it worked quite well. However, I wondered if Emotion10 offers something out of the box.
