### ISSUE TITLE
eslint-plugin-emotion not working

### ISSUE THREAD

**Issue by cadejscroggins** [emotion-js/emotion#1024]
I'm probably missing something obvious here, but...

- `emotion` version: 9.2.12
- `react` version: 16.6.3
- `eslint-plugin-emotion` version: 9.2.6

Relevant code.

```javascript
// .eslintrc.json
{
  "env": { "browser": true },
  "extends": ["airbnb", "prettier", "prettier/react"],
  "parser": "babel-eslint",
  "plugins": ["emotion", "prettier"],
  "rules": {
    "emotion/import-from-emotion": "error",
    "emotion/jsx-import": "error",
    "emotion/no-vanilla": "error",
    "emotion/styled-import": "error",
    "prettier/prettier": "error",
    "react/jsx-sort-props": "error",
    "sort-keys": "error"
  }
}
```

What you did: I ran eslint.

What happened: I got the following errors for each file:

```
1:1  error  Definition for rule 'emotion/import-from-emotion' was not found  emotion/import-from-emotion
1:1  error  Definition for rule 'emotion/jsx-import' was not found           emotion/jsx-import
1:1  error  Definition for rule 'emotion/no-vanilla' was not found           emotion/no-vanilla
1:1  error  Definition for rule 'emotion/styled-import' was not found        emotion/styled-import
```

Reproduction:

1. clone https://github.com/cadejscroggins/amplify-sandbox
2. run `yarn`
3. run `yarn lint`

Problem description: N/A

Suggested solution: N/A

Thanks in advance.

**Comment by Ailrun** [comment]
@cadejscroggins It's because you used old version which does not include those rules.
You see the rules of 9.2.6 in the following link.
https://github.com/emotion-js/emotion/tree/v9.2.6/packages/eslint-plugin-emotion
If you want to use other rules, you should use `@emotion/core` (or other emotion V10 packages) with  eslint-plugin-emotion.

**Comment by cadejscroggins** [comment]
Got it. Thank you.
