### ISSUE TITLE
injectGlobal, with theme

### ISSUE THREAD

**Issue by cyrilchapon** [emotion-js/emotion#1028]
Hey,

I'm trying to `injectGlobal` with theming stuff.

```
html {
  font-size: ${props.theme.sizes.normal}px;
}
```

I found [this](https://github.com/emotion-js/emotion/issues/546) but it doesn't realy do the stuff... the provided solution hardly sets the style in `style=""` prop of the DOM nodes on `didUpdate`...

I think I have to create a component (children of `<ThemeProvider>`) that `injectGlobal` on `willReceiveNewProps`, but I found that `injectGlobal` hardly inserts the `<style>` node without a logic of replacement included.

**Comment by mitchellhamilton** [comment]
This is possible with the Global component in v10.

https://codesandbox.io/s/o419j90opq
