### ISSUE TITLE
emotionjs site

### ISSUE THREAD

**Issue by Komar0ff** [emotion-js/emotion#1031]
Problem description:
I can not go to the site(https://emotion.sh ) from different regions of Russia.
Your site may have been blocked. Saves only VPN.

**Comment by Ailrun** [comment]
Our site is emotion.sh. Could you check this one?

**Comment by Komar0ff** [comment]
@Ailrun oh wait... Yes, Of course https://emotion.sh. Sorry for the mistake.
I sometimes can't enter on https://emotion.sh site
