### ISSUE TITLE
TS Styled Plugin doesn't recognize the label property as legitimate 

### ISSUE THREAD

**Issue by carpben** [emotion-js/emotion#1037]
- `emotion` version: 9.2.12
- `react` version: 16.6

Relevant code. 
In a typescript .tsx file
```typescript
const Box = styled("div")`
   label: switch-row; 
   display: flex; 
   justify-content: space-between; 
   align-items: center; 
   margin: 0  0 15px;  
`
```
It compiles well and works well. But Visual Studio Code complains. There is a green line under label with the following message: "[ts-styled-plugin] Unknown property: 'label'"
![image](https://user-images.githubusercontent.com/13496178/49009215-addb4c80-f178-11e8-852f-ed22e9ccfc8d.png)

**Comment by Ailrun** [comment]
Thank you for reporting the issue!
However, IMO, the issue is about ts-styled-plugin, not about emotion. We cannot fix how ts-styled-plugin works.

**Comment by carpben** [comment]
Of course. Thanks.

**Comment by lettertwo** [comment]
In case it is useful for anyone else googling their way through this and other [closed issues](https://github.com/Microsoft/typescript-styled-plugin/issues/57), there is now a way to get ts-styled-plugin to accept the `label` property:

in `tsconfig.json`:
```json
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "lint": {
          "validProperties": "label"
        }
      }
    ]
  }
}
```


Discovered in https://github.com/Microsoft/typescript-styled-plugin/issues/58#issuecomment-444733368

**Comment by robinmetral** [comment]
Hi @lettertwo, this doesn't fix it for me, do you have anything else in your `tsconfig.json`?

My project doesn't actually use typescript so I had to create this file.

**Comment by hatton** [comment]
> this doesn't fix it for me, do you have anything else in your tsconfig.json?

I found I had to give it an array:

`"validProperties": ["label"]`

(and then reload my vscode window).

**Comment by robinmetral** [comment]
@hatton you're right, according to the plugin's README, `validProperties` takes an array.

However this still didn't fix it for me, probably because my project doesn't use Typescript (yet 😛).

I found the fix, at least for VS Code. Instead of a `tsconfig.json` file, I added a [**`jsconfig.json`**](https://code.visualstudio.com/docs/languages/jsconfig) at the root of my project:

```json
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "lint": {
          "validProperties": ["label"]
        }
      }
    ]
  },
  "include": ["src/**/*"]
}
```

**Comment by Rocamonde** [comment]
@robinmetral `tsconfig.json` is a configuration file for the TypeScript runtime/compiler. If you are not using TypeScript, this file will obviously have no effect in your runtime.

**Comment by robinmetral** [comment]
@Rocamonde in this case `tsconfig.json` has nothing to do with compiling. We're just using it to pass custom linting rules to the `ts-styled-plugin` dependency of Emotion.

And as explained [here](https://code.visualstudio.com/docs/languages/jsconfig):
```
`jsconfig.json` is `tsconfig.json` with `"allowJs"` attribute set to true.
```

So `tsconfig.json` for JS projects obviously doesn't compile the code, but it does have an effect on linting, which is what this issue is about.

**Comment by Rocamonde** [comment]
@robinmetral my apologies. I didn’t know that the plugin also worked for JS files — thought it was TypeScript only.

**Comment by kevinchou-pge** [comment]
It appears the input property max-length also has the same issue.

**Comment by talentlessguy** [comment]
Same with `text-underline-offset`

**Comment by Seanmclem** [comment]
Since my errors were with `typescript-styled-plugin`

I had to use, in my `tsconfig.json` file

```javascript
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true,
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "lint": {
          "validProperties": [
            "padding-vertical",
            "padding-horizontal",
            "shadow-color",
            "shadow-offset",
            "shadow-radius",
            "shadow-opacity"
          ]
        }
      }
    ]
  }
}

```

**Comment by MohammedYoussefSoliman** [comment]
you may try this:
`${css`
    label: container;
  `}`

**Comment by dylancagnotti** [comment]
The solution provided is not working for me.

`{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "lint": {
          "validProperties": ["label"]
        }
      }
    ]
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
`

I added the plugin to the tsconfig.json at the root of my project. 
However, even after restarting vscode, I still see the errors.

I'm using vite, if that somehow has an influence.

I also have an eslintsr.cjs file, but I don't think that matters?

The extension is version 1.7.8

**Comment by ricardxalvarez** [comment]
https://github.com/microsoft/typescript-styled-plugin was archived, I don't know if due to this reason, It has not been working lint validProperties. I tried to install an older version and it still didn't work, so I'll probably have to live with that warning.

**Comment by dylancagnotti** [comment]
> https://github.com/microsoft/typescript-styled-plugin was archived, I don't know if due to this reason, It has not been working lint validProperties. I tried to install an older version and it still didn't work, so I'll probably have to live with that warning.

I think I figured it out:

Inside the tsconfig.json instead of: 

```
 "plugins": [
      {
        "name": "typescript-styled-plugin",
        "lint": {
          "validProperties": ["label"]
        }
      }
    ]
```

Try to use 

```
 "plugins": [
      {
        "name": "@styled/typescript-styled-plugin",
        "lint": {
          "validProperties": ["label"]
        }
      }
    ]
```

For me, it worked this way!

**Comment by Amoong** [comment]
@dylancagnotti wow... I finally resolve this. Thanks!

**Comment by adamerose** [comment]
Could this be somehow fixed by the emotion package? It's not great DX that using documented emotion syntax gives typescript warnings unless you add custom TS config. 

I don't think this would ever get fixed upstream because the `styled-components.vscode-styled-components` extension and `typescript-styled-plugin` plugin are specifically for `styled-components` which doesn't support the `label` property so the warning is correct. 

I can't find any linter/highlighter specifically for Emotion, it seems like everyone just uses the Styled Components tools: https://github.com/emotion-js/emotion/issues/1316
