### ISSUE TITLE
Changing theme does not update components

### ISSUE THREAD

**Issue by piotrblasiak** [emotion-js/emotion#1041]
I´m using emotion10 and changing the theme in with ThemeProvider does not make the components using themes update. Is this the expected behavior or a bug, and/or is there a workaround?

**Comment by Andarist** [comment]
It should rerender. Can u prepare codesandbox showcasing the problem?

**Comment by mitchellhamilton** [comment]
Are you using `emotion-theming@next`?

**Comment by piotrblasiak** [comment]
Yes, 10 beta 13. Will try to reproduce on codesandbox and get back to you. Good to know that´s how it´s supposed to work at least.

**Comment by piotrblasiak** [comment]
Sorry for wasting your time guys. My mistake of course - I tried it on the sandbox and it worked flawlessly so found the problem in my code which was something else entirely as usual. Dark mode here we come :)

**Comment by oliviertassinari** [comment]
On a related note, I was curious. Updating the theme updates the components that don't use it: https://codesandbox.io/s/admiring-dhawan-77tmu?file=/src/App.tsx. I can understand why, it's hard to know if the theme with the public API

**Comment by Andarist** [comment]
Right - the theme is consumed [here](https://github.com/emotion-js/emotion/blob/06b314725db578439181331691976beb41203cf5/packages/styled/src/base.js#L85) without any conditions to make it available to all interpolations. It's rather hard to optimize this because of the "rules of hooks".
