### ISSUE TITLE
[native] [emotion 10] can't find variable document

### ISSUE THREAD

**Issue by kevinwolfcr** [emotion-js/emotion#1050]
- `emotion` version: 10.0.0
- `react` version: native (expo snack)

What you did:

Trying to migrate from `@emotion/native`@`9.2.9` to `@emotion/native`@`10.0.0` gives error on React Native.

What happened:

![screen shot 2018-11-28 at 20 27 35](https://user-images.githubusercontent.com/3157426/49195381-7e7d3900-f34c-11e8-9d2b-ff15cf58b202.png)

Reproduction:

https://snack.expo.io/@kevinwolf/emotion-10-issue

Problem description:

`@emotion/core` is trying to use `document` here: https://github.com/emotion-js/emotion/blob/master/packages/core/src/global.js#L75, but React Native does not have this variable.

**Comment by Andarist** [comment]
cc @nitin42

**Comment by nitin42** [comment]
Sorry for being not responsive 😓

Can't make any promises but, I'll try to stay active (a little) from next week.

Props to the emotion team for the great work. @mitchellhamilton, you've done a stellar work on the new release 👌

**Comment by kevinwolfcr** [comment]
Fixed on `@emotion/native`@`10.0.1`. Thanks, emotion team! 🎉
