### ISSUE TITLE
Using v10 "cx" function does not "work the same" as v9

### ISSUE THREAD

**Issue by meebix** [emotion-js/emotion#1052]
- `emotion` version: v10.0.0
- `react` version: 16.6.1

The new documentation for "Class Names" suggests that the "cx" function from the render prop `<ClassNames` "works exactly the same" as v9. While that may actually be true, in the complete context of using the `cx` function, I have not found that to be the case.

I can no longer pass variables to the `cx` function in the same manner as before. Can someone please provide me with a more full example of how to use the new `cx` function?

```js
/** @jsx jsx */
import { ClassNames, css, jsx } from '@emotion/core';
import styled from '@emotion/styled';

const type = css`
  color: #708da0;
  font-size: 0.875em;
`;

const required = css`
  ${type};
`;

const requiredTrue = css`
  ${required};
  color: #e42c0c;
`;

...

  return (
    <ClassNames>
      {({ cx }) => (
          {sortedDefinitions.map(argument => {
            const requiredClass = cx(required, {
              [requiredTrue]: argument.required,
            });

            return (
              <div css={requiredClass}>Required</div>
            );
          })}
      )}
    </ClassNames>
  );
```

`required` and `[requiredTrue]` were picked up just fine in v9, but not in v10. This seems to be due to the fact that `css` from `@emotion/core` returns an object now, but I do not understand how to rectify this.

**Comment by meebix** [comment]
Eh, apparently I **must** use the `css` function from the new `ClassNames` exported from emotion/core. Therefore I have to restructure my code and _everything_ has to be inside the render prop. 

Not a huge fan of that organization, but it works.

**Comment by Andreyco** [comment]
Dont like render props approach as well. Makes me stick with v9 or picking other solution.

**Comment by mattlo** [comment]
@meebix @Andreyco Yep, to this day, I continue to use v9 for new projects. It's way easier to compose styles and more flexible with different coding patterns a developer might use.
