### ISSUE TITLE
Styles are output multiple times during SSR

### ISSUE THREAD

**Issue by staylor** [emotion-js/emotion#1061]
- `emotion` version: 10.0.0
- `react` version: 16.6.3

**Relevant code.**

```javascript
import styled from '@emotion/styled';

const Header = styled.h1`
  color: green;
  font-size: 48px;
  line-height: 48px;
`;

function App() {
  return (
    <section>
      <Header>HI</Header>
      <Header>How</Header>
      <Header>Are</Header>
      <Header>You?</Header>
    </section>
  );
}
```

**What you did:**

Rely on automatic SSR

**What happened:**

The styles are output before every instance of `<Header>`. Rules are repeated 4 times.

**Reproduction:**

Render the same styled component multiple terms during SSR

**Problem description:**

I expect the styles to only be output once.

**Suggested solution:**

Ensure that styles are unique when output.

**Comment by mitchellhamilton** [comment]
This will only happen when there isn’t a common ancestor that uses emotion. If there is a parent component that uses emotion it will work fine and the styles won’t be duplicated.

This is a trade off we make, in most cases it will work okay. We haven’t figured out a way to fix this yet, though it might be possible to fix in the future. Cases like this are obviously not great but for most people it will work fine.

**Comment by Andarist** [comment]
Is it possible to at least warn about it in dev mode?

**Comment by staylor** [comment]
can you link to the rationale doc for switching to this new API?

**Comment by leebenson** [comment]
@mitchellhamilton - how about a simple de-dupe step of some kind? e.g. updating a WeakSet with a class name and if it already exists, avoid rendering a duplicate `<style>` tag?

In my particular use-case, the same tag is being output **30** times:

<img width="1440" alt="screenshot 2019-01-26 at 13 29 09" src="https://user-images.githubusercontent.com/719722/51787857-bd721400-216e-11e9-85cc-2b1b88e5f751.png">

Every `<style>` tag is identical.

**Comment by luishdz1010** [comment]
This also happens with <Global>, no matter if there are parent components I get the same exact Global style rendered many times. My use case involves the rendering of several @font-faces depending on each component's data.

**Comment by jsanchez034** [comment]
Anyone find a workaround for this? @mitchellhamilton not sure what you meant by..

> This will only happen when there isn’t a common ancestor that uses emotion. If there is a parent component that uses emotion it will work fine and the styles won’t be duplicated.

Could you give an example of a common ancestor that uses emotion? I have some code that basically looks like this that runs into this error...
```
import { css, jsx } from "@emotion/core";
import OtherComponent from `./OtherComponent';
import test from './some-function';

const myCss = test();
// above returns something like..
// {
//  fontSize: '14px'
// }

export default function MyComponent() {
   return <OtherComponent css={myCss} />
}
```
and then in another component..
```
import MyComponent from './MyComponent';

function App() {
  return (
    <MyComponent />
    <MyComponent />
    <MyComponent />
  );
}
```
In the above example an identical style tag is rendered for every instance of `MyComponent`. But if I change `MyComponent` to..
```
import { css, jsx } from "@emotion/core";
import OtherComponent from `./OtherComponent';
import test from './some-function';

const myCss = {
  fontSize: '14px'
};

export default function MyComponent() {
   return <OtherComponent css={myCss} />
}
```
There is no repetition of style tags.

**Comment by leebenson** [comment]
Here's an example -> https://github.com/leebenson/reactql/blob/master/src/components/example/hackernews.tsx#L21

I created a wrapped `<ul>`. Even though there's no styling attached, it's an Emotion-created component, which prevents the child `<li>` tags from experiencing the error.

Basically - as long as at least _one_ parent is controlled by Emotion whenever there are multiple siblings that share the same class, this error won't show up -- at least in the use-cases I've encountered.

I still think there should be some sort of de-dupe happening in the lib, although I'm not sure if there have been any efforts to fix this yet. For now, just create a `styled.*` tag somewhere in your HTML hierarchy that's above wherever you're using identical sibling tags.

**Comment by Andarist** [comment]
The issue can also be "fixed" by wrapping your application within a CacheProvider component. Without it, the first emotion-based component has to create wrap its subtree within one - but obviously each sibling has to do it on its own (in such case) and this causes this duplication.

This is not a problem per se - just a tradeoff for things working "out of the box". Still, this can be easily "fixed" (as described here and above) if you care about this.

**Comment by axeen** [comment]
> The issue can also be "fixed" by wrapping your application within a CacheProvider component. Without it, the first emotion-based component has to create wrap its subtree within one - but obviously each sibling has to do it on its own (in such case) and this causes this duplication.
> 
> This is not a problem per se - just a tradeoff for things working "out of the box". Still, this can be easily "fixed" (as described here and above) if you care about this.

How would this be done more specifically?

**Comment by andgra** [comment]
> > The issue can also be "fixed" by wrapping your application within a CacheProvider component. Without it, the first emotion-based component has to create wrap its subtree within one - but obviously each sibling has to do it on its own (in such case) and this causes this duplication.
> > This is not a problem per se - just a tradeoff for things working "out of the box". Still, this can be easily "fixed" (as described here and above) if you care about this.
> 
> How would this be done more specifically?

The easiest way is to wrap your whole app in custom CacheProvider (https://emotion.sh/docs/cache-provider). For me, it fixed the problem.
But the downside is you must set up ssr manually (https://emotion.sh/docs/ssr)

**Comment by Andarist** [comment]
It should be also possible to just wrap your top-level component with a single extra div with a css prop used on it because when SSRed it will act as a CacheProvider automatically.

**Comment by AshConnolly** [comment]
It's worth noting the [next.js emotion example](https://github.com/vercel/next.js/blob/canary/examples/with-emotion/pages/_app.js) does this too.

For anyone curious, in `pages/_app.js`, import `CacheProvider` and `cache`, then wrap your whole app with `CacheProvider`, and set cache as a `value` prop:
```js
import React, { Component } from 'react'
import { CacheProvider, Global } from '@emotion/core'
import { cache } from 'emotion'

const MyApp = ({ Component, pageProps }) => {
  return (
    <CacheProvider value={cache}>
      <Component {...pageProps} />
    </CacheProvider>
  )
}

export default MyApp
```
OR, the other suggestion of adding a div in the top level component with the css prop also worked, and didnt mean adding `emotion` as a dep, much neater!
```js
import React, { Component } from 'react'
import { css } from '@emotion/core'

const MyApp = ({ Component, pageProps }) => {
  return (
    <div css={css` margin: 0;`}>
      <Component {...pageProps} />
    </div>
  )
}

export default MyApp
```
Both solved my issue. 

Would be good if the SSR docs could be updated with this information. Currently it the SSR Next.js docs, after saying the _doc.js file needs changes, has this callout:

> This only applies if you’re using vanilla Emotion or a version of Emotion prior to v10. For v10 and above, SSR just works in Next.js.

Which for me, with the huge amount of duplicate style tags making the pages much larger,  wasn't a case of it just working out of the box. 

Thanks @Andarist 👍

**Comment by Andarist** [comment]
Documentation PRs are always welcome 😉

**Comment by shobhitsharma** [comment]
I am still encountering this issue using next.js with custom koa server, I tried both babel and custom `CacheProvider` both doesn't work in SSR. Has anyone managed to solve it?

cc @mitchellhamilton

**Comment by sgehrman** [comment]
same issue.

**Comment by Chisom-Maxwell** [comment]
> The issue can also be "fixed" by wrapping your application within a CacheProvider component. Without it, the first emotion-based component has to create wrap its subtree within one - but obviously each sibling has to do it on its own (in such case) and this causes this duplication.
> 
> This is not a problem per se - just a tradeoff for things working "out of the box". Still, this can be easily "fixed" (as described here and above) if you care about this.

this did not work for me.

**Comment by caub** [comment]
@mitchellhamilton I understand, but this annoying because it's more practical to define styles near the component itself

I hope you'll figure a solution, at least deduping when the styles are adding in consecutive siblings in a list, that should be possible

Thanks for your work anyway

**Comment by rgerio** [comment]
I'm using Next,js with Material UI and Emotion and I had the same problem. I solved by adding a `<Container />` wrapping my app main component:
```
import type { AppProps } from 'next/app';
import Container from '@mui/material/Container';

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Container maxWidth={false} disableGutters>
      <Component {...pageProps} />
    </Container>
  );
}
```

**Comment by Andarist** [comment]
@rgerio and it works because this `Container` renders internally a `CacheProvider`. If anybody can provide a repro case for the `CacheProvider` solution not working for them - I could take a look at it.

**Comment by zopelee** [comment]
> 

our workaround:

```
const globalCss = `body { width: ${xxx}; }`

return (
  ...
  <style>{globalCss}</style>
  ...
)
```

**Comment by caub** [comment]
Not using next.js I tried this: https://replit.com/@caub/emotion-dup-styles#index.js

```jsx
import { CacheProvider, Global } from '@emotion/react';
import { cache } from '@emotion/css';
import styled from '@emotion/styled';

const Bg = styled.div({
  backgroundColor: '#48c'
});

const Sub = ({ children }) => <Bg>[children}</Bg>;

const app = (
  <CacheProvider value={cache}>
    <Global styles={{ div: { margiin: 0 } }} />
    <Sub>Test 1</Sub>
    <Sub>Test 2</Sub>
  </CacheProvider>
)
```

Then react renderToStaticMarkup doesn't give any styles

I can see them in cache, what's the properway to add them in the markup? `Object.values(cache.inserted).join('\n')`?

**Comment by felixcatto** [comment]
For me this is works perfectly. And i don't even need to do additional SSR setup on server. It works automatically, and returns html with **injected style tags**.

```javascript
import { CacheProvider } from '@emotion/react';
import createCache from '@emotion/cache';

const myCache = createCache({ key: 'css' });

export const App = () => {
  return <CacheProvider value={myCache}> ... </CacheProvider>;
};
```

**Comment by zecka** [comment]
CacheProvider seems work:

Here is a stackblitz example

https://stackblitz.com/edit/emotion-nextjs-avoid-duplicate-css-with-cache-provider?file=pages%2F_app.js,shared%2Fstyles.js,pages%2Findex.js

**Comment by SWICRIOT** [comment]
Just bumped into this problem as well using Material UI. Suddenly my page went super slow and after some profiling I found that I have around 7 000 style tags inserted. First attempt at shotgun-fixing this with CacheProvider was a dud but regardless I think it would be good to solve this better from a library point-of-view. I'm just using some UI components, I think it's unexpected that I have to troubleshoot this kind of problem and I don't see how it should belong to my problem domain as a consumer.
