### ISSUE TITLE
[primitives] [emotion 10] Sketch example: "Can't find variable: document"

### ISSUE THREAD

**Issue by adaptivdesign** [emotion-js/emotion#1062]
- `emotion` 10.0.0:

**Relevant code.**

Sketch Example at https://github.com/emotion-js/emotion/tree/master/packages/primitives

**What you did:**

I tried out the example.

**What happened:**

The following error occured: `ReferenceError: Can't find variable: document`. Traced back to packages/cache/src/index.js  -> line 70 : at the  createCache method.

**Problem description:**

This problem is not specifically caused by the primitives package but rather by the @emotion/cache package. The skpm builder internally uses webpack and is configured to use look for "browser" field in all the packages. The resulting browser build strips out the `if (isBrowser)` statements.

We could argue that the skpm builder uses an invalid webpack configuration and should exclude "browser" from the mainFields, but unfortunately this introduces a lot of errors.

Suggested solution:

I got the example working by removing the `browser` field from packages/cache/package.json.

**Comment by adaptivdesign** [comment]
I agree, in the meanwhile emotion can solve this issue by itself. As you suggest add a new mainfield called "sketch" and update documentation for sketch example to include a `webpack.skpm.config` with the following:

```
module.exports = function(config, isPluginCommand) {
  config.resolve.mainFields = ['sketch', 'browser', 'module', 'main']
  return config
}
```

**Comment by Andarist** [comment]
That's rather weird for us to add a custom field to our package.json which is not yet standardized anyhow.

What you can do to solve this temporarily on your side is to include smth like this:
```js
module.exports = function(config, isPluginCommand) {
  config.resolve.alias = config.resolve.alias || {}
  config.resolve.alias['@emotion/cache'] = require.resolve('@emotion/cache')
  return config
}
```

**Comment by Andarist** [comment]
I agree that we need to fix the docs regarding this, but IMHO we don't have to edit our package.json before skpm decides to support sketch field, because anyway it needs some custom setup on your side and it doesnt matter which one of the given snippets do you use. The latter (the one using `alias`) should just work the same without us needing to add a special non-standard stuff.
