### ISSUE TITLE
create-emotion-styled in emotion v10?

### ISSUE THREAD

**Issue by RoystonS** [emotion-js/emotion#1064]
- `emotion` version: 10.0.1
- `react` version: 16.7.0-alpha2

Problem description:

I'm currently attempting to update a significant (TS) codebase from Emotion 9 to Emotion 10 but I can't figure out what the equivalent of `create-emotion-styled` now is.  We need to construct our own custom `emotion` because we need to insert various `stylis` plugins.

With Emotion 9 I would create a custom `emotion` object, passing in my `stylis` plugins.  That's still fine with Emotion 10. But with v9 I would then go on to create a custom `styled` object using 
`createEmotionStyled` from the `create-emotion-styled` package, passing in that custom emotion instance.  But I can't figure out what the equivalent of that step is with Emotion 10.

Suggested solution:

Add some documentation to explain how we use custom emotion instances (e.g. with stylis plugins) with `styled`.

**Comment by RoystonS** [comment]
So is there any point using `create-emotion`?

**Comment by Andarist** [comment]
When using react i dont think so, its useful for integrating with other frameworks or with vannila js

**Comment by sampotts** [comment]
Is there an example of how to replace/upgrade `createEmotionStyled` in v10 syntax? I have the same setup where I have to inject a stylis plugin to make all styles `!important` as they're embedded on external websites.

**Comment by Andarist** [comment]
You should be able to follow this demo - https://codesandbox.io/s/8x51k1mp2l - the answer is to use `CacheProvider` instead.

**Comment by Andarist** [comment]
I'm closing because lack of the new activity in the thread and because the answer was given. Feel free to open new issues.

**Comment by davesnx** [comment]
Hey @Andarist 

I wanted to use `create-emotion-styled` in order to have more than one instance of emotion per page. 

Should I use cacheProvider too? I'm using Preact right now and cacheProvider internally uses React.createContext and makes it very tricky to use.

**Comment by sampotts** [comment]
@davesnx I’ve had to use Preact X. It’s in beta but should go to stable in a week or two by the sound of it. Works well with the latest emotion.
