### ISSUE TITLE
(Bug): when rendering conditional styles break styles into additional classes

### ISSUE THREAD

**Issue by lifeiscontent** [emotion-js/emotion#1065]
- `emotion` version:
- `react` version:

Relevant code.

https://codesandbox.io/s/w0kw14w3y7

What you did:

created a menu with a fluid prop

What happened:

all items except the first should have a seperator, in the example that obviously isn't the case due to either a bug or something I'm not considering in emotion.

Reproduction:

Problem description:

this is due to styles not being copied over to the conditional style.

Suggested solution:

instead of copying additional styles to a condition, conditional styles should just be broken down into additional classNames that get appended to the dom when they are being rendered.

**Comment by lifeiscontent** [comment]
cc @Andarist @mitchellhamilton

**Comment by mitchellhamilton** [comment]
This isn't a bug in emotion. The correct styles are being applied if you look in devtools.

**Comment by lifeiscontent** [comment]
@mitchellhamilton how would code something in emotion so that each item except for the first has a &::before?
