### ISSUE TITLE
user-select is not prefixed

### ISSUE THREAD

**Issue by Runjuu** [emotion-js/emotion#1079]
- `emotion` version: 10.0.4
- `react` version: 16.3.0

Relevant code.

```javascript
import { css } from '@emotion/core';

console.log(
  css({ userSelect: 'none' }).styles
); // user-select:none;
```
Problem description:
user-select without prefix is not fully supported by most modern browser, see [caniuse](https://caniuse.com/#search=user-select)

**Comment by Andarist** [comment]
Could u report it at https://github.com/thysultan/stylis.js ? It's a parsing/autoprefixing solution that we use.

**Comment by mitchellhamilton** [comment]
This isn't actually an issue. Prefixing occurs when styles are inserted so the prefixes aren't on the styles property of a style object.

https://codesandbox.io/s/570200q3n

**Comment by Runjuu** [comment]
@mitchellhamilton @Andarist Oh! It must my mistakes. Sorry about that 😂.  btw, Nice jobs~
