### ISSUE TITLE
Lets get some docs really going.

### ISSUE THREAD

**Issue by tkh44** [emotion-js/emotion#108]
The reorganization and expansion of the docs. 

**If you would like to help please open PRs**

We need to move/merge the docs that are inlined in the readme and put them into their relevant file in the `docs` folder. When moving the files over it may be tempting to just delete the entire code block. Keep in mind we will have these linked to in the readme so they still need some context.

If you need to expand a live example. 

1. find or add the example in `example/src/blocks/[your-example].example`
2. update the code to demonstrate what you need to. Please keep these demos focused and remember you can have more than one example per section. 

The currently available variables are
```
avatarUrl,
css,
React,
styled,
render
```

3. Once you have your docs and your examples ready go into `main.js` and copy/paste a similar group of Markdown and Playground and modify however needed.

4. open pr

If you start working on a section make sure to note it here so we don't step on each other's toes

**Comment by andrewdelprete** [comment]
Hey @tkh44, would an initial PR help where I just moved the sections from the README over to their associated files in the docs and just link to them from the README? I don't really have anything to add to the docs atm but could at least move some stuff around if it's helpful.

Thx!

**Comment by tkh44** [comment]
@andrewdelprete That would be very helpful. Thank you!

**Comment by andrewdelprete** [comment]
@tkh44 - It looks like I broke some deps in `src/main.js`... Adding another PR shortly.
