### ISSUE TITLE
Requires React

### ISSUE THREAD

**Issue by snaptopixel** [emotion-js/emotion#1081]
- `emotion` version: latest
- `react` version: none

Relevant code.

```ts
import { css } from '@emotion/core'
```

What you did:
Tried to use Emotion with StencilJS. The docs mention that it's able to be used without React, but that doesn't seem to be true.

What happened:
```
[ ERROR ]  TypeScript: node_modules/@emotion/core/types/index.d.ts:17:7
           Cannot find module 'react'.

     L16:    createElement
     L17:  } from 'react'
```

**Comment by Andarist** [comment]
If you want to use emotion in non-React context then `emotion` package is the recommended way to do so (not the `@emotion/core`)

**Comment by snaptopixel** [comment]
I'll give that a try, thanks @Andarist!
