### ISSUE TITLE
create-emotion not applying styles correctly

### ISSUE THREAD

**Issue by gillesdemey** [emotion-js/emotion#1082]
- `emotion` ^10.0.4
- `react` ^16.7.0-alpha.2

Relevant code.

```javascript
/** @jsx jsx */
import ReactDOM from "react-dom";
import { jsx } from "@emotion/core";
import createEmotion from "create-emotion";

const { css } = createEmotion({
  key: "my-key"
});

const base = css`
  color: red;
`;

function App() {
  return (
    <div css={base}>
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

What you did:
Tried to combine the jsx pragma function with a custom `create-emotion` instance.

What happened:
Styles are not being properly applied when mixing the `css` function from the custom `create-emotion` instance and it does not export a `jsx` function to replace the default one from `@emotion/core`.

Reproduction:
https://codesandbox.io/s/p7krw1493q

Problem description:
I'm not quite sure if I'm either misunderstanding the documentation on how to use multiple Emotion instances in a single application with v10, or if there is a genuine bug :)

Suggested solution:
Maybe export a `jsx` function in `create-emotion` that functions properly and applies the styles, I'm not quite sure if that's the root cause.

**Comment by Andarist** [comment]
This is not yet documented clearly - but the recommended way to customize emotion@10 options when using React is through cache package, not create-emotion. Im not that proficient with new APIs yet so I cant give u more concrete example but this test ( https://github.com/emotion-js/emotion/blob/0ae6b39e2a080471d3c6c37db09f087f910a2378/packages/core/__tests__/custom-cache.js ) should show how to do it.

**Comment by Andarist** [comment]
The documentation for this feature is live for some time already - https://emotion.sh/docs/cache-provider
