### ISSUE TITLE
Typings are missing SerializedStyles

### ISSUE THREAD

**Issue by PierreAndreis** [emotion-js/emotion#1084]
- `emotion` version: 10.0.4
- `react` version: 16.6.3

Relevant code.

```javascript
/** @jsx jsx */
import { css, jsx } from "@emotion/core";

const base = css`
background-color: hotpink;
`;

export default () => (
  <div
    css={base}
  >
    This has a hotpink background.
  </div>
);
```

**What you did:**
Wrote a small react component using emotion 10, using the example in the docs

**What happened:**
Typescript complained about wrong typing
![image](https://user-images.githubusercontent.com/5843816/49628232-e01a5480-f997-11e8-8c7b-78792a6fa1ad.png)

**Reproduction**
https://github.com/hiiyar/vgprime-web/tree/emotion-10
`yarn install && yarn dev`

**Comment by Ailrun** [comment]
Thank you for posting an issue.
This is because one of your dependencies, namely, `react-spinners`, depends on old emotion(@9) typing.
With version number, exact error message would be
```
Type 'SerializedStyles'(@10) is not assignable to type 'Interpolation'(@9).
```
(other two lines are meaningless, since it just explain the way that TS tried to assign version 10 type to version 9 type.

**Comment by PierreAndreis** [comment]
@Ailrun thank you, makes sense.

**Comment by itzsaga** [comment]
So when we run into this would the correct course of action be to raise an issue on the library causing the error?

**Comment by Andarist** [comment]
In cases like this, you should raise an issue in the dependant project and ideally help them migrate to a new version of emotion. Closing this as the problem has been investigated and the advice has been given.
