### ISSUE TITLE
Is there a way to override styled component when using withComponent?

### ISSUE THREAD

**Issue by ruifortes** [emotion-js/emotion#1087]
Hi.
I have these components (parts of a larger widget) that I exposed as styled components
I want to be able to customize then without having to separate component and css.

If I wanted to change cursor type for example:

```javascript
const TweekedComp = BaseStyledComp.withComponent(props => {
  const {className} = props
   return (
     <li className={className} css={css({cursor: 'grab'})}></li>
  )
})
```

The styles defined in the original styled component take precedence.
I understand this is intentional exactly to be able to overwrite styles using className
Is there a way to do it in reverse?

TIA

**Comment by ruifortes** [comment]
humm...maybe I'm being a little dense but I still didn't manage to do it

Can I pass a more complex component to "as" or just simple html tags?

I created an example where there is a base already styled component "BaseStyledItem" that I want to be able to overwrite some styles but also change the component itself.

I know it is possible if I separare the css objects but I think it would be nice to just reuse the styled component.

Here's the sandbox test https://codesandbox.io/s/r4yx5057mp  
Am I missing something??

**Comment by Andarist** [comment]
`css` prop works with custom jsx pragma, so u have to do it like this - https://codesandbox.io/s/0qqq76n520

You can read more about `as` [here](https://emotion.sh/docs/styled#as-prop).

**Comment by ruifortes** [comment]
Ahh..ok! Missed this jsx pragma thing.
I agree it's a little quirky but carrying them separately is also not that elegant.
Thanks a lot!
