### ISSUE TITLE
Site (emotion.sh) styling bug

### ISSUE THREAD

**Issue by amitnovick** [emotion-js/emotion#1090]
Using Firefox 63.0.3
Font settings:
![emotion-website-styling-issue-2](https://user-images.githubusercontent.com/43674238/49698862-73d76500-fbd2-11e8-9ee6-992fc909330f.png)

On 200% zoom (also buggy on 200%+):
![emotion-website-styling-issue](https://user-images.githubusercontent.com/43674238/49698846-3ecb1280-fbd2-11e8-923d-29ed4a7608a0.png)

Suggestions:
- Tweak the styling configuration to allow for variable font sizes / zoom depths in the navigation bar
- Collapse navigation bar into hamburger-style drop-down menu in response to depletion of space.

**Comment by FezVrasta** [comment]
The website changed and this doesn't seem to be a bug anymore.
