### ISSUE TITLE
Spreading className prop results in [object Object]

### ISSUE THREAD

**Issue by ryanditjia** [emotion-js/emotion#1092]
- `emotion` version: 10.0.4
- `react` version: 16.7.0-alpha.2

```javascript
const linkCss = css`
  color: black;

  &.active-section {
    color: red;
  }
`

function setClass({ href, isPartiallyCurrent }) {
  if (isPartiallyCurrent && href !== '/') {
    return {
      className: `${linkCss} active-section`,
    }
  }

  return {
    className: linkCss,
  }
}

<Link getProps={setClass} />
```

I’m migrating from Emotion 9 to 10, on a Gatsby site. The above (simplified) code used to work:

```javascript
<a class="css-RANDOMHASH>

// or, when applicable
<a class="css-RANDOMHASH active-section">
```

After the migration, css-RANDOMHASH is replaced by [object Object]. Does anyone know a fix?

Further information:
This uses the [`getProps` API](https://reach.tech/router/api/Link) from @reach/router. [Source here](https://github.com/reach/router/blob/master/src/index.js#L385-L389).

**Comment by anton-kabysh** [comment]
Just button with a custom classes and emoticon renders to:
`<span class="[object Object]">Delete User</span>`

**Comment by Andarist** [comment]
@anton-kabysh from which package do you import `css`? If you want to pass `css` result to `className` prop you probably should use `emotion` package (not `@emotion/core`). However your `css` calls will be React-agnostic (no notion of context/theme etc) then.

**Comment by anton-kabysh** [comment]
`import { css } from '@emotion/core';`

**Comment by mnpenner** [comment]
```
import { css as cssClass } from 'emotion';
```

Doesn't exist in emotion 10. What's the proper way to do this now?

**Comment by FezVrasta** [comment]
`css` is exported by `emotion`, please double check your code.

https://unpkg.com/emotion@10.0.9/src/index.js

**Comment by TarVK** [comment]
> ```
> import { css as cssClass } from 'emotion';
> ```
> 
> Doesn't exist in emotion 10. What's the proper way to do this now?

https://emotion.sh/docs/class-names seems like this is the solution now if you want to obtain a class name
