### ISSUE TITLE
Suggested way to inject font family?

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#1093]
Hi, this is strictly a usage question that I think deserves an official answer.

`injectGlobal` has been deprecated, you can use `Global` now, but it is limited to the render phase.

If I have an `Icon` component (that I want to export so that my library consumers can use it) and I use `Global` to inject the font-face definition, I will end up with several `css-global` style elements, because the `Icon` component is used several times.

What if I want to inject it just once at component import/definition time?

**Comment by Andarist** [comment]
Can't you recommend to people using your Provider (which would use Global inside it) at the top of their application?

**Comment by FezVrasta** [comment]
Thanks for the reply, yes I could, but since the previous API allowed to do that I think it may be worth to reconsider the deprecation.

**Comment by Andarist** [comment]
You can still use `emotion` package in your library and call `injectGlobal` from there. `@emotion/core` is on purpose react-only package, everything is associated with components, contexified etc.

**Comment by FezVrasta** [comment]
I thought that was deprecated, thanks for the clarification!

**Comment by JackHowa** [comment]
Fantastic thanks @Andarist
