### ISSUE TITLE
css array not working for ':hover' styles

### ISSUE THREAD

**Issue by philholden** [emotion-js/emotion#1094]
- `emotion` 10.0.4:
- `react` 16.5.2:

**Relevant code:**

```javascript
<div css={{ ":hover": [{ color: "green" }] }} />
```
**What you did:**
Upgraded to 10.04 from beta. 

**What happened:**
Hover styles specified using array syntax did not appear when used with `css={}` but did work with `styled`.

```javascript
{  ":hover": [{ color: "green" }] }
```

**Reproduction:**

https://codesandbox.io/s/vjqyl3kly5

**Problem description:**

Arrays are often need for browser compatibility so needs to work for ":hover" etc

**Suggested solution:**

not sure but worked in beta

**Comment by Andarist** [comment]
I'm surprised there is a difference when handling this through styles and css, but either way I think the correct way of using array syntax is `[{ ":hover": { color: "green" } }]`, why would you like to wrap css value in an array? Most commonly arrays are used for composing rules.

**Comment by philholden** [comment]
I have a prop that allows you to reapply the same styles but nested under CSS selector with mapped props. It is an escape hatch for prototyping and makes it possible to add media queries, hover etc without exposing props for each of these things. 

```js
<Text
  color="error"
  selectorMappings={{
    ':hover': props => ({
      ...props,
      color: 'success'
    })
  }}
>
  Hover me
</Text>
```
