### ISSUE TITLE
Disable source maps with macros?

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#1096]
I can't seem to find in the documentation how to disable the sourcemaps when I use emotion macros.

I see the [source code](https://github.com/emotion-js/emotion/blob/master/packages/babel-plugin-emotion/src/macro.js#L9) reads a `emotionSourceMap` option but where do I define it?

Specifically, I'd like to disable them during tests

**Comment by mitchellhamilton** [comment]
Why do you want to disable them during tests?

**Comment by FezVrasta** [comment]
I want to snapshot test the result of a `css` call and right now it includes the inlined source map

**Comment by mitchellhamilton** [comment]
Why do you want to snapshot the result of a css call? Why can't you snapshot an element with styles?

**Comment by FezVrasta** [comment]
I have a utility that returns just css so I want to test just that 🤷‍♂️

**Comment by mitchellhamilton** [comment]
The recommended approach is to snapshot elements. What `css` returns is intended to be an internal data structure, it's also before prefixing and some keyframe things happen. Is there something wrong with rendering an element with the style?

**Comment by FezVrasta** [comment]
No nothing wrong, I just thought it would have been better to avoid to add some (apparently) unneeded logic to my tests. I'll use `styled` then, thanks.!
