### ISSUE TITLE
emotion macro returns undefined when used as selector

### ISSUE THREAD

**Issue by lifeiscontent** [emotion-js/emotion#1097]
when using the babel macro for `@emotion/styled/macro` the element returns an `undefined` selector it should either throw if it cannot be found or return the right selector.

e.g.

``` js
import styled from '@emotion/styled/macro';

const ListItem = styled.li();
const List = styled.ul({
    [ListItem]: {
        color: 'green'
    }
});
```

**Comment by mitchellhamilton** [comment]
Could you provide a reproduction? It's working in CodeSandbox, https://codesandbox.io/s/10240kz3pl

**Comment by lifeiscontent** [comment]
@mitchellhamilton I'm honestly baffled, I literally copy/pasted the code from my codebase into codesandbox and it works... any ideas on how to debug something like this? in the meantime I'll try to track down the issue on my end.

**Comment by lifeiscontent** [comment]
@mitchellhamilton okay, I tracked down the issue. it was because the component I was importing wasn't exported. maybe this should throw an error similar to how react does if you render `undefined` in a component tree and says 'maybe you forgot to export it?`

**Comment by Andarist** [comment]
@lifeiscontent I've implemented a warning for this in https://github.com/emotion-js/emotion/pull/1580  . Closing this right now as the PR will most likely be merged soon.
