### ISSUE TITLE
React-redux incompatibility after upgrade to 10.0.4

### ISSUE THREAD

**Issue by rylek90** [emotion-js/emotion#1099]
- `emotion` version: 10.0.4
- `react` version: 16.6.3

**What you did:**
I've upgraded our codebase following the [migration guide](https://emotion.sh/docs/migrating-to-emotion-10)
I don't know, perhaps I did something wrong in here but code seems right

**What happened:**
`react-redux` started to throw circular structure serialization exceptions

**Reproduction:**
https://codesandbox.io/s/q4nj22j8jq

**Suggested solution:**
No idea, really... might be my problem and everything I need is only direction in good way 🤔

**Comment by Andarist** [comment]
I've prepared a fix in react-redux - https://github.com/reduxjs/react-redux/pull/1122

**Comment by Andarist** [comment]
The react-redux PR got merged in, nothing to do more on emotion's side. You'll have to wait for their new release. In the meantime you can create a proxy component like this https://codesandbox.io/s/w02oj3xzq8
