### ISSUE TITLE
HOC TypeErrors after upgrade to 10.0.4

### ISSUE THREAD

**Issue by rylek90** [emotion-js/emotion#1100]
- `emotion` version: 10.0.4
- `react` version: 16.6.3

**Relevant code:**
See codepen

**What you did:**
Followed migration guide 🤷‍♂️ 

**What happened:**
High order components started to throw errors

**Reproduction:**
See this for a working code before upgrade:
https://codesandbox.io/s/koqplx1vvv

And after upgrade:
https://codesandbox.io/s/o7xk6l07yq

**Suggested solution:**
No idea, maybe I'm doing something wrong and need point to the right direction

**Comment by Andarist** [comment]
`styled` is a functional component wrapped in `forwardRef` in v10. Extending class components is discouraged by the React team and something really uncommon in the wild. Can't you rewrite your `withDoesntMatter` HOC to use other composition techniques?

**Comment by rylek90** [comment]
Yeah, probably I will. Thanks for answer!
