### ISSUE TITLE
Refactoring classList usage with Emotion 10

### ISSUE THREAD

**Issue by mherodev** [emotion-js/emotion#1101]
In Emotion 10, how do I refactor vanilla Emotion `css` usage with the new approach?

Is this pattern even possible, now?

- `emotion` version: 10

**Relevant code:**

```javascript
import { css } from 'emotion';

const myClass = css({ color: 'red' });
this.myRef.current.classList.add(myClass);
this.myRef.current.classList.remove(myClass);
```

Thanks in advance!

Best
Michael

**Comment by Andarist** [comment]
You can still use `emotion` package in v10, `css` from it just wont know about react's context - it will still be able to produce classnames though. For context-aware `css` you have to use `@emotion/core`  package.

**Comment by mherodev** [comment]
My thought was that I'd like to refactor `emotion` out of our app so we don't have to send vanilla emotion as well as the core package down to the client; that seemed redundant?

**Comment by tkh44** [comment]
Using the `emotion` and `@emotion/core` imports at the same time won't add that much to the bundle size because they share quite a bit of code (if using esm imports). 

https://github.com/emotion-js/emotion/blob/c65cd38b364e8554d310a85b9b500d5bb528187e/packages/create-emotion/src/index.js#L2-L9

**Comment by FezVrasta** [comment]
The proper way to generate class names (rather than Emotion CSS objects) is to use `import { ClassName } from '@emotion/core'`.

I'm closing this issue since it has several answers already and it's inactive.
