### ISSUE TITLE
psuedo elements not able to be targeted

### ISSUE THREAD

**Issue by tylerthehaas** [emotion-js/emotion#1104]
targeting psuedo selectors isnt supported when using object style.

- `emotion` version: 10.0.2
- `react` version: 16.7.0-alpha.2

**Relevant code:**

This works:

```javascript
const Branding = styled(Container)`
  display: flex;
  flexdirection: row;
  alignitems: center;
  height: 100%;
  &::before {
    content: ' ';
    display: table;
  }
`
```
But not this:
```javascript
const Branding = styled(Container)({
  display: 'flex',
  flexdirection: 'row',
  alignitems: 'center',
  height: '100%',
  '&::before': {
    content: ' ',
    display: 'table',
  }
})
```

**What you did:**

**What happened:**

**Reproduction:**

**Problem description:**

**Suggested solution:**

**Comment by abettadapur** [comment]
@tylerthehaas how did you resolve this, I am running into the same problem

**Comment by tylerthehaas** [comment]
I wrote about this in my dev-journal [here](https://github.com/tylerthehaas/dev-journal/blob/master/2018/December.md#december-12th-2018).

**Comment by peterwiebe** [comment]
😞 just ran into this problem myself. The selector is generated and inserted in the head but for some reason the browser doesn't seem to pick it up.

Guess no more object styling for me.

**Comment by abettadapur** [comment]
@peterwiebe try content:' "" "
