### ISSUE TITLE
@emotion/babel-preset-css-prop and babel-plugin-transform-react-jsx behave differently

### ISSUE THREAD

**Issue by damusnet** [emotion-js/emotion#1111]
- `emotion` version: `10.0.5`
- `react` version: `16.7.0-alpha.2`

**Relevant code:**

```javascript
import React from 'react';
import { css } from '@emotion/core';

const container = css({ display: 'flex' });

const content = { display: 'flex' };

const MyComponent = ({ ... }) => (
  <div css={container}>
    <div css={content}>
      ...
    </div>
  </div>
);
```

**What you did:**
- Swaped `babel-plugin-transform-react-jsx` for `@emotion/babel-preset-css-prop`

**What happened:**

- label becomes duplicate when using `const aStyle = css({ ... })` (bad)
- label receives component name when using `const aStyle = { ... }` (good)

**Reproduction:**

*Before:*

```
// .babelrc
{
  "presets": ["next/babel",
  "plugins": [["emotion"], ["transform-react-jsx", { "pragma": "Emotion.jsx" }]]
}
```

![screen shot 2018-12-14 at 4 37 32 pm](https://user-images.githubusercontent.com/433409/50036595-d2c82000-ffbe-11e8-9b1f-8661923190e4.png)

*After:*

```
// .babelrc
{
  "presets": ["next/babel", "@emotion/babel-preset-css-prop"],
  "plugins": [["emotion"]]
}
```

![screen shot 2018-12-14 at 4 38 53 pm](https://user-images.githubusercontent.com/433409/50036600-de1b4b80-ffbe-11e8-97cb-b91aba64d1ef.png)

**Problem description:**

- looking at the first `<div css={container} />` that uses `const container = css({ ... })` ; before the change in babel preset, the label reads `css-[hash]-[local]` ; after the change, it reads `css-[hash]-[local]-[local]`
- looking at the `<div css={content} />` that uses an object directly `const content = { ... }` ; before the change the label reads `css-[hash]` ; after the change, it reads `css-[hash]-[ComponentName]`

**Suggested solution:**

- Ideally, regardless of babel configuration, all labels would read `css-[hash]-[ComponentName](-[local])?`

I tried changing the label through babel `labelFormat` option, but couldn't quite get it where I'd like it to be. The duplicate `[local]-[local]` is what makes me think there might be a glitch somewhere.

**Comment by tkh44** [comment]
The emotion babel plugin is included with the preset. If you remove the `emotion` plugin for your second example it should work as expected.

**Comment by tkh44** [comment]
I updated the docs to help devs avoid this in the future
https://github.com/emotion-js/emotion/commit/07eafe5b90af10910460832f9c2f016e040f90d0#diff-75a4f92e69fdc700846516f08b9ca129

**Comment by damusnet** [comment]
This makes sense, and works perfectly. Thanks for helping me out and updating the docs!
