### ISSUE TITLE
Accessibility of documentation

### ISSUE THREAD

**Issue by calumryan** [emotion-js/emotion#1115]
**Problem description:**
The documentation in general is hard to read for users with many different types of visual impairment. As an example please refer to this contrast ratio tool https://contrast-ratio.com/#%23fb84bf-on-white

**Suggested solution:**
Change pink text color #fb84bf to something like #000 (or another compliant contrast) when the page/section background is white/light grey.

**Comment by Andarist** [comment]
The hotpink text in the docs was a bug which I believe was fixed.

We always appreciate any feedback and we care about accessibility, so if you notice anything off in the future - please raise a new issue.
