### ISSUE TITLE
css prop returns [object, object]

### ISSUE THREAD

**Issue by harmeetjaipur** [emotion-js/emotion#1122]
- `emotion` version:
`"@emotion/core": "^10.0.5", 
"@emotion/styled": "^10.0.5",`

- `react` version: 16.6.3

**Relevant code:**

```javascript

const app = css({
	'.ant-btn-primary': {
		background: colors.highlight,
	},
});

<div css={app}>...</div>


```

**package.json**

`{
	"name": "app",
	"version": "0.1.0",
	"private": true,
	"dependencies": {
		"@emotion/core": "^10.0.5",
		"@emotion/styled": "^10.0.5",
		"antd": "^3.11.2",
		"jwt-decode": "^2.2.0",
		"react": "^16.6.3",
		"react-dom": "^16.6.3",
		"react-router-dom": "^4.3.1",
		"react-scripts": "2.1.1"
	},
	"scripts": {
		"start": "react-scripts start",
		"build": "react-scripts build",
		"test": "react-scripts test",
		"eject": "react-scripts eject"
	},
	"eslintConfig": {
		"extends": "react-app"
	},
	"browserslist": [
		">0.2%",
		"not dead",
		"not ie <= 11",
		"not op_mini all"
	],
	"devDependencies": {
		"react-localize-redux": "^3.5.1"
	}
}`

**What you did:**

I am trying to upgrade from v9 to 10 and all the class imports have stopped working.

**What happened:**

This is the output for all classes: `<div css="[object Object]">...</div>`

The image below shows you the output for `css`. `styled` components work as they should.

 <img src="https://i.ibb.co/2ZNMr23/Selection-043.png" alt="Selection-043" border="0"> 

I am not sure what needs to happen for all the classes to work and not emotion return an array of objects.

**Comment by sgilligan** [comment]
@harmeetjaipur did you find the answer to this? Finding the same problem myself.

**Comment by harmeetjaipur** [comment]
> @harmeetjaipur did you find the answer to this? Finding the same problem myself.

 Adding `/** @jsx jsx */ import { jsx } from '@emotion/core'
` at top of the component files fixed it for me.

**Comment by fsultani-aspiration** [comment]
That solution worked for me, too.  So strange!

**Comment by serayuzgur** [comment]
@harmeetjaipur Do you have any idea how to fix it with typescript?

**Comment by tbaustin** [comment]
for those of you getting jsx undefined add `jsx` to your import.

`/** @jsx jsx */ import { jsx, css } from "@emotion/core"`

Fixed it for me

**Comment by keguigong** [comment]
same problem, lol, haven't found any answer.

**Comment by efleurine** [comment]
What is I just want the string className to pass to a component. How would I do that?

**Comment by seanWLawrence** [comment]
Was stuck on this too, and realized that I missed this in the [Getting started docs](https://emotion.sh/docs/css-prop#get-started)

Instructions for the installing the [recommended babel plugin](https://emotion.sh/docs/@emotion/babel-preset-css-prop)

Basic steps to fix:
- `npm i @emotion/babel-preset-css-prop
- Add `'@emotion/babel-preset-css-prop` to your Babel config under `presets`

Or if you don't want to (or can't easily) use the Babel preset, you can add the `/** @jsx jsx */` comment at the top of any file that uses the `css` function. 

Hope this helps!

**Comment by shahzaibkhalid** [comment]
Same setup of `@emotion/babel-preset-css-prop` is working fine for a JavaScript-React project but not for a TypeScript-React project.

**Comment by strass** [comment]
+1 - is there any way to not have to use pragma in a typescript project?

**Comment by worc** [comment]
the `/** @jsx jsx */ doesn't seem to work in `@emotion/core@^10.0.10`, so...? what now? does emotion just not work in jsx?

**Comment by simajzenman** [comment]
Any news about this?

**Comment by Andarist** [comment]
@simajzenman it most likely is an issue with your configuration. If you share a repro case I could take a look

**Comment by simajzenman** [comment]
@Andarist you were right and I fixed it, thanks a lot for your reply

**Comment by worc** [comment]
> the `/** @jsx jsx */ doesn't seem to work in `@emotion/core@^10.0.10`, so...? what now? does emotion just not work in jsx?

^that was a misspelling on my part. the "comment" is actually significant code and needs to be exactly `/* @jsx jsx */` with a single star after the first slash

also... significant comments 🤮

**Comment by DominicTobias-b1** [comment]
This doesn't work when the css prop is in an NPM module (storybook of components). Works fine running them in isolation, or css prop directly used in the CRA app, but css props in the NPM module become [Object object]. Tried with both v10 and v11, with preset (10) or plugin (11), with jsx pragma (10) or jsxImportSource (11) 🤷‍♂️

**Comment by Andarist** [comment]
I can't say why exactly it has not been working for you - but it was purely a configuration/usage issue. There is no difference between a file being in your app directory and in your node_modules.

**Comment by fatemehqasemkhani** [comment]
Has someone found a solution for cra typescript? 
/** @jsx jsx */ import { jsx } from '@emotion/core' not works for me

**Comment by ALFmachine** [comment]
For anyone still running into this here are some resolutions:

### emotion docs
- [css prop babel setup](https://emotion.sh/docs/css-prop#babel-preset)
- [babel css prop](https://emotion.sh/docs/@emotion/babel-preset-css-prop)

### my typescript resolution
- added type reference in `types/@emotion-types/index.d.ts`
```typescript
/// <reference types="@emotion/react/types/css-prop" />
```
- added custom type to tsconfig
```json
{
  ...
  "compilerOptions": {
    ...
    "types": ["node", "@emotion-types"]
  }
  ...
}
```
- updated `.babelrc` as per the docs (in my base using nrwl/nx presets
```json
{
  "presets": [
    [
      "@nrwl/react/babel",
      {
        "runtime": "automatic",
        "useBuiltIns": "usage",
        "importSource": "@emotion/react"
      }
    ]
  ],
  "plugins": ["@emotion/babel-plugin"]
}
```
