### ISSUE TITLE
No plugin for tslint in the react-emotion 10

### ISSUE THREAD

**Issue by Werter12** [emotion-js/emotion#1124]
In the process of migration to react-emotion 10 I found out that there is only `eslint-plugin-emotion`. I use `tslint ` in the project that's why I cant use that plugin. The development experience without this plugin is quite bad. Because things related to new `react-emotion` highlighted poorly and a lot of mistakes raising up

**Comment by Andarist** [comment]
A port to tslint shouldnt be that hard - i doubt we have time to do it ourselves though. Maybe you could consider creating it on ur own (either as PR to our repo or as separate project entirely)?

**Comment by Andarist** [comment]
According to TS roadmap TSLing is being kinda deprecated in favour of ESLint - I doubt anyone would want to focus on making a plugin for TSLint right now.
