### ISSUE TITLE
type error on @emotion/core#context.js

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#1125]
Currently [this line](https://github.com/emotion-js/emotion/blob/master/packages/core/src/context.js#L7) throws an error on Flow 0.89.0

```
Cannot call React.createContext with isBrowser ? createCache() : null bound to defaultValue because null [1] is
incompatible with EmotionCache [2].

      4│ import createCache from '@emotion/cache'
      5│ import { isBrowser } from './utils'
      6│
 [1]  7│ let EmotionCacheContext = React.createContext(isBrowser ? createCache() : null)
      8│
      9│ export let ThemeContext = React.createContext<Object>({})
 [2] 10│ export let CacheProvider: React.ComponentType<{ value: EmotionCache }> =
```

**Comment by daniellizik** [comment]
Hi, thanks for looking at this a while ago. Still seeing this with 
```
@emotion/core: "10.0.9"
```

```
Checking flow
node_modules/@emotion/core/src/context.js Line 7 Column 32: Cannot get `React.Context` because property `Context` is missing in module `react` [1].

        let EmotionCacheContext: React.Context<EmotionCache | null> = React.createContext(
```

**Comment by FezVrasta** [comment]
@daniellizik are you sure you are on an updated Flow version? It seems like you are not.

**Comment by daniellizik** [comment]
@FezVrasta thanks for the help! It's actually easier for me to use 
```
@emotion/core: 10.0.5
@emotion/styled: 10.0.5
```
than to update my flow (company private monorepo package)

downgrading to 10.0.5 "fixed" my flow lint

**Comment by Andarist** [comment]
@FezVrasta is this still an issue?

**Comment by FezVrasta** [comment]
I'm not getting that error anymore on master.

Anyways, for any node_modules errors, we can now add the following to the `.flowconfig` file:

```
[declarations]
<PROJECT_ROOT>/node_modules/*
```

So that the types are used, but the errors are ignored.
