### ISSUE TITLE
v10 or @emotion/core doesn't run without babel-plugin-transform-inline-environment-variables

### ISSUE THREAD

**Issue by raveenakothapally** [emotion-js/emotion#1132]
- `emotion` version: "@emotion/core": "^10.0.5"
- `react` version: ^16.7.0-alpha.2

**Relevant code:**

```javascript
import React from "react";

const Login = () => {
  return (
    <section>
      <span
        css={{
          color: "blue"
        }}
      >
        Login
      </span>
    </section>
  );
};

export default Login;

```

**What you did:**
I followed the documentation and installed emotion and the css prop babel plugin. I then configured `.babelrc` also as mentioned in documentation. FYI., I am using `parcel.js`.

1. npm i --save @emotion/core
2. npm i -D @emotion/babel-preset-css-prop
3. .babelrc:
```json
"presets": [
  [
    "@emotion/babel-preset-css-prop",
    {
      "autoLabel": true,
      "labelFormat": "[local]",
      "useBuiltIns": false,
      "throwIfNamespace": true,
      "sourceMap": false
    }
  ]
]
```

**What happened:**
I get the following error in browser console when I navigate to the `login` page:
```process is not defined```

**Reproduction:**
What you did section pretty much captures reproduction steps.

**Problem description:**
Looks like v10 needs an explicit installation of `babel-plugin-transform-inline-environment-variables` which was not needed in previous versions.

**Suggested solution:**
Bundle `babel-plugin-transform-inline-environment-variables`  in `babel-plugin-emotion`

**Comment by Andarist** [comment]
It's weird that you have to configure it manually with parcel - it should be done automatically https://github.com/parcel-bundler/parcel/blob/0fac29efd7a60cd982eb26ba026ac4b8ad715e91/packages/core/parcel-bundler/src/visitors/env.js

**Comment by mitchellhamilton** [comment]
Im pretty sure I tested this sometime and I think that parcel is replacing process.env.NODE_ENV before babel runs so when we insert process.env.NODE_ENV for source maps parcel never replaces it.

**Comment by raveenakothapally** [comment]
@Andarist @mitchellhamilton,
I don't know if it is a pure `parcel.js` issue as it has no issues replacing such environment variables for other libraries like `react`. It only complains for `emotion`.

**Comment by karol-majewski** [comment]
For anyone interested: adding `"transform-inline-environment-variables"` in the beginning of the list of plugins in `.babelrc` takes care of the `process is not defined` error.

However, the `@emotion/babel-preset-css-prop` preset is still not applying the pragma for me.

**Comment by louiscenter** [comment]
@karol-majewski I had the same issue too. The general feeling I got was that `babel-preset-css-prop` doesn't play ball with `parcel` right now, so I looked into the preset's source code and adapted it to a fresh `.babelrc` which I'm now using instead.

```
{
  "plugins": [
    [
      "transform-inline-environment-variables"
    ],
    [
      "babel-plugin-jsx-pragmatic",
      {"export": "jsx", "module": "@emotion/core", "import": "___EmotionJSX"}
    ],
    [
      "@babel/plugin-transform-react-jsx",
      {"pragma": "___EmotionJSX", "pragmaFrag": "React.Fragment"}
    ],
    [
      "emotion"
    ]
  ]
}
```

**Comment by karol-majewski** [comment]
Brilliant! Thank you, @louiscenter. Your solution worked for me once I set `"jsx": "preserve"` in my `tsconfig.json`.

If anyone is struggling with the error reported by TypeScript:

```
Property 'css' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
```

it will be gone as soon as you import anything from `@emotion/core`. The act of importing its type definitions will add `css` to the `DOMAttributes` interface. If you don't need to import anything from `@emotion/core`, just add `"@emotion/core`" to `compilerOptions.types` in your `tsconfig.json`.

**Comment by ncklug** [comment]
@louiscenter @karol-majewski I ran into the same thing and filed this bug to Parcel, if you want something to track: https://github.com/parcel-bundler/parcel/issues/2470

**Comment by karol-majewski** [comment]
@ncklug Thank you. 🙇

**Comment by alflennik** [comment]
There is a PR on the parcel repo that will resolve this issue (not merged yet) #2695

**Comment by ford04** [comment]
Solution from @louiscenter seems to work for me, with illustration from [this example repository](https://github.com/lee-reinhardt/parcel-ts-emotion).
Unfortunately, there is some missing puzzle piece:  If I define a custom styled theme to enable strong typing for my app theme like shown [here](https://emotion.sh/docs/typescript#define-a-theme), the `label` is not appended to the `styled` component anymore 😢. Is there a workaround too?

**Comment by Andarist** [comment]
This got fixed in Parcel with https://github.com/parcel-bundler/parcel/pull/3334 - but I believe it has not yet been published (it's part of the upcoming Parcel 2). Either way - going to close this as the issue was in an external tool, rather in emotion itself and also workarounds have been found for this in the meantime.
