### ISSUE TITLE
[@emotion/core] cache `createElement`, and make `jsx` to use as polyfill

### ISSUE THREAD

**Issue by morlay** [emotion-js/emotion#1135]
- `emotion` version: 10.x
- `react` version: 16.7

**Relevant code:**

```javascript
import React from "react"
import { jsx } from "@emotion/core"

React.createElement = jsx
```

**What you did:**

If we use emotion for full project, we could hack createElement when initializing application, use code above. 

**What happened:**
But now, `React.createElement` is used directly in the `jsx` function, it will cause a loop call issue.

**Suggested solution:**

we could change a little here

https://github.com/emotion-js/emotion/blob/master/packages/core/src/jsx.js#L107

```javascript
const createElement = React.createElement
export const jsx: typeof React.createElement = function(
  type: React.ElementType,
  props: Object
) {
  let args = arguments

  if (props == null || props.css == null) {
    // $FlowFixMe
    return createElement.apply(undefined, args)
  }
  // ...
}
```

**Comment by tkh44** [comment]
While this is technically working, setting the `jsx` pragma is effectively doing the same thing and in a much safer way imo.

**Comment by morlay** [comment]
@tkh44 
Yes. using the `jsx` is safe but cause other costs: 

* need to import `@emotion/core` in each file. 
* additional configuration in `babel` or `typescript`
  * For TypeScript user, when `jsxFactory` changed, `Fragment` could not be used by shout version  `<></>`

I just hope there is someway way to use `emotion` directly and easier 😄

**Comment by tkh44** [comment]
> I just hope there is someway way to use emotion directly and easier 😄

You don't have to use the css prop.

```javascript
import { css } from 'emotion'

const blueClassName = css({ color: 'blue' })

const Button = (props) => <button className={} />
```
