### ISSUE TITLE
[Question] Is it possible to use macro version to publish custom npm ui package?

### ISSUE THREAD

**Issue by rockmandash** [emotion-js/emotion#1138]
Hello, thank you for this wonderful tool!
I've been a huge fan of emotion almost a year.
Lately, I was wondering if I can publish my own UI package using ```'@emotion/styled/macro'```, and make ```@emotion/styled``` as peer dependencies.
I know that create-react-app v2 will process node_modules when developing, but unfortunalty, it seems can't process packages who contain macro.
It seems that my only option is to use ```import { ClassNames } from '@emotion/core';```.
I wonder that how can I use macro as npm packages.
Thank you for listening my question.

**Comment by Andarist** [comment]
If you are making an npm package it would be better to just publish compiled files (so macros already processed) - otherwise you'd impose configuration burden on your consumers.

**Comment by rockmandash** [comment]
@Andarist Thank you! Now I understand.
