### ISSUE TITLE
recover from exception for server side rendering

### ISSUE THREAD

**Issue by wangzuo** [emotion-js/emotion#1141]
Here is a simple test case for the problem:
``` javascript
const Test = ({ x }) => {
  if (x === 1) {
    throw new Error('test');
  }
  return <p>{x}</p>;
};

const App = ({ x }) => (
  <Row>
    <Test x={x} />
  </Row>
);

try {
  const html = renderToString(<App x={2} />); // contains <style>
  renderToString(<App x={1} />); // throw error
} catch (e) {
  const html = renderToString(<App x={2} />); // no <style> tag
}
```

For example, reach-router handles redirect by catching a redirect error on server side. [link](https://reach.tech/router/server-rendering). It seems once the rendering fails on server side, later rendering will output no inline `<style>` tag due to the emotion cache. Is there any way to get around this problem?

**Comment by wangzuo** [comment]
Right now recreating cache for each request fixes the issue

``` javascript
import { CacheProvider } from '@emotion/core';
import createCache from '@emotion/cache';

<CacheProvider value={createCache()}>
  <App />
</CacheProvider>
```

**Comment by mitchellhamilton** [comment]
This is because of a bug in React. https://github.com/facebook/react/issues/14502

**Comment by mitchellhamilton** [comment]
Nope, that’ll work fine.

**Comment by wangzuo** [comment]
Thank you, really like the new emotion 10!
