### ISSUE TITLE
[@emotion/babel-preset-css-prop] `withComponent` of custom Class will be added wrong arguments

### ISSUE THREAD

**Issue by morlay** [emotion-js/emotion#1153]
- `emotion` version: 10.0.5
- `react` version: 16.7

**Relevant code:**

```javascript
import * as React from 'react'

class Factory {
  static create() {
    return new Factory()
  }

  withComponent(Comp, v) {
    return Comp
  }
}

export const Test = props => {
  const t = Factory.create().withComponent("test", v)

  return (
    <div>
      {t}
    </div>
  )
}
```
**What you did:**

We have custom class with method `withComponent`

**What happened:**

[![Edit 643nx857n](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/643nx857n?expanddevtools=1&previewwindow=tests)

the transformed codes with wrong argument

```javascript
import * as React from 'react';

class Factory {
  static create() {
    return new Factory();
  }

  withComponent(Comp, v) {
    return Comp;
  }

}

export const Test = props => {
  const t = Factory.create().withComponent("test", /* wrong argument here*/ _extends({}, {
    target: "e5i1odf0",
    label: "t"
  }, v));
  return ___EmotionJSX("div", null, t);
};
```

**Reproduction:**

**Problem description:**

**Suggested solution:**
add more limit for `withComponent`

if it is not easy to fix.
may notice this conflict in document.

**Comment by Andarist** [comment]
Unfortunately it's too hard to fix it for all cases with Babel (it operates only on a single files, so there is no easy way to know what imported things are - not mentioning that it's not always easy to tell what a thing created in the very same file is).

I would advise you to just name this method differently.

**Comment by morlay** [comment]
@Andarist 
Thanks. I already renamed my method 😄 

Reporting this issue is for developers who have same problem.

Btw, This behavior may be in document.

**Comment by Andarist** [comment]
Closing as this was an edge case and we've explained why this happens. Note that when using babel macros instead of `@emotion/babel-preset-css-prop` this wouldn't happen.
