### ISSUE TITLE
[jest-emotion] flow error on match[1]

### ISSUE THREAD

**Issue by kievu** [emotion-js/emotion#1154]
- `emotion` version: 10.0.5
- `react` version: 16.6.3

**Relevant code:**
https://github.com/emotion-js/emotion/blob/704ea1d3ece84dee6e3acfdaebb73706e51f30c5/packages/jest-emotion/src/utils.js#L107

**What you did:**
Using `jest-emotion` as a dependency.

**Problem description:**
Flow prompt error 
```
Cannot get `match[1]` because an indexer property is missing in null or undefined [1]. (utils.js:108:24)flow
```
So `if (match !== null)` checks only for `null`, but it can also be `undefined`.

**Suggested solution:**
Since [String.match()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) is optional and can return `null` or `undefined`, [line 107](https://github.com/emotion-js/emotion/blob/704ea1d3ece84dee6e3acfdaebb73706e51f30c5/packages/jest-emotion/src/utils.js#L107) 
Two solutions come to mind:
1) 
`if (match !== null && match !== undefined)`
2)
`if (!!match)`

Or what you guys think?

**Comment by FezVrasta** [comment]
The String.match() spec says it can only return an array, or `null`. `undefined` is not an option.
This is reflected by the Flow definitions (https://github.com/facebook/flow/blob/master/lib/core.js#L334).

If you experience other issues like this:

Flow 0.110.0 finally fixed the `[declarations]` option, so now you can tell Flow to ignore errors inside your dependencies, but still take advantage of their types.

```
[declarations]
<PROJECT_ROOT>/node_modules/.*
```

This should allow you to use any library with internal errors without worrying about it.
