### ISSUE TITLE
[@emotion/native] Use StyleSheet.create to create styles for improved performance

### ISSUE THREAD

**Issue by hammadj** [emotion-js/emotion#1155]
**Problem description:**
Was digging into the react-native implementation when I noticed that the styles are just passed around as plain JS objects instead of number references created with `StyleSheet.create` (https://facebook.github.io/react-native/docs/stylesheet#flatten). This has serious performance implications, and isn't ideal for a decently sized RN app.

**Suggested solution:**
Implement creating styles with StyleSheet.create, like [this library](https://github.com/robinpowered/glamorous-native) does here: https://github.com/robinpowered/glamorous-native/blob/01112810f99b1e783681ccbc09948ccb18f44ad7/src/create-glamorous.js#L16

**Comment by mitchellhamilton** [comment]
[This isn't true. StyleSheet.create returns the original object in newer versions of react-native because the optimisations that were mentioned were never implemented.](https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/StyleSheet.js#L361-L373)
