### ISSUE TITLE
Define stylis plugins through ThemeProvider (or similar)?

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#1158]
Would it be possible to add a way to define stylis plugins through some context API rather than the `create-emotion` package?

I find the need to use a custom stylis plugin for some accessibility features and I don't feel confident in asking my users to use a custom Emotion package just for my library needs.

Ideally it would look like this:

```jsx
import { ConfigProvider } from 'emotion';

<ConfigProvider stylisPlugins={...} prefix="..." key="..." container="..." etc>
  <StyledComponentAffectedByConfigHere />
</ConfigProvider>
```

would this be something possible?

**Comment by Andarist** [comment]
Look for CacheProvider - its already implemented :)

**Comment by FezVrasta** [comment]
I'm sorry I can't find it in the docs, any hint please? 🙏

**Comment by tkh44** [comment]
It is undocumented at the moment.

```javascript
import React from 'react'
import { CacheProvider } from '@emotion/core'
import createCache from '@emotion/cache'

const myCache = createCache({
  key: 'my-prefix-key',
  // only prefix the following style properties
  stylisPlugins: [/* Your plugins here */],
  prefix: key => {
    switch (key) {
      case 'appearance':
      case 'user-select':
      case ':placeholder':
        return true
      default:
        return false
    }
  }
})

export default function EmotionProvider(props) {
  return <CacheProvider value={gremlinCache} {...props} />
}
```

After this wrap your App at whatever level you need (top-level or only a portion)

Here's the source if you are curious.

**Comment by ivan-kleshnin** [comment]
Can we use the above to resolve values e.g `justify-content: end` to `justify-content: flex-end` (for mobile devices)?

**Comment by srmagura** [comment]
You can probably write a custom Stylis plugin for that if there is not one already. Though, likely more trouble than it's worth.

**Comment by ivan-kleshnin** [comment]
Thanks, Sam! There're no docs on how to write Stylis plugins but I've managed to write a working version following existing examples. For anyone interested: https://gist.github.com/ivan-kleshnin/3a04dadfd606db1200c073cee2a8fcd3
