### ISSUE TITLE
[RFC/improvement] CSS Module-like syntax for React Native

### ISSUE THREAD

**Issue by njradford** [emotion-js/emotion#1164]
When using emotion for React native styling, the `css` function is a much cleaner approach IMO than using a new styled component for every nested element. It seems like it would be useful to allow support for CSS module-style name-spacing within template block stylesheets. That way, a single stylesheet could contain all relevant styles, which could be accessed from the view using the classname keys.

An example 
```tsx
const moduleStyles = css`
	.outer-container {
		background-color: pink;
	}	
	
	.inner-text {
		background-color: teal;
	}
`;

export default class App extends React.Component {
	render() {
		return (
			<View style={moduleStyles.outerContainer}>
				<Text style={moduleStyles.innerText}>
					Inner Text
				</Text>
			</View>
		);
	}
}
```

Any suggestions on how to achieve this within the emotion API? Or pointers if I'm missing something obvious.

**Comment by TrySound** [comment]
@njradford I think you already may use safer (statically analyzable) way
```js
const outerContainer = css`
  background-color: pink;
`

const innerText = css`
  background-color: teal;
`

export default class App extends React.Component {
	render() {
		return (
			<View style={outerContainer}>
				<Text style={innerText}>
					Inner Text
				</Text>
			</View>
		);
	}
}
```

**Comment by FezVrasta** [comment]
I'm closing this since OP never replied and the issue is inactive.
