### ISSUE TITLE
No vendor prefixes for available property

### ISSUE THREAD

**Issue by JohannesKlauss** [emotion-js/emotion#1172]
- `emotion` version: 10.0.5
- `react` version: 16.7

**Relevant code:**

```javascript
const style = css({
  marginLeft: '10px',
  height: 'available',
});

// .... rendering
<div css={style}>.....</div>
```

**What you did:**
I want to use the webkit and moz vendors for the `available` value [like here](https://stackoverflow.com/questions/26275982/putting-moz-available-and-webkit-fill-available-in-one-width). I expected emotion.js to polyfill it like so:

```
height: -webkit-fill-available;
height: -moz-available;
height: available;
```

**What happened:**
emotion.js does not polyfill, but only prints `height: available`

**Reproduction:**
https://codesandbox.io/s/qzmvo4oyz9
I added the height property to the Wrapper component.

**Problem description:**

**Suggested solution:**
I guess that is not a hard bug to fix, but I don't know where the corresponding code is located at.

**Comment by tkh44** [comment]
This would be a stylis issue. https://github.com/thysultan/stylis.js/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

If you are impatient you could write your own stylis plugin.

As an aside, thats a pretty obscure css value that might not be as widely supported as using something like css grid to achieve a similar effect.
