### ISSUE TITLE
Custom components, wrappers and properties

### ISSUE THREAD

**Issue by akullpp** [emotion-js/emotion#1174]
I want to build a wrapper for components to be wrapped in a styled component in order to avoid duplication. Unfortunately, this doesn't seem to work with Typescript, e.g.

I have a decorator which takes a component and checks on a boolean property in order to set the color

```
const Disable = (component: any) => styled(component, {
  shouldForwardProp: prop => prop !== 'disabled',
})<{
  disabled: boolean
}>`
  color: ${({ disabled }) => {
    if (disabled) {
      return 'lightgrey'
    }
  }};
`
```

So I only need to define this decorator once and can pass it an arbitrary component, e.g.:

```
const PlayControl = Disable(PlayArrow)
const PauseControl = Disable(Pause)
const ResetControl = Disable(Replay)
```

Usage:

```
<PlayControl onClick={this.start} disabled={!startable} />
```

This whole thing is as verbose as it is and to make it work I need to declare every property, e.g.

```
<{
  onClick: Function
  disabled: boolean
}>
```

Now if any other component has another property my abstraction won't work anymore. Ideas?

**Comment by vadistic** [comment]
@akullpp imho  the biggest issue is that you want to type HOCs and they are always a bit of a pain with typescript, but I've got you fam :smile: Personally, I would avoid decorators for styling altogether and use dynamic styles approach. 

CODE SANDBOX: https://codesandbox.io/s/386l8yxy0q

**What you want:**
```tsx
// always define some interfaces for clarity/reusability
interface DisableableProps {
  disabled?: boolean
}

// technically it's disableable not disabled :)
const Disableable = (component: React.ComponentType) => styled(component, {
  shouldForwardProp: prop => prop !== "disabled",
})<DisableableProps>`
  ${({ disabled }) =>
    disabled &&
    css`
      color: lightgrey;
    `}
`

// ... more styles

// Typing HOCs/decorators is pain imo but works :)
const ComposedHeading = compose<{}, DisableableProps & SizeableProps>(
  Disableable,
  Sizeable
)(Heading)

```

**What you really want:**

```tsx
const disableStyles = ({ disabled }: DisableableProps) =>
  disabled &&
  css`
    color: lightgrey;
  `

const CoolHeading = styled(Heading)<SizeableProps & DisableableProps>`
  ${sizeStyles};
  ${disableStyles};
`

```

I hope it helps and solves this issue :)

**Comment by Andarist** [comment]
Thank you @vadistic for answering this! Personally I find this approach cleaner than what OP was attempting to do.
