### ISSUE TITLE
Problems surrounding SSR injection of <style> and unreliability of :first-child selectors

### ISSUE THREAD

**Issue by kylegach** [emotion-js/emotion#1178]
**Problem description:**

In emotion v10+, a new warning is thrown if you use `:first-child`, `:nth-child`, or `:nth-last-child` selectors in a styled component or css prop value. This is because, when using SSR, the `style` element is injected immediately above (prepended) the associated component. ([More details](https://github.com/emotion-js/emotion/issues/898).)

There are a number of problems with this approach:

> _Note: I made a [test case demo](https://codepen.io/anon/pen/BvMjeQ) to illustrate which selectors are unreliable._

1. In [our codebase](https://github.com/mineral-ui/mineral-ui/) and matching years of experience for myself and peers, the "first" selectors are used much more often than the "last". Making these selectors unreliable is a big blow to those expecting standard CSS features to work.
1. The suggested workaround of changing, e.g. `:first-child` to `:first-of-type`, only works if _all_ sibling elements are of the same type. This is probably fairly common for components like lists, grids, etc... But it's far from a guaranteed solution. It could also discourage the use of semantic markup by driving devs to "just use divs" for everything, since it's a simpler "fix".
1. The [list of unsafe selectors](https://github.com/emotion-js/emotion/blob/master/packages/cache/src/index.js#L208) is incorrect.
    - The adjacent sibling pattern, `* + [anything]`, is unreliable, but not listed.
      - This [type of selector](https://alistapart.com/article/axiomatic-css-and-lobotomized-owls) may seem somewhat obscure, but it can be rather useful.
    - `:only-child` is unreliable, but not listed.
    - `:nth-last-child` is still reliable when prepending the `style` element and should not be listed.
1. Consumers not interested in SSR should be able to turn off the warning (#1105)

**Suggested solution:**

Let's tackle each problem, in turn:

1. "First" vs. "last" selectors (or prepending vs. appending the `style` element)

    If emotion injected the `style` element _after_ (appended) the associated component, then the following selectors would be unreliable: `:last-child`, `:nth-last-child`, `:only-child`.

    Compare that to the currently unreliable selectors: `* + [anything]`, `:first-child`, `:nth-child`, `:only-child`.

    By changing to appending the `style` element, emotion would no longer block use of the common adjacent sibling selector and the "last" (rather than "first") varieties of the selectors would be affected, which I would argue is a better tradeoff more in line with actual usage of each [citation needed].

1. "of-type" workaround

    The warning's suggestion should be reworded to make clear that it may not work in all scenarios.
  
1. Incorrect unsafe list of selectors

    - `:only-child` needs to be added (changing this to `:only-of-type` is a good workaround, though!
    - If the `style` element remains prepended
      - The `* + [anything]` selector pattern needs to be flagged
      - `:nth-last-child` needs to be removed
    - If the `style` element is appended
      - Update list to include selectors in (1), above.

1. Mute the unsafe selectors warning

    At the very least, emotion should allow consumers to do so.

**Alternative solutions:**

Another suggested workaround is to somehow replace `:first-child` selectors with `:first-child:not(style), style:first-child + *` in the styles output. While a clever bit of CSS selecting, this suggestion has two main problems I can think of: 1) it won't work for non-`:first-child` selectors (though maybe we could come up with other rewrites for the others) and 2) replacing `:first-child` in a selector is not trivial, as it is affected by whether or not its used on the immediate element being styled or a descendent element.

The maintainers of emotion and its community could also simply decide that making these selectors unreliable is not worth the tradeoff of SSR "just working" and abandon the approach of injecting colocated `style` elements entirely. I have no idea how palatable such a change would be, but wanted to enumerate all the options.

-----

This issue is intended to open discussion around these problems. If we can decide on forward actions, I'm happy to help implement wherever I can.

**Comment by FezVrasta** [comment]
Considering that Emotion knows if it's being server-rendered, it could even replace `:first-child` with `:nth-child(N + 1)` when server-side rendered, and adjust any `:nth-child(N)` accordingly

**Comment by OriginalEXE** [comment]
I don't think we can simply move the styles to after the elements as that would trigger the flash of unstyled content until the styles are parsed. I agree this is a pain in the rear, but I can't think of immediately obvious solutions. Does anyone have experience with other css-in-js libraries, how are they solving this problem, and is it actually solvable.

Rewriting of selectors sounds like a possible solution but it also sounds dangerous.

**Comment by FezVrasta** [comment]
Another possible solution would be to wrap the components into an additional `div` with `display: contents;` and use it to contain the `style` tag, but that wouldn't work on unsupported browsers.

**Comment by OriginalEXE** [comment]
> Another possible solution would be to wrap the components into an additional `div` with `display: contents;` and use it to contain the `style` tag, but that wouldn't work on unsupported browsers.

Do you have time to create a simple example of how this would look like?

**Comment by FezVrasta** [comment]
I mean:
```
<div style="display: contents;">
  <style></style>
  <div class="css-xyz">stuff</div>
</div>
```

the `display: contents` will make sure the additional DIV doesn't break the layout, but it may break descendant selectors and adjacent ones so I don't think it's that feasible actually...

**Comment by OriginalEXE** [comment]
Hmm I don't think that would help, the `.css-xyz` component is still not a first child, I think you would have to do it this way:
```
<style></style>
<div style="display: contents;">
  <div class="css-xyz">stuff</div>
</div>
```
This solves the problem of the `:first-child` selector, but it breaks some other selectors, like immediate sibling `X + .css-xyz`. As you mentioned, it also only works in very modern browsers.

**Comment by kylegach** [comment]
Glad this spurred some discussion, and thanks for chiming in.

@FezVrasta

Replacing with `:nth-child(N + 1)` is an interesting idea. I thought selectors needed to work in both SSR and client "modes", but if emotion knows, there could be something here.

Using `display: contents` is a clever idea, but (currently) has [serious accessibility flaws](http://adrianroselli.com/2018/05/display-contents-is-not-a-css-reset.html#A11y).

-----

@OriginalEXE

>  don't think we can simply move the styles to after the elements as that would trigger the flash of unstyled content until the styles are parsed.

This came up in outside conversation, so I started looking for a reference to confirm. Do you know of one?

If you're right (I suspect you are), I suppose that makes the first problem in this issue moot.

**Comment by Andarist** [comment]
> Replacing with :nth-child(N + 1) is an interesting idea. I thought selectors needed to work in both SSR and client "modes", but if emotion knows, there could be something here.

It needs to work in both modes, the problem at hand here is FOUC. The SSR styles are being moved at runtime to head - as emotion in browser works the same, it doesnt need to know much if the html was SSRed or not. Because of this the rules would have to rewritten both on server and on the client so they produce the same hash for caching purposes. 

I think those rules CAN be rewritten reliably - it's just not super easy and need some effort into writing the smart-ish parser and writing comprehensive tests to ensure we doesnt break anything.

**Comment by OriginalEXE** [comment]
> > don't think we can simply move the styles to after the elements as that would trigger the flash of unstyled content until the styles are parsed.
> 
> This came up in outside conversation, so I started looking for a reference to confirm. Do you know of one?
> 
> If you're right (I suspect you are), I suppose that makes the first problem in this issue moot.

I was actually wrong, apologies for providing false information. It looks like there is no FOUC with the inline style tags, at least not in Chrome and Firefox. I was not able to find any conclusive info on it, though.

**Comment by Andarist** [comment]
Have you tried slower connections? `:first-child` will match "inline" style tags until your script gets downloaded & executed.

Maybe one of the options to avoid FOUC currently would be also to put this:
https://github.com/emotion-js/emotion/blob/2971dba3d4a30be10adea2a7afae047ed83eea0e/packages/cache/src/index.js#L69-L84
into inline script tag 🤔

**Comment by OriginalEXE** [comment]
Sorry if I was not clear, I meant that I was not able to produce a FOUC with the style tags placed after the HTMl they are targetting.

**Comment by OriginalEXE** [comment]
Example reproduction: https://s.codepen.io/OriginalEXE/debug/vvqbrb/vPAKKzQzPgVA

I have checked the rendering in chrome and the very first frame already includes the styled paragraph.

**Comment by Andarist** [comment]
Oh, the issue here is different though - FOUC in this case is caused purely by the fact that we render style tags together with elements and this messes up mentioned pseudo classes (`:first-child` etc)

**Comment by OriginalEXE** [comment]
I understand that. But the thread author initially proposed a solution of moving the style tags after the elements, hence solving the issue of the `:first-child` selector as it's more often used than the `:last-child`, and my immediate reaction was that this would cause FOUC, but it seems like that is not the case.

**Comment by Andarist** [comment]
Oh, I've misunderstood you then. If we can't confirm FOUC for this - I would be in favour of switching the order of those, technically this would be a breaking change though ;s

**Comment by kylegach** [comment]
If we can find a solution that doesn't make _any_ selectors unreliable, that'd be great!

Thank you for the reproduction, @OriginalEXE! I'll investigate other browsers to confirm behavior there, too.

**Comment by OriginalEXE** [comment]
Yup, I think it would be a better solution, but it's definitely a breaking change. I am trying to dig up whether it would have any performance implications.

**Comment by OriginalEXE** [comment]
> Maybe one of the options to avoid FOUC currently would be also to put this:
> [emotion/packages/cache/src/index.js](https://github.com/emotion-js/emotion/blob/2971dba3d4a30be10adea2a7afae047ed83eea0e/packages/cache/src/index.js#L69-L84)
> 
> Lines 69 to 84 in [2971dba](/emotion-js/emotion/commit/2971dba3d4a30be10adea2a7afae047ed83eea0e)
> 
>  if (isBrowser) { 
>    container = options.container || document.head 
>   
>    const nodes = document.querySelectorAll(`style[data-emotion-${key}]`) 
>   
>    Array.prototype.forEach.call(nodes, (node: HTMLStyleElement) => { 
>      const attrib = node.getAttribute(`data-emotion-${key}`) 
>      // $FlowFixMe 
>      attrib.split(' ').forEach(id => { 
>        inserted[id] = true 
>      }) 
>      if (node.parentNode !== container) { 
>        container.appendChild(node) 
>      } 
>    }) 
>  } 
> 
> into inline script tag

Here is a simplified version: https://s.codepen.io/OriginalEXE/debug/yGdrrL/mVkbGpLpGPvM

I was not able to reproduce FOUC this way either. I wonder however whether anything changes with a more complex DOM. Also, I believe not reproducing the FOUC should not be the only thing we consider before making any changes, performance implications should be tested as well.

**Comment by maximilianschmitt** [comment]
I don't think rewriting selectors is a good idea because it's confusing when debugging and also complex and error-prone.

The server-rendering of Emotion 10 unfortunately also messes up the following selector:

```
> * + * { margin-top: 5px; }
```

I agree with @brentertz that sacrificing common CSS selectors for easier setup is not worth it. At least not for us.

**Comment by bradwestfall** [comment]
Yep. @maximilianschmitt Just launched the new ReactTraining.com website (not trying to market) and we're using Emotion 10 with a utility class for "lobotomized owl" (the `* + *` shown above). Just to catch anyone up on that selector, it's importance is that it selects all first level children except for the very first one to add margin top to. Without getting into the details of why this is so cool (read https://css-tricks.com/lobotomized-owls), the point is the mechanics of this selector are to only add margin to non-first child elements. So with Emotion we're experiencing a janky shifting around of things on initial load because <style> is the first child for a moment before it's relocated to the <head>. So what should have been my first div tag is actually second (getting margin top) and then becomes first so it loses margin top. Here is the fix we might be implementing:

```
.owl > * + * {
  margin-top: 1em !important;
}

.owl > style + * {
  margin-top: 0 !important;
}
```
The second selector is basically saying "Take the second child of .owl which is next to a style and lets just remove top margin now because when emotion js kicks in and removes style, the second element will become the first". This fixes the shifting.

Btw, I imagine we'll get this pushed in production today so anyone reading this in the future probably won't see the said "shiftiness". Just wanted to put this here for documentation purposes.

**Comment by jesstelford** [comment]
@bradwestfall 

To stop the FOSC (Flash-Of-SSR'd-Content) when using the labotomized owl, I found this selector to be useful:

```css
*:not(style[data-emotion-css]) + * {
  margin-top: 1em;
}
```

**Comment by jesstelford** [comment]
It looks like most of the issues can be avoided by doing the following for a React app:

```javascript
import { extractCritical } from "emotion-server";
import { CacheProvider } from "@emotion/core";
import createCache from "@emotion/cache";

let { html, css, ids } = extractCritical(
  renderToString(
    <CacheProvider value={createCache()}>
      <App />
    </CacheProvider>
  )
);

let styleTag = `<style data-emotion-css="${ids.join(" ")}">${css}</style>`;
```

(Thanks @mitchellhamilton for the suggestion)

**Comment by grsmvg** [comment]
@jesstelford That's what I will do also. Tried to rewrite a few selectors, but it's a pain. So a combinatino of `extractCritical` and muting the warning in the console, will do for now.

I can't imagine basic CSS being sacrificed for the sake of magic SSR. People doing serious SSR are usually not the least skilled and people using NextJS for SSR are being pushed to styled-jsx by default anyway.

**Comment by joe-bell** [comment]
Cheers @jesstelford!

Probably a dumb question as I'm fairly new to tinkering with SSR (but I'm currently stuck on this issue too), but am I right in thinking that `styleTag` means we don't have to worry about calling [`hydrate()`](https://emotion.sh/docs/ssr#hydrate) as per the docs?

If this is the case, would it be worth my time raising a PR to update the documentation? I've been quite stuck trying to resolve this with the current docs

**Comment by JakeGinnivan** [comment]
Just to echo what @jesstelford has said and suggest a path forward.

1) Document the two SSR approaches, the magic one liner which has this limitation OR use extractCritical. Each are supported and have their pros/cons, ie no streaming support when using extract critical vs css limitations
2) A change is made to emotion so if you are using extractCritical the warning is muted (because it doesn't apply)

In my mind it solves this issue?

We gave 2 a try, but couldn't find a nice place to put a flag when extractCritical is called which could be checked when the warning is about to be output.

**Comment by JakeGinnivan** [comment]
Any thoughts on the above @mitchellhamilton? I don't mind helping, I just do not know the codebase well enough to implement suggestion 2.

**Comment by mitchellhamilton** [comment]
I think this makes sense to me, I think I'm okay with adding a check, it should be as simple as adding a check around the block at https://github.com/emotion-js/emotion/blob/master/packages/cache/src/index.js#L204-L227 if `cache.compat === undefined`

**Comment by JakeGinnivan** [comment]
Created a PR to progress the conversation

**Comment by joe-bell** [comment]
Going back to https://github.com/emotion-js/emotion/issues/1178#issuecomment-461524602 and https://github.com/emotion-js/emotion/issues/1178#issuecomment-469010046 on "lobotomized owl" selectors (`* + *`), the following worked for me:

```js
export const Example = styled.div({
  '& > * + *': {
    marginTop: 16,
  },
  '& > style:first-child + *': {
    marginTop: 0,
  },
});
```

---

This is far from ideal though. I really appreciate the hard-work achieved by the Emotion team to get us all this far, but I agree with @brentertz the trade-off of “breaking” commonly used CSS pseudo selectors. We should be encouraging developers to make use of the cascade, not shy away from it

**Comment by billymoon** [comment]
I couldn't get the `extractCritical` approach to work with my next js app, but this works for me...

```jsx
import Document from "next/document";

const filterEmotion = htmlIn => {
  const styles = [];
  const unique = {};

  const html = htmlIn.replace(
    /<style data-emotion-css="([^"]+)">(.+?)<\/style>/g,
    (all, id, content) => {
      if (!unique[id]) {
        styles.push(
          <style
            key={id}
            data-emotion-css={id}
            dangerouslySetInnerHTML={{ __html: content }}
          />
        );
      }
      unique[id] = true;
      return "";
    }
  );

  return [styles, html];
};

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    const page = ctx.renderPage();

    const [styles, html] = filterEmotion(page.html);

    return {
      ...initialProps,
      html,
      styles
    };
  }
}
```

**Comment by elliotdickison** [comment]
Here's a potential workaround for folks looking for a style-only solution (i.e. no walking through children, no requiring the extractCritical SSR API).

These styles work by stacking up the adjacent sibling selector to reach the desired index. This means a) that they'll need to be programmatically generated for each usage (but hey, this is CSS-in-JS) and b) you can only target a specific index (e.g. 0, 3). This doesn't allow the the fancy arguments that nth-* selectors normally take (e.g. "odd" or "4n").

These styles make me kind of sad, but I'm hoping to just wrap them up in a helper and forget about this whole thing.

```css
/*
 * This will select the 3rd child when no style
 * tag is present (client-side rendering, or SSR
 * with the critical-styles API). This style will
 * not apply if a style tag is present.
 */
.container > *:first-child:not(style) + * + * { /* emotion-disable-server-rendering-unsafe-selector-warning-please-do-not-use-this-the-warning-exists-for-a-reason */
  background-color: red;
}

/*
 * This will select the 3rd non-style child when a style
 * tag is present (normal SSR). This will not apply
 * if no style tag is present.
 */
.container > style + * + * + * {
  background-color: red;
}
```

Demo in JS Bin: https://jsbin.com/xejekumuyu/1/edit?html,css,output

**Comment by jooj123** [comment]
Considering this one is merged: https://github.com/emotion-js/emotion/pull/1483 Can this be closed? Or is it waiting for docs?

**Comment by JakeGinnivan** [comment]
I've noticed a few warnings we are still getting, also I haven't done the docs. I'll try sort it out after I get my types PR merged

**Comment by bradwestfall** [comment]
@jooj123 That PR looks like it's more about fixing the warning right? I think this issue is more about the fact that <style> shows up and then disappears which causes a flickering jumping visual effect with some selectors

**Comment by jooj123** [comment]
@bradwestfall this fixes it: https://github.com/emotion-js/emotion/issues/1178#issuecomment-469098353

If you use `extractCritical` it should mute the message which is what the PR does
I think the documentation is missing around this (hence why this is still open?)

**Comment by bradwestfall** [comment]
@jooj123 I don't have as much experience with Emotion, and I read through the PR but I'm still not sure if what you're saying is that the PR only mutes the warnings when it comes to certain selectors. I guess I view this as a two headed problem based on injecting `<style>` tags among the HTML in SSR. There's the warnings around certain selectors, but there's also the jumpiness that happens even when I'm using selectors that aren't being warned against.

**Comment by Andarist** [comment]
@bradwestfall which selectors are causing you trouble? we can warn about more selectors

**Comment by bradwestfall** [comment]
Thanks @Andarist, I actually don't want any warnings about any selectors but that's not what I was saying :)

Since the issue is "Problems surrounding SSR and injection of <style>", it kind of morphed into other issues beyond warnings about `:first-child` etc. Some selectors are meant to seek out non-first child elements and add margin to them for layout purposes. Since `<style>` is injected all over the server rendered HTML, when it hits the client it's there for a moment before it's removed. This changes "what _is_ the first element" in lots of cases and causes a jumping effect in the layout. Imagine the way I author my code, I have a div that I expect to be the first element, but it's not because a <style> element comes in and then gets removed. So my div was not the first element and now it is.

It's also worth noting that this particular strategy of selector is *very very* popular and well known -not just a bizarre thing that only I do. its all documented above. It's called the [Lobotomized Owl selector](https://www.google.com/search?q=css+lobotomized+owl&oq=css+lobot&aqs=chrome.0.0j69i57j69i64.5964j0j9&sourceid=chrome&ie=UTF-8)

 🙏 Thanks for all your work on this

**Comment by elliotdickison** [comment]
+1 to @bradwestfall 's comment. The reason I loved Emotion was that I could use all the features of css - it had none of the inline style limitations of early CSS-in-JS solutions. If Emotion stops supporting key CSS features I think the value will be considerably diminished.

Are there any benefits to the embedded-style-tags approach other than zero-config SSR? I definitely don't mind a couple extra lines of SSR configuration if that's what it takes to get full CSS support. That seems well worth the tradeoff.

Thanks for the hard work on this lib, it's fantastic!

**Comment by Andarist** [comment]
> Are there any benefits to the embedded-style-tags approach other than zero-config SSR? 

It's not solely about zero-config. This strategy allows for seamless SSR streaming. 

This is definitely a tradeoff that emotion is choosing right now, it also tries to promote more "explicit" relations between styled components (in render) - this has its drawbacks for users accustomed to standard CSS obviously, but it is also something that is restricted in other libraries, like react-native and react-native-web. 

@mitchellhamilton maybe we could create a docs section presenting preferred way of handling those popular patterns with emotion? There is a fair share of confusion regarding this.

**Comment by mitchellhamilton** [comment]
A docs section about handling these patterns with emotion sounds great.

**Comment by Gersom-NL** [comment]
@Andarist Would streaming still work if you add the style as last child of the parent? I think people target elements relative to the first item way more often than to the last item.

**Comment by Andarist** [comment]
I don't think it would, with streaming you receive parts of data and you can always have a time gap between received elements - so putting style tags last could create FOUC

**Comment by bradwestfall** [comment]
Ironically, we're saying the choice of putting it there at all (first or otherwise) _is_ causing a flash just like FOUC. I don't know how your streaming stuff is implemented, so I trust you'll do whatever you can. But is there really no other way to do the streaming?

**Comment by Andarist** [comment]
This is definitely the easiest because all we have to do is render stuff. I'm not working on any SSR-ed project though and won't act like a know it all about this stuff - this approach has been chosen by Mitchell and I'm sure he has taken all things into consideration. He just has chosen different tradeoffs than what probably people involved in the discussion here would chose. I think styled-components are using a slightly different strategy - implemented [here](https://github.com/styled-components/styled-components/blob/d088d689fcf950308864411b5b465686e57e4c1c/packages/styled-components/src/models/ServerStyleSheet.js#L60). It maybe could have been investigated and compared to our current solution, maybe @mitchellhamilton has already done that - not sure.

**Comment by fionawhim** [comment]
FWIW earlier in this thread @OriginalEXE tested and was not able to reproduce a FOUC when the `<style>` tags came after their elements: https://github.com/emotion-js/emotion/issues/1178#issuecomment-455672974

The Codepen has expired, though, so I can’t speak to their methods. But this does seem to be an area of browser behavior than one can’t make assumptions about.

**Comment by Andarist** [comment]
Problem is that I'm worried that those tests were run on a good connection etc. From the very nature of streaming the FOUC should be possible this way, unless I'm missing some part about how this is actually working. It should be possible to hang waiting for a new chunk of data at any point in time so this can happen between receiving elements and styles (talking about styles-last approach).

**Comment by FezVrasta** [comment]
I wouldn't spend too much time on first vs last anyways. It would be just a slight improvement but the problem would still be there

**Comment by JakeGinnivan** [comment]
Docs now cover an Advanced integration which doesn't have selector limitations so people can choose their trade offs.

**Comment by bradwestfall** [comment]
Thanks @JakeGinnivan, do we still see selector warnings even if we're nor using SSR. To my understanding those advanced integrations are all about what to do if you are using SSR right?

**Comment by JakeGinnivan** [comment]
@bradwestfall you need to do the advanced client integration https://emotion.sh/docs/ssr#on-client

Basically if you use the default cache you get the warn, you have to create and use your own cache to disable the warning.

**Comment by elliotdickison** [comment]
Just read the docs - love it, thanks for putting those together! The trade off is much clearer and knowing there’s an escape hatch when you really need it is nice.

**Comment by emmenko** [comment]
FYI: in case it helps, I ended up patching the Lobotomized Owl selector when using the advanced approach for SSR.

https://medium.com/@emmenko/patching-lobotomized-owl-selector-for-emotion-ssr-5a582a3c424c

**Comment by Andarist** [comment]
@emmenko this is a great article and a good take on the problem (if you really, really need to make those selectors to work). We plan to always inject `style` as the first child, so you probably could simplify the output to just be `*:not(style) ~ *`.

I'm afraid that Emotion 11 won't bring much help with that problem because this is explicitly not our goal, but **maybe** it will be easier~ to write a stylis plugin that could automate this for you. Such a plugin would have to be a community-driven effort though.

**Comment by Andarist** [comment]
A great podcast outlining some problems with those selectors (among other things) - http://www.fullstackradio.com/134

**Comment by jooj123** [comment]
I assume that the advanced approach (https://emotion.sh/docs/ssr#advanced-approach) wont work with setups for nextjs ?

as they dont expose the `renderToString` for it to be modified with `CacheProvider` and `extractCritical` etc

**Comment by azizhk** [comment]
@jooj123 Check if these help:
https://github.com/zeit/next.js/tree/canary/examples/with-emotion-10
https://github.com/zeit/next.js/tree/canary/examples/with-emotion-11

**Comment by jooj123** [comment]
awesome thanks @azizhk

**Comment by Vadorequest** [comment]
I experienced this warning today for the first time `The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".` and after 30mn of reading through various issues, I kind of understand the issue.

But the warning is very misleading, and it's not explicit that it comes from Emotion either. Using the term `unsafe` made me believe it might be a security issue.

Could it be possible to:
- Make it clear it's an Emotion warning
=> Would help understand where this is coming from faster (DX)
- Add a link in the warning to learn more about the issue 
=> Would help understand the implications of what we're doing faster (DX), and how disable those warnings (I haven't figure it out yet)
- Replace `unsafe` by `unreliable` in the warning

Couldn't Emotion rewrite those CSS rules, e.g: `:first-child` by something like `:first-child:not(style)` or similar?

If not possible to rewrite, could a solution be given within the warning (or its link)?
I'm thinking about something along the lines of `Replace :first-child by :first-child:not(style)`.

**Comment by Andarist** [comment]
Yes, those are possible. I would be open to merging PRs improving any of those points.

As to rewriting CSS rules - it's hard to cover all possible use cases and we probably wouldn't like dive into this unless someone provides a quality PR for this (then we could start considering it). What we try to avoid here is potential FOUC and thus a simple replacement like you have proposed is not enough. This could work on the assumption that `style` is always a first child for Emotion SSRed output (which should always hold true): `:first-child:not(style), > style + *`:
https://jsfiddle.net/z4nskr61/

**Comment by Vadorequest** [comment]
Is there an existing webpage where this issue is explained thoroughly with developer experience in mind that could be printed alongside the warning? Or is it something that needs to be created?

**Comment by Andarist** [comment]
> Or is it something that needs to be created?

It's vaguely mentioned [here](https://emotion.sh/docs/ssr#default-approach) but a dedicated page or a new section should be created that would go into more details.

> Does using :first-child:not(style) triggers the warning at this time? 

It probably triggers it right now as it's currently just a very simple check.

**Comment by deansimcox** [comment]
Hey everyone, I just wanted to share a way to recreate the `:first-child` selector using `:is()` and `:not()`.
```
  > *:not(:is(*:not(style) ~ *)) {
    float: absolute;
  }
```
This will select the first of any element that is not style and has adjacent siblings.
The only time this selector will break, is if there is only one child, because then the `* ~ *` will not match.

This would selector can also have an element or class like this
```
  > article.this-article-has-a-class:not(:is(*:not(style) ~ *)) {
    float: relative;
  }
```

**Comment by Leonelswinger** [comment]
> Considering that Emotion knows if it's being server-rendered, it could even replace `:first-child` with `:nth-child(N + 1)` when server-side rendered, and adjust any `:nth-child(N)` accordingly





https://stylesheets.space/questions/stylize-the-final-element-within-a-webpage-using-css-styling-techniques
