### ISSUE TITLE
Add peerDependency for `styled` package

### ISSUE THREAD

**Issue by huchenme** [emotion-js/emotion#1180]
Currently @emotion/styled does not contains a `peerDependency`, it should have the same `peerDependency` as @emotion/core

**Comment by tkh44** [comment]
It has a hard dependency of `@emotion/styled-base` (https://github.com/emotion-js/emotion/blob/master/packages/styled/package.json#L14) which has a peerDependency of `@emotion/core` (https://github.com/emotion-js/emotion/blob/master/packages/styled-base/package.json#L28)

Is this causing issues?

**Comment by huchenme** [comment]
@tkh44 no it is not causing issues, just noticed that `@emotion/styled` does not have peerDependency of `@emotion/core` as well, when people checking `package.json` of `@emotion/styled` they will not know what is the minimal react version they need

**Comment by tkh44** [comment]
That's a fair point. If it doesn't break anything I don't see a problem with adding it.

**Comment by FezVrasta** [comment]
This has been fixed

https://github.com/emotion-js/emotion/blob/master/packages/styled/package.json#L24
