### ISSUE TITLE
[Question] Passing classes from parent component

### ISSUE THREAD

**Issue by lkostrowski** [emotion-js/emotion#1181]
Hi

I migrated to Emotion from Glamorous and I miss one thing (or maybe I just don't know how to do it).
It's connected to this: https://emotion.sh/docs/class-names, but I don't think it's actually good developer experience.

What I do is writing self-contained components, which are basically *not* positioned (no margins, sizes etc) and positioning happens in parent, which layout them. 

To achieve that, there are two ways to do this:
1: Wrapper:

```
  <div className="layout">
    <div className="layout__nav">  
      <NavComponent />
    </div>
  <div />
```

This more-or-less works, but has some limitations, also required extra markup

2: Mix classes

```
  <div className="layout">
     <NavComponent className="layout__nav" />
  <div />
```

This is preferable to me, my component looks like this then:

```
  const NavComponent = ({...props}) => (<SomeEmotionStyled {...props}>...</SomeEmotionStyled>)
```

This worked in Glamorous. I've seen in `<ClassNames>` HOC this can be achievable, but it's a lot of extra code, when I use it quite often.

What is desirable approach here? `css` function doesn't return css class, so it's not easy to pass it down

**Comment by carpben** [comment]
I mostly work with Emotion 9, but also work with Emotion 10. Here is an example to my solution : 

```js
const Link = styled("a")`
	color: ${COLORS.GREEN};
        text-decoration: underline;
   ${ ( {stl}) => stl }
`
const BorderedBox = styled("div")`
    border: 1px solid black; 
    ${ ( {stl}) => stl }
`
const Parent = (props) => (
    <BorderedBox stl="margin: 10px;"/>
         Visit us at 
         <Link href="http://www.ourSite.com"  stl=`
               padding: 5px; 
               font-size: 22px; 
         `> 
               Our Cool Website
         </Link>
    </BorderedBox> 
)

```

**Comment by tkh44** [comment]
I'm having trouble understanding exactly what it is you are asking for. Can you give a better example of what you are doing now and what you want?

`<NavComponent className="layout__nav" />` is going to render the underlying element with the class name `layout__nav`?

```js
const Thing = props => (
  <div
    css={{
      '& .layout__nav': {
        padding: 8
      }
    }}
  >
    <NavComponent className="layout__nav"/>
  </div>
)
```

or with css prop. Notice that the NavComponent doesn't need any layout styles but can be styled via the css prop.

```js
const Thing = props => (
  <div
    css={{
      display: 'flex'
    }}
  >
    <NavComponent css={{
      padding: 8
    }}/>
  </div>
)
```

**Comment by lkostrowski** [comment]
@carpben more or less described solution to my case but this is workaround.

```
<NavComponent css={{
      padding: 8
    }}/>
```
This doesn't seem to work 🤔 also should it be `css={css({...})}`?

My case is quite simple. All components are standalone and fluid, for example some `<Button />` has default set `width: 100%` so it fits parent.
But in some cases I want `<Button />` to be `width: 50%`. I don't want to hardcode it into `<Button />` but make this responsibility of parent component, which lay out these components.
So I need some best practice how to pass down (via props) class or style and somehow assign it to the root of `<Button />`. Keep in mind that root el of `<Button />` is styled component

`const Button = (props) => Emotion.styled('button', {... some button internal styles})`

**Comment by tkh44** [comment]
If you are using `import { css } from 'emotion'`

```jsx
const Parent = () => {
  return <div><Button className={css({width: '50%'})} />
}
```

What version of emotion are you using and how are you importing it? It might be worth taking another look at the docs. Styled components accept a className prop just like any other component.

**Comment by akd-io** [comment]
I'm finding this really frustrating as well. I was honestly expected styled components to override their styles when given a css prop, and it was one of the reasons I chose to dive deeper into emotion, because it would make it extremely easy to make components reusable.  
  
Are there plans to implement this? I was really hoping to be able to write:
```javascript
const ButtonEl = styled.button({display: 'inline-block'})
export const Button = ({css, children, ...props}) => <ButtonEl css={css} {...props}>{children}</ButtonEl>
```
as @lkostrowski mentioned [here](https://spectrum.chat/emotion/general/idiomatic-way-of-extending-styles-of-another-component-in-emotion-10~1c44fdd1-af20-443f-b485-eaccad88b51f?m=MTU0ODg5MDM1ODY4Ng==)

**Comment by Andarist** [comment]
@akd-io It already should work like this, take look at docs section which described this composition behaviour - https://emotion.sh/docs/css-prop#style-precedence

**Comment by akd-io** [comment]
@Andarist I'm sorry if my errors are my own fault because of a flawed babel setup or similar, but are you sure it works with components styled with `styled.*()` syntax as well? style precedence using css() only works fine for me too. This does not:
![image](https://user-images.githubusercontent.com/30059155/58809012-664be680-861b-11e9-86b8-040e89457331.png)

**Comment by Andarist** [comment]
Could you prepare a repro case on something like https://codesandbox.io ? Pasting in a screenshot is not the best way to share code 😉

**Comment by akd-io** [comment]
Of course, @Andarist, I'll do it as soon as I get the time! Thanks for listening so far.

**Comment by akd-io** [comment]
@Andarist Sorry for wasting your time man. I forgot `/** @jsx jsx */` and the jsx import 🤦‍♂️. No css-prop was working, even on unstyled components. Sorry!

**Comment by Andarist** [comment]
Hopefully, everyone engaged in this conversation has resolved their issue. If not please open a new one.

**Comment by hatton** [comment]
In Typescript I ran into a situation where there was a clash between the types of an `onChange` prop such that I could not get away with just adding {...props} to the child.  The solution is to specifically add `className` to the child's props and then just add that instead of all the props.

```typescript
const Parent: React.FunctionComponent<{}> = (props) => (
    <Child
        css={css`
            background-color: red;
        `}
        onChange={(x) => {}}
    ></Child>
);

const Child: React.FunctionComponent<{
    onChange: (value: string) => void;
    className?: string;
}> = (props) => 
    <FormControl className={props.className}> 
         /* some code that eventually calls props.onChange*/
    </FormControl>;

```
