### ISSUE TITLE
Cannot make 'jest-emotion' work with Emotion 10, CSS Prop and Enzyme

### ISSUE THREAD

**Issue by ianvieira** [emotion-js/emotion#1187]
- `emotion` version: @emotion/core@10.0.6
- `react` version: 16.6.1
- `jest` version: 23.5.0

**Relevant code:**

setupTestFrameworkScriptFile file:
```javascript
const jsonSerializer = require('enzyme-to-json/serializer');
const emotionSerializer = require('jest-emotion');

expect.addSnapshotSerializer(emotionSerializer);
expect.addSnapshotSerializer(jsonSerializer);
```
Component.js
```javascript
render() {
       const ratioStyles = css(generatedObjectWithStyles);

        return (
            <div className={ theme.placeholder } css={ [ratioStyles, placeholderStyle] } />
        );
}
```

Component.test.js
```javascript
test('should render with required props', () => {
        const wrapper = shallow(
            <Component { ...mockProps } />
        );

        expect(wrapper).toMatchSnapshot();
    });
```

**What you did:**
I added the `@emotion/babel-preset-css-prop` preset, the code is working as expected and added the snapshot serializer.

**What happened:**
Component snapshot (Shallow):
```javascript
 +     <div
    +       className="Theme__Placeholder"
    +       css={
    +         Array [
    +           Object {
    +             "map": undefined,
    +             "name": "ac6mem",
    +             "next": undefined,
    +             "styles": "padding-bottom:56.25%;",
    +           },
    +           Object {
    +             "map": undefined,
    +             "name": "1wdfeuq",
    +             "next": undefined,
    +             "styles": "
    +     background: #e6e6e6;
    +     border-radius: 0.4rem;
    + ",
    +           },
    +         ]
    +       }
          />

```

Component snapshot (Mount):
```javascript
<div
    +           className=""
    +           css={
    +             Array [
    +               Object {
    +                 "map": undefined,
    +                 "name": "ac6mem",
    +                 "next": undefined,
    +                 "styles": "padding-bottom:56.25%;",
    +               },
    +               Object {
    +                 "map": undefined,
    +                 "name": "1wdfeuq",
    +                 "next": undefined,
    +                 "styles": "
    +     background: #e6e6e6;
    +     border-radius: 0.4rem;
    + ",
    +               },
    +             ]
    +           }
    +         />

```

**Problem description:**
The CSS prop is returning the object instead of the className prop filled and the styles in a separated part, as in the docs.

Tried also setting manually the pragma, same result.

Following this [thread](https://github.com/emotion-js/emotion/issues/949#issuecomment-432099235), I saw that `shallow` is not supported, so I tried with `mount`, same result again.

Is something wrong in my setup? I found no further documentation, or related issues, that could support me.

**Comment by JackHowa** [comment]
*    "jest": "23.6.0",
*    "jest-emotion": "^10.0.10",
*   "jest-enzyme": "^7.0.1",
*   "@emotion/core": "^10.0.10",
*    "@emotion/styled": "^10.0.10",

I'm having similar issues of passing down props using mount. Getting error that style props were not found on passed component

**Comment by Vaexqua** [comment]
If you're still struggling with this issue, the only way I could find to get it to work was to the add the pragma _to the test file_. If anyone knows a way of getting jest to pick up `@emotion/babel-preset-css-prop`, please let me know...

**Comment by Vaexqua** [comment]
I had exactly the same problem. The only way I could get this to work was to add the pragma to the component files for which I require the `jest-emotion` tools, even though I'm still using `@emotion/babel-preset-css-prop` for everything else. This is obviously not ideal, so it'd be great if someone could address this

**Comment by ianvieira** [comment]
In my case, it was a very specific problem, my Jest configuration was with the `babelrc` option disabled (it's in a different package so I didn't see it), that's why even with everything set up, it was not working with Jest. After enabling it, worked as expected.
