### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by steida** [emotion-js/emotion#119]
Is React Native version planned?

**Comment by tkh44** [comment]
Not currently.

**Comment by loganpowell** [comment]
Looks like emotion is a real contender for unseating styled-components and a native effort might be the nail in the coffin. Just sayin'

**Comment by lukewlms** [comment]
@loganpowell glamorous has native support, I'm really pleased with our results from that lib.

**Comment by loganpowell** [comment]
@lukewlms yes, but the preference is for the template string ('just css') paradygm on our end...

**Comment by collegeimprovements** [comment]
Maybe now !!!! As styled-component and glamor provide it out of the box now. But we love emotion.

**Comment by eugenehp** [comment]
+1

**Comment by brunolemos** [comment]
Why is this closed btw? Isn't there any interest in this, even by a community effort?

**Comment by tkh44** [comment]
Please put the word out that we want this.

**Comment by ilyanoskov** [comment]
yes, that will be great! looking forward to have this

**Comment by luddzo** [comment]
Yes! I'm loving emotion and right now it seems like I'll have to use styled-components for React Native with a similar syntax. Erase that reason to switch guys!!!11

**Comment by jonsherrard** [comment]
If anyone has any inkling on how this might be implemented, I could take a look.

I guess I could look at Styled Components...

Update: I have looked:


This is the PR from Styled Components that got it working on Native Initially: https://github.com/styled-components/styled-components/pull/53/files

I'll have a play around this week.

**Comment by DavideDaniel** [comment]
This is actually one of the make or break use cases in some decisions around alignment at multiple companies so if we can get some community support around this it'd be great...

**Comment by Jaikant** [comment]
oh. I have been using emotion with react. Just stepped into react-native and I was so hoping emotion is supported.

**Comment by t49tran** [comment]
👍 +1

**Comment by zsajjad** [comment]
@DavideDaniel any update on this?

**Comment by brunolemos** [comment]
Seems like #658 is ready to be merged

**Comment by brunolemos** [comment]
#658 got merged! Maybe this can be closed now? cc @steida

**Comment by Andarist** [comment]
While #658 should work in RN this is a specific use case (primitives). General RN integration could still be developed.

**Comment by brunolemos** [comment]
Just tested!

<img width="400" src="https://user-images.githubusercontent.com/619186/42404042-26285d1e-815c-11e8-9b85-976847e55bac.png" />

```jsx
import React, { PureComponent } from 'react'

import styled from '@emotion/primitives'

const Container = styled.View`
  flex: 1;
  justify-content: center;
  align-items: center;
  background-color: #f5fcff;
`

const Title = styled.Text`
  font-size: 20;
  text-align: center;
  color: hotpink;
`

const Description = styled.Text`
  text-align: center;
  color: #333333;
  margin-bottom: 5;
`
export default class App extends PureComponent {
  render() {
    return (
      <Container>
        <Title>Welcome to Emotion Primitives</Title>
        <Description>Style and render primitives across targets.</Description>
      </Container>
    )
  }
}
```

**Comment by Enalmada** [comment]
Can someone explain/estimate the amount of community effort that remains to be able to consider emotion-js having enough react native support that it could be considered a viable alternative to styled-components, fela, or glamorous-native?  The above post makes it feel so close to the finish line that alternatives have already crossed and I would love to see emotion-js keep the momentum going so that what might be the biggest reason most people can't migrate from styled-components/fela goes away.

**Comment by Andarist** [comment]
Most work was done by @nitin42 , so I think he should answer on that question :)

**Comment by jfrolich** [comment]
Awesome work folks! Especially @nitin42, will use this in the native app I'm working on!
