### ISSUE TITLE
Styling child component based on props

### ISSUE THREAD

**Issue by MrBr** [emotion-js/emotion#1192]
**Problem description:**

Can't override/define child component style based on it props, without introducing `className` to reflect props. The same thing applies actually to any component. So, the question is, how to style a component from parent component based on child props.

Example, how to style `Icon` from parent component in the case it has `primary` prop:
```
const Component = ({primary, children}) => (
  <div>
    {children}
    <Icon primary={primary}/>
  </div>
);

const ParentComponent = styled(() => <Component>Test</Component>)({
  [`Icon primary`]: {color: 'red'} // Style Icon color **only** if it has primary prop set to true
});
```

**Suggested solution:**

To be honest I do not have a solution at the moment but as I see it, propagating dynamic style through the `Context` could do the trick. I am aware that it could potentially arise performance issues and API should be extended somehow to support this new feature that is why I want to see what you all think about it.

I guess an end implementation I want to acheive could look something like this:
```
const ParentComponent = styled(() => <Component>Test</Component>)({
  [Icon]: parentProps => childProps => childProps.primary && {color: 'red'}
});
```
New implementation should definitively preserve current "style object" interface and only extend it.

**Why**

Emotion and other CSS in JS libs are already going in that direction I just find we could move even step further. Seems to me that this is the last stepping stone to leave classes behind. Looking at the open source UI libs, such as Material UI, they still provide a lot of classes per component exactly to support better flexibility when it comes to dynamic styling (or overriding).

There are few more issues that arise but let's take it one step at a time.
Let me know what you think, I am more than happy to work on it.

Thanks

**Comment by Slapbox** [comment]
@Andarist sorry to ask a support question on the issue tracker, but I've been searching and waiting for an answer on Stack forever without luck. I've even tried searching the `styled-components` docs for a technique since there's a lot of overlap, but no luck.

If you can't style children based on their props, and `first-of-type` and `first-child` don't work consistently (even without SSR,) what's the workaround besides resorting to old-fashion css classes and rules? Specifically trying to move a rule like this from css to `emotion`, I can't find any way to only target a span that's `enabled` and `:first-of-type` or `:first-child`. 

```js
const SomeComponent = styled.div`
  > span.enabled:first-of-type {
    background: red;
  }
`
```

**Comment by Andarist** [comment]
We don't plan to introduce support for anything like this. Even putting aside code complexity and performance penalty for doing anything resembling the proposed solution, we don't believe this would make a good design decision. 

Emotion (as many other CSS-in-JS libraries) tries to avoid the cascade as much as possible to avoid strong coupling between components and this is what you propose here. We believe that doing prop-based styling (limited to own props) leads to more maintainable styling overall.
