### ISSUE TITLE
Extraneous kebab-case warning for media queries

### ISSUE THREAD

**Issue by clight-fastly** [emotion-js/emotion#1198]
- `emotion` version: @emotion/core@10.0.6
- `react` version: react@16.8.0-alpha.1

**Relevant code:**

```javascript

mq.sm = `@media (min-width: 800px)`

<div css={{
	[mq.sm]: {
		display: 'flex'
	}
}}>

```

**What happened:**

Error: 
```Using kebab-case for css properties in objects is not supported. Did you mean @media (minWidth: 800px)?```

**Problem description:**
Emotion warns about kebab case on media queries but probably should not. Using a kebab-casing of the original media query ie (minWidth: 800px) does not work as intended.

**Suggested solution:**
Relax the warning for media queries

**Comment by mitchellhamilton** [comment]
Could you create a reproduction?

**Comment by clight-fastly** [comment]
Ah, through the process in trying to create one I found that my media query value was `undefined` which caused the error.
ie
```jsx
<div css={{
	['@media (min-width 800px)']: undefined
}}/>
```

If the value is an object, there is no warning. The warning could perhaps be improved but I wouldn't consider it a bug. Thank you.

**Comment by Andarist** [comment]
From what I can tell - this no longer happens. Additionally, falsy values as object values are allowed, see this test:
https://github.com/emotion-js/emotion/blob/6cb8d15438b01b8623af42f304d5ea3032332187/packages/emotion/test/css.test.js#L248-L252

Closing this as resolved.

**Comment by corysimmons** [comment]
@mitchellhamilton Here's a reproduction: https://codesandbox.io/s/icy-hill-5kh1m?file=/src/App.js

I thought what we passed to the `css` prop was 1-to-1 with what we can pass to styled elements. This is really confusing.

**Comment by Andarist** [comment]
@corysimmons this is a different issue than reported originally here. And the warning you have received is sound - when using object styles you should use camel-cased properties. The same would have been reported for styled elements:
```js
styled.div({
  'font-size': 16
})
```

**Comment by corysimmons** [comment]
@Andarist Ah, sorry about that. Thank you for the help!
