### ISSUE TITLE
react-native-web & @emotion/native Cannot find module 'StyleSheet'

### ISSUE THREAD

**Issue by robskidmore** [emotion-js/emotion#1199]
I'm trying to use `emotion/native` with `react-native-web` and `nextjs`.

To get `react-native-web` to work with next I've added a resolve alias to my webpack config as shown [here](https://github.com/zeit/next.js/blob/b8057edd6e691db4549bbedf11a526e02f0d8f4e/examples/with-react-native-web/next.config.js#L6) 

Everything works great with next and react-native-web but as soon as I import something from `emotion/native` I get an error saying it can't find the ['StyleSheet' module](https://github.com/emotion-js/emotion/blob/56551b8a418cd9044832026f64840ab30986e85e/packages/native/src/styled.js#L1).

I've managed to reproduce the error in a codesandbox

https://codesandbox.io/s/jnovo3kmyy

Any insight would be appreciated.

**Comment by Aleksion** [comment]
Hi @robskidmore did you ever figure this out?

**Comment by robskidmore** [comment]
@Aleksion I used https://www.npmjs.com/package/patch-package to patch things myself. That worked great. But then I ran into other struggles with `react-native-web` and ended up just ripping it out of the app.

Hope that helps.

**Comment by Andarist** [comment]
The error happens on the server. On the server, Next.JS uses a custom `externals` function (https://webpack.js.org/configuration/externals/#externals) and it tries to keep everything from node_modules as external:
https://github.com/zeit/next.js/blob/8e62c9b688aa7a92e339b728237e8c63ec31f1b5/packages/next/build/webpack-config.ts#L475-L479
So basically this alias in webpack doesn't impact the server at all - as resolving of `@emotion/native` (and thus `react-native`) is left for Node.JS to do and it doesn't know about your webpack aliases.

I have no idea how this should be solved - seems really like it should be described here: https://github.com/zeit/next.js/blob/f10f3304fe3926b69ad01fdf76e4ae1fbafaf141/examples/with-react-native-web/README.md , but it is not. Maybe this example doesn't suffer from this problem somehow - I'm not sure as I never have used Next.JS myself so I don't know how a page built with it is structured exactly.

I believe you should raise this issue in Next.JS - going to close the ticket here as it isn't an emotion issue specifically. Hope you understand.

**Comment by robskidmore** [comment]
Ah, that makes sense. Thanks @Andarist. I'll give it another go when I get the chance.

**Comment by philscott-dev** [comment]
https://github.com/vercel/next.js/issues/7244#issuecomment-660113933

This solution worked for me on Next.JS 9.5.3 & @emotion/native 11.0.0-next.17
