### ISSUE TITLE
Emotion 10 and basic SSR

### ISSUE THREAD

**Issue by WestonThayer** [emotion-js/emotion#1205]
- `emotion` version: 10.0.6
- `react` version: 16.5.2

I'm trying to demo rendering React + Emotion 10 to an HTML string in this CodeSandbox: https://codesandbox.io/s/oxjlz3llqz

The class names are coming through just fine, but no `<style>` tags are present in the string (however, they are being injected into the containing CodeSandbox page). The [docs](https://github.com/emotion-js/emotion/blob/master/docs/ssr.md) say SSR should work "out of the box". What am I missing?

Is emotion detecting whether it's running in a node environment or the browser behind the scenes and changing behavior?

**Comment by mitchellhamilton** [comment]
Yes, emotion only does server rendering in Node.
