### ISSUE TITLE
Styled shorthand with custom instances and babel-plugin doesn't work

### ISSUE THREAD

**Issue by Tokery** [emotion-js/emotion#1207]
- `create-emotion` version: 10.0.6
- `create-emotion-styled` version: 9.2.8
- `react` version: 16.7.0

**Relevant code:**

Create a custom styled instance (CustomEmotion.js)
```javascript
import createEmotion from 'create-emotion';
import createEmotionStyled from 'create-emotion-styled'
import React from 'react';


const customEmotion = createEmotion();
export default createEmotionStyled(customEmotion, React);
```

Use the customStyle (Styled.js)
```javascript
import styled from './customEmotion';

export const SpecialDiv = styled.div`
    background-color: hotpink;
`
```
.babelrc
```JSON
{
  "presets": ["@babel/preset-react"],
  "plugins": [["emotion", {
    "instances": ["./src/Styled.js", "./src/CustomEmotion.js"]
  }]]
}
```

**What you did:**
Attempt to run app with babel-plugin-emotion
styled('div') works but not styled.div

**What happened:**
Error: You're trying to use the styled shorthand without babel-plugin-emotion.
Please install and setup babel-plugin-emotion or use the function call syntax(`styled('div')` instead of `styled.div`)

**Reproduction:**
Attempt to run the app in the linked repo

Link to example:
https://github.com/Tokery/EmotionInstancesStyled

**Problem description:**
Error: You're trying to use the styled shorthand without babel-plugin-emotion. **However**, babel-plugin-emotion is installed.

**Suggested solution:**
Not sure if I misconfigured or it is genuinely broken.

**Comment by Andarist** [comment]
You shouldnt mix emotion@10 with styled@9. Keep both in sync if you make it work.

Emotion@10 has no create-emotion-styled though, you can customize how styled handles your styles with CacheProvider component.

**Comment by FezVrasta** [comment]
Closing since the issue has an answer.
