### ISSUE TITLE
Flow is not working inside jsx

### ISSUE THREAD

**Issue by rpavlovs** [emotion-js/emotion#1211]
- `emotion` version: `10.0.6`
- `react` version: `16.7.0`
- `flow-bin` version: `0.92.0`

**Relevant code:**

```javascript
// @flow

/** @jsx jsx */
import { jsx } from '@emotion/core'
import React from 'react'
import * as ReactRouter from 'react-router-dom'

import Flex from 'components/common/flex'
import ROUTE from 'constants/route'

export default class NavBar extends React.PureComponent<{}> {
  render() {
    const route = ROUTE.SALES <-- [Error] Cannot get ROUTE.SALES because property SALES is missing in object literal [1].
    console.log({ route })
    return (
      <Flex>
        <ReactRouter.NavLink exact to={ROUTE.PATH.STORE}>
          Store
        </ReactRouter.NavLink>
        <ReactRouter.NavLink exact to={ROUTE.SALES}> <-- No error
          Sales
        </ReactRouter.NavLink>
        <ReactRouter.NavLink exact to={ROUTE.PATH.PROFILE}>
          Profile
        </ReactRouter.NavLink>
      </Flex>
    )
  }
}
```

**Problem description:**

Flow seems to be not running inside the jsx. Removing `@jsx` pragma reveals the errors.

Silencing some but not all erorrs makes use of Flow + Emotion dangerous in a subtle way. 

Not sure how exactly `@jsx` pragma works and why it breaks Flow. Any ideas why is this happening?

**Comment by rpavlovs** [comment]
Oh, I guess it's a Flow issue actually https://github.com/facebook/flow/issues/5469

Is there any way to setup Emotion without `@jsx` gragmas?

**Comment by FezVrasta** [comment]
If you don't need the `css` property, you can just use `@emotion/styled/macro` and get most of the functionalities offered by the babel plugin

**Comment by Andarist** [comment]
@FezVrasta could you confirm this issue? Or is it just reluctance towards adding the jsx pragma?

**Comment by FezVrasta** [comment]
I’d need to check, I personally don’t use the custom pragma

**Comment by Andarist** [comment]
@rpavlovs if the issue persists - please open a new issue with a runnable repro case and exact repro steps. Thank you for understanding
