### ISSUE TITLE
Changelog not kept up to date ? 

### ISSUE THREAD

**Issue by sync** [emotion-js/emotion#1213]
- `emotion` version: 10.0.7

**What happened:**

Cannot find changelog for version 10.0.7

**Comment by Andarist** [comment]
Not sure why new version has been created back then but there were no changes between the previous one and this one: https://github.com/emotion-js/emotion/compare/emotion@10.0.6...emotion@10.0.7?expand=1

Currently, changelogs are automatically generated with the help of changesets so this shouldn't happen anymore.
