### ISSUE TITLE
Your site is broken

### ISSUE THREAD

**Issue by haf** [emotion-js/emotion#1221]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/193115/52531459-27b1b980-2d16-11e9-9e8f-6960a6187604.png">

Disabling `display: grid` on the main element causes text flow to work.

**Comment by therobinkim** [comment]
For what it's worth, my view of emotion.sh is just fine on the latest version of Firefox, Chrome, and Safari (on latest version of macOS). Not sure what browser @haf might be using though. ¯\_(ツ)_/¯

**Comment by tkh44** [comment]
The new version of the site has been deployed. Going to close this.

**Comment by haf** [comment]
I've verified that your fix works. You can close this issue now.
