### ISSUE TITLE
Typings: withComponent loses event handler callback types

### ISSUE THREAD

**Issue by epeli** [emotion-js/emotion#1226]
- `emotion` version: 10.0.7
- `react` version: 16.8.1
- `typescript` version: 3.3.1

**Relevant code:**

```ts
import styled from "@emotion/styled";
import React from "react";

const View = styled("div")({
    display: "flex",
    position: "relative",
    boxSizing: "border-box",
    flexDirection: "column",
});

const Input = styled(View.withComponent("input"))({
    color: "red",
});

function App() {
    return (
        <Input
            onChange={e => {
                // Implicit any on `e`
            }}
        />
    );
}

```

**What you did:**

Tried to extend styled component from `div` to `input` using `withComponent`

**What happened:**

Got `Parameter 'e' implicitly has an 'any' type.` type error with TypeScript strict mode.

![image](https://user-images.githubusercontent.com/225712/52634564-3512a380-2ed0-11e9-81dd-add4ca3074a0.png)

**Reproduction:**

Just paste the example code to vscode.

Use this tsconfig.json:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "esnext",
        "lib": ["es2018", "dom", "esnext"],
        "jsx": "react",
        "inlineSourceMap": true,
        "moduleResolution": "node",
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "noEmit": true,
        "esModuleInterop": true
    }
}
```

**Problem description:**

For some reason event handlers lose their types. The same thing happens with `onClick`, `onBlur` etc.

The event handler has following type

![image](https://user-images.githubusercontent.com/225712/52634655-6c815000-2ed0-11e9-9620-7f87442689ec.png)

`React.FormEvent<HTMLDivElement>)` seems wrong.

If the withComponent does not change the underlying component type it works like expected

```ts
const View = styled("input")({
    display: "flex",
    position: "relative",
    boxSizing: "border-box",
    flexDirection: "column",
});

const Input = styled(View.withComponent("input"))({
    color: "red",
});

function App() {
    return (
        <Input
            onChange={e => {
                // `e` has correct React.ChangeEvent<HTMLInputElement> type!
            }}
        />
    );
}
```

**Suggested solution:**

🤷‍♂️

**Comment by epeli** [comment]
This seems to be regression since 9.x.

**Comment by flaff** [comment]
For me typings don't seem to work for any `styled` elements.
For `styled.label` quick documentation points me to `StyledComponent<JSXInEl["label"], Omit<InnerProps & ExtraProps, ReactClassPropKeys>, any>` type, but acts like `any` (no prop suggestions).

**Comment by Andarist** [comment]
@JakeGinnivan could you take a look at this to see if your PR resolves this?

**Comment by JakeGinnivan** [comment]
Yep, works fine.

**Comment by Andarist** [comment]
🎉 

Closing this issue as it will get resolved by https://github.com/emotion-js/emotion/pull/1501
