### ISSUE TITLE
change `emotion-theming` to `@emotion/theme`

### ISSUE THREAD

**Issue by ianstormtaylor** [emotion-js/emotion#1227]
It seems like there's a move towards `@emotion/*` prefixes, which is good. But the theming package is left behind. And at the same time, "theming" is a hard word to spell and pronounce (is it "theming" or "themeing") so I recommend changing to the simpler "theme" instead.

**Comment by Andarist** [comment]
Package renaming RFC has just been opened (#1635) - we are open for any feedback. At the same time, theme stuff is being moved into what is currently `@emotion/core` so that would "fix" this issue by just removing `emotion-theming` entirely 😅
