### ISSUE TITLE
How to hot-reload with emotion?

### ISSUE THREAD

**Issue by flexdinesh** [emotion-js/emotion#1233]
- `emotion` version: 10.0.7
- `react` version: 16.8.1

**Relevant code:**

```javascript
// no code - this is a generic question
```

**What you did:**

Used `css` prop to add styles via template literals

**What happened:**

I used to work with css-modules with styles imported from `.scss` files. With css-modules, I can change the styles in `.scss` file and the styles will be hot-reloaded in the browser without refreshing the page.

With emotion, the styles are written in js and present in `.js` files. Because of this, every time I update the styles, the browser refreshes the page.

Is there a way to hot reload the styles without having to have the page refreshed with emotion?

_Note: I usually import my styles from a file named `Foo.styles.js` and pass it to the css prop._

**Comment by harsh-tamr** [comment]
I'm having the same issue.

**Comment by alexmacarthur** [comment]
Same here! Using `@emotion/core` at version 10.0.10, and React at version 16.8.6.

**Comment by tomaszkepa** [comment]
The same here :( Is there any updates?

**Comment by flexdinesh** [comment]
Emotion has nothing to do with this. React should ideally handle hot reload. Probably when hooks came out hot reload was not completely working but the React team released an update few months later for hot reload to work right with hooks. Closing this issue for now.
