### ISSUE TITLE
Jest snapshot tests fail using css={css(`....`)}

### ISSUE THREAD

**Issue by volkanunsal** [emotion-js/emotion#1234]
- `emotion` version: 10.0.5
- `react` version: 16.6.0

**Relevant code:**

```javascript
<div
        css={css(`
        display: grid;
        grid-template-rows: 50px 1fr 40px;
        height: 100%;
      `)}
      >...</div>
```

**What you did:**

I tried to snapshot test the component above.

**What happened:**

I got this error:

```js
Error: Uncaught [Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

**Problem description:**

When I use `css` prop on my HTML components, I get the error message above in my snapshot tests. I have followed the instructions on testing document and added `jest-emotion` as a snapshot serializer in my Jest config file, but this didn't solve the problem:

```js
snapshotSerializers: ['enzyme-to-json/serializer', 'jest-emotion'],
```

My babel plugins:

```
'universal-import',
'react-hot-loader/babel',
['@babel/plugin-proposal-decorators', { legacy: true }],
'@babel/plugin-syntax-dynamic-import',
'@babel/plugin-proposal-class-properties',
'@babel/plugin-transform-runtime',
'@babel/plugin-transform-flow-strip-types',
'inline-react-svg',
'macros',
'emotion',
```

**Comment by ifiokjr** [comment]
I'm having the same problem, except I'm not even trying to use the snapshot testing. Just rendering a component which has the `css` prop causes this issue. 

![image](https://user-images.githubusercontent.com/1160934/59549365-450cc380-8f54-11e9-8933-9d90384b9600.png)


```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
      
      Check the render method of `Context.Consumer`.          in EmotionCssPropInternal (created by Context.Consumer)          in EmotionCssPropInternal (created by Remirror)          in Remirror
```

The way I fixed this was to remove the `@emotion/babel-preset-css-prop` from my presets and now tests pass (although I suspect I won't be able to use `jest-emotion` for snapshot testing anymore).

**Comment by Andarist** [comment]
To the extent of my knowledge, there are currently no issues with snapshotting components using css prop. I guess this was some kind of configuration mistake on OP's side. Can't quite be sure because no repro case has been given. If you manage to create such - please open a new issue and I will gladly take a look at this. Until then - I'm going to close this to keep the issue tracker clean.
