### ISSUE TITLE
Missing source maps when function is used in `css` prop

### ISSUE THREAD

**Issue by RafalFilipek** [emotion-js/emotion#1235]
- `emotion` version: `10.0.7`
- `react` version: `-`

**Relevant code:**

```javascript
export default () => (
<div>
    <div css={{ color: 'red' }} />

    <div css={() => ({ color: 'blue' })} />
  </div>
);
```

**What you did:**

If we transpile this file with babel:

```bash
yarn babel --presets @babel/preset-react,@emotion/babel-preset-css-prop index.js -o index.out.js
```

```javascript
import { jsx as ___EmotionJSX } from "@emotion/core";

var _ref = process.env.NODE_ENV === "production" ? {
  name: "tokvmb",
  styles: "color:red;"
} : {
  name: "tokvmb",
  styles: "color:red;",
  map: "/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImluZGV4LmpzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUVTIiwiZmlsZSI6ImluZGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiZXhwb3J0IGRlZmF1bHQgKCkgPT4gKFxuICA8ZGl2PlxuICAgIDxkaXYgY3NzPXt7IGNvbG9yOiBcInJlZFwiIH19IC8+XG5cbiAgICA8ZGl2IGNzcz17KCkgPT4gKHsgY29sb3I6IFwiYmx1ZVwiIH0pfSAvPlxuICA8L2Rpdj5cbik7XG4iXX0= */"
};

export default (() => ___EmotionJSX("div", null, ___EmotionJSX("div", {
  css: _ref
}), ___EmotionJSX("div", {
  css: () => ({
    color: "blue"
  })
})));
```

**What happened:**

As you can see, source map was generated only for first element (`color: red`)

**Reproduction:**

```bash
yarn init -y
yarn add @babel/cli @babel/preset-react @emotion/babel-preset-css-prop @emotion/core
echo "export default () => <div><div css={{ color: 'red' }} /><div css={() => ({ color: 'blue' })} /></div>
" > index.js
yarn babel --presets @babel/preset-react,@emotion/babel-preset-css-prop index.js -o index.out.js
cat index.out.js
```

**Comment by Andarist** [comment]
To generate source maps we need to be able to target some AST nodes, we don't want to transpile every object in a file after all. `css` prop is a good candidate for auto-targeting because we know that this object is intended to be used as emotion styles. We can't automatically assess that for just any object returned from a function though - however, it's possible to get source maps for those, you just have to wrap those object styles with `css`, like this:
```diff
export default () => (
<div>
    <div css={{ color: 'red' }} />

-    <div css={() => ({ color: 'blue' })} />
+    <div css={() => css({ color: 'blue' })} />
  </div>
);
```

**Comment by marchaos** [comment]
Hey. I've attempted to get sourceMaps working with the above suggestion using css() like so 

`<input
       css={() => css({
                color: 'red'
            })}
...
`

but this ends up with this class + styles: 

`.css-1nrz2np-Comp {
    css-hz0fof-Comp -Comp : ;
}
`
