### ISSUE TITLE
[Question] will `useMemo` and separating dynamic and static css help perf?

### ISSUE THREAD

**Issue by xiaofan2406** [emotion-js/emotion#1239]
### Problem description

Say I am creating a component with some base static css that does not change with props, and some css based on props;

```jsx
const Button = ({ color }) => 
  <button 
    css={css`
      border-none;
      color: ${color};
    `} 
  />
```

I have the following implementations with  `useMemo`:

**Implementation A**
```jsx
const base = css`
  border-none;
`;

const Button = ({ color }) => {
  const dynamic = useMemo(
    () => css`
      color: ${color};
    `,
    [color]
  );

  return (
    <button
      css={css`
        ${base};
        ${dynamic};
      `}
    />
  );
};
```

**Implementation B**
```jsx
const Button = ({ color }) => {
  const all = useMemo(
    () => css`
      border-none;
      color: ${color};
    `,
    [color]
  );

  return (
    <button css={all} />
  );
};
```

### Questions

- Which one of the implementation is actually helping perf-wise?
- What happens if the `Button` also takes a `className` prop, will that change anything?

**Comment by Andarist** [comment]
The question is - do you experience perf problems?

**Comment by Andarist** [comment]
We have not received any response since Februrary so I'm going to close this. Please do not be overly concerned with perf unless you really hit some bottleneck - emotion is quite fast (we care about perf).
