### ISSUE TITLE
Namespacing themes

### ISSUE THREAD

**Issue by r-walsh** [emotion-js/emotion#1241]
- `emotion` version: 10.0.7 (core, styled, babel-plugin, theming)
- `react` version: 16.8.3

**Relevant code:**

```typescript
// theme/index.ts
import styled, { CreateStyled } from '@emotion/styled';

export interface Theme {
  color: {
    // ...colors
  };
  dimensions: {
    headerHeight: string;
  };
}

export const theme: Theme = {
  color: {
    // colors...
  },
  dimensions: {
    headerHeight: '80px',
  },
};

export default styled as CreateStyled<Theme>;

// Foo.tsx
import { Menu } from 'antd';
import * as React from 'react';

import styled from 'theme';

const StyledMenu = styled(Menu)`
  height: ${props => props.theme.dimensions.headerHeight};
`;

export const Foo = () => <StyledMenu>{/* children */}</StyledMenu>;
```

**What you did:**

Attempted to render the above

**What happened:**

`Uncaught TypeError: Cannot read property 'headerHeight' of undefined`

**Reproduction:**
https://codesandbox.io/s/wq6m7qppq8?fontsize=14

Delete the `color` in the `StyledMenu` and the error goes away.

**Problem description:**

I believe this is due to [Ant Design](https://github.com/ant-design/ant-design) providing their own `theme` prop to components which overwrites the one provided by `emotion-theming`.

**Suggested solution:**

Ideally there would be same way to control the namespace of props passed to components. Perhaps allow `ThemeProvider` to accept a `themePropName` prop which defaults to `'theme'` but allows users to specify a custom name for the theme prop?

**Comment by Andarist** [comment]
This is basically why we believe `theme` should not be a core part of emotion. People want it though so it will stay here, but we don't plan to introduce any namespacing features to it. We believe that this can be cleanly handled through hooks as described here https://github.com/emotion-js/emotion/pull/973 . In the upcoming v11 you should use this approach for library-level themes, in combination with https://github.com/emotion-js/emotion/pull/1577 (just for convenience).
