### ISSUE TITLE
Labels issue with nested selectors

### ISSUE THREAD

**Issue by nevf** [emotion-js/emotion#1243]
I'm using the Framework agnostic version "emotion": "^10.0.7",

Not using React.

````
const treeIcon = css`
    label: treeIcon;
    ....
`

const treeItemContainer = css`
    label: treeItemContainer;

    .some-nested-class {
        ${treeIcon};
    }
   ...
`
````

Chrome Dev tools:
````
<div class="css-1qdqt31-treeItemContainer-treeIcon">
  <div class="some-nested-class">
  </div>
</div>
````

`treeIcon` should not be included in `css-1qdqt31-treeItemContainer-treeIcon"`

Labels in any nested selector result in the nested selectors label being appended to it's parent label instead of being in the nested selector's element.

The response may well be that label's can't be used in nested selectors and that's ok, however it would be nice of they did work.

**Comment by Andarist** [comment]
Labels are extracted from a "plain" styles string - as you have interpolated one css class name into another you have ended with styles like this:
```
  label: treeItemContainer;
  border: 1px solid black;

  .some-nested-class {
    
  label: treeIcon;
  color: hotpink;
;
  }
```
What I mean by "plain" string is that label extraction doesn't read this as CSS - it doesn't track nesting etc and it just gathers all labels available in the style string and concatenates them.

Labels are meant to be used just as a dev-only feature, helping you to track an origin of the composed classes and as such, I believe this serves its purpose - losing that label would be like losing helpful information. 

I agree that this looks weird at first when looking at your given example, but after consideration, I believe this is fine and expected.
