### ISSUE TITLE
[Question] Empty style[data-emotion] in production build

### ISSUE THREAD

**Issue by radreamer** [emotion-js/emotion#1248]
- `emotion` version: 9.2.12
- `react` version: 16.6.3

![screen shot 2019-02-27 at 4 23 51 pm](https://user-images.githubusercontent.com/16123063/53497105-23262880-3aac-11e9-928e-f72211d5e90d.png)

I want to see emotion styles on production, but I see only empty `<style data-emotion></style>`. How is it possible that there is no CSS code, but styles works?

**Comment by Andarist** [comment]
This is because emotion in production uses [`insertRule`](https://developer.mozilla.org/pl/docs/Web/API/Stylesheet/insertRule) API which is faster than creating text nodes.

**Comment by radreamer** [comment]
@Andarist thank you! is it possible to insert this style[data-emotion] tag into other than head location, I need it for shadow dom

**Comment by Andarist** [comment]
@radreamer https://emotion.sh/docs/cache-provider

**Comment by mrsum** [comment]
Is it possible to get all css styles programatically at production build?  I need styles for PDF generation.

**Comment by Andarist** [comment]
@mrsum 
```js
[...document.querySelectorAll('[data-emotion]')].flatMap(({ sheet }) => [...sheet.cssRules].map(rules => rules.cssText)).join('\n')
```

**Comment by FezVrasta** [comment]
While I'm here I'm going to close the issue since it has been answered already, I hope you guys don't mind.

**Comment by cristianoccazinsp** [comment]
@mbrevda I believe @Andarist solution is better as it does not involve messing up with emotion and its caching, nor making it slower.

**Comment by sarink** [comment]
@mbrevda this still does not work in production (it does in development though) https://github.com/emotion-js/emotion/issues/2902

**Comment by FN-FAL113** [comment]
> @mrsum
> 
> ```js
> [...document.querySelectorAll('[data-emotion]')].flatMap(({ sheet }) => [...sheet.cssRules].map(rules => rules.cssText)).join('\n')
> ```

thanks, was looking for this, just used a normal map operation instead of flatmap to simulate a minified resource which still works fine

**Comment by Lemonreds** [comment]
good.

**Comment by ManoMangaldas** [comment]
> For anyone else coming via google, for server-side PDF generation or other post-processing of the html, here's how to allow all styles to be generated as text:
> 
> ```js
> import createCache from '@emotion/cache'
> import {CacheProvider} from '@emotion/react'
> 
> const emotionCache = createCache({
>     key: 'css',
>     container: doc.head, // pointing to <iframe>.document in this case, ymmv
>     prepend: true, // ymmv
>     speedy: false // <--- key setting
>   })
> 
>  <CacheProvider value={emotionCache}>
> {children}
> </CacheProvider>
> ```

Thank you
