### ISSUE TITLE
[eslint-plugin-emotion] the syntax-preference rule does not check css props

### ISSUE THREAD

**Issue by Nouzbe** [emotion-js/emotion#1253]
- `emotion` version: 10.0.7
- `react` version: 16.6.0

**Relevant code:**

```javascript
// eslintrc.js
rules: {
  ...
  'emotion/syntax-preference': ['error', 'string'],
  ...
}

// MyComponent.js
// Despite using the object syntax, the following line doesn't raise an ESLint error
const MyComponent = () => <div css={{background: 'red'}} />;

```

**Problem description:**

The [syntax-preference](https://github.com/emotion-js/emotion/blob/master/packages/eslint-plugin-emotion/src/rules/syntax-preference.js) ESLint rule currently works for `styled` but not with the CSS prop.

**Suggested solution:**

It would be nice if this rule could also enforce a syntax choice for projects using CSS props.

**Comment by Andarist** [comment]
This has been implemented in https://github.com/emotion-js/emotion/pull/1659 and will be a part of upcoming v11 release.
