### ISSUE TITLE
Duplicate class name generated when media query was used

### ISSUE THREAD

**Issue by itszero** [emotion-js/emotion#1255]
- `emotion` version: 10.0.7
- `react` version: 16.8.3

**Relevant code:**

```javascript
import { css } from '@emotion/core'

const styles = {
  mediaQuery: css`
    @media only screen {
      background-color: red;
    }
  `
}

const MyComponent = ({ className }) => {
  return <div className={className} css={css({ color: 'white', fontSize: '2em', fontWeight: 'bold' })}>Hello</div>
}

class App extends Component {
  render() {
    return (
      <div className="App">
        <MyComponent css={styles.mediaQuery}/>
      </div>
    );
  }
}
```

**What you did:**

Created a media query style with `css` and pass it into a component to override styling.

**What happened:**

I see duplicate classnames being generated in the style tags.

```
<style data-emotion="css">@media only screen{.css-1vu9dni-mediaQuery{background-color:red;}}</style>
<style data-emotion="css">.css-13cq4ul-MyComponent-mediaQuery{color:white;font-size:2em;font-weight:bold;}</style>
<style data-emotion="css">@media only screen{.css-13cq4ul-MyComponent-mediaQuery{background-color:red;}}</style>
```

Noticed that `.css-1vu9dni-mediaQuery` and `.css-13cq4ul-MyComponent-mediaQuery` and actually the same rule.

**Reproduction:**

I can't get codesandbox to work with the css prop babel preset so here's a git repo: https://github.com/itszero/emotion-10-bug

It's just `create-react-app` ejected and added the css prop plugin. See the `App.js` for the code.

**Problem description:**

The classname should not be generated twice. I think this is probably happened in the `css` prop consolidation process where we injected the style directly instead of just using the classname.

**Suggested solution:**

Not sure. I don't have enough context about how the classname conslidation process was implemented.

**Comment by Andarist** [comment]
I'm afraid this is just how emotion works - when you use css prop on a composite component (yours `MyComponent`) we don't know if it will render an emotion-controlled component so we need to eagerly inject those outer styles into DOM/CSSOM. Later the inner component receives the generated className, based on that it retrieves registered for it styles, composes it with whatever you have passed into `css` prop there and creates whole new styles which in this example share the same single media rule, but the hash of the overall styles has changed and thus new rules are being inserted. This shouldn't yield any meaningful perf problems though. Also - the same can be observed on CodeSandbox: https://codesandbox.io/s/emotion-zzwez
