### ISSUE TITLE
object style css not working with animations

### ISSUE THREAD

**Issue by bitzkrieg** [emotion-js/emotion#1259]
- `emotion` version: 10.0.7
- `react` version: 16.8.3

**Relevant code:**

```javascript
/** @jsx jsx */
import { jsx, css, keyframes } from "@emotion/core";
import ReactDOM from "react-dom";

const kf = keyframes({
  from: {
    color: "back"
  },
  to: {
    color: "white"
  }
});

const blinkString = css`
  animation-name: ${kf};
  animation-duration: 1s;
  animation-iteration-count: infinite;
  animation-direction: alternate;
`;

const blinkObject = css({
  animationName: kf,
  animationDuration: "1s",
  animationIterationCount: "infinite",
  animationDirection: "alternate"
});

function App() {
  return (
    <div>
      <div css={blinkString}>I blink!</div>
      <div css={blinkObject}>I should blink, but do not!</div>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**What you did:**

Used object style CSS with animations.

**What happened:**

No animation :(

**Reproduction:**

https://codesandbox.io/s/mqoow6yq1j

**Problem description:**

Seems like either there is a problem with animations when using object style or the docs need to be updated to show how to use animations with object style.

**Suggested solution:**

Not sure...

**Comment by ElliotChong** [comment]
Docs need to be updated indeed, but it seems like if you use the Keyframe's `toString()` method it will work correctly.

```
animationName: kf.toString(),
```

```
animationName: `${kf.}`,
```

**Comment by Andarist** [comment]
Seems like a bug in emotion, gonna fix it tomorrow - thanks for bringing this up.

**Comment by dinoturic** [comment]
It seems like the fix has not been made for template literals.
If one is to create an emotion component like this using template literals, the keyframe is still not passed properly and does not show the animation. Using `.toString()` only works in this case, but can it be fixed so that template literals, like objects can use this without `toString` function?

Example:
```javascript
const BackgroundContainer = styled.div(({fadeIn, theme: {customOverlay}}) => `
  animation: ${fadeIn} 1s ease 1;
  background: ${customOverlay.background};
  height: 100%;
  width: 100%;
`);
```
Also no info about this in the docs.
