### ISSUE TITLE
Styling Global component using styled approach is not possible. 

### ISSUE THREAD

**Issue by AlexanderProd** [emotion-js/emotion#1262]
I was trying to create a Global style using styled on the `Global` component. But it seems like this is not possible yet. I feel like this would be a nice feature to add since I prefer the styled approach to using inline styles with the `Global` component. 

But doing so results in an error in the browser console saying 

I'm using emotion with `create-react-app`
- `emotion` version: 10.0.7
- `react` version: 16.8.3

**Relevant code:**

```javascript
import styled from '@emotion/styled'
import { Global } from '@emotion/core'

export const GlobalStyle = styled(Global)`
  * {
    background-color: blue;
  }
`
```

**What you did:**
Applied style to `Global` component using `styled`
```javascript
export const GlobalStyle = styled(Global)`
  * {
    background-color: blue;
  }
`
```

**What happened:**
Error in browser console: 
`It looks like you're using the css prop on Global, did you mean to use the styles prop instead?`

**Reproduction:**
Use styled on Global component. 

**Suggested solution:**
Add functionality to use styled on Global component.

**Comment by piavgh** [comment]
@AlexanderProd : Hi, you closed this issue yourself. So how did you solve this?

**Comment by piavgh** [comment]
Thank you. Basically this is using css as in the official guide.
I thought that there is a way of using "styled" approach

**Comment by eguitler** [comment]
Did anyone found a more elegant solution? I'll choose this I think but it doesn't taste good.

**Comment by eguitler** [comment]
I found a solution! I hope this helps the next who need it.

```
import { Global } from "@emotion/react";
import { css } from "@emotion/react";

const GlobalStyles = css`
    body {
         background-color: red;
    }
`

function App() {
    return (
        <Router>
            <Global styles={GlobalStyles} />
            <Switch>
                <Route exact path="/" component={Home} />
            </Switch>
        </Router>
    );
}

export default App;
```

**Comment by GaganZee** [comment]
Hi 
When using theme variables with global styles we get a Typescript error:
`No overload matches this call.
  Overload 1 of 2, '(template: TemplateStringsArray, ...args: CSSInterpolation[]): SerializedStyles', gave the following error.
    Argument of type '({ theme }: { theme: any; }) => any' is not assignable to parameter of type 'CSSInterpolation'.
  Overload 2 of 2, '(...args: CSSInterpolation[]): SerializedStyles', gave the following error.
    Argument of type 'TemplateStringsArray' is not assignable to parameter of type 'CSSInterpolation'.
      Type 'TemplateStringsArray' is missing the following properties from type 'CSSInterpolation[]': pop, push, reverse, shift, and 6 more.ts(2769)`
    

Use case:
`import { Global, css } from "@emotion/react";

const GlobalStyle = css`
body {
        background: ${({ theme }) => theme.colors.primaryBlack};
        font-family: ${({ theme }) => theme.font.rootFontFamily};
        font-weight: 400;
        color: ${({ theme }) => theme.colors.primaryWhite};
        box-sizing: border-box;

        div#app {
            height: 100vh;
            width: 100vw;
        }
    }
`;`
