### ISSUE TITLE
[Question] - Why not extract static css properties to one css file?

### ISSUE THREAD

**Issue by omerman** [emotion-js/emotion#1263]
First of all, great library and concepts! thanks!

I'm not 100% sure but wouldn't the it be optimized and easier to cache if something like this
was going on:

File1
```
const StyledDiv = styled('div')({
flex: 1,
})
```

File2
```
const StyledDiv = styled('div')({
display: 'flex',
flexDirection: 'column'
})
```

File3
```
const StyledDiv = styled('div')({
display: 'flex',
flexDirection: 'column'
})
```

would opt something like this:

index.html
```
<link rel="stylesheet" type="text/css" href="emotion_somehash.css">
```

emotion_somehash.css
```
.asd {
flex: 1,
}

.asd2 {
display: 'flex',
flexDirection: 'column'
}
```

int the output js
```
....styled('div')('.asd')
....styled('div')('.asd2')
....styled('div')('.asd2') // since it has the same props, it can even get the same class..
```

** Offcourse if there are any dynamic properties going on, do not extract them, extract only the static props.

Thanks again for the amazing library

**Comment by Andarist** [comment]
We believe that static extraction is just not worth it and also has its drawbacks (such as lack of tree-shakeability, auto lazy-loading etc).

Nothing like this is currently planned. Sorry!
