### ISSUE TITLE
CacheProvider options link is broken in the documentation.

### ISSUE THREAD

**Issue by DesignerDave** [emotion-js/emotion#1265]
**Problem description:**
The link to CacheProvider options gives a 404-esque message. https://emotion.sh/docs/cache-provider

**Suggested solution:**
Instead of linking here: https://emotion.sh/docs/cache#options
It should probably link here: https://emotion.sh/docs/@emotion/cache#options

**Comment by Andarist** [comment]
I believe this particular issue has been fixed. I can access https://emotion.sh/docs/@emotion/cache#options and it's linked to correctly from https://emotion.sh/docs/cache-provider
