### ISSUE TITLE
Platform.select support for react-native? 

### ISSUE THREAD

**Issue by mgcrea** [emotion-js/emotion#1269]
- `emotion` version: `^10.0.9`
- `react` version: `^16.8.4`

**Relevant code:**

```javascript
export const styles = StyleSheet.create({
  inputContainer: {
    width: '100%',
    ...Platform.select({
      ios: {
        shadowColor: 'black',
        shadowOffset: {height: 0, width: 0},
        shadowOpacity: 0.1,
        shadowRadius: 4
      },
      android: {
        elevation: 1
      }
    })
  }
});
```

**What you did:**

I'm looking for a way to easily implement the following `Plateform.select` using `@emotion/native`. For single props it's quite obvious with string interpolation (eg. `color: ${Platform.select({ios: 'red', android: 'blue'})};`) but for multiple props is there a way to keep things clean?

**Suggested solution:**

One nice possible way to solve it could be to introduce a new media-query syntax: 

```jsx
const Wrapper = styled.View`
 @media android { background-color: red; }
 @media ios { background-color: blue; }
`
```

or 

```jsx
const Wrapper = styled.View`
 @platform android { background-color: red; }
 @platform ios { background-color: blue; }
`
```

Idea from https://github.com/styled-components/css-to-react-native/issues/46#issuecomment-319770415

Thanks!

**Comment by Andarist** [comment]
We don't plan anything like that. Truth to be told - we don't maintain native packages the same way we do core emotion. Native packages have been created by the community members, the core team doesn't have time capacity to work on it properly - we don't plan to remove them from this monorepo but we expect the community to step up and send us PRs for those packages if needed. We are happy to help, review etc. We just can't work actively on them.
