### ISSUE TITLE
Disable vendor prefixes in next.js app

### ISSUE THREAD

**Issue by shashkovdanil** [emotion-js/emotion#1274]
How to disable vendor prefixes? I tried to disable them using `CacheProvider` and `createCache`, but I see FOUC. `CacheProvider` does not work with Next.js SSR. Help please.

**Comment by tkh44** [comment]
Here is a working example. https://codesandbox.io/s/hello-world-7wvmp

**Comment by FezVrasta** [comment]
I'm going to close the issue as "support" or "question", please next time use StackOverflow for this kind of questions, it's the best place to get help for own code issues.
