### ISSUE TITLE
Emotion core is bundled even though it is not yet used / referenced

### ISSUE THREAD

**Issue by raveenakothapally** [emotion-js/emotion#1279]
- `emotion` version: ~7.3.4
- `react` version: ~16.8.4

**Relevant code:**

##### Component
```javascript
import React, { Suspense } from "react";
import * as ReactDOM from "react-dom";
import Loader from "~/components/loader"; // Does not use any css prop yet

const App = React.lazy(() => import("./screens/app")); // Uses css props / emotion

function AppRoot() {
  return (
    <Suspense fallback={<Loader />}>
      <App />
    </Suspense>
  );
}

ReactDOM.render(
  <AppRoot />,
  document.getElementById("web-root")
);

```

##### Babel Configuration
```babelrc
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "browsers": [">0.25%", "not ie 11", "not op_mini all"]
        },
        "useBuiltIns": "usage",
        "modules": false
      }
    ],
    "@babel/preset-react",
    [
      "@emotion/babel-preset-css-prop",
      {
        "autoLabel": true,
        "labelFormat": "[local]",
        "useBuiltIns": false,
        "throwIfNamespace": true
      }
    ]
  ],
  "plugins": [
    "react-hot-loader/babel",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-runtime",
    [
      "transform-inline-environment-variables",
      {
        "include": ["NODE_ENV"]
      }
    ]
  ],
  "env": {
    "production": {
      "presets": [
        [
          "@emotion/babel-preset-css-prop",
          {
            "autoLabel": false,
            "useBuiltIns": false,
            "throwIfNamespace": true,
            "sourceMap": false
          }
        ]
      ]
    },
    "development": {
      "presets": [
        [
          "@emotion/babel-preset-css-prop",
          {
            "autoLabel": true,
            "labelFormat": "[local]",
            "useBuiltIns": false,
            "throwIfNamespace": true,
            "sourceMap": true
          }
        ]
      ]
    }
  }
}

```

**What you did:**
Start the app and navigate to app home page

**What happened:**
Because of automatic code splitting with the usage of dynamic imports and parceljs, I see two javascript files loaded. The first is the `index.js` bundle which on initial on-load and then `app.js` which is coming from the code split and dynamic import.

The issue is that both these bundles have `babel-core` and all other babel specific dependencies bundled.

**Reproduction:**

**Problem description:**
1. All code split files have `emotion` specific code (emotion is bundled with app code)
2. Code split files that do not depend on emotion also bundles emotion core library. This will be a problem for the initial page load when app decides not to bring in any emotion dependencies and don't have any references to it or the css props.

**Suggested solution:**
1. I don't think the bundles that do not use emotion should include its bundle
2. This may be a general babel question that there should only be one `emotion` specific dependencies bundled across all code split files if they all depend on it.

**Comment by Andarist** [comment]
I think it doesn't matter if css is used - if you are using `@emotion/babel-preset-css-prop` on all files then all of them will use `jsx` from emotion rather than React.createElement.

**Comment by raveenakothapally** [comment]
@Andarist,

IMHO `babel-preset-css-prop` should replace `React.createElement` with `jsx` only in files that depend on it (`css` prop).
It seems to have a side-effect the way it is implemented today that it replaces in all files. Clients of `babel-preset-css-prop` could be expecting the replacements only for the ones that use `css` prop.

**Comment by Andarist** [comment]
With how Babel plugins operate independently to each other this is really tricky to do - I've looked into it lately and assessed that is just not worth it and would probably be buggy as hell.

That's a price you are paying for using this preset - it has been created only because people were vocal that they want to have this automated. We recommend using plain jsx pragma - that way you control which files use it and you wouldn't suffer from over-transpilation like in this case here.
