### ISSUE TITLE
How to easily add (third party) classNames?

### ISSUE THREAD

**Issue by baba43** [emotion-js/emotion#1282]
How can we use emotion together with external CSS frameworks like Bulma? 

The obvious problem is that I can't pass `className` to a styled component, because it gets overriden by emotion. Is there an easy way to compose those classes or maybe add *className inheritance* as an opt-in default behaviour?

**Comment by FezVrasta** [comment]
use provided `className` is not overridden by Emotion, it gets merged with.

**Comment by Andarist** [comment]
What @FezVrasta said, we don't override passed className.
