### ISSUE TITLE
Missing trailing semicolon breaks classes concatenation

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#1284]
- `emotion` version: 10
- `react` version: any

**Relevant code:**

```javascript
className={cx(
  css`
    color: red // missing semicolor here
  `,
  css`
    background-color: black;
  `
)}
```

**Reproduction:**

https://codesandbox.io/s/nk3pwpk1mj

**Problem description:**

The missing semicolon is not added between the two concatenated styles, leading to invalid CSS.

**Suggested solution:**

Ideally, a semicolon (`;`) should be automatically added between CSS fragments to make sure the final CSS is still valid.

A possible solution would be to put a `styles +=  ';'` at line 324 of `@emotion/serialize/src/index.js`

**Comment by Leland-Kwong** [comment]
CSS requires a semicolon for each rule https://stackoverflow.com/questions/11939595/leaving-out-the-last-semicolon-of-a-css-block. I feel like this is expected behavior and should be left alone. If anything maybe a warning for missing semicolons?

**Comment by FezVrasta** [comment]
According to W3C, trailing semicolon at the end of a rule block is optional.

You can verify it using the validation service:
https://jigsaw.w3.org/css-validator/#validate_by_input

with this snippet:

```css
.foo {
  color: red
}
```

**Comment by Leland-Kwong** [comment]
I see what you're saying now. Each one of those css declarations is technically considered a block, so no semi should be allowed there. I still feel like optionally adding semicolons just leads to potential bugs in the future.

**Comment by avin-kavish** [comment]
I don't agree. I think we should stick to the css specification. It is causing the transition from Sass/CSS to CSS-in-JS harder because it's instinctive to leave out the semi-colon at the end of a declaration. Not only does it break on `cx`, it is also broken on `css`

i.e. this is broken

```
const appClassName = css`
  font-family: sans-serif;
  text-align: center             // <-- Outputs: `text-align: centerlabel:appClassName`
`
```

[Code Sandbox](https://codesandbox.io/s/emotion-issue-template-5iy2d)

**Comment by Andarist** [comment]
This has been fixed lately in https://github.com/emotion-js/emotion/pull/1560
