### ISSUE TITLE
Get theme props in an object

### ISSUE THREAD

**Issue by yashhy** [emotion-js/emotion#1287]
- `emotion` version: 9.2.3
- `react` version: 16.6.3

I use [react-popup](https://react-popup.elazizi.com/component-api/) library in which there is a use case to pass styles as an object. The code goes like...

```javascript

// Setting the color like below from the object
const overlayStyle = {
    color: colors.border.active // <-- here I need to have access to the theme
};

// Need something like 
// const overlayStyle = {
//    color: `${props => props.theme.colors.border.active }` // <-- here I need to have access to the theme
// };

render(<Popup 
    trigger={<button>Trigger</button>} 
    position="top left"
    overlayStyle={overlayStyle}> // this expects an object
    ...
</Popup>) 
```

**Question:** Is it possible to get `theme` in the object? I referred [advanced](https://emotion.sh/docs/theming) docs where it is suggested to use `styled.div` and have a template string, which I cannot use in this case.

**Comment by VladimirPittner** [comment]
Hi, I think you should be able to do something like this

```js
const overlayStyle = theme => {
    color: theme.colors.border.active // <-- here you have access to theme
};

render(<Popup 
    trigger={<button>Trigger</button>} 
    position="top left"
    overlayStyle={overlayStyle(theme)}> // here you need to pass the theme to the function which returns object
    ...
</Popup>) 
```
Also you need to provide the theme to your component ;)

**Comment by Andarist** [comment]
@VladimirPittner thanks for replying! Closing this because the answer is given and it's a good one 😉
