### ISSUE TITLE
issue with Run button in benchmarks

### ISSUE THREAD

**Issue by lstkz** [emotion-js/emotion#1294]
https://github.com/emotion-js/emotion/tree/master/scripts/benchmarks

Open any benchmark https://benchmarks.emotion.sh and click RUN. Nothing happens. It only works if you click on edges/border.
Video https://take.ms/PaDCJ

Chrome 73

**Comment by Andarist** [comment]
This has not been touched for quite a long time and I can't reproduce this now. Everything seems to be OK with that button. Thanks for the report though! I appreciate it.
