### ISSUE TITLE
Vulnerability in dependency js-yaml in version 9

### ISSUE THREAD

**Issue by yairkukielka** [emotion-js/emotion#1297]
- `emotion` version: 9.2.12
- `react` version: 16.8.2

**What you did:**
Run `npm audit`

**What happened:**
![advisory](https://user-images.githubusercontent.com/11599360/55264391-69001900-5231-11e9-961e-9c686b10710d.png)

**Problem description:**

This is an npm security advisory for js-yaml, which is a dependency of a dependency of a dependency: https://www.npmjs.com/advisories/788

All other dependencies in the chain have been updated with the new version of js-yaml, so babel-plugin-emotion is the last one to update.

**Suggested solution:**
Would it be possible to release another version (of emotion version 9) that depends on `babel-plugin-macros` version 2.5.1? That version of `babel-plugin-macros` does not have the vulnerability issue.

**Comment by vospascal** [comment]
more info
https://snyk.io/vuln/SNYK-JS-JSYAML-173999
https://snyk.io/vuln/SNYK-JS-JSYAML-174129

 Introduced through: babel-plugin-emotion@10.0.9, @emotion/styled@10.0.10, emotion@10.0.9, @emotion/core@10.0.10
  From: babel-plugin-emotion@10.0.9 > babel-plugin-macros@2.5.0 > cosmiconfig@5.0.7 > js-yaml@3.12.0
  From: @emotion/styled@10.0.10 > babel-plugin-emotion@10.0.9 > babel-plugin-macros@2.5.0 > cosmiconfig@5.0.7 > js-yaml@3.12.0
  From: emotion@10.0.9 > babel-plugin-emotion@10.0.9 > babel-plugin-macros@2.5.0 > cosmiconfig@5.0.7 > js-yaml@3.12.0

**Comment by benpolinsky** [comment]
Not sure why this hasn't been fixed, but you can update around it:

`npm install --save-dev babel-plugin-macros@2.5.1`

**Comment by FezVrasta** [comment]
I think v9 is not maintained anymore, but I may be wrong.

**Comment by Andarist** [comment]
Yes - we don't plan to backport anything to emotion@9. You can upgrade to emotion@10 which doesn't suffer from this problem.
