### ISSUE TITLE
Ignore import of tagged function in babel plugin

### ISSUE THREAD

**Issue by danielhusar** [emotion-js/emotion#1302]
Hi!

We have a custom wrapper around `styled` for accessibility, but this broke the babel plugin as import of `styled` no longer match whitelisted imports in babel plugin.

Would you be interested in adding an option for ignoring path, and checking only tagged function?
So all `css` `styled` and `keyframes` tagged templates will get processed?

**Comment by Andarist** [comment]
This will be solved by https://github.com/emotion-js/emotion/pull/1220 . If you are interested in helping us move this PR forward - we'd appreciate all the help we can get.
