### ISSUE TITLE
Suggestion: Reimplement styled to make react element tree cleaner

### ISSUE THREAD

**Issue by TerenceZ** [emotion-js/emotion#1307]
- `emotion` version: 10.0.10
- `react` version: 16.8.5

**Problem description:**

Currently, if we use `styled(Element)` to style components, it will wrap with two consumers. When the tree goes deep, it will be messed up.

**Suggested solution:**

styled-components seems to reimplement using hooks internally (https://github.com/styled-components/styled-components/pull/2390), which leads to be more efficient and a cleaner react tree.

**Comment by FezVrasta** [comment]
#967

**Comment by Andarist** [comment]
As mentioned - #967 will solve this. This will be part of the upcoming emotion@11
