### ISSUE TITLE
documentation: example babel-config for react + babel-preset-css-prop

### ISSUE THREAD

**Issue by PutziSan** [emotion-js/emotion#1312]
**Problem description:**
I cannot find an example of how `@emotion/babel-preset-css-prop` and `@babel/preset-react` should be included in a babel configuration. Or should `@babel/preset-react`  at all?

**Suggested solution:**
Currently my `babel.config.js` looks like this:

```javascript

const emotionPreset = require("@emotion/babel-preset-css-prop").default;
const reactPreset = require("@babel/preset-react").default;

module.exports = api => {
  // always recompile config
  api.cache.never();

  return {
    presets: [
      ["@babel/preset-react", { useBuiltIns: true }],
      // emotions preset must run BEFORE reacts preset to properly convert css-prop. 
      // Since babels preset-ordering runs reversed (from last to first), it has to be after reacts preset.
      ["@emotion/babel-preset-css-prop", { useBuiltIns: true }],
    ],
    // ... other config
  };
};
```
I think a hint similar to this in the get-started-documentation (depending on how it really should look in the end) would be quite good:

```diff
{
  "presets": [
-   "@babel/preset-react",
+   "@emotion/babel-preset-css-prop",
    // ... other presets
  ],
  // ... other babel-config 
}
```

**Comment by briandipalma** [comment]
Is this correct should preset-react be removed from your babel config? If so I agree this should be documented.

**Comment by Andarist** [comment]
As far as I know `@babel/preset-react` can be used together with `@emiotion/babel-preset-css-prop` - it's just that our preset has to come AFTER React's preset. This is described here:
https://github.com/emotion-js/emotion/blob/master/packages/babel-preset-css-prop/README.md#usage
