### ISSUE TITLE
Why haven't we switched from <Context.Consumer/> to `useContext` ?

### ISSUE THREAD

**Issue by Dudeonyx** [emotion-js/emotion#1314]
- `emotion` version: 10.0.10
- `react` version: 16.8.6

**Problem description:**
Honestly I am sick and tired of seeing a polluted react tree full of nested <Context.Consumer/>, it reminds me too much of callback hell.

I know there is an ongoing discussion on a new hooks API but rather than re-inventing the wheel all at once why not take an approach similar to what `react-redux` is doing and internally rewrite `emotion` to use hooks while maintaining the same public API?

Particularly, `useContext` would finally convince a lot of devs who I know have avoided `emotion` and `styled-components` because of the messed up react tree.

I know switching to useContext isn't hard because I did it myself by heading into my node_modules, ctrl + F '.Consumer>' and replacing as needed with `useContext`.
Changing stuff like this
```js
var Emotion = withEmotionCache(function (props, cache, ref) {
  if (typeof props.css === 'function') {
    return createElement(ThemeContext.Consumer, null, function (theme) {  // <- this
      return render(cache, props, theme, ref);
    });
  }

  return render(cache, props, null, ref);
});
```

to this

```js
var Emotion = withEmotionCache(function (props, cache, ref) {
  var theme = useContext(ThemeContext);  // <- this
  if (typeof props.css === 'function') {
    return render(cache, props, theme, ref);
  }

  return render(cache, props, null, ref);
});
```
 And I know fuck all about the internals of `emotion` but it worked and my react tree has never looked so readable.

Not to mention `useMemo` would be an easy way to memoize stuff and speed things up.

**Comment by FezVrasta** [comment]
#967 is trying to address this

**Comment by FezVrasta** [comment]
I'm going to close this and point you to #1307. I'll try to keep #1307 the issue of reference for this kind of requests (Hooks reimplementation of the Emotion components).

**Comment by corysimmons** [comment]
@Dudeonyx Can you `npm publish` your solution?

>Particularly, useContext would finally convince a lot of devs who I know have avoided emotion and styled-components because of the messed up react tree.

styled-components v5 fixed this and it's really nice: https://medium.com/styled-components/announcing-styled-components-v5-beast-mode-389747abd987

![image](https://user-images.githubusercontent.com/224636/59902540-7eb65200-93cc-11e9-9abf-1ea99d75eb74.png)
