### ISSUE TITLE
cx should return as undefined when yielding an empty string

### ISSUE THREAD

**Issue by kylemh** [emotion-js/emotion#1322]
- `emotion` version: latest
- `react` version: latest

**Relevant Code / Problem Description:**

```javascript
const shouldHaveClass = false;

return <span className={cx({ 'class': shouldHaveClass })}>Yo</span>
```

this will yield `<span class>Yo</span>` in the DOM when I'd expect it to yield `<span>Yo</span>`. I realize this is the behavior of browsers, but I feel like we could improve upon it.

**Reproduction:**
https://codesandbox.io/s/1o6km8ypvq

**Also Relevant:**
https://github.com/JedWatson/classnames/issues/182
https://github.com/JedWatson/classnames/pull/183

It seems as though Jed is worried about ever shipping the breaking change, but I thought I'd bring it up here in case Emotion is more willing.

**Comment by Andarist** [comment]
Thanks for the report! We'll consider this as part of the upcoming emotion@11. No guarantees though that this will get in - the clean DOM would be nice, but that vanilla `cx` has at the moment guaranteed string return type. Seems like most commonly this is used directly before passing the return value to the DOM sink, so this change might be OK - but I need to give this more thought.

**Comment by mitchellhamilton** [comment]
Sorry but I think we should leave the current behavior because the `emotion` package could be used outside of React and in places where you'd expect a string, the attribute also doesn't cause any problems so we would only be creating problems by changing this.
