### ISSUE TITLE
Nesting Generated Classes from cx

### ISSUE THREAD

**Issue by ahmedam55** [emotion-js/emotion#1323]
- `emotion` version: 10.0.9
- `react` version: 16.8.3

**Relevant code:**

```javascript
const toolTipArrowStyles = css`
  position: absolute;
  top: -${arrowHeight}px;
  left: 50%;
  transform: translate(-50%, 0);
  width: 15px;
  fill: #4e4e4e;

  .${tooltip}[data-at-top="true"] &,
  /* to keep arrow at the bottom when mouseleaves till it disappears*/
  .${cx(tooltip, tooltipHidden)}[data-at-top="true"] & {
    top: auto;
    bottom: -${arrowHeight}px;
    transform: translate(-50%, 0) rotate(180deg);
  }
`;
/////////////////////////////////////////////
// render method
<span className={cx(tooltip, { [tooltipHidden]: !isVisible })} ref={tooltipRef}>
          {props.text}
          <TooltipArrow />
</span>
```

**Problem description:**
So, here I'm combining two classes, one is the base and the other when it's hidden

I need to style the TooltipArrow accordingly from the class of the parent

My question is about this part: `${cx(tooltip, tooltipHidden)}`
It seems hacky, so, I was asking if there is a better way to achieve the same.

If that doesn't make sense, please check out this codesandbox: https://codesandbox.io/s/v6kop794k5

Thank you :)

**Comment by Andarist** [comment]
`&` refers to the current computed class name, more on this can be found in this issue - https://github.com/emotion-js/emotion/issues/1417 .

I would just advise here not to couple child & parent classes like this at all. Simplify things - you can do that for example like this:
https://codesandbox.io/s/emotion-css-in-js-issue-29954
