### ISSUE TITLE
Comments are stripped out before being passed to Stylis plugins, which breaks the stylis-rtl RTL plugin

### ISSUE THREAD

**Issue by Zenwolf** [emotion-js/emotion#1325]
- `emotion` version: 10.0.7
- `react` version: 16.6.0

**Relevant code:**

```javascript
const myCss = css`
    color: #000;
    /* @noflip */
    padding-right: 100px;
`;
```

**What you did:**
I used the `stylis-rtl` plugin with the Emotion cache and added a `/* @noflip */` comment to prevent a css property from being flipped. 

**What happened:**
The css property was flipped even though I used the required `/* @noflip */` comment to prevent flipping in a certain case. I tested the plugin itself, as well as the underlying cssjanus library and they all work as expected when the comment is used. I noticed that the CSS comment was already stripped out of the source when it was passed into the plugin. 

**Reproduction:**
https://codesandbox.io/s/7j00kmqzmj

**Problem description:**
Emotion seems to strip out the CSS comments before passing the content to the stylis plugins. Some Stylis plugins rely on comments to control their behavior. By stripping out the comments before passing the css to the plugins, that functionality is broken. For example, the `stylis-rtl` plugins relies on a `/* @noflip */` comment, either before a rule declaration, or before a property declaration, to prevent flipping that value. This is important for complex UIs that have several use cases where certain flipping behavior needs to be disabled in rtl languages in order to protect the integrity of the UI.

**Suggested solution:**
The css comments should remain intact when passed into the Stylis plugins, since various plugins depend on certain comments to change their behavior.

**Comment by ahmedam55** [comment]
Actually this is the case as you see below:
![Fullscreen_4_24_19__11_25_AM](https://user-images.githubusercontent.com/3703533/56640336-cd24ca00-6683-11e9-9a0f-12a0153a8c79.jpg)

**Comment by Zenwolf** [comment]
Thanks for responding, @ahmedam55 . When I put a breakpoint or console log out in the plugin's function https://github.com/FindHotel/stylis-rtl/blob/master/src/stylis-rtl.js#L19, I see what appears to be minified `content` with no comments passed into from the caller: `background-color:#444;color:#dedede;padding-right:100px;`. Could this potentially be due to an internal Emotion Stylis setting? I seem to remember seeing a `stylis_min` function running in the minfied Emotion code before the plugin received the content. Could that somehow be related?

**Comment by Zenwolf** [comment]
Here is a screenshot of the console.logs of all content passed into the `stylis-rtl` plugin:

![emotion-rtl-01](https://user-images.githubusercontent.com/354809/56687284-c77eb280-668a-11e9-9bfd-d65e83c2fc5c.jpg)

Here is the story source-code:
```js
/* @jsx jsx */

import { CacheProvider, css, jsx } from '@emotion/core';
import createCache from '@emotion/cache';
import React from 'react';
import { storiesOf } from '@storybook/react';
import stylisRtl from 'stylis-rtl';

const compCss = css`
    background-color: #444;
    color: #dedede;
    /* @noflip */
    padding-right: 100px;
`;

/*
NOTE: We should not see any left padding, but the @noflip comment
is stripped out before being passed to stylis-rtl.
*/
function App() {
    return (
        <div css={compCss}>
            <h1>Hello CodeSandbox</h1>
            <h2>Start editing to see some magic happen!</h2>
        </div>
    );
}

storiesOf('Language', module).add('rtl', () => (
    <CacheProvider value={createCache({ stylisPlugins: [stylisRtl] })}>
        <App />
    </CacheProvider>
));
```

**Comment by ahmedam55** [comment]
Maybe it has to do with the environment itself, as the example you posted on codesandbox showed the comments.

**Comment by ahmedam55** [comment]
Maybe it has to do with the environment itself, as the example you posted on codesandbox showed the comments.

**Comment by Zenwolf** [comment]
The interesting thing is that both environments end up with the incorrect output. I checked out the plugin source code, which contains a test that tests processing comments, and all the tests pass. 

@ahmedam55 are you able to use the stylis-rtl plugin with the `/* @noflip */` comment and see the correct output? In my example, the UI should never be indented on the left since the `padding-right` should never be flipped to `padding-left`.

**Comment by ahmedam55** [comment]
I checked the code of the library. It's checking for properties, and when emotion pass properties (which has the code of 1), it doesn't count comments as properties (which makes sense in this case), but it passes the whole css code intact in the step of preparation which has a code of -1.

**Comment by ahmedam55** [comment]
If you take a look below:
I replaced the plugin with the basic code that it does, and it worked perfectly fine.
![image](https://user-images.githubusercontent.com/3703533/56698799-32b89b00-6704-11e9-9a3b-730eb227bc7d.png)

**Comment by Zenwolf** [comment]
Hi @ahmedam55 , I think I figured out what is going on. I am using the `@emotion/babel-preset-css-prop` , and when I remove that, the comments are no longer stripped out. In the preset, I tried setting `cssPropOptimization: false` but that didn't seem to change anything. It looks like people cannot use the `@emotion/babel-preset-css-prop` if they want to support rtl using Stylis. Do you know of any way to turn off comment-stripping in `@emotion/babel-preset-css-prop`? Thanks for your help!

**Comment by Zenwolf** [comment]
It looks like comments were explicitly removed when using the babel plugin starting with this PR: https://github.com/emotion-js/emotion/pull/650. Unfortunately, this is not compatible with any Stylis plugin that depends on comments.

**Comment by ahmedam55** [comment]
To be honest, managing the code in comments wasn't a maintainable or readable way to begin with. I prefer the preprocessor approach with two files that change dir variable and compile into two files -rtl and -ltr and in the html file you import accordingly, a lot easier especially in debugging.

**Comment by Zenwolf** [comment]
Hi @ahmedam55 , I am working on some changes to add support for keeping comments when using the babel plugin. My plan is to have an option that allows users to opt-in to keep comments, with the default being the current behavior of removing all comments.

If you opt-in to keep comments, the minification will do the following:

1. Replace line breaks and multiple spaces in the multiline comments so that they are now standard CSS comments on one line.
2. Split on the line breaks.
3. Transform the non-standard single-line comments into standard CSS comment syntax so that they will work with the compression.
4. Rejoin all the lines.

The default setting would remove all the comments. However, if someone wants to use Stylis plugins that depend on CSS comments, or keep the comments for any reason, they could opt into keeping the comments in the babel plugin settings while still getting the other compression benefits.

Please let me know if this sounds OK. Thanks!

**Comment by Zenwolf** [comment]
Who can point me in the right direction to add a test for the new babel plugin feature in PR #1336 ?
