### ISSUE TITLE
Classnames for components created programmatically  

### ISSUE THREAD

**Issue by philholden** [emotion-js/emotion#1326]
- `emotion` version: 10.0.7
- `react` version: 16.8.4

**Relevant code:**

I may want to generate a family of components with related styles e.g. H1 ... H6 so I have a factory that can be used to generate related components. It is used like this (a bit like withComponent):

```javascript
const H2 = H1.create({displayName: 'H2', defaultProps: {textSize: 20}})
```

This is the function used create components that can create related copies:

```javascript
export function createComponentFactory(componentStyles, defaultAs = "div") {
  const create = statics =>
    Object.assign(
      forwardRef(({as = defaultAs, children, ...props}, ref) =>
        jsx(
          as,
          {
            css: adaptStyles(props, componentStyles),
            ref,
            ...filterProps(props),
          },
          children
        )
      ),
      {create: create, ...statics}
    );
  return create;
}
```

**What you did:**
When I create components via a factory they do not get labels on their classnames or source maps.

```javascript
const createH1 = createComponentFactory(h1ComponentStyles, "h1");
export const H1 = createH1({displayName: "H1"});
```

**What happened:**
```html
<h1 class="css-1e43i7y">
```

**Problem description:**
I am guessing that because the component is generated at runtime it is not statically analysable by babel.

**Suggested solution:**
It would be nice if there were some hint that would let babel-plugin-emotion know that H1 is a component so it can be labelled. This might be a comment.

**Comment by philholden** [comment]
Finding source maps do not work if css prop is used with a function.

```javascript
// no sourcemap
const Thing = () => <div css={() => ({color: 'blue'})}  />

// sourcemap works
const Thing = () => <div css={{color: 'blue'}}  />
```

**Comment by Andarist** [comment]
> Finding source maps do not work if css prop is used with a function.

This is why `css` is actually important at times, this particular case can be solved by just wrapping your return value in `css` call. 
```js
// this should get source maps
const Thing = () => <div css={() => css({color: 'blue'})}  />
```

As to your factory problem - I don't think the label problem is easily fixable on our side. Static analysis just hard for a dynamic language like JS. You can manually add labels though - it's just a special "style", so you can either append `label:FOO` to your styles or combine them with object form of that `{ label: FOO }`. I know that you probably would prefer to have this automated more - but I'm afraid we don't plan to work on adding any extra support for dynamic patterns like this.
