### ISSUE TITLE
TypeScript Autocompletion

### ISSUE THREAD

**Issue by joe-bell** [emotion-js/emotion#1327]
- `emotion` version: `10.0.10`
- `react` version: `16.6.0`
- VSCode version: `1.33.1`
- `typescript` version: `3.1.6`

**Relevant code:**

```ts
/* components/text.ts */
import styled from '@emotion/styled';
import {
  fontFamily,
  FontFamilyProps,
  fontWeight,
  FontWeightProps,
  textAlign,
  TextAlignProps,
  lineHeight,
  LineHeightProps,
  letterSpacing,
  LetterSpacingProps
} from 'styled-system';
import { Block, BlockProps } from '../block';

export interface TextProps
  extends BlockProps,
    FontFamilyProps,
    FontWeightProps,
    TextAlignProps,
    LineHeightProps,
    LetterSpacingProps {}

export const Text = 
  styled(Block)<TextProps>(fontFamily, fontWeight, textAlign, lineHeight, letterSpacing);

Text.defaultProps = {
  ...Block.defaultProps,
  as: 'p',
  fontSize: 'body'
};
```

**What you did:**

Created a text component using [Styled System](https://styled-system.com) that extends the props, with the intention of fast autocompletion in VSCode e.g.

```
<Text fontSize="body" lineHeight={1} />
```

**What happened:**

In reality, these props don't seem to be added at all. With no Emotion props either (e.g. `as`).

**Reproduction:**
https://codesandbox.io/s/y0o45ny469

**Problem description:**

No autocomplete features appear whatsoever in VSCode:

<img width="557" alt="Screenshot 2019-04-25 at 11 11 26" src="https://user-images.githubusercontent.com/7349341/56728535-e80e4180-674a-11e9-8b14-63c043c5d1ff.png">
<img width="562" alt="Screenshot 2019-04-25 at 11 11 33" src="https://user-images.githubusercontent.com/7349341/56728541-e9d80500-674a-11e9-8457-c133aa7b376e.png">

What's even weirder is that if I switch the styled definition to a function (e.g. `const Text = () => styled(Block)...` then some of Emotion's autocomplete features appear but not my custom `TextProps`

**Suggested solution:**

I'm not too sure what the suggested solution, but either way it would need a change to the docs for clarity. One I would be happy to help with.

**Comment by joe-bell** [comment]
Doing some further research it seems to be the `ColorProps` from `@types/styled-system` clashing with the intrinsic values from `styled`, not sure if this is an Emotion issue or one for the types?

**Comment by Andarist** [comment]
I no longer can reproduce the problem on your codesandbox:
<img width="524" alt="Screenshot 2019-10-28 at 23 36 01" src="https://user-images.githubusercontent.com/9800850/67723252-be74f200-f9db-11e9-8d57-69fca14231f8.png">
I assume the issue has been fixed by type changes, either in emotion or in styled-system. Or maybe just new TS version got better at this, hard to tell which one.

**Comment by joe-bell** [comment]
No worries, thanks for investigating @Andarist
