### ISSUE TITLE
styled and withTheme have different theme's in SSR

### ISSUE THREAD

**Issue by SimeonC** [emotion-js/emotion#1330]
- `emotion` version: `10.0.10`
- `emotion-theming` version: `10.0.10`
- `react` version: `16.8.6`

**Relevant code:**

```javascript
// this works correctly
const Test = withTheme(({ theme }) => {
  console.log('[debug] test1', theme);
  return null;
});

// this doesn't work
const Test2 = styled.div`
  ${({ theme }) => {
  console.log('[debug] test2', theme);
  return null;
}};
`;

// In render function
<ThemeProvider theme={{ customTheme: 'testing' }}>
  <Test />
  <Test2 />
</ThemeProvider>
```

**What you did:**
The above code is being run on SSR and then in the browser and the theme is different.

**What happened:**
In node.js Server side rendering I get this output:
```
[debug] test1 { customTheme: 'testing' }
[debug] test2 {}
```

The same code running on browser outputs this:
```
[debug] test1 { customTheme: 'testing' }
[debug] test2 { customTheme: 'testing' }
```

**Suggested solution:**

I'll do some more investigating after May 7th as I'm on holiday until then (need to make sure I don't forget and maybe someone else has come across this before?).
My initial findings seem to point to `styled-base` using `import { withEmotionCache, ThemeContext } from '@emotion/core';` whereas `withTheme` does not use `withEmotionCache`.

**Comment by SimeonC** [comment]
Eh, sorry about this - turns out it was something weird in my webpack setup. After much tinkering around I've found that sometimes it was loading the `cjs` dist version and other times the `esm` dist version so of course the themes wouldn't correctly be shared... 😭

**Comment by lawnzapper** [comment]
Hi @SimeonC, I have a similar issue, can you point me out where on webpack things were not configured properly? After removing emotion related dependencies from externals in my webpack config I managed to build a working server bundle locally, but for some strange reason when building on docker it breaks again and my theme props is always empty on my components props.
