### ISSUE TITLE
eslint-plugin-emotion feature request: error if not imported from */macro

### ISSUE THREAD

**Issue by osdiab** [emotion-js/emotion#1334]
- `emotion` version: 10.0.10
- `react` version: 16.8.6

**What you did:**
I am using `create-react-app` and my understanding is that I need to import from the babel macro versions of all the Emotion code, not the base ones.

For example, `@emotion/styled/macro`, `emotion/macro`, `@emotion/css/macro`.

**What happened:**
Nothing tells me I'm doing something wrong if I import from the normal ones, like so:

```typescript
import css from "@emotion/css";  // shouldn't be fine for CRA app
```

**Problem description:**
This is a potential footgun for new devs on my codebase who want to use Emotion on my  `create-react-app` codebase without ejecting and including the emotion babel plugin.

**Suggested solution:**
Add a lint rule to `eslint-plugin-emotion` to throw an error when you try to import from a non-macro emotion library

**Comment by arvigeus** [comment]
Workaround: https://www.styled-components.com/docs/tooling#enforce-macro-imports

**Comment by osdiab** [comment]
That works! Maybe the macro page can add a similar comment like that of styled components. I can make a PR

**Comment by Andarist** [comment]
Closing this because it seems that it's easily achievable through existing ESLint rules - as suggested by @arvigeus (thanks!).
