### ISSUE TITLE
Types missing for macro versions of emotion libs

### ISSUE THREAD

**Issue by osdiab** [emotion-js/emotion#1335]
- `emotion` version: 10.0.10
- `react` version: 16.8.6

**Relevant code:**

```typescript
import css from "@emotion/css/macro";  // types for module not found
import { injectGlobal} from "emotion/macro"  // same
```

**What you did:**

I started a codebase with `create-react-app` with TypeScript, which without ejecting, can't use the Emotion babel plugin. So i want to use the babel macros as suggested in docs, but no typings are available for the macro versions of the codebase. There are, however for `@emotion/styled`, but they are not yet published. #1315 

**What happened:**

I had to add declarations for the emotion modules in my own codebase to use it

**Suggested solution:**
Add similar typings for all the other Emotion packages.

**Comment by Andarist** [comment]
Typings for `@emotion/css/macro` and `@emotion/styled/macro` are available already for quite some already. I've just created a PR (https://github.com/emotion-js/emotion/pull/1583) for missing types for `emotion/macro` though. 

I expect this PR to be merged & released soon, so I'm closing this issue to keep the issue tracker clean.
