### ISSUE TITLE
how  to remove the underline when the mouse moves on the link?

### ISSUE THREAD

**Issue by acuteapple** [emotion-js/emotion#1338]
```js
const LogoLink = styled.a`
  color: green;
  text-decoration: none;
  &:hover {
    color: red;
    text-decoration: none;
  }
`
```

The font color changes to red and the underline dosen't be removed when the mouse moves on the link.   I used emotion.js in my first blog. Help me, thanks!

**Comment by FezVrasta** [comment]
Hi! This question isn't specific to Emotion, but it's a general CSS question.

Your code should work flawlessly unless some other global CSS is overriding it.

Here's an example: https://codesandbox.io/s/ww45jzwj2w

Please consider asking your question on StackOverflow.
