### ISSUE TITLE
how caching works?

### ISSUE THREAD

**Issue by roeycohen** [emotion-js/emotion#1340]
Hi, 

I'm using emotion like this (see https://www.npmjs.com/package/emotion):
```
import { css } from 'emotion' 
const app = document.getElementById('root')
const myStyle = css`
  color: rebeccapurple;
`
app.classList.add(myStyle)
```

when the script load, the css tag is running immediately.

should i be considered if i have hundreds of components? 
how does the caching works for this scenario?

will it be a good idea wrap the template inside a function, so that it will work only when needed? something like this:
```
import { css } from 'emotion' 
const app = document.getElementById('root')
const myStyle = () => css`
  color: rebeccapurple;
`;
app.classList.add(myStyle())
```

**Comment by roeycohen** [comment]
@roeycohen

**Comment by roeycohen** [comment]
for anyone reading this:
- i've ended up calling the css` tag inside a function within the components so that it runs only when the component is in use.
- seems like css` won't append new style Rules if called more than once. might be a good idea to cache the result so that emotion won't have to recalculate the hash again.

**Comment by FezVrasta** [comment]
I can't give a definitive answer, but the Emotion docs clearly show usage examples, and `css` is always called at the top scope (hence, executed immediately).

The typical example is React's usage:

```jsx
import React from 'react';
import { css } from '@emotion/css`;

const foo = css`color: red;`;

const Comp = () => <div className={foo} />;
```

**Comment by roeycohen** [comment]
Hi @FezVrasta!

the behavior is different between 
`import { css } from '@emotion/css;`
and 
`import { css } from 'emotion`;`

the second one returns a class name, while the first returns an object that can be used with react.
since i'm using the latter, i'm worried the css complication might take a considerable amount of time in case of many components.

**Comment by FezVrasta** [comment]
`import { css } from 'emotion'` was the way it worked on Emotion 9, but the examples were the same. That makes me think the perf overhead is low enough to don't worry about it.

**Comment by roeycohen** [comment]
maybe... :) still it might have impact when you have many many components.

**Comment by Andarist** [comment]
With thousands of components - yes, it can matter. I believe though that you try to prematurely optimize this. There are probably many other things working slower in your apps than emotion (it's pretty fast) - to improve overall performance focus on things like code-splitting and stuff rather than this.
