### ISSUE TITLE
Types missing for macro version of @emotion/css

### ISSUE THREAD

**Issue by ivandotv** [emotion-js/emotion#1350]
- `emotion` version:10.0.9
- `react` version:16.8.6

**Relevant code:**

```javascript
import css from '@emotion/css/macro'  // types for module not found error
```

**What you did:**
Tried to use macro version of `css`

**What happened:**
Typescript errors out with: `Could not find a declaration file for module '@emotion/css/macro'. '`

**Suggested solution:**
Add a typescript declaration file

**Comment by peduarte** [comment]
Same here

**Comment by FezVrasta** [comment]
(related to #933)
