### ISSUE TITLE
Inconsistent class names

### ISSUE THREAD

**Issue by sergio-bravo** [emotion-js/emotion#1355]
Hi,

We use generated themes with have some asset paths:
```
export const backgroundCss = theme => css`
  background-image: url(${theme.asset.background});
  background-repeat: repeat-x;
  background-position: top left;
  position: fixed;
  top: 0;
  right: 0;
  width: 100%;
  height: 100%;
  z-index: -1;
`;
```

Recently we noticed that BG image flickers during page updates. After some debug I've found that hash in the classname is not consistent:

`css-8wduvf-PageBg`
`css-gs1goa-PageBg`

I've hardcoded the path inside css and hash became consistent.

Have no Idea why variable backgrounds should break hash, so it looks like a bug to me.

**Comment by FezVrasta** [comment]
I don't think we'll be able to figure out the issue without more info. May you please create a reproducible example on something like CodeSandbox?

**Comment by sergio-bravo** [comment]
@FezVrasta
Hi I've found the case it was on our side actually. Closing this.

Thnx!
