### ISSUE TITLE
Usage with CRA + Typescript

### ISSUE THREAD

**Issue by peduarte** [emotion-js/emotion#1356]
- `emotion` version: 10.0.10
- `react` version: 16.8.6

**What you did:**
Replaced Styled Components with Emotion

**What happened:**
Multiple `React is not defined` Errors.

**Problem description:**
Hey there,

After replacing Styled Components with Emotion on a project bootstrapped by Create React App and Typescript I started getting `React is not defined` errors.

After looking at related issues (#1046) I realised most of these errors were happening because I was using the React Fragment shorthand syntax `<>`. I replaced them with `<React.Fragment>` and they went away.

But I did a fresh clone of the repo in a different directory, and after `yarn install` I now get other `React is not defined` Errors... And this time they're not related to the React Fragment syntax.

I honestly have no idea what it is, but here's the error:
![image](https://user-images.githubusercontent.com/372831/58082556-84dfc580-7bb7-11e9-95d0-3ae7859c1fd7.png)

And here's the file:

![image](https://user-images.githubusercontent.com/372831/58083621-a2159380-7bb9-11e9-8e4f-ee33483dd38b.png)

There's really not much happening there.

---

- Is this related to the jsx pragma? 
- Do I only need to use the jsx pragma is I use the `css` prop?
- If I use the jsx pragma, do I still need React in scope?

I've spent a few hours trying to search related issues and reading the docs, but I'm not getting the answers I need.

Any help is appreciated.

Thanks!

**Comment by FezVrasta** [comment]
Hi, would you be able to provide a CodeSandbox example to better understand the issue?

**Comment by JustinTRoss** [comment]
@FezVrasta The same problem is detailed here as well with repro: #1303

**Comment by FezVrasta** [comment]
Ok cool then I'm going to close this and focus the discussion on #1303
