### ISSUE TITLE
`lazy` and `decode` DOM attributes for `img` tags aren't supported

### ISSUE THREAD

**Issue by elektronik2k5** [emotion-js/emotion#1362]
- `emotion` version: 10
- `react` version: 16.8

**Relevant code:**
```javascript
import styled from '@emotion/styled'

const UserAvatarImage = Object.assign(
  styled.img`
    max-width: 2rem;
    max-height: 2rem;
  `,
  { defaultProps: { loading: 'lazy', decoding: 'async' } },
)
```

**What you did:**
I wanted to try the new [native lazy loading mechanism for images](https://addyosmani.com/blog/lazy-loading/). It is also applicable to `iframe`s. 

Same goes for async decoding for `img` elements: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decoding

**What happened:**
The DOM props never get to the DOM. :cry: 
Here's a workaround example for the `decode` prop:
```js
const ImageWithForwardedDecodingProp = styled(Image, {
  shouldForwardProp(propName) {
    return propName === 'decoding' || isPropValid(propName)
  },
})({ decoding: 'async' })
``` 

**Reproduction:**

**Problem description:**

**Suggested solution:**
Whitelist these new props in the `is-prop-valid` package: https://github.com/emotion-js/emotion/blob/master/packages/is-prop-valid/src/props.js

**Comment by Andarist** [comment]
You are right that those probably should be allowed, slight problem is that this is kinda a breaking change (like any change to this whitelist, but the odds of breaking somebody's code in this case is quite huge in case of the "loading" prop).

Not sure what's best way forward, cc @probablyup

**Comment by probablyup** [comment]
I’m not sure how emotion consumes the package these days, but for s-c we only use it for filtering properties on styled primitives e.g. styled.div, so the maximum risk is just a React console warning that the attribute shouldn’t be there for a div for example.

**Comment by Andarist** [comment]
That's the risk - I assume some people might get back complaining about this.

**Comment by probablyup** [comment]
Yeah, but it’s just a console warning so I wouldn’t be too concerned about it. They can just change their prop name to “isLoading” or something and it’ll go away
