### ISSUE TITLE
Assorted docs feedback from a first-time user

### ISSUE THREAD

**Issue by markerikson** [emotion-js/emotion#1363]
I've been wanting to try out a CSS-in-JS lib for a while now, and finally had some time this evening.  I eventually got Emotion to work, but I have a number of concerns about the docs that I wanted to pass on.

First, a bit of background.  I'm a Redux maintainer and I would consider myself an expert on React in general.  I am well acquainted with CSS-in-JS concepts and can even describe some of the differences between various libraries - I've just never had a chance to use any of them.  So, no hands-on experience, but not exactly a newbie overall.

My rough criteria:

- Needs to work in a CRA 3.0 + TypeScript project (with potentially some overridden config settings if necessary)
- I'd prefer to write styles as template literals rather than components
- The CSS prop looks interesting, but not critical

With that in mind, observations on the docs:

- Appearance-wise, the content layout is way too narrow.  As a result, the examples are all very hard to read, because half the code is obscured.  If there's horizontal scrollbars, that's not a good sign.  (This _may_ somehow be connected to my use of Firefox and a page zoom plugin?  The code snippets look a bit better in Chrome, but don't get any better in FF if I un-zoom the page.)
- The various packages are confusing.  I kinda get that `emotion` is the non-framework-specific package, while the `@emotion` scoped packages seem to be React-specific, but the similarity in export names between `emotion` and `@emotion/core` isn't helping.
- I don't yet understand what exactly the Babel macros do.  I get that it's somehow connected to the Babel plugins, but what do the macros actually implement ? What limitations exist compared to the plugins?  Does one of them actually make the CSS prop work?  What's the difference between `import {css} from "emotion"`, and `import {css} from "@emotion/css/macro"` ?

I did get basic classname handling working with plain Emotion, so that's a step in the right direction.  Also was able to use the WebStorm `styled-components` plugin to get CSS highlighting / handling as well.

Also, when I did briefly try to use the `@emotion/css/macro` import, TS yelled at me.  Looks like #1351 hasn't been published yet or something?

**Comment by Andarist** [comment]
> I don't yet understand what exactly the Babel macros do. I get that it's somehow connected to the Babel plugins, but what do the macros actually implement ? What limitations exist compared to the plugins?

Macros are just babel plugins which operate on a given AST node, so it's kinda like a function call (most commonly) but at build time. The advantages of that are:
- they don't "magically" operate on the whole file, you have to explicitly use them and only the affected part of the code will get transformed
- they don't have to be configured in tools like CRA

In general there are no real constraints on what they can and can't do - so there are no hard limitations on them in comparison to their "equivalent" babel plugins. 

So in case of emotion they mostly do the same as babel plugins, but only them can be used in CRA etc. So they give you things like nice labels & source maps in dev mode, minification in production.

> What's the difference between import {css} from "emotion", and import {css} from "@emotion/css/macro" ?

```
import css from '@emotion/css'
import cssCore from '@emotion/core'
import { css as emotionCss } from 'emotion 

css === cssCore // core is just reexporting it
css !== emotionCss 
```

Because emotion is framework agnostic it inserts styles right away when its css gets called. And it gives a className string to use.

Css from @emotion/core gives you an object representation of the styles to be inserted at later point by `jsx`. So this css function can be considered as pure.

 > Does one of them actually make the CSS prop work? 

Babel plugins/macros are not needed for css prop to work. It's handled inside `jsx` custom  pragma./

**Comment by markerikson** [comment]
Let me clarify: I do (mostly) know what macros are in general already.

What I'm _not_ clear on, just from looking at the docs, is:

- Exactly what capabilities importing the macro forms give you
- How those capabilities differ from what the full-blown plugins give you


On the `css` thing: so you're saying that the generic `css` function always inserts rules immediately, while the React-ified version will only insert rules when a component gets mounted for the first time?

**Comment by FezVrasta** [comment]
One of the most useful capabilities of the macro is the ability to use styled components as selectors.

```JSX
cons Foo = styled.div`color: red;`
cost Bar = styled.div`
 ${Foo} { color: blue; }
`
```

**Comment by Andarist** [comment]
> How those capabilities differ from what the full-blown plugins give you

They don't. Macros are here mostly to accommodate CRA and similar restrictions. Using plugins is roughly equivalent to macros in this case.

> On the css thing: so you're saying that the generic css function always inserts rules immediately, while the React-ified version will only insert rules when a component gets mounted for the first time?

Almost, React-ified version inserts rules at render time - so they are available after mount without any delay, avoiding FOUC etc

**Comment by Andarist** [comment]
I believe all questions here have been answered - we recognize the overall problem with confusing naming etc. But there are is also a reason why both libraries, for example, export `css` function - it's the only function which Prettier formats (and they have even rejected formatting `keyframes`, so chances that other function name would get formatting similar formatting to `css` are really low) and that styled-components VSC plugin works out of the box for both of them.

We'd like to improve the situation - but truth to be told, we don't know exactly what can be improved right now. We already try to communicate those differences in the docs. Any help that we could get in this area from the community would be highly appreciated.

Closing this to keep the issue tracker clean, there are also other issues about the documentation. We appreciate your honest feedback and we'll try to improve this somehow.
