### ISSUE TITLE
Option to customize injected className

### ISSUE THREAD

**Issue by ericclemmons** [emotion-js/emotion#1365]
**The problem**

I'm working with @cdonohue on [benefit](https://github.com/cdonohue/benefit).

It's a similar solution to [TailwindCSS](https://tailwindcss.com/) in that it's a utility CSS library, but powered by `emotion`.

```html
<div class='bg-blue-500 text-white p-8 rounded'>...</div>
```

becomes (via our own `jsx` wrapper):

```html
<div class='css-p8ywv3 css-1u78gm9 css-1rhef98 css-yrxnuw'>...</div>
```

Because we convert `bg-blue-500` to `css(declarations)`, emotion returns `css-p8ywv3`.

**Proposed solution**

When working **in development, I'd like to keep the utility classes the same**.

I'm having a hard time proposing a _how_, but my best guess would be introducing a `prefix` options to `babel-plugin-emotion`, similar to:
> https://emotion.sh/docs/babel-plugin-emotion#labelformat

The default value of `prefix` would be `css-[hash]` for backwards compatibility:

```js
{
  "plugins": [
    [
      "emotion",
      {
        // sourceMap is on by default but source maps are dead code eliminated in production
        "sourceMap": true,
        "autoLabel": process.env.NODE_ENV !== 'production',
        "labelFormat": "[local]",
        "prefix": "css-[hash]",
        "cssPropOptimization": true
      }
    ]
  ]
}
```

Users would be able to specify `"prefix": false`, which would ignore the prefix entirely and only output `label`.

Now, I fully understand the need for hashes for preventing conflicting rules under the same name.

In development, I'd propose that the computed className from a `label` would maintain it's hash association so that, should that same className be generated with a different hash, a warning/error is thrown.

**Alternative solutions**

Because the declarations are generated dynamically, even `local` doesn't work:
> https://emotion.sh/docs/babel-plugin-emotion#labelformat

`label` comes _close_, but ends up being very verbose:
> https://emotion.sh/docs/labels#___gatsby

**Additional context**

**Comment by Andarist** [comment]
I'm afraid hashing is just too core concept in emotion - any changes to this would just bring too much of maintenance complexity. It might be possible to build this yourself with a few hacks on top of existing stuff (would probably also require build-time hacks). If you are in desperate need of this - reach out to me on Twitter (my DMs are open) so we can discuss this further.

**Comment by SensationSama** [comment]
Not sure if this is correct forum but I would be interested in seeing this feature implemented or how a hack might be achieved.

**Comment by a-tonchev** [comment]
I am also interested in this matter. Now we have `css-[hash]`, it would be just fine if we have `css-[hash]_myCustomString`

Thus you don't really need huge maintenance, since you can just parse the hash out of the custom string.

and maybe while creating the css:

```
css({
  padding: 10,
  margin: 2,
}, {
 customClassName: 'myCustomString',
})
```

**Comment by Andarist** [comment]
You should be able to do this:
```js
css({
  padding: 10,
  margin: 2,
}, {
 label: 'myCustomString',
})
```

**Comment by a-tonchev** [comment]
@Andarist Thanks, this did the job!
