### ISSUE TITLE
Styling shadow dom.

### ISSUE THREAD

**Issue by flo-pereira** [emotion-js/emotion#1366]
Hi, better than explain, let me show you.

What's happening:
<img width="728" alt="Capture d’écran 2019-05-27 à 14 49 07" src="https://user-images.githubusercontent.com/1889274/58421267-d55f9300-808f-11e9-9eed-0d049a2793a5.png">

What I expected:
<img width="711" alt="Capture d’écran 2019-05-27 à 14 50 00" src="https://user-images.githubusercontent.com/1889274/58421295-e14b5500-808f-11e9-9a3b-502522b9e21f.png">

**Environment information:**

"@emotion/core": "^10.0.10",
"@emotion/styled": "^10.0.11",
"react": "^16.8.6",
"react-dom": "^16.8.6",

How can I use emotion/styled inside Webcomponents shadow dom.

```
// index.js

import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

class XComponent extends HTMLElement {
  connectedCallback() {
    const mountPoint = document.createElement('div');
    this.attachShadow({ mode: 'open' }).appendChild(mountPoint);

    ReactDOM.render(<App />, mountPoint);
  }
}

customElements.define('x-component', XComponent);
```

```
// App.js
import React from 'react';
import styled from '@emotion/styled';

function App() {
  return <StyledComponent>ok</StyledComponent>;
}

export default App;

const StyledComponent = styled.div`
  background: red;
`;
```

```
// index.html

<!DOCTYPE html>
<html lang="en">
  <body>
    <x-component></x-component>
  </body>
</html>

```

**Comment by diffidentDude** [comment]
Hey,

According to the docs, you need to use createEmotion or createCache and assign a container for emotion to render your styles into.

**Comment by flo-pereira** [comment]
thanks @diffidentDude, it does the trick !! 👍

**Comment by cihangir-mercan** [comment]
it worked for me too. working example:

`export default function Portfolio() {

    const muiRef = useRef(null);

    // Declare a new state variable, which we'll call "count"
    const [refCurr, setRefCurr] = useState(null);

    useEffect(() => {
        setRefCurr(muiRef.current);
    }, []);
    
    return (
        <div ref={muiRef} style={{height: '650px'}}>
            <CacheProvider value={createCache({
                key: 'aaa',
                prepend: true,
                container: refCurr,
            })}>
                <Box sx={{ width: '100%' }} >
                    <DataGridPro
                        autoHeight
                        treeData
                        rows={rows}
                        columns={columns}
                        getTreeDataPath={getTreeDataPath}
                        rowThreshold={0}
                        getDetailPanelContent={getDetailPanelContent}
                        getDetailPanelHeight={getDetailPanelHeight}
                        hideFooter
                    />
                </Box>
            </CacheProvider>
        </div>
    );
`
