### ISSUE TITLE
css prop doesn't work with React.createElement

### ISSUE THREAD

**Issue by pizza-r0b** [emotion-js/emotion#1368]
This can be reproduced easily in the sandbox. The css prop does not work when used with React.createElement.

https://codesandbox.io/s/emotion-issue-template-wwf8q

**Comment by FezVrasta** [comment]
You need to replace `React.createElement` with `jsx` from Emotion.

**Comment by pizza-r0b** [comment]
It's impossible to do this with JSX without the need for an additional component:

`React.createElement(useAnchorTag ? 'a' : ReactRouterLink, props, children)`

Not a deal breaker - you could always make a new component and do this (as long as you could pass the css prop through?) 

```js
const Component = useAnchorTag ? MyAnchor : ReactRouterLink;
// ...
return <Component css={css} />
```

What are the complexities of making this work with `createElement`? Happy to create a pull request if I can. Can you point me in the right direction? It doesn't seem great to make `React.createElement` unusable with emotion.

**Comment by FezVrasta** [comment]
Probably I wasn't clear, you need to use `Emotion.jsx(Component, { css: x })`

React doesn't support the css property out of the box, yoo need to use the "createElement" from emotion, which is called "jsx"
