### ISSUE TITLE
Improve documentation for composes

### ISSUE THREAD

**Issue by hawkins** [emotion-js/emotion#137]
*(We've talked about this before, I'm just opening an issue so it stays on my radar, so I can be sure to remember to knock this out first chance I get time for oss this week)* 😄

I'd like to touch just a little bit on the `composes` section of the documentation in order to better cover some pitfalls, like we discussed in slack last week (i.e., since `composes` with a pseudo selector like `&:hover` does not work, here's the suggested pattern...). I think addressing this here will help readers adopt the right patterns for quickly working with emotion effectively.

**Comment by tkh44** [comment]
Yep! @hawkins I would love to have you spend some time on this. It's sorely needed.
