### ISSUE TITLE
Close issues not following issue templates?

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#1371]
What do you guys think about closing the issues that purposefully not follow the provided issue templates?

I do this in my own OSS projects and it helps a lot to keep the issues list healthy. Usually people either create a new issue, this time following the template, or goes to StackOverflow, Spectrum, etc...

Alternatively, if you don't feel like about closing issues, we may create a new `Low priority (missing issue template)` label, to help us focus on the "good" issues and at the same time let the users know they are less likely to get quick help if they don't help us first with the issue template.

**Comment by mitchellhamilton** [comment]
yes. do it.
