### ISSUE TITLE
[SUPPORT] How to pass Themes to Unit Tests with Emotion v10

### ISSUE THREAD

**Issue by mmartinsky** [emotion-js/emotion#1372]
With the removal of createBroadcast, https://stackoverflow.com/questions/54554803/how-to-pass-emotion-theme-to-unit-tests is no longer applicable. 

Does anyone have a way of wrapping enzyme's shallow/mount methods to use the ThemeProvider?

**Comment by Andarist** [comment]
this should be as simple as:
```js
const Component = mount(<ThemeProvider theme={theme}><MyComponent/></ThemeProvider>)
```
You might not be able to use shallow though with this but I would advise against using it anyway - https://kentcdodds.com/blog/why-i-never-use-shallow-rendering/

**Comment by billyvg** [comment]
> this should be as simple as:
> 
> ```js
> const Component = mount(<ThemeProvider theme={theme}><MyComponent/></ThemeProvider>)
> ```
> 
> You might not be able to use shallow though with this but I would advise against using it anyway - [kentcdodds.com/blog/why-i-never-use-shallow-rendering](https://kentcdodds.com/blog/why-i-never-use-shallow-rendering/)

This won't work if you need to use `enzyme` functions that require a root instance (e.g. `setProps()`)
