### ISSUE TITLE
[SUPPORT] Implementing Preact SSR and RTL support

### ISSUE THREAD

**Issue by oyo-ravi-yadav** [emotion-js/emotion#1374]
I have a preact SSR app and have used Emotion.JS 10 for styling.

I wanted to add RTL support with this so have used `createEmotion` and `createEmotionServer` and used the resulting `renderStylesToString` to render the app.

However while creating `createEmotion` it requires the plugins to be used for which i added the `stylis-rtl` plugin but this would always apply the RTL styles while i want the RTL styles to be applied on the basis of each request.

I could not find any way to tell emotion to apply and get the styles for RTL on each request basis.

One solution could be to serve different webpack builds for RTL but that would be unnecessary overhead.

stackoverflow link: https://stackoverflow.com/questions/56394931/emotion-js-with-preact-ssr-and-rtl-support

**Comment by FezVrasta** [comment]
Hi, thanks for the issue, please let's keep the conversation on StackOverflow, it's the best place for this kind of questions.

The question you created is perfect already:  
stackoverflow.com/questions/56394931/emotion-js-with-preact-ssr-and-rtl-support
