### ISSUE TITLE
CamelCase CSS custom properties should not be transformed

### ISSUE THREAD

**Issue by daneden** [emotion-js/emotion#1376]
**Current behavior:**

Setting a CSS custom property with a camel case name (`--textColor`) will transform it to dash-separated (`--text-color`) or all lowercase unexpectedly.

**To reproduce:**

Reproduced in [this Codesandbox](https://codesandbox.io/s/emotion-issue-1376-863lg)

1. Set and try to use a CSS custom property with a camelCase name (e.g. `--textColor`) in a template literal method (`css` or `styled`)
2. Inspect the element that the custom property is used on; observe that the custom property is transformed to all lowercase (e.g. `--textcolor`)
3. Set and try to use a CSS custom property with a camelCase name using `styles` prop on `Global`, or `css` prop on any jsx element using Emotion’s exported `jsx`
4. Inspect the element that the custom property is used on; observe that the custom property is transformed to dash-separated (e.g. `--text-color`)

**Expected behavior:**

CSS custom properties should not be transformed and should be output exactly as authored.

**Environment information:**

- `react` version: 16.8.6
- `emotion` version: 10.0.10

**Comment by daneden** [comment]
I sanity-checked the [CSS spec](https://drafts.csswg.org/css-variables/#defining-variables) to make sure that my expected behavior (“CSS custom properties […] should be output exactly as authored”) was correct. There’s nothing that explicitly states this, but it can be inferred from the following:

> Unlike other CSS properties, custom property names are case-sensitive.

And: 

> While both --foo and --FOO are valid, they are distinct properties - using var(--foo) will refer to the first one, while using var(--FOO) will refer to the second.

**Comment by Andarist** [comment]
Thanks for the report, I've prepared a fix in #1378
