### ISSUE TITLE
[QUESTION] Is extractCritical working by default with emotion 10 and Next.js

### ISSUE THREAD

**Issue by Ktchan825** [emotion-js/emotion#1380]
Hi,
I am using Nextjs 8.1 with emotion 10, I wonder if I need to set anything for extracting critical css?

**Comment by FezVrasta** [comment]
You can find the `extractCritical` documentation here, please follow the instructions and if anything doesn't work for whatever reason feel free to open a new issue pointing out the actual problem.

https://emotion.sh/docs/ssr#extractcritical

Thanks!
