### ISSUE TITLE
Sourcemaps don't work if you alias styled.div to another variable

### ISSUE THREAD

**Issue by MattMorrisDev** [emotion-js/emotion#1383]
**Current behavior:**
Sourcemaps don't work if you alias styled.div to another variable before calling it.

For example:
```
import styled from '@emotion/styled';
import React from 'react';
import 'src/App.css';

const createStyledDiv = styled.div;
const extendStyled = styled;

const StyledDiv = styled.div({
  color: 'green',
});

const StyledDivViaAlias = createStyledDiv({
  color: 'blue',
});

const ExtendedStyledDiv = extendStyled(StyledDiv)({
  color: 'red',
});


const App: React.SFC = () => {
  return (

    <div className="App">

      {/* Sourcemaps work here*/}
      <StyledDiv>StyledDiv</StyledDiv>

      {/* Sourcemaps DO NOT work here*/}
      <StyledDivViaAlias>StyledDivViaAlias</StyledDivViaAlias>

      {/* Sourcemaps work here*/}
      <ExtendedStyledDiv>ExtendedStyledDivViaAlias</ExtendedStyledDiv>

      {/* Sourcemaps work here*/}
      <div css={{color: 'purple'}}>inline css prop</div>
    </div>
  );
};

export default App;
```
Sourcemaps working:
<img width="1205" alt="Screen Shot 2019-06-03 at 12 17 48 PM" src="https://user-images.githubusercontent.com/27645392/58829012-9c796e00-85fb-11e9-9bc1-4af2ec193872.png">

Sourcemaps not working:
<img width="1207" alt="Screen Shot 2019-06-03 at 12 17 58 PM" src="https://user-images.githubusercontent.com/27645392/58829013-9d120480-85fb-11e9-8d90-f5d730710e0a.png">

**To reproduce:**
1. Clone https://github.com/MattMorrisDev/emotion-repro
2. `yarn install && yarn start`
3.  See in App.tsx that sourcemaps don't work in dev tools if you assign styled.div to another variable before invoking it

**Expected behavior:**

Ideally the sourcemaps would work in this scenario, or the generated css name would at least include `StyledDivViaAlias` instead of `createStyledDiv`.

If it isn't fixable, maybe we should mention this limitation in the docs. 

**Environment information:**
```
    "@emotion/babel-preset-css-prop": "10.0.9",
    "@emotion/core": "10.0.10",
    "@emotion/styled": "10.0.11",
    "emotion-theming": "10.0.10",
    "react": "16.8.6",
    "react-dom": "16.8.6"
    "typescript": "3.4.5"
```

**Comment by Andarist** [comment]
The complexity of fixing this issue is too big for us to implement this ourselves and anyway it wouldn't ever work cross-file, because babel operates on a single files.

Our babel plugin uses static analysis to insert those sourcemaps and by assigning styled to a variable you make it harder to follow what thing is a styled and what is not.

**Comment by MattMorrisDev** [comment]
Thanks for the clarification. I'll do some refactoring on my end :)

**Comment by boycce** [comment]
This also has troubles if `css` is a global.
