### ISSUE TITLE
Support for nested callbacks

### ISSUE THREAD

**Issue by danielhusar** [emotion-js/emotion#1388]
Styled components supports nested callbacks inside your styles, but emotion supports just one level callback.

Usually it's not a good idea to do it, but I think it's still would be nice for emotion to not silently fail in production and evaluate nested callbacks as well.

Especially since it's quite hard to statically check for such scenarios.
(you can have various helpers, etc..)

Here's a demo of this behaviour in styled components: https://codesandbox.io/s/lcsk9

**Comment by Andarist** [comment]
This was intentionally removed in https://github.com/emotion-js/emotion/pull/643 but no dev warning was added for this misusage in emotion@10.

**Comment by danielhusar** [comment]
Is there any limitation why `css` callback would not be called with props? (before it was removed)
Is it because you can use it outside styled?

Styled components call them with props correctly: https://codesandbox.io/s/lcsk9

My main reasoning behind supporting it: it's so easy to shoot yourself in the foot now. Especially for beginners.

**Comment by Andarist** [comment]
> Is it because you can use it outside styled?

Yes. It's just regular function call, it's not component-aware.

> Styled components call them with props correctly: https://codesandbox.io/s/lcsk9

It's indeed not impossible to support this, BUT it makes `css` a weird API which behaves differently based on which context it is used in. It seems to me that such "magic" implicit and behind the curtains logic is rarely a good thing.

> My main reasoning behind supporting it: it's so easy to shoot yourself in the foot now. Especially for beginners.

Agreed that it might trip somebody, so IMHO we should introduce a dev-only warning about passing functions into css interpolations. Would you be willing to prepare a PR for this?

**Comment by danielhusar** [comment]
Yeah that's fair.

Sounds good, I can implement the warning :)
Ideally there would be eslint plugin so you can get static warnings, rather than rely on runtime.

**Comment by danielhusar** [comment]
I created (pretty dummy) eslint plugin that will warn you if you use callbacks inside of `css` helper.

https://github.com/danielhusar/eslint-plugin-emotion-utils

**Comment by Andarist** [comment]
Seems like the dev-only warning was already there when this issue got reported. Can be observed [here](https://codesandbox.io/s/styled-components-rimeo). Not sure how you have missed it - maybe it was swallowed by some tool? Either way - I believe this can be closed. If you still suffer from any problems with emotion - let us know by opening a new issue.
