### ISSUE TITLE
Add looser peer dep requirements for react and react-dom?

### ISSUE THREAD

**Issue by majapw** [emotion-js/emotion#1389]
QQ: Would it be possible to loosen the react and react-dom peer dep restrictions to ^16.0.0 or are there explicit dependencies on react 16.3+ features in this library?

**Comment by Andarist** [comment]
We are depending on createContext and forwardRef - I'm afraid they were both introduced in 16.3

**Comment by majapw** [comment]
No worries, thanks for the quick response!
