### ISSUE TITLE
hot reload when you use emotion-theming not working

### ISSUE THREAD

**Issue by nephlin7** [emotion-js/emotion#1391]
**Current behavior:**

It is an bug or it works like this?

**Expected behavior:**

**Environment information:**

- `react` version: ^16.8.6
- `emotion` version: ^10.0.9
- `emotion-theming` version: ^10.0.10

**Comment by Andarist** [comment]
The issue is described without any details. I'm forced to close this until you provide more details - we need to know what you did, what exactly did you observe and preferably with a runnable repro case.
