### ISSUE TITLE
Failed tests with Jest using components with @emotion/styled

### ISSUE THREAD

**Issue by valevassallo** [emotion-js/emotion#1392]
**Current behavior:**

Using styled tags (with @emotion/styled) to create a form, Jest tests don't work, but if I take them out and use normal HTML tags instead, tests do run successfully.

**To reproduce:**

https://codesandbox.io/s/emotion-issue-template-5s3co

**Expected behavior:**

Make the test run successfully using styled tags

**Environment information:**

"@emotion/core": "^10.0.10",
"@emotion/styled": "^10.0.11",
"@testing-library/react": "^8.0.1",
"jest-emotion": "^10.0.11",
"react": "^16.8.6",
"react-dom": "^16.8.6",
"react-scripts": "3.0.1"

**Comment by Andarist** [comment]
You are trying to fire a submit event on an input, you should do that on a form element. This is a correct version for this test:
```js
test("CompanyForm functionality", () => {
  const setCompanyName = jest.fn();
  const { asFragment, getByLabelText, getByRole } = render(
    <CompanyForm setCompanyName={setCompanyName} />
  );

  expect(asFragment()).toMatchSnapshot();
  const input = getByLabelText("Input to get Company's name");

  fireEvent.change(input, {
    target: { value: "Able" }
  });

  const form = getByRole('form')
  fireEvent.submit(form);

  expect(setCompanyName).toHaveBeenCalledWith("Able");
});
```
