### ISSUE TITLE
Ability to set default shouldForwardProp or expose to extended components

### ISSUE THREAD

**Issue by rathpc** [emotion-js/emotion#1394]
_**UPDATED TO REFLECT MORE ACCURATE ISSUE**_

**The problem**

I would love the ability to set a default shouldForwardProp value, project wide by either a simplistic factory extension or via a theme. Currently when I set the shouldForwardProp value on a styled div it works great. However if I extend that styled component to form another one leveraging the `withComponent` helper, that shouldForwardProp value is not exposed to that new styled component and I need to set it again.

ie:
```
import { css } from '@emotion/core';
import styled from '@emotion/styled';
import * as styledSystem from 'styled-system';
import { COLORS, fontAR, shouldForwardProp } from '../../constants/styles';

const baseStyle = css`
  ${fontAR};
  font-size: 14px;
  line-height: 1.43;
`;

const smallStyle = css`
  font-size: 12px;
  line-height: 1.67;
`;

const largeStyle = css`
  font-size: 16px;
  line-height: 1.91;
`;

const boldStyle = css`
  font-family: Avenir;
  font-weight: 900;
`;

const styleMap = {
  small: smallStyle,
  large: largeStyle,
  bold: boldStyle,
};

interface ParagraphProps
  extends styledSystem.ColorProps,
    styledSystem.FontFamilyProps,
    styledSystem.FontSizeProps,
    styledSystem.FontWeightProps,
    styledSystem.HeightProps,
    styledSystem.LetterSpacingProps,
    styledSystem.LineHeightProps,
    styledSystem.SpaceProps,
    styledSystem.TextAlignProps,
    styledSystem.WidthProps {
  color?: COLORS;
  size?: string;
}

export const Paragraph = styled('p', { shouldForwardProp })<ParagraphProps>`
  ${baseStyle}
  ${styledSystem.color}
  ${styledSystem.fontFamily}
  ${styledSystem.fontSize};
  ${styledSystem.fontWeight}
  ${styledSystem.height}
  ${styledSystem.letterSpacing}
  ${styledSystem.lineHeight}
  ${styledSystem.space}
  ${styledSystem.textAlign}
  ${styledSystem.width}
  ${props => (props.size ? styleMap[props.size] : null)}
`;

const Label = styled(Paragraph)`
  color: ${COLORS.slate};
  display: flex;
  align-items: center;
  margin-bottom: 4px;
`.withComponent('label');
```

Now Label does not know to exclude any props that are a result of the imported function which works as intended in the Paragraph component.

**Proposed solution**

- Add the ability in the core code to consume the underlying shouldForwardProp value if a styled component is extending another styled component combined with `withComponent`.

It works if you use the `as` prop but my intention is to not need to remember to add that additional prop anytime I want to use the new Label component

**Comment by FezVrasta** [comment]
I wonder if `CacheProvider` could help here

**Comment by Andarist** [comment]
> However if I extend that styled component to form another one, that shouldForwardProp value is not exposed to that new styled component and I need to set it again.

Created component should "inherit" shouldForwardProp:
https://github.com/emotion-js/emotion/blob/62576aabd29e5159b7394243cec9d04fc906a9c3/packages/styled-base/src/index.js#L35

If it's not the case please provide a codesandbox with the issue reproduced.

**Comment by rathpc** [comment]
This is totally my mistake, I lost track of where the issue was actually happening. It loses "inheritance" when combined with `withComponent`

I will update the original code example above but also putting here for reference

```
import { css } from '@emotion/core';
import styled from '@emotion/styled';
import * as styledSystem from 'styled-system';
import { COLORS, fontAR, shouldForwardProp } from '../../constants/styles';

const baseStyle = css`
  ${fontAR};
  font-size: 14px;
  line-height: 1.43;
`;

const smallStyle = css`
  font-size: 12px;
  line-height: 1.67;
`;

const largeStyle = css`
  font-size: 16px;
  line-height: 1.91;
`;

const boldStyle = css`
  font-family: Avenir;
  font-weight: 900;
`;

const styleMap = {
  small: smallStyle,
  large: largeStyle,
  bold: boldStyle,
};

interface ParagraphProps
  extends styledSystem.ColorProps,
    styledSystem.FontFamilyProps,
    styledSystem.FontSizeProps,
    styledSystem.FontWeightProps,
    styledSystem.HeightProps,
    styledSystem.LetterSpacingProps,
    styledSystem.LineHeightProps,
    styledSystem.SpaceProps,
    styledSystem.TextAlignProps,
    styledSystem.WidthProps {
  color?: COLORS;
  size?: string;
}

export const Paragraph = styled('p', { shouldForwardProp })<ParagraphProps>`
  ${baseStyle}
  ${styledSystem.color}
  ${styledSystem.fontFamily}
  ${styledSystem.fontSize};
  ${styledSystem.fontWeight}
  ${styledSystem.height}
  ${styledSystem.letterSpacing}
  ${styledSystem.lineHeight}
  ${styledSystem.space}
  ${styledSystem.textAlign}
  ${styledSystem.width}
  ${props => (props.size ? styleMap[props.size] : null)}
`;

const Label = styled(Paragraph)`
  color: ${COLORS.slate};
  display: flex;
  align-items: center;
  margin-bottom: 4px;
`.withComponent('label');
```

Now Label does not know to exclude any props that are a result of the imported function which works as intended in the Paragraph component.

**Comment by Andarist** [comment]
Could you prepare a codesandbox with the issue reproduced? Copy-pasted code is still a far way from getting this running and debuggable and I, unfortunately, don't have time to do this right now.

**Comment by rathpc** [comment]
> Could you prepare a codesandbox with the issue reproduced? Copy-pasted code is still a far way from getting this running and debuggable and I, unfortunately, don't have time to do this right now.

Here is a sandbox showing the issue:

https://codesandbox.io/s/emotion-issue-template-uz95h?fontsize=14

`Example 1` should be working just like the other two but does not currently. The ideal situation is for it to work just like `Example 2` which I found as a workaround for now. `Example 3` is the fail-proof solution but requires more code, more often.

`Example 4` is an extra situation I decided to illustrate that shows while the workaround `Example 2` does work, it only works one level deep since color re-appears in the DOM render in this example.

Let me know if you need any other clarification. Thanks 👋

**Comment by Andarist** [comment]
Ok, I see what's happening now. When using `withComponent` [this line "fails"](https://github.com/emotion-js/emotion/blob/d5a80f9c7e1e27b01f34b613cd5a2511567af533/packages/styled-base/src/index.js#L43) and things are not being merged like you might have expected.

Need to think about how this and other options are handled when extending components

**Comment by Andarist** [comment]
This issue got fixed by https://github.com/emotion-js/emotion/pull/1668 and the fix is going to be a part of the upcoming v11.
