### ISSUE TITLE
How to use obj style with @font-face

### ISSUE THREAD

**Issue by pvinis** [emotion-js/emotion#1395]
I'm trying to do this:
```
<Global
  styles={{
    '@font-face': {
      fontFamily: 'Iosevka',
      src: 'url(woff2/iosevka-thinitalic.woff2) format(woff2)',
    },
  }}
/>
```

**Description:**

I can't figure out if the `src` part needs to be a string like above, or `'url(\'fonts..\') format(\'..\')` or something else?

**Documentation links:**

**Comment by pvinis** [comment]
I figured it out.. for reference:
https://github.com/pvinis/blog/commit/3d0f6f13046b855d81b3188fe4b8995154d754be

**Comment by jvanderen1** [comment]
How do you load multiple styles of the same font-family in object notation?

**Comment by flo-sch** [comment]
Thanks @Andarist for that snippet :)
It believe it could be useful to document that on the [Global](https://emotion.sh/docs/globals) component page, WDYT?

**Comment by Andarist** [comment]
@flo-sch PRs are welcome 😉

**Comment by flo-sch** [comment]
PR open :)
