### ISSUE TITLE
document is not defined with react-on-rails

### ISSUE THREAD

**Issue by brandoncc** [emotion-js/emotion#1407]
**Current behavior:**

The documentation says that server side rendering works with no configuration needed if you install `@emotion/core` in a React app. I am getting `document is not defined` during the SSR.

I am using `@emotion/styled`, not `css` or `jsx`, I'm not sure if that could be where my problem is?

```jsx
import * as React from 'react';
import styled from '@emotion/styled';

const Container = styled.div(
  {
    marginTop: 6,
    position: 'relative'
  },
  props => props.css
);
```

The error looks to be coming from a `createCache` method.

**To reproduce:**

I can create an example app if needed but I don't have one handy.

**Expected behavior:**

The page should render.

**Environment information:**

- `react` version: 16.8.0
- `emotion` version: 10.0.10

**Comment by Andarist** [comment]
How so you build your server? Webpack?

**Comment by brandoncc** [comment]
Yes, using webpacker via rails

**Comment by brandoncc** [comment]
I saw the other issue about cache breaking some static site generators....I don't think I have the same problem though. I have two bundles, one if which is for the server and uses remderToString. That is there I am having this error.

**Comment by xtroncode** [comment]
I am facing the same issue with ReactJS.net

**Comment by Andarist** [comment]
You should use target: ‘node’ in your webpack config

**Comment by brandoncc** [comment]
I don't think I can change that with webpacker :-/

**Comment by brandoncc** [comment]
Also, my code is running in the browser except that one bundle, don't I want it targeting the web?

**Comment by Andarist** [comment]
Well, I dont know how your bundles are structured - but in general client-side bundles are not the same as your SSR entry point, so you should have 2 separate builds.

**Comment by Dangoo** [comment]
@Andarist I have a similar issue, but I'm forced to use `target: webworker` in order to deploy my code to cloudflare. In that mode neither `document` nor `process` are allowed.

**Comment by Andarist** [comment]
If you specify target as webworker the bundler should use default entries which have document access guarded.

If this is not working properly you would have to prepare a repro case that would showcase the behavior and which would be easy to investigate.

**Comment by Andarist** [comment]
Closing this because we have not received a repro case since September. It's also definitely a problem with used tooling or its configuration - not something we can fix in Emotion.
