### ISSUE TITLE
Meta/docs: how is Emotion versioning handled? 

### ISSUE THREAD

**Issue by kevinSuttle** [emotion-js/emotion#1408]
I'm wondering what the versioning and release process is for Emotion, and if it is documented anywhere. I can't seem to find it, and noticed that there are 40+ commits right now to master that aren't in the latest version from 2.5 months ago. Thanks!

**Comment by Andarist** [comment]
It's not documented, releases are done manually when appropriate. Not sure how you have checked this but latest release was done 13 days ago - https://github.com/emotion-js/emotion/commit/133136aabfa9630d9cc360f9432e6c771bb9e293

**Comment by kevinSuttle** [comment]
Thanks. I was checking here 

• https://github.com/emotion-js/emotion/releases

 • https://github.com/emotion-js/emotion/tags 

• https://www.npmjs.com/package/emotion
