### ISSUE TITLE
Inconsistent selector between server and client

### ISSUE THREAD

**Issue by droganov** [emotion-js/emotion#1409]
Hi
Found an issue with selector.

This code makes elements move in nextjs app after client init:

````
export const scrollboxCss = {
  '> * + *': {
    marginLeft: 10,
  },
};
```

**Comment by Andarist** [comment]
The issue has been described so briefly, that I'm actually not sure what the issue is. If you still suffer from this issue please raise a new ticket with a proper description of the problem.
