### ISSUE TITLE
Using emotion/styled with antd components gives typescript error

### ISSUE THREAD

**Issue by paramsinghvc** [emotion-js/emotion#1411]
**Current behavior:**

![Screenshot 2019-06-24 at 17 33 33](https://user-images.githubusercontent.com/4329912/60017479-70a35280-96a6-11e9-8cf3-d767887bfb1c.png)

**To reproduce:**

```
import React, { FC, useState } from "react";
import styled from "@emotion/styled";
import { Button } from "antd";

const TButton = styled(Button)`
  position: relative;
  display: inline-block;
`;

const ToggleButton: FC<any> = props => {
  const isOn = useState<boolean>(false);
    
  return (
    <div>
      <TButton>dsfdf</TButton>
    </div>
  );
};

export default ToggleButton;
```

Here's the link to **CodeSandbox** https://codesandbox.io/embed/react-typescript-9i4l7

**Expected behavior:**

Should work seamlessly with antd react components.

**Environment information:**

- `react` version: 16.8.6
-  "@emotion/core": "10.0.10",
    "@emotion/styled": "^10.0.10",

**Comment by craigmorrison** [comment]
Your example doesn't match the description. Perhaps you intended to link a different version?

**Comment by Andarist** [comment]
@craigmorrison thanks for checking this issue! Closing this because the error doesn't show up on the linked repro case and @paramsinghvc hasn't provided a proper repro since August.
