### ISSUE TITLE
styled types do not support object notation

### ISSUE THREAD

**Issue by thomasthiebaud** [emotion-js/emotion#1422]
**Current behavior:**

`styled` types do not support object notation.

According to the documentation (https://emotion.sh/docs/typescript#passing-props), it should be possible to write 

```
interface ImageProps {
  src: string;
  width: number;
};

const Image1 = styled('div')(
  {
    backgroundSize: 'contain',
  },
  (props: ImageProps) => ({
    width: props.width,
    background: `url(${props.src}) center center`,
  })
);
```

but it give me that error locally

```
Argument of type '{ backgroundSize: string; }' is not assignable to parameter of type 'TemplateStringsArray'.
Object literal may only specify known properties, and 'backgroundSize' does not exist in type 'TemplateStringsArray'.ts(2345)
```

Looking at the types test (https://github.com/emotion-js/emotion/blob/master/packages/styled/types/tests.tsx) it only seems that string literals are supported. 

Where types for object notation supported? Is it a bug?

**Environment information:**

```
"@emotion/core": "10.0.14"
"@emotion/is-prop-valid": "0.8.2"
"@emotion/styled": "10.0.14"
"react": "^16.8.6"
```

**Comment by Andarist** [comment]
Can't reproduce here - https://codesandbox.io/s/stupefied-https-uw7bg

Also we have more TS tests here - https://github.com/emotion-js/emotion/blob/master/packages/styled-base/types/tests.tsx

**Comment by thomasthiebaud** [comment]
Which `tsconfig.json` are you using? I can always reproduce it

**Comment by eriktoyra** [comment]
We have noticed a similar issue since updating to `"@emotion/core": "10.0.14"` and `"@emotion/styled": "10.0.14"`.

We are passing around the `theme` props to our styled components. Up until `10.0.14` this has worked fine with components as the one below. But since `10.0.14`, we started to get errors like 

```bash
error TS2741: Property 'theme' is missing in type '{ children: Element[]; }' but required in type '{ theme: typeof import("/Users/[removed-for-privacy-reasons]/src/themes/[removed-for-privacy-reasons]"); }'.

190                 <Range>
                     ~~~~~

  node_modules/@emotion/styled-base/types/index.d.ts:33:11
    33   : P & { theme: T }
                 ~~~~~
    'theme' is declared here.
```

#### Examples

```tsx
// Worked pre 10.0.14, but blows up in 10.0.14
const Range = styled.div(({ theme }) => ({
    display: 'flex',
    justifyContent: 'space-between',
    font: theme.fonts.desktop.medium,

    [theme.breakpoints.mobileAndLower]: {
        font: theme.fonts.mobile.medium,
    },
}));
```

```tsx
// Works with all versions
const Range = styled.div<{}>(({ theme }) => ({
    display: 'flex',
    justifyContent: 'space-between',
    font: theme.fonts.desktop.medium,

    [theme.breakpoints.mobileAndLower]: {
        font: theme.fonts.mobile.medium,
    },
}));
```

#### Conclusion

It seems that the `theme` prop will never be added if we don't provide a type to the styled component. For now it works if we add `<{}>` to all styled components that takes `theme` as a prop. But it feels like we shouldn't have to.

**Comment by thomasthiebaud** [comment]
If I use `create-react-app` locally I can reproduce the error, but I can't in `CodeSandBox`. I'll continue to investigate

**Comment by Andarist** [comment]
> Which tsconfig.json are you using? I can always reproduce it

Hard to tell exactly - codesandbox uses CRA template, so it should be some shape of [this](https://github.com/facebook/create-react-app/blob/24143089afc1034b9733605dc44c06b800fd1c90/packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js#L94). Please provide a repository with the issue reproduced so we can reliably investigate this.

@eriktoyra

Can't reproduce your issue on [codesandbox](https://codesandbox.io/s/condescending-violet-2npht). Please provide a repository with the issue reproduced so we can reliably investigate this 😉

**Comment by thomasthiebaud** [comment]
@Andarist Here's a repo that reproduces the issue https://github.com/thomasthiebaud/emotionstyled-tsissue

**Comment by Andarist** [comment]
The preferred way to pass a props type to styled is:
```ts
const Image = styled("div")<ImageProps>(
  {
    backgroundSize: "contain",
    zIndex: 30
  },
  (props) => ({
    width: props.width,
    background: `url(${props.src}) center center`
  })
);
```
It's the most

**Comment by thomasthiebaud** [comment]
Thanks for the help. I'll code this issue for now.

My code was a copy paste from the documentation, so it probably will be better to remove it from there if it is not correct (https://emotion.sh/docs/typescript#passing-props)

**Comment by Andarist** [comment]
> My code was a copy paste from the documentation, so it probably will be better to remove it from there if it is not correct (https://emotion.sh/docs/typescript#passing-props)

Oh, I haven't realized that. Maybe @Ailrun could take a look at this one to see why the first overload is not being able to be matched here, I wonder if it has changed with any particular version of TS or was it always the case 🤔
