### ISSUE TITLE
extractCritical doesn't extract css from <Global> components

### ISSUE THREAD

**Issue by luisherranz** [emotion-js/emotion#1424]
**Current behavior:**

`extractCritical` doesn't extract css from `<Global>` components.

Some applications, like for example Google AMP, cannot have multiple `<style>` tags and/or cannot have `<style>` tags rendered in the `<body>`.

**To reproduce:**

1. Use `extractCritical` to extract the CSS from the React app
2. Inject that CSS in it's own <style amp-custom> in the <head>

**Expected behavior:**

The `<style amp-custom>` tag is fine, but there's an additional tag 
`<style data-emotion-css="xxx">` with the css from the `<Global>` component.

The CSS from `<Global>` should be extracted as well.

**Environment information:**

- `react` version: 16.8.6
- `emotion` version: 10.0.14

I'll add a codesandbox with the production soon (cloudflare seems down right now).

**Comment by Andarist** [comment]
Seems like those styles are explicitly [not cached](https://github.com/emotion-js/emotion/blob/c257d2a399016d235199554bcf9070fedd081ab2/packages/core/src/global.js#L129) (4th parameter is called `shouldCache`) and extracted styles are extracted from the cache object. 

I'm not sure about exact design here (there is some reason why those are not cached after all), so hopefully @mitchellhamilton could clear that up. The request itself (for those being extractable) seems reasonable for me.

**Comment by mitchellhamilton** [comment]
The reason is that when Global components unmount, their styles are removed so therefore, we can't cache them.

**Comment by luisherranz** [comment]
Will adding a `shouldCache` prop would solve the problem? If so, would you accept a PR?

Right now emotion is pretty much unusable to build AMP valid sites with React SSR for this reason and that's something (frameworks are starting to add)[https://nextjs.org/blog/next-8-1#amp-first-pages]. And it's pretty cool I should say :D

**Comment by Andarist** [comment]
> The reason is that when Global components unmount, their styles are removed so therefore, we can't cache them.

Ok, i havent' noticed that inserted cache is checked at insertion sites. What' the reason behind separate inserted & registered caches? Is registered supposed to contain "unflattened" styles ("fragment styles") while inserted has just IDs of those which were actually flattened and inserted?

> Will adding a shouldCache prop would solve the problem? 

As @mitchellhamilton mentioned they are not supposed to be cached, so we have to figure out different solution here.

@mitchellhamilton do you agree that this should be supported though?

**Comment by luisherranz** [comment]
Maybe it could be a more explicit prop name like `extract=true` or `neverUnmount=true`.

**Comment by mitchellhamilton** [comment]
> Ok, i havent' noticed that inserted cache is checked at insertion sites. What' the reason behind separate inserted & registered caches? Is registered supposed to contain "unflattened" styles ("fragment styles") while inserted has just IDs of those which were actually flattened and inserted?

Yes, `registered` is for composition and `inserted` is for now reinserting styles and on the server, with the emotion/create-emotion, it's used for storing the processed css that should be returned to extractCritical and the other SSR methods.

I don't really think this use case should be supported with `Global`, you can already do this with `injectGlobal` from the emotion package.

**Comment by luisherranz** [comment]
I tought `injectGlobal` was not good for SSR and that was the reason `<Global>` was created.

We used it in the past and we suffered from the SSR leakage explained in this issue:
https://github.com/emotion-js/emotion/issues/573

Is that problem fixed in emotion 10?

**Comment by Andarist** [comment]
> I don't really think this use case should be supported with Global, you can already do this with injectGlobal from the emotion package.

Seems like `<Global/>` is favoured API (and it's isomorphic) when using React, as all you have to do is use `@emotion/core` package. Seems weird to suggest using "raw" `emotion` for this - especially given that it wouldnt be discoverable by developers.

Considering "0 config" philosophy (I know it's not config, but still) it seems weird to expect people to use different API when using SSR than in the browser. And also `injectGlobal` is ofc less powerful than `<Global/>` so it wouldn't cover all use cases.

**Comment by luisherranz** [comment]
@mitchellhamilton what's your take on this?

We'd love to be able to use `<Global/>` for AMP :)

No problems if that's through a prop. Something like:
```jsx
<Global ssrOnly="true" />
```
because we could do:
```jsx
<Global ssrOnly={isAmp} />
```

**Comment by mitchellhamilton** [comment]
> Seems like <Global/> is favoured API (and it's isomorphic) when using React, as all you have to do is use @emotion/core package. Seems weird to suggest using "raw" emotion for this - especially given that it wouldnt be discoverable by developers.

This use case is already not zero config since this is about using extractCritical and I don't see why we should expand the Global API when this behavior can already be achieved with injectGlobal, it's not a really common use case and it would be tying the external API of something in @emotion/core with emotion-server which I'd rather not do.

> We used it in the past and we suffered from the SSR leakage explained in this issue:
> #573
> 
> Is that problem fixed in emotion 10?

You could do something like this with next as an `_document` file and you wouldn't have the leakage problem.

```jsx
import Document from "next/document";
import { CacheProvider } from "@emotion/core";
import createEmotion from "create-emotion";
import createEmotionServer from "create-emotion-server";

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    let { cache, injectGlobal } = createEmotion();

    // you could provide this function to other components via context if you wanted to
    injectGlobal({
      html: {
        color: "green"
      }
    });
    const initialProps = await Document.getInitialProps({
      ...ctx,
      renderPage: () =>
        ctx.renderPage({
          enhanceApp: App => props => (
            <CacheProvider value={cache}>
              <App {...props} />
            </CacheProvider>
          )
        })
    });
    let { css } = createEmotionServer(cache).extractCritical(initialProps.html);

    return {
      ...initialProps,
      styles: (
        <>
          {initialProps.styles}
          {css}
        </>
      )
    };
  }
}
```

**Comment by Andarist** [comment]
> This use case is already not zero config since this is about using extractCritical

I wasn't strictly referring to 0 config here in a sense that there is no setup, but rather in general sense that in this case it seems that user has to be aware of additional things and handle them on their own in a special way. A natural thing to expect is that injectGlobal and Global would behave the same in terms of CSS extraction. This seems like an API flaw to me.

> and I don't see why we should expand the Global API when this behavior can already be achieved with injectGlobal, it's not a really common use case and it would be tying the external API of something in @emotion/core with emotion-server which I'd rather not do.

How would it tie any external API in emotion packages? We are talking here strictly about cooperation between different emotion packages.

> You could do something like this with next as an _document file and you wouldn't have the leakage problem.

The proposed solution IMHO only showcase the problem at hand - it seems that a user has to do extra hoops to avoid memory leakage (which is rather not something they should be concerned with) in addition to having to learn 2 very similar APIs and the distinction between them in terms of SSR/prerendering, which is not apparent at first sight.

**Comment by luisherranz** [comment]
Hey guys, thanks for your time here and sorry to bother you again, but we need to make a decision so we'd love to know if this is somehow going to be fixed in Emotion (if that's the case, we can try to help) or we need to either switch to a different library or implement a workaround based on `injectGlobal`.

**Comment by mitchellhamilton** [comment]
Did some more thinking about the problem, I implemented a solution in #1443, I'll merge it soon and do a release.

**Comment by luisherranz** [comment]
Amazing. Thank you so much @mitchellhamilton for providing a solution that works with `<Global>`.

Once the release is out we'll test it out and report back the results.

**Comment by NNSTH** [comment]
Hey @luisherranz ,

I'm new to emotion, and want to switch some of our pages to AMP valid pages.
Can you describe the way you've used emotion in this case?

thanks in advance!

**Comment by luisherranz** [comment]
Sure.

You have to import this
```js
import createCache from "@emotion/cache";
import createEmotionServer from "create-emotion-server";
```

then, create an emotion server using a cache:
```js
// Create emotion server and cache.
const cache = createCache();
const { extractCritical } = createEmotionServer(cache);
```

use extractCritical in the html returned by React:
```js
const html = renderToStaticMarkup(App);
const emotion = extractCritical(html);
```

and finally use `emotion.css` and `emotion.html` to populate your HTML template.

**Comment by NNSTH** [comment]
thank you very much @luisherranz ! now I can use emotion with my AMP pages!

**Comment by ribeirogab** [comment]
Sorry for the stupidity, but I couldn't use the @emotion on AMP pages with Next.js. Can anyone help me with an example?
