### ISSUE TITLE
Next.js SSR composition not removing redundant declarations

### ISSUE THREAD

**Issue by baldurh** [emotion-js/emotion#1425]
**Current behavior:**

The css generated during Next.js SSR is not optimized like it should be. There are redundant declarations that should be omitted.

Code:
![image](https://user-images.githubusercontent.com/1823617/60521378-af549080-9cd6-11e9-881f-0e18394dc21e.png)
Result (on production):
![image](https://user-images.githubusercontent.com/1823617/60521240-6dc3e580-9cd6-11e9-904b-fc35e2eabac8.png)

**To reproduce:**
Repo: https://github.com/baldurh/nextjs-emotion-ssr-example
Running example: https://nextjs-emotion-ssr-example.herokuapp.com

1. Look at the css of any of the elements on the index page. Notice that it contains redundant declarations.
![image](https://user-images.githubusercontent.com/1823617/60520986-e4141800-9cd5-11e9-8f4f-0f95388c3c94.png)

2. Click the link Foo to view a client-side rendered page and notice that the styles are optimized in that case.
![image](https://user-images.githubusercontent.com/1823617/60521063-1291f300-9cd6-11e9-9438-21aea4a141fb.png)

**Expected behavior:**

SSR rendering should produce optimized css where redundant declarations have been omitted.

**Environment information:**

```JSON
  "dependencies": {
    "@emotion/core": "10.0.14",
    "@emotion/styled": "10.0.14",
    "babel-plugin-emotion": "10.0.14",
    "next": "8.1.0",
    "react": "16.8.6",
    "react-dom": "16.8.6"
  },
  "devDependencies": {
    "@emotion/babel-preset-css-prop": "10.0.14"
  }
```

**Comment by baldurh** [comment]
Can someone point me to the code where the optimisation happens? Where redundant declarations are removed?

**Comment by Andarist** [comment]
This is something which we deliberately not optimizing because it would come at expanse of runtime performance

**Comment by baldurh** [comment]
> This is something which we deliberately not optimizing because it would come at expanse of runtime performance

Oh I see. Never mind then 😅
