### ISSUE TITLE
Provide default export for @emotion/core

### ISSUE THREAD

**Issue by jsejcksn** [emotion-js/emotion#1426]
It would be nice to provide a default export for the case where destructuring is desired—since named imports don't presently destructure. It would eliminate a few characters during the import statement:

```js
// Right now
import * as Emotion from '@emotion/core';

// Requested
import Emotion from '@emotion/core';

const {jsx: j} = Emotion;
```

**Comment by Andarist** [comment]
You are requesting exporting an object under a default export, this is an anti-pattern and should be avoided.

If you want to rename imported thing you can do this:
```js
import { jsx as j } from '@emotion/core'
```

**Comment by jsejcksn** [comment]
Thank you for responding. I didn't know it is possible to use the `as` keyword to alias named imports.
