### ISSUE TITLE
Make an alias of `css` for the agnostic library

### ISSUE THREAD

**Issue by marcotoniut** [emotion-js/emotion#1433]
The problem right now is that, given the inadequacies of using some of react emotion's features for existing components, I find myself installing both versions of the library, and using them interchangeably as I see fit.

However this spawns all sorts of conflicts and points of confusion for me, whenever I want to use the `css` function from both libraries. This could be easily circumvented by creating an alias for the function that could be called `className`.

Support for this functionality in react's package, as well as `cx`, could also be a huge aid.

**Comment by FezVrasta** [comment]
You can use the ClassName component from @emotion/core 

Mixing the two libraries is not advised because the “css” from the basic emotion library can’t hook into the React context and theme

**Comment by Andarist** [comment]
Actually we could rename vanilla emotion's `css` to `className` - this would be slightly more appropriate right now. Problem is that i.e. Prettier would not recognize the new name and wouldn't format the contained string styles. This is a problem we are not able to fix here and AFAIK Prettier doesn't want to extend set of things they consider as containing CSS - sadly they don't even format `keyframes`. It's also not only about Prettier - but things like VSCode extension and such.

I believe we don't want to export an alias for this - as that could only bring more confusion to the table. For the time being, we have to decline this feature request - even though I believe it has some merit in wanting to be able to differentiate easier between those 2 packages.
