### ISSUE TITLE
DX improvement: `content` in pseudo-elements should auto-quote string values

### ISSUE THREAD

**Issue by jlengstorf** [emotion-js/emotion#1435]
**The problem**

The requirement to double-quote `content` values leads to hard-to-spot bugs in pseudo-elements.

For example, this code won't work:

```jsx
<div
  css={{
    '::after': {
      content: ' ',
    }
  }}
/>
```

The required double quotes are tricky to spot and unintuitive:

```diff
  <div
    css={{
      '::after': {
-       content: ' ',
+       content: '" "',
      }
    }}
  />
```

**Proposed solution**

I _think_ a backwards-compatible workaround for this would be adding a check like this for `content` values:

```js
const wrapString = str => {
  const raw = str.match(/^['"].*?['"]$/) ? JSON.parse(str) : str;
  return JSON.stringify(raw);
}
```

```js
wrapString('test'); //=> "test"
wrapString('"test"'); //=> "test"
wrapString(''); //=> ""
wrapString('""'); //=> ""
```

This would be a great DX improvement and would avoid surprising, hard-to-track bugs (anecdotally, I'm here because I spent an hour debugging this earlier). 😄 

**Alternative solutions**

I imagine there are lots of different ways to solve this problem — the above is just the first thing that came to mind.

**Comment by Andarist** [comment]
We try to warn users about this - https://github.com/emotion-js/emotion/blob/61e61edceb0f742f614bb5285bea923f8427b771/packages/serialize/src/index.js#L90

Could you prepare a codesandbox showcasing when this has failed to help you fix a problem?

**Comment by jlengstorf** [comment]
@Andarist tools that implement Emotion under the hood may swallow this error (in my case I'm using `theme-ui` in Gatsby, so that warning never showed up). In general, is there an edge case I'm thinking of that makes this improvement a bad idea?

**Comment by jlengstorf** [comment]
Another option could be to keep that warning, but add the quotes so things don't fail?

```diff
    if (key === 'content') {
      if (
        typeof value !== 'string' ||
        (contentValues.indexOf(value) === -1 &&
          !contentValuePattern.test(value) &&
          (value.charAt(0) !== value.charAt(value.length - 1) ||
            (value.charAt(0) !== '"' && value.charAt(0) !== "'")))
      ) {
        console.error(
          `You seem to be using a value for 'content' without quotes, try replacing it with \`content: '"${value}"'\``
        )
+
+       key = `"${key}"`
      }
    }
```

**Comment by Andarist** [comment]
This is dev-only path, we don't quite want to maintain whitelisting allowed patterns - it's a moving target, costs bundlesize & runtime performance. It's easier to point to potential dev mistake during development than to fix up this problem behind the scenes. 

I don't think using theme-ui should cause our friendly dev warnings to be swallowed - if you could prepare a repro case maybe we could figure out where this happens and fix it there?

**Comment by jlengstorf** [comment]
@Andarist I’m not sure I agree that `content` is a moving target; that spec has been stable for a long time. That being said, I can understand the concern about bundle size. My own philosophy is that confusing errors damage the developer experience and cost more in the long run, but I respect that not everyone would agree with that take.

Some work to reproduce shows that the output is actually showing up, but I completely missed it.

- Gatsby shows it in the build log (https://glitch.com/edit/#!/cute-pie — see "log" under Tools)
- Theme UI shows it in the browser console (https://gaudy-football.glitch.me/)

While we could just chalk this up to me needing to be better at debugging, the fact that I missed this (along with the others who opened issues when they missed the warnings) makes what I'd consider to be a pretty strong case for the warning being insufficient.

If fixing the content value isn't in the cards, perhaps throwing an actual error so it's extremely obvious what went wrong is better?

**Comment by Andarist** [comment]
> My own philosophy is that confusing errors damage the developer experience and cost more in the long run, but I respect that not everyone would agree with that take.

Well, in this case, the logged error is rather well-formed, certainly it ain't confusing. I understand that logs can always be missed though.

> the fact that I missed this (along with the others who opened issues when they missed the warnings) makes what I'd consider to be a pretty strong case for the warning being insufficient.

Well - hard to quantify this, there are probably much more people which made a mistake and a warning has guided them quickly towards the fix. I'm not saying this to dismiss your concerns or anything, just stating that those things are hard to quantify like this.

> If fixing the content value isn't in the cards, perhaps throwing an actual error so it's extremely obvious what went wrong is better?

For me this wouldn't be much of a problem, but there are also people with strong opinions that dev and prod behavior should be the same - and we certainly don't want to validate this in prod (if we stick to not "fixing" this), so throwing in dev vs swallowing the problem in prod could not be seen as appropriate.

Truth to be told - I'm not sure about the exact reasons why this has been decided to be a warning and not something which we could fix on our side. This was @mitchellhamilton's decision, so maybe he could pitch in here with arguments. I'm not having strong opinions on this one - personally a dev warning here is enough for me, but I don't plan to die on this hill 😉

**Comment by Andarist** [comment]
I think it's OK to make this an error - but I prefer doing it in the next major version (v11), which I work on right now.

Thanks for the feedback!

**Comment by mitchellhamilton** [comment]
The reasoning for not fixing this automatically is because of the bundle size costs, I'm totally happy with making this an error in dev though

**Comment by Andarist** [comment]
Closed by https://github.com/emotion-js/emotion/pull/1611
