### ISSUE TITLE
babel-preset-css-prop in cra, breaks ie11

### ISSUE THREAD

**Issue by d3bgger** [emotion-js/emotion#1436]
**Current behavior:**

In a create react app project, with react polyfills to support ie 11, i added the "@emotion/babel-preset-css-prop" preset. This break ie 11.

**To reproduce:**

1. Create a clean create react app project
2. Add support for ie11 (https://stackoverflow.com/a/55967049/1816713)
3. Eject
4. Add @emotion/babel-preset-css-prop preset
5. Run on ie11. Nothing renders and console reports errors: 

`Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
`

You can clone this project (clean cra project, ejected, and added emotion) and see that it doesn't work in ie11
https://github.com/d3bgger/react-test

adding `<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>` in the html page that loads the react project, makes ie11 working, but this seems hacky. Polyfills that are inside the react project should work.

**Expected behavior:**

ie11 and polyfills shouldn't be affected by @emotion/babel-preset-css-prop preset.

**Environment information:**

- `create react app` version: 3.0.1
- `react` version: 16.8.6
- `emotion` version: 10.0.14

**Comment by Andarist** [comment]
I've prepared a fix for this - https://github.com/emotion-js/emotion/pull/1576 . But keep in mind that if you mess up order imports it's still possible to break IE11. We advise splitting polyfills & entry file to avoid this completely.
