### ISSUE TITLE
create-emotion@10 cx TypeScript signature not backwards compatible

### ISSUE THREAD

**Issue by mgroenhoff** [emotion-js/emotion#1437]
**Current behavior:**

When passing an object as an argument to `cx(...)` it used to be possible to pass not only string values. The current definition does not allow that anymore.
https://github.com/emotion-js/emotion/blob/1b7333a837813949fa4fe301bb0d53887e784b8b/packages/create-emotion/types/index.d.ts#L18-L24

**Expected behavior:**

I would suggest changing the object signature to include the other primitive types as well.
```ts
export type ClassNamesArg =
  | undefined
  | null
  | string
  | boolean
  | { [className: string]: undefined | null | string | boolean; } // <--
  | ArrayClassNamesArg
```

**Environment information:**

- `create-emotion` version: 10

**Comment by Andarist** [comment]
Could you paste in the code you write which those typings dont satisfy?

**Comment by mgroenhoff** [comment]
All of these really, whatever is not a boolean. It used to allow all these types (which where implicitly converted to a boolean).
```ts
// These should all evaluate to false
cx({ foo: "" });
cx({ foo: 0 });
cx({ foo: undefined });
cx({ foo: null });
```

**Comment by Andarist** [comment]
Could you post a real-life use case for this? When the value is not yet evaluated to 0/''/undefined/null?

**Comment by mgroenhoff** [comment]
These values can come out of basic boolean expressions if not explicitly converted to a boolean (wrapped within `!!(...)`).

```ts
let obj: { someBooleanProperty: boolean; } | undefined;
let result = obj && obj.someBooleanProperty; // result may be undefined, true or false depending on the value of obj

let str: string | undefined;
let result = str && str.length > 2; // result may be "", undefined, true or false depending on the value of str
```

**Comment by mgroenhoff** [comment]
Oh and one other thing, if you use React and TypeScript and try to infer the types of props using `prop-types`, the `Requireable` interface makes a type `T` optional by making a new type `T | null | undefined` so allowing `undefined` and `null` is an easy way to use props directly  `cx({ foo: props.optionalProp })`

**Comment by Andarist** [comment]
Well - I was hoping for a more concrete code example involving `cx` usage. I assume I know what you have in mind in regards to props being a base for `cx` "condition", but wanted to get a concrete example to get a better understanding of what you are struggling with. I know how coercion and everything works in JavaScript 😉 

>  the Requireable interface makes a type T optional by making a new type T | null | undefined so allowing undefined and null is an easy way to use props directly cx({ foo: props.optionalProp })

What `Requireable` is? Did you refer to TypeScript's `Required`? Doesn't match the description, but I also can't find any reference to `Requireable`.

**Comment by mgroenhoff** [comment]
The point i am trying to make is that it is not bound to specific use cases. I came across this issue while upgrading our code base from using emotion 9 to 10 and i had to fix **a lot** of these by explicitly converting them to a boolean type.

Maybe i was not clear enough about the `Requireable` interface. It comes from the `prop-types` package. I was walking about a feature of TypeScript+React to automatically infer the type of `props` by looking at the `propTypes` and `defaultProps` (see https://dev.to/busypeoples/notes-on-typescript-inferring-react-proptypes-1g88 to quickly get an idea of what i am talking about.

The type of a propTypes member might end up being `PropTypes.Requireable<boolean>` (return type of `PropTypes.bool`) which simply means that is must be a boolean and it is optional. The name might be a little confusing but it simply means that you can make it required by using the `isRequired` property on the validator (return type of `PropTypes.bool.isRequired`).

When you infer the prop type for a prop which has a validator with type `PropTypes.Requireable<boolean>` you and up with the resulting type `boolean | null | undefined`.

**Comment by Andarist** [comment]
> I was walking about a feature of TypeScript+React to automatically infer the type of props by looking at the propTypes and defaultProps (see https://dev.to/busypeoples/notes-on-typescript-inferring-react-proptypes-1g88 to quickly get an idea of what i am talking about.

Oh, that's wild! Thanks for sharing.

> The point i am trying to make is that it is not bound to specific use cases. I came across this issue while upgrading our code base from using emotion 9 to 10 and i had to fix a lot of these by explicitly converting them to a boolean type.

Well - I believe that concrete use cases would be really helpful for this because we have to add a type test to make sure this doesn't break in the future and those should reflect real-life scenarios.

I believe that static typing can often constrain what is actually possible at runtime. Taking this as an example - even as you probably can pass an empty string or 0 there and have it working, we shouldn't allow string and number at those positions. For those, I strongly believe we should enforce boolean casting on the user. 

Similarly, React's `createRef` API returns (according to TS types) a ref object which you can't manipulate (you can't write to `.current` property), but actually at runtime this is very much possible (and even has to be because React needs to be able to write to it). Besides providing correctness types can also guide people for using things "like intended".

I'm not saying we shouldn't allow null & undefined at those positions, just that it would be good to assess that based on real-life scenarios.

**Comment by mgroenhoff** [comment]
Actually, there is an overload for createRef that creates a mutable ref, it is even in the React documentation for hooks.

If you indeed choose to only allow boolean types you may want to restrict the types of other arguments to cx as well for consistency.

**Comment by Andarist** [comment]
I was strictly referring to createRef - it is very similar to useRef, but their types differ (for mentioned reasons - useRef can return a mutable object, while createRef doesn't).

> If you indeed choose to only allow boolean types you may want to restrict the types of other arguments to cx as well for consistency.

I'm not saying I want only boolean types there, I'm somewhat fine with allowing null & undefined at positions we discuss - I'd only like to add this after having some real-life scenario presented which would justify this change.

**Comment by mgroenhoff** [comment]
Like i tried to explain, we have a lot of props that can be either a boolean, null or undefined. We currently pass them directly because they just coerce to false.
```ts
interface Props {
	className?: string | null;
	active?: boolean | null;
	changed?: boolean | null;
	disabled?: boolean | null;
	invalid?: boolean | null;
	open?: boolean | null;
}
declare const props: Props;
const className = cx(props.className, {
	active: props.active,
	changed: props.changed,
	disabled: props.disabled,
	invalid: props.invalid,
	open: props.open
});
```

I didn't think this backwards incompatibility thing would be such a big issue. If you are still not convinced then that's ok but i might want to put my time into fixing the errors that are present because of this.

**Comment by Andarist** [comment]
And this is what I call a real-life scenario 😉 This certainly convinces me that `undefined` should be accepted - `null` ofc can be allowed too.
