### ISSUE TITLE
[v10] Keyframes broken using object notation in styled component

### ISSUE THREAD

**Issue by mattkrick** [emotion-js/emotion#1442]
**Current behavior:**

After migration code to v10, calling `toString()` on a keyframe animation is required to regain keyframe functionality.

Similar to #1066, but since this is a styled component & a loss of functionality, I _think_ it's a bug, not just a documentation issue.

**To reproduce:**
```
const keyframesRotate = keyframes`
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}`

const SVG = styled('svg')({
  animationDuration: '3s',
  animationName: keyframesRotate,
}))
```

**Expected behavior:**

the same result as this: 

```
const SVG = styled('svg')({
  animationName: keyframesRotate.toString(),
}))
```

- `react` version: all
- `emotion` version: 10.0.14

**Comment by Andarist** [comment]
This has been fixed by https://github.com/emotion-js/emotion/pull/1414 and is already released. See demo https://codesandbox.io/s/emotion-8k5fd
