### ISSUE TITLE
Does @emotion/native depend on @emtion/core?

### ISSUE THREAD

**Issue by tian-yi** [emotion-js/emotion#1452]
**Description:**
In the install section of "@emtion/native", it just says to install `@emotion/native`, but when I've done that, it gives this  error:

> Unable to resolve "@emotion/core" from "node_modules/@emotion/primitives-core/dist/primitives-core.browser.cjs.js"

It works after installing `@emtion/core`. Maybe I should have installed `@emtion/core`, but in the example `import styled, { css } from '@emotion/native'` it looks like I do not need the `@emotion/core` package. 

So I wonder If I am doing something wrong as in it should work without installing the `@emtion/core` or maybe the doc can be improved? I can send in a PR to improve the doc if it's the latter. 

**Documentation links:**
https://emotion.sh/docs/@emotion/native

Thanks

**Comment by Andarist** [comment]
`@emotion/primitives-core` depends on `ThemeContext` which is an export of `@emotion/core`. Could you prepare a PR fixing installation instruction in the docs?
