### ISSUE TITLE
Using the css prop to pass options to styles with TypeScript

### ISSUE THREAD

**Issue by vladinator1000** [emotion-js/emotion#1456]
Hey y'all, I'm getting super close to having a nice example of how to use the css prop in TypeScript. I'd like to open a PR that adds some docs around it but I can't figure out how to make it work with extra props / options you might want to add.

**Description:**

Basically, I want the styles to have autocomplete and be able to accept extra options in addition to the theme:

```ts
import { CSSObject } from "@emotion/core";

type ThemedStyle = (theme: Theme) => CSSObject | CSSObject;
type Styles = Record<string, ThemedStyle>;

const styles: Styles = {
  // This works
  button: (theme) => ({
    fontSize: theme.sizes.M,
    padding: theme.sizes.S,
  }),

  // This doesn't
  title: ({ isToggled }) => ({ sizes }) => ({
    color: isToggled ? "palevioletred" : "darkcyan",
    marginBottom: theme.sizes.S
  }),
};

const App: React.FC = () => {
  const [isToggled, setToggled] = useState(false);

  return (
    <div className="App">
      <h1 css={styles.title({ isToggled })}>Emotion with TypeScript</h1>
      <button css={styles.button} onClick={() => setToggled(!isToggled)}>
        Toggle Color
      </button>
    </div>
  );
};
```

Here is a **Codesandbox** link that reproduces the issue:
https://codesandbox.io/s/emotion-typescript-example-wy1oq

How would you type that thing to also accept a style with options?

**Comment by savovs** [comment]
So far I've been doing 
```ts
import { Styles, StyleWithOptions } from "../style/types";

type Options = { isToggled: boolean };

const title: StyleWithOptions<Options> = ({ isToggled }) => ({ sizes }) => ({
  color: isToggled ? "palevioletred" : "darkcyan",
  marginBottom: sizes.S
});

const styles: Styles = {
  // ...
};

export default { title, ...styles };
```

where the styles with options type is

```ts
export type StyleWithOptions<T> = (options: T) => ThemedStyle | CSSObject
```

Does this look right?

**Comment by Andarist** [comment]
I'm not sure what is the original issue here - on your sandbox I see `.title` working but not `.button`. And this is a TS issue - you cannot have non-concrete Styles transfer `button` property when spreading because it doesn exist on Styles.

**Comment by Andarist** [comment]
Going to close this issue because it seems more like a general TS question rather than emotion-specific issue. If you still have any problems with emotion, please raise new issue and I will gladly answer and try to help you.
