### ISSUE TITLE
theme property in styled component is object instead of any

### ISSUE THREAD

**Issue by maleetz** [emotion-js/emotion#1457]
According to the documentation (https://emotion.sh/docs/typescript#define-a-theme)

> By default, props.theme has an any type annotation and works without any errors. However, you can define a theme type by creating another styled instance.

Possibly a result of https://github.com/emotion-js/emotion/pull/1421/commits/a1f114392da2bad2fc0e15909fea39795458a709, the theme prop type in a styled component changed from `any` to `object`, which essentially forces you to use a custom styled instance and breaks the documentation above.

**To reproduce:**

https://codesandbox.io/s/emotion-issue-template-qbwyb
![image](https://user-images.githubusercontent.com/16912745/62415652-314c1800-b5fb-11e9-974c-73d06a61f3e1.png)

**Expected behavior:**

By default, props.theme has an any type annotation and works without any errors. 

**Environment information:**

- `@emotion/core` version: 10.0.15
- `@emotion/css` version: 10.0.14
- `@emotion/styled` version: 10.0.15

**Comment by pleunv** [comment]
Running into the same issue after trying to upgrade from `@emotion/core@10.0.10` and `@emotion/styled@10.0.12` to latest. This is breaking all of our custom `Theme` typings and is forcing us to revert. Any chance this change can be rolled back?

**Comment by pleunv** [comment]
Should perhaps get @Andarist involved 😄 
Something we do quite often to get our `theme` props typed is something similar to the following:

```
import styled from '@emotion/styled';
import { Theme } from 'theme';

const SectionHeaderWrapper = styled.div<{ textColor: string }>`
  color: ${({ textColor }) => textColor};
  text-align: center;
  padding-bottom: 1.5rem;

  @media (min-width: ${({ theme }: { theme: Theme }) => theme.breakpoints.md}) {
    padding-bottom: 2rem;
  }
`;

export default SectionHeaderWrapper;
```
As of https://github.com/emotion-js/emotion/commit/a1f114392da2bad2fc0e15909fea39795458a709 this doesn't work anymore as theme is now typed as `object` and can't be assigned to `Theme`. I'm hoping there's a different way to achieve a similar result without having to resort to creating a customStyled instance.

**Comment by Andarist** [comment]
> Side question: does anyone know if custom Theme types, custom instances and the babel preset play nicely together these days? Last time I checked this wasn't the case and that's one of the reasons we resorted to the above approach.

Not yet - I hope to work on resolving this soon~. We could certainly use some help regarding that if you'd like to get involved.

As to your issue - there is an ongoing effort (https://github.com/emotion-js/emotion/pull/1501) to rework the types and I believe it's going to fix your problem.

**Comment by Andarist** [comment]
This will get resolved~ in v11 by https://github.com/emotion-js/emotion/pull/1501 .
