### ISSUE TITLE
Preact X + Emotion 10 + Babel Plugin autoLabel not working

### ISSUE THREAD

**Issue by sirphoenix** [emotion-js/emotion#1461]
**Current behavior:**

Using latest Preact 10.rc1 with preact-cli, emotion-js 10.0.15 and the babel plugin does not generate correct classNames for components.

**To reproduce:**

Check out this codesandbox (which isn't working online).
Run it locally where it should render without errors:
https://codesandbox.io/s/preact-emotion-babel-plugin-v9zlv

1. Page renders correctly with styles set on h1
2. check class tag of the h1 element
3. only has the automatic generated class "css-xxxx"

**Expected behavior:**
1. class tag of h1 should have component name set

Working previously with preact 8.x and emotion 9.x where all classNames had their corresponding component names when autoLabel was true.

**Environment information:**

see package.json in codesandbox
- `preact` version: 10.0.0-rc.1
- `emotion` version: 10.0.15

**Comment by jooj123** [comment]
I thought they dropped preact support in 10 ? https://github.com/emotion-js/emotion/pull/896

**Comment by developit** [comment]
Hi there,

Emotion works fine with Preact X, your `.babelrc` is just broken since it is removing a bunch of required Babel plugins Preact CLI ships with by default.  Replace the `.babelrc` with a `preact.config.js` containing this:

```js
// preact.config.js
export default (config, env, helpers) => {
	const babelConfig = helpers.getLoadersByName(config, 'babel-loader')[0].rule.options;
	babelConfig.plugins.push(
		['emotion', {
			sourceMap: true,
			autoLabel: true
		}]
	);
};
```

Working version of your demo: https://codesandbox.io/s/preact-x-emotion-l6toy

**Comment by FezVrasta** [comment]
Thanks @developit for the help, closing the issue here!
