### ISSUE TITLE
jest-emotion: TypeError: node.getAttribute is not a function

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#1463]
**Current behavior:**

On some specific React components/trees, the jest-emotion serializer throws an error: `TypeError: node.getAttribute is not a function`.

If I comment out the `jest-emotion` serializer from `setupTests.js` the snapshot is written properly.

**To reproduce:**

1. Clone https://github.com/quid/refraction
2. `cd refraction`
3. `yarn`
4. `git checkout 6b7a3f0746510779191d5547f357d9afca99227b`
5. `cd packages/expandable-table`
6. `yarn test`

**Expected behavior:**

A snapshot should be written.

**Environment information:**

- `react` version: 16
- `emotion` version: 10.0.15

**Comment by liamcmitchell-sc** [comment]
I managed to track this down to serializing fragments in deep mode: https://github.com/emotion-js/emotion/pull/1477/files#diff-1c3f3af1ec5f3c0a2955f0700c9520f6R115-R129

**Comment by FezVrasta** [comment]
Thank you so much!!! ❤️

**Comment by dherault** [comment]
This error popped again:

I had:
```jsx
const component = renderer.create(
  <ThemeProvider theme={theme}>
    <Div color-mobile="blue">Honorable</Div>,
  </ThemeProvider>
)
```
Which triggered the error.

But this worked:
```jsx
const component = renderer.create(
  <ThemeProvider theme={theme}>
    <Div color-mobile="blue">Honorable</Div>
  </ThemeProvider>
)
```

(Mind the comma)

Hope this helps.

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by dherault** [comment]
Ofc! Please checkout https://github.com/dherault/honorable
Working commit: `b2d778740ce27c9b3683512e7a276aff969da13c`
From that commit:
- Run `npm i && cd packages/honorable && npm i`
- Delete the whole file content of `packages/honorable/tests/components/__snapshots__/tags.test.tsx.snap`
- Head to `packages/honorable/tests/components/tags.test.tsx`
- Add a comma where my previous post shown
- Run `npm run test`

You should be getting that error:
<img width="578" alt="image" src="https://user-images.githubusercontent.com/4154003/168310953-321ba849-7bdd-45dc-a2f0-a2a66f6bc083.png">

**Comment by dherault** [comment]
The error clears on two conditions:
- Remove the comma (feels like a bug)
- Rewrite the snapshots

**Comment by Andarist** [comment]
You might not have pushed out this commit - it's not available on GitHub and I can't checkout it.

**Comment by dherault** [comment]
Should be good now.

**Comment by Andarist** [comment]
This comma is not insignificant. We can confirm this by inspecting the transformed output of this JSX:
```jsx
// input
const component = renderer.create(
  <ThemeProvider theme={theme}>
    <Div color-mobile="blue">Honorable</Div>,
  </ThemeProvider>
);

// output
const component = renderer.create(
  React.createElement(
    ThemeProvider,
    { theme: theme },
    React.createElement(Div, { "color-mobile": "blue" }, "Honorable"),
    ","
  )
);
```

As we may see here - the `comma` is present in the `children` variadic argument of the `React.createElement` call. This means that you have passed an array of nodes to the `toHaveStyleRule` and that is a problem because it won't be able (and shouldn't be able) to handle this.

So I don't think this is a problem in our code - but what we could do is to introduce an explicit error message for a situation like this.
