### ISSUE TITLE
@emotion/babel-preset-css-prop documentation is inconsistent.

### ISSUE THREAD

**Issue by thomasobrien99** [emotion-js/emotion#1464]
**Description:**
@emotion/babel-preset-css-prop documentation is inconsistent.
**Documentation links:**
https://emotion.sh/docs/@emotion/babel-preset-css-prop#usage
and 
https://github.com/emotion-js/emotion/tree/master/packages/babel-preset-css-prop#usage

give the instructions: 

> If you use @babel/preset-react or @babel/preset-typescript ensure that @emotion/babel-preset-css-prop is inserted before them in your babel config.

while here:
https://www.npmjs.com/package/@emotion/babel-preset-css-prop

Says 

>  If you use @babel/preset-react ensure that @emotion/babel-preset-css-props is inserted after @babel/preset-react.

=======================================

I messed around with the first for a while before finding the second, which actually worked for me. I want to be sure that's correct for others before opening a PR.

Thanks!

**Comment by pleunv** [comment]
I also noticed that the docs were changed recently but noticed that it does in fact need to be *behind* preset-react & preset-typescript to work. I'm guessing this ambiguity might be due to babel applying presets right to left, instead of left to right?

**Comment by thomasobrien99** [comment]
Is "behind" to the left or right in this case? It only worked for me after moving ` @emotion/babel-preset-css-prop` to the right.
