### ISSUE TITLE
Automatically strip out selectors referencing `null` values

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#1466]
**The problem**

I often need to generate a selector starting from some of the component properties. And in some cases, I also desire not to select anything at all (not define the selector).

Right now, the process is very verbose, because we have to do this:

```jsx
const SubComponent = styled.div``;
const SUB_SELECTOR = props => props.open ? SubComponent : null;

const Component = styled.div`
  ${props => {
    if (SUB_SELECTOR(props) {
      return css`
        ${SUB_SELECTOR(props)} {
          color: red;
        }
      `
    }
  }
`;
```

**Proposed solution**

What I'd like to propose, is to tell Emotion to completely skip a rules block if its selector is `null` (or any falsy value maybe).

This would allow the code to be simplified as shown below:

```jsx
const SubComponent = styled.div``;
const SUB_SELECTOR = props => props.open ? SubComponent : null;

const Component = styled.div`
  ${SUB_SELECTOR} {
    color: red;
  }
`;
```

**Alternative solutions**

I can't think of any alternative solution to this problem, right now we have to either use the very verbose approach, or make up an invalid selector so that the compiled CSS looks like `.123 { color: red; }`

**Additional context**

N/A

**Comment by Andarist** [comment]
We at the moment just assume that `null` kinda means an empty string and this comes handy in bunch of composition situations. Most importantly - it behaves the same way everywhere and for mentioned composition situations we definitely want to preserve current behavior. What you propose would have to be context~ specific - would introduce lookaheads during serialization and brings unecessary complexity to the implementation. I believe this feature request has to be declined - especially that this is just about some sugar syntax, not anything that would bring any new features which cannot be achieved with current APIs.
