### ISSUE TITLE
JSX pragma slow in dev mode

### ISSUE THREAD

**Issue by pomber** [emotion-js/emotion#1467]
**Current behavior:**

In dev mode, using the jsx pragma, my app is taking several seconds to render.

**To reproduce:**

Render an app with a lot of react elements using the jsx pragma

**Environment information:**

- `react` version: 16.8.6
- `@emotion/core` version: 10.0.14

Actually, I'm using it via [`theme-ui` with the `sx` prop](https://theme-ui.com/getting-started#sx-prop), but after profiling I found the bottleneck is [this line from emotion core](https://github.com/emotion-js/emotion/blob/4a3b18a2c4a42823dd6a0c2f2d7ae8fc2df2caab/packages/core/src/jsx.js#L154):

![image](https://user-images.githubusercontent.com/1911623/62824540-0dab4380-bba0-11e9-8088-fcd1636ec204.png)

I'm creating the issue just in case there's some easy optimization to replace the `new Error` bottleneck. Feel free to close it otherwise.

**Comment by Andarist** [comment]
Do you observe decreased performance on initial render, on rerenders or on both?

**Comment by pomber** [comment]
on initial render, but i'm not rerendering the elements so I'm not sure if it's the same or not.

**Comment by Andarist** [comment]
Would you be willing to make a small experiment? Would be great to introduce a simple Map-based caching (using `type` as key) for those stack-retrieved labels. I wonder if that would help.

**Comment by Andarist** [comment]
I've tried but I can't repro this, for this to get fixed (or handled somehow) you'd have to share a repro case, share your environment (versions etc). Closing this for now as no enough information has been shared - but feel free to ask for reopening or just open a new issue if you still suffer from this.

**Comment by itsUndefined** [comment]
I am experiencing the same issue. Having to render 3 divs with css prop takes 2.5ms on development and 0.015ms on production.
