### ISSUE TITLE
Issue with nonce in SSR

### ISSUE THREAD

**Issue by flosch-hb** [emotion-js/emotion#1469]
I am facing an issue with SSR and a custom cache instance injected to `<CacheProvider />`.
It may be related to https://github.com/emotion-js/emotion/issues/1468, except I do not use Gatsby.

I need to specify a `nonce` since I have a `Content-Security-Policy` not allowing `'unsafe-inline'` for `style-src` (security requirement).

I have also read the discussion here: https://github.com/emotion-js/emotion/pull/1396

The SSR part works fine: styles are being injected with a nonce attribute (the response contains them).
But as soon as the client-side application loads and hydrate the styles, the nonce attributes are lost, and the styles are then blocked by the CSP.

I may be missing something obvious?
I was thinking that I may need to share the cache instance between the SSR and CSR parts somehow?

**Current behavior:**

```js
// server-side rendering
import crypto from 'crypto';
import React from 'react';
import { renderToString } from 'react-dom/server';
import createEmotionServer from 'create-emotion-server';
import createCache from '@emotion/cache';
import { CacheProvider } from '@emotion/core';

import App from '../../src/app/App.js';

const STYLES_NONCE = crypto.randomBytes(64).toString('base64');

const cache = createCache({
  nonce: STYLES_NONCE
});

const { renderStylesToString } = createEmotionServer(cache);

// rendering
const html = renderStylesToString(
  renderToString(
    <CacheProvider value={cache}>
      <App />
    </CacheProvider>
  )
);
```

```js
// client-side hydratation
const root = document.getElementById('app');

const render = renderMethod => renderMethod(
  <App />,
  root
);

if (root.hasChildNodes()) {
  render(ReactDOM.hydrate);
} else {
  render(ReactDOM.render);
}
```

**To reproduce:**

1. Clone the repository: https://github.com/flosch-hb/emotion-ssr-nonce-issue
2. yarn
3. yarn dev
4. Browse http://localhost:3000/
5. View page source and notice the nonce attributes
6. Open the console and notice the CSP errors

**Expected behavior:**

- Nonce attribute get preserved on hydrated styles

**Environment information:**

- `react` version: 16.9.0
- `emotion` version: 10.0.14
- `emotion-server` version: 10.0.14
- `@emotion/cache` version: 10.0.15
- `@emotion/core` version: 10.0.15
- `@emotion/styled` version: 10.0.15

**Comment by Andarist** [comment]
You have to use CacheProvider on your client side as well - you need to retrieve `nonce` somehow (e.g. by querying created meta tag) and pass it to `createCache`. The implementation should be pretty straightforward - I hope this comment helps you. If not - please answer back and we can discuss this more, but I'm closing this to clean up the issue tracker.

**Comment by caub** [comment]
Just a question pleasy guys, if I'm using emotion only on client-side, it generates inline `<style>`'s. Would the CacheProvider + nonce approach work? I wonder what is the security behind this, as any 3rd-party could also grab the nonce attribute I'm padding in the DOM and use it for themselves to comply with CSP

**Comment by Andarist** [comment]
Client-side Emotion doesn't generate inline styles - it typically injects style elements into `<head/>`. So I'm not entirely sure what you are asking for here - as the security implications of the CSP and nonce, this is somewhat out of the scope of this project. The subject can be researched elsewhere - there are a lot of online resources going into details of this approach.

**Comment by caub** [comment]
> it typically injects style elements into `<head/>`

yea sorry that's what I meant by inline `<style>` elements, not a `<link>` in short (like the difference between `<script>` and `<script src="..">` which have same CSP restrictions

**Comment by Andarist** [comment]
> I'm wondering and testing on how to pass a nonce to them

The nonce can be configured using a custom cache provided through CacheProvider.

**Comment by caub** [comment]
Ok thanks then
