### ISSUE TITLE
Initialize css-vars if possible

### ISSUE THREAD

**Issue by kylpo** [emotion-js/emotion#147]
- `emotion` 5.2.0:
- `react` 15.5.4:

### Relevant code.

```jsx
render() {
    const grow = 1

    return (
      <div
        css={`
          display: flex;
          flex-direction: column;
          position: relative;
          flex-shrink: 0;
          align-items: center;
          justify-content: center;
          flex-grow: ${grow};
        `}
      >
```

### What you did:
Set to `extract` mode.

### What happened:
![emotion-flash](https://user-images.githubusercontent.com/720177/28230546-4ccf7328-689c-11e7-9ecd-60c343d538b3.gif)

### Problem description:
If a variable is used in `css`, it is converted to a css-var. With SSR (in `external` mode), the page loads with all other styles shown, then javascript loads and injects a value for the associated css-var. This results in a style flash.

Above is a contrived example, but I could see it being a bigger issue for sharing constants.

For example,
```jsx
import COLOR from 'constants/color'

//...

<div
  css={`
    background-color: ${COLOR.RED};
  `}
/>
```

will see a paint flash on load.

### Suggested solution:
Initialize the generated css-var to `1` so that the style flash does not occur.

@hamlim said it best: "SSR ideally should evaluate that at first though right? It won’t change but should compile out initially"

*Note, this was briefly discussed in the slack channel from 8:00am on July 14, 2017*

**Comment by mitchellhamilton** [comment]
Just to confirm, you're doing SSR with extract mode? If so, how? (We've never done SSR with extract mode)

**Comment by hamlim** [comment]
Not actually sure if this is possible with just babel, I could be wrong but babel won't evaluate the code, so even if you could keep a map of identifiers and their initial values, and if you could inject those initial values in the second argument of the `var()` function, from a babel standpoint you will have no idea what is valid css.

For example:
```Javascript
const initValue = Math.pow(3, 2);
///
<div
  css={`
    height: ${initValue};
  `}
/>
/// ->
.selector { height: var(--css-[hash], Math.pow(3, 2)); }
```

**Comment by kylpo** [comment]
Hey, @mitchellhamilton. Yes, this is SSR with extract mode. I just followed Emotion's guide for SSR, but also enabled `extract`.

You're welcome to pull down this project's branch and tinker with it. Here are the relevant lines:

enable extract - https://github.com/constelation/static-starter/blob/emotion-flash/.babelrc#L7

combine into `style.css` - https://github.com/constelation/static-starter/blob/emotion-flash/webpack.config.js#L163

and include in the html template - https://github.com/constelation/static-starter/blob/emotion-flash/src/html.ejs#L38

**Comment by kylpo** [comment]
@hamlim, hmmm, I wonder if I can leverage babel-plugin-preval or something to initialize it then?

**Comment by kylpo** [comment]
@mitchellhamilton hmm, I could be wrong. Looks like I also still have `extractCritical` and `hydrate` in my code.

https://github.com/constelation/static-starter/blob/emotion-flash/src/entry.static.js#L23
https://github.com/constelation/static-starter/blob/emotion-flash/src/entry.client.js#L18

I'm about to head out camping for the weekend, but will dig in more when I return and report back.

**Comment by mitchellhamilton** [comment]
We could extract the vars and return them from `extractCritical`, it wouldn't really be critical css but it would solve this problem.

If anyone wants to submit a PR, change the regex on [this line](https://github.com/tkh44/emotion/blob/master/src/server.js#L6) to this
```regex
/(?:css|vars)(?:[a-zA-Z0-9-]*)-([a-zA-Z0-9]+)/gm
```

**Comment by mitchellhamilton** [comment]
Closing since we don't use css vars anymore.
