### ISSUE TITLE
Warn when multiple instances of Emotion are used

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#1470]
**The problem**

When multiple instances of Emotion are used (specifically, `@emotion/core`), theming and other parts of the library stop behaving correctly.

**Proposed solution**

Following the React way to solve this problem, we should put a check in Emotion to warn the user if multiple versions are being used together.

**Alternative solutions**

Alternatively we could store the whole Emotion context into a global variable and use it instead of defining a new one for each instance, but I'm not sure about possible downsides of this approach.

**Additional context**

For reference, here's the React PR where the check was first introduced: https://github.com/facebook/react/pull/3579

**Comment by willgriffiths** [comment]
Hi @FezVrasta, did you manage find a workaround? We're hitting what seems like a similar issue.

**Comment by Andarist** [comment]
@willgriffiths what's your exact issue? what kind of a problem are you facing?

**Comment by willgriffiths** [comment]
Thanks for your reply @Andarist We're moving from emotion 9 to emotion 10. And theming isn't working like it used to.

My colleague was explaining the issue to me: 
> There seems to be some kind of problem with emotion-theming and its context.
> If we use ThemeProvider and the useTheme hook from emotion-theming everything works
> ThemeProvider however doesn't interacting properly with the css prop from @emotion/core or styled from @emotion/styled
> The themes in them are coming through as an empty object, which seems to be the default
> I think this is due to emotion 10 switching to the new way of using context, where instead of tying it to an id it ties it to the Context object, and I guess @emotion/styled and emotion-theming aren't using the same Context?
>As far as i can tell the context is made in @emotion/core. So maybe theres multiple copies of it running at once? Im unsure how to find that out

```
@emotion/core: 10.0.17
@emotion/styled: 10.0.17
emotion-theming: 10.0.19
```

We can setup a repro. And also also make a seperate issue once we have more info. :)

**Comment by FezVrasta** [comment]
In any case, this issue aims to provide a way to easily debug the issue, not to provide a solution to the multiple theme contexts. I'm saying this just in case you guys find an issue for this specific problem and may decide this issue can be closed.

**Comment by Andarist** [comment]
> We can setup a repro. And also also make a seperate issue once we have more info. :)

That would be really helpful.

@FezVrasta sure - a warning seems reasonable, shouldn't be a hard error though. Would you like to work on this or should I get to it sometime later?

**Comment by FezVrasta** [comment]
I can try to put a PR together 👍

**Comment by willgriffiths** [comment]
Turns out it there were two versions of emotion/core in our monorepo. Our components were finding a different version than our application. So we've solved it. 

Sorry for the noise. 

Consider this a vote for the feature, though. :)

**Comment by mitchellhamilton** [comment]
I'm good with this, @FezVrasta are you still planning to submit a PR?

**Comment by Andarist** [comment]
This got merged into v11 branch.
