### ISSUE TITLE
Possibility to disable theming (or disable all the Contexts)

### ISSUE THREAD

**Issue by tomitrescak** [emotion-js/emotion#1472]
**The problem**

Currently each styled component is wrapped with two Context Providers. This is attributed in theming. Is it possible to disable the use of context providers by opt-in disabling themes?

WHY: In 95% application which do not use theming it just gives unnecessary overhead and also makes the React debug tree veeeeeeery laaaaaaaarge ;)

**Proposed solution**

Opt-in for disabling themes and removal of the context providers.

**Alternative solutions**

**Additional context**

I can see that the Context is baked in the Styled component.

https://github.com/emotion-js/emotion/blob/master/packages/styled-base/src/index.js#L76

**Comment by FezVrasta** [comment]
This PR (https://github.com/emotion-js/emotion/pull/967) should address your issue, with Hooks you wouldn't see a `Context.Consumer` for each styled component.

**Comment by tomitrescak** [comment]
Let’s hope it will be accepted. I can see some controversy there and not much will to push it through. But, it made a lot of sense to me.

**Comment by Andarist** [comment]
I'm currently triaging issues and when I'm done I'm going to work on stuff we need to ship emotion@11. This should just get rid of this problem completely. Stay tuned.
