### ISSUE TITLE
Any way of having utilized builds with stable selectors [Context: E2E Testing]?

### ISSUE THREAD

**Issue by de-robat** [emotion-js/emotion#1475]
I can't seem to find any information within the documentation on how to force stable selector names.

I'm wondering how people use js-css-replacements like this within e2e test setups. As far as i understand it, i can't rely on the generated classNames (as they may differ from build to build) to select elements within, e.g. webdriverio e2e tests.

I found the sourcemaps part, which helps for developers, but not for automation, or i may be missing something.

Can anyone shed some light on this? Is it a good practice to not use BEM style semantic classes in this use case, and rather anotate the elements of interest with custom data attributes?

Thanks in advance!

**Comment by MMT-LD** [comment]
@de-robat Hey, the way i have got around this is to provide a context provider and consumer to which you pass a config. and then use the config to generate a data-id or something to that affect to add readable tags to get control of for e2e testing.

``` <div data-e2e-id="something-from-config">dssd</div>```

**Comment by jackpope** [comment]
We're also struggling with this. We use `babel-plugin-emotion` with contextual classnames which helps because at least we can target elements with partially wild-carded selectors but it would be great to not have to use wildcards all the time as they can be tough to write and are not suported by all systems.

It would be great if in addition to generated classnames, we could get generated data ids similar to how @MMT-LD is doing manually. For example:

```javascript
const MyComponent = styled('div')`
  color: red;
`;
```

could produce

```html
<div class="css-<uniq_hash>-MyComponent" data-component-name="MyComponent"></div>
```

or, an additional class with no styling attached

```html
<div class="css-<uniq_hash>-MyComponent MyComponent"></div>
```

**Comment by Andarist** [comment]
Consider finding your elements by their aria roles, text inside them etc. This leads to more stable tests than relying on class names or custom identifiers. When needed just introduce data attributes like proposed by @jackpope

**Comment by de-robat** [comment]
Thank you @Andarist , @jackpope and @MMT-LD for all the food for thought! Back in the days we used to have "semantic classes", that where used to bind js to dom elements.

Coming from there, going with data-attributes is what we came up with too, but in general i don't like the idea of altering the code-basis for test purposes. One could do a build that strips out e2e attributes for production, but than again you can't test exactly what you will roll out.

But generally speaking, its really hard to derive stable selectors from todays library structure. 

Wit data attributes / classnames you could move along the class name to the new dom element whenever you refactor. With generated ids nothing stays stable. Elements that have bound listeners to them could be identified by a hash derived from the called function name and the class name probably. But that comes with a lot of pitfalls too.

We were thinking of utilizing aria labels too, but due to the application in question actually has high demands on accessibility, and the aria standard beeing rather strict (explicitly stating that "bad aira roles, labes, and so on are worse than no araia labels") we stepped away from this solution too, because keeping to the standard does not fulfill all e2e needs.

So obv. no real golden bullet here neither.

So i think we will settle on data-attributes or even just BEM (http://getbem.com/introduction/). 

My question can therefore be considered as "Closed" but feel free to reopen if you want to keep the discussion going. Im really interested in the cleanest possible solution here!
