### ISSUE TITLE
Custom CSS variables not available from styled component

### ISSUE THREAD

**Issue by carsoni** [emotion-js/emotion#1480]
Seems to be a type error when using CSS variables with @emotion/styled with Typescript and react-spring. This may not be an inherent emotion problem but I thought I should highlight it to you in any case.

**Current behavior:**

When attempting to animate a custom CSS variable on a styled div with react-spring the variable is not available/visible to react-spring. I'm using an inline style to apply the animated value and the code editor shows an error

 "Object literal may only specify known properties, and '"--cloud-opacity"' does not exist in type 'CSSProperties'.ts(2322)"

**To reproduce:**
Have a look at [this](https://codesandbox.io/s/crazy-noether-ou1sk) sandbox.  

1. Hover (not click) over the little cloudy div in the browser
2. Note the brightening of the clouds
3. Note the red squiggly under the inline style in the AnimatedContainer component

**Expected behavior:**

CSS variables should operate in the same manner as other CSS properties 

**Environment information:**

See CodeSandBox provided above

**Comment by Andarist** [comment]
This is a TypeScript limitation and an advice on how to solve it is written down here - https://www.npmjs.com/package/csstype#what-should-i-do-when-i-get-type-errors
