### ISSUE TITLE
Doesn't remove dead code with Rollup

### ISSUE THREAD

**Issue by DominicTobias** [emotion-js/emotion#1481]
**Current behavior:**

Dead code is not eliminated from production builds.

**To reproduce:**

https://github.com/DominicTobias/emotion-rollup-dead-code

**Expected behavior:**

Non production code should be eliminated. But this is the output, note how in userland code the conditional "I should be eliminated" has successfully been removed, but the Emotion stuff hasn't:

![Screenshot 2019-08-24 at 17 45 35](https://user-images.githubusercontent.com/760314/63640358-37cc2d80-c697-11e9-9ed7-14b8064fe51c.png)

**Environment information:**

- `react` version: 16.9
- `emotion` version: 10.0.16

**Comment by Andarist** [comment]
Long story short - plugins order matter 😉 . https://github.com/DominicTobias/emotion-rollup-dead-code/pull/1 - you need to use replace plugin AFTER babel one.

**Comment by DominicTobias** [comment]
Whoops thanks, should have tried that!
