### ISSUE TITLE
Text Color Contrast

### ISSUE THREAD

**Issue by jimmymorris** [emotion-js/emotion#1491]
I'm not sure if this is a bug or something that just needs to be adjusted. 

Want to suggest a different color is selected for the documentation text. The hotpink that is currently implemented has a low contrast ratio when on a white background. It is worth mentioning that this isn't a problem everywhere but only on certain doc sections like: https://emotion.sh/docs/emotion-theming. Whereas https://emotion.sh/docs/introduction the text is nice and contrasted being much easier to read on a light background.

![pick-contrast](https://user-images.githubusercontent.com/377487/64375744-8c0ad200-cff4-11e9-94f5-2aa7da602d3e.PNG)

**Comment by grncdr** [comment]
@jimmymorris I think this is a bug, since it only seems to happen when you initially load the docs on the theming page. E.g. if you go to the intro and click on theming you get the correct colors.

**Comment by jlkiri** [comment]
It happens only (and always) on direct URL access to any page in docs.

**Comment by Andarist** [comment]
I can't repro this right now. Could you check if any of you still experience this and list the steps which you do to trigger the problem?

**Comment by grncdr** [comment]
It seems fixed for me.

**Comment by Andarist** [comment]
Thank you for checking this! Closing the issue as it seems that it has been fixed already.

**Comment by jimmymorris** [comment]
Looks to be fixed!
