### ISSUE TITLE
Accept objects as className in styled components

### ISSUE THREAD

**Issue by benmerckx** [emotion-js/emotion#1495]
**Current behavior:**

Class names passed to styled components that are not of type string are not passed to React.
````js
const myclass = {toString: () => 'myclass'}
const Comp = styled.div``
<Comp className={myclass} /> // => no "myclass" in output
````

See: https://github.com/emotion-js/emotion/blob/66cda64128631790b81e3c9df273a972358ea593/packages/styled-base/src/index.js#L102-L108

As React accepts objects and runs `toString` implicitly this would be expected to work (hence marked as bug).

**To reproduce:**

See above

**Expected behavior:**

Example should render `<div class="_emotionserializedclass_ myclass" />`

**Comment by Andarist** [comment]
This has been fixed in https://github.com/emotion-js/emotion/pull/1545
