### ISSUE TITLE
Extending a `styled` component with SSR throws `className` Server and Client mismatch error

### ISSUE THREAD

**Issue by timramsier** [emotion-js/emotion#1498]
While using SSR in an application and calling `styled` on another styled component, React will throw a warning in development such as `react-dom.development.js:506 Warning: Prop `className` did not match. Server: "e1j1hae02 css-bpfslw-Animal-Dog e1j1hae01" Client: "css-82yfcy-Animal-Dog e1j1hae02"`.  It appears that the server is generating different class names when extending another styled component

## Example Code to Cause Error
```javascript
const Animal = styled.p`
  font-family: Arial;
`;

const Dog = styled(Animal)`
  font-size: 18px;
`;

const App = () => (
  <div>
    <Animal>I am an animal</Animal>
    <Dog>I am a dog</Dog>
  </div>
)
```

If I add an intermediate functional component to wrap the usage of the `Animal` component and pass the `className` into it, the warning goes away.

## Example Code to Remove Error
```javascript
const Animal = styled.p`
  font-family: Arial;
`;

const Canine = props => <Animal {...props} />;

const Dog = styled(Canine)`
  font-size: 18px;
`;

const App = () => (
  <div>
    <Animal>I am an animal</Animal>
    <Dog>I am a dog</Dog>
  </div>
```

This appears to be in issue with how `styled()` handles another styled component and SSR.

**Comment by Andarist** [comment]
Could you prepare a runnable repro case?

**Comment by Andarist** [comment]
We haven't received a response in nearly 10 days - going to close this to keep the issue tracker clean. If you provide a repro case in the future I will happily take a look at it. Hope you understand.
