### ISSUE TITLE
what the packages

### ISSUE THREAD

**Issue by geddski** [emotion-js/emotion#1512]
I dig emotion once it's all setup, but I'm straight up confused by the packages. I have three projects using emotion 9, via the `emotion-react` package. 

I'm trying to upgrade them to the latest emotion and have no fetching idea which package(s) to use now. 

![image](https://user-images.githubusercontent.com/515722/65273717-081a1500-dadf-11e9-927a-528353e07893.png)

This is a mess y'all. I use `css`, `injectGlobal`, `cx`, and sometimes `styled.div`. Gotta admit I'm lost with where everything went now and how to upgrade.

**Comment by geddski** [comment]
the docs appear to be just as confused as I am

![image](https://user-images.githubusercontent.com/515722/65274232-13217500-dae0-11e9-98dd-0d72b3eb4893.png)

**Comment by Andarist** [comment]
The linked docs are correct - that's because css from `@emotion/core` and css from `emotion` are 2 different functions with slightly different behaviors. The one from `emotion` returns a usable class name string while the one from `@emotion/core` returns an opaque object describing the class name.

**Comment by Andarist** [comment]
RFC has just been opened #1635 with some proposed name changes, I'm going to close this issue, but we are very keen to hear what you think of the proposed changes.
