### ISSUE TITLE
Everything hot pink after 'Global Styles'!

### ISSUE THREAD

**Issue by shiatsumat** [emotion-js/emotion#1513]
**Description:**
It is cool that when in the article 'Global Styles' virtually everything including the header and the navigation bar turns into hot pink.
However, even more curiously and awkwardly, that effect applies also to every article after 'Global Styles'.

**Documentation links:**
All the articles after 'Global Styles' https://emotion.sh/docs/globals, i.e.
https://emotion.sh/docs/keyframes, https://emotion.sh/docs/ssr, https://emotion.sh/docs/with-props, ....

For example, the article 'Keyframes' https://emotion.sh/docs/keyframes looks like this.
<img width="994" alt="Screenshot 2019-09-20 11 41 52" src="https://user-images.githubusercontent.com/529217/65295210-a66bb080-db9b-11e9-87cc-9cc3cc74f330.png">

**Comment by AntonNiklasson** [comment]
If this is not already being worked on I could take a stab at it 👋

**Comment by Andarist** [comment]
@AntonNiklasson you are more than welcome to take a stab at this. If you need any help you can ping me on our Slack. Most likely we should purge all global styles on navigation.

**Comment by AntonNiklasson** [comment]
I'm not able to reproduce this. Not on the live site, and not in my local development environment. 🤷‍♂

**Comment by shiatsumat** [comment]
That sounds strange. I experienced this 'hot pink' phenomenon on Google Chrome (version 77.0.3865.90), Safari (version 13.0.1) and Firefox (version 69.0.1) on MacBook Mojave (version 10.14.6).

**Comment by AntonNiklasson** [comment]
Alright, this is weird. I was actually able to reproduce it now. Loading the site straight into https://emotion.sh/docs/globals makes the `hot pink` stick around when navigating. If I reload the page on something like `https://emotion.sh/docs/introduction`, navigate the "Global styles" and then to some other page, the global styles are purged.

I'll look into it a bit further.

**Comment by shiatsumat** [comment]
Ah, I have also experienced that.

**Comment by zslabs** [comment]
I've run into this pretty randomly as well.

Maybe not as "flashy", but could we just extract the `.some-class` styles from the example into `<Global />` and target just that selector to help stop the bleeding onto other pages?

**Comment by mitchellhamilton** [comment]
> Maybe not as "flashy", but could we just extract the .some-class styles from the example into <Global /> and target just that selector to help stop the bleeding onto other pages?

This sounds good to me.
