### ISSUE TITLE
class assigns without style

### ISSUE THREAD

**Issue by NasKadir123** [emotion-js/emotion#1517]
Hello! I'm not sure if is it correct to ask about here, but I will try, so sorry.

I'm creating Gutenberg blocks for Wordpress implementing on React JSX ES6.
In creating blocks need 2 render functions, one for backend, second for frontend.
And emotion is correct for first render, but for second it assigns class, but without styles.
So here is my code:
```
...
import { css, cx } from 'emotion';
import classnames from 'classnames';
...
attributes: {
hoverTextColor: {
	type: 'string'
} }
...

edit: ({ attributes }) =>   //First render function
...
onChangeHoverTextColor = ( hoverTextColor ) => {
	setAttributes( { hoverTextColor } )
}
...
return (
<>
<PanelColorSettings
	title={ __('Colors', 'modest-gutenberg-blocks') }
	colorSettings={[
		{
			value: hoverTextColor,
			onChange: this.onChangeHoverTextColor,
			label: __('Hover Background Color', 'modest-gutenberg-blocks')
		}
	]} />  //Here is color picker for changing hover text color
<div className={ classnames(className, css` background-color: hotpink; &:hover {color: ${hoverTextColor} !important; }`) } >some text</div>
</>
) }, //end for frontend and everything is working great
save: ({ attributes }) => { //start of second function
...

...
return (
<div className={classnames(css` background-color: hotpink; &:hover {color: ${hoverTextColor} !important; }`)}>some text</div> 
)} //this render doesn't work
```
Second function take class from emotion and give to div, but without any styles.
Can you help me, please? I surfed whole internet, but nothing.

- `react` version:
"react": "^16.9.0"
- `emotion` version:
"emotion": "^10.0.17"

**Comment by Andarist** [comment]
Please prepare a repro case, pasting in incomplete code is not that helpful.

**Comment by Andarist** [comment]
Sorry, didn't mean to close this just yet - miss click.

**Comment by Andarist** [comment]
We haven't received a response in nearly 10 days - going to close this to keep the issue tracker clean. If you provide a repro case in the future I will happily take a look at it. Hope you understand.
