### ISSUE TITLE
Css Prop does not override library style, but styled function does.

### ISSUE THREAD

**Issue by jmadelaine** [emotion-js/emotion#1520]
**Current behavior:**

If a library contains a component that's styled using `@emotion/styled`, when importing that component into an app, the following can be observed:
- Setting the `css` prop directly on the imported component DOES NOT override style defined in the library
- Styling the imported component with `@emotion/styled` DOES override style defined in the library
- Styling the imported component with `@emotion/styled` and then styling with `css` prop DOES override style defined in the library (`css` prop style takes precedence in this case).

It's as if the `css` prop is discounted unless the component is restyled locally using `@emotion/styled`, at which point, the `css` prop now takes precedence again.

**To reproduce:**

1. Define a library component with emotion and export from a library:

```jsx
import React from 'react'
import styled from '@emotion/styled'

export const Flex = styled.div({
    display: 'flex',
})
```

2. Import component into a project and try to override `display` style with `css` prop:

```jsx
import React from 'react'
import { Flex } from 'my-awesome-library'

const Component = () => (
    <Flex
        css={{
            display: 'inline-block',
        }}
    />
)

export default Component
```

3. Notice that in the browser, the `flex` style from the library overrides the `inline-block` style from the `css` prop (incorrect behaviour).

4. Style the imported component with `@emotion/styled` instead of `css` prop.

```jsx
import React from 'react'
import styled from '@emotion/styled'
import { Flex } from 'my-awesome-library'

const StyledFlex = styled(Flex)({
    display: 'block',
})

const Component = () => (
    <StyledFlex  />
)

export default Component
```

5. Notice that in the browser, the `block` style from the styled version of the imported component overrides the `flex` style from the original imported component (correct behaviour).

6. Apply `css` prop to the styled version of the imported component.

```jsx
import React from 'react'
import styled from '@emotion/styled'
import { Flex } from 'my-awesome-library'

const StyledFlex = styled(Flex)({
    display: 'block',
})

const Component = () => (
    <StyledFlex
        css={{
            display: 'inline-block',
        }}
    />
)

export default Component
```

7. Notice that in the browser, the `css` prop (display: inline-block;) now overrides both the `StyledFlex` style (display: block;) and the `Flex` style (display: flex;) (correct behaviour).

**Expected behavior:**

I expect the `css` prop to override the styles applied in the library regardless of whether I style the component locally with `@emotion/styled`. Currently, it seems that the library's style takes precedence over the `css` prop, unless the imported library component is styled using the local `styled` function, in which case, the `css` prop works as expected.

**Environment information:**

react: 16.9.0
@emotion/core: 10.0.17
@emotion/styled: 10.0.17

**Comment by Andarist** [comment]
Thank you for the detailed description. Could you provide a full repro case for this though? I've tried to repro this on codesandbox, but everything seems to work - https://codesandbox.io/s/beautiful-hugle-836gt

**Comment by Andarist** [comment]
A repro case was not provided for a month and there was also no other response - I have to close this. If the issue still affects you please open a new issue with repro case.

**Comment by c0z0** [comment]
I ran into this problem myself. Fixed it by making sure there aren't multiple instances of emotion in the code. I did this by saving emotion as a peer dependency. 

I am leaving this here in the hope that it would help anyone stumbling upon this.

**Comment by dohun-toss** [comment]
If you're using a `react-helmet` and putting the css script code in `Helmet`, this problem might be happened. Since the `emotion`'s style code is above the `React-helmet`'s style code, you will need to load the css script without using the react-helmet.
