### ISSUE TITLE
Add DefaultTheme for TypeScript

### ISSUE THREAD

**Issue by jeroenvisser101** [emotion-js/emotion#1521]
**The problem**
When using TypeScript, defining a typed theme for `@emotion/styled` requires importing from a different path, which can also be confusing with autocompletion (for instance, emotion could be higher up the list than project-local exports).

**Proposed solution**
Add a DefaultTheme interface [like Styled Components does](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-components/index.d.ts#L407-L414) that can be easily augmented by users.

Example of how that can be used:
```ts
// styled.d.ts
import "styled-components";
import { ITheme } from "./theme";

declare module "styled-components" {
  export interface DefaultTheme extends ITheme {}
}
```

**Comment by Andarist** [comment]
See - https://github.com/emotion-js/emotion/issues/1507#issuecomment-531549946

**Comment by jeroenvisser101** [comment]
Ah, this can actually be marked as a duplicate of #1507, I'll propose this there. Thanks!
