### ISSUE TITLE
Theming styled component wont work with animations

### ISSUE THREAD

**Issue by AidenFaulconer** [emotion-js/emotion#1525]
**Current behavior:**
Nothing is placed in the spot the themed value should inject into, causing undefined behavior in that particular CSS's attribute value

**To reproduce:**

create a theme, and use it with this...
```

const Pages = styled.div'
  position: relative;
  text-decoration: none;
  border-bottom: 5px solid
    ${(props) => {
      props.theme.primarycolor;
    }};

  & > a:hover:before {
    visibility: visible;
    -webkit-transform: scaleX(1);
    transform: scaleX(1);
    -moz-transform: scaleX(1);
    -ms-transform: scaleX(1);
    -o-transform: scaleX(1);
  }

  & > a:before {
    content: "";
    position: absolute;
    width: 100%;
    height: 2px;
    bottom: 0;
    left: 0;
    color: rgba(0, 0, 0, 0.6);
    background: 4px;
    background-color: ${(props) => {
      props.theme.primarycolor;
    }};
    visibility: hidden;
    -webkit-transform: scaleX(0);
    transform: scaleX(0);
    -webkit-transition: all 0.3s ease-in-out 0s;
    transition: all 0.3s ease-in-out 0s;
    -moz-transition: all 0.3s ease-in-out 0s;
    -ms-transition: all 0.3s ease-in-out 0s;
    -o-transition: all 0.3s ease-in-out 0s;
    -moz-transform: scaleX(0);
    -ms-transform: scaleX(0);
    -o-transform: scaleX(0);
  }
';
//note the use of ', change to `. Using ` was preventing this from formatting in this comment 

```
**Expected behavior:**

I expect my themes primary color to be in the & >a:before{} state for the animation
**Environment information:**
 both react and emotion are in their latest versions

**Comment by Andarist** [comment]
Please prepare a runnable repro case (e.g. on codesandbox.io).

**Comment by AidenFaulconer** [comment]
I solved the problem, I misused the lambda function where before it was ${(props)=>{...}} where after it should be ${(props)=>...} since the first version expects a return statement due to the {} while the second has it implied by removing the {}, silly mistake on my part

**Comment by Andarist** [comment]
Thanks for reporting back. As the problem got solved - closing this ticket.
