### ISSUE TITLE
Multiple css props not being compiled together

### ISSUE THREAD

**Issue by AndrewBrough** [emotion-js/emotion#1534]
**Current behavior:**

Passing css on a component and spreading it to a rendered element using {...rest} doesn't always cause the styles to be compiled together on the final rendered element.

**To reproduce:**
I have a NavigationLink component with some props:

```
interface Props extends BaseHTMLAttributes<HTMLLIElement> {
  label: string;
  url: string;
  anchor?: boolean;
}

const NavigationLink: FC<Props> = ({label, url, anchor, ...rest }) => {
  ...
  return (
    <li css={styles.navigationLink} {...rest}>
      {anchor ? renderAnchorTag() : renderNavLink()}
    </li>
  );
};
```

Used as such:
```
<NavigationLink
  css={conditionalItemStyles()}
  id="someId"
  label={"some label}
  url={"some-route"}
/>
```

Only the `navigationLink` styles are applied to the rendered <li>, not the passed down styles in {...rest}. It doesn't matter what order I put them in (css before or after ...rest is the same effect).

The interesting part is it seems to be an issue on some of our dev machines and not on others. All using the same installed packages, same model macbook pro.

1. ...
2. ...
3. ...

**Expected behavior:**

**Environment information:**

- `react` version: "react": "^16.10.1",
- `emotion` version: "@emotion/core": "^10.0.17",

**Comment by Andarist** [comment]
Could you prepare a repro case? Without that it's hard to even determine if what you are experiencing is a broken behavior or not.

**Comment by Andarist** [comment]
A repro case was not provided for 3 weeks and there was also no other response - I have to close this. If the issue still affects you please open a new issue with repro case.
