### ISSUE TITLE
CodeSandbox demo not updated in Readme

### ISSUE THREAD

**Issue by tan31989** [emotion-js/emotion#1540]
**Current behavior:**

When we visit the demo codesandbox link, we see it's still using `react-emotion` as seen here: https://codesandbox.io/s/pk1qjqpw67

This becomes a misleading notion for those who are looking for some sample code.

**To reproduce:**

1. Open the link https://codesandbox.io/s/pk1qjqpw67 from the [READM.md](https://github.com/emotion-js/emotion/blob/master/README.md)
2. Check the code is still using an older version for react configuration

**Expected behavior:**

The latest documentation for using version-10 states the following changes to be made across for using the latest version-10: https://emotion.sh/docs/migrating-to-emotion-10

**Environment information:**

- `react` 16.8.6
- `emotion` 10.0.17

I would love to contribute to this, but I think since it's hosted under your code sandbox, I can only pass on the modified and updated code sandbox code here.

https://codesandbox.io/s/emotionlatestreact-7l753

**Comment by Andarist** [comment]
Isn't any other, more fresh, codesandbox linked anywhere that we could just use here?

**Comment by tan31989** [comment]
@Andarist I updated that via https://codesandbox.io/s/emotionlatestreact-7l753, but since I am not a contributor to your repo, I was of the opinion, you would be forking that for your repo and updating your README.

**Comment by FezVrasta** [comment]
We have the one in the bug report template:
https://github.com/emotion-js/emotion/tree/master/.github/ISSUE_TEMPLATE

https://codesandbox.io/s/zljgy

**Comment by tan31989** [comment]
@FezVrasta I was referring to the main Readme page: https://github.com/emotion-js/emotion

Since the project's main readme has an older codesandbox, it can mislead people who are adopting the library.

**Comment by FezVrasta** [comment]
> Isn't any other, more fresh, codesandbox linked anywhere that we could just use here?

@tan31989 I was answering to this question.

**Comment by Andarist** [comment]
I've let know Kye of the issue and he has already upgraded that sandbox to emotion@10 APIs with a basic demo and is going to add some better examples in a moment.

@tan31989 thanks for letting us know! I think the issue can be closed now.
