### ISSUE TITLE
Invalid css property typing

### ISSUE THREAD

**Issue by tutok** [emotion-js/emotion#1544]
**Current behavior:**

TypeScript typings overwrite `css` property typing even I am using only `styled` (I am not using `jsx pragma` nor `babel-plugin-emotion`).

This resulting in conflicting types in my codebase as I am defining `css` property on my own components

this is caused probably by this declaration:
https://github.com/emotion-js/emotion/blob/master/packages/core/types/index.d.ts#L96 

**To reproduce:**

1. install `@emotion/core`
2. see that any component has property `css` with type: `css?: InterpolationWithTheme<any>`

https://codesandbox.io/embed/withered-sun-e0pwm

**Expected behavior:**

property `css` should not be defined when `@emotion` `css` is not used

**Environment information:**

- `react` version: 16.8.4
- `emotion` version: 10.0.21

**Comment by Andarist** [comment]
There are ongoing discussions on how we should handle this in other issues - could you locate them and give your feedback there? This is somewhat a duplicate, so going to close this.

**Comment by tutok** [comment]
@Andarist can you please help me find the mentioned "other issue"?

**Comment by Andarist** [comment]
https://github.com/emotion-js/emotion/issues/1257
https://github.com/emotion-js/emotion/issues/1507
