### ISSUE TITLE
[SUPPORT] How to use @mixin and @include of SCSS in styled

### ISSUE THREAD

**Issue by taiphamhdweb** [emotion-js/emotion#1550]
I have @mix function and I want to call as @include. Currently, I can't use SCSS: @mixin and @include.
Example:
const Wrap= styled.div<props>`
  @mixin draw-circle() {}
  @include draw-circle()
`
Please check help me!

**Comment by Andarist** [comment]
Emotion is not SCSS-compatible and it doesn't even want to be. This is CSS-in-JS and you can use JS to create helpers, mixins etc
