### ISSUE TITLE
Opera gives error!

### ISSUE THREAD

**Issue by ikoral** [emotion-js/emotion#1551]
**Current behavior:**

When I try to open demo (https://codesandbox.io/s/pk1qjqpw67) in browser(opera) I received this error.
![error](https://user-images.githubusercontent.com/40534340/66963331-b4fe9800-f073-11e9-8260-d21b9b2b02fe.jpg)

**Comment by Andarist** [comment]
I've successfully loaded that page in Opera (both 63 and 64). Maybe it was some temporary problem with CodeSandbox itself and not with our demo?

**Comment by Andarist** [comment]
OP has not responded for over 10 days - I have to assume this is not an issue as I couldn't reproduce this myself.
