### ISSUE TITLE
At-rules (@supports) change order of generated css

### ISSUE THREAD

**Issue by Grsmto** [emotion-js/emotion#1564]
**Current behavior:**

Hi guys!

It seems like adding an at-rule is changing the final order of generated css. The code within the at-rule is generated after.

**To reproduce:**

See index.js l.33

https://codesandbox.io/s/emotion-32ox8

**Expected behavior:**

The original order of css rules should be kept. This makes sense for media query but in this scenario I'm using @support which should not increase specificity.

**Environment information:**
See codesandbox.

Thanks!

**Comment by Andarist** [comment]
Right now this has been generated:
```
h1{background-color:midnightblue;}
@supports (display:grid){h1{background-color:red;}}
```
from
```
h1 {
  @supports (display: grid) {
    background-color: red;
  }
  background-color: midnightblue;
}
```

Could you post your exact expected output?

**Comment by Grsmto** [comment]
I would expect the order to be preserved. The @support rule according to the spec I believe is not adding specificity so the order does matter in this case.

```
@supports (display:grid){h1{background-color:red;}}
h1{background-color:midnightblue;}
```

**Comment by thysultan** [comment]
With nesting this is how [sass](https://www.sassmeister.com) handles it as well. Vanilla CSS does not support nesting.

**Comment by Andarist** [comment]
Thank you @thysultan for chiming in! Taking the SASS as a rule of thumb here it seems that this is working as intended, although I admit this might seem a little bit strange at first. You'll have to use this as a workaround for your issue:
```css
@supports (display: grid) {
  h1 {
    background-color: red;
  }
}

h1 {
  background-color: midnightblue;
}

```
