### ISSUE TITLE
"Cannot convert a Symbol value to a string" from Global

### ISSUE THREAD

**Issue by volkanunsal** [emotion-js/emotion#1573]
**Current behavior:**

After the code is minified and mangled using TerserPlugin of Webpack, the code fails with the following error:

`Cannot convert a Symbol value to a string`

**To reproduce:**

Very hard to reproduce. 

**Environment information:**

- `react` version: 16.8.6
- `emotion` version: 10.0.5

**Comment by Andarist** [comment]
> Very hard to reproduce.

And it's even harder for us as we don't even suffer from this problem. Please put more effort into reproducing your problem so we can take a look to help you - I don't know how you imagine we do that with the information (or rather lack of it) you have provided.

**Comment by volkanunsal** [comment]
Sorry, this is actually unrelated to emotion. Turns out it has to do with `react-hot-loader`.

**Comment by ktalebian** [comment]
@volkanunsal I'm getting the same thing, but my stacktrace is showing

```
at Object.get (node_modules/create-emotion-styled/dist/index.cjs.js:216:200)
          at Proxy.toString (<anonymous>)
          at Array.forEach (<anonymous>)
```

which made me think it's emotion - was your different? How did you fix yours?
