### ISSUE TITLE
Flow check on CI not detecting errors

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#1579]
**Current behavior:**

CI seems not to detect any Flow error for some reason.

**To reproduce:**

1. Check out the CI logs on master (e.g. https://circleci.com/gh/emotion-js/emotion/7855)

**Expected behavior:**

CI should report the same errors I'm getting locally:
![image](https://user-images.githubusercontent.com/5382443/67681722-2c92c800-f98e-11e9-946f-00445aca7332.png)

**Environment information:**

- `react` version: N/A
- `emotion` version: N/A

**Comment by Andarist** [comment]
What exact errors are you seeing locally? Wasn't that PR of yours ready to be merged?

**Comment by FezVrasta** [comment]
The errors I see are from the primitives packages, I didn't touch them (and I saw them even before I started working on the `styled` types)

**Comment by FezVrasta** [comment]
This is the Flow output if you checkout 3b7e2f2e (way before my changes)

![image](https://user-images.githubusercontent.com/5382443/67690468-3cfe6f00-f99d-11e9-910e-bad48d4142c9.png)

**Comment by FezVrasta** [comment]
I ran a bisect and the errors started happening after 3faff18589af66e7654fb4fc8de5b6d3c7490c2e

Anyways, the main issue is that CI is not catching them, not much that we have some errors.

**Comment by FezVrasta** [comment]
I guess there's something weird with Flow or my local setup, I tried to run a bisect and after a few checkouts, going back to master I don't get those errors anymore 👀

**Comment by Andarist** [comment]
Can this be closed then?

**Comment by FezVrasta** [comment]
I suppose, still that's so weird...
