### ISSUE TITLE
Jest-Emotion with Nested Components as Selectors

### ISSUE THREAD

**Issue by iasinov** [emotion-js/emotion#1582]
When generating the snapshots for the storybook stories, jest-emotion doesn't replace classes for the cases, when in style definitions components were used as selectors:

```
const MyComponent = styled.div`
  width: 100%;
  ${AnotherComponent} {
    margin-top: 5px;
  }
```
Snapshot piece generated on Linux/Mac:

```
.emotion-1 {
  width: 100%;
}
.emotion-1 .e10hmdzl0 {
  margin-top: 5px;
}
```
Snapshot piece generated on Windows:

```
.emotion-1 {
  width: 100%;
}
.emotion-1 .e1xyhye30 {
  margin-top: 5px;
}
```
Class for the AnotherComponent doesn't have jest-emotion-like class name and is being generated differently among Windows and Linux/Mac which is causing snapshots mismatch.

Default jest-emotion configuration is being used. Jest configuration contains `"snapshotSerializers": ["jest-emotion/serializer"]`,

```
"emotion": "9.2.12"
"jest-emotion": "9.2.11",
"react-emotion": "9.2.12",
"babel-plugin-emotion": "9.2.11"
```
Is there any workaround to make it generate className the same as for the rest of the components or at least the same hashed classes among the platforms? I know that the 10th version is suggested to use, but I need to make it work on the v9. Thank you very much

**Comment by Andarist** [comment]
You can fork the babel plugin for v9 and change this:
https://github.com/emotion-js/emotion/blob/7c582301317cd9c0038a13a118456e798ffcadf8/packages/babel-plugin-emotion/src/index.js#L182
to 
```js
const normalizePath = path => nodePath.normalize(path).replace(separator, '/')
// ...
stuffToHash.push(normalizePath(finalPath))
```

This is how this [has been fixed](https://github.com/emotion-js/emotion/blob/97673098945a75b716d4cac100c1af46a5ae18f2/packages/babel-plugin-emotion/src/utils/get-target-class-name.js#L44) in emotion@10. 

We can't backport this fix ourselves, hope you understand.
