### ISSUE TITLE
Make StyledComponent type polymorphic

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#1587]
I started to use the new Flow types into my project, and I figured out it would make sense to make `StyledComponent` a polymorphic type, so that we can do this:

```typescript
const Foo = styled<Props>(props => <div {...props} />)`
  color: ${props => props.color};
`;

const Bar = styled<Props>('div')`
  color: ${props => props.color};
`;
```

Which would allow to:

1. type `props` inside the styled component logic
2. allow to workaround the lack of tagged template support of Flow

Unfortunately I doubt my Flow knowledge is good enough to implement this without breaking the existing types, which make sense because we also want to allow:

```typescript
const Foo = styled.div<Props>`
  color: ${props => props.color};
`;
```

What do you think?

**Comment by Andarist** [comment]
Well, I'm not sure if there is anyone other than you willing to jump on this. This definitely makes sense, I just don't have enough expertise with flow to implement this myself. I also don't understand how those types were used so far, so it's hard to assess what might be breaking and what is not. 

I'm not against breaking changes in types though - I believe that we can release type changes each minor version~ (it's completely unergonomic to make them bump major versions).

**Comment by FezVrasta** [comment]
I think it could be enough to change the `CreateStyled` call signature, while leaving the `[key: string]: ...` type as is it now.

That way we can still do `styled.div<Props>()`, we can do `styled<Props>(fn)()`, but we'll not be allowed to do `styled(fn)<Props>()` (which I think would be okay).

Obviously something is not working with my implementation...

https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6hwJ7oCmoA3qAKLTGrEB2OAKkcQDSgDKOAhjsTQDOggGIBXegGMcyWPR7QAwrAxyGeAL6hIWFaADkWYj2n7EiYgA9MufK1ABJRsSyZofWfUGgAvKACCWFg8BAA8PPQEAHzmVjZ4hCRchDQAJgDy6DJy3n5kiKCg7gBGAgD8AFyggjhYyPQA5mwF1QAWsGLQqSLY8DxYqQAKuuiV1bX1Db5RoMWwsDQRzYW8WA3EOGM1dY2IGrHW2An23ARpyqr06qGDM37cfALEwuJS2fJKKphXjDczAGTkFqpYiQHidHDDWDoQRVCIEZb4WDcHYNKoACgAlNNxqjEfBkDhWhdvuoMS1CldLMweGiqDQ6IwWCREZSrDhMu9BGNTmlOZ5BC1sT4ZrziKkSWpfrc9gd4nYksNkAA3R5iiVfKU4P6+ZJncWSn7a26gQH5QoAfQttFg7wtRgUVXVhuut0RVptduKPEExDhkXd1tQts8Fpq+thoHhgc9ocgvX6QxG-oIsosh1siVIigd-GdmqNur+6JaADpy-0GpGnPxXAsPDlEMLRSkDQXXTF0-Ks6Ac8Y863UrrzaBixT8LSqtRaOpmexx9CuTzB-zG4VMVVi+XS5Xq846+4uc29ed29KooiANoAa2IBCq20mAF0qn21YOXYxEcV6qkMce3wHfVUjTQowLAxBJByPBJFzYh1VfOD1V1dF6E6aAU0xABuSDoPGYDdVg-t4MHdF9FSFV9Gw8dwMQHsoRhYcWiguAsAfCZdg0HDwNoqCvGOEhUn8VpjCHPxwzSG4RkEKIyIo5UqPRAADFjsCqIxUiwpTsKAA

**Comment by Andarist** [comment]
This got fixed by https://github.com/emotion-js/emotion/pull/1588 (merged to `next` branch)
