### ISSUE TITLE
Please considering a more human readable format for generated css classes. 

### ISSUE THREAD

**Issue by jcklpe** [emotion-js/emotion#1590]
**The problem**

Emotion produces class names like this: `class="css-jdkslf-Item"`

![image](https://user-images.githubusercontent.com/9451726/67908113-36602b00-fb48-11e9-89a5-6d33a176d1c0.png)

While the Item trailing the end is useful because it helps identify the name of the Component it was attached to, it also is harder to read at the end. 

**Proposed solution**

It would be better if the class name was something like `class="Item-css-kfjdslf"` because that makes it easier to scan. 

**Alternative solutions**

Even better would be if you could get rid of the "css-fdsafdjk" entirely. I am guessing it's there for namespacing css purposes but I think there's got to be a more visually elegant solution. Something along BEM or these lines maybe? https://zellwk.com/blog/css-architecture-2/

**Additional context**
I'm just using emotion in a framework that uses it as a dependency. So I admittedly don't know the ends and outs of it.

**Comment by Andarist** [comment]
I'm afraid this is a no-go. Hashing is here so you don't have to think about class names at all, you don't have to write them manually - and this is one of the best appeals for css-in-js.

Also labels being suffixes rather than prefixes is important because it's completely an optional thing - we might have it or not and it's easier to manage optional things in the code if they are at the end.

**Comment by jcklpe** [comment]
@Andarist  it's ya'll's project, but I'll just say that while it may be appealing to some to not have to deal with class names, you are still in fact using classes names so they should be easier to understand and read. 

Basing the label format of the css classes off the react component mark up is done in order that developers can keep track of which html elements came from which part of their JSX markup. If that's going to be done then it might as well be done in a way which is readable to the developer.

**Comment by Andarist** [comment]
> you are still in fact using classes names so they should be easier to understand and read.

Using class names with emotion is really just an implementation detail (to some extent).

> Basing the label format of the css classes off the react component mark up is done in order that developers can keep track of which html elements came from which part of their JSX markup. If that's going to be done then it might as well be done in a way which is readable to the developer.

Labels are indeed a helpful development feature - but truth to be told I don't find appending them to the end of the inserted class name much less readable. Emotion is out for quite some time already and also used by many and we didn't have much feedback about this deteriorating readability so far.

**Comment by FezVrasta** [comment]
Aren't source maps there to help you figure out where styles come from? I never need to read the generated class names.

**Comment by jcklpe** [comment]
>Aren't source maps there to help you figure out where styles come from? I never need to read the generated class names.

That's fair. The framework I'm using that uses Emotion has not had support for source maps though there is a pull request currently to fix that so maybe this will be a pretty obvious moot point.

**Comment by nsaunders** [comment]
If you want meaningful class names, you might be interested in a project of mine: https://inline.style/
