### ISSUE TITLE
Warn about interpolation of undefined variables?

### ISSUE THREAD

**Issue by Slapbox** [emotion-js/emotion#1594]
This issue turned out to be caused by an improper import on my part, which `ESLint` didn't identify as missing and which is hard to catch in the debugger. Is there anything that can be done to warn about interpolation of undefined variables?

**Not a bug - Original issue text below**
# Disregard below this point

---- 
## Current behavior:

Referencing another Emotion component from within rules generated via `css` can somehow silently drop the referenced component from the constructed final selector.

```js
const MyHeading = styled.h1``;
const blockquoteStyles = ({ theme }) => css`
    .myDiv & {
      margin-top: 0.5rem;
      padding-left: 14px;
      border-left: 3px solid gray;
      -webkit-margin-start: 30px;

      ${MyHeading} > span {
        border: 1px solid green;
      }
    }
  `;

const MyBlockquote = styled.blockquote`
  ${blockquoteStyles}
`;
```
### `${MyHeading} > span` Outputs:
**Expected:** `.myDiv .css-1kjm6ew-MyBlockquote .css-8kmj9aw-MyHeading > span`
**Actual:** `.myDiv .css-1kjm6ew-MyBlockquote > span`

If I replace `${MyHeading} > span` with `h1 > span` it comes out as expected.

### `h1 > span` Outputs:
**Expected/Actual:** `.myDiv .css-1kjm6ew-MyBlockquote h1 > span`

##To reproduce:
**I cannot reproduce this in a sandbox so far.** I'm confused about why I can even reference emotion components on CodeSandbox, since I don't see the babel plugin referenced anywhere?

This is my template so far, but no luck reproducing: https://codesandbox.io/s/emotion-issue-template-hp56u

## Expected behavior:

Reference to another Emotion component should not be silently dropped.

## Environment information:
- `react` version: `16.10.2`
- `emotion/core` version: `10.0.22`
- `emotion/styled` version: `10.0.23`

**Comment by Andarist** [comment]
> I cannot reproduce this in a sandbox so far. I'm confused about why I can even reference emotion components on CodeSandbox, since I don't see the babel plugin referenced anywhere?

You are using macros there, which are kinda babel plugins 😉 

> This issue turned out to be caused by an improper import on my part, which ESLint didn't identify as missing and which is hard to catch in the debugger. Is there anything that can be done to warn about interpolation of undefined variables?

Undefined is kinda allowed at certain places - so it's not so easy to detect when this happens by accident and when not. I'll try to analyze this later to see if there is anything we could to warn people against this, but this might be tricky to assess.

**Comment by Andarist** [comment]
After giving this some thought over past 2 days - I don't see how we can reliably detect this situation without false positives. Unfortunately we won't try to implement a warning for this ourselves right now, but any external contributions in that area are welcomed if you'd like to take a stab at this.
