### ISSUE TITLE
Remove `innerRef` error, and default prop filtering of `innerRef`.

### ISSUE THREAD

**Issue by ajs139** [emotion-js/emotion#1597]
**Current behavior:**

If a component exposes an `innerRef` property, and it is wrapped with a `styled` component, then the returned component, by default, will intercept the `innerRef` prop. It will also output an error in the console. This is to warn users of prior versions that the `innerRef` prop is no longer supported by emotion's styled components. 

**To reproduce:**

```
// Test.js
import styled from '@emotion/styled';
import React from 'react';

const Component = ({innerRef}) => <p>Inner Ref: {innerRef}</p>;
export default styled(Component);

// App.js
import ReactDOM from 'react-dom';
import React from 'react';
import Test from './Test';

ReactDOM.render(<Test innerRef="some value" />, document.getElementById('root'));
```

**Expected behavior:**

The prop is passed down, or the ability to circumvent the error log is available.

**Other information:**

Several OS libraries have adopted the `innerRef` prop as a means to access the underlying ref, it would be useful to be able to pass this prop through.

#878 also seems to be relevant here.

**Comment by Andarist** [comment]
We can't change this right now as this would be a breaking change. Good news though is that we are preparing a v11 release which, among other things, will do exactly that - remove special handling of `innerRef` altogether. Stay tuned!
