### ISSUE TITLE
Link to nonce 404s

### ISSUE THREAD

**Issue by bolatovumar** [emotion-js/emotion#1598]
**Description:**

See "nonce" link here: https://emotion.sh/docs/create-emotion#primary-use-cases
It leads [here](https://emotion.sh/docs/cache#nonce-string) which is a 404 page.

I would expect it to take you the page explaining what the nonce does.

**Comment by Andarist** [comment]
Thank you for the report! I'll try to fix it as soon as I can - in the meantime the section you were looking for is available here: https://emotion.sh/docs/@emotion/cache#nonce

**Comment by Andarist** [comment]
Got fixed by https://github.com/emotion-js/emotion/pull/1903 for the `next` branch. I hope to ship v11 soon and when this happens the main site will benefit from this fix.
