### ISSUE TITLE
Does emotion support dynamic styling 

### ISSUE THREAD

**Issue by MAmin233** [emotion-js/emotion#1637]
**it can be a great feature if we can update component styles dynamically**
i need a way to update component style as we update the state or props 
however it can be a great feature for creating dynamic animations

if a code like below could work it was fantastic but it don't
```jsx
class MyElem extends Component {
  constructor(props) {
    super(props);
    this.elemRef= React.createRef();
    this.state = {
      opacity: 0
    };
    this.show = this.show.bind(this);
  }

  show() {
    this.setState({ opacity: 1 })
  }

  render() {
    const style = css`
      width:  400px;
      height: 400px;
      opacity: ${ this.state.opacity };
      transition: opacity 1000ms;
    `;
    return (<div ref={this.elemRef} css={style}></div>);
  }
}

```
as we know it's not possible in that way by using setState function because it's style rendered and added before the state changes
how ever we can't even use dynamically add emotion styles as a class to our element like below:

```jsx
const style = css` opacity: 1`;
this.elemRef.current.classList.add(style);  
```
is there any solution for using emotion for dynamic styling? if there is a way to use component's state for styling it can be great

**Comment by FezVrasta** [comment]
styled components can read their own props:

```js
const Foo = styled.div`
  width:  400px;
  height: 400px;
  opacity: ${props => props.opacity};
  transition: opacity 1000ms;
`;
const App = () => {
  const [opacity, setOpacity] = useState(0);

  return <Foo opacity={opacity} onClick={() => setOpacity(1)} />;
}
```

**Comment by Andarist** [comment]
It's also totally possible to do this without styled API. Truth to be told - what you are asking in the issue should already work (with a given code snippet). If it doesn't then please create a repro case that we could inspect (and most likely help you to find a problem in your code).

**Comment by YodgorGA** [comment]
[FezVrasta](https://github.com/FezVrasta) Thank you so much!
