### ISSUE TITLE
Property name validation doesn't work correctly

### ISSUE THREAD

**Issue by zouxuoz** [emotion-js/emotion#1646]
**Current behavior:**

```js
import isPropValid from "@emotion/is-prop-valid";

console.log(isPropValid("onAnyInvalidPropName")); // true
```

**To reproduce:**

Run tests here: https://codesandbox.io/s/emotionis-prop-valid-onanyinvalidpropname-gvl0z

**Expected behavior:**

The package should contain a list of names of all `on` handlers and use it for validation.

```js
import isPropValid from "@emotion/is-prop-valid";

console.log(isPropValid("onAnyInvalidPropName")); // false
```

**Environment information:**

- `@emotion/is-prop-valid` version: 0.8.5

**Comment by Andarist** [comment]
We don't plan to include a whitelist for all possible DOM events - we believe that `on` prefix (followed by an upper case letter) is enough to be considered a "valid" prop in this context. I don't see why you would like to use such prop **just** for styling purposes without forwarding it to the wrapped component.

**Comment by Andarist** [comment]
Closing because we don't plan to change this and OP has not answered back to a previous comment.
