### ISSUE TITLE
[Question]: insertion point of emotion styles. Another component library overrides react emotion rules

### ISSUE THREAD

**Issue by vitaliiznak** [emotion-js/emotion#1647]
I use Ant design components along with react-emotion.
I am ending up with the situation when sometimes ant design styles are added after emotion styles within page <head>tag like.
```html
<style data-emotion="css">...</style>
<style>...</style> <-- ant design style here-->
```
```antd``` is added through ```babel-plugin-import``` so it adds styles as needed on component import.
Anyone has an idea how to fix this?
Is it possible to specify insertion point  when working using libraries like `antd` together with emotion to put emotion styles always at the end?

**Comment by Andarist** [comment]
You can control container where emotion will inject its styles - but they are always inserted after last inserted (emotion) style element. So if any external style gets injected after emotion style tag, emotion wont insert its next style tag after it but rather will keep inserting after its own style tag.

You could configure emotion's container to be `document.body` - which sounds hacky, but it works. And it would probably fix your issue.

**Comment by vitaliiznak** [comment]
@Andarist 
Thanks, it may help
But, how can I configure emotions style containers?
Are you talking about this configuration [docs/@emotion/cache#container](https://emotion.sh/docs/@emotion/cache#container)?
it is used with CacheProvider from `@emotion/core` and it doesn't seem to work with framework-agnostic `emotion` configuration

**Comment by Andarist** [comment]
Basically the same configuration can be used in combination with `create-emotion` which you have to use instead of the default emotion’s instance
