### ISSUE TITLE
Importing an Emotion style partial from a separate module yields improper results, but importing from file works

### ISSUE THREAD

**Issue by Slapbox** [emotion-js/emotion#1649]
**Current behavior:**

Importing a style partial from another module in Webpack environment leads to invalid style output, but importing from a local file works fine.

**To reproduce:**

I'm using Webpack and Babel. I've searched as thoroughly as I can for a cause to this issue, but I've found no leads. The main project and the module I'm trying to import from are both within a single Lerna monorepo and both have identical `.babelrc` configurations. The Babel configuration includes the `babel-plugin-emotion`.

 Here's the style partial in question:

```js
import { css } from 'emotion';
export const zoomPartial = css`
  zoom: 0.9;
`;
```

**When I import the partial like this, I get the proper output:**

```js
import { zoomPartial } from './partials';
```

![image](https://user-images.githubusercontent.com/6835891/69460242-a32ea580-0d41-11ea-9f36-0286e4f65e52.png)

[![enter image description here][1]][1]

**But when I import like this, I get an improper output:**

```js
import { zoomPartial } from 'partials-module';
```
![image](https://user-images.githubusercontent.com/6835891/69460260-ad50a400-0d41-11ea-9ddc-1b16948233cc.png)

**Expected behavior:**

Import behavior would be identical.

**Environment information:**

- `react` version: `16.11.0`
- `emotion` version: `10.0.23`

**Comment by Andarist** [comment]
> Import behavior would be identical.

Emotion is totally unaware of your imports - this is a clear indication that your issue is not caused by emotion as emotion just receives a value in the runtime and has no idea about its origin. It just processes what it gets.

I could help you debug this - if you provide a repro case, can't do much without it.

**Comment by Slapbox** [comment]
Thanks for the response @Andarist. I'll continue to search on my end and re-open if I still can't come up with anything.
