### ISSUE TITLE
babel-emotion-plugin not working with custom instances

### ISSUE THREAD

**Issue by ivanbanov** [emotion-js/emotion#1657]
Seems like the custom instances are not working properly
I've reported it on xstyled repo (https://github.com/smooth-code/xstyled/issues/77) but perhaps it's related to the emotion plugin.
Also, when importing xstyled ThemeProvider using its own preset an error is happening, it may be related to the [babel-plugin-jsx-pragmatic](https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-jsx-pragmatic) plugin

xstyled preset
https://github.com/smooth-code/xstyled/blob/master/packages/babel-preset-emotion-css-prop/src/index.js

is it anyhow related to the emotion plugins?

**Comment by Andarist** [comment]
This got fixed in https://github.com/emotion-js/emotion/pull/1220 but this is going to be a part of upcoming v11, unfortunately we don't have time resources to backport this to v10.

**Comment by Andarist** [comment]
Closing this because it has already been implemented in v11. Stay tuned for a release!
