### ISSUE TITLE
style tag won't be provided if styled property contains ascii unicode prefix

### ISSUE THREAD

**Issue by hachibeeDI** [emotion-js/emotion#1660]
**Current behavior:**

Style isn't provided if ascii unicode was applied like `content: "\1f4a5";`.

**To reproduce:**

1. Create a styled component contain unicode prefix:

```javascript
const Title = styled.h1`
  font-size: 30px;
  color: red;
  &::after {
    content: "\1xxx"; // any unicode for web emoji
    /* content: "\\1xxx"; to work around, I doubled the backslash and it works fine */
  }
`;
```

2. Open browser

3. Confirm css name was generated like `css-1cdv3h8-Title`

4. Confirm no styled was provided for the class

Working Sandbox:
https://codesandbox.io/s/emotion-issue-template-wuh80

**Expected behavior:**

Generate same css as I written.
  or
Provide error message because of unicode around problem.

**Environment information:**

- `react` version: 16.8.6
- `emotion` version:
    "@emotion/core": "10.0.10",
    "@emotion/css": "10.0.9",
    "@emotion/styled": "10.0.11",

Thanks!

**Comment by Andarist** [comment]
The error is already in place - see https://codesandbox.io/s/emotion-issue-template-ze0kf

It's available in more recent versions of our packages than what is installed in that CodeSandbox. The error might not be visible if you are using our babel plugin or macros with `@babel/parser` (which gets used by you indirectly) older than 7.4.3

I hope this resolves your issue - if not please followup with questions and I will gladly answer.

**Comment by hachibeeDI** [comment]
Hi, thanks for your quick reply!
Sorry, I missed the runtime error in the CodeSandbox.

And yes, my project is using babel and babel-plugin-emotion as you guess, those are latest though... 
 Compile process of my project has bunch of plugins so I guess something is happening in it.
I'll dig into it. Thank you again.

**Comment by lucaseverett** [comment]
@hachibeeDI Did you ever find what was causing this? I'm having the same issue.
