### ISSUE TITLE
Inline Optional Typescript Type is invalid in eslint

### ISSUE THREAD

**Issue by RichieRunner** [emotion-js/emotion#1669]
**Current behavior:** Adding an optional type throws off a generic eslint error.

**To reproduce:**
```javascript
const StyledChevron = styled.div<{
  stateOpen?: boolean,
  inverse: boolean
}>``;
```

![image](https://user-images.githubusercontent.com/20289967/70015234-9aa05100-1531-11ea-91de-8ae268d4bf8e.png)

**Expected behavior:**
Not including the optional type does not throw an error from eslint.
```javascript
const StyledChevron = styled.div<{
  stateOpen: boolean,
  inverse: boolean
}>``;
```
I understand that having the inline optional Typescript type should be valid? Has anyone able to get this to work with Typescript?

**Environment information:**

- `react` version: "^16.8.0"
- `emotion` version: "^10.0.6"
- `typescript` version: "3.8.0-dev"
- `estlint` version: "5.16.0"

**Comment by Andarist** [comment]
It seems like a possible bug with ESlint's TypeScript parser. Could you report it over there?
