### ISSUE TITLE
@emotion/styled with theme is still marked as any and not the custom theme

### ISSUE THREAD

**Issue by lowe1111** [emotion-js/emotion#1671]
I wanted to use a @emotion/styled with my custom theme.I am using typescript and I did everything as documented in: 
https://emotion.sh/docs/typescript#define-a-theme
So this is my `styled.tsx` file: 

```
import emotionStyled from '@emotion/styled'
import {
  CreateStyled,
} from '@emotion/styled'
import {theme} from "./aroundTheme";

const styled = emotionStyled as CreateStyled<typeof theme>;

export default styled;
```

Now when I'm using this `styled` function, the props are still marked as `any` and not as props with my custom Theme. 

```
import styled from "../../theme/styled";

export const ButtonWrapper = styled.button`
//...
  background-color: ${props => props.theme.green.a10};
`;
```
This is the error I receive:
`Error:(5, 23) TS7006: Parameter 'props' implicitly has an 'any' type.`

Am I'm missing something here? Or have I done anything wrong?

I'm using: 

```

    "@emotion/core": "^10.0.22",
    "@emotion/styled": "^10.0.23",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
    "typescript": "^3.7.2"

```

**Comment by Andarist** [comment]
Sorry for the inconvenience but I'm afraid that I won't be able to help you with this one right now. v10 typings are rather complex and have some quirks - they have been completely reworked and the rewrite is available in v11 (still in beta). We plan to release v11 this month (no promises though!) and I believe that migrating to it will resolve your issue. I also encourage you to try out currently published v11 version - it's very much usable, doesn't have many breaking changes and we don't plan to make any significant breaking changes either. You could only maybe hold off until we release this https://github.com/emotion-js/emotion/pull/1609 as it is concerned with TS and Theme so affects you quite a bit.

**Comment by lowe1111** [comment]
Okay no problem! Thanks for the quick response anyway :)
