### ISSUE TITLE
unable to use css props with create-react-app and typescript 

### ISSUE THREAD

**Issue by kurosh-z** [emotion-js/emotion#1674]
I setup a create-react-app project with typescript and as documentation says added  jsx Pragma /** @jsx */ on top of the code  to be able to access css prop.
But I'm still getting this error :

<img width="609" alt="Screenshot 2019-12-05 at 22 21 02" src="https://user-images.githubusercontent.com/32224317/70274999-88324b80-17ad-11ea-88ab-b25a1a601cd0.png">

doing the exact same thing however in codesanbox works perfectly fine!
I assume I have to import jsx form emotion-core but then it completely fails to compile because jxs is imported and it's never been used!

<img width="609" alt="Screenshot 2019-12-05 at 22 25 57" src="https://user-images.githubusercontent.com/32224317/70275325-38a04f80-17ae-11ea-8eb2-736c9832c6ea.png">

I was wondering if I'm missing something here or there is an actual issue with jsx Pragma.

**Comment by Andarist** [comment]
Could you prepare a repro case? I could then take a look at this.

**Comment by kurosh-z** [comment]
I reduced the code to a very simple example and it actually works fine. Somewhere in my original code I had  /** @jsx */ instead of /** @jsx jsx */ .
