### ISSUE TITLE
border-radius property not working with Text (@emotion/native)

### ISSUE THREAD

**Issue by hwkd** [emotion-js/emotion#1678]
**Current behavior:**
The border-radius property doesn't work with `styled.Text`:
```
const MyText = styled.Text`
  border: 1px solid #888;
  border-radius: 5px;
`;

<MyText>Hello, world!</MyText> // Border radius is not applied
```

However, if I do the following, it works fine:
```
<Text style={{ borderRadius: 5, borderWidth: 1, borderColor: "#888" }}>
  Hello, world!
</Text>
```

I've tried using `border-radius` with `styled.View` and it works fine too, so my guess is that it's a bug with `styled.Text`.

**To reproduce:**
Try the following:
```
import styled from "@emotion/native"

const MyText = styled.Text`
  border: 1px solid #888;
  border-radius: 5px;
`;

const Example = () => (
  <MyText>Hello, world!</MyText> // Border radius is not applied
);

export default Example; // then import, and render in your sample app.
```

**Expected behavior:**
It should apply `border-radius` on the `MyText` component (created via `styled.Text`).

**Environment information:**

- `react` version: 16.12.0
- `react-native` version: 0.60.5
- `@emotion/core` version: 10.0.22
- `@emotion/native` version: 10.0.22

**Comment by Andarist** [comment]
Those React Native packages are fully community-drive. The core team has no enough time resources to handle issues with those packages. I encourage you to dive into the codebase and try to fix the issue.

**Comment by hwkd** [comment]
Sure, I'll see if I can work on that once I get some time.

**Comment by nanxiaobei** [comment]
Any update? 😟

**Comment by hwkd** [comment]
I completely forgot about this issue. I've done a rework on the app I worked on at the time and used the React Native's StyleSheet API instead and I'm pretty satisfied with it. I will close this issue since it's been a while this issue was opened but has not been addressed for such a long time.
