### ISSUE TITLE
Invalid type for styled components targeting other components

### ISSUE THREAD

**Issue by OzTK** [emotion-js/emotion#1684]
**Current behavior:**

When using TypeScript with styled components, creating 2 separate components, one referring to the other in its style, the second component (targeting the first one in style) is also inheriting the props from the first one.

**To reproduce:**

Can be observed here: https://codesandbox.io/s/emotion-issue-template-vmxxl

1. Create a component with a prop
2. Create the styled version of that component
3. Create another component with a different prop
4. Create the styled version for that other component. Refer to the previous component in the style
5. Use the second component in some JSX --> Both props are required

**Expected behavior:**

A styled component targeting another one should not inherit its props

**Environment information:**

- `react` version: 16.8.6
- `@emotion/core` version: 10.0.22
- `@emotion/styled` versuion: 10.0.23

**Comment by frankwallis** [comment]
This sounds like the same issue as https://github.com/emotion-js/emotion/issues/1655
Which has been resolved by https://github.com/emotion-js/emotion/pull/1664

But I don't think the fix has been released yet (it is not present in v11.0.0-next.8)

**Comment by Andarist** [comment]
I have just released 11.0.0-next.9 with a fix for this issue - please try it out and raise a new issue if the problem persists.

**Comment by OzTK** [comment]
Confirmed it works. Thanks a lot!
