### ISSUE TITLE
Migration docs, cache not resolved

### ISSUE THREAD

**Issue by JeSuis** [emotion-js/emotion#1687]
**Description:**
Migration docs state adding a cache while updating emotion to v10 piecemeal
https://emotion.sh/docs/migrating-to-emotion-10#manual-steps

However upon attempting this I saw that `cache` is not resolved
![image](https://user-images.githubusercontent.com/2349269/70659227-aaa0ea80-1c2d-11ea-9215-4a73299f478f.png)
https://github.com/emotion-js/emotion/blob/v9-docs/packages/emotion/types/index.d.ts#L17

Upon seeing that `caches` exists, I gave that a try, however the following error occurs
`cache.insert is not a function`

I'm assuming the later is resolved when `cache` is imported properly.

**Documentation links:**
https://emotion.sh/docs/migrating-to-emotion-10#manual-steps
https://github.com/emotion-js/emotion/blob/v9-docs/packages/emotion/types/index.d.ts#L17

**Comment by Andarist** [comment]
Im not sure why you are checking v9-docs branch - not sure about the history, maybe caches has existed back then but its cache and its typed correctly on master branch (and in published to npm v10 package)

**Comment by JeSuis** [comment]
you just made me realize I had v10 for @emotion/core but emotion was still at 9
