### ISSUE TITLE
Update type definitions to latest @types/jest

### ISSUE THREAD

**Issue by NicholasBoll** [emotion-js/emotion#1689]
**Current behavior:**

If a project uses Jest types at version 24 or greater, this package will conflict the type definition of `Matchers`. The type error is:

```
node_modules/jest-emotion/types/index.d.ts:33:15 - error TS2428: All declarations of 'Matchers' must have identical type parameters.

33     interface Matchers<R> {
```

The change to the `Matchers` signature happened here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39243/files#diff-013c5ccd6d4d4b59b744d1b1aa39c80fL54

The version this change occurred in is `@types/jest@24.0.20`. This package requires `@types/jest@^23.0.2`.

https://github.com/emotion-js/emotion/blob/master/package.json#L178

Since `jest` is declared globally, these interfaces must have mergeable signatures. Fixing might be a breaking change?

Fixing would require updating the `@types/jest` to the latest version and changing the interface of `Matchers` to:

```ts
interface Matchers<R, T> {
```

https://github.com/NicholasBoll/jest-emotion-issue
Repo:
1. `yarn install`
2. `yarn tsc index.ts`

**Expected behavior:**

There should be no error

**Environment information:**

It only matters that the project depends on `test@24.0.30` or higher or another dependency does. The PR I linked shows many packages that rely on `@types/jest` that were updated together.

**Comment by Andarist** [comment]
This has been already done on `next` branch - unfortunately, it's a breaking change of sorts and we'd like to avoid introducing it to v10.

**Comment by NicholasBoll** [comment]
Thanks for that info. I didn't find an issue that matched. If the next major version of @emotion comes out soon, it is probably fine. If v11 will take a while, people using Typescript and later versions of Jest types will be blocked from upgrading until that change is released.

**Comment by Andarist** [comment]
Yes - this is unfortunate but also not our fault. `@types/jest` broke this in a patch release.

A good thing though is that v11 is almost done - hopefully we should ship this month

**Comment by Andarist** [comment]
As discussed - this is already a part of the upcoming v11 and we'd rather like to avoid fixing this in v10 because it's sort of a breaking change. Gonna close this and I hope we manage to release v11 in a couple of weeks.
