### ISSUE TITLE
LICENSE file should be included in npm bundle

### ISSUE THREAD

**Issue by nappy** [emotion-js/emotion#1694]
The license text is currently not provided with the npm bundle.
In order to allow automation tools like `license-webpack-plugin` to pick it up, it should be included there.
Also the license states: The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
This includes the npm registry.

**Comment by Andarist** [comment]
Do you require license text everywhere? Why `license` field is not enough? It points to MIT license which has known content that can be checked in a lot of places on the internet - for example here: https://opensource.org/licenses/MIT

**Comment by nappy** [comment]
a) Not I require it, the license requires it.
b) Its not required everywhere but In all copies or substantial portions of the software, which an npm package definitely is.
c) The generic text does not include year and copyright holder and might change over time. Also there is no link to the URL where it could be sourced from automatically.
d) 90% of the packages I (indirectly) depend on already do it this way, so its the best practice.
e) If yourself do not include the license text, how much sense make it to you to require it from your dependents?

**Comment by Andarist** [comment]
Ok, I've created a PR to add this - https://github.com/emotion-js/emotion/pull/1698
