### ISSUE TITLE
allow optional @ inside /* emotion-disable-server-rendering-unsafe-selector-warning-please-do-not-use-this-the-warning-exists-for-a-reason */

### ISSUE THREAD

**Issue by xxx** [emotion-js/emotion#1705]
**The problem**

We're have a library, and want to turn off the `first-child`, etc. warnings, since SSR is not a concern for us. I'm aware of adding `/* emotion-disable-server-rendering-unsafe-selector-warning-please-do-not-use-this-the-warning-exists-for-a-reason */` as a comment, but because we also use [babel-plugin-emotion](https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion), the comment is simply stripped away during minification.

[babel-plugin-emotion skips removal of comments that have `@` embedded within them](https://github.com/emotion-js/emotion/pull/1336), and it would be nice to be able to add that to the magic comment that, at this time, must be character-for-character identical to what I pasted above.

**Proposed solution**

Loosen the requirements to use the magic comment such that a `@` can be added, to prevent babel-plugin-emotion from stripping it away during minification.

**Alternative solutions**

Only emit the warning if actually used in an SSR context.

**Additional context**

N/A

**Comment by Andarist** [comment]
This indeed sounds useful, I think we should squeeze this into upcoming v11. Would you maybe be willing to work on this? I believe we should just make this comment kept **for** non-production code as-is, no `@` required.

**Comment by xxx** [comment]
I will see what I can do, but my time is squeezed at the moment. I don't know what the schedule for v11 is.

**Comment by Andarist** [comment]
I've implemented this change as part of the https://github.com/emotion-js/emotion/pull/1817 , any comment that includes this ignore flag will work when this PR lands.
