### ISSUE TITLE
Types: `props.theme` should not be optional in Emotion 11

### ISSUE THREAD

**Issue by fabien0102** [emotion-js/emotion#1707]
**Current behavior:**

The `props.theme` is `Theme | undefined` instead of `Theme`, so it's very hard to migrate to emotion 11 since we need to make sure that the theme is there on every usage.

This was previously discussed and fixed here -> https://github.com/emotion-js/emotion/pull/1501#issuecomment-553489241

I also follow the project to migrate to the new way, as describe here -> https://github.com/emotion-js/emotion/blob/next/docs/typescript.mdx

Note: Since the theme is a runtime variable inject by the `ThemeProvider`, I totally get that `Theme` is actually in reality optional and the current implementation is more typesafe, but in another hand, this will be very painful to use if we need to check everytime if the theme is there before consuming it… 

**To reproduce:**

https://codesandbox.io/s/brave-tereshkova-lx8sn

![image](https://user-images.githubusercontent.com/1761469/71978846-9811d500-321c-11ea-9df5-6229562949d4.png)

=> `props.theme` is `Theme | undefined` instead of `Theme`

**Expected behavior:**

I was expecting `props.theme` to be `Theme`, so the migration to emotion 11 is way less painful 😬 

**Environment information:**

- `react` version: 16.8.4
- `emotion` version: 11.0.0-next.10

**Comment by Andarist** [comment]
https://github.com/emotion-js/emotion/blob/31e610f2385d5a3dfd532b31f743e5f6b9fee43b/docs/typescript.mdx#define-a-theme
> If you were previously relying on theme being an any type, you have to restore compatibility with: [...]

**Comment by fabien0102** [comment]
Thanks, but I like my typesafety, this was not `any` and putting `any` there will be a HUGE lost…

So I guess you suggest that we need to check if theme is there everytime? 😕

**Comment by fabien0102** [comment]
For the record, this was considered like a bug two months ago and fixed -> https://github.com/emotion-js/emotion/pull/1501#issuecomment-553840838

**Comment by fabien0102** [comment]
Also, this is not consistant with the object notation, `Theme` is well defined in this case.

```tsx
import styled from "@emotion/styled";

export default styled.h2(({ theme }) => ({
  color: theme.color // `theme` is `Theme` here
}));
```

**Comment by Andarist** [comment]
Ok, so I've actually misunderstood your original report here. I've focused myself on that error reported in french - and for that my advice still holds, you should augment builtin interface. But you have also found an issue with our typings 👍 probably a result of different PRs being merged in a roughly the same time and caused a mergeable conflict.

**Comment by Andarist** [comment]
Has been fixed by https://github.com/emotion-js/emotion/pull/1708 . Still need to resolve `@emotion/serialize` problem in https://github.com/emotion-js/emotion/pull/1710 , but expect a new release soon-ish.
