### ISSUE TITLE
How to merge `css` styles with `cloneElement`?

### ISSUE THREAD

**Issue by moroshko** [emotion-js/emotion#1713]
Given an element with `css` styles, I'd like to clone it and add more `css` styles.

Using a [custom `cloneElement`](https://github.com/emotion-js/emotion/issues/1102#issuecomment-446887725) throws an error:
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

...and using `React.cloneElement` doesn't merge the styles.

Any ideas?

cc @Andarist

[Codesandbox](https://codesandbox.io/s/quirky-butterfly-ep8v4)

**Comment by Andarist** [comment]
https://codesandbox.io/s/compassionate-curie-3gkzn

**Comment by moroshko** [comment]
@Andarist Yeah, I was thinking about doing this but it felt like a hack.
Is this the recommended approach? Is it future proof?

**Comment by Andarist** [comment]
Yes, arrays will be always supported and its a good composition mechanism :)

**Comment by moroshko** [comment]
Hey @Andarist,

What type of objects the `css` array is expected to have?
In [your sandbox](https://codesandbox.io/s/compassionate-curie-3gkzn), I see plain style objects like `{ color: "red" }` and `{ border: "1px solid black" }`.

But, in my app, I see 2 different behaviors:

1. `children.props.css` has the following shape: `{ name: "dlz2dp-Checkbox", styles: "...", map: "...", next: undefined, toString: <function> }`.
  The objects are still merged as expected here and I see the expected outcome.

2. `children.props.css` is `undefined` and the result in dev tools is: `<label css=",[object Object]" ... />`
  Obviously, here the objects are mot merged and the result is not what I expect.

The difference between the 2 cases is that in (1) both components live side by side (they are both part of the design system), whereas in (2) the wrapper component (the one that performs the cloning) is part of a Gatsby site and the inner component (the one that doesn't define any `css`) is part of the design system. The Gatsby website is using `gatsby-plugin-emotion`.

I'll try to create a minimal repro when I get the time, but I thought I'd ask you first in case you have any clues. Thanks for your help 👍

**Comment by Andarist** [comment]
> The objects are still merged as expected here and I see the expected outcome.

`css` call outputs such an object, it's called a serialized style. This is an optimization that we have implemented because many styles can be evaluated once and cached in such an object - some of the styles can be even converted to such an object at build time by our Babel plugin. That's why it's a valid input argument for `css`, css prop etc. You just receive it from the caller, already preevaluated and that's why you are seeing that. Object styles are allowed as well, because we don't force you to wrap it with css call each time (`css(objStyle)`)

> Obviously, here the objects are mot merged and the result is not what I expect.

Most likely you have forgotten to use a jsx pragma.

**Comment by Andarist** [comment]
@moroshko have you resolved your problem? Can this be closed?

**Comment by moroshko** [comment]
Yep, thanks @Andarist for your help!
