### ISSUE TITLE
Reverse Selector does not work properly for generated classnames.

### ISSUE THREAD

**Issue by LXSMNSYC** [emotion-js/emotion#1715]
Example code:

```jsx
/** @jsx jsx */
import { jsx, css } from '@emotion/core'

const paragraph = css`
  color: turquoise;
`

const link = css`
  color: red;
  .${paragraph} & {
    color: green; 
  }
`;

render(
  <>
    <a css={link}>A link with a bottom border.</a>
    <p css={paragraph}>
      Some text.
      <a css={link}>A link with a bottom border.</a>
    </p>
  </>
)
```

**Current behavior:**

From the Emotion website:
<img width="734" alt="Screen Shot 2020-01-12 at 11 41 31 PM" src="https://user-images.githubusercontent.com/4783372/72221381-38f1ee80-3595-11ea-98f4-c3038f565c2c.png">

**To reproduce:**

https://codesandbox.io/s/emotion-issue-template-4ellp

**Expected behavior:**

The first `<a>` component should have been colored in red.

**Comment by LXSMNSYC** [comment]
<img width="222" alt="Screen Shot 2020-01-12 at 11 55 02 PM" src="https://user-images.githubusercontent.com/4783372/72221552-01844180-3597-11ea-84ab-c1996f060010.png">

Interestingly, it seems that the link also receives the same style as the paragraph.

**Comment by Andarist** [comment]
This seems like a problem with documentation. It seems to use an outdated pattern. 

One of emotion's goal is to have predictable styles. Using nested selectors is against this goal - because you really cannot ever tell what exact styles an element will have without knowing its surrounding context.

`@emotion/core` doesnt allow you easily to access a class name as a string (you get an object back that you should , so this kind of a composition is not possible. What happens here, in fact, is that `paragraph2` styled are being merged into `link2` styles (in an incorrect way, because of the `.`).

**Comment by LXSMNSYC** [comment]
After looking up tens of past issues, I found out that interpolation of classnames will be deprecated.

It's disappointing though that such a good feature, which was implemented by a css-in-js library that supports template strings, is going to be deprecated.

**Comment by Andarist** [comment]
> The emotion types tells us that it is a string.

Not quite, it's `SerializedStyles`:
<img width="641" alt="Screenshot 2020-01-14 at 09 46 17" src="https://user-images.githubusercontent.com/9800850/72328218-cf680200-36b2-11ea-9ceb-ba6195223135.png">

**Comment by LXSMNSYC** [comment]
You might be talking about the latest typings, because in Emotion 10, this is clearly the output
<img width="286" alt="Screen Shot 2020-01-14 at 10 17 39 PM" src="https://user-images.githubusercontent.com/4783372/72351690-ca8b6880-371b-11ea-803e-39b7e9d306de.png">

**Comment by Andarist** [comment]
`emotion` is a different package - with slightly different goals. And in its case - yes the return type is a string. 

The cascade is really often a source of maintainability problems and thus this pattern is strongly discouraged by emotion.

**Comment by LXSMNSYC** [comment]
so class names interpolation for nested selectors are now deprecated? now, that'd disappointing.

**Comment by Andarist** [comment]
This is a tradeoff we are making - less flexibility in defining your styles for maintainable & predictable styles.

I understand that you might not like it, but we don't plan to change our philosophy around this.
