### ISSUE TITLE
@emotion/serialize is not published with the renamed packages.

### ISSUE THREAD

**Issue by cornedor** [emotion-js/emotion#1718]
**Current behavior:**

@emotion/serialize is not published and its types still refer to @emotion/core.

**To reproduce:**

1. Install @emotion/react@11.0.0-next.10
2. Open node_modules/@emotion/serialize/types/index.d.ts
3. Third line reads: import { Theme } from '@emotion/core'

Or

See: https://cdn.jsdelivr.net/npm/@emotion/serialize@0.12.0-next.3/types/index.d.ts

**Expected behavior:**

The already updated version is published. The renamed packages can be used with TypeScript again.

**Environment information:**

- `react` version: 16.11.0
- `emotion` version: 11.0.0-next.10 `@emotion/serialize` version: 0.12.0-next.3

**Comment by Andarist** [comment]
Yes, this was an oversight on our side. You can track progress on the fix for that here https://github.com/emotion-js/emotion/pull/1710 .

**Comment by Andarist** [comment]
I believe that this got fixed by https://github.com/emotion-js/emotion/pull/1726 . Gonna prepare a new release with that included in a moment.
