### ISSUE TITLE
sheet.speedy option has no impact on global styles

### ISSUE THREAD

**Issue by oleblaesing** [emotion-js/emotion#1720]
**Current behavior:**

We want to have all of our CSS written directly into the documents head (for whatever reason). To enable this behavior, we are using the `sheet.speedy` option and provide it via the cache provider. Every styled component CSS gets written to the document head, only styles given to the `<Global>` element won't show up there.

It seems to be the case, that the global stylings are only get rendered to the head, when the `NODE_ENV` is set to `development` (or just not set to `production`, don't know). The speedy option seems to be fully ignored here.

**Expected behavior:**

The speedy option is prioritized over the current `NODE_ENV` setting for every functionality related to it.

**Environment information:**

- `react` version: `^16.8.6`
- `emotion` version: `^10.0.27`

**Comment by Andarist** [comment]
If that's not a problem for you - I would prefer fixing this only for the upcoming v11.

**Comment by Andarist** [comment]
The fix for this got merged into v11 some time ago and should be released soon.
