### ISSUE TITLE
Sourcemapping can't be turned off in development

### ISSUE THREAD

**Issue by craigtockman** [emotion-js/emotion#1722]
Steps to reproduce.

1. Install babel-plugin-emotion
2. In .babelrc set sourceMap to false
```
"plugins": [
    ["emotion", { "sourceMap": false }],
```
3. Run project and check styles in head tag:
```
.css-whh5e5-ioS0rIYrB61{opacity:1;}/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCl19... */
```
Expected:
Not to see sourceMappingURLs in development.
Actual:
Seeing sourceMappingURLs in development.

```
"@emotion/babel-preset-css-prop": "^10.0.17",
"@emotion/core": "^10.0.17",
"babel-plugin-emotion": "^10.0.27"
```

**Comment by Andarist** [comment]
Could you prepare a **runnable** repro case?

**Comment by oeduardoal** [comment]
In the docs

https://emotion.sh/docs/source-maps

**Comment by oeduardoal** [comment]
Required For Source Maps:

- babel-plugin-emotion must be in your Babel setup.
- process.env.NODE_ENV must be any value **except** "production"

**Comment by Andarist** [comment]
yes, that's true - but `sourceMap: false` being passed to the babel plugin should disable it for all environments ( https://emotion.sh/docs/babel-plugin-emotion#sourcemap )

**Comment by Andarist** [comment]
Closing because the OP has not responded back after my prompt response. If you provide a **runnable** repro case for this then I could take a look at your problem.
