### ISSUE TITLE
`forwardRef` in combination with `as` isn't typed as expected (tsc)

### ISSUE THREAD

**Issue by AlexFrazer** [emotion-js/emotion#1725]
**Current behavior:**

I want to use an existing component, override the `as` property, and forward a ref. When I try to do this, it causes a mismatch with the expected type for the `ref`.

**To reproduce:**

1. Create a styled component of any variety.
```tsx
const Box = styled.div`
  padding-left: 1rem;
  padding-right: 1rem;
  padding-top: 0.25rem;
  padding-bottom: 0.25rem;
`;
```
2. Create a separate component which forwards a ref and applies an `as` that doesn't match the type of the existing element that is being rendered.
```tsx
type BoxProps = ComponentPropsWithoutRef<typeof Box>;

const Input = forwardRef<HTMLInputElement, BoxProps>((props, ref) => {
  return <Box as="input" {...props} ref={ref} />
});
```

This will emit the following error from TSC:
```tsx
Type 'Ref<HTMLInputElement>' is not assignable to type 'string | ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined'.
```

See above

**Expected behavior:**

I would expect `as` to change the type of the component such that ref could be applied. I'm not entirely sure if this can be done with Typescript.

**Possible workaround**: optional generic?

```tsx
<Box<HTMLInputElement> as="input" ref={ref} />
```

**Environment information:**

- `react` ^16:
- `emotion` ^10:

**Comment by Andarist** [comment]
`"as"` is a highly dynamic prop, I personally have no idea how to add type support for what you are asking for.

**Comment by JakeGinnivan** [comment]
`Box.withComponent('input')` will work as expected with the types, the proposed workaround I don't think will be possible because it's not just the ref type, it's the event handlers and all the other intrinsic component prop types which would need to be replaced.

If you need the dynamic nature of `as` you will probably just need to use a cast. `<Box as="input" ref={ref as any} />`.

**Comment by AlexFrazer** [comment]
@JakeGinnivan that works great for me, I'll use that

**Comment by Andarist** [comment]
Closing this then 😄
