### ISSUE TITLE
Show compiled code on website

### ISSUE THREAD

**Issue by mitchellhamilton** [emotion-js/emotion#173]
It would be great if people could easily see what emotion's compiled code looks like so they can understand how it works and understand the limitations.

I'm thinking we could do this with a button on the editor that swaps between compiled code and uncompiled code similar to [Svelte's REPL](https://svelte.technology/repl) and [the React docs homepage](https://facebook.github.io/react/).

**Comment by tkh44** [comment]
Yes! I was also thinking we should steal the `x-ray` look from styled-system's site http://jxnblk.com/styled-system/

**Comment by tgrecojs** [comment]
hey! I'm definitely interested in helping out here 😄 i'm going to spend some time getting some stuff together. let me know if there's any other references you think may be helpful! 

emotion-js is awesome. excited to help build such an awesome piece of technology 💪 💪 💪
