### ISSUE TITLE
unable to display images as background images dynamically

### ISSUE THREAD

**Issue by harish92** [emotion-js/emotion#1740]
const products = [
  {
    title: 'Golden Emerald',
    price: '700',
    image: 'images/products/1.jpg',
  },
  {
    title: 'Logan Sapphire',
    price: '700',
    image: 'images/products/2.jpg',
  },
  {
    title: 'Royal Topaz',
    price: ' 700',
    image: 'images/products/3.jpg',
  },
  {
    title: 'Light azore',
    price: '700',
    image: 'images/products/4.jpg',
  },
  {
    title: 'Chawlk Emerald',
    price: '700',
    image: 'images/products/5.jpg',
  }
]

       <Card css={css`
       background-image: ${props.bgImage}
      `}>
          <div className="prdImage">
              <image src={props.productImage} />
          </div>
            <CardFooter>
                <Link href="/products">
                    <Title>
                        {props.ProductTitle}
                    </Title>
                    <Paragraph>
                        <div dangerouslySetInnerHTML={createMarkup(props.productPrice)} />
                    </Paragraph>
                </Link>
            </CardFooter>
        </Card>

**Comment by Andarist** [comment]
Please provide a **runnable** repro case.

**Comment by Andarist** [comment]
A runnable repro has not been provided, so I have to close this.
