### ISSUE TITLE
Generated classname doesn't use labelFormat template, using css props with theming

### ISSUE THREAD

**Issue by mariajplmiranda** [emotion-js/emotion#1742]
**Current behavior:**
I've a typescript project which supports theming and we use css props to style the components. We do have the labelFormat configured as documented but for the our use case the passed templated is ignored and it's used the default labelFormat value. 

I've tested exactly the same component without theme, and the labelFormat is used properly as set in the babel.config.json. 

I believe this is an issue when we use functions (which happens when we need to use the theme), since the same component works properly with string templates.

**To reproduce:**

1. Typescript project with emotion, @emotion/babel-preset-css-prop preset and emotion-theming
2. Set `"labelFormat": "[filename]--[local]"`
3. Call the following component `<LabelFormatBug />`

```
export const without = css`
  background: red
`;

export const with = (theme: Theme) => css`
  background: green
`;

const LabelFormatBug = () => (
  <div>
    <span css={styles.without}>Hi I'm styled without theming</span>
    <span css={styles.with}>Hi I'm styled WITH theming</span>
  </div>
);
```

4. You should be able to notice now the second span doesn't follow the labelFormat guidelines

**Expected behavior:**

With or without theme, using css props as string template or as a function all scenarios should follow the labelFormat templated defined in our babel config file.

**Environment information:**

- "react": "16.12.0"
- "@emotion/core": "10.0.22"
- "emotion-theming": "10.0.19"
- "@emotion/babel-preset-css-prop": "10.0.23"

**Comment by Andarist** [comment]
This is currently not working by design, but it makes IMHO sense to change this behavior. I've prepared a PR for this - https://github.com/emotion-js/emotion/pull/1805 . Please note that it is targeting the next branch, so it will be a part of our upcoming v11 release.
