### ISSUE TITLE
cache.sheet.rehydrate is not a function in @emotion/cache v11

### ISSUE THREAD

**Issue by hennessyevan** [emotion-js/emotion#1743]
**Current behavior:**

While trying to get tests to pass upgrading @xstyled to emotion 11 tests fail with `cache.sheet.rehydrate is not a function` coming from https://github.com/emotion-js/emotion/blob/next/packages/cache/src/index.js#L252

In my codesandbox however, I'm getting something else. I'm not sure what's going on here.

**To reproduce:**

https://codesandbox.io/s/dawn-sun-tkico

**Environment information:**

- `react` version: 16.11.0
- `emotion` version: 11.0.0-next.11

**Comment by Andarist** [comment]
Have you maybe forgotten to save the sandbox? I don't see emotion nor xstyled used in there and there are no errors as far as I can tell.

**Comment by Andarist** [comment]
Closing because a runnable repro case has not been shared.
