### ISSUE TITLE
Styles disappear (flash) with latest Chrome on Ubuntu

### ISSUE THREAD

**Issue by belgattitude** [emotion-js/emotion#1745]
**Current behavior:**

> **Edit**. Seems related to loom extension, see #1746 

Since yesterday and with latest chrome Version 79.0.3945.130 (Official Build) (64-bit) / Ubuntu, emotions styles appears on page load then suddenly disappear.

![issue-emotion](https://user-images.githubusercontent.com/259798/73447110-59c08f00-435e-11ea-8966-7d43965ef8fa.gif)

This issue does not happen with Firefox or Chrome for MAC (all latests). I initially had this issue working on a nextjs project, but it seems the same happens on the official website.

**To reproduce:**

Go to the 
1. https://emotion.sh

**Expected behavior:**

Persist styles ;)

**Environment information:**

- Ubuntu 18.04/Chrome 79
- Emotion 

- `react` version:

```
    "react": "16.12.0",
```

- `emotion` version:
```
    "@emotion/babel-preset-css-prop": "^10.0.27",
    "@emotion/core": "^10.0.27",
    "@emotion/styled": "^10.0.27",
    "babel-plugin-emotion": "^10.0.27",
    "emotion-theming": "^10.0.27",
```

**Comment by belgattitude** [comment]
Linked to #1746. Seems to be related to loom extension

**Comment by belgattitude** [comment]
loom extension bug. emotion rocks 😁

**Comment by vladinator1000** [comment]
This happens to me on the iOS and Android Instagram web view, as well as Android Firefox. How do you even debug this?
