### ISSUE TITLE
[v11] @emotion/native types are based on old react-native types.

### ISSUE THREAD

**Issue by Zn4rK** [emotion-js/emotion#1749]
**Current behavior:**

Both ActivityIndicatorIOS and WebView are included in the Pick from `@types/react-native@0.57.0`.
Both of which seems to be gone in the latest version of `@types/react-native@^0.61.10`

I'm getting:
`Type '"ActivityIndicatorIOS"' is not assignable to type '"ActivityIndicator" | "Button" | "DatePickerIOS" | "DrawerLayoutAndroid" | "FlatList" | "Image" | "ImageBackground" | "KeyboardAvoidingView" | "ListView" | "Modal" | "NavigatorIOS" | ... 147 more ... | "ViewPropTypes"'.`

**To reproduce:**

Compile TypeScript-project that uses the types and a newer version of react-native.

**Expected behavior:**

I would expect to be able to use the latest version of react-native (and @types/react-native).

**Environment information:**

- `react` version: n/a
- `emotion` version: `@emotion/native@11.0.0-next.11`

**Comment by Andarist** [comment]
Feel free to open a PR to fix this.

cc @patsissons , i guess there is really no way to support a wide range of RN versions, right? So we should just stick to supporting latest

**Comment by patsissons** [comment]
I think I just aligned with whatever was being used in the native package at the time.

**Comment by Andarist** [comment]
closed by https://github.com/emotion-js/emotion/pull/1750
