### ISSUE TITLE
jest-emotion: Type errors with @types/jest@^25.1.2

### ISSUE THREAD

**Issue by anilanar** [emotion-js/emotion#1753]
**Current behavior:**

`jest-emotion` breaks with `@types/jest@^25.1.2` because in the newer major version, `SnapshotSerializerPlugin` is different. In `@types/jest@^23`, `print` function is guaranteed to exist on type `SnapshotSerializerPlugin`. In the new version, it's not guaranteed. `@types/jest` imports it from `pretty-format`. In `pretty-format`, it's defined as follows:

```
declare type OldPlugin = {
    print: (val: any, print: Print, indent: Indent, options: PluginOptions, colors: Colors) => string;
    test: Test;
};
export declare type NewPlugin = {
    serialize: (val: any, config: Config, indentation: string, depth: number, refs: Refs, printer: Printer) => string;
    test: Test;
};
export declare type Plugin = NewPlugin | OldPlugin;
```

Thus, we get errors like:

```
node_modules/jest-emotion/types/index.d.ts:26:51 - error TS2339: Property 'print' does not exist on type 'Plugin'.

26 export const print: jest.SnapshotSerializerPlugin['print']
```

Notice that `yarn` did not hoist `@types/jest` to top level due to version mismatch and that's probably another issue to handle.

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by anilanar** [comment]
https://codesandbox.io/s/divine-currying-wu7pc

Right click `matchers`, click "Go to definition", see line 26 in `/sandbox/node_modules/jest-emotion/types/index.d.ts`.

![image](https://user-images.githubusercontent.com/753736/76689322-074ce080-6635-11ea-99c6-ee7a4bf5713d.png)

**Comment by Andarist** [comment]
For some I see old typings on that sandbox, however I've confirmed with their source files that they should look like what you have described. Given I have hard time confirming this myself - could you maybe replace the faulty line with:
```ts
export const print: Extract<jest.SnapshotSerializerPlugin, { print: any }>['print']
```
and confirm if it fixes the problem?

**Comment by anilanar** [comment]
https://github.com/anilanar/jest-emotion-typebug repro in repo.

Run `yarn tsc`.

And yes, that fixes the problem.

**Comment by Andarist** [comment]
Thank you for providing repros and checking this out! Should release a fix soon.
