### ISSUE TITLE
Cannot read property 'name' of null

### ISSUE THREAD

**Issue by vsolanogo** [emotion-js/emotion#1756]
ERROR #98123  WEBPACK appears when i apply css={ prop  to <E.Text>

import React from "react"
import { Link, graphql, StaticQuery } from "gatsby"
import styled from "@emotion/styled"
import Icons from "../shared/icons"
import { css } from "@emotion/core"

const E = {}

E.Wrapper = styled.div`
  border: 1px solid #d6d6d6;
  box-sizing: border-box;
  border-radius: 10px;
  padding: 32px 25px;
  max-width: 400px;
  margin-bottom: auto;
  @media (max-width: 1200px) {
    margin: auto;
  }
`

E.h4 = styled.h4`
  margin: 0;
  padding: 0;
  font-weight: 500;
  font-size: 35px;
  color: #333333;
  margin-bottom: 20px;
`

E.Benefits = styled.div`
  display: grid;
  grid-template-columns: 20px 1fr;
  row-gap: 14px;
  svg {
    margin-top: 6px;
  }
`

E.Text = styled.div`
  font-weight: 500;
  font-size: 14px;
  color: #333333;
`

export default function() {
  return (
    <E.Wrapper>
      <E.h4>Our Benefits 🎉</E.h4>
      <E.Text
        css={css`
          margin-bottom: 14px;
        `}
      >
        Available
      </E.Text>
    </E.Wrapper>
  )
}

**Comment by Andarist** [comment]
This is not an appropriate repro case. Please provide a **runnable** one. You must understand that we need to handle multiple issues, reports, etc and we just can't afford the time to setup repro cases on vague reports ourselves.

**Comment by Andarist** [comment]
Closing because a runnable repro case has not been provided so far.
