### ISSUE TITLE
@emotion/primitives and form inputs, is there a prop for html element name 

### ISSUE THREAD

**Issue by marcelmokos** [emotion-js/emotion#1764]
**Description:**

We are considering to use react native and we are already using emotion in our project. Our application has to use inputs, labels, and other HTML elements, and in the description on https://emotion.sh/docs/@emotion/primitives does not state anything about this use case. I suggest adding to the example codesandbox one functioning input and label.  

**Documentation links:**

https://emotion.sh/docs/@emotion/primitives

**Comment by Andarist** [comment]
I actually have no experience with `react-primitives` and I have no idea how you should implement an input using it. It's really more of a `react-primitives` question rather than `emotion` one.

**Comment by marcelmokos** [comment]
I see in the readme of react-primitives `In the future, a TextInput component may also be added.`

**Comment by Andarist** [comment]
So in the future, we might extend supported primitives with `TextInput`, once they add it 😉

**Comment by Andarist** [comment]
Closing this as we can't currently do much about this. `react-primitives` would have to implement this first.
