### ISSUE TITLE
Pass props to a css

### ISSUE THREAD

**Issue by sptGabriel** [emotion-js/emotion#1765]
Hello I am trying to do the following:

 ```
const flexCenter = props => css`
  display: flex;
  justify-content: ${({ justify }) => justify};
  align-items: ${({ align }) => align};
  flex-direction: ${({ direction }) => direction};
`;
export const Content = styled.div`
  ${mxw80};
  ${flexCenter}
`;
```

and my comp:

```
    <Container>
      <Content
        theme={Theme}
        justify={'center'}
        align={'center'}
        flex-direction={'column'}
      >
        a a
      </Content>
    </Container>
```

but it doesn't work

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given (which in here they are not).

**Comment by Andarist** [comment]
Closing because we haven't received a repro case for this.
