### ISSUE TITLE
Using Gatsby and components as selectors

### ISSUE THREAD

**Issue by falconmick** [emotion-js/emotion#1766]
Hi All

I have `@emotion/core`, `@emotion/styled`, `gatsby-plugin-emotion` all installed aswell as `gatsby-plugin-emotion` setup inside my plugins folder.

Why can't I use Components as selectors like you normally can with the babel plugin, see example:

![image](https://user-images.githubusercontent.com/713449/74669973-32cdde00-51e3-11ea-9822-fd23c5fb8594.png)

This causes the following error:

![image](https://user-images.githubusercontent.com/713449/74670003-3e210980-51e3-11ea-91f0-d0782344ca72.png)

When i remove the components as selectors the error goes away

**Comment by falconmick** [comment]
Also finding that the css prop doesnt work.. Is there any info on supported/unsupported features for gatsby?

**Comment by Andarist** [comment]
Everything should be supported. Could you share a sample repository with the issue reproduced?

**Comment by falconmick** [comment]
I will do later this evening, there is a good chance that it was a case of the “1am and things don’t work” kinda issues

**Comment by falconmick** [comment]
I've added you to https://github.com/falconmick/emons-world private currently because there are some assets that need to be properly watermarked before it can be made public. Heres the code that causes the issue: https://github.com/falconmick/emons-world/blob/master/src/pages/index.js#L20

**Comment by Andarist** [comment]
You have changed your code since the report. Please provide clear instructions on how to run repro case in a reliable manner in the future.

I've just added:
```
  ${PortraitGroup} {
    flex: 1;
  }
```
to your `GalleryWrapper` and I can't repro your issue. This component is correctly targeted in css:
<img width="255" alt="Screenshot 2020-02-18 at 23 34 12" src="https://user-images.githubusercontent.com/9800850/74783986-332fad00-52a7-11ea-8fc3-57244c8fc48f.png">

**Comment by falconmick** [comment]
Hi sorry about that, was a bad link. If you check the project out again and reset hard to ‘4a2a654’ you should see the following in that index.js page

```
   ${PortraitGroup}, ${GalleryImage} {
      flex: 1;
   }
```

**Comment by Andarist** [comment]
Well, this happens because your second component - `GalleryImage` - is not a styled component. You can't target arbitrary components as selectors, only the ones created with `styled`

**Comment by falconmick** [comment]
Cheers for that!

Maybe if I can find the time I’ll try to make a PR with better error
message. Is that even possible?

**Comment by Andarist** [comment]
Its hard to give a better one because interpolating a function (and your component is a function) is a valid use case. But sure - if you have any idea on how this could be improved, let me know.
