### ISSUE TITLE
TypeScript error when component renders a styled component

### ISSUE THREAD

**Issue by criles25** [emotion-js/emotion#1770]
**Current behavior:**
I'm using `styled` to create a button. In my implementation, my button is a function component that returns a styled component.

TypeScript throws an error when I use it.

**To reproduce:**
My button implementation
```
// Button.tsx

type Size = "small" | "medium" | "large";

type ButtonProps = {
  size?: Size;
  kind?:
    | "primary"
    | "text-primary"
    | "cta"
    | "gray"
    | "danger"
    | "danger-neutral"
    | "warning";
  link?: boolean;
};

const ButtonStyled = styled.button`
/* styles */
`
const Button = (props: ButtonProps) => <ButtonStyled {...props} />

export default Button;
```

```
import Button from 'Button.tsx';

// tsx does not complain
<Button size='small'></Button>
// tsx does not complain
<Button>foo</Button>
// tsx complains
<Button size='small'>foo</Button>
```

```
Type '{ children: string; size: "small"; }' is not assignable to type 'IntrinsicAttributes & Pick<Pick<ButtonProps, "size" | "link" | "kind"> & Pick<InferProps<{ size: Requireable<string>; kind: Requireable<string>; link: Requireable<...>; }>, never> & Pick<...>, never> & Partial<...> & Partial<...>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & Pick<Pick<ButtonProps, "size" | "link" | "kind"> & Pick<InferProps<{ size: Requireable<string>; kind: Requireable<string>; link: Requireable<...>; }>, never> & Pick<...>, never> & Partial<...> & Partial<...>'
```

- `react` version: 16.12.0
- `emotion` version: 10.0.27

**Comment by Andarist** [comment]
Try this:
```ts
const Button: React.FC<ButtonProps> = (props) => <ButtonStyled {...props} />

```

**Comment by criles25** [comment]
I tried ^.

Now I get this when I try to pass an `onClick` prop.

```
<Button onClick={onClick} kind={kind}>foo</Button>
```

```
Type '{ children: string; onClick: () => void; kind: "primary" | "text-primary" | "cta" | "gray" | "danger" | "danger-neutral" | "warning"; }' is not assignable to type 'IntrinsicAttributes & ButtonProps & { children?: ReactNode; }'.
  Property 'onClick' does not exist on type 'IntrinsicAttributes & ButtonProps & { children?: ReactNode; }'.
```

**Comment by jonavila** [comment]
@criles25 React types exposes `ComponentProps` type. It will extract the types of a component, so no need to manually add HTMLProps. I would try:

```
const Button: React.FC<ButtonProps & React.ComponentProps<'button'>> = (props) => <ButtonStyled {...props} />
```

**Comment by criles25** [comment]
I'm going to close this issue. Thanks for your help, ^ solved my problem.

**Comment by Gil3co** [comment]
Is there a more basic solution to all of this? Instead of doing this for each and every component with children? Happens to me with other components than button

**Comment by Gil3co** [comment]
Is there a more basic solution to all of this? Instead of doing this for each and every component with children? Happens to me with other components than button

**Comment by srmagura** [comment]
@Gil3co I don't think so. The `Props` interface in `React.FC<Props>` needs to reflect all of the props that the component accepts, so you need to use `extends` or `&` with the props type of the underlying component/element.

**Comment by Gil3co** [comment]
That's really weird. I've used the same idea of `styled` from MUI before, and have never encountered anything like this

**Comment by srmagura** [comment]
Can you show us an example of how it works with MUI?

**Comment by Gil3co** [comment]
Basically the same. You import `styled` from `@mui/material/styles`, and wrap it like this:

const StyledButton = styled(Button)`
color: red;
`
There are backtics after `(Button)` and after `color:red;` (The formatting changes it)

**Comment by srmagura** [comment]
This issue is for the case when you have a component that renders `StyledButton`:

```tsx
const MyComponent = (props) => <StyledButton {...props} />
```

So it's a bit different than the code you have shown.

**Comment by Gil3co** [comment]
Oh I'm sorry, I just got the exact same error when I tried to pass children, i.e. the text the button should show, to the styled button. Is there anything you can suggest I'd do?

**Comment by srmagura** [comment]
@Gil3co Can you create a new GitHub discussion with a runnable example that shows the problem? You can use our [CodeSandbox template](https://codesandbox.io/s/emotion-issue-template-y306ue).

**Comment by Gil3co** [comment]
@srmagura Created one, thanks!
https://github.com/emotion-js/emotion/issues/2807
