### ISSUE TITLE
Apply element style to children when hovering over parent element

### ISSUE THREAD

**Issue by arhoy** [emotion-js/emotion#1771]
Hello, I am trying to make this work in css in js using @emotion styled.

Not sure why this is not working. Where Animate is inside SubContainer.
```
const Animate = styled.span``;
const SubContainer = styled.div`
  &:hover {
    ${Animate} {
      text-decoration: underline;
    }
  }
`;

```

Something similar like this is what I am after

https://stackoverflow.com/questions/4502633/how-to-affect-other-elements-when-one-element-is-hovered

Thank you!

**Comment by Andarist** [comment]
Please share a runnable repro case. We can't quite tell why this is not working just from the code snippet you have provided.

**Comment by arhoy** [comment]
OK is that the correct syntax though?

**Comment by Andarist** [comment]
At first glance, it looks OK.

**Comment by arhoy** [comment]
I see. Okay I understand my issue now. It works if it is an immediate child but if it is nested deeper it will not work. Is there a way to work around that, or should that still theoretically work?

**Comment by arhoy** [comment]
It looks like I just need to brush my css up haha. It works perfectly

**Comment by AbhisekGIT** [comment]
@arhoy Can you please post the code that worked for you?

I get the following error in ${Animate}

`[ERROR] Expected "}" but found "{"`
