### ISSUE TITLE
Kebab keys for object styles

### ISSUE THREAD

**Issue by steida** [emotion-js/emotion#1774]
Kebab keys for object styles, WDYT? I can implement it.

**Comment by Andarist** [comment]
We dont want to implement too many features in this library - camelCase match browser APIs, other css-in-js implementations and has good strict coverage in TS types provided by csstype package

**Comment by steida** [comment]
Match browser API? May I know how? CSS is kebab-case. But I understand the other arguments. Thank you for your answer.

**Comment by Andarist** [comment]
CSS itself is kebab-case - yes, but CSS represented in JS - not so much. `CSSStyleDeclaration` API has camelCased properties - this the one which you get if you for example check `.style` property of any node.
