### ISSUE TITLE
emotion-theming@11.0.0-next.6 package missing source/types

### ISSUE THREAD

**Issue by tpict** [emotion-js/emotion#1776]
Just a minor packaging issue, I think. It seems that when the `@emotion/core` imports were changed to `@emotion/react`, we lost the source and type declarations from the NPM package. Thanks!

**Comment by Andarist** [comment]
`emotion-theming` got moved into `@emotion/react`, so it "no longer exists" - the published version is deprecated.

You can just import `useTheme`, `ThemeProvider` and `withTheme` from the `@emotion/react` itself.

**Comment by tpict** [comment]
My mistake, thanks!
