### ISSUE TITLE
Alternative api to classnames component

### ISSUE THREAD

**Issue by zmitry** [emotion-js/emotion#1777]
**The problem**

Classnames(component) api at this moment is not super useful and I guess it can be improved and simplified. 

**Proposed solution**

I suggest to replace Classnames (component) api with solution similar in https://cssinjs.org/react-jss.
So the idea is next 
```
const useStyles = createUseStyles({
  myButton: {
    color: 'green',
    margin: '20px',
  },
 label: css`background: red`
})
function MyButton() {
 const styles = useStyles()
return <div className={styles.myButton}>
<span className={styles.label} >
 hello
</span>
</div>
}

```

**Alternative solutions**

alternative solution might be inlining useStyles with no createUseStyles

```
function MyButton() {
 const styles = useStyles({
  myButton: {
    color: 'green',
    margin: '20px',
  },
 label: css`background: red`
})
return <div className={styles.myButton}>
<span className={styles.label} >
 hello
</span>
</div>
}
```
What do you think? One issue with it doesn't work with zero-ssr approach (which I don't quite like) but I guess we can have one more hook with classnames object and style component which you will have to render somewhere in case you want to use zero ssr approach
```
function createUseStylesSSR():[classnames, styleObject]
```

**Comment by Andarist** [comment]
We care about the zero-ssr approach and thus your proposals are not a good fit for us. I personally don't quite like the current API (but I understand why it is what it is) so I'm thinking about how it could be improved on a regular basis~ but haven't yet figured it out.
