### ISSUE TITLE
Difference between `cx` and `css`

### ISSUE THREAD

**Issue by jancellor** [emotion-js/emotion#1778]
**Description:**

This regards the framework-agnostic `emotion` package. It appears to me, a new user, that `cx` does not do anything `css` already does. I am confused as to why I would need `cx`. For example:

```
let red = css({color: "red"});
let blue = css({color: "blue"});
let cxRedBlue = cx(red, blue);
let cxBlueRed = cx(blue, red);
let cssRedBlue = css(red, blue);
let cssBlueRed = css(blue, red);
document.body.appendChild(h("p", {className: cxRedBlue}, "cxRedBlue"));
document.body.appendChild(h("p", {className: cxBlueRed}, "cxBlueRed"));
document.body.appendChild(h("p", {className: cssRedBlue}, "cssRedBlue"));
document.body.appendChild(h("p", {className: cssBlueRed}, "cssBlueRed"));
```

In both cases, the second color overrides the first. In both cases, the result of the combination is a single class consisting of both rules rather than a space-separated string of multiple classes (which is what I would expect from a performance perspective, at least when it is possible for emotion to ensure the individual classes were defined in the right order). The generated classes are the same, at least in dev mode. In prod mode I believe the `stylesheet.insertRule` API is used making it harder for me to tell what's going on.

**Documentation links:**

Documentation is on [npm](https://www.npmjs.com/package/emotion) and [emotion.sh](https://emotion.sh/docs/emotion).

**Comment by Andarist** [comment]
`cx` resolves things like:
```
cx(
  { [cls1]: foo },
  { [cls2]: bar }
)
```
which `css` can't do.

**Comment by Andarist** [comment]
Closing as I got no feedback about my clarification in the past 2 weeks.

**Comment by jancellor** [comment]
Sorry I forgot to comment. I was half expecting someone to point out a more fundamental difference. `css` can do
```
css([foo && cls1, bar && cls2])
```
The one thing I can see is that `css` cannot combine non-emotion classes where `cx` can. If this is the case, maybe that should be stressed. It's easy to see that `css` combines classes like `cx` then ignore it. There are no examples of `css` doing that here unlike in the React versions of the docs. Anyway, no problem with this being closed from me.
