### ISSUE TITLE
Global styles prop does not reveice the theme object as of @emotion/core 10.0.28

### ISSUE THREAD

**Issue by matchatype** [emotion-js/emotion#1780]
I'm using `Global` from `@emotion/core` to inject some global styles in a gatsby site with `theme-ui`. 

```jsx
// /components/layout.js

...
return (
  <Fragment>
    <Global styles={globalStyles} />
    {children}
  </Fragment>
)
...
```

```js
// /styles/global-styles.js

export default theme => ({
  html: {
    ...
  }
})
```

Until v10.0.27 everything worked just fine. As of 10.0.28, the `styles` prop passes as theme an empty object, which causes the app to crash.

**Current behavior:**

```js
// /styles/global-styles.js

export default theme => console.log('theme >>>', theme) || ({
  html: {
    ...
  }

// => theme >>> {}
})
```

- `react` version: 16.13.0
- `emotion` version: 10.0.28

**Comment by Andarist** [comment]
Most likely you have multiple copies of `@emotion/core` in your `node_modules`.

**Comment by matchatype** [comment]
My bad, that's correct. Thanks @Andarist  🙏
