### ISSUE TITLE
border radius with @emotion/native gives a jagged edge on android

### ISSUE THREAD

**Issue by codecog** [emotion-js/emotion#1782]
**Current behavior:**
Using border radius on android gives a jagged edge.

**To reproduce:**
Use border radius > 15px

**Expected behavior:**
A smooth edge should be shown, the same code shows a smooth circle in styled-components v5

**Environment information:**
latest version of react, react native & emotion/native

**Comment by Andarist** [comment]
I'm afraid that we do not have time to fix this, but we would be more than happy to accept a PR for this.

**Comment by nikoloza** [comment]
I'm guessing it's referred to React native itself and should not be an emotion issue https://github.com/facebook/react-native/issues/17311

**Comment by Andarist** [comment]
Closing this as, like @nikoloza has noticed, this doesn't seem to be Emotion's issue.
