### ISSUE TITLE
Wrapping a input with a styled component has issues with onFocus/onBlur events  

### ISSUE THREAD

**Issue by Drakota** [emotion-js/emotion#1797]
**Current behavior:**
I tried wrapping a input with a styled component like this:
```javascript
 <Wrapper>
      <input
        type="text"
        onFocus={() => setIsFocused(true)}
        onBlur={() => setIsFocused(false)}
      />
      {isFocused && "test"}
</Wrapper>
```
I need to click twice on the input to focus and be able to write text.

**To reproduce:**

[Link to Sandbox](https://codesandbox.io/s/styled-div-focus-issue-edoc4)
1. Try to click on the input
2. You see the isFocused state is changed and displays Focused
3. Click again to gain control of the input and now you can start writing

**Expected behavior:**
The browser's default behavior (click once)

**Environment information:**

- `react` version: 16.12.0
-  `@emotion/core` version: "^10.0.28",
-  `@emotion/styled` version: "^10.0.27",

**Comment by Andarist** [comment]
You need to move out your Wrapper out of render. You are recreating a component's type each render and thus React loses the whole state (including focus) for it. Fixed sandbox: https://codesandbox.io/s/styled-div-focus-issue-ojd5r

It's basically like if you would do smth like this:
```js
function Comp() {
  const Another = () => <input/>
  return <Another/>
}
```
Which is an anti-pattern because React won't even be able to know that `Another` is the same component between renders.

**Comment by Drakota** [comment]
Ah... I see! Thank you very much 😄

**Comment by milenaNeumann** [comment]
I just ran into a similar problem. You can also solve it with `useMemo` (see [this CodeSandBox](https://codesandbox.io/s/styled-div-focus-issue-forked-m5hbe)).

This approach pairs particularly well when using the `useTheme` hook:

```  
const Wrapper = useMemo(
    () => styled.div`
      padding: 10px;
      background: ${theme.color.primary};
    `,
    [theme]
  );
```

**Comment by Andarist** [comment]
In the majority of applications - you really should not do it. Just declare your components outside of the render functions.

**Comment by milenaNeumann** [comment]
what makes you say that? I'd like to understand why. Declaring the the components in the render functions results in much cleaner code in our project. Is it a performance concern?

**Comment by JaredMichel** [comment]
> In the majority of applications - you really should not do it. Just declare your components outside of the render functions.

This isn't really an option if the styles you specify are dynamic

**Comment by JaredMichel** [comment]
For people in the future that are confused like I was for making this work for dynamic styles, here is a working example:

https://github.com/Mipke/pyramid/blob/ecabf4411bb14579a9df85f20e5b78e31e3578ca/src/components/Spacer/index.tsx

**Comment by Andarist** [comment]
> what makes you say that? I'd like to understand why. Declaring the components in the render functions results in much cleaner code in our project. Is it a performance concern?

Yes, it's a performance concern and not because of Emotion but because of React. By declaring components in render you force them to **remount** which each rerender as React won't be available to reconcile them.

**Comment by milenaNeumann** [comment]
Thanks for clearing that up!
