### ISSUE TITLE
Allow props to be passed in shouldForwardProp

### ISSUE THREAD

**Issue by alexandrzavalii** [emotion-js/emotion#1798]
**The problem**

I need to allow my custom prop to be passed, and there is no such functionality right now.

**Proposed solution**
```
const createShouldForwardProp = function createShouldForwardProp(props, allowedProps) {
  var regex = new RegExp("^(" + props.join('|') + ")$");
  return memoize(function (prop) {
    return (isPropValid(prop) && !regex.test(prop)) || allowedProps.includes(prop)
  });
};

const shouldForwardProp = createShouldForwardProp(props,['tag'])
```

My current use case is this component
```
import { jsx } from '@emotion/core';

const Comp =  ({ tag, children, ...otherProps }) => {
  return jsx(tag, { ...otherProps }, children)
}

const Text = styled(Comp,  {shouldForwardProp})(
  compose(space, layout, typography, variantStyle),
);
```

I need to make sure that `tag` is passed down to `Comp` because I am creating the component using `jsx`

**Comment by Andarist** [comment]
I don't quite see why you can't just do this:
```js
const Text = styled(
  Comp, 
  {
    shouldForwardProp: prop => isPropValid(prop) || prop === 'tag'
  }
)(
  compose(space, layout, typography, variantStyle),
);
```

Could you explain the difference?

**Comment by alexandrzavalii** [comment]
@Andarist Thanks for your help!
would I sacrifice on performance avoiding memoize function?

**Comment by Andarist** [comment]
Not much, `isPropValid` is already memoized and I wouldnt consider memoizing such a short wrapper worthwhile.

**Comment by alexandrzavalii** [comment]
Okay I guess we can close it off, I might just create a memoized function locally
Thanks!
