### ISSUE TITLE
Emotion styled breaks transitions in nested components

### ISSUE THREAD

**Issue by iwatakeshi** [emotion-js/emotion#1799]
**Current behavior:**

I'm using emotion-theming to provide a theme to all my components. However, when I use `@emotion/styled` component and add a child that does some transitions, the transitions do not appear to work correctly. I'm not sure what the exact issue is but hopefully the reproducible can help.

**To reproduce:**

*CodeSandbox*:  https://codesandbox.io/s/next-typescript-app-r4doi

1. Use ThemeProvider
2. Create a component using `@emotion/styled` (in my case it was `styled.nav`)
3. Add a component that uses transitions and transformations (in my case it was a burger menu)

**Expected behavior:**

As shown in the reproducible, the top burger menu should replicate the transitions like the burger menu at the bottom.

**Environment information:**

- `react` version: 16.13.0
- `emotion` version: 
```json
{
  "emotion": "10.0.27",
  "emotion-theming": "10.0.27",
}
```

**Comment by Andarist** [comment]
[This](https://github.com/emotion-js/emotion/issues/1797#issuecomment-597478132), but about your `NavBar` 😉

**Comment by iwatakeshi** [comment]
@Andarist You, are awesome. Thanks!
