### ISSUE TITLE
Inserted identifier clashes with existing one

### ISSUE THREAD

**Issue by Andarist** [emotion-js/emotion#1818]
Originally reported by @zslabs in https://github.com/emotion-js/emotion/issues/1751, but I've managed to slim it down to a minimal repro. The key to reproduce the error is to crawl the scope before our plugin.

I don't intend to fix this right away as it might not be trivial **and** the issue also happens with Babel's core plugins (tested on the newly introduced automatic mode of React's preset). I've reported it over there to see how it plays out, hopefully we'll benefit here from their fix 🤞 Reporting the issue in here right now, just so it doesn't get lost.

```js
require('@babel/core').transform(`

import _css from "@emotion/css";

const Header = () => {
  var _css2;

  return _css((_css2 = {}, _css2[Math.random()] = {color: 'hotpink'}, _css2))
};

export default Header;

`, {
  plugins: [
    [api => ({ visitor: { Program(p) { p.scope.crawl() } } })],
    'babel-plugin-emotion'
  ]
}).code
```

**Comment by zslabs** [comment]
Thanks for creating this @Andarist! Do you have a link handy to the Babel issue you created?

**Comment by Andarist** [comment]
The fix has landed in Babel and should be available in its next release: https://github.com/babel/babel/pull/11323#pullrequestreview-380388294

**Comment by zslabs** [comment]
Thank you very much @Andarist for going down the rabbit-hole with this one! 🙌
