### ISSUE TITLE
EmotionCssPropInternal instances duplicate props with identical propnames

### ISSUE THREAD

**Issue by seanmhanson** [emotion-js/emotion#1819]
### The Problem

Currently, in our testing environment and framework (node, enzyme), styled components or components provided css using emotion render internal components that wrap the expected output, and duplicate all props provided to the intended component.

Polluting the props namespace for the component is less than ideal, but could be ignored. However, this unfortunately has the high visibility problem of duplicating fields like `data-testid` that are used across our teams as the basis of all selectors in testing, resulting in two results instead of one.

This is quite common for us, as we use `data-testid` across different teams/divisions. For example, here's an instance where we provide emotion styles to our `Button` component, using the `css` prop:

#### JSX
```
<Button
  size="xsmall"
  variant="primary"
  data-testid="add-archive-button"
  css={controlButton}
>
  Add Active
</Button>
```

#### Output
```
<EmotionCssPropInternal
  size="xsmall"
  variant="primary"
  data-testid="add-archive-button"
  css={{...}}
  __EMOTION_TYPE_PLEASE_DO_NOT_USE__={[Function: x]} 
  __EMOTION_LABEL_PLEASE_DO_NOT_USE__="ParentComponentName"
>
  <Button
    size="xsmall" 
    variant="primary"
    data-testid="add-archive-button"
    className="css-tonir0-controlButton"
  >
    <button
      type="button"
      className="css-tonir0-controlButton leafygreen-ui-n2zrya"
      disabled={false}
      aria-disabled={false}
    >
      Add Archive
    </button>
  </Button>
</EmotionCssPropInternal>
```

As a result, there are two matches for a selector like `[data-testid="add-archive-button"]` when there should be only one.

### Proposed solution

I would propose a namespaced prefix be added to all the names of all props when appended to `EmotionCssPropInternal`, that would then be removed when passing the prop to the child it is wrapping.  

For example, the output might change to look something like the example below. Note that I do not know how Emotion handles the `css` prop, so I've prefixed it in the example but it should be handled however you deem it prudent.

```
<EmotionCssPropInternal
  __emotion__size="xsmall"
  __emotion__variant="primary"
  __emotion__data-testid="add-archive-button"
  __emotion__css={{...}}
  __EMOTION_TYPE_PLEASE_DO_NOT_USE__={[Function: x]} 
  __EMOTION_LABEL_PLEASE_DO_NOT_USE__="ParentComponentName"
>
```

Doing so eliminates any duplicated prop names, and therefore helps prevent selecting emotion internal components as a result. If this solution is approved, I might be able to contribute a PR for the changeset, since I'm in isolation due to COVID-19 😅😅😓 

### Alternative solutions

I do not know enough about the implementation of Emotion and React to speak definitively to this, but if possible, suppressing `EmotionCssPropInternal` from output to the VDOM or other equivalent. This strikes me as much more difficult, and I don't have the knowledge to tell if this is even relevant.

As our current workaround, we face three main approaches, each resulting in brittle and/or overly verbose tests:
- append an element tag any selectors, or otherwise increase specificity significantly
- query for a parent or child, then traverse the DOM/VDOM/etc
- filter all relevant queries every time, using enzyme's mount api

These are workarounds, but do not address the fact that the namespace of props for a given component is being polluted. 

### Additional context

Some Relevant (and likely some irrelevant) Dependencies:

```
// dependencies
"@emotion/core": "10.0.28",
"@emotion/styled": "10.0.27",
"emotion": "10.0.27",
"react": "16.8.6",
"react-dom": "16.8.6",
```

```
// dev-dependencies
"@emotion/babel-preset-css-prop": "10.0.27",
"enzyme": "3.11.0",
"enzyme-adapter-react-16": "1.15.2",
"mocha": "7.0.0",
"react-test-renderer": "16.8.6",
```

**Comment by Andarist** [comment]
Thanks for the report - I will try to think about it. I've actually tried to "fix" this but it broke integration with Enzyme's shallow rendering, need to give this more thought.

**Comment by Andarist** [comment]
After some thinking - it’s not worth fixing from our perspective, especially given that a potential fix would break `React.cloneElement` on those components. You should be able to target your desired component using different selectors/matchers that are not so implementation-specific (after all your user doesnt care what props are used for what elements so tests around that tend to be more brittle)
