### ISSUE TITLE
Don't drop defaultProps of wrapped component

### ISSUE THREAD

**Issue by stefanprobst** [emotion-js/emotion#1821]
**Current behavior:**

Emotion loses the `defaultProps` of a wrapped styled component.

**To reproduce:**

See: https://codesandbox.io/s/emotion-issue-template-k7fkx

```js
const RedColor = styled.div`
  color: ${props => props.color};
`;
RedColor.defaultProps = { color: "red" };

const BlueBackgroundRedColor = styled(RedColor)`
  background: ${props => props.background};
`;
BlueBackgroundRedColor.defaultProps = { background: "blue" };
```

renders `BlueBackgroundRedColor` like this:

![defaultprops-emotion](https://user-images.githubusercontent.com/20753323/77519545-fc3d5000-6e7f-11ea-8faf-dc0ebbf28892.png)

note: `styled-components` renders the same example like this:

![defaultprops-styledcomponents](https://user-images.githubusercontent.com/20753323/77519486-e039ae80-6e7f-11ea-824c-eb257d221dea.png)

**Expected behavior:**

`defaultProps` should not be dropped. behavior should match `styled-component`'s

**Environment information:**

- `react` version: 16.13.1
- `emotion` version: 10.0.27 and 11.0.0-next.12

**Comment by Andarist** [comment]
I'm afraid that we don't intend to change this behavior. There is a high chance of `defaultProps` being removed from React in the future and thus we don't want to handle their quirks one our side.

The preferred way to handle this is to just use the language™:
```js
const RedColor = styled.div`
  color: ${({ color = 'red' }) => color};
`;

const BlueBackgroundRedColor = styled(RedColor)`
  background: ${({ background = 'blue' }) => background};
`;
```
