### ISSUE TITLE
Emotion 11 + Typescript: theme is "any" when wrapping components with styled

### ISSUE THREAD

**Issue by Kadrian** [emotion-js/emotion#1822]
**Current behavior:**

When using `styled` with an existing component, the `theme` prop has `any` type.

I'm augmenting the theme as described here, https://deploy-preview-1600--emotion.netlify.com/docs/typescript#define-a-theme

![Bildschirmfoto 2020-03-26 um 18 23 43](https://user-images.githubusercontent.com/1403093/77679652-25023a00-6f93-11ea-9ded-f62afa5a1e7f.png)

**To reproduce:**

- Go to: https://codesandbox.io/s/friendly-agnesi-ufbpb
- In `X` Hover over `color`, see that it's properly typed
- In `Y` Hover over `color`, see that it's `any`

**Expected behavior:**

The theme prop should be defined no matter what I'm wrapping with `styled()`

**Environment information:**

- `react` version: `16.13.1`
- `emotion` version: `11.0.0-next.12`

**Comment by Andarist** [comment]
I can't quite repro what you are observing, but I had a slightly different problem - that TS did not recognize the Theme being augmented with your types. I've fixed it by adding an additional import statement to:
```js
import "@emotion/react";

declare module "@emotion/react" {
  export interface Theme {
    color: {
      blue: string;
    };
  }
}
```

Could you check if this helps you?

**Comment by Kadrian** [comment]
Ah, well! Yes, that fixes it. And that's already mentioned in the docs. Missed it :-)

**Comment by dreampulse** [comment]
This doesn't work in the latest version anymore :-(

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.
