### ISSUE TITLE
Excessively deep types with Typescript and styled inheritance

### ISSUE THREAD

**Issue by jsonmaur** [emotion-js/emotion#1823]
**Current behavior:**

When you use styled component inheritance down ~4 levels, Typescript will throw the error `Type instantiation is excessively deep and possibly infinite.`. Have tried to do some research on that error, and it seems TS limits type chains that are excessively large and take a long time to compile (see [here](https://github.com/microsoft/TypeScript/issues/34933)).

The question is: why are emotion styled component types compounding on each inheritance? Is there a way to simplify the types so it doesn't hit this limit?

Maybe there is a better way to handle inheritance, and if so, feel free to point me in the right direction. If so, it should be noted in the docs that this is an issue.

**To reproduce:**

https://codesandbox.io/s/emotion-issue-1823-g8k6z

```jsx
import styled from "@emotion/styled";

const A = styled("h1")();
const B = styled(A)();
const C = styled(B)();
const D = styled(C)();
const E = styled(D)(); // Type instantiation is excessively deep and possibly infinite.

function App() {
  return <E>Hello CodeSandbox</E>;
}
```

**Expected behavior:**

Should be able to create styled components inheriting from other components more than 4 levels deep, or outline a better solution in the documentation.

**Environment information:**

- `react` version: 16.12.0
- `@emotion/core` version: 10.0.28
- `@emotion/styled` version: 10.0.27
- `typescript` version: 3.7.5

**Comment by Andarist** [comment]
I'm afraid that we are just unable to fix this in v10 at this point in time. The good news is that this doesn't happen with reworked types in the upcoming v11: https://codesandbox.io/s/emotion-issue-1823-ikj8z . We hope to ship it in the following weeks.

**Comment by jsonmaur** [comment]
@Andarist Great, looking forward to the new release. Thanks for responding so quickly.
