### ISSUE TITLE
v11 - Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by MMT-LD** [emotion-js/emotion#1826]
Hey,

So, i have been playing around with the new v11 in an existing design system that used the v10 syntax which  just seemed to work. However, in V11 emotion/react and styled is now implemented with nothing else changing. Previously, i never had to use the CacheProvider. However, i have upgraded from v10 to v11 (next) version and now when i try to get it to work in CRA (just importing my components from the package, say Button), for example, now results in this error....

```
TypeError: Cannot read property 'key' of undefined
createCache
node_modules/@emotion/cache/dist/cache.browser.esm.js:83
  80 | var movedStyles = false;
  81 | 
  82 | var createCache = function createCache(options) {
> 83 |   var key = options.key;
  84 |   var stylisOptions;
  85 | 
  86 |   if (!key) {
View compiled
```

I appreciate the is a newer version with little documentation, however i'm wandering what, a) i'm doing wrong b) is createCache now a default requirement or something... as i noticed that key is now required, and Nextjs _app.js now includes the< CacheProvider> component, where it was not required previously...

If this is not suited for here please close...

**Comment by Andarist** [comment]
I strongly suspect that you have mixed versions of `@emotion` packages - loos like you might have new `@emotion/cache` but slightly older `@emotion/react` (or `@emotion/css`).

> and Nextjs _app.js now includes the< CacheProvider> component, where it was not required previously...

Custom cache is not a requirement, everything should work without it.

**Comment by MMT-LD** [comment]
well, well, well... It would seem that another package was using v10 in its dependencies. So yes your correct, this was the issue. I must admit though i'm still unclear of why i need (potentially) to use cacheProvider, this was something i struggled to understand from the beginning of time (v9). 

By the way, i know how difficult it can be to work on something, normally in your spare time. Just want to say i appreciate all your efforts relating to this lib. 👏 👏

**Comment by MMT-LD** [comment]
FYI, rather then using "next" in package.json i added:
```
"@emotion/react": "^11.0.0-next.11",
"@emotion/styled": "^11.0.0-next.11"
```

this seemed to fix the above issue

**Comment by Andarist** [comment]
> I must admit though i'm still unclear of why i need (potentially) to use cacheProvider, this was something i struggled to understand from the beginning of time (v9).

It's useful only when you need advanced customization over style insertion or style generation, you can customize things like the key prefix for generated classes, stylis (parser) plugins, a node to which styles should be inserted (you can, for example, target iframe) and similar. Just look at those options - https://github.com/emotion-js/emotion/blob/master/packages/cache/README.md#options

> I vaguely remember when next js just worked with emotion with no other setup, i just imported my ThemeProvider. However, correct me if i'm wrong but _app.js and document have been added recently. I guess, judging by my experiment this is now required for a library previously using emotion?

Not really, I'm suspect that the CacheProvider was added there (keep in mind that we do not take care of the next integration - it lives in their repo) so people don't get warnings about using "unsafe selectors" (such as `:first-child`). Those exist for a reason though (especially when using something like next with SSR) so I'm not sure if that is a good default. 

> this seemed to fix the above issue - in CRA

Could you try upgrading to `*-next.12`?

**Comment by Andarist** [comment]
Closing because it got stale and there are no followup actions we could take here.
