### ISSUE TITLE
Calling withComponent on styled component loses base styling further down the chain

### ISSUE THREAD

**Issue by russx2** [emotion-js/emotion#1828]
**Current behavior:**

I create a JSX component which has a styled component as its top level element. The JSX component is wrapped in a `styled()` call. Calling `withComponent()` on this object changes the top level styled component's element correctly but loses the base styling.

**To reproduce:**

Example here: https://codesandbox.io/s/emotion-issue-template-g4jni

**Expected behavior:**

I would expect the styling to be preserved.

**Environment information:**

- `react` version: 16.12.0
- `emotion` version: 10.0.27

**Comment by Andarist** [comment]
This is expected - `styled` can only carry over styles from the component it knows and you call `withComponent` on the non-styled Heading. We just don't have a way to read any styles from it because it is just a function, nothing else from our perspective.

**Comment by Andarist** [comment]
Closing this as the answer has been given quite some time ago and I have not heard back from the OP since then.
