### ISSUE TITLE
[SUPPORT] Production build doesn't have prefixes

### ISSUE THREAD

**Issue by katalonne** [emotion-js/emotion#1831]
As I undestood by reading the docs and many previous issues, emotion comes with some sort of `autoprefixer` out of the box.

Prefixes are added in development mode, yet in production they are not.

I'm using react-scripts wepack config.

* Tried adding `CacheProvider`, still no changes.
* Tried all sorts of `browserslist`, still no changes.

- versions
`"@emotion/core": "^10.0.28"`
`"@emotion/styled": "^10.0.27"`

This issue can also be reproduced in `circuit-ui`:
https://github.com/sumup-oss/circuit-ui/blob/5fbe0111738933acc82d352ac9581af989c38b24/.storybook/preview.js#L40-L50

* Development mode `display: flex` is autoprefixed.
* Production mode is not.

------

Am I missing something?

Any help would be highly appreciated.

**Comment by Andarist** [comment]
Prefixer is applied regardless of the environment and it's a default - to disable it you must configure the cache to disable it explicitly.

Hard to tell what's going wrong for you without seeing the issue reproduced. Could you share the exact steps to reproduce this? I don't have much time to figure out the circuit-ui build setup myself and find the right section - it's obviously not hard, just taking some time which I would rather spend on more pressing issues.

**Comment by katalonne** [comment]
@Andarist 
* Does it check in the runtime if a css property needs autoprefix based on useragent (maybe)? 
* Or does it apply all the prefixes possible based on `browserslist` as `autoprefixer` does?

I see this issue (maybe feature) on the majority of websites listed in `README.MD`.
- How to reproduce:
* Find any `display: flex` property value. To be more precise go to `www.healthline.com` and find `css-lm0pdr` class (as of current build).
* It has no prefixes.

**Comment by Andarist** [comment]
> Does it check in the runtime if a css property needs autoprefix based on useragent (maybe)?

No, we are "over-prefixing". Supported properties are roughly [those](https://github.com/thysultan/stylis.js/blob/1cfdff820340f72f5a0bedce49a13d49011b6947/src/Prefixer.js) (although they are not 100% the same, it's the same parser - stylis - just I've linked to its v4 and we are still on v3. I've linked to v4 code as it's easier to see its supported properties).

> Find any display: flex property value. To be more precise go to www.healthline.com and find css-lm0pdr class (as of current build).

This is not a repro case, it's already built and minified site with a potentially very custom setup. I've tried to look into its minified source for a brief moment and it seems that it doesn't have the prefixer in it (or at least doesn't have some parts of it). It also contains es6+ code in place of what should be es5, so it definitely involves some custom build setup.

A repro case is something I can inspect from its source code to the final build artifacts - I can't do that here.

**Comment by katalonne** [comment]
Hmm... Thanks for the answer. Maybe I will reopen the issue later.
I think it is minifier related, I will dig deeper...

**Comment by kpdecker** [comment]
Chiming in as the owner of healthine.com :)

We have disable the bulk of our prefixing functionality to target our specific browser support matrix (as well as a modern js and legacy js build target thus the es6). Lack of prefixes was very purposeful to reduce the generated code size.

**Comment by bitbot-rafa** [comment]
Experiencing a similar issue. @katalonne, were you able to identify the source? :thinking:

**Comment by katalonne** [comment]
@bitbot-rafa It has to be the `browserslist`. It can also be already declared in your `package.json`
