### ISSUE TITLE
document for theming is incorrect?

### ISSUE THREAD

**Issue by thomaszdxsn** [emotion-js/emotion#1843]
**Description:**

![image](https://user-images.githubusercontent.com/23616426/79074023-8ad51c80-7d1c-11ea-8e45-d27182cfb292.png)

I dont understand this command for npm? what is -S option, can't find it in [NPM doc](https://docs.npmjs.com/cli-commands/install.html)

**Documentation links:**

https://emotion.sh/docs/theming

**Comment by thebuilder** [comment]
In older versions of NPM you needed to add `--save`(or `-S`) when running `npm install` before the dependency was added to the package.json. It's done by default now.

**Comment by Andarist** [comment]
If you feel like removing this flag from this installation instruction - feel free to open a PR for this.
