### ISSUE TITLE
Add Using with Stylelint section

### ISSUE THREAD

**Issue by ai** [emotion-js/emotion#185]
- `emotion` version: github

What you did:

Open [github.com/tkh44/emotion](https://github.com/tkh44/emotion)

What happened:

I saw great docs, but without docs how to add linter for CSS

Suggested solution:

Something similar to [styled-components docs](https://github.com/styled-components/stylelint-processor-styled-components)

**Comment by tkh44** [comment]
*I think* we could potentially do this during compile and put it behind a `lint` flag. @ai we are using postcss-js internally to compile the styles, do you think this could work?

**Comment by ai** [comment]
It is even better 😄

Using standard PostCSS parser instead of postcss-scss will be better, because you will be able to lint spaces. Is it possible to change parser?

**Comment by ai** [comment]
Maybe we can use [styled-components stylelint plugin](https://github.com/styled-components/stylelint-processor-styled-components)? I will check on next week.

**Comment by ai** [comment]
I tried styled-components stylelint plugin and everything works (it is compatible with Emotion as well)

**Comment by severen** [comment]
Is it compatible with *object styles* though?

**Comment by vhlongon** [comment]
@ai can you please show me your config? I am trying to make stylelint works with emotion, but no luck yet :|

**Comment by vhlongon** [comment]
@jhwohlgemuth dude, thanks a bunch!  Works like a charm now!

**Comment by gucong3000** [comment]
Related: #686

**Comment by ilias-t** [comment]
This issue issue should probably be reopened. There is currently no documentation on how to lint emotion.

**Comment by montezume** [comment]
With the latest version of stylelint it's pretty straightforward. What are you having trouble with? 

I have a [repo](https://github.com/montezume/stylelint-css-in-js) open with it setup. The `.stylelintrc` file is [here](https://github.com/montezume/stylelint-css-in-js/blob/master/.stylelintrc)

**Comment by nhooyr** [comment]
@montezume how does your stylelintrc work? It doesn't use the styled-components processor.

**Comment by montezume** [comment]
The styled-components processor isn't required anymore thanks to the native support for CSS in JS in stylelint.

I wrote a blog post about it if you want to [check it out](https://medium.com/swlh/keeping-your-css-in-js-clean-with-stylelint-8822c8c1543a)

What errors / problems are you having with stylelint and emotion? Are you running the latest version of stylelint?

**Comment by nhooyr** [comment]
Its currently broken when u have a babel config for some reason. There's an issue on the stylelint repo.
