### ISSUE TITLE
Nesting css tagged template literals vs strings

### ISSUE THREAD

**Issue by seaneking** [emotion-js/emotion#1855]
**Description:**

I'm trying to convert from CSS modules to Emotion, and the docs are pretty light on more advanced usage of the `css` tagged template literal. 

My particular use-case is conditional styles based on props. Should those conditions return nested `css` tagged templates, or just strings? 

Contrived examples:
 
```js
const button = css`
  background: blue;
  ${busy && css`
    pointer-events: none;
    background: grey;
   `}
`
```

```js
const button = css`
  background: blue;
  ${busy && `
    pointer-events: none;
    background: grey;
   `}
`
```

Both seem to work, but I'm not sure if there are ramifications for either. Are there best practices around this common pattern? Should I not be nesting this stuff at all and instead use some kind of composition pattern in Emotion I'm not aware of?

In general as a newcomer to Emotion I think the docs could use more guidance around the `css` prop + tagged template. I get that Emotion is flexible, but best practices are useful for someone just getting their head around it.

**Documentation links:**

- https://emotion.sh/docs/css-prop

**Comment by seaneking** [comment]
Nevermind, passing arrays with conditional items to the `css` prop works better for my usecase. 

I'll leave this open though, because I still think this area of the docs could be expanded on a bit.

**Comment by Andarist** [comment]
The only difference is that when you are using plain strings they are... well, strings. This means that it's harder for tooling to recognize them as special css strings, so you don't get syntax highlighting in editor, auto-formatting with prettier, babel plugin optimizations etc.

**Comment by seaneking** [comment]
Okay awesome, I wasn’t sure if there was any repercussions of nesting the tagged template literals
