### ISSUE TITLE
Docs: cannot target components without using styled syntax

### ISSUE THREAD

**Issue by earksiinni** [emotion-js/emotion#1856]
**Description:**

The docs for styled state:

> ## Targeting another emotion component
>
> Similar to styled-components, emotion allows for emotion components to be targeted like regular CSS selectors when using babel-plugin-emotion.

However, I've only been able to target emotion components that are written using styled syntax. I.e., non-styled components don't seem to work with emotion components written using the `css` prop.

It would be great to clarify with something like, "Similar to styled-components, emotion allows for emotion components written with `styled` to be targeted like regular CSS selectors when using babel-plugin-emotion."

Unless I'm mistaken and there is a way to target non-styled components...?

**Documentation links:**

https://emotion.sh/docs/styled

**Comment by Andarist** [comment]
> Unless I'm mistaken and there is a way to target non-styled components...?

No, there is no such way - we don't recommend using cascade at all, it only leads to specificity wars, multiple sources of truth etc.

If you feel like it - please prepare a PR to the docs with the proposed change so this.
