### ISSUE TITLE
@emotion/native - flex: 1 should match React Native behavior or be otherwise documented

### ISSUE THREAD

**Issue by Slapbox** [emotion-js/emotion#1857]
**Current behavior:**

```js

import Touchable from 'react-native-platform-touchable';

const RestyledTouchable = styled(Touchable)`
  flex: 1;
`;

```

Adding `flex: 1` to `Touchable` in this manner leads to elements collapsing to a zero pixel height. This only occurs in one location in our application but I kept cutting away until I found that `flex: 1` is the cause. 

Adding `flex: 1` via `style` like this works though, and the elements have their expected size:

```js

const RestyledTouchable = styled(Touchable)`
 // ... any other styles under the sun, except flex: 1
`;

<RestyledTouchable style={{ flex: 1 }} />

```

I found this really surprising, and it took me about two hours to find the cause. I'm not sure how it might be re-created under 

**To reproduce:**

One very strange aspect of this bug is that the wrongly styled components will initially render properly before collapsing - and they'll also magically and persistently become properly styled after React Native's Fast Refresh refreshes them.

**Expected behavior:**

`flex: 1` should produce results identical to `style={{ flex: 1 }}` or be otherwise documented

**Findings:**

It looks like (single quotes for backticks) `css'flex: 1'` outputs:

```js
 flexGrow: 1,
 flexShrink: 1,
 flexBasis: 0, 
```

So I guess `style={{flex: 1}}` in React Native doesn't imply those properties. And indeed, applying those properties exactly via `style={{}}` leads to the exact same breakage.

**Environment information:**

- `OS` version: `Android 9`
- `react` version: `16.9.0`
- `emotion` version: `10.0.27`
- `@emotion/native`: `10.0.22`

**Comment by Andarist** [comment]
We are using https://github.com/styled-components/css-to-react-native to parse css strings into RN-compatible objects. Even though we don't use its latest version, it behaves the same way in this regard (this has not been changed in `css-to-react-native@3`). You might find why this works this way [here](https://github.com/styled-components/styled-components/issues/1158#issuecomment-328527408)

**Comment by Slapbox** [comment]
Thanks @Andarist. I'd strongly suggest adding that to https://emotion.sh/docs/@emotion/native. Are there some more docs for `@emotion/native` I'm not aware of? It should really be mentioned somewhere.

**Comment by Andarist** [comment]
>  I'd strongly suggest adding that to https://emotion.sh/docs/@emotion/native.

PRs are welcome 😉 We treat `@emotion/native`-related packages as community-driven. We don't use them ourselves in production so it's rather hard to maintain them appropriately. In [styled-components docs](https://styled-components.com/docs/basics#react-native) there is such note about this:

"Note that the flex property works like CSS shorthand, and not the legacy flex property in React Native. Setting flex: 1 sets flexShrink to 1 in addition to setting flexGrow to 1 and flexBasis to 0."

I would suggest copying this and finding a good place for it in our docs - it should be a fairly simple PR.

> Are there some more docs for @emotion/native I'm not aware of? It should really be mentioned somewhere.

I'm not sure if there are any other gotchas like this, but it's rather unlikely.

**Comment by Slapbox** [comment]
I very much doubt there's any others since it took an entire year for me to hit this one haha. Submitted a PR. Thanks as always for your help @Andarist. Closing this in anticipation of #1858 being merged.
