### ISSUE TITLE
CreateStyled is not Templated in @emotion/native @next (11.0.0-next.12)

### ISSUE THREAD

**Issue by andrewphillipo** [emotion-js/emotion#1861]
I'm using ```@emotion/native@next``` and want to get a typed theme prop applied across all ```styled.<ReactNativeComponent>``` emotion components.

Currently I'm trying the example as laid out in the docs for React rather than React Native.

Unfortunately the CreateStyled interface is not Templated so I cannot pass my theme type in the same way on Native as with vanilla React.

```ts
import styled, { CreateStyled } from "@emotion/native";

type Theme = {
  color: {
    primary: string;
    positive: string;
    negative: string;
  };
  // ...
};

export default styled as CreateStyled<Theme>;
```

The error I get is ```Type 'CreateStyled' is not generic.```.

**Expected behavior:**

CreateStyled supports a prop for the shape of the Theme I've built and I get correct auto completion for theme properties such as colors in my Emotion Components.

**Environment information:**

- `react` version: react@16.9.0
- `emotion` version: @emotion/core@11.0.0-next.10 @emotion/native@11.0.0-next.12 etc.

**Comment by Andarist** [comment]
Could u try this - https://github.com/emotion-js/emotion/issues/1606#issuecomment-623882701 ?

**Comment by andrewphillipo** [comment]
Brilliant!

```
import "@emotion/react";
import theme from "../styles/theme";

type ThemeType = typeof theme;

declare module "@emotion/react" {
  export interface Theme extends ThemeType {}
}
```

This is what I ended up with thank you 👍🏻
