### ISSUE TITLE
Please review my DefinitelyTyped PR for compatibility with emotion

### ISSUE THREAD

**Issue by cyrilchapon** [emotion-js/emotion#1863]
**The problem**

When using Typescript with rebass and Emotion; getting a compile error for the `css` prop attending the `StyledComponents` version **ONLY**

> SerializedStyle is not assignable...

**Proposed solution**

Here's the DT PR.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44516

In a nutshell, [I mixed the type of `BaseProps.css`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44516/files#diff-219b1cad54ad5e8c9efd241f9e314f23R23-R39) to accept both StyledComponents and Emotion versions; but I'm unsure of what I just did.

I would appreciate some help there 🙂

**Additional context**
Related :
- https://github.com/emotion-js/emotion/issues/1084

**Comment by Andarist** [comment]
Could you prepare a runnable usage example of how you are mixing rebass and emotion?

**Comment by cyrilchapon** [comment]
Yes; but the PR is not ready. I suspect cssobject not being assignable to this at all

**Comment by Andarist** [comment]
Hm, I'm not sure if we understood each other - I would appreciate you sharing the runnable usage example for rebass+emotion. Ignoring your DefinitelyTypes PR for a moment, because to review it I would have to know how rebass+emotion can work together at runtime (ignoring TS right now).

**Comment by cyrilchapon** [comment]
Hey @Andarist ;

Sorry bud; I thought you had replied on the PR itself there.

Here :

_theme.ts_
```
import { preset } from '@rebass/preset'
import emotionNormalize from 'emotion-normalize'
import { css } from '@emotion/core'

export const normalize = (theme: Theme) => emotionNormalize

export const globalStyles = (theme: Theme) => css`
  // Some global styles
`
export const theme = {
  ...preset,
  ...{ /* some theme tweaks */ }
}
export type Theme = typeof theme
```

_app.ts_
```
import { FunctionComponent } from 'react'
import { ThemeProvider } from 'emotion-theming'
import { Global } from '@emotion/core'

import { theme, Theme, normalize, globalStyles } from './theme'

import { SomeComponent } from './some-component'

export const App: FunctionComponent = () => (
  <ThemeProvider theme={theme}>
    <Global<Theme> styles={normalize} />
    <Global<Theme> styles={globalStyles} />

    <SomeComponent />
  </ThemeProvider>
)
```

_some-component.ts_
```
import { FunctionComponent, forwardRef } from 'react'
import { Box, BoxProps } from 'rebass'

export const SomeComponentProps extends BoxProps {
  // Some props
}

export const SomeComponent: FunctionComponent<SomeComponentProps> = forwardRef<typeof Box, SomeComponentProps>((props, ref) => {
  return (
    <Box
      ref={ref}
      my={['3', null, null, '4']}
      {...props}
    />
  )
})
```

_index.ts_
```
import * as ReactDOM from 'react-dom'

import { App } from './app'

ReactDOM.render(
    <App />,
    document.getElementById('root')
)
```

**Comment by Andarist** [comment]
This is a not a runnable usage example. I can't afford to set this up - everything, unfortunately, costs time, and I have too many repositories to take care of to do this kind of work for each issue. I hope you understand.

**Comment by Andarist** [comment]
I'm afraid that the sufficient repro case has not been provided here and the problem is concerned with `rebass` package which we do not maintain, so I can't really justify putting too much of my time into it. Hope you understand.
