### ISSUE TITLE
bable-plugin-emotion not observing devtoolModuleFilenameTemplate

### ISSUE THREAD

**Issue by boycce** [emotion-js/emotion#1864]
**Current behavior:**

`webpack.output.devtoolModuleFilenameTemplate` is ignored 

**To reproduce:**

_Webpack.config.js_
```
output: {
    devtoolModuleFilenameTemplate: info => {
      return "file://" + encodeURI(info.absoluteResourcePath)
    }
}
```
**Expected behavior:**

Rendered sourcemap filenames should be prefixed with the `file://` protocol.
If `devtoolModuleFilenameTemplate` is defined, this should be called to resolve source-map filenames

**Environment information:**

- `react` version: `16.13.1`
- `emotion` version: `10.0.28`
- `babel-plugin-emotion` version: `10.0.33`

**Comment by Andarist** [comment]
Babel has no knowledge of webpack, so it can't know that - maybe `babel-loader` can pass this somehow to Babel (and thus to our plugin) but I'm afraid I won't have time to investigate this. Feel free to do so and prepare a PR if u manage to make it work.

**Comment by Andarist** [comment]
I've checked the source code of `babel-loader`. This information is not provided to plugins from there, so to get it working you would have to create an issue in their repository asking for this to be added and if it ever gets published then we could add support for it here. Closing this now as it's not actionable on our side, hope you understand.
