### ISSUE TITLE
Target another component on hover using emotion-js

### ISSUE THREAD

**Issue by sptGabriel** [emotion-js/emotion#1866]
Hello i have a problem to target another component in focus using emotion-js

i try this:

```
  &:hover + ${WrapScrollable} {
    background: red;
  }
```

but dont work 

my code:

```
const WrapScrollable = styled.div`
  height: calc(100% - 165px);
  overflow: scroll;
  background: orange;
  margin-bottom: 100px;
`;

const Litem = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  background: hotpink;
  &:hover + ${WrapScrollable} {
    background: red;
  }
`;
```

example:

https://codesandbox.io/s/dazzling-turing-qbzlh?file=/src/App.js

**Comment by Andarist** [comment]
Is this what you are looking for - https://codesandbox.io/s/vibrant-snow-nww98?file=/src/App.js ?

**Comment by sptGabriel** [comment]
> Is this what you are looking for - https://codesandbox.io/s/vibrant-snow-nww98?file=/src/App.js ?

Hello I ended up changing the codesandbox but basically I want to add a css to the parent when the li tag is hovered

my parent have overflow-y: auto

on hover li i want overflow-y: hidden;

**Comment by Andarist** [comment]
> I want to add a css to the parent when the li tag is hovered

This is just not possible in CSS and emotion is CSS after all - even if authored in JS files. So this is impossible - you need to implement this using JS.

**Comment by sptGabriel** [comment]
> > I want to add a css to the parent when the li tag is hovered
> 
> This is just not possible in CSS and emotion is CSS after all - even if authored in JS files. So this is impossible - you need to implement this using JS.

@Andarist  hii thank u for help

and about this:
https://codesandbox.io/s/vibrant-snow-nww98?file=/src/App.js
how i can make this with css from '@emotion/core' ?

**Comment by Andarist** [comment]
Use data attribute if needed: https://codesandbox.io/s/festive-ramanujan-jlhds?file=/src/App.js

**Comment by sptGabriel** [comment]
@Andarist  sorry for this, but u can help me with last question?

with css emotion core is possible make dynamic props?

pass props with css core?

like this:

```
const dynamicStyle = props =>
  css`
    color: ${props.color};
  `

const Container = styled.div`
  ${dynamicStyle};
`
```

but with css core?

**Comment by JuanDiegoAcostaT** [comment]
> Use data attribute if needed: https://codesandbox.io/s/festive-ramanujan-jlhds?file=/src/App.js

this Workssss

**Comment by Qliksenseportly** [comment]
@sptGabriel https://csser.space/questions/displaying-an-element-when-hovering-over-another-using-css
