### ISSUE TITLE
Theming with Next.js not working (empty object)

### ISSUE THREAD

**Issue by dwalsh01** [emotion-js/emotion#1867]
**Current behavior:**

I am working with the latest available versions of the emotion packages and Next.js. The issue that currently persists is that when attempting to access the `theme` from props the object is empty. 

An important note to make is that I am using a tailwind macro plugin to use the `${tw`bg-green-500`}` syntax within my 

**To reproduce:**

Please view my repository below:
https://github.com/dwalsh01/prime-garden

1. clone the repo
2. yarn install
3. yarn run dev
4. open dev tools to see the theme object is empty
5. To view where this is occurring please view `CreateItemForm.js:54`, where the theme is being logged.
6. The `PageLayout.js` file contains the root all pages and is where the theme is used.
7. To view the `ThemeProvider itself please view the `theme.js` file. 

**Expected behavior:**

I expected to be able to access the theme object within my components as all of them are children of the `ThemeProvider`

**Environment information:**

- `react` version: 16.13.1
- `emotion` version: ^10.0.27
- `emotion/styled` version: ^11.0.0-next.12

**Comment by dwalsh01** [comment]
I apologise I placed the issue within the `feat/prisma` branch.

Here is the updated link:

https://github.com/dwalsh01/prime-garden/tree/feat/prisma

**Comment by Andarist** [comment]
You shouldn't be mixing v10 and v11 like this - this only partially works because they stay somewhat compatible but you have already bumped into a problem.

Please change [this line](https://github.com/dwalsh01/prime-garden/blob/e9c39d0ee0ddbfb831fd16159b646f6b87c908cc/styles/theme/theme.js#L1) to:
```js
import { ThemeProvider } from '@emotion/react';
```

**Comment by dwalsh01** [comment]
That fixed the issue, thank you.

**Comment by DominicTobias-b1** [comment]
For anyone else coming here from Emotion 11 wondering why theme object is empty in styled components once consumed in an app you need to do horrendous fixes to storybook's webpack config: https://gitmemory.com/issue/storybookjs/storybook/12262/681953346
