### ISSUE TITLE
Pseudo element isn't rendered when using ObjectInterpolation

### ISSUE THREAD

**Issue by henryqrm** [emotion-js/emotion#1869]
Hi guys,

I believe I found a small bug. When creating a component with a pseudo-element using the object, it does not occur as expected.

My code: 

```ts
className={css({
      position: "relative",
      color: "blue",

      "::after": {
        borderStyle: "solid",
        borderWidth: "1px",
        pointerEvents: "none",
        bottom: 0,
        content: "",
        left: 0,
        position: "absolute",
        right: 0,
        top: 0
      }
    })}
```

In devTools

![image](https://user-images.githubusercontent.com/11713190/81773929-d0256f00-94bf-11ea-9679-73b09652a192.png)

Where is `content`?

**exemple**

https://codesandbox.io/s/tender-newton-l4mb4?file=/src/App.js

- `react` version: 16.12.0
- `emotion` version: 10.0.27

**Comment by Andarist** [comment]
Please check console output, you have been warned about the mistake you have made:
<img width="670" alt="Screenshot 2020-05-13 at 11 41 09" src="https://user-images.githubusercontent.com/9800850/81797226-c8d98200-950e-11ea-9ea3-b10aa1bfe64e.png">

**Comment by henryqrm** [comment]
thanks
