### ISSUE TITLE
Interpolating functions in css calls

### ISSUE THREAD

**Issue by josephmarkus** [emotion-js/emotion#1871]
I would like to use a helper function for media queries that essentially wraps my CSS.

My problem is when this function attempts to style based on props.

Although I know that styled-components has only been a source of inspiration for emotion, I have a working example here: https://codesandbox.io/s/breakpoints-styled-components-64yox?file=/src/App.js

Equivalent of that in Emotion throws an error: https://codesandbox.io/s/breakpoints-emotion-js-nf58w?file=/src/App.js

I saw this suggested solution here - https://github.com/emotion-js/emotion/issues/1085#issuecomment-516793663 - but I'm unsure how to correctly apply this when my styles can have generic conditionals inside them.

Note that the example uses Emotion v9

Any help would be much appreciated 🙏

**Comment by Andarist** [comment]
A working solution for Emotion 9: https://codesandbox.io/s/breakpoints-emotion-js-umbcd?file=/src/App.js
