### ISSUE TITLE
The babel-preset-css-prop incompatible with Next.js 9.4.0

### ISSUE THREAD

**Issue by nghiepit** [emotion-js/emotion#1872]
The problem when upgrading `Next.js` from `9.1.7` to `9.4.0`. Sorry if this is not a problem for `emotion`.

The `babel-preset-css-prop` incompatible with `Next.js 9.4.0`.
In the production build stage the `css prop` does not work like in the `development`.

The below result:
```
<div css="[object Object]">
```
![image](https://user-images.githubusercontent.com/4768095/82170633-390d4c80-98ef-11ea-9e16-d1f3b458af4e.png)

My `.babelrc`
```json
{
  "presets": [
    [
      "next/babel",
      {
        "preset-env": {
          "targets": {
            "browsers": ["> 0.25%", "not ie 11", "not op_mini all"]
          }
        }
      }
    ],
    "@emotion/babel-preset-css-prop"
  ],
  "plugins": []
}
```

**Environment information:**

- `next: 9.4.0`
- `@emotion/core: ^10.0.28`
- `@emotion/styled": ^10.0.27`
- `@emotion/babel-preset-css-prop: ^10.0.27`

**Additional information**
I don't custom `_document.js` and `_app.js`, just use `emotion`

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by nghiepit** [comment]
Sorry. I've solved the issue.
This is because I'm used the experimental feature of Next.js.

```diff
module.exports = {
  experimental: {
-   modern: true,
  },
};

```

**Comment by mstaicu** [comment]
I have `next@9.4.4` and `@emotion/babel-preset-css-prop@11.0.0-next.10` and I cannot get the preset to load

```
{
  "presets": ["next/babel", "@emotion/babel-preset-css-prop"],
  "plugins": ["@babel/plugin-proposal-optional-chaining"]
}
```

Yields

`Error: Cannot find module '@emotion/babel-preset-css-prop'`

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by mstaicu** [comment]
Totally agree @Andarist. Turns out it was an inconsistency with my Docker images. All good now, simply rebuild the images and re ran the containers
