### ISSUE TITLE
VS Code Organize Imports causes JSX error

### ISSUE THREAD

**Issue by Hainesy** [emotion-js/emotion#1873]
Reorganizing imports in VS code causes the comment to separate from the jsx import. Is there any way to solve/prevent this?

```
/** @jsx jsx */
import { css, jsx } from '@emotion/core';
```

**Comment by Andarist** [comment]
Im not sure if i understand the issue - could you paste in the input code + actual and expected outcomes?

**Comment by Andarist** [comment]
The repro case has not been provided for over 20 days. As I don't fully understand the issue without it I'm going to close this as non-actionable on our side right now. If you find a time to report this back in the future together with the detailed explanation I could take a look at it then.
