### ISSUE TITLE
First class support for `className={css(…)}`?

### ISSUE THREAD

**Issue by amannn** [emotion-js/emotion#1877]
I read in the upgrade docs for v10 that the [usage of the `css` function should be changed to the `css` prop](https://emotion.sh/docs/migrating-to-emotion-10#manual-steps-over-time).

I'm curious if that was a necessary change to unlock improvements that just aren't possible with the `className={css(…)}` API?

There was recently a [discussion on Twitter](https://twitter.com/Tibfib/status/1262138540403507200) where also [@threepointone agreed ](https://twitter.com/threepointone/status/1262182894698745858)that the `css` prop isn't an ideal API.

As far as I understand the current implementation of Emotion, the `css` prop is turned into `className` in the `jsx` helper. I think what's really nice about this, is that this works for more edge cases, e.g. spreading a `css` prop onto an element.

However I think it's still a bit confusing that you assign a `css` prop on an element but then receive `className` in the component itself. I think another advantage of the `className` prop API is that it works for edge cases like `wrapperClassName` without needing additional API like `ClassNames`. I guess TypeScript integration would also be simpler without this mapping, e.g. a mandatory `className` prop doesn't seem to work with the current typings ([CodeSandbox demo](https://codesandbox.io/s/css-in-js-emotion-typescript-gj47u?file=/src/App.tsx)).

I experimented a bit with the `className={css(…)}` API and I found that hoisting of style declarations isn't enabled for this API. The zero-config server rendering API seems to be another feature that is reserved for the `css` prop.

So my question is: Would it be possible to have the same level of support for the `className={css(…)}` API as for the `css` prop? Or is this a non-goal for this library?

Thanks for your thoughts!

**Comment by amannn** [comment]
I guess this is related: https://github.com/emotion-js/emotion/issues/961

**Comment by Andarist** [comment]
> However I think it's still a bit confusing that you assign a css prop on an element but then receive className in the component itself. I

When this matters though? Inspecting children element is rather an anti-pattern so this should be avoided anyway.

> I think another advantage of the className prop API is that it works for edge cases like wrapperClassName

This, in particular, is not quite true - we need to know which props should we handle in a special manner and handling all of them is definitely not something we'd like to do.

> I guess TypeScript integration would also be simpler without this mapping, e.g. a mandatory className prop doesn't seem to work with the current typings (CodeSandbox demo).

We'd have to tamper with builtin `className` type which sounds like a can of worms 😅 The presented code is also not that compelling to me as I don't see why you would like to **require** `className` prop - this is stylistic and should nearly always be up to the consumer to provide it or not.

> So my question is: Would it be possible to have the same level of support for the className={css(…)} API as for the css prop? Or is this a non-goal for this library?

This is a non-goal unless we decide to use className instead of the css prop. Supporting both doesn't IMHO make much sense - education etc suffers a lot in cases like this.

Just an additional note - `className={css({color:'hotpink'})}` is still allowed if you are willing to stick to vanilla Emotion.

**Comment by amannn** [comment]
Thanks for your detailed response!

> However I think it's still a bit confusing that you assign a css prop on an element but then receive className in the component itself.
>> When this matters though? Inspecting children element is rather an anti-pattern so this should be avoided anyway.

I meant this use case:

```js
function App() {
  return <Foo css={{color: 'blue'}} />;
}

// No `css` prop, but instead a `className` appears from somewhere
function Foo({className}) {
  return <p className={className}>Foo</p>;
}
```

This is something the users of the library and tooling has to understand. The TypeScript error I mentioned above is an example of an edge case where the tooling hasn't really understood this yet, arguably it's a bad example though 🙂.

> This is a non-goal unless we decide to use className instead of the css prop. Supporting both doesn't IMHO make much sense - education etc suffers a lot in cases like this.

Yep, I think so too!

For me personally it comes down to:
- `css` prop: Convenient API, but slightly magical and some edge cases to consider.
- `css` function provided to `className`: Slightly more verbose, but explicit. In the current implementation this has some performance drawbacks in comparison to the `css` prop.

In the end it's different tradeoffs I guess and I definitely see the point for the `css` prop!

Btw. thank you very much for your work on emotion! I'm finally getting into css-in-js and emotion with its `css` prop seems to be a really nice way to author components 🙂.

**Comment by Andarist** [comment]
This is something we definitely won't change in the near future - it would be a substantial change affecting our consumers. Going to close this as it's not actionable right now on our part, but I've noted your concerns and will monitor similar concerns from others in the future to see how this is seen by other consumers as well. Thanks for the feedback!

**Comment by amannn** [comment]
Thank you too for your thoughts!
