### ISSUE TITLE
[jest-emotion] snapshots reordering css based on test order, causing failures.

### ISSUE THREAD

**Issue by Jimmydalecleveland** [emotion-js/emotion#1878]
**Current behavior:**
Rendering styled components in `jest` using `@testing-library/react` and `@testing-library/jest-dom` is causing some sort of mutation that changes the order css is written in the snapshot. This causes snapshots to fail when a test is skipped, removed, or re-ordered, among other situations.

It took me many hours to track this down in a large project and it makes our tests very unreliable and causes a ton of noise when the code in many of our styled components changes.

**To reproduce:**
I've created a reproduction repo here:
[https://github.com/Jimmydalecleveland/emotion-jest-reordering-bug](https://github.com/Jimmydalecleveland/emotion-jest-reordering-bug)

The instructions are in the readme. This is not the only way to reproduce this bug, but it's the most simple and clear that I could come up with. Thank you, in advance, for looking at this and any help you can give.

Here is a quick example screenshot from the repo I linked which shows the css being re-ordered:
![image](https://user-images.githubusercontent.com/3894120/82841617-fff74e00-9e93-11ea-8897-018ffb5b4826.png)

**Expected behavior:**
The order of the tests should not mutate other test snapshots. Removing, skipping, or moving a test should not fail other tests snapshots due to css being moved around.

**Environment information:**

- `react` version: 16.12.0
- `emotion` version: 10.0.27
- `jest` version: 24.9.0 (25's new diffing tool still has conflicts with `jest-emotion`)
- `jest-emotion` version: 10.0.27

**Comment by Andarist** [comment]
`getStylesFromClassNames` currently works by iterating through extracted `classNames`:
https://github.com/emotion-js/emotion/blob/fc119766b539f73546dc8e2863cca1439af3cb1c/packages/jest/src/utils.js#L168
and appending matches to the output string, so yes - this currently is prone to style elements being reordered.

A possible solution to this would be to change how this is being iterated in a way that would preserve the order of input `classNames`. Would you like to take a stab at this?

**Comment by Jimmydalecleveland** [comment]
That makes sense, but what I'm quite confused on is why rendering a component in separate tests (like in my repo example) would cause other tests snapshots to re-order. It does not seem like they should affect each other at all, and in most cases they do not.

Thanks for linking to the code, I'll try looking around there, but I don't know if it is exactly the same issue.

**Comment by Andarist** [comment]
Both tests share the same underlaying cache which is only populated when styles are about to be rendered (so as lazily as we can get). If you have 2 tests - A and B (in that order) and you render both then you end up with A and B styles injected (in that order), if you skip A then you only have B styles injected and this has messed up your snapshots.

**Comment by Jimmydalecleveland** [comment]
Thank you for the additional info. I believe I understand the nature of the problem now.

I've traced the ordering of the HTMLStyleElements back to here:
https://github.com/emotion-js/emotion/blob/fc119766b539f73546dc8e2863cca1439af3cb1c/packages/jest/src/utils.js#L211

And the order the styles are written in when queried from jsdom is different depending on the order the components are called in. 

This makes sense to me now, since it is calling component A or B first and choosing that as the first style rule, as you explained (I just needed to see it to make full sense of your explanation).

So I'm stuck on what to do at that point. I can't imagine we'd want to change that behavior for emotion in general, so all I can think of is either sorting them in the serializer by classname or clearing the test cache between renders (and I worry that would be a performance issue without knowing more).

Any ideas?

**Comment by Jimmydalecleveland** [comment]
I have a fork with the sorting change I mentioned, and it seems to fix the problem from the testing I've done so far. The problem is, that is a pretty big change that would require everyone already using the package to update a lot of their snapshots.

On the emotion repo, 32 snapshots failed and needed updating. So I don't think you are going to want that fix. I can create a PR if you want to look at it. I made it off the `next` branch since I wasn't sure which you wanted me to branch from and merge back into.

**Comment by Andarist** [comment]
Yes - changing this on the next branch would probably be best. Could you prepare a PR with the change? We could discuss this further then.

**Comment by Jimmydalecleveland** [comment]
Sorry it took a bit, I wanted to run some additional tests to make sure it worked in different scenarios. Here it is: #1880

**Comment by Andarist** [comment]
This got fixed in https://github.com/emotion-js/emotion/pull/1880
