### ISSUE TITLE
styled(Components) should override the base component properties

### ISSUE THREAD

**Issue by DominicTobias-b1** [emotion-js/emotion#1882]
**The problem**

Hi, I don't want to litter my app with `!important` when extending styled objects.

**Proposed solution**

```js
const RightAlignedTextInput = styled(TextInput)`
  text-align: right;
`
```

Should override the `text-align` property of `TextInput` instead of being overwritten:

<img width="333" alt="Screenshot 2020-06-02 at 7 58 19 AM" src="https://user-images.githubusercontent.com/58683337/83465535-d4cdb980-a4a6-11ea-9749-502ea2b12699.png">

**Alternative solutions**

Using !important which is nasty

Thanks!

**Comment by Andarist** [comment]
Your former rule is more specific than the latter one - it's targeting a descendent element (input). We can't make the latter class stronger because we have no idea that you have targeted `input` there, nor we know that the latter class will be applied onto `input`.

**Comment by DominicTobias-b1** [comment]
Hm yes I see your point, is there a way to merge in new styles which overwrite the original ones if they exist in TextInput? I can see that getting complicated for nested css I guess.

**Comment by Andarist** [comment]
This is not possible, you would have to replicate the exact nesting in your new styles. In general, we don't recommend using nested selectors at all as they make stuff like that harder to reason about and Emotion's philosophy is "predictable styles".
