### ISSUE TITLE
Theme prop rendering incorrect styles

### ISSUE THREAD

**Issue by amykapernick** [emotion-js/emotion#1884]
**Current behavior:**

Based on the props in a theme, styles are rendered. Eg. the header logo svg changes colours based on a prop in the theme
```
.name {
    fill: #000;
    fill: ${(props) => (props.theme.colours.themes.header.lightLogo === true && `#fff`)};
}
```
If it has the `lightLogo` prop, it should fill with white, otherwise black.

But on the homepage of the site, it currently renders the logo with a white fill, despite the fact that the `lightLogo` prop is false

This only happens during a production build (`gatsby build`), not in dev mode (`gatsby develop`)

In React dev tools, can see the theme prop on the logo, and the `lightLogo` prop is set to false on the homepage, however the white fill style is still being rendered
![image](https://user-images.githubusercontent.com/15953185/83599081-e3e36300-a59d-11ea-841d-5edfc575ea0e.png)
![image](https://user-images.githubusercontent.com/15953185/83599113-f3fb4280-a59d-11ea-98d4-f5a59b352b45.png)

**To reproduce:**

- Github Repo <https://github.com/amykapernick/emotion-theming-issue>
- Netlify Build of repo <https://serene-bardeen-30de22.netlify.app>

**Expected behavior:**

**Environment information:**

- `react` version:
```
"react": "^16.13.1",
"react-dom": "^16.13.1",
"gatsby": "^2.22.17"
```
- `emotion` version:
```
"@emotion/core": "^10.0.28",
"@emotion/styled": "^10.0.27",
"emotion-theming": "^10.0.27",
"gatsby-plugin-emotion": "^4.3.3",

```

**Comment by Andarist** [comment]
Have you managed to fix your problem?
