### ISSUE TITLE
Components into attributes of a component don't respect `labelFormat` for class names

### ISSUE THREAD

**Issue by kud** [emotion-js/emotion#1887]
**Current behavior:**

When using attributes of a component to inject some sub-components, the class names generated don't respect the labelFormat.

**To reproduce:**

https://codesandbox.io/s/emotion-issue-template-o66xu?file=/src/index.js

Create this code:

```
const Timeline = styled.ul``;
Timeline.Item = styled.li``;
```

**Expected behavior:**

Timeline.Item should have a more explicit class name like `css-kt62j9-Timeline-Item` and not `css-0`

**Environment information:**

- `react` version: 16.13.1
- `emotion` version: 10.0.28 (core) / 10.0.27 (styled)

**Comment by javialon26** [comment]
as a workaround, you can create the component and then pass it as an attribute.

```
const Timeline = styled.ul``;
const TimelineItem = styled.li``;
Timeline.Item = TimelineItem;
```

**Comment by Andarist** [comment]
I've implemented support for this in https://github.com/emotion-js/emotion/pull/1893 . Keep note that this only targets the upcoming v11 release.

I'm going close this issue as the PR probably will land soon and I'm in the process of going through issues so closing this helps me organize my work. Thanks for understanding.

**Comment by kud** [comment]
Thank you @Andarist !
