### ISSUE TITLE
Generic "Box" component with dynamic HTML props

### ISSUE THREAD

**Issue by gabrielsch** [emotion-js/emotion#1889]
I have a generic `Box` component in my codebase and this Box can be any HTML element, by passing the `as` prop into it.

The problem is that some HTML elements have different attributes and they don't come dynamically from the `as` property.

```
const Box = styled("div", {})(truncate, systemProps);
```

then:

```
<Box as="a" href="https://github.com">My anchor</Box>
```

Typescript would throw an error here because `href` is not a `div` attribute.

Do you have an idea of how I can type this component?

**Comment by Andarist** [comment]
From our perspective - `as` prop is too dynamic and it's too hard for us to create types aware of this kind of thing. This is not ideal of course, but it is what it is.
