### ISSUE TITLE
You can't style components wrapped with React.memo

### ISSUE THREAD

**Issue by Ed-Ed** [emotion-js/emotion#1890]
If the component is wrapped in React.memo, it does not apply the styles.

Example: https://codesandbox.io/s/gracious-brahmagupta-4wt2o

**Comment by Andarist** [comment]
You have to forward received props like this:
```js
const FunctionalComponent = React.memo(props => {
  return <div {...props}>hello world 1</div>;
});
```
because styling happens based on a `className` prop which you have not set on your div element.
