### ISSUE TITLE
Possibility to use class-name property instead of className

### ISSUE THREAD

**Issue by khmelevskii** [emotion-js/emotion#1892]
**The problem**

I created a tiny Emotion wrapper in ClojureScript. I'm going to open-source this wrapper but I have issue with `className` property. In Clojure idiomatic to use kebab-case notation. So, it would be great to use prop `class-name` in styled components instead of `className` but unfortunately I don't have any methods in emotion to change it.
Currently I have only one way, it's wrap styled component to `react.createElement` and convert `className` to `class-name`.

**Proposed solution**

It would be great to add this to options (somethings like `shouldForwardProp`). For example,
```
{
  classNameProps: 'class-name',
}
```
Link to this wrapper (WIP) https://github.com/khmelevskii/emotion-cljs

**Comment by Andarist** [comment]
I'm afraid that this is out of Emotion's scope and we do not plan to make this customizable. The primary target of this library is regular React written in JS in which this works as expected.

Thanks for taking interest in Emotion though!

**Comment by khmelevskii** [comment]
@Andarist yes, I see your point. In ClojureScript world it's very easy to use React and it would be great to have Emotion in our ecosystem too.
I agree that it's a little strange to add not relevant for JS option but maybe it's possible to add some common method, which I will be able to use for my case too.
For example,
```
options: {
  renameForwardProp: (propName) => propName === 'className' ? 'class-name' : propName,
  // or
  attachForwardProps: (props) => ({
    'class-name' => props.className,
  })
}
```
So, if we can think of some good method, which you guys approve and this method solves my case and is useful in JS world, I would love to create PR.

**Comment by Andarist** [comment]
I have no idea about ClojureScript - so please bear with me. Are you reimplementing stuff in your library or just wrapping our JS code and provide "bindings" for the ClojureScript? Haven't you already implemented what you are looking for [here](https://github.com/khmelevskii/emotion-cljs/blob/01be75a1fe9ec7762f28fa8974e37284511639cf/src/emotion/core.cljs#L51)? If yes - what's your concern about the used technique?

**Comment by khmelevskii** [comment]
Sure, no problem. `emotion-cljs` is just a tiny wrapper which provides "bindings" to Emotion. I don't implement any features and just provide idiomatic clojure syntax for working with emotion.
You are right, I handled this problem in my lib but unfortunately I have only one way how I can do it - I need to wrap component to another component where I convert `className` property.
https://github.com/khmelevskii/emotion-cljs/blob/01be75a1fe9ec7762f28fa8974e37284511639cf/src/emotion/core.cljs#L71
I mean the following:
instead of this
```
@emotion.styled(MyComponent, options)
```

I had to do the following:
```
@emotion.styled((props) => react.createElement(MyComponent, convertPropsToKebab(props)), options)
```

It works, but I'm not happy that I have this wrapper in my components tree :(. It would be really awesome if I am able to do something like this:
```
@emotion.styled(MyComponent, {
  withProps: (props) => convertPropsToKebab(props),  // or just withProps: convertPropsToKebab,
})
```

**Comment by khmelevskii** [comment]
@Andarist just wanted to let you know that I added documentation to emotion-cljs and you can see which interface I provide to work with emotion in clojure.
This feature which we discuss here just will help me to reduce some complexity and unnecessary wrapping of react components.

**Comment by Andarist** [comment]
Hm, so how does it even work with React? It seems that you are using bare React package:
https://github.com/khmelevskii/emotion-cljs/blob/01be75a1fe9ec7762f28fa8974e37284511639cf/src/emotion/core.cljs#L12
How does it know to handle `class-name` instead of `className`? It's not what React handles by default and I'm confused by this.

Also - how other libraries handle this? I would expect this to be quite a common problem when integrating any library that provides `className`.

**Comment by khmelevskii** [comment]
Hi @Andarist ! I would like to get back to this question :)
Answer to your questions:
> Hm, so how does it even work with React? It seems that you are using bare React package:
https://github.com/khmelevskii/emotion-cljs/blob/01be75a1fe9ec7762f28fa8974e37284511639cf/src/emotion/core.cljs#L12
How does it know to handle class-name instead of className?

Yes, I use bare react and react doesn't know anything about `class-name`, that's why `emotion-cljs` replace all `class-name` to `className` and then pass it to bare react component. It looks like this example below (simplified version):
```
react.createElement(
  (props, children) => react.createElement('div', { ...props, className: props['class-name'] }, children),
  props,
  children
)
```
But in this case I had to create additional `createElement` to be able to transform props.

> how other libraries handle this

In Clojure it is idiomatic to use kebab-case notation and most libraries support it. For example:
1. https://github.com/reagent-project/reagent
As you can see we use `on-change` instead of `onChange`, `on-mouse-move` instead of `onMouseMove`, `class-name` instead of `className` etc. Also it's possible to use `class` instead of `className` https://cljdoc.org/d/reagent/reagent/1.0.0/doc/tutorials/using-hiccup-to-describe-html#special-interpretation-of-class-attribute
> In JavaScript, class is a reserved keyword, so React uses the className to specify class attributes. Reagent just uses class.
2. https://github.com/lilactown/helix The same in another popular react wrapper.

So, it's idiomatic for clojurists and we would like to use kebab notation that's why it would be great to do the same in emotion-cljs and do it effectively.

My idea is super easy and it's only a few lines. Please check my PR. Ready to discuss everything what you need, change interface and write test if it's necessary in this case. Just want to deliver this PR :)

**Comment by khmelevskii** [comment]
@Andarist any thoughts? Can my PR being in emotion?

**Comment by Andarist** [comment]
Well - I understand why you need this but I think it just has to be handled on your side. `@emotion/react` & `@emotion/styled` are mainly for JS users and while they can be used with clojure etc it's not up to those libraries to handle integration needs. It might look like a couple of extra lines that could easily be added but we need to consider also other aspects - like added complexity, bundlesize etc and this just won't be used at all by 99%+ of Emotion users so I don't think it's appropriate for us to support this.

**Comment by khmelevskii** [comment]
@Andarist yes, I understand that you don't want to add any additional code that not relevant for JS users. In general I agree with it thats why new option `shouldTransformProp` can potentially be useful for all users and semantically close to` shouldForwardProp`. For example, with help of this method users can sanitize or normalize values. Pretty useful in some rare cases.
About supporting additional code - agree. Hope I added not a lot of code in one file and it can be possible to support without a lot of efforts. If I can help with it on my side I would happy to do it.
Also, I'm happy to do this transformation on my side and currently I did it, but unfortunately it's not effective and I need to wrap each component to additional component where I transform props. With `shouldTransformProp` I will be able to transform props without this overhead.

**Comment by Andarist** [comment]
So far there have been no feature requests for changing props in any way - IMHO it's a sign that this is just not needed for JS users.

> I need to wrap each component to additional component where I transform props.

Isn't this true for basically any other function that you reuse from npm? You need to transform manually inputs and outputs so they conform to Clojure conventions.

**Comment by khmelevskii** [comment]
> So far there have been no feature requests for changing props in any way - IMHO it's a sign that this is just not needed for JS users.
Maybe you are right, maybe no :) If you add this function and document it, it's possible that JS users will use it. So, I think it's your call and I described everything what I could. From my side I can say only that I would like to have this function and hope that it can be useful for everybody, also impact to code base is small.

>Isn't this true for basically any other function that you reuse from npm? You need to transform manually inputs and outputs so they conform to Clojure conventions.
Within react components case it's a little bit another case, than just wrap function. With react component I have 2 component in react dev tools instead of single component, I need be careful with forwarding ref etc.

**Comment by Andarist** [comment]
Ye, I understand that it's more annoying with React components but it still is not enough of an argument for me to accept this change. I understand that this has not played out like you would have hoped and I'm sorry for that.

**Comment by khmelevskii** [comment]
@Andarist 
This is still issue for my library https://github.com/khmelevskii/emotion-cljs and as I can see for some of other cases too in JS world. Maybe it's possible to move forward with my PR? It's a few code lines. If it's possible I will check PR again write any tests which you want and do everything what you need to accept this PR.

**Comment by Andarist** [comment]
I understand why this might be frustrating to you but I don't see a reason to make such a change in a React-oriented library to aid other non-React systems. Especially given that workarounds can be used for this.

**Comment by khmelevskii** [comment]
Got it. What do you mean - "workarounds can be used for this"?
