### ISSUE TITLE
allow style based on parent with suffixed & expansion `.isLoading &`

### ISSUE THREAD

**Issue by zanona** [emotion-js/emotion#1894]
**The problem**

As we're focusing on isolated/contained styles, but sometimes we need to inflict changes to an element depending on its parent, so in this case:

```tsx
// BAD
<Parent css={[styles.parent,loading && styles.isParentLoading]}>
    <Child css={[styles.child, loading && styles.isChildLoading]}/>   
    .... [100 children]
   <Child css={styles.child}/>
</Parent>
```

It would be overkill updating the state of N number of children so it's best to leave this to the CSS engine to handle.
```tsx
// GOOD
<Parent className={loading && 'isLoading'} css={styles.parent}>
    <Child css={[styles.child]}/>   
    .... [100 children]
   <Child css={styles.child}/>
</Parent>
```

**Proposed solution**

A good way to cover this would be, allowing something like on Less.

```js
const styles = {
   parent: {...},
   child: {
      color: 'hotpink',
      '.isLoading &': { color: 'green' }
   }
};
```

**Alternative solutions**

At the moment we need to manually add a `className` for the children like so:
```tsx
<Parent css={[styles.parent, loading && style.parentIsLoading]}>
    <Child className='child' css={[styles.child]}/>   
    .... [100 children]
   <Child className='child' css={styles.child}/>
</Parent>

const styles = {
   parent: {...},
   parentIsLoading: { '.child': { color: 'green' }},
   child: { color: 'hotpink' }
};
```

Which is OK, however, we lose the feeling that we are styling a component in a contained way, where styles related to `Child` are derived from its `Parent` instead on itself.

**Additional context**

This has many other use cases such as `'.parent:hover &': { color: 'hotpink' }`

I guess the work involved would be generating selectors where  `.isLoading &` gets translated to `.isLoading .css-hash {...}`.

**Comment by Andarist** [comment]
This already works:
https://codesandbox.io/s/vigorous-lamarr-g6lob?file=/src/App.js

**Comment by zanona** [comment]
That's awesome! Thanks.
Would a PR be welcome for adding this info to https://github.com/emotion-js/emotion/blob/master/docs/nested.mdx?

**Comment by Andarist** [comment]
The second example there is pretty much the same, isn't it? It doesn't really matter if you put a class name, id, tag, attribute selector or anything else before `&`, as long as those things are "statically known".

**Comment by zanona** [comment]
That's true. Thanks @Andarist.
