### ISSUE TITLE
How to use Emotion with SWC + Webpack + React + Typescript

### ISSUE THREAD

**Issue by JonathanCa97** [emotion-js/emotion#1897]
I'm working on a React App (Typescript) that is compiled using SWC (https://github.com/swc-project/swc).
Everything works perfect, except for the css prop on an element. It converts the css to the className `[object object]`
I have set the JSX pragma but this does not seem to work
```javascript
/** @jsx jsx */
import { jsx } from '@emotion/core';
import * as React from 'react';

const Test = () => {
   return <div css={{ height: '50px', width: '50px', backgroundColor: 'red'}} />
}
```

My **.swcrc** file looks like this:
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    }
  }
}
```

My **webpack.config.js** file looks like this:
```javascript
const path = require('path');

module.exports = {
  entry: './src/index.tsx',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
    publicPath: '/',
  },
  module: {
    rules: [
      {
        test: /\.(js|ts|tsx)$/,
        exclude: /(node_modules)/,
        use: {
          // `.swcrc` can be used to configure swc
          loader: 'swc-loader',
        },
      },
    ],
  },
  resolve: {
    extensions: ['*', '.js', '.ts', '.tsx'],
    modules: [path.resolve(__dirname, './src'), 'node_modules'],
  },
  devServer: {
    contentBase: path.join(__dirname, 'public'),
    compress: true,
    port: 3000,
    historyApiFallback: true,
  },
};
```

Does anyone have an idea to get this working?

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by Andarist** [comment]
I've checked the compile output and this is it:
```js
"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _emotion_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @emotion/core */ "./node_modules/@emotion/core/dist/core.browser.esm.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! react */ "./node_modules/react/index.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_1__);
/* harmony import */ var react_dom__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! react-dom */ "./node_modules/react-dom/index.js");
/* harmony import */ var react_dom__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(react_dom__WEBPACK_IMPORTED_MODULE_2__);
/** @jsx jsx */



react_dom__WEBPACK_IMPORTED_MODULE_2__["render"](react__WEBPACK_IMPORTED_MODULE_1___default.a.createElement('div', {
    css: {
        backgroundColor: 'blue'
    }
}, 'test'), document.getElementById('root'));
```
As you might notice `jsx` has not been used here. I suspect this is some kind of a config problem or a general problem with SWC. I see that they should be honoring `@jsx` pragma as there is a test case for it in their repo:
https://github.com/swc-project/swc/blob/8615d69ac385979bc7a0bf5a49be5d8e87d3a8ec/ecmascript/transforms/src/react/jsx/tests.rs#L291

Maybe a version with support for this has not been released yet? Hard to tell. I would recommend asking about it in their issues.

I hope this helps you. Going to close this issue as there is no much more that we can help you here with that.

**Comment by JonathanCa97** [comment]
This was indeed a bug in SWC: https://github.com/swc-project/swc/issues/838. Thanks for helping !
