### ISSUE TITLE
Search background is transparent in website

### ISSUE THREAD

**Issue by ashikmeerankutty** [emotion-js/emotion#1904]
**Current behavior:**

Search background is transparent in the website

![image](https://user-images.githubusercontent.com/10515204/84686296-50c10a80-af59-11ea-8ea8-69b3b5ff5b9c.png)

**To reproduce:**

1. Got to the docs [website](https://emotion.sh/docs/introduction)
2. Click on the search bar

**Expected behavior:**

There must be a background for search dropdown

**Environment information:**

- `react` version:
- `emotion` version:

**Comment by Andarist** [comment]
I believe that I've fixed this in https://github.com/emotion-js/emotion/pull/1905 but if you could take a look if everything is working correctly I would highly appreciate it.

**Comment by ashikmeerankutty** [comment]
@Andarist Yes its working fine now. Thanks!
