### ISSUE TITLE
Large bundle size

### ISSUE THREAD

**Issue by morriq** [emotion-js/emotion#1907]
Hello, I'm using 'emotion' package with 'emotion-babel-plugin' and my bundle looks like this:

![image](https://user-images.githubusercontent.com/2962338/84787275-181f4080-afee-11ea-83c5-f45db28db1d8.png)

emotion stuff costs 40kb. I'm using webpack5 in production mode

I think it might be continuation of https://github.com/emotion-js/emotion/issues/646

**Comment by Andarist** [comment]
webpack-bundle-analyzer tends to be really inaccurate. For instance, from what I remember, it operates on webpack stats and might not account for some of the minification processes.

It all really matters on the used measuring technique. For example, bundlephobia reports 5.8kb min+gzipped with 15.4kb without gzip (just minified). As you can see the results are vastly different.

If you want to get more information about this topic and why webpack reports what it does then you would have to share your repo (or just a repro case) with me so I could inspect it and point out what's happening.

**Comment by morriq** [comment]
I deceided to use https://github.com/callstack/linaria

that way I achieved:

![image](https://user-images.githubusercontent.com/2962338/85009484-c6e28e80-b15e-11ea-8f0f-7cc6124e9299.png)
