### ISSUE TITLE
can extend StyleComponent in css style? 

### ISSUE THREAD

**Issue by wildfrontend** [emotion-js/emotion#1909]
example 

i create a style component

```js

const Input = styled.input`
    ...style 
`
```

and  another style component have nesting selector, i want the selector can extend style component sheet 
```js

const Field  = styled.div`
     label {
        ....
     }
    input {
          // extend Input component styled
    }
`
```

it is possible?

**Comment by Andarist** [comment]
When using our Babel plugin this is possible:
```js
const Input = styled.input``

const Field  = styled.div`
  label {}
  ${Input} {}
`
```

This is not advised though as might lead to specificity wars and breaks encapsulation, creates 2 sources of truth.

**Comment by wildfrontend** [comment]
look like not working

i want it can do this

```js
import { Field } from './emotion.js'

const App =() =>{
   return (
      <Field>
          <input /> // same style with Input 
      </Field>
   )
}

```

**Comment by Andarist** [comment]
Oh, if you want this then you should just do something like this:
```js
/** @jsx jsx */
import { jsx } from '@emotion/core
import { Field, inputStyles } from './emotion.js'

const App = () =>{
   return (
      <Field>
          <input css={inputStyles} />
      </Field>
   )
}
```

You need to somehow pass us those styles, we can't magically infer them from a random place.
