### ISSUE TITLE
useContext hooks to refactor @emotion/styled, too mutch consumer in chrome react extenstions

### ISSUE THREAD

**Issue by rainke** [emotion-js/emotion#1910]
**The problem**

Too mutch consumer in Chrome React extenstions, whitch makes it is hard to use

**Proposed solution**

use useContext hooks

**Comment by Andarist** [comment]
This is already implemented in v11, it's still in a beta version though - we hope to release it soon-ish, but we have very little time to move this forward lately. You can install it from npm though - it's available under the `next` tag and its docs can be found [here](https://deploy-preview-1600--emotion.netlify.app/docs/introduction).

**Comment by lunelson** [comment]
Related question: is there a way to turn off `ThemeProvider` and `ThemeConsumer` and avoid this overhead completely? I'd like to use CSS custom properties to implement this kind of dom-tree inheritance and not React Context...

**Comment by Andarist** [comment]
In v11 there won't be any `ThemeConsumer`s (there can be only `useTheme`) - do you see any extra ThemeProviders that you have not rendered yourself? I don't think there should be any in a browser but might have missed something.

**Comment by lunelson** [comment]
Thanks @Andarist for answering. To be clear: does this mean that they are really not being used (unless invoked in some way), or are they actually present but just being hidden from the React DevTools by using `useTheme` internally? 

I'm thinking in particular about the performance impacts of every single component subscribing to a theme `Context`. I noticed poor hydration performance in a recent Gatsby project with a large DOM using `styled-components` where I was implementing a [styled-system](https://styled-system.com/)-like approach, and then around the same time ran across [this (well-known, I think) article from Aggelos Arvanitakis](https://calendar.perfplanet.com/2019/the-unseen-performance-costs-of-css-in-js-in-react-apps/) and [this tweet from Jared Palmer](https://twitter.com/jaredpalmer/status/1271482711132254210). 

I was hoping to move away from using the `styled` API in favor of the `css` API in _emotion_, to avoid the invocation of any theme contexts, but I have the impression from reading the v11 docs that they are still being created...🤔

**Comment by Andarist** [comment]
> Thanks @Andarist for answering. To be clear: does this mean that they are really not being used (unless invoked in some way), or are they actually present but just being hidden from the React DevTools by using useTheme internally?

If you plan to only use `css` prop then `useTheme` would only be used under those circumstances:
https://github.com/emotion-js/emotion/blob/4d3b60d0d448a61d762ee150e6cb7a2c995ccc2f/packages/react/src/jsx.js#L47-L49

Keep in mind that just **reading** context which doesn't change (and in your case, it wouldn't as you don't plan to really utilize the builtin theming) is really cheap. Only updating the context value is usually costful.

The first article you have linked to is about `Context.Consumer`s - and that is quite a different story than `useContext`. The latter should be considerably cheaper.

**Comment by lunelson** [comment]
Thanks again @Andarist, I appreciate this clarification! It's nice to know that I can avoid the theme context if I want to, but also reserve it for special use-cases 👍 .
