### ISSUE TITLE
[SUPPORT] Multiple <style> tags in production mode

### ISSUE THREAD

**Issue by quadlayers** [emotion-js/emotion#1912]
Hello guys

Thanks for this amazing tool

I'm having an issue in the production and development mode

In the development mode when I update de styles of a component and this is re-rendered multiple styles <style> tags are included in the head for the same element

In production mode, this is not visible but the  unique <style> tag containers all the CSS generated over the loops

`export const {
  css
} = createEmotion({
  key: 'test-block'
})

class GenerateCSS extends Component {

  constructor() {
    super(...arguments);
  } 

  componentDidMount() {
    const {
      forwardRef
    } = this.props;

    if (
      forwardRef &&
      forwardRef.current
    ) {
      if (this.state.classCSS) {
        forwardRef.current.classList.add(css(//some css//));
      }
    }
  }

  componentDidUpdate(prevProps, prevState) {
    const {
      forwardRef
    } = this.props;
    if (
      forwardRef &&
      forwardRef.current
    ) {
        forwardRef.current.classList.remove(//remove previous class//);
        forwardRef.current.classList.add(css(//create some css//));
      }
  }

  render() {
    const {
      children
    } = this.props;

    return (
      children
    )
  }
}
`

**Comment by Andarist** [comment]
Hm, I'm not sure what the question is here exactly. By default, this is how Emotion works because it allows us to use source maps in development, but in the production using a single style element and CSSOM APIs is faster so we stick to it there. This can be controlled through `speedy` option though.

**Comment by quadlayers** [comment]
Hello @Andarist 
Thanks for your response
I've sorted this by creating my own cache
Thanks!
