### ISSUE TITLE
babel-plugin-emotion does not label components if `@babel/styled` is not imported directly

### ISSUE THREAD

**Issue by ambertino** [emotion-js/emotion#1914]
**Current behavior:**

`babel-plugin-emotion` does not label components if styled is not imported directly from `@emotion/styled`. Currently I do not import it directly since I use theme as described here:

https://emotion.sh/docs/typescript#define-a-theme

**To reproduce:**

Repro is below. Solid button is themed and has no label added while outlined does. Inspect the DOM via DevTools.

https://codesandbox.io/s/boring-cookies-q85vg

**Expected behavior:**

Should have label regardless of how `styled` is imported.

**Environment information:**

- `react`: ^16.12.0
- `@emotion/styled`: ^10.0.27
- `@emotion/babel-preset-css-prop`: ^10.0.27

**Comment by Andarist** [comment]
Babel operates on single files, if you don't use our standard imports we just don't know which imports are representing our APIs. However, in the upcoming v11 you will be able to tell us which ones should we treat as ours by using new `importMap` option: https://deploy-preview-1600--emotion.netlify.app/docs/@emotion/babel-plugin#importmap

**Comment by ambertino** [comment]
Thanks for the response @Andarist. Looking forward for v11

**Comment by ambertino** [comment]
Also, will that be possible to export it as a part of a property of default export? I.e. something like this:
```js
export default {
  ...utils,
  styled: styled as CreateStyled<Theme>
}
```

**Comment by Andarist** [comment]
No, we haven't designed the `importMap` to support something like this and I doubt we'd like to add support for this.

Keep in mind that with v11 there won't be much need to use `CreateStyled` as you will be able to just augment the builtin interface. This is described here: https://deploy-preview-1600--emotion.netlify.app/docs/typescript#define-a-theme

**Comment by ambertino** [comment]
Ok, thanks @Andarist! Good thing about `CreateStyled` is that you can make the `Theme` type out if object:
```
const theme = {...}
type Theme = typeof theme;
```
Anyway, thanks for you comments @Andarist! Appreciate it!
