### ISSUE TITLE
[SUPPORT] How to remove specific style injected by insertStyles

### ISSUE THREAD

**Issue by quadlayers** [emotion-js/emotion#1915]
Hello guys

I'm running into an issue with a component that allows users to customize its css properties

The component uses ClassNames. The issue is that the generated CSS is not overwritten, its included over and over.

`
this will be rendered many times to display user style changes
return (
      <ClassNames>
        {({ css }) => {
          let styles = createCSS(attributes);
          props.classCSS = styles && css(styles);
              return children(props);
        }}
      </ClassNames>
    )`

So, when the user updates the attributes, new CSS is inserted and class updated.

I need a way to remove the previous generated CSS because I took this via js to save it and display in frontend

Is this possible?

**Comment by Andarist** [comment]
This is currently not possible as Emotion relies heavily on caching. For fast-changing styles, it is advised to use `style` prop over Emotion styles. 

**Disclaimer:** Well... actually this can be built with custom sheets and flushing them, but this would involve a considerable effort and I would not recommend doing this because gains are questionable at best.

**Comment by quadlayers** [comment]
Hello @Andarist 

I understand but I need this to be done through ClassNames because the generated CSS will be saved and used in the frontend

I find the way to record previously generated className via state and I was able to delete it via

`delete cache.registered[prevState.classCSS]
`
This will allow me to get the CSS from cache.registered and save it

But I'm concerned about performance issues: Also in production mode, all styles al included in the node element

This could easily grow up to 1mb -> https://snipboard.io/j84UPo.jpg

**Comment by Andarist** [comment]
Could u describe your whole use case in more detail?

**Comment by quadlayers** [comment]
We've sorted this by creating our own cache

Thanks for your help!
