### ISSUE TITLE
[SUPPORT] re-render when composition

### ISSUE THREAD

**Issue by doong-jo** [emotion-js/emotion#1916]
I think using the array in the code below can cause unnecessary re-rendering in the composition. This is because React re-renders the component with a shallow comparison and in the example below we are putting a new array reference in the prop. 

What do you think?

```javascript
/** @jsx jsx */
import { css, jsx } from '@emotion/core'

const danger = css`
  color: red;
`

const base = css`
  background-color: darkgreen;
  color: turquoise;
`

render(
  <div>
    <div css={base}>This will be turquoise</div>
    <div css={[danger, base]}>
      This will be also be turquoise since the base styles
      overwrite the danger styles.
    </div>
    <div css={[base, danger]}>This will be red</div>
  </div>
)
```

so..to-be is

```javascript
/** @jsx jsx */
import { css, jsx } from '@emotion/core'
import { useMemo } from 'react';

const danger = css`
  color: red;
`

const base = css`
  background-color: darkgreen;
  color: turquoise;
`
const combinedStyle = useMemo(() => [base, danger], [base, danger]);

render(
  <div>
    <div css={base}>This will be turquoise</div>
    // <div css={[base, danger]}>This will be red</div>
    <div css={combinedStyle}>This will be red</div>
  </div>
)
```

Therefore, I have also created related package.
https://www.npmjs.com/package/emotion-injector

**Comment by Andarist** [comment]
This literally doesn't matter for host components. They are going to be reevaluated anyway. For composite components - if this matters to you then you should just `React.memo` your inner component which should help to avoid some extra rerenders.

**Comment by doong-jo** [comment]
Thanks your answer.
