### ISSUE TITLE
Colors matters for docs - please provide option to turn them on

### ISSUE THREAD

**Issue by jinalskothari** [emotion-js/emotion#1918]
**Please restore colors on doc site**
It is difficult to grasp some of the examples on the docs without the colors. 

**Proposed solution**
Please consider providing a means to turn the color back on. A simple button on the banner. Alternatively have

**Additional context**
This is only about the utility of the docs.

**Comment by TheZano** [comment]
agree.. please this is no offense :(

**Comment by dilvermg** [comment]
for a beginner it is very confusing to see everything in one color u.u

why don't they do the same as styled-components with their documentation?

**Comment by Andarist** [comment]
Thank you for the raised concerns - I've removed this grayscale filter from our docs. Hope this makes the docs more approachable and accessible again.
