### ISSUE TITLE
Can't get importMapping to work on package that wraps @emotion/styled

### ISSUE THREAD

**Issue by TheSisb** [emotion-js/emotion#1932]
**Current behavior:**

I'm currently wrapping emotion in my own package and installing that in a new project, but I'm unable to use component selectors.

I'm getting the following error: `Error: Component selectors can only be used in conjunction with babel-plugin-emotion.`

**To reproduce:**

Repro here: https://codesandbox.io/s/nesting-styleds-jrdvo

If you remove this block of code it works just fine, but I'm limited to using emotion without descendant selectors. I'd like to fix that.
![image](https://user-images.githubusercontent.com/1592327/87571382-94f61680-c68f-11ea-86cc-c2ff1fb67494.png)

**Expected behavior:**

No error, component selector functionality is enabled.

**Environment information:**

`@twilio-paste/styling-library` is a wrapper around:

```
"@emotion/core": "10.0.28",
"@emotion/styled": "10.0.27",
"emotion": "10.0.27",
"emotion-theming": "^10.0.27",
```

peerDeps
```
"react": "^16.8.6",
"react-dom": "^16.8.6"
```

**Comment by Andarist** [comment]
The `importMap` option is only available in the upcoming v11 - you are using v10 in this codesandbox.
