### ISSUE TITLE
Source maps in Firefox

### ISSUE THREAD

**Issue by webegguk** [emotion-js/emotion#1933]
I'm really excited about emotion features over other css-in-js solutions mainly because of the tracable elements like labels to give some semantics and sourcemaps (I don't know how people manage without them). All works as expected in Chrome however I am also an avid Firefox advocate where the sourcemap feature doesn't work. Is this the same for anyone else or am I missing something?

It's in development env (I understand it should only be turned on here).

- react 16.8.2
- @emotion/core 10.0.28

**Comment by Andarist** [comment]
It's a bug in FF which got already fixed in Nightly. Not sure when it will be released in a stable version though.

**Comment by Andarist** [comment]
The issue has been answered. Closing because the OP has not responded back.

**Comment by webegguk** [comment]
Thank you for the answer, I have just noticed source mapping now works since updating to Firefox v79 and I'll be using emotion on my next project for sure.
