### ISSUE TITLE
Pseudo element is invalid, hope to add warning

### ISSUE THREAD

**Issue by okboy5555** [emotion-js/emotion#1940]
**Current behavior**
No warning
No pseudo elements are actually created
I am very troubled because I used it for the first time
https://github.com/emotion-js/emotion/issues/1869
After a period of inquiries, I solved it, but I hope to add a warning message

**To reproduce**:
```
const myRadio = css({
    display: 'none',
    '&:checked+ .myRadioInput:after': {
        backgroundColor: '#7ebcff',
        borderRadius: '100%',
        content: '',
        display: 'inline-block',
        height: '12px',
        margin: '2px',
        width: '12px',
    }
  })
```
**Expected behavior**
![image](https://user-images.githubusercontent.com/29430497/88161563-b8e2ca80-cc42-11ea-8e7a-3e72d55f85df.png)

**Environment information:**

`"@emotion/core": "^10.0.27",`

**Comment by Andarist** [comment]
You have been told where the problem is and how you should fix it in that error message. Just apply this change
```diff
const myRadio = css({
    display: 'none',
    '&:checked+ .myRadioInput:after': {
        backgroundColor: '#7ebcff',
        borderRadius: '100%',
-        content: '',
+        content: '""',
        display: 'inline-block',
        height: '12px',
        margin: '2px',
        width: '12px',
    }
  })
```
