### ISSUE TITLE
It is possible to use a PostCSS plugin ?

### ISSUE THREAD

**Issue by wyeo** [emotion-js/emotion#1944]
Hello 👋🏿
I just want to know if it's possible to use additional plugin of PostCSS to combine with `autoprefixer` with Emotion

Why i am asking ? Because i found this usefull [plugin](https://github.com/postcss/postcss-100vh-fix) and i want to use it with emotion

Thanks

**Comment by Andarist** [comment]
No - it's not possible. PostCSS is a build-time tool, whereas Emotion works at runtime (with some build-time optimizations possible). 

You could write a Stylis plugin though - it's the parser that we are using under the hood and it has a plugin system.
