### ISSUE TITLE
Explain the performance differences between Vanilla Emotion and React Emotion

### ISSUE THREAD

**Issue by dfernandez-asapp** [emotion-js/emotion#1946]
**Description:**

The introduction describes the differences between React Emotion and Vanilla Emotion.

It brings the benefits: zero SSR config, and out of the box theming support. But it doesn't say if there is any performance impact.

That information will be helpful when picking Emotion over other frameworks. I prefer to manually set up SSR and do the theming by myself (the React Context API makes custom theming a low effort), but I'm not sure if there are other implications by choosing Vanilla Emotion over React Emotion. 

Some clarifications about performance of React vs Vanilla in the comparison section will help others to choose the framework.

**Documentation links:**

https://emotion.sh/docs/introduction#react

**Comment by Andarist** [comment]
I dont have any real data but my intuition tells me that React Emotion has a better startup time than Vanilla Emotion because it can perform more work **lazily**.

**Comment by Andarist** [comment]
We don't have real data regarding this - theoretically, the difference should really be negligible and this goes into the micro-optimization territory. I think the choice should be made purely based on a feature set and tradeoffs and no on the performance as the performance should be comparable - most of the implementation is shared between both.
