### ISSUE TITLE
Support Babel React Automatic Runtime

### ISSUE THREAD

**Issue by jknight12882** [emotion-js/emotion#1957]
**The problem**

Starting with `babel@8.x.x`, babel will have a new runtime for transforming jsx https://babeljs.io/docs/en/babel-plugin-transform-react-jsx/#react-automatic-runtime. This is available for use since `babel@7.9.0`

**Comment by Andarist** [comment]
We are aware of this - I've been watching the PR introducing it before it got merged in. I think we'll be able to switch to this and thus deprecate `@emotion/babel-preset-css-prop`, but we are waiting for the TS team to implement support for this. We want to have both in place so we can properly evaluate our defaults, recommendations and such. So I'm going to close this issue right now as it's not immediately actionable from our PoV, but just know that we are watching this matter closely.
