### ISSUE TITLE
The jest snapshot serializer is failing to properly replace hashed classnames.

### ISSUE THREAD

**Issue by vorillaz** [emotion-js/emotion#1960]
**Current behavior:**

The `jest-emotion` snapshot serializer is failing to properly replace the generated class names when styling gets generated from the passed props.

**To reproduce:**
You can find a [CodeSandbox](https://codesandbox.io/s/emotion-issue-template-ju60p?file=/src/index.test.js) replicating the bug. Since snapshots can't get generated properly though CodeSandbox you have to download the `zip` file

The bug can also get easily reproduced as follows:
1. Create a dummy component that it's styling is generated through prop passing.
```jsx
const Box = styled.div`
  ${({ colored }) => {
    if (colored) {
      return {
        color: "red",
      };
    }
  }}
`;
```
2. Setup `jest-emotion` snapshot serializer as described in [docs](https://www.npmjs.com/package/jest-emotion)
3. Create two new tests with Jest snapshot checking:
```jsx
import React from "react";
import { render } from "@testing-library/react";
import styled from "@emotion/styled/macro";
import Box from "./box";

const Failing = styled.div``;

test("Failing is failing ¯\_(ツ)_/¯", () => {
	const { container } = render(<Failing />);
	expect(container).toMatchSnapshot();
});

test("Box without props is failing badly", () => {
	const { container } = render(<Box />);
	expect(container).toMatchSnapshot();
});

test("Box with props is passing", () => {
	const { container } = render(<Box truncated />);
	expect(container).toMatchSnapshot(``);
});
```

**Expected behavior:**

The snapshots are failing as the generated classnames are not properly replaced from the serializer, eg:
```html
<div>
  <div
    class="css-1efsrtw-Box emotion-0"
  />
</div>
```

**Environment information:**

- `react` version: `16.8.6`
- `emotion` version: `10.0.10` and `11.0.0-next.12`

**Comment by Andarist** [comment]
It's not that this is not being replaced correctly when styling is generated based on props or not but rather it fails if you want to snapshot a component without styles, for example
```js
styles.div``
```
**without** rendering a component with styles first.

So given your repro case (thanks for that!), this doesn't work:
```js
test("Box without props is failing", () => {
  const { container } = render(<Box />);
  expect(container).toMatchSnapshot();
});

test("Box with props is passing", () => {
  const { container } = render(<Box truncated />);
  expect(container).toMatchSnapshot();
});
```

but this does work:
```js
test("Box with props is passing", () => {
  const { container } = render(<Box truncated />);
  expect(container).toMatchSnapshot();
});

test("Box without props is failing", () => {
  const { container } = render(<Box />);
  expect(container).toMatchSnapshot();
});
```

It happens because we need style elements to be injected to a JSDOM document for our style extraction logic to work (and class name replacing), but we don't inject any style elements until you actually give us some styles to inject.

This really seems like a harmless edge case, so I would rather like to not "fix" it.

**Comment by vorillaz** [comment]
Hey @Andarist thanks for the reply, it's a bit weird in my case that we need to ensure the order of our specs and make them work as expected.
While this might not seem like a big deal we are heavily affected by this scenario as we are incorporating `styled-system` a lot for optional styling and we are asserting HTML properties through snapshot testing.

Is there any chance I could manually solve this one by injecting a dummy `style` element when Jest kicks in?

**Comment by vorillaz** [comment]
Apparently the fix was pretty easy. 
I added a snippet to my `jest/setup.js` 

```js
beforeAll(() => {
  document.head.insertAdjacentHTML(
    'beforeend',
    `<style data-id="jest-emotion-setup" data-emotion="css"></style>`
  );
});
```

**Comment by Andarist** [comment]
Right - I was about to propose something like that. And I think I might even introduce a dev-only code to insert something like this automatically to the document - this would help cases like yours without any hacks on your side.

**Comment by vorillaz** [comment]
Exactly, thanks a lot for your help :)

**Comment by Andarist** [comment]
I've opened a PR for this: https://github.com/emotion-js/emotion/pull/1962
