### ISSUE TITLE
NPM Package down?

### ISSUE THREAD

**Issue by riccardolardi** [emotion-js/emotion#1961]
[https://www.npmjs.com/package/@emotion/stylis](https://www.npmjs.com/package/@emotion/stylis) timing out... this is breaking my dependency chain. Any hint on this?

**Comment by dcoxall** [comment]
I'm getting the same issue with `@emotion/memoize` which is now blocking builds for us. NPM is returning a 404 on `https://registry.npmjs.org/@emotion/memoize/-/memoize-0.7.4.tgz`

**Comment by voidale** [comment]
https://status.npmjs.org/

**Comment by bmtdh** [comment]
Also experiencing this for this package, preventing application deployments at present

**Comment by riccardolardi** [comment]
@dcoxall @voidale thanks I hope it's fixed soon

**Comment by Andarist** [comment]
Closing this issue as it's not caused by us. Please track the linked npm's status page to check when this gets resolved.
