### ISSUE TITLE
removeChild of null

### ISSUE THREAD

**Issue by artjoms-faltins** [emotion-js/emotion#1968]
`tag.parentNode` can be `null` which throws unhandled exception
https://github.com/emotion-js/emotion/blob/a836d31e3fb5f143942e41a2eb5dd8f79feb5417/packages/sheet/src/index.js#L139

**Comment by Andarist** [comment]
When it can be null? Or tags should be attached to the DOM.

**Comment by Andarist** [comment]
A runnable repro case has not been provided. I'm going to close this issue for housekeeping purposes as I must assume this is not a problem anymore. If you manage to create a repro case then please open a new issue with the repro case attached to it.
