### ISSUE TITLE
upgrade from styled@11.0.0-next.12 > styled@11.0.0-next.13 causes bery long TSC compile

### ISSUE THREAD

**Issue by isaac-martin** [emotion-js/emotion#1972]
upgrade from styled@11.0.0-next.12 > styled@11.0.0-next.13 causes a large increase in TS compilation time.
On one repo it is from 20 seconds to about 2 minutes

Sorry I can't get a reproducible repo - ours is all private.

typecheck diagnostics `next.12`
![image](https://user-images.githubusercontent.com/8649366/90181514-91cd7380-dd7e-11ea-8462-67ca8fa3e3f8.png)

typecheck diagnostics `next.13`

![image](https://user-images.githubusercontent.com/8649366/90183280-3badff80-dd81-11ea-9622-e5d571b4c248.png)

The biggest difference in here is the Instantiations from `659363` on 12 to `2085227` on 13

Diff for PR i just merged to roll back to 12 from 13. 
![image](https://user-images.githubusercontent.com/8649366/90182050-5bdcbf00-dd7f-11ea-8e7e-2e705c62d1ea.png)

I believe its probably related to this release. 
https://github.com/emotion-js/emotion/commit/9e998e3755c217027ad1be0af4c64644fe14c6bf

Let me know if I can do anything to help debug this

**Comment by Andarist** [comment]
Thanks for the report! And at the same time, I'm really sorry about hearing that. This definitely doesn't sound right and we have every intention of improving the situation.

The problem here is that I don't really see any potential of such regressions between `.12` and `.13` prereleases 🤔 Would u maybe be willing to jump into the call with me to talk this through and experiment with a bunch of stuff?

**Comment by isaac-martin** [comment]
yeah i can do that - I'm about to finish for the day, but am available tomorrow.

**Comment by Andarist** [comment]
Won't be able to schedule anything for tomorrow - but I'm open to next week's meetings. Could you reach out to me on Slack or via Twitter so we could discuss this via DMs?

**Comment by Andarist** [comment]
After talking with @isaac-martin  - the problem has disappeared after upgrading to `.15`. Not exactly sure why as we haven't investigated it but I have a hunch that it might be related to https://github.com/emotion-js/emotion/issues/1974 . It's not worth investigating this further though as the problem doesn't occur any longer.
