### ISSUE TITLE
`ref` prop missing in `@emotion/styled` in Emotion 11

### ISSUE THREAD

**Issue by RoystonS** [emotion-js/emotion#1987]
**Current behavior:**

The `ref` property doesn't appear in the typing for styled components with Emotion 11.

That causes this error when compiling with TypeScript and attempting to provide a `ref` prop:
```
 Property 'ref' does not exist on type 'IntrinsicAttributes & Pick<FixedSizeGridProps, "columnCount" | "columnWidth" | "height" | "width" | "children" | "itemKey" | "overscanCount" | ... 16 more ... | "rowCount"> & Partial<...> & Partial<...> & { ...; } & { ...; }'.
```

(This may be related to issue #1942 which was for `@emotion/native`?)

**To reproduce:**

Basically, use `styled` to style a component:
```
const MyStyledComponent = styled(MyComponent)({
  background: "pink"
});
```
then use it with a `ref` prop:
```
  <MyStyledComponent ref={ref2} message="MyStyledComponent" />
```

Here's a CodeSandbox illustrating the issue:
https://codesandbox.io/s/emotion-11-ref-issue-wi5dt?file=/src/index.tsx

**Expected behavior:**

Wrapping a component with `styled` should not remove the typing for the `ref` prop.

**Environment information:**

- `react` version: 16.13.1
- `emotion` version: 11.0.0-next.15

**Comment by Andarist** [comment]
Yes, this looks very similar to the issue regarding `@emotion/native` - my bet is the issue is the same. 

Question: why do u want to access a ref of a class component?

**Comment by RoystonS** [comment]
In the actual use-case in our full codebase we're using the third-party `react-window` library and that has a `FixedSizeList` class component which exposes a `scrollTo` method which we need to be able to call, sadly.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-window/index.d.ts#L375

**Comment by Andarist** [comment]
Thank you for sharing - the problem is that `ref` is not part of the props of your component. It's part of the global `JSX.IntrinsicClassAttributes` which is an extension used when type-checking JSX-created elements (`<MyClass ref={() => {}}/>`). We can't test if a received component is a class though and we could add support for `ref` that way - gonna discuss this with @JakeGinnivan some time this week (hopefully).

**Comment by RoystonS** [comment]
Thanks. So this is only an issue with class components?

**Comment by Andarist** [comment]
Yes, i believe so. We have type tests for other component types and it works fine.
