### ISSUE TITLE
TypeScript definition of `EmotionCache` has `stylis` function but no `insert` function

### ISSUE THREAD

**Issue by RoystonS** [emotion-js/emotion#1990]
**Current behavior:**

The TypeScript typings for `EmotionCache` contain a method (`stylis`) that isn't actually present, and are missing an important one (`insert`) that is.

**To reproduce:**

Flow typings: https://github.com/emotion-js/emotion/blob/next/packages/utils/src/types.js#L22
TypeScript typings: https://github.com/emotion-js/emotion/blob/next/packages/utils/types/index.d.ts#L18

**Expected behavior:**

The TypeScript typings should match the Flow ones and reality.

**Environment information:**

- `emotion` version: `@emotion/utils 1.0.0-next.0`

**Comment by Andarist** [comment]
Good catch - this was available in some v10 betas (https://github.com/emotion-js/emotion/blob/2a9a1b8c4e2109fc483ebf2d808b26cdcc11ae93/packages/cache/src/index.js#L88) but it has been removed since then. Would you like to prepare a PR fixing this or should we take care of this?

**Comment by RoystonS** [comment]
I thought I was going to need to use `insert` but it turns I don't.  (I've got some code that needs to generate CSS using the same stylis plugins that Emotion has, but I don't seem to be able to get Emotion to do that for me so I'm doing a separate Stylis run.)

I'll chuck a PR together for this little change.

**Comment by Andarist** [comment]
Got fixed in https://github.com/emotion-js/emotion/pull/1999
