### ISSUE TITLE
Typescript warning on the "as" property in Emotion V11

### ISSUE THREAD

**Issue by Rolchau** [emotion-js/emotion#1992]
**Current behavior:**
I am getting a Typescript error when using the "as" attribute on a element: 
`Type '{ as: string; }' is not assignable to type 'IntrinsicAttributes & { theme?: any; } & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & { ...; }'.
  Property 'as' does not exist on type 'IntrinsicAttributes & { theme?: any; } & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & { ...; }'`

**To reproduce:**
Following code reproduces it: 
```
import React from 'react';
import styled from '@emotion/styled';

const Test = styled.div`color: red;`;
const TestComp = (): JSX.Element => <Test as="p"></Test>;
```

**Expected behavior:**
To not get any TS errors when using the "as" attribute like that - or am I missing something here?

**Environment information:**

- `react` version: 16.9.35
- `@emotion/styled` version: 11.0.0-next.15
- `typescript` version: 3.9.3

**Comment by Andarist** [comment]
Thank you for the report - this was an oversight on our part, I've prepared a fix for this here: https://github.com/emotion-js/emotion/pull/1995

**Comment by Andarist** [comment]
The fixing PR has been merged - gonna close the issue now, we hope to release a new prerelease version in the following week.
