### ISSUE TITLE
[babel-plugin] Component name in className dosnt work when use CreateStyled

### ISSUE THREAD

**Issue by Erwin0917** [emotion-js/emotion#2001]
**Current behavior:**
When extend EmotionTheme via CreateStyled plugin doesn't add an correct className. ClassName is like without plug => class="css-t0lbh8" instead class="css-t0lbh8-MyComponentName"
I styled files I import styled from my own config file. When i import from "@emotion/styled" plugin works correct.

**Expected behavior:**

Plugin search for all styled files.

**Environment information:**

- `react` version: 16.13.0
- `emotion` version: 10.0.27

**Comment by Andarist** [comment]
The feature allowing for that has been implemented here: https://github.com/emotion-js/emotion/pull/1220 . It's already released in our v11 prereleases (available on npm) - there are no plans to ship this in v10. Please try out the v11 or just wait until we ship it as latest on npm.
