### ISSUE TITLE
Emotion 11 mangles selectors when mixing pseudo-elements and media queries

### ISSUE THREAD

**Issue by RoystonS** [emotion-js/emotion#2002]
**Current behavior:**

If we have a pseudo-element such as `::before` (or `dialog`'s `::backdrop`) and attempt to style it using media queries, the generated CSS selector is incorrect.  It worked fine with Emotion 10.

A little code:
```
const MyControl = styled.div({
  "::before": {
    content: '"::before content"',
    background: "pink",
    "@media screen and (max-width: 800px)": {
      background: "cyan"
    }
  }
});
```

This is the CSS that Emotion 10 generates with that input:
```
.css-z60a1g::before{content:"::before content";background:pink;}
@media screen and (max-width:800px){.css-z60a1g::before{background:cyan;}}
```

This is the CSS that Emotion 11 generates with that input:
```
.css-z60a1g::before{content:"::before content";background:pink;}
@media screen and (max-width: 800px){.css-z60a1g::before::before{background:cyan;}}
```
(Note the doubled-up `::before` selector.)

This then fails to apply the style correctly because it's attempting to target the 'before' pseudo element of the before pseudo 
element.

**To reproduce:**

Here's the above code running in CodeSandbox:

- Emotion 10: https://codesandbox.io/s/emotion-10-pseudo-media-query-busww?file=/src/index.tsx
- Emotion 11: https://codesandbox.io/s/emotion-11-pseudo-media-query-issue-1e80z?file=/src/index.tsx

If you make the screen narrower it should trigger the media query into making the background cyan rather than pink.  That only works on Emotion 10.

This is a cut-down example and not the same use case we found:  we first noticed this when our Visual Regression tests spotted an issue with our `dialog` `::backdrop` styling not working with print media queries.  But that's a little trickier to reproduce and diagnose.  Using `::before` demonstrates the issue more easily.

**Expected behavior:**

It should generate a correct CSS selector as Emotion 10 did.

**Environment information:**

- `react` version: 16.13.1
- `emotion` version: 11.0.0-next.15

**Comment by RoystonS** [comment]
It's actually slightly worse than this.  Our original code that found this problem looks like this:

```javascript
styled.dialog({
  '::backdrop, & + .backdrop': {
    backgroundColor: 'grey',
      '@media print': {
        display: 'none'
      }
    }
})
```

(We're targeting both `::backdrop` and the adjacent `.backdrop` selector because we're using the polyfill for the `dialog` element.)

That gets turned into
```
.cache-abdskw::backdrop,.cache-abdskw+.backdrop{background-color:grey;}
@media print{.cache-abdskw::backdrop::backdrop,.cache-abdskw+.backdrop::backdrop{display:none;}}
```
i.e. `::backdrop` is added **both** to the actual `::backdrop` pseudo-element selector and the other `.backdrop` selector.

**Comment by RoystonS** [comment]
I think it's an issue in Emotion 11's `compat` stylist plugin?  At the `@media` phase of the Stylis plugin execution the selectors look fine, but the `compat` plugin is changing them during the `rule` phase to add in the extraneous pseudos.

**Comment by Andarist** [comment]
Thanks for the detailed repro and being an active early adopter of the v11! This truly helps us a lot - I will investigate this soon. Your diagnosis about the compat plugin not handling those cases correctly seems very probable.

**Comment by RoystonS** [comment]
No problem.  We're still stuck on TypeScript 3.7 and are very keen to upgrade to 3.9/4.0, but that's somewhat blocked on the fixed types in Emotion 11 so my hands are a little tied.   I couldn't quite tell what the `compat` plugin is actually attempting to do (and there don't appear to be tests for it) otherwise I would have had a go at fixing it.

**Comment by Andarist** [comment]
The fix is on the way: https://github.com/emotion-js/emotion/pull/2003 .

> I couldn't quite tell what the compat plugin is actually attempting to do (and there don't appear to be tests for it) otherwise I would have had a go at fixing it.

There are: https://github.com/emotion-js/emotion/blob/debaad9ab4bd6c80312092826d9146f3d29c0899/packages/css/test/selectivity.test.js#L122-L211
They are just no unit tests so they are less discoverable here. Basically it brings back support for those orphaned pseudos because they have always had `&` implicitly prepended to them in Emotion, Styled-Components, and others. This was a mistake~ on Stylis part and as it has been fixed in Stylis 4 - we could have made it a breaking change for us as well (we would require writing `&:hover` instead of `:hover`) or bring back old semantics with a Stylis plugin. Given possible churn in the community for such a change, we have gone with the second option for now.

**Comment by RoystonS** [comment]
Lovely - thanks so much for the super-fast turnaround!  Would it be possible to get that into a release?

Ah, I get the point of `compat` now.  Yes I had indeed wondered as I was looking through our problematic selector `::backdrop, & + .backdrop` why it wasn't `&::backdrop, & + .backdrop`.  It does _kinda_ make sense to bind `:foo` and `::foo` pseudos to the current element as you'd very rarely want it to map to ':foo' elements _inside_ the current one, but it isn't necessary and isn't consistent. I presume writing `&::backdrop` is actually legal though?

**Comment by Andarist** [comment]
>  I presume writing &::backdrop is actually legal though?

Totally legal and I would consider it to be preferred - it's consistent with Less/Sass etc.

**Comment by RoystonS** [comment]
Great stuff.  I've just arranged to patch our local version with your fix, and those failing visual regression tests do now pass.  Thank you!
