### ISSUE TITLE
[SUPPORT] Why <style> tag appears in the middle of an element and disappear again?

### ISSUE THREAD

**Issue by Munkyu-Yang** [emotion-js/emotion#2004]
Hi, I can't find any resources about this, that why <style> tag appears in an element during the rendering and disappears again after then?
Can anyone explain it to me why this happens??

![image](https://user-images.githubusercontent.com/66347060/92440561-abc86d80-f1e7-11ea-8e18-564f71d7d21c.png)
![image](https://user-images.githubusercontent.com/66347060/92440601-b7b42f80-f1e7-11ea-869e-73015563f14a.png)

**Comment by Andarist** [comment]
You are probably seeing SSRed styles that are moved to the `<head/>` at runtime.

**Comment by Munkyu-Yang** [comment]
But how come the style tags put into the body tag during SSR, during the head time?

**Comment by Andarist** [comment]
They are conditionally rendered inline on the server:
https://github.com/emotion-js/emotion/blob/c85378a204613885a356eaba1480c5151838c458/packages/core/src/jsx.js#L75-L95

**Comment by Munkyu-Yang** [comment]
I see, thank you.
So is there a benefit for adding a style tag next to the JSX elements during SSR, compared to add it to the head tag?

**Comment by Andarist** [comment]
Yes - it's a single render pass, it doesn't need an after-render extraction. Therefore the response can be streamed to the client.

**Comment by Andarist** [comment]
I hope this has answered question questions so I'm going to close this issue. Feel free to continue asking if you still are curious about some things - I will try to do my best to answer any questions.

**Comment by moonformeli** [comment]
@Andarist Thanks for your time! 💯
