### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop. - Check the top-level render call using <EmotionCssPropInternal>.

### ISSUE THREAD

**Issue by Vadorequest** [emotion-js/emotion#2005]
**Current behavior:**

I'm getting this warning message after upgrading from `@emotion/core": "10.0.28` to @emotion/core": "10.0.35.

```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <EmotionCssPropInternal>. See https://fb.me/react-warning-keys for more information.
    in ProductRow (at Products.tsx:37)
    in Products (at AllProducts.tsx:22)
    in Fragment
    in AllProducts (at example-with-ssg.tsx:107)
    in div
    in Container (at example-with-ssg.tsx:68)
    in div (at DefaultPageContainer.tsx:147)
    in div
    in Fragment
    in Context.Provider
    in BasicProvider
    in Context.Consumer
    in EmotionCssPropInternal (at DefaultPageContainer.tsx:56)
    in DefaultPageContainer (at DefaultLayout.tsx:113)
    in div (at DefaultLayout.tsx:96)
    in Amplitude (at DefaultLayout.tsx:65)
    in DefaultLayout (at example-with-ssg.tsx:60)
    in ExampleWithSSGPage (at ServerPageBootstrap.tsx:47)
    in Context.Provider (at ServerPageBootstrap.tsx:46)
    in ServerPageBootstrap (at MultiversalAppBootstrap.tsx:194)
    in Context.Provider
    in Context.Consumer
    in ThemeProvider (at MultiversalAppBootstrap.tsx:187)
    in Context.Provider (at MultiversalAppBootstrap.tsx:183)
    in Context.Provider (at MultiversalAppBootstrap.tsx:182)
    in Context.Provider (at MultiversalAppBootstrap.tsx:181)
    in MultiversalAppBootstrap (at _app.tsx:98)
    in MultiversalPageEntryPoint
    in Unknown
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in AppContainer

```

![image](https://user-images.githubusercontent.com/3807458/92449101-d6033680-f1b9-11ea-952c-be14f59737dd.png)

Products.tsx:
https://github.com/UnlyEd/next-right-now/blob/30a804e6a130eb7d511e8771eba54079ccd8fcce/src/components/data/Products.tsx#L31

ProductRow.tsx
https://github.com/UnlyEd/next-right-now/blob/d78c9b2fe9c2b2a3ce4ac2661cecc5c261d29a37/src/components/data/ProductRow.tsx#L21

Clearly, the `key` is defined (value is `2`) so it doesn't seem to come from my own code.

**To reproduce:**

Error can be seen at http://localhost:8888/en/examples/native-features/example-with-ssg in the browser console

To install the project locally, do:
1. `git clone https://github.com/UnlyEd/next-right-now.git nrn-quick-start`
1. `cd nrn-quick-start && git checkout upgrade-deps`
1. `yarn`
1. `yarn start`
1. Open `http://localhost:8888/en/examples/native-features/example-with-ssg`
 

**Expected behavior:**

Shouldn't warn.

**Environment information:**

- `react` version: "react": "16.13.1",
- `emotion` version:
    "@emotion/core": "10.0.35",
    "@emotion/styled": "10.0.27",

**Comment by Andarist** [comment]
Thank you for the repro case but it is not runnable on its own - some JSON cannot be fetched from airtable because my env variables are not populated correctly for this project. Please provide some sample ones for me so I can debug this.

**Comment by Vadorequest** [comment]
@Andarist THanks for looking into this.

Oh, I missed the step where you need to copy the example config file, before starting the server:
- `cp .env.local.example .env.local`

Regarding the console.log, that's what I did on the screenshot. Below the error is the `product` printed.

**Comment by Andarist** [comment]
`.env.local.example` has empty entries such as `AIRTABLE_BASE_ID` and it still doesn't work out of the box when I copy this file.

> Regarding the console.log, that's what I did on the screenshot. Below the error is the product printed.

If your log is **below** the error then this log is not really related to that error. Correctly, placed log should be listed **before** the error. The error message also tells you to check out the render method of `Products` - where I can see that you are iterating through some airtable without setting `key` properly on the `ProductRow` component:
https://github.com/UnlyEd/next-right-now/blob/d78c9b2fe9c2b2a3ce4ac2661cecc5c261d29a37/src/components/data/Products.tsx#L33-L37

`key` is useless within `ProductRow` as it's only useful for differentiating children within a list of elements and `ProductRow` is already deeper in the tree - React doesn't need to differentiate it from other ProductRows at this point in the tree.

**Comment by Vadorequest** [comment]
> `key` is useless within `ProductRow` as it's only useful for differentiating children within a list of elements and `ProductRow` is already deeper in the tree - React doesn't need to differentiate it from other ProductRows at this point in the tree.

Indeed, you're right, I missed that.

I'll check it and update this issue.

Regarding `Check the top-level render call using <EmotionCssPropInternal>`, any hint as to why it mentions Emotion at all? That's what led me here. if it's indeed my own mistake, then I don't get why this error would show. 🤔

**Comment by Vadorequest** [comment]
Indeed, I can confirm it's my own mistake.

Fixed through https://github.com/UnlyEd/next-right-now/commit/267b2fa67844d7d4386a07c92d8a9d6bbe5f1e60
