### ISSUE TITLE
Emotion 11's `compat` plugin is generating different selectors to Emotion 10

### ISSUE THREAD

**Issue by RoystonS** [emotion-js/emotion#2011]
**Current behavior:**

I've found a case in our source where Emotion 11 isn't generating the same CSS selector as Emotion 10 when using pseudo classes and slightly more complex expressions.

A styling input of
```
{
  ".foo": {
    ":hover": {
      ".bar": {
        "color": "grey"
      }
    }
  }
}
```

generated this output in Emotion 10:
```
.css-urj3b8 .foo:hover .bar{color:grey;}
```
but generates this output in Emotion 11:
```
.css-urj3b8 .foo :hover .bar{color:grey;}
```
(note the space between `.foo` and `:hover` which changes the selector significantly)

**To reproduce:**

Here's the behaviour in Emotion 10:
https://codesandbox.io/s/emotion-10-compat-behaviour-npzm7?file=/src/index.tsx

Here's the behaviour in Emotion 11:
https://codesandbox.io/s/emotion-11-compat-issue-iflkt?file=/src/index.tsx

Note that it's still an issue even with the recent (but unreleased) "avoid duplicating ::backdrop" patch in place.

I do have a workaround which is to change `:hover` to `&:hover`, which I actually prefer, but I think Emotion 11 is trying to avoid making that a requirement?

**Expected behavior:**

Emotion 11 should either state that it's going to have a breaking change and not support the same 'compat' behaviour as it had with old stylis in Emotion 10 or it should behave the same as Emotion 10.

**Environment information:**

- `react` version: 16.13.1
- `emotion` version: 11.0.0-next.15

**Comment by Andarist** [comment]
Thanks for the report - the input code seems pretty standard so im surprised that this doesnt work correctly know. Gonna investigate it soon

**Comment by Andarist** [comment]
Ok, I know what is going on. If we check the output for such input:
```js
    css({
      '.foo': {
        ':hover': {
          color: 'hotpink',

          '.bar': {
            color: 'grey'
          }
        }
      }
    })
```
then we get semi-correct output of:
```css
.user .foo:hover{color:hotpink;}
.user .foo :hover .bar{color:grey;}
```
As you might notice that pesky whitespace is being removed from the first rule - the one at the `:hover` level. Rules nested within a pseudo are not being fixed correctly. Need to rethink our options to do this in a performant way - maybe just a simple WeakSet would help here.

**Comment by Andarist** [comment]
Fixed in https://github.com/emotion-js/emotion/pull/2015
