### ISSUE TITLE
@emotion/react@11.0.0-next.16 causes module resolution problems with TS

### ISSUE THREAD

**Issue by kyle-mccarthy** [emotion-js/emotion#2017]
**Current behavior:**

Prior to @emotion/react@11.0.0-next.16 typescript correctly worked. However, after that change TS has problems resolving the module and type declarations.

**To reproduce:**

- [Working sandbox: @emotion/react@11.0.0-next.15](https://codesandbox.io/s/stoic-euler-4z0b2?file=/src/App.tsx)
- [Broken sandbox: @emotion/react@11.0.0-next.16](https://codesandbox.io/s/kind-easley-crnz4?file=/src/App.tsx) 

**Expected behavior:**

Types should continue to work

**Environment information:**

- `react` version: latest
- `emotion` version: 11.0.0-next.16

**Comment by Andarist** [comment]
That's weird - I don't see anything in [that release](https://github.com/emotion-js/emotion/pull/1982) that could have influenced this. Thanks for the report though - I'm going to investigate this as soon as I can.

**Comment by Andarist** [comment]
I can confirm that I've seen this failing on CodeSandbox yesterday but I can't the error today - both locally and on CodeSandbox. Could you confirm that you can't repro this anymore either? Maybe this was just some hiccup on CodeSandbox's site?

**Comment by Andarist** [comment]
Didnt get more information in a couple of days and i cant repro this. Therefore im closing this issue - we can always reopen if u provide more information
