### ISSUE TITLE
Identical class name applied to all styled components.

### ISSUE THREAD

**Issue by 2Steaks** [emotion-js/emotion#2021]
**Current behavior:**

Using a centralised function to build styled components causes failure to generate unique class names.

**To reproduce:**

Example: [https://codesandbox.io/s/dawn-tree-zk713](https://codesandbox.io/s/dawn-tree-zk713)

1. Centralise function to generate styled components (service.js) 
2. Apply and export components using above function
3. Use styled components as a nested selector (App.js)

**Expected behavior:**

Styles only applied to nested component selector.

**Environment information:**

- `react` version: 16.13.1
- `emotion` version: 10.0.28 (seems to be all versions, even 11)

**Comment by Andarist** [comment]
Yes, this won't work as expected by you - you would have to provide a unique class name to the `withStyles` call, either manually or automatically (babel plugin) and pass that class name as `target` option to the `styled` call. It's the only way to make it work - it's actually how our Babel plugin works, it inserts extra param to the `styled` calls.

**Comment by 2Steaks** [comment]
Amazing thank you!
