### ISSUE TITLE
Put Style tags into header

### ISSUE THREAD

**Issue by SimonKlausLudwig** [emotion-js/emotion#2022]
**The problem**
The w3c complains that putting style within the body is invalid.

<img width="1525" alt="Bildschirmfoto 2020-09-21 um 16 36 54" src="https://user-images.githubusercontent.com/13765114/93780605-a841d700-fc28-11ea-8315-2f52684c9d7a.png">

**Proposed solution**

Add a options to put style tags into the documents head

**Comment by Andarist** [comment]
This is only „an issue” if u are using the default 0config SSR. It doesnt cause any problems in practice - regardless of this validator’s results.

If you care about fixing this then u might use a custom cache with `.compat = true` set on it in combination with CacheProvider or use `@emotion/server` to handle building the SSR output in a slightly custom way. There are docs for both of those solutions - although they are not related to the problem you have mentioned. You should be able to find both quite easily.
