### ISSUE TITLE
Vendor prefix for animation property missing in production mode

### ISSUE THREAD

**Issue by F0LI4GE** [emotion-js/emotion#2024]
Hello!

**Current behavior:**

Facing an issue with missing vendor prefix for animation property in production mode.
Because of this issue, ios browsers can't work with `animation`.

I have a styled component:

```
import { keyframes } from '@emotion/core';
import styled from '@emotion/styled';

const bounce = keyframes`
  from, 20%, 53%, 80%, to {
    transform: translate3d(0,0,0);
  }

  40%, 43% {
    transform: translate3d(0, -30px, 0);
  }
`;

export const AnimationTest = styled.div`
  animation: ${bounce} 1s ease infinite;
  align-items: center;
  width: 150px;
  height: 150px;
`;
```
After building with `NODE_ENV=production` I get the following styles:

```
.css-lo6jxh-AnimationTest {
    animation: 1s ease 0s infinite normal none running animation-1x6uqa8;
    -webkit-box-align: center;
    align-items: center;
    width: 150px;
    height: 150px;
}
```

Building in development mode results in the following:

```
.css-j0g2kx-AnimationTest {
    -webkit-animation: animation-4meq4k 1s ease infinite;
    animation: animation-4meq4k 1s ease infinite;
    -webkit-align-items: center;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    width: 150px;
    height: 150px;
}
```

Note that there is no ` -webkit-animation` property in the production build, but autoprefixing for `align-items: center;` works fine and produces `-webkit-box-align: center;`

**To reproduce:**

We've set up a small repo with Parcel as a bundler. The same issue appears there.

[emotion-animation-prefix-bug](https://github.com/fsher/emotion-animation-prefix-bug)

**Expected behavior:**

animation property has all the necessary vendor prefixes in the production bundle.

**Environment information:**

- `react` version: 16.13.1
- `emotion` version: 10.0.27
- `webpack` version: 4.44.1

**Comment by Andarist** [comment]
I haven't noticed this effect before but it seems that `-webkit-animation` is somehow handled in a special way by browsers when using `insertRule` API. I've debugged your repro and I can confirm that this property **is** being inserted - it just gets converted by a browser to a regular `animation` property. I've checked this in Chrome, Safari and Firefox and it behaves the same in all of them.

You can kinda confirm this by executing such script in a console:
```js
var styleElement = document.createElement('style')
styleElement.dataset.test = 'foo'
document.head.appendChild(styleElement)
styleElement.sheet.insertRule('div { -webkit-animation: customname }', 0)
```
and inspecting any div on your page. Notice how it will have `animation` property, rather than `-webkit-animation`.

**Comment by F0LI4GE** [comment]
I wonder then why does it work in when `NODE_ENV !== 'production'`, insertRule is not used?

**Comment by F0LI4GE** [comment]
My bad, looks like `animation` doesn't need a vendor prefix for ios browsers

**Comment by Andarist** [comment]
> I wonder then why does it work in when NODE_ENV !== 'production', insertRule is not used?

Yes, `insertRule` is not used but we rather set `textContext` on created `script` elements. It works like that to support source maps etc in dev mode.
