### ISSUE TITLE
Error from Enzyme serializer when creating snapshot for component accepting another element as prop

### ISSUE THREAD

**Issue by ctumolosus** [emotion-js/emotion#2025]
**Current behavior:**

The following error is displayed when creating a snapshot for a React component accepting another element as prop.

```
PrettyFormatPluginError: Cannot redefine property: propsTypeError: Cannot redefine property: props
```

**To reproduce:**

You should be able to see the error on this sandbox URL:
https://codesandbox.io/s/emotion-issue-template-forked-pvxld?file=/index.test.js

Basically, setup your environment to work with Emotion 11, Enzyme, and Jest. A simple test for a component accepting another element as prop should reveal the error afterwards.

```jsx
import { configure, mount } from "enzyme";
import { createEnzymeSerializer } from "@emotion/jest";
import React from "react";
import Adapter from "enzyme-adapter-react-16";

configure({ adapter: new Adapter() });
expect.addSnapshotSerializer(createEnzymeSerializer());

const FixMe = ({ element }) => element;

test("works", () => {
  const wrapper = mount(<FixMe element={<button>Foo</button>} />);
  // PrettyFormatPluginError: Cannot redefine property: propsTypeError: Cannot redefine property: props
  expect(wrapper).toMatchSnapshot();
});

```

**Expected behavior:**

Should create snapshot without errors.

**Environment information:**

- `react` version: 16.13.1
- `emotion` version: 11.0.0-next.17

**Comment by Andarist** [comment]
Thank you for reporting your issue with the appropriate repro case! I've prepared a fix for it here: https://github.com/emotion-js/emotion/pull/2027

A sideways question - I've noticed that our serializer serializes "mounted" components by serializing both the full, mounted, tree but also by serializing all props and keeping intermediate components in the output. Would you consider this correct when dealing with `mount`? Or would you rather like to see a "flattened" output - basically what you would actually see rendered in the browser?

Currently, things like [this](https://github.com/emotion-js/emotion/blob/d55556ec2f3bbaf8ed8b3b3574069d93a3c83334/packages/jest/test/__snapshots__/react-enzyme.test.js.snap#L122-L140) happen and such input:
```js
const Test1 = () => <span>BAZINGA</span>
const Test2 = () => <Test1 test="foo" />
mount(<Test2 />)
```
yields such output:
```
<Test2>
  <Test1
    test="foo"
  >
    <span>
      BAZINGA
    </span>
  </Test1>
</Test2>
```

**Comment by Andarist** [comment]
We’ve merged the fixing PR so im going to close this issue. Feel free to respond anytime though

**Comment by ctumolosus** [comment]
Thanks for looking into the issue!

Is your question around serialization related to `enzyme-to-json` serialization [modes](https://github.com/adriantoine/enzyme-to-json/blob/HEAD/docs/modes.md)? If so, what do you think about lifting the `enzyme-to-json` serializer options on `createEnzymeSerializer`? This would allow engineers to choose their preferred serialization mode.

**Comment by Andarist** [comment]
Right - I didn't really know about those modes much. It seems that `"shallow"` mode yields exactly those results that I have seen so this is expected.

> If so, what do you think about lifting the enzyme-to-json serializer options on createEnzymeSerializer? This would allow engineers to choose their preferred serialization mode.

Right, this probably would be best. It can be added without introducing any breaking changes though so I'm going first to focus on releasing v11.
