### ISSUE TITLE
Formatting with eslint

### ISSUE THREAD

**Issue by Twiggeh** [emotion-js/emotion#2039]
**The problem**

I don't like the way Prettier formats ternaries, so I switched to eslint for my formatter. EmotionJS seems to have a plugin for eslint, but it doesn't seem like that plugin includes any css in js formatting rules. (Maybe there are some that help with css in js, but I couldn't find any >.<)

Would be awesome if it would !

**Proposed solution**

Extending the plugin :D

**Alternative solutions**

**Additional context**

**Comment by Andarist** [comment]
Well, we are huge fans of Prettier and we do not see a reason to reimplement stuff that it already does. So I'm afraid you are on your own here - you could always create a custom rule, using some existing CSS formatters. This shouldn't be too hard.

**Comment by srmagura** [comment]
Prettier is the de facto formatter used by the community so we are not too concerned about ESLint formatting rules. Feel free to create your own linting rules and share them with us.
