### ISSUE TITLE
babel-plugin-emotion inherits Babel 6 JSX syntax plugin

### ISSUE THREAD

**Issue by billyjanitsch** [emotion-js/emotion#2048]
**Current behavior:**

I noticed that babel-plugin-emotion depends on (and inherits) the v6 JSX syntax plugin rather than the v7 one:

https://github.com/emotion-js/emotion/blob/c85378a204613885a356eaba1480c5151838c458/packages/babel-plugin-emotion/package.json#L18

https://github.com/emotion-js/emotion/blob/c85378a204613885a356eaba1480c5151838c458/packages/babel-plugin-emotion/src/index.js#L66

In contrast, `babel-plugin-jsx-pragmatic` depends on the v7 plugin:

https://github.com/emotion-js/emotion/blob/539bc0c2acf164b6c31f5df55f05db35932af100/packages/babel-plugin-jsx-pragmatic/package.json#L10

Is there a reason for this, or is it an oversight?

**To reproduce:**

n/a

**Expected behavior:**

No reliance on Babel 6 packages, and consistency in dependencies between the Emotion packages.

**Environment information:**

- `react` version: n/a
- `emotion` version: `babel-plugin-emotion@10.0.27`

**Comment by billyjanitsch** [comment]
I see that this is fixed in the v11 RC so I'll close the issue if you don't plan on backporting it.

**Comment by Andarist** [comment]
Yes, if this doesn't cause any problem we'd like to avoid backporting. Emotion 10 is supporting both Babel 6 and Babel 7 (we run some tests against both!) and that was somewhat tricky due to renamed packages and stuff.
