### ISSUE TITLE
Ilegal escape sequence in your template literal

### ISSUE THREAD

**Issue by ShivangiKhandelwal27** [emotion-js/emotion#2050]
@Andarist
I am facing the same ILLEGAL ESCAPE SEQUENCE WARNING when i run the test case for the component containing my emotion components.
I get the error as

```
 "console.error ../../node_modules/@emotion/styled-base/dist/styled-base.cjs.dev.js:85
      You have illegal escape sequence in your template literal, most likely inside content's property value.
      Because you write your CSS inside a JavaScript string you actually have to do double escaping, so for example "content: '\00d7';" should become "content: '\\00d7';"
```

I am using babel-plugin-macros  as plugins in my babel config.

Changing my target to es6 from es5 in tsconfig removes this error in jest but I want to know why this happens ?
Why can't we have output as 'es5' from TScompiler which is then transferred to babel. (Babel shouldn't do any changes in this case )

**Comment by Andarist** [comment]
We probably have failed to recognize the received input as transformed by TS - we have util trying to do that [here](https://github.com/emotion-js/emotion/blob/c85378a204613885a356eaba1480c5151838c458/packages/babel-plugin-emotion/src/utils/transpiled-output-utils.js#L5).

It's hard for me to give you any concrete advice if you don't share a repro case of the problem that I could investigate.

**Comment by Andarist** [comment]
I'm going to close this as no repro case has been provided. If you manage to create one - I'll reopen this.
