### ISSUE TITLE
Will support for the new JSX runtime be backported to Emotion 10?

### ISSUE THREAD

**Issue by billyjanitsch** [emotion-js/emotion#2052]
Sorry for removing the issue template; this is just a design question and there wasn't a relevant template.

I see that [support for the new JSX runtime](https://github.com/emotion-js/emotion/pull/1970) is being worked on in a PR that targets `master`. I'm wondering whether you plan to release that work only as part of Emotion 11, or also to backport it to Emotion 10.

Just trying to plan some migration paths. Thanks!

**Comment by Andarist** [comment]
Yes, given the fact that the React team has backported those to the older versions we'll do the same. As you have noticed we are working on it [here](https://github.com/emotion-js/emotion/pull/1970) and quite frankly - it's pretty much done. Just need to update docs - unless you maybe would like to help with that? 😉

**Comment by billyjanitsch** [comment]
Thanks for answering. Going to close this, but I've answered your question about docs in https://github.com/emotion-js/emotion/pull/1970#issuecomment-713599597.
