### ISSUE TITLE
Implement the `as` prop for React Native in Emotion 11

### ISSUE THREAD

**Issue by efoken** [emotion-js/emotion#2055]
**The problem**

Currently there is no support for using the `as` prop in Emotion 11 with React Native. 

**Proposed solution**

The Web version does have support for it, so I think we can provide a similar solution with the primitives package.

**Comment by Andarist** [comment]
We consider packages related to React Native as community-driven. We don't have the time capacity to work on them ourselves but we welcome any external contributions to them.

**Comment by efoken** [comment]
Did a PR to add support for that @Andarist

**Comment by Andarist** [comment]
Implemented in https://github.com/emotion-js/emotion/pull/2058, thank you!
