### ISSUE TITLE
Transform between CSS string and JS object

### ISSUE THREAD

**Issue by n8sabes** [emotion-js/emotion#2056]
Are there any functions in emotion (either via api, or in the supporting code) that will accept a css string (or css file of classes and transform into a proper JS object? I see a few other libraries out there that do this, but if it can be done with emotion, this is a win.

For example, convert 
```
foo {
  background-color: black;
  color: orange;
  margin-top: 10px;
} 
```
Into:
```javascript
{
  foo: {
    backgroundColor: "black",
    color: "orange",
    marginTop: "10px"
  }
}
```

I tried passing the string to css``, but it just transforms it into a string under a `style` field.

**Comment by Andarist** [comment]
We don't ever need to do such conversion in our codebase, so - no it's not supported. I would probably implement this as a custom Stylis serializer.

**Comment by n8sabes** [comment]
@Andarist, thank you for the quick response.

Because I use emotion in my front-end, which supports a simple css editor, I was hoping to find a simple way to move emotion objects in and out of standard css format. A couple of other css-transform libraries out there either don't work well, or require a lot of hacking to make emotion-compatible JS / JSON objects. I am not seeing the Stylis serializer you're referring to, but will look again. Whatever the path forward is, it needs to be light-weight for a PWA browser environment.

Yes, Closing is fine -- thanks, again.

**Comment by Andarist** [comment]
Not sure what is your exact use case and what do u plan to do with the converted object but this should be a good base for you to start working with:
https://codesandbox.io/s/stupefied-tdd-j70vt?file=/src/index.js

**Comment by n8sabes** [comment]
@Andarist you're awesome!! Much appreciated, I'll start there — Thank you. 😊

**Comment by n8sabes** [comment]
@Andarist, Stylis is a cool library and enables css to be transformed to a JS object preserving kebab-case. I can resolve to camelCase with a RegEx.

Do you have any advice on moving the JS object back to css? I have found `serialize( compiled, stringify )` to transform it from compiled to css, but not from JS object to compiled or JS to css.

**Comment by Andarist** [comment]
U can use `serializeStyles` from `@emotion/serialize`:

```js
serializeStyles([cssObj])
```

**Comment by n8sabes** [comment]
Hi @Andarist, Thanks so much for the pointer. `serializeStyles` does a nice job transforming Stylis JS Objects to a pure css styles. It does complain about kebob-case properties, however as emotion wants camelCase JS objects.

**Console Error:**
`Using kebab-case for css properties in objects is not supported. Did you mean backgroundColor?`

If the kebab-case errors are not an issue, this may work 🤞. I suppose `addToObj` could be modified to convert to camelCase.

**Comment by dherault** [comment]
This thread is from two years ago, has emotion evolved into its own solution for
- JSS to CSS
- CSS to JSS

conversions ?
