### ISSUE TITLE
React Native (Web) and Emotion 11 should use `StyleSheet.create` ?

### ISSUE THREAD

**Issue by efoken** [emotion-js/emotion#2059]
**The problem**

I think Emotion should use `StyleSheet.create` instead of `StyleSheet.flatten`, even if this maybe affects performance (?) it is in my opinion the best solution, because `StyleSheet.flatten` only creates "inline styles" and `StyleSheet.create` create an instance which is referenced later.

And besides that, when someones uses React Native Web it is always better to use `StyleSheet.create`, because it creates atomic CSS classes while `StyleSheet.flatten` only creates inline styles...

**Proposed solution**

Switch to `StyleSheet.create` in primitives-core package.

**Alternative solutions**

N/A

**Additional context**

N/A

**Comment by Andarist** [comment]
I've checked what Styled Components do and they indeed use `StyleSheet.create`: https://github.com/styled-components/styled-components/blob/28b4c28f1ebd1ea5a34717df2fe49634461285b1/packages/styled-components/src/models/InlineStyle.js#L28

If you are interested in changing this - we are open for pull requests 😉

**Comment by efoken** [comment]
#2060

**Comment by Andarist** [comment]
Got implemented in https://github.com/emotion-js/emotion/pull/2060
