### ISSUE TITLE
CSS is required but should be optional (when using ComponentPropsWithoutRef<'button'>)

### ISSUE THREAD

**Issue by AidanRRR** [emotion-js/emotion#2068]
**Current behavior:**
`Property 'css' is missing in type '{ mode: \"blue\"; text: string; icon: Element; }' but required in type 'Pick<DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, \"form\" | ... 265 more ... | \"css\">'.",
`

**To reproduce:**

I've started splitting code recently and refactored out repeating code into seperate node packages. One of those, is for a button using the following code:

`export const Button = forwardRef<HTMLButtonElement, Props & ComponentPropsWithoutRef<'button'>>((props, ref) => {
}`

However, when compiling with tsc it becomes:
`export declare const Button: React.ForwardRefExoticComponent<Props & Pick<React.DetailedHTMLProps<React.ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, **"css"** | "form" | "slot" | "style" | "title" | "key" | "autoFocus" | "disabled" ....... (all button props)> & React.RefAttributes<HTMLButtonElement>>;`.

However; when using this in another package it works fine but i have to add the empty css prop as it is required: `css={{}}`. So for example: `<Button mode="normal" text="Hoela">}/>` only works when I add the required CSS prop. 

**Expected behavior:**

Should work without a required CSS prop?

**Environment information:**

- `react` version: ^16.13.1,
- `emotion` version:
@emotion/react": "^11.0.0-rc.0,
@emotion/styled": "^11.0.0-rc.0,

It might be related to: https://github.com/emotion-js/emotion/pull/1941?

Or some problem that CSS type comes from emotion and not from React? I did not understand it fully, so I might say things that are not correct.

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by AidanRRR** [comment]
Thanks for the reply! It is an electron application that is not easy to run. I'll see what I can do to extract this part in order to share the problem with a better context.

Specifically when using: `ComponentPropsWithoutRef<'button'>` it will generate a required CSS attribute that somehow is interpreted as required. Is this normal? Or does CSS collide with something that is been used in the package itself?

**Comment by Andarist** [comment]
@AidanRRR have you solved your issue?

**Comment by AidanRRR** [comment]
Yes, I still had a reference to @emotion/core in the application. So only @emotion/react and @emotion/styled (latest, 11) and it works. So I guess it has been fixed already.
