### ISSUE TITLE
SSR Rendering has a weird and reproducible issue [Repo link inside]

### ISSUE THREAD

**Issue by lucax88x** [emotion-js/emotion#2079]
**Current behavior:**

Check the reproducible repro below, easier to explain.

Anyway, I have a component, that based on a condition renders one div or another.

One div has styles, the other doesn't have styles.

For some reason it renders the div without styles, but with the styles of the other div.

**To reproduce:**

1) https://github.com/lucax88x/nextjsemotionrepro
2) yarn dev
3) check that you see "I should see this without any style, but I am getting Typography class" big and with red color

**Expected behavior:**

the "I should see this without any style, but I am getting Typography class" should not have any style

**Environment information:**

- `react` version: 17.0.1
- `emotion` version: 10.1.1
- `next` version: 10.0.1

**Comment by lucax88x** [comment]
I try to help understanding the issue..

So, the parent component does this,

```tsx
return !isServer ? (
    <div>
      I should see this without any style, but I am getting Typography class
    </div>
  ) : (
    <Typography>I should NOT see this</Typography>
  );
```

So what is happening is that, on the server it renders the Typography component, which has a div and some styles.
Once it comes to the client, it renders the other div, but it gets the styles of the other div, which is wrong.

If I change from div to p, in the first condition, everything works fine.

Am I doing something wrong?

If I can do something to help you guys  tracking down the issue, just tell me :+1:

**Comment by Andarist** [comment]
I'm afraid that this is not Emotion issue. This is how React hydration works: https://codesandbox.io/s/romantic-lake-wcoif?file=/src/index.js
