### ISSUE TITLE
babel-preset-css-prop crashes when development is set with classic runtime

### ISSUE THREAD

**Issue by billyjanitsch** [emotion-js/emotion#2082]
**Current behavior:**

I know you've just deprecated `runtime` support in `@emotion/babel-preset-css-prop` so I don't know if you care to fix this, but just in case...

Given this Babel config:

```js
module.exports = {
  presets: [["@emotion/babel-preset-css-prop", { development: true }]],
};
```

And this code:

```js
import * as React from "react";

export default function MyComponent() {
  return <div />;
}
```

Babel crashes when transpiling:

```
SyntaxError: /index.js: pragma and pragmaFrag cannot be set when runtime is automatic.
> 1 | import * as React from "react";
    | ^
  2 | 
  3 | export default function MyComponent() {
  4 |   return <div />;
    at File.buildCodeFrameError (/node_modules/@babel/core/lib/transformation/file/file.js:250:12)
    at NodePath.buildCodeFrameError (/node_modules/@babel/traverse/lib/path/index.js:144:21)
    at PluginPass.enter (/node_modules/@babel/helper-builder-react-jsx-experimental/lib/index.js:167:26)
    at newFn (/node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/node_modules/@babel/traverse/lib/context.js:140:19) {
  code: 'BABEL_TRANSFORM_ERROR'
}
```

**To reproduce:**

1. Clone [this repo](https://github.com/billyjanitsch/emotion-classic-dev).
2. Run `npm it`.

**Expected behavior:**

I understand that there's no reason to set `development` unless you've also set `runtime` to `'automatic'`. But if you do, I'd expect it to have no effect (like any other unsupported setting) rather than crashing. (I encountered this because I maintain a preset that wraps React and Emotion and supports both runtimes, and I was [setting the `development` option unconditionally](https://github.com/kensho-technologies/babel-preset/blob/a491c4475d95dd14738a8f44e5f8753e87578372/index.js#L79), thinking that it would only take effect for the automatic runtime.)

The issue is here:

https://github.com/emotion-js/emotion/blob/e67a57b14c7fc69932fb693a8762539d14b06291/packages/babel-preset-css-prop/src/index.js#L33-L45

If `development` is true, Emotion uses `jsxDev` regardless of whether `runtime` is `'classic'` or `'automatic'`. `jsxDev` [implicitly defaults to `runtime: 'automatic'`](https://github.com/babel/babel/blob/d7e32d8c3df9447624f20677bf1b01761ee7a438/packages/babel-plugin-transform-react-jsx-development/src/index.js#L21). The automatic runtime conflicts with Emotion's pragmatic plugin, causing the crash.

One way to fix this is by changing the check to:

```js
development && options.runtime === 'automatic' ? jsxDev : jsx
```

**Environment information:**

- `react` version: 16.14.0
- `emotion` version: 10.2.0

**Comment by Andarist** [comment]
Good catch and a detailed report ❤️ Would u like to provide a PR for this? Also keep in mind that for automatic runtime u should no longer use our preset - it’s supposed to only be used for the classic runtime.

https://github.com/emotion-js/emotion/releases/tag/%40emotion%2Fbabel-preset-css-prop%4010.2.0

**Comment by billyjanitsch** [comment]
> for automatic runtime u should no longer use our preset - it’s supposed to only be used for the classic runtime.

Yeah, I ended up doing this: https://github.com/kensho-technologies/babel-preset/pull/100. The deprecation makes complete sense but unfortunately it's a bit awkward for presets that compose React/Emotion and want to support both runtimes. You have to toggle between the preset and the plugin depending on the runtime.

> Would u like to provide a PR for this?

Sure, it's late here but I'll PR that fix tomorrow.

**Comment by Andarist** [comment]
> The deprecation makes complete sense but unfortunately it's a bit awkward for presets that compose React/Emotion and want to support both runtimes. You have to toggle between the preset and the plugin depending on the runtime.

Right, I was actually thinking about this when I've been responding to you. It's definitely a downside but IMHO a reasonable tradeoff - given how people can get into very hard to debug situations when we keep supporting `runtime` option 😢 Presets authors are generally more aware of Babel intricacies so it makes sense to favor regular users over them.

> Sure, it's late here but I'll PR that fix tomorrow.

Thanks for the offer but I'm going to do this in a moment. I hope to release v11 tomorrow so need to handle all pending v10 issues asap :P

**Comment by billyjanitsch** [comment]
>it makes sense to favor regular users over them

+1 I totally agree. 🙂 Thanks for the PR.
