### ISSUE TITLE
The babel-preset-css-prop handles css errors differently than the jsx pragma.

### ISSUE THREAD

**Issue by sever1an** [emotion-js/emotion#2086]
**The problem**

When adapting my project to use the `@emotion/babel-preset-css-prop` in preparation for Next.js 10 and React automatic runtime mode, I ran into a few difficult to diagnose bugs relating to different handling of lightly invalid CSS. Specifically, the babel plugin seems to fully ignore blocks containing any invalid parts, whereas the non-babel approach follows browser rules. 

Example lightly invalid style. The babel plugin would not apply the gray style, whereas the approach with jsx pragma does.

```css
{
  //color: cornsilk;
  color: gray;
}
```

**Proposed solution**

Handle errors the same using both approaches, possibly by having the babel preset follow browser rules for invalid css. Ideally, it would (or have an option to) emit warnings when handling errors.

**Alternative solutions**

Since babel is *not* a browser, the proposed approach may be highly undesirable. Alternative solutions not affecting functionality might be:

- Highlight the different behavior in a pragma-to-babel migration guide.
- Emit console warning messages when the babel plugin ignores invalid code differently than the browser.
- Provide a check using `eslint-plugin-emotion`

**Additional context**

I am using next.js 9.5.5, and included the babel plugin in a custom `.babelrc` file. I am not using any type of plugin project.

```json
{
  "presets":["next/babel",["@emotion/babel-preset-css-prop",{"cssPropOptimization":true, "autoLabel":true, "sourceMap":false}]],
  "plugins":[]
}
```

Please forgive me if the babel preset does emit errors which next is hiding. If it is the case I will complain to the next.js team!

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by sever1an** [comment]
I would be happy to create an example. Is there a code sandbox service that you prefer?

**Comment by Andarist** [comment]
https://codesandbox.io/ works great :)

**Comment by sever1an** [comment]
A cursory minimal code example attempt reveals that the error was much more of an edge case than I originally suspected, and this feature request is 100% not necessary. Sorry for the clutter.

For your amusement, this is actually the isolated error from my real code that worked before using the babel preset, but not after:

https://codesandbox.io/s/laughing-tu-4lrvo?file=/pages/index.js
