### ISSUE TITLE
GitHub release watching causes excessive spam

### ISSUE THREAD

**Issue by CodeWitchBella** [emotion-js/emotion#2091]
**Description:**

If I have "watch releases" function enabled on this repository I get email for release of every npm package. What some other libraries do is that they merge releases of different packages into on github release. This issue also makes it harder to find changelog for given package in github releases - I know I can look at CHANGELOG.md in every package, but that time consuming when I use multiple packages.

**Documentation links:**

https://github.com/emotion-js/emotion/releases

**Comment by Andarist** [comment]
> What some other libraries do is that they merge releases of different packages into on github release.

Grouping doesn't always make sense for our packages. Published versions are independent, although for many packages they are linked to a single major version.

> This issue also makes it harder to find changelog for given package in github releases

This seems like a GitHub's issue - that there is no search functionality there. 

> If I have "watch releases" function enabled on this repository I get email for release of every npm package.

This was a new major release so there were a lot of releases at once but usually not so many packages are involved so I don't think this is that big of an issue.

**Comment by srmagura** [comment]
I believe we need the ability to release individual packages one-by-one, rather than releasing all packages at once and bundling everything into a single GitHub release. So there doesn't seem to be anything actionable for us here. Sorry for the inconvenience caused by the notifications.
