### ISSUE TITLE
Can't resolve '@emotion/core/jsx-runtime.js

### ISSUE THREAD

**Issue by sqal** [emotion-js/emotion#2094]
**Current behavior:**

Hi. Today I upgraded @emotion to 11.0.0 in my project and I wanted to enable "automatic runtime" option both in React's babel plugin and  @emotion's plugin.  I did everything according to this description https://github.com/emotion-js/emotion/blob/master/docs/css-prop.mdx##babel-preset  but I am getting Module not found error:

```
ERROR in ./src/app.tsx
Module not found: Error: Can't resolve 'C:\Users\pc\dev\myproject\node_modules\@emotion\react\dist\emotion-react.cjs.js/jsx-dev-runtime.js' in 'C:\Users\pc\dev\myproject\apps\myapp\src'
 @ ./src/app.tsx 1:0-157 12:18-25 13:14-21
```

What's weird to me is that part **dist\emotion-react.cjs.js/jsx-dev-runtime.js**

Here's my babel config:

```js
module.exports = {
  presets: [
    ['@babel/preset-env', {
      useBuiltIns: 'usage',
      modules: false,
      loose: false,
      bugfixes: true,
    }],
    ['@babel/preset-react', {
      development: process.env.NODE_ENV !== 'production',
      runtime: 'automatic',
      importSource: '@emotion/react',
    }],
  ],
  plugins: [
    ['@emotion/babel-plugin', {
      sourceMap: process.env.NODE_ENV !== 'production',
      autoLabel: 'dev-only',
      labelFormat: '[local]',
    }],
  ],
};
```

**Expected behavior:**

Should correctly resolve JSX runtime module

**Environment information:**

- `OS`: Windows 10
- `react` version: 17.0.1
- `@emotion/react` version: 11.0.0

**Comment by Andarist** [comment]
You can read through the issue here: https://github.com/emotion-js/emotion/issues/2071 , but the TLDR answer is that you should upgrade `@babel/preset-react`.

**Comment by sqal** [comment]
@Andarist I am already using the latest version of @babel/preset-react -> 7.12.5

**Comment by Andarist** [comment]
It looks like the dependency ranges have not been bumped appropriately when releasing this version 😞 

Please follow this advice then: https://github.com/emotion-js/emotion/issues/2071#issuecomment-720962176

**Comment by sqal** [comment]
Ok. There has been some issue with my Yarn lockfile. I re-installed everything, and the original issue is gone.
