### ISSUE TITLE
Congrats on v11!

### ISSUE THREAD

**Issue by billyjanitsch** [emotion-js/emotion#2095]
Sorry for the non-issue. Just wanted to say congrats on the v11 release! 🎉 The new features are great and it's remarkably stable. In migrating 10+ projects, I haven't noticed a single bug.

Thanks for all of the love you've put into this. ❤️

**Comment by Andarist** [comment]
Thanks for the kind words of appreciation. It means a lot ❤️

**Comment by NBruhno** [comment]
If anyone do run into some trouble, please remove your modules and lock files and reinstall (as per usual). I was ripping my hair out trying to figure out why I got a "not a function" error for `stylis.middleware`. But now that everything is running, it sure is nice!

**Comment by belgattitude** [comment]
Thanks @Andarist !

**Comment by prabhuignoto** [comment]
> If anyone do run into some trouble, please remove your modules and lock files and reinstall (as per usual). I was ripping my hair out trying to figure out why I got a "not a function" error for `stylis.middleware`. But now that everything is running, it sure is nice!

hit the exact same problem and this helped thanks
