### ISSUE TITLE
Webpack is unable to tree-shake unused theming code

### ISSUE THREAD

**Issue by billyjanitsch** [emotion-js/emotion#2100]
Related to https://github.com/emotion-js/emotion/issues/2097.

**Current behavior:**

`withTheme` is now exported from `@emotion/react`. It uses `hoist-non-react-statics`:

https://github.com/emotion-js/emotion/blob/f4b9dc6ea6863e499586a61b9fd64f2c2cdf4092/packages/react/src/theming.js#L75

Unfortunately, this package doesn't provide an ESM entry point, which interferes with webpack's ability to tree-shake it if it's unused. `hoist-non-react-statics` also [depends on `react-is@16`](https://github.com/mridgway/hoist-non-react-statics/blob/f3de655212b47f20b9c6a27e89a60d23f358925a/package.json#L25), which is especially unfortunate for React 17 projects.

**To reproduce:**

See [this repo](https://github.com/billyjanitsch/emotion-theming). Specifically, note that [this entrypoint](https://github.com/billyjanitsch/emotion-theming/blob/01f2886939a889729dcf8b78edbecbeaa67667b6/src/index.js) results in [this bundle](https://github.com/billyjanitsch/emotion-theming/blob/01f2886939a889729dcf8b78edbecbeaa67667b6/dist/main.js), which includes the entirety of `hoist-non-react-statics` and `react-is`. (n.b. I ran Prettier on the bundle so that it's intelligible, but it was generated in prod mode.)

**Expected behavior:**

I'd expect `withTheme`, as well as all of `hoist-non-react-statics` and `react-is`, to be pruned from the bundle. I don't personally use Emotion's theming features so this would be really nice. 🙂 

There's an [open PR to add ESM support](https://github.com/mridgway/hoist-non-react-statics/pull/86) but it's 1.5 years old so I wouldn't expect it to be merged soon. Perhaps it would be worth forking the package to add the ESM entry and update the `react-is` dependency to `^16.7.0 || ^17.0.0`?

I'm happy to work on whatever approach you prefer.

**Environment information:**

- `react` version: 17.0.1
- `@emotion/react` version: 11.0.0

**Comment by Andarist** [comment]
Hah, I actually already had a tree-shaking demo prepared but haven't pushed it out before you have posted 😅 Here it is: https://github.com/Andarist/emotion-11-tree-shaking-test . It's pretty similar to yours - I just also test Rollup in addition to webpack.

I've prepared a PR fixing this particular issue with `hoist-non-react-statics`: https://github.com/emotion-js/emotion/pull/2101 . The only other tree-shaking deopt I have found is the property access here:
https://github.com/emotion-js/emotion/blob/f4b9dc6ea6863e499586a61b9fd64f2c2cdf4092/packages/react/src/context.js#L20
but fixing this would either require isolating this in a similar fashion to what I have done with `hoist-non-react-statics` or wrapping this in something like:
```js
export let CacheProvider = /* #__PURE__ */ (() => EmotionCacheContext.Provider)()
```
but none of this seems justifiable for this particular thing.

**Comment by billyjanitsch** [comment]
Maybe someday I will manage to get a contribution in before you beat me to it... 😛

Thanks, that fix looks great!

**Comment by Andarist** [comment]
Hah, contributions are always welcome - this was a tricky issue though and I was already investigating it before you have posted. Sorry for that 😅
