### ISSUE TITLE
renderToString() doesn't embed styles when called in the browser

### ISSUE THREAD

**Issue by nicolasschabram** [emotion-js/emotion#2102]
**The problem**

When calling React's `renderToString()` in the browser, emotion won't embed the styles into the output HTML. If I'm not mistaken, this was discussed before in https://github.com/emotion-js/emotion/issues/1245, but in the context of jest and without a solution that would work in a real browser.

**Proposed solution**

I suspect that my problem would be solved by removing the `isBrowser` check in here: https://github.com/emotion-js/emotion/blob/f4b9dc6ea6863e499586a61b9fd64f2c2cdf4092/packages/styled/src/base.js#L135
I'm pretty sure though it's there for a reason that's beyond my knowledge of how emotion is implemented. :) I'd appreciate some input on what's behind that check.

**Alternative solutions**

Me giving up my plans and rendering on the server instead 🤷‍♀️

**Additional context**

The reason why I'm trying to do this in the first place is that I'm looking for a way to render React code as HTML that I can in turn feed into an HTML-to-PDF converter, preferably all in the browser.

Using emotion for this might be a bit of a stretch, but I'm close enough to make it happen that I feel like there must be some way.

**Comment by Andarist** [comment]
Thanks for bringing this up - I will give this a thought. Could you tell me if the rest of your app is using Emotion as well? I suspect that for the rest of the app you wouldn't like `style` elements to be rendered inline, right?

**Comment by nicolasschabram** [comment]
Thanks for considering it, @Andarist! Yes, that is correct, we're also using Emotion in the rest of the application (which ideally wouldn't be affected). Not sure that's relevant, but it's mostly still on `@emotion/css` and the className-based API. I should be able to restrict the statically generated HTML part to exclusively using the new APIs though, in case that makes things easier.

**Comment by Andarist** [comment]
Using `@emotion/react` this can be quite trivial to achieve:
https://codesandbox.io/s/interesting-nash-ipyko?file=/src/App.js

**Comment by nicolasschabram** [comment]
Ha yes, that seems to do the trick. Thanks a lot, I appreciate your help (and your work on emotion in general)!

**Comment by nicolasschabram** [comment]
One thing I noticed that doesn't yet work with this approach is `<Global>`: https://codesandbox.io/s/agitated-bird-44cou. Is that easily fixable as well? 🤔

**Comment by Andarist** [comment]
The easiest that comes to my mind is to replace `<Global/>` with an empty element that renders `:global()` styles after adding a `namespace` plugin:
https://codesandbox.io/s/long-star-x8zmy?file=/src/App.js

**Comment by jtabone16** [comment]
@Andarist will this strategy work if using Emotion styled components?

**Comment by Andarist** [comment]
@jtabone16 it should

**Comment by david-ic3** [comment]
@Andarist  @mnajdova  

We have tried but it's not working for styled components , check a
 simplified example :  

https://codesandbox.io/s/autumn-morning-3mdyj7?file=/demo.tsx

One additional question, how would you inject the styles to emotion back ?

**Comment by jockjocko** [comment]
Tested in react 18 does not work no styled are received and insert is not called

**Comment by dbousamra** [comment]
Still an issue

**Comment by dimamarksman** [comment]
For me [this fix](https://github.com/emotion-js/emotion/issues/2102#issuecomment-727186154) doesn't work when I run it in the browser.

**Comment by noe** [comment]
Not working for me either. Is there any workaround for this issue in react 18?

**Comment by dberardo-com** [comment]
indeed it seems that the insert function is actually never called. at the end of the process the cache.registered array is populated but not the inserted map
