### ISSUE TITLE
Allow passing the Theme type with the useTheme hook

### ISSUE THREAD

**Issue by AliRain** [emotion-js/emotion#2104]
**The problem**

When I use the `userTheme` hook, I cannot specify the type. That leads to my code being very angry at me about missing types.
<img width="405" alt="Screen Shot 2020-11-15 at 11 43 53 AM" src="https://user-images.githubusercontent.com/51526307/99180517-daa71680-2737-11eb-9378-29e86b55565c.png">

**Proposed solution**

I believe updating the definition here: packages/react/types/theming.d.ts
To something like this should do the trick:

```typescript
export function useTheme<T>(): T
```

**Comment by Andarist** [comment]
Have you tried providing a global `Theme` type like it's described here: https://emotion.sh/docs/typescript#define-a-theme ?

**Comment by AliRain** [comment]
Doh! Dunno how I missed that. 🤦
