### ISSUE TITLE
Error to run tests with emotion-jest 11

### ISSUE THREAD

**Issue by mverissimo** [emotion-js/emotion#2110]
**Current behavior:**

I've upgraded to v11, I received the following error when the run the test suite.

```bash
 Cannot find module 'enzyme-to-json' from 'node_modules/@emotion/jest/dist/emotion-jest.cjs.dev.js'

    Require stack:
      node_modules/@emotion/jest/dist/emotion-jest.cjs.dev.js
      node_modules/@emotion/jest/dist/emotion-jest.cjs.js
      src/setupTests.js
```

**To reproduce:**

Repro case -> [emotion-jest](https://github.com/mverissimo/emotion-jest-bug)

**Environment information:**

- `react` version: 17.0.1
- `@emotion/react` version: 11.0.0

**Comment by Andarist** [comment]
Fix is on the way: https://github.com/emotion-js/emotion/pull/2109

**Comment by mverissimo** [comment]
Nice, thanks @Andarist

**Comment by Andarist** [comment]
The fix has been released.
