### ISSUE TITLE
Cannot find module 'react/jsx-runtime'

### ISSUE THREAD

**Issue by mverissimo** [emotion-js/emotion#2119]
**Current behavior:**

I've upgraded to v11, I received the following error when the run the test suite.

```bash
  ● Test suite failed to run

    Cannot find module 'react/jsx-runtime' from 'node_modules/@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs.dev.js'

    Require stack:
      node_modules/@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs.dev.js
      node_modules/@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs.js
      packages/react-ui/src/utils/test-utils.js
      jest.setup.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs.dev.js:14:23)
```

My babel file:

```
module.exports = {
  env: {
    test: {
      presets: [
        [
          "@babel/preset-env",
          {
            targets: {
              node: "current",
            },
          },
        ],
        [
          "@babel/preset-react",
          {
            runtime: "automatic",
            importSource: "@emotion/react",
          },
        ],
      ],
      plugins: ["@emotion/babel-plugin"],
    },
  },
};
```

**Environment information:**

- `react` version: 17.0.1
- `@emotion/react` version: 11.0.0
- `@emotion/jest` version: 11.1.0
- `@emotion/babel-plugin` version: 11.0.0

**Comment by Andarist** [comment]
It means that it doesn't find `react/jsx-runtime` module as if you would have an older version installed.

Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given (and here they are not).

**Comment by mverissimo** [comment]
I'm investigating and this looks like a problem with `yarn` to resolve the dependencies, when I try to run `npm install` this works fine, but with `yarn` not.

**Comment by mverissimo** [comment]
I generated a new `lock` file and works fine, thanks for the help!

**Comment by shubham-dentsu** [comment]
Cannot find module 'react/jsx-runtime' from 'Accordion.js'

I'm facing same issue, I removed node_modules and package-lock.json and run npm i.
still getting "Cannot find module 'react/jsx-runtime' from 'Accordion.js'" error.

Any idea ?

**Comment by mverissimo** [comment]
Hi @shubham-dentsu do you have a repro case?

**Comment by shubham-dentsu** [comment]
@mverissimo Thanks for reply. Issue is resolved now, I locked my dependency versions so removing node_modules and package-lock.json didn't worked for me 😅.

So I updated my react and react-script version and issue is resolved.

Thanks 🤩.

**Comment by moimikey** [comment]
this is still an issue with yarn 2 + workspaces + pnp. same with `/styled/base` not found.

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by KevinGhadyani-minted** [comment]
Looks like certain versions of Emotion aren't compatible with certain versions of React. In this particular case, I had to upgrade `react` and `react-dom` from `16.13.1` to `17.0.1` for Emotion 11 to successfully pass unit tests.

**Comment by iam-yan** [comment]
Hey @moimikey 
I am facing with a similar issue. How did you solve it?

**Comment by KevinGhadyani-minted** [comment]
Upgraded everything to React 17 and Emotion 11.

**Comment by hongf** [comment]
Possible by typescript version is not match.
Similar issue happened when VS code using VS code Typescript verison, issue resolved after change to Typescript in node_modules.

**Comment by cforsyth68** [comment]
As of now, this fixes it for me...

`yarn add @types/react`

or
 
`npm install @types/react`

**Comment by Eliav2** [comment]
for me it was just an issue because I'm using Linux subsystem for windows with pnpm.

so in my `node_modules/.modules.yaml` i needed to change
```
#storeDir: /mnt/d/.pnpm-store/v3 # from this
storeDir: D:\.pnpm-store\v3 # to this
```

I think webstorm\vs code should understand both of them... but I am too last to open an issue for this.

**Comment by hscheuerle** [comment]
npm detects manual changes in package.json devDependencies but yarn doesn't? Is that the difference here?

**Comment by twalibnurrein07** [comment]
how do you solve this problem in codesandbox.io.

**Comment by YusufSanusi** [comment]
> how do you solve this problem in codesandbox.io.

I'm still waiting for someone to answer this

**Comment by LotfiOR** [comment]
> I generated a new `lock` file and works fine, thanks for the help!

how do you generate a new lock file? and what exact lock file are you referring to? yarn-lock or package-lock?

**Comment by NourIM** [comment]
> > I generated a new `lock` file and works fine, thanks for the help!
> 
> how do you generate a new lock file? and what exact lock file are you referring to? yarn-lock or package-lock?

npm ci

**Comment by joseallef** [comment]
I'm also experiencing the same problem, so I deleted node_modules and reinstalled with npm instead of yarn

**Comment by amunrarara** [comment]
> > I generated a new `lock` file and works fine, thanks for the help!
> 
> how do you generate a new lock file? and what exact lock file are you referring to? yarn-lock or package-lock?

You've probably learned this one by now (since the thread is almost a year old), but just in case it's helpful, `package-lock.json` is generated by npm, while `yarn.lock` is generated by yarn package manager. They should _not_ both be in your project (unless you have a very specific reason), which indicates you've attempted to generate a dependency graph using _both_ package managers. Delete both lock files, remove the `node_modules` folder, then run the install command from root from your favorite package manager (and stick with it!): `yarn` or `npm install`

**Comment by josiah-brown** [comment]
Upgrading to React 17.0.1 fixed it for me

**Comment by avanavana** [comment]
> As of now, this fixes it for me...
> 
> `yarn add @types/react`
> 
> or
> 
> `npm install @types/react`

Just wanted to say that I was banging my head against the wall for 1.5 days at work running into this issue, and this is finally what solved it.  I must have tried nearly a dozen other things.
