### ISSUE TITLE
support for dynamic Theme type composition

### ISSUE THREAD

**Issue by webican** [emotion-js/emotion#2123]
useTheme in v10 used to be a generic useTheme<T>() where T would be the Theme's type. In v11 however it is now required to use module declaration.

The problem is that I'm using a monorepo with multiple apps that reuse many components. That means I have no fixed theme type for the app and the final Theme type is constructed depending on which components are being used and the Theme type fragments are being passed up the component tree to compose a final Theme type.

My only option right now would be to explicitly cast the Theme to desired type when using useTheme, which isn't ideal.

**Comment by Andarist** [comment]
Your use case seems reasonable - could u prepare a PR for this?

**Comment by webican** [comment]
I have added the following lines to the modules declaration for a time being:

```typescript
import '@emotion/react';

declare module '@emotion/react' {
  function useTheme<T>(): T;
}
```

Feel free to close this issue

**Comment by szagi3891** [comment]
@webican 
And can you tell us how to use it ? I also have monorepo in my project and exactly the same problem

**Comment by webican** [comment]
@szagi3891 Create modules.d.ts file in your src folder for example and paste it there

**Comment by Andarist** [comment]
a second thoughts question - why do u need to parameterize this? even if you have multiple themes they usually adhere to the same schema and only values should be changed but this shouldn't affect the types, what am i missing?

**Comment by webican** [comment]
@Andarist In my case I think it makes more sense to build the theme from bottom up from Theme fragments rather than define entire Theme type at the top and then pass it down. Here is how I have been doing it so far:

components/ListItem.tsx
```typescript
export type Theme = {
  colors: {
    primary: string;
  };
  listItem?: {
    color?: string;
  };
};

export const ListItem = () => {
   const theme = useTheme<Theme>();

   ...
}
```

components/List.tsx
```typescript
import { ListItem, Theme as ListItemTheme } from './ListItem';

export type Theme = ListItemTheme & {
  colors: {
    secondary: string;
  };
  list?: {
    color?: string;
};

export const List = () => {
   const theme = useTheme<Theme>();

   ...
}
```

components/Table.tsx
```typescript
export type Theme = {
  colors: {
    primary: string;
  };
  table?: {
    color?: string;
};

export const Table = () => {
   const theme = useTheme<Theme>();

   ...
}
```

apps/appWithList/Theme.ts
```typescript
export const Theme = {
  colors: {
    primary: 'blue',
    secondary: 'orange',
  },
  list: {
    color: 'green',
  },
  listItem: {
    color: 'red',
  }

  ...
};
```

apps/appWithTable/Theme.ts
```typescript
export const Theme = {
  colors: {
    primary: 'white',
  },
  table: {
    color: 'black',
  }

  ...
};
```

**Comment by Andarist** [comment]
Well, if you want this - please prepare a PR for adding this and we'll continue discussing then. I'm not strongly opposed to this but I'm also trying to assess if the actual benefits are worth it.

**Comment by webican** [comment]
Thanks. I will be very busy in the coming week, I might be able to do that during the following week.

**Comment by zce** [comment]
You can use typescript type declaration merging to solve this problem. like this:

types.d.ts

```typescript
import theme from './theme'

declare module '@emotion/react' {
  type Custom = typeof theme
  interface Theme extends Custom {}
}
```

**Comment by Andarist** [comment]
@webican's issue is about something else - your solution assumes a single `Theme` type for the whole application whereas he'd like to use different themes in different sections of his app.

**Comment by dylanvorster** [comment]
Really not a fan of this new change, generics exist for a reason.

```
export type Tags<T> = {
  // normal tags
  [Tag in keyof JSX.IntrinsicElements]: CreateStyledComponent<{
    theme?: T
    as?: React.ElementType
  },
    JSX.IntrinsicElements[Tag]>
}

export type Component<T> = {
  <C>(
    component: C,
    options?: any
  ): CreateStyledComponent<{
    theme?: T
  }>
}

export function createStyled<T>(): Tags<T> & Component<T> {
  return styled;
}

// test
const s = createStyled<{ value: string }>();

const DoSomething: React.FC<any> = () => {
  return <div></div>;
};

export const test1 = s.div`
  ${p => p.theme.value}
`;


export const test2 = s(DoSomething)`
  ${p => p.theme.value}
`;
```
I found that this is an okay work around for most use cases but acknowledge that it doesn't account for everything. I would have much preferred this API still provided as a more granular approach with the current generics as a further abstraction on-top. This would allow for both cases.

**Comment by Andarist** [comment]
https://github.com/emotion-js/emotion/pull/2352#issuecomment-821769442
