### ISSUE TITLE
Using state for the theme in ThemeProvider 

### ISSUE THREAD

**Issue by TheCodingGorilla** [emotion-js/emotion#2124]
**The problem**

Changing the theme using state. Although its possible to do it requires either another context or passing state down via props. 

A use case would be switching a theme to a dark mode or a more accessible theme.

**Proposed solution**

Allow for the ThemeProvider to take either a theme or a theme and a setTheme returned from `useState`.

**Alternative solutions**

Set the state and apply to another provider that would be used for setting the theme.

**Additional context**

If this is something that sounds like a good addition I'm happy to make a PR.

**Comment by Andarist** [comment]
I'm afraid I don't quite understand what you are proposing. Could you fork this codesandbox - https://codesandbox.io/s/aged-haze-t5l9w?file=/src/App.js - to present your API idea?

**Comment by TheCodingGorilla** [comment]
**Passing theme state as props:** https://codesandbox.io/s/youthful-wu-w773x?file=/src/App.js

**Creating another context:** https://codesandbox.io/s/hopeful-cdn-w5308?file=/src/App.js

**Ideal usage:** https://codesandbox.io/s/hopeful-cdn-w5308?file=/src/App.js

Hopefully this helps clarify.

**Comment by Andarist** [comment]
This can be easily handled by composition: https://codesandbox.io/s/adoring-pond-39vw0 (you have probably posted similar solutions as part of the 2 first demos), so I don't think this is something that we should provide. Especially that this would most likely be a breaking change now and would require some runtime costs for all users that do not with to use this.

**Comment by TheCodingGorilla** [comment]
Great solution and appreciate there isn't a need to change the API to support this. There is a minor challenge with extending the `ThemeProviderProps` when using Typescript but nothing too taxing on users. Thanks for responding.

**Comment by salientknight** [comment]
@Andarist I don't get it. The example you provided doesn't use emotion.
