### ISSUE TITLE
Hashed classes from css function

### ISSUE THREAD

**Issue by Alecell** [emotion-js/emotion#2129]
**The problem**

I'm always wanted to find a css-in-js solution that don't hurt the cascading and have a pretty similar syntax with the SASS itself. I just discover Emotion and I find it awesome, it does almost what I've been looking for, the syntax when we use nested selector is awesome, the only point that I believe could be improved is a way to hash the generated css inside `css` function.

**Proposed solution**

**Currently we use nested styles this way:**
```tsx
/** @jsx jsx */
import { jsx, css } from '@emotion/react'

const paragraph = css`
  color: turquoise;

  .link {
    border-bottom: 1px solid currentColor;
    cursor: pointer;
  }
`
render(
  <p css={paragraph}>
    Some text.
    <a class='link'>A link with a bottom border.</a>
  </p>
)
```
The problem with this approach is that the class `link` isn't hashed, so it will be on the final build just like this, `class='link'`. This is a problem because if in anywhere else on the app someone define `.link` class it will clash with this `.link` class defined here.

**To avoid this problem the `css` function could return the other defined class just like CSSModules/SASSModules does:**
```tsx
/** @jsx jsx */
import { jsx, css } from '@emotion/react'

const classes = css`
  color: turquoise;

  .link {
    border-bottom: 1px solid currentColor;
    cursor: pointer;
  }
`
render(
  <p css={classes.root}>
    Some text.
    <a class={classes.link}>A link with a bottom border.</a>
  </p>
)
```
_The `root` class has the same content as `paragraph` on the first example and the `link` class now is hashed, so its wont build as `class='link'`, but as `class='38ds9_link_SourceFile'`_.

**Alternative solutions**

We can, of course, create a hook to deal with it, but it maybe isn't the best and would be awesome if that is exported from the Emotion package.

**Additional context**

Why do this? Why don't just use the `styled` approach? My main point is code reading, styled approach maybe isn't the best way to define styles since when you need to do some semantics or accessibility work it brings a little difficult that you need to read the styles files to know what each tag is. One other point is that keep the main read of styles is mind-blowing, noting completelly different need to be learned.

**Comment by allocenx** [comment]
I'm totally in for this! Been struggling with this past couple of days not being able to make the second nested class hashed as well... . This is a must, if you ask me.

Tho, until it gets approved, is there any workaround we can use?

**Comment by Andarist** [comment]
I'm afraid that this is an explicit non-goal of Emotion - we believe that parents influencing their child's styles are causing more harm than good, breaks encapsulation and composability. What we want to encourage is the ability to look at a component in the code and be somewhat sure what styles can be applied to it - local reasoning over global knowledge.
