### ISSUE TITLE
ESLint Plugin Rule: next/link `passHref` required with `css` prop

### ISSUE THREAD

**Issue by karlhorky** [emotion-js/emotion#2153]
Hi @Andarist! 👋 

**The problem**

When using the Next.js `Link` component, the `href` is not set properly on `<a>` elements using the Emotion `css` prop:

https://codesandbox.io/s/peaceful-sun-1yusf?file=/pages/index.js

**Proposed solution**

The workaround is to [use the `passHref` prop](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag).

It would be great for students and new learners to get a warning about this if:

- the element that the `css` prop is set on is an `<a>`
- the parent element is a `<Link>` imported from `next/link`
- that parent element does not use the `passHref` prop

It feels a bit unusual, since this rule is actually related to a specific library integration. But I can't think of anywhere else to put it, except for in the Next.js ESLint plugin (but over there, it's also related a specific library integration 🤔).

**Alternative solutions**

- adding this to the Next.js ESLint plugin

**Comment by Andarist** [comment]
The problem is that I don't know how we could detect this at runtime. The only solution that really comes to my mind is what you are also mentioning - a lint rule. This probably should live here (unless Next.js team would like to account for this in their ESlint plugin). I would be open to accepting a PR for such a lint rule.

This is how Next determines if it should set `href` on the child element:
https://github.com/vercel/next.js/blob/20949612dfb56e44a623498eb3237a69177229e5/packages/next/client/link.tsx#L297

**Comment by karlhorky** [comment]
Hmm, yeah, if Next.js would just automatically do the right thing and pass the `href` prop all the time with Emotion children, then that would be even better 🤔

What is the `child.type` on the Emotion element? Could it return an `EmotionStyledA` or something when the `css` prop is on an `<a>` element, or does it not work like that? If that would be possible, then it would make it possible to do a small PR to Next.js to automatically pass the `href`...

**Comment by Andarist** [comment]
I rather meant that maybe they would be on board with adding a lint rule for this scenario.

It's rather a hard ask to both of our libraries add runtime stuff "just" for integration purposes with the other one - especially that this affects a very specific scenario (a single type of a component).

**Comment by karlhorky** [comment]
Looks like the Next.js team has an issue open about an ESLint rule to deal with `a` elements and the `passHref` prop! 🙌

https://github.com/vercel/next.js/issues/23713

Closing...
