### ISSUE TITLE
CSS properties defined in class selectors are not being converted when using the stylis-plugin-rtl 

### ISSUE THREAD

**Issue by mnajdova** [emotion-js/emotion#2156]
**Current behavior:**

I noticed a bug when using the `stylis-plugin-rtl` with emotion. The issue may be related more to the plugin, so if that's the case, please let me know and I will report it on that repo.

Basically, the issue is that the rtl related properties defined under a class selector are not being converted. 

**To reproduce:**

You can see the behavior on this codensadbox - https://codesandbox.io/s/infallible-ganguly-jngfw?file=/src/App.js If you click on the `Swtich RTL/LTR` button you will notice that the spacing between the boxes disappears, as the `marginRight` rule defined under the class selector is not being converted:

```
  "& .first-child": {
    marginRight: "32px" // this is not converted :(
  }
```

**Expected behavior:**

All rtl related properties in the styles should be converted.

**Environment information:**

- `react` version: 17.0.0
- `@emotion/react` version: 11.1.1

**Comment by Andarist** [comment]
It's that RTL plugin issue - I've prepared a fix for it here: https://github.com/styled-components/stylis-plugin-rtl/pull/21

**Comment by mnajdova** [comment]
Thanks for the prompt reply @Andarist 👍
