### ISSUE TITLE
Upgrade Emotion's theming to interpolate scales in `css` prop

### ISSUE THREAD

**Issue by ianstormtaylor** [emotion-js/emotion#2160]
**The problem**

The idea of using interpolated "theme scales" seems pretty mainstream now in the CSS world. It seems like `theme-ui / styled-system` is the gold standard for this kind of thing. For example for a theme of:

```ts
const theme = {
  space: [0, 4, 8, 12, 16, ...],
  colors: {
    red: { ... },
  },
  fonts: {
    sans: 'ui-sans-serif, system-ui, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif',
    serif: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
  },
}
```

Using `theme-ui` you could write:

```tsx
const Component = (props) => (
  <h1
    sx={{
      color: 'red.500',
      fontFamily: 'sans',
    }}>
    Hello
  </h1>
)
```

Or similarly using `styled-system` you could create your own components to write:

```tsx
<Box color="red.500" fontFamily="sans">
  Hello
</Box>
```

Or even using something like Tailwind you could do something similar:

```html
<div class="font-sans text-red-500">
  Hello
</div>
```

Right now this is possible with the function-based API in Emotion:

```tsx
<div css={theme => ({ color: theme.colors.red[500], fontFamily: theme.fonts.sans })}>
  Hello
</div>
```

But this is more verbose than the existing solutions because of (a) the need to create a function, and (b) the mapping layer isn't smart about specific properties.

**Proposed solution**

I think this pattern is so commonplace that Emotion should actually move to support it out of the box, potentially with an addition to `ThemeProvider` that would allow for interpolating elements directly from the theme. It could be as simple as:

```tsx
<ThemeProvider theme={theme} interpolation={interpolation}>
  ...
</ThemeProvider>
```

Where `interpolation` is a default that ships with Emotion for the mapping between properties (similar to [`theme-ui`s mapping](https://theme-ui.com/theme-spec)).

This would allow using Emotion's existing `css` prop to do:

```tsx
<div css={{ color: 'red.500', fontFamily: 'sans' }}>
  Hello
</div>
```

Bringing this functionality into Emotion could actually set a new baseline, and eliminate the need for UI libraries to have to solve these problems themselves. For example `chakra-ui` which uses Emotion currently has a mix of theme-related props and component-related props, like:

```tsx
<Button colorScheme="red" fontSize="md" onClick={...}>
  Click
</Button>
```

They've had to implement the `fontSize="md"` logic on their own even though they use Emotion, and keeping track of which properties are CSS ones and which are component-specific ones is tedious. Every other component or UI kit has the same issue. When it could be nicely separated as:

```tsx
<Button colorScheme="red" onClick={...} css={{ fontSize: 'md' }}>
  Click
</Button>
```

If it were at the Emotion level, all other UI components could benefit from the same terse theme interpolating, so that when you had to use different components for autocompleting, layout, tables, etc. (which invariably no single UI kit seems to provide) you can maintain the same "themeability" across all of them.

**Additional context**

I think this is an area where a lot of value could be provided in Emotion streamlining this process and offering a sane default out of the box. Technically this is possible by integrating `theme-ui`/`styled-system` with Emotion, but this process is much more convoluted.

**Comment by MMT-LD** [comment]
From using emotion for a while and both styled-system and theme-ui - i think this goes against what emotion is trying to do/be. The reason why theme-ui/style-system implements on top of emotion is because thats the point of emotion imo. It's a low level api that can be extended to suit anyone's needs.

Im not sure supporting this would be a good idea out of the box. A separate package maybe with some defaults... However, that being said i kinda like emotion the way it is 😄 - but hey that just my opinion
