### ISSUE TITLE
Quick one, why is the slack label just a link?

### ISSUE THREAD

**Issue by BMCwebdev** [emotion-js/emotion#2161]
That's basically it, why does the Slack label go to emotion-slack.now.sh? There appears to be no way to join or get information about a Slack group for Emotion.

**Comment by Andarist** [comment]
It probably should just be https://emotion.slack.com/ . Would you be so kind and prepare a PR changing this?

**Comment by BMCwebdev** [comment]
Sure thing. Quick follow up, should there be any documentation on how to join the Slack group? This link would be for those who already are members of the group.

**Comment by Andarist** [comment]
Oh, I guess that https://emotion-slack.now.sh had an app that was able to generate invites. Let me contact Mitchell about that.

**Comment by Andarist** [comment]
This one should work: https://join.slack.com/t/emotion-slack/shared_invite/zt-jwd6t4bn-3byTBItoXuwPl5uU~8Qbdg

**Comment by BMCwebdev** [comment]
Excellent. Looks like someone has already done the work too. Thank you all!

**Comment by Andarist** [comment]
Oh, yea - seems like Mitchell has fixed this right away. Thanks for bringing this up though.
