### ISSUE TITLE
@types/react conflict for @types/react@17.0.0

### ISSUE THREAD

**Issue by dfee** [emotion-js/emotion#2167]
**Current behavior:**
There's a conflict between `@types/react` and `@emotion/react` – likely because `@emotion/react` is using the [`@types/react@16.9.11`](https://github.com/emotion-js/emotion/blob/master/packages/react/package.json#L55) vs the more recent `@types/react@17.0.0`:
```
ERROR in /Users/dfee/code/.pnpm/@types/react@17.0.0/node_modules/@types/react/index.d.ts(1341,15):
TS2320: Interface 'HTMLProps<T>' cannot simultaneously extend types 'AllHTMLAttributes<T>' and 'ClassAttributes<T>'.
  Named property 'css' of types 'AllHTMLAttributes<T>' and 'ClassAttributes<T>' are not identical.
ERROR in /Users/dfee/code/.pnpm/@types/react@17.0.0/node_modules/@types/react/index.d.ts(1346,15):
TS2320: Interface 'SVGProps<T>' cannot simultaneously extend types 'SVGAttributes<T>' and 'ClassAttributes<T>'.
  Named property 'css' of types 'SVGAttributes<T>' and 'ClassAttributes<T>' are not identical.
```

**Environment information:**

- `react` version: 17.0.1
- `@types/react`: 17.0.0
- `@emotion/react` version: 11.1.2

**Comment by Andarist** [comment]
We do not depend on the exact version of `@types/react` - we try to cope with whatever you have installed. You have linked to a devDependency range but that is not used when you are using Emotion in your project. 

--- 

Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by dfee** [comment]
Back to the drawing board. I'm unsure where this is coming from.

Perhaps it's because there was a change from `@emotion/core` (v10) -> `@emotion/react` (v11) ... I'm using `@storybook/react` which has a dep on the former, but my code has the latter?

I'm hoping this is where the conflict is coming from. Hopefully it's solved by this: https://github.com/storybookjs/storybook/pull/13300

**Comment by Andarist** [comment]
There is also this issue with Storybook: https://github.com/storybookjs/storybook/issues/13145 . I believe this should be fixed as well - they shouldn't enforce a single version of Emotion packages like that because they don't control what their users actually use.

**Comment by srmagura** [comment]
Closing this stale issue because there doesn't seem to be anything actionable for our team. Seems like the conflict may originate from Storybook rather than Emotion.
