### ISSUE TITLE
Using TypeScript's React.ComponentType with Emotion 11 and /** @jsxImportSource @emotion/react */

### ISSUE THREAD

**Issue by stuartkeith** [emotion-js/emotion#2169]
**Description:**

I'm upgrading a project from Emotion 10 to Emotion 11. There are some parts of the code that use a generic Prop type then use React.ComponentType to specify a component that uses those props. Ultimately something like this:

```
function example<Props>(Component: React.ComponentType<Props>, props: Props) {
    return <Component {...props} />;
}
```

With Emotion 11 and `/** @jsxImportSource @emotion/react */`, the props cannot be assigned to the component:

```
Type 'Props' is not assignable to type 'IntrinsicAttributes & WithConditionalCSSProp<PropsWithChildren<Props>> & Props & { children?: ReactNode; }'.
  Type 'Props' is not assignable to type 'WithConditionalCSSProp<PropsWithChildren<Props>>'.ts(2322)
```

From what I can gather, TypeScript can't assign `Props` to `WithConditionalCSSProp<Props>` due to `WithConditionalCSSProp` being a conditional type. TS can't handle something like the following, even though to the reader it seems intuitive `X` would be assignable to `Output<X>`:

```
type Output<T> = T extends string ? T : T;

function example<X>(input: X): Output<X> {
  // Type 'X' is not assignable to type 'Output<X>'
  return input;
}
```

Is there any workaround for this issue? I'm not sure if there's a way I can fix React.ComponentType or there's a fundamentally different approach I should be taking. Thanks!

**Comment by Andarist** [comment]
Could you prepare a runnable repro case for this problem? It would allow me to experiment with it.

**Comment by stuartkeith** [comment]
No problem, here's one: https://codesandbox.io/s/billowing-night-ml4g7

- `App.tsx` uses `/** @jsx jsx */` and has the type error.
- `AppNoEmotion.tsx` doesn't have the comment or the type error.

**Comment by stuartkeith** [comment]
I've also added a demonstration of a conditional type causing the same issue here: https://codesandbox.io/s/billowing-night-ml4g7?file=/src/AppConditionalType.tsx

**Comment by Andarist** [comment]
The conditional type doesn't work without Emotion either, right?

**Comment by Andarist** [comment]
Another note to myself - it seems that changing the `LibraryManagedAttributes` to this is fixing the issue:
```ts
type LibraryManagedAttributes<C, P> = WithConditionalCSSProp<ReactJSXLibraryManagedAttributes<C, P>>
```
I need to rethink the correctness of this but it looks good at the first glance.

**Comment by stuartkeith** [comment]
> The conditional type doesn't work without Emotion either, right?

That's right, it's a TypeScript limitation. It was just an example of it causing a problem. Thanks for looking into this!

**Comment by Andarist** [comment]
The problem is that this:
```ts
type LibraryManagedAttributes<C, P> = WithConditionalCSSProp<ReactJSXLibraryManagedAttributes<C, P>>
```
is fixing your issue but it breaks a more important one:
https://github.com/emotion-js/emotion/pull/1952/files#diff-14884e6a6f6f190fd064fc4e66badad8bd9e4e38cffe7b8b7ac3847834731d95R180-R185

+ some other things as well (from what I remember). This has been checked on this commit and its checks:
https://github.com/emotion-js/emotion/tree/7fd75f47c976cc6801a6f98b59a7f396c6d09776

I'm really not sure how to fix this properly to accommodate for both use cases. This is over my head - I kinda would really expect for both versions to produce the same final result.

**Comment by Andarist** [comment]
I've been digging into this and I believe that I have found a genuine bug in TS as the result: https://github.com/microsoft/TypeScript/issues/42240

Because of that bug I was thinking that switching from intersection to types composition fixes your issue - but it isn't. In the composition variant I was structuring it incorrectly (well, according to TS - the composition itself was OK, more details in the provided TS issue) and this has caused the whole thing to be entirely swallowed by TS, not affecting the code at all. So when our part has been removed from the equation then your test case has been working.

The real culprit is quite simple - it's here:
https://github.com/emotion-js/emotion/blob/a89d4257b0246a1640a99f77838e5edad4ec4386/packages/react/types/jsx-namespace.d.ts#L5
we can't test `keyof P` as `P` is generic in your situation. I have not been able to figure out how we could work around this - it's not possible to test in TS if a type is generic or not.

**Comment by stuartkeith** [comment]
Thank you for looking further into this. To be honest, I struggle a bit with wrapping my head around the React types, so I'm not sure if I'm following everything completely.

I can see why in this example, `Props` can't be checked to determine whether it supports `className`, and therefore `css`:

```
// component with "className" prop
function ComponentWithClass(props: { className?: string }) {
  ...
}

function example<Props>(Component: React.ComponentType<Props>, props: Props) {
    return <Component {...props} />;
}

// this won't work despite className being supported - Props will still be { className?: string },
example(ComponentWithClass, { css: { ... } });
```

Would there be some kind of workaround if a type was exported for direct use for this case? So you could do something like:

```
import { Helper } from "emotion";

// Props is not completely generic
function example<Props extends Helper>(Component: React.ComponentType<Props>, props: Props) {
    return <Component {...props} />;
}
```

Or:

```
import { Helper } from "emotion";

// wrap the Props type so it is compatible with Component (and so support for css prop can be added)
function example<Props>(Component: React.ComponentType<Helper<Props>>, props: Helper<Props>) {
    return <Component {...props} />;
}
```

I'm not sure if this is helpful or not!

**Comment by Andarist** [comment]
Quite frankly - this is over my head right now. If you could figure out how to write this `Helper` in a way that would satisfy the TS then I wouldn't have much problem with merging a PR providing such `Helper`.

**Comment by stuartkeith** [comment]
I've found that manually extending the `props` type with `Props & WithConditionalCSSProp<Props>` fixes the issue:

```
function example<Props>(Component: React.ComponentType<Props>, props: Props & WithConditionalCSSProp<Props>) {
  return <Component {...props} />;
}

function ComponentWithClassName(props: { className?: string }) {
  ...
}

// Props generic is inferred as `{ className?: string }`,
// `props` variable is `{ className?: string; css?: Interpolation<Theme>; }`
example(ComponentWithClassName, { css: { color: 'red' } });
```

This makes sense to me - `Props` is still generic but we're telling TypeScript the `props` variable should also be checked for compatibility with emotion's `css` prop, and then it's compatible with `Component`.

So exporting a helper along the lines of `type Helper<T> = T & WithConditionalCSSProp<T>` is pretty straightforward, to enable `props: Helper<Props>` and avoid working with `WithConditionalCSSProp` directly. That seems promising and I can look into that more next week.

**Comment by stuartkeith** [comment]
Not related to this issue, but I also realised inferring Props means components with no props let anything through. In theory the component should ignore the props anyway, but something to consider.

```
function NoProps() {}

// Props can't be inferred from the component so they're inferred from the second `props` argument, which could be anything:
example(NoProps, { asdasdsd: "zxczxc" });
```

So maybe it's better to have a fix that works with inferring the component instead of inferring the props. Will think about that too.

**Comment by osdiab** [comment]
looks like the linked issue in React has had a fix merged - this blocked me from using the babel codemod to remove the JSX pragma from my app, and I'd still like to do that; would the change you suggested to the emotion typing from there work as is now that the fix is in and published in the latest version of typescript?

**Comment by Andarist** [comment]
The bug in TS has just caused me to believe that I've found a way to work around this for some scenarios but actually, I didn't. The fix makes this error (correctly~) using all variations of the types that I've tried.

**Comment by osdiab** [comment]
oh wait is this related to the issue? I literally just ran into this for my own company's internal project. https://github.com/microsoft/TypeScript/issues/24929

**Comment by Andarist** [comment]
I don't think this issue is related.

**Comment by osdiab** [comment]
In the meantime should this typing be made more lax like the older ones so that using the JSX namespace typing isn't totally broken? Would love to use it but this blocks my migration.

**Comment by Andarist** [comment]
Could you create a repro case of your problem?

**Comment by osdiab** [comment]
Hm tried to make a minimal repro case but it worked, so maybe I've misconfigured something on my end. Will report back if i run into problems.

**Comment by stuartkeith** [comment]
It turns out the helper approach didn't really work for me. I ended up manually asserting the type, using `EmotionJSX.LibraryManagedAttributes` directly. This means that the `css` prop is defined as `any`, which is not ideal, but I wasn't able to come up with a better solution.

```
import { EmotionJSX } from '@emotion/react/types/jsx-namespace';

function example<Props>(Component: React.ComponentType<Props>, props: Props) {
  return <Component {...props as EmotionJSX.LibraryManagedAttributes<typeof Component, Props>} />;
}
```

I will close this issue for now. Thanks.
