### ISSUE TITLE
Declaring a emotion.d.ts file doesn't override `Theme` - it stays an object

### ISSUE THREAD

**Issue by Twiggeh** [emotion-js/emotion#2176]
**Current behavior:**
Not all themes become the same theme type, some stay as an empty "object"

**To reproduce:**

1. Have typescript
2. Add this to  @types
```ts
import '@emotion/react';

declare module '@emotion/react' {
	export interface Theme {
		color: {
			primary: string;
			positive: string;
			negative: string;
		};
	}
}

```
3. ThemeProvider now has the proper type for theme, but all styled elements still have an empty object for the theme property.

I circumvent that by doing this : 

```ts
import { Theme } from '@emotion/react';

type StyledProps = Pick<ButtonProps, 'bgColor' | 'fColor'> & { theme: Theme };

const StyledButton = styled.a<StyledProps>`
	${({ bgColor, fColor, theme }) =>
		`background-color: ${bgColor ? bgColor : theme.color.primary};
color: ${fColor};`}
`;

```

**Expected behavior:**

**Environment information:**

"react": "^16.13.1"
"react-dom": "^16.13.1"
"@emotion/react": "^11.1.2"
"@emotion/styled": "^10.0.27"
"typescript": "^4.1.2"
"ts-loader": "^8.0.11"

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by Twiggeh** [comment]
Sorry, I have added a minimal example with a github repo :)

**Comment by Twiggeh** [comment]
Nevermind, it was an issue with yarn upgrade not updating all packages, so emotion react was one version ahead of all the other ones
