### ISSUE TITLE
Server-side rendering creates a new cache for every element

### ISSUE THREAD

**Issue by Dru89** [emotion-js/emotion#2177]
**Current behavior:**

Today, if you create a component that looks like:
```jsx
export const Box = () => (
  <div
    css={{
      display: "inline-block",
      width: 300,
      height: 300,
      margin: 10,
      backgroundColor: "#040405",
    }}
  />
);
```

And then you render it with:
```jsx
export default function Page() {
  return (
    <div>
      <Box />
      <Box />
      <Box />
      <Box />
      <Box />
    </div>
  );
}
```

You'll get five equal `<style>` tags in the server-side rendered response. For instance:
```html
<style data-emotion="css gqphe5-Box">.css-gqphe5-Box{display:inline-block;width:300px;height:300px;margin:10px;background-color:#040405;}</style>
<div class="css-gqphe5-Box"></div>
<style data-emotion="css gqphe5-Box">.css-gqphe5-Box{display:inline-block;width:300px;height:300px;margin:10px;background-color:#040405;}</style>
<div class="css-gqphe5-Box"></div>
<style data-emotion="css gqphe5-Box">.css-gqphe5-Box{display:inline-block;width:300px;height:300px;margin:10px;background-color:#040405;}</style>
<div class="css-gqphe5-Box"></div>
<style data-emotion="css gqphe5-Box">.css-gqphe5-Box{display:inline-block;width:300px;height:300px;margin:10px;background-color:#040405;}</style>
<div class="css-gqphe5-Box"></div>
<style data-emotion="css gqphe5-Box">.css-gqphe5-Box{display:inline-block;width:300px;height:300px;margin:10px;background-color:#040405;}</style>
<div class="css-gqphe5-Box"></div>
```

Note that all of the class names are the exact same.

This is _not_ the case if you use your own CacheProvider:
```jsx
const cache = createCache({
  key: "x",
});

export default function Page() {
  return (
    <CacheProvider value={cache}>
      <div>
        <Box />
        <Box />
        <Box />
        <Box />
        <Box />
      </div>
    </CacheProvider>
  );
}
```

Output:
```html
<style data-emotion="x gqphe5-Box">.x-gqphe5-Box{display:inline-block;width:300px;height:300px;margin:10px;background-color:#040405;}</style>
<div class="x-gqphe5-Box"></div>
<div class="x-gqphe5-Box"></div>
<div class="x-gqphe5-Box"></div>
<div class="x-gqphe5-Box"></div>
<div class="x-gqphe5-Box"></div>
```

**To reproduce:**

Check out my sample repository at https://github.com/Dru89/emotion-next-demo.

These are the specific areas of interest:
* The [Box component](https://github.com/Dru89/emotion-next-demo/blob/main/components/Box.jsx)
* A [page with no CacheProvider](https://github.com/Dru89/emotion-next-demo/blob/main/pages/no-cache.jsx) (and the [rendered html](https://github.com/Dru89/emotion-next-demo/blob/main/.next/server/pages/no-cache.html))
* A [page with the CacheProvider](https://github.com/Dru89/emotion-next-demo/blob/main/pages/yes-cache.jsx) (and the [rendered html](https://github.com/Dru89/emotion-next-demo/blob/main/.next/server/pages/yes-cache.html))

You can also run this yourself by running `npm run dev`, and then checking out:
* http://localhost:3000/no-cache
* http://localhost:3000/yes-cache

**Expected behavior:**

I would expect that, using the default CacheProvider, we'd still only have one `<style>` tag in the output of the server-side render, just like we do with a custom provided CacheProvider. Naively, it seems like you could create your default cache outside of the `withEmotionCache` higher-order component at the "global" scope instead of creating one for every `withEmotionCache` call like you do here: https://github.com/emotion-js/emotion/blob/2f9ce557df6974aafd8d515fbe676ebae6df6e36/packages/react/src/context.js#L35-L46

Reading specifically through the comment in that method, it looks like it was left in the method because there's an expectation that the cache might get recreated on every render, but in this case it's getting recreated for *every component*. Which doesn't feel desirable here.

**Environment information:**

If this matters at all here, I've been specifically testing this in Next.js.

- `react` version: 17.0.1
- `@emotion/react` version: 11.1.2
- `next` version: 10.0.3

**Comment by Andarist** [comment]
This is by design - it's not that the cache gets recreated for each component but rather that they do not have a common emotion-aware ancestor. Wrapping all with CacheProvider ensures that you have such an ancestor and thus styles can be deduplicated with 100% accuracy. In your example, each of those Boxes acts as a "root" - further elements in each of those would use the already existing cache (from the context) and wouldn't create more caches.

**Comment by Dru89** [comment]
Thanks, that makes sense.

We’re in the process of writing a small library of components where the user *may not already* be using emotion anywhere else, so it’s likely the tree would have some sparse emotion components without a common ancestor. 

We could suggest they use their own cache provider if thats the expected use case there, but is there something else we should do instead?

(I’ll go ahead and close this though since it’s by design.)

**Comment by Andarist** [comment]
Ensuring a common ancestor/CacheProvider is the best way to work around this issue~
