### ISSUE TITLE
@emotion/react Global error with nested pseudo selector within media query

### ISSUE THREAD

**Issue by JoshRosenstein** [emotion-js/emotion#2179]
**Current behavior:**
Strange bug when bumping to emotion V11 using Global. 
I narrowed it down to nested pseudo-classes within a media query. ie.` .github-corner:hover` in: 
```css
  @media (max-width: 500px) {
    .github-corner:hover .octo-arm {
      animation: none;
    }
    .github-corner .octo-arm {
      animation: octocat-wave 560ms ease-in-out;
    }
  }
```
No errors occur while using Styled or Classnames, just with Global.

**To reproduce:**

1. https://codesandbox.io/s/emotion-v11-global-issue-8n691?file=/src/App.js
In the sandbox, enable the "Inject Potential Style Issue", everything works as it should until we try it using Global.

```
×
←→1 of 7 errors on the page
TypeError
Cannot read property 'type' of null
    at Array.compat (https://8n691.csb.app/node_modules/
emotion/cache/dist/emotion-cache.browser.esm.js:48:17
eval
https://8n691.csb.app/node_modules/stylis/dist/stylis.mjs:882:42
se
https://8n691.csb.app/node_modules/stylis/dist/stylis.mjs:863:36
Array.ue
https://8n691.csb.app/node_modules/stylis/dist/stylis.mjs:876:16
eval
https://8n691.csb.app/node_modules/stylis/dist/stylis.mjs:882:42
se
https://8n691.csb.app/node_modules/stylis/dist/stylis.mjs:863:36
    at stylis (https://8n691.csb.app/node_modules/
emotion/cache/dist/emotion-cache.browser.esm.js:184:41
    at Object.insert (https://8n691.csb.app/node_modules/
emotion/cache/dist/emotion-cache.browser.esm.js:195:7
    at eval (https://8n691.csb.app/node_modules/
emotion/react/dist/emotion-react.browser.esm.js:214:11
...
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.
```
**Expected behavior:**

**Environment information:**

- `react` version:17
- `@emotion/react` version:11.1.2

Original Ref: https://github.com/emotion-icons/emotion-icons/pull/245#issuecomment-747673092

**Comment by Andarist** [comment]
At the first glance, it seems like the same problem reported here: https://github.com/emotion-js/emotion/issues/2143#issuecomment-742009604 . I hope to fix this asap but it's a special time of the year and I couldn't find time to handle this just yet.

**Comment by Andarist** [comment]
Fix is on the way
