### ISSUE TITLE
Can't use custom props with Styled components in Typescript

### ISSUE THREAD

**Issue by VladimirHumeniuk** [emotion-js/emotion#2184]
Here's my very simple component:
```js
import React, { ReactChild, ElementType } from 'react'
import styled from '@emotion/styled'

type WrapperPropsType = {
  size?: SizeType
}

type ButtonPropsType = {
  as?: ElementType<any>,
  size?: SizeType,
  children?: ReactChild
}

const Wrapper = styled.button<WrapperPropsType>((props: WrapperPropsType) => ({
  fontSize: FontSize[props.size],
}))

const Button = ({ as, size, children }: ButtonPropsType) => {
  return (
    <Wrapper as={as} size={size}>
        { children }
    </Wrapper>
  )
}
```

My `.tsconfig`:
```json
{
  "compilerOptions": {
    "types": ["node", "@emotion/react"],
    "declaration": true,
    "declarationDir": "build",
    "module": "esnext",
    "target": "es5",
    "sourceMap": true,
    "jsx": "preserve",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "include": ["src/**/*"],
  "exclude": [
    "node_modules",
    "build",
    "src/**/*.test.tsx"
  ]
}
```

But on compile I'm getting next error:
> Error: src/components/Button/Button.tsx(18,30): semantic error TS2339: Property 'size' does not exist on type '{ theme?: Theme; as?: ElementType<any>; } & Pick<DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "form" | ... 265 more ... | "onTransitionEndCapture"> 
& { ...; }'.

What am I doing wrong? Thanks for any help

Packages versions:
`@emotion/react` version: 11.1.2
`@emotion/styled` version: 11.0.0
`typescript` version: 4.1.3

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by VladimirHumeniuk** [comment]
@Andarist repository: https://github.com/VladimirHumeniuk/samurai-ui , to get an error you have to run build script: `npm i &&  npm run build` 

Would be amazing if you can take a look because I have checked all similar issues on SO and here, I have checked the documentation a million times and have already dropped my hands, have no idea what I'm doing wrong.

🙏

**Comment by Andarist** [comment]
I'm not quite sure what's happening but it's not really related to our types and TS itself - I can compile your code just fine with `tsc` and there are not errors highlighted by the IDE. However, the error indeed shows up when trying to run `npm run build` which uses Rollup and `rollup-plugin-typescript2` to compile this. I've even ensured that it is using the same TS version as you have installed in your workspace by configuring this in your `rollup.config.js`:
```js
        typescript({
            typescript: require('typescript')
        }),
```
but it didn't resolve the problem. I'm afraid I won't have time to dig into this further - given this doesn't seem like a problem with Emotion itself.

**Comment by VladimirHumeniuk** [comment]
@Andarist it seems really weird, but I managed to solve this issue by replacing `rollup-plugin-typescript2` with `@rollup/plugin-typescript`.

**Comment by Andarist** [comment]
Glad you have been able to fix this on your side 👍
