### ISSUE TITLE
Doc cleanup for v7

### ISSUE THREAD

**Issue by tkh44** [emotion-js/emotion#219]
Problem description:
We are close to releasing v7 and need help going over the docs to make sure they are correct.

Suggested solution:
Pick a section proof read it 😄 

If you find something wrong either describe it here or better yet open a PR and just reference this issue.

Thanks!

**Comment by Geczy** [comment]
https://github.com/tkh44/emotion/blob/master/example/webpack.config.js

Still references extract, when extract was removed
