### ISSUE TITLE
Theme object not provided by ThemeProvider when using a component library

### ISSUE THREAD

**Issue by Vazerthon** [emotion-js/emotion#2192]
**Current behavior:**

If `ThemeProvider` is imported into a component library, re-exported and packaged, the `theme` object doesn't seem to be available to components in a project that consumes the library.

I'm honestly not sure if this is a bug or something I'm doing wrong. If it's a config problem at my end I'm sorry.

**To reproduce:**

Minimal repo here
https://github.com/Vazerthon/node-monorepo-test

Node 15 required!

- Clone the repo and follow guide in README
  - `npm install` in `common/ui` then `npm run build`
  - `npm install` at top level (to make shared lib available)
  - `npm install` in `apps/simple` and `npm start`
  - Uncomment any use of theme in `App.js`

**Expected behavior:**

The above steps should show that the `theme` is never provided to components in the React tree despite `ThemeProvider` being used and dev tools showing that the context is in place.

**Environment information:**

In common/ui
"react": "^17.0.1",
"react-dom": "^17.0.1",
"webpack": "^5.6.0",

In apps/simple
"react": "^17.0.1",
"react-dom": "^17.0.1",
"react-scripts": "4.0.1",

~ Edit ~

Upgrading to Emotion 11 has made the problem different / worse. It's no longer limited to just the theme, any use of emotion in the client project causes a React hooks error.

**Comment by Andarist** [comment]
99,9% of such cases are caused because you are using a duplicate `@emotion/react` dependency - so you provide from one copy but consume from another one. Please inspect your node_modules, npm link setup (if applicable) and so on

**Comment by Vazerthon** [comment]
> 99,9% of such cases are caused because you are using a duplicate `@emotion/react` dependency - so you provide from one copy but consume from another one. Please inspect your node_modules, npm link setup (if applicable) and so on

Thanks for the fast response @Andarist! Emotion is only installed in the component library project, nowhere else. The only dependencies in my CRA client app project are react, react-dom and react-scripts.

**Comment by Andarist** [comment]
Well - i have seen people reporting this issue dozen of times and this was always the culprit. There is multiple ways in which you can get this problem though so it’s hard to help any further unless u provide a runnable repro case of this.

**Comment by Vazerthon** [comment]
Yeah, I'm sure it's entirely possible that that's the problem. There's a link to a repo in my original post above - https://github.com/Vazerthon/node-monorepo-test

**Comment by Andarist** [comment]
Oh, sorry! Was handling this issue in a hurry from mobile and ive missed it. Thanks for providing it - i will take a look at it when i get to my desktop

**Comment by Vazerthon** [comment]
No worries, I appreciate any help I can get! Thanks for you time

**Comment by Andarist** [comment]
I don't fully understand the monorepo setup of this repository - might be some npm-related stuff but this is not how usually monorepos are installed when using different tools (yarn 1, yarn 2, pnpm, lerna with hoisting). I don't know why you have to install in both 2 subdirectories and in the root - this leads to some packages being installed multiple times in your repository, including 2 copies of React and this is just not allowed by React itself.

More than that - you are bundling your library code without specifying `externals` and thus u make all dependencies (including React) to be contained in the resulting bundle - also leading to duplicated React in your app

**Comment by Vazerthon** [comment]
> I don't fully understand the monorepo setup of this repository

It's using npm workspaces which were added recently. Learning how that works was part of my motivation for setting up this component library project. https://github.com/npm/rfcs/blob/latest/implemented/0026-workspaces.md

>  I don't know why you have to install in both 2 subdirectories and in the root

As far as I understand it, installing in the root is what makes the library available in child projects. Something to do with how npm resolves dependencies by looking up the tree I think (but again, I'm just learning this stuff so I could be wrong)

> you are bundling your library code without specifying externals

Sounds like that's my actual problem. I'll take a look at my build setup.

Thanks for your help. I think it's safe to say this isn't an Emotion bug if you want to close this ticket.

**Comment by Andarist** [comment]
I believe that you should not have to install in each workspace - nor of them should have its own package-lock. THe root acts as an aggregate for the monorepo. This seems to be confirmed by some example that I have found in the wild and reflects what I'm used to from other monorepo setups: https://github.com/Quramy/npm-ts-workspaces-example/tree/0358e4cc84a5bea03604d2dafe4bb1eefc0af1f9

`npm install` in the root makes your packages available in the monorepo **but** your library has to also be built before it can actually be used by your app.
