### ISSUE TITLE
Flow issue with inline styled function

### ISSUE THREAD

**Issue by gabrielmicko** [emotion-js/emotion#2200]
**Current behavior:**

**To reproduce:**
- Use an example code like this: 
```
type Props = {
  isLoading: boolean
}
const Example = styled<Props>(({ isLoading, ...props }) => (
  <div {...props}>{isLoading ? `Loading`: `Not loading`}</div>
))`
    color: red;
`
```

In this case ...props and isLoading are not type checked.

**Expected behavior:**

Providing flow type definition like this `styled<Props>` should provide checks in the inner function too: `styled<Props>(({isLoading, ....props}`

**Environment information:**

- `react` version:^16.12.0
- `@emotion/react` version:^11.1.4
- `@emotion/sytled` version: ^11.0.0

**Comment by gabrielmicko** [comment]
I believe this fixes the problem: https://github.com/emotion-js/emotion/pull/2199/files

**Comment by gabrielmicko** [comment]
I tried it and yes it does.

**Comment by Andarist** [comment]
Fixed by https://github.com/emotion-js/emotion/pull/2199
