### ISSUE TITLE
[TS][Proposal] Infer component prop types based on real-time value of `as` prop

### ISSUE THREAD

**Issue by zikaari** [emotion-js/emotion#2201]
**The problem**

_This issue is apparent when using `emotion` with TypeScript._

When using the `as` prop to override the rendered component, the prop types are not only bad, they even cause red squiggly lines. For example when rendering a styled button component as an anchor that needs the `href` prop, or a legend component being rendered as `label` needing the `htmlFor`.

This enhancement will also help people moving away from `withComponent` API _(as they've already done that over at styled-components)_

**Proposed solution**

We can employ typescript's type parameters to infer the component's prop-types depending on it's "actual usage" as governed by the `as` prop, or if absent, the original prop types for that component.

Here's a working example of how such an implementation will look, feel and behave:

(In the linked example just imagine as if `GenericComponent` was a component generated by a call to `styled` function)

https://codesandbox.io/s/dynamic-prop-types-based-on-as-prop-qcw0m

**Comment by Andarist** [comment]
This **maybe** could be done - but would have to work with both host components and custom components. We'd also have to check the performance of the proposed solution and check if it wouldn't collide with some other existing options.

I would be open to evaluating a PR implementing this.

**Comment by srmagura** [comment]
Thanks for the suggestion @zikaari! I am closing this in favor on #2266 which is about the same issue.
