### ISSUE TITLE
Include `SerializedStyles` in `@emotion/react`'s flow types

### ISSUE THREAD

**Issue by jimmydief** [emotion-js/emotion#2203]
**The problem**

We make heavy use of Emotion's `css` prop. One pitfall comes when allowing custom components' styles to be extended by parent components. The main issue with this is that the `css` prop is unknown to our type system (flow) and thus needs to be manually declared in the extensible component's props type. To do this, we currently import the `SerializedStyles` type from `@emotion/utils` which means that we need an explicit dependency on `@emotion/utils` just for this.

Looking at the Typescript typedefs for `@emotion/react`, it seems like `SerializedStyles` is explicitly exported already there:

https://github.com/emotion-js/emotion/blob/a89d4257b0246a1640a99f77838e5edad4ec4386/packages/react/types/index.d.ts#L27-L35

**Proposed solution**

Re-export the `SerializedStyles` type from `@emotion/react` like is currently done for Typescript.

```js
export type {SerializedStyles} from `@emotion/serialize`;
```

**Alternative solutions**

Definitely open to any suggestions of how to more easily combine custom components with the `css` prop and a type system.

**Additional context**

I'm happy to make the change if this sounds agreeable.

**Comment by Andarist** [comment]
I would accept a PR for this. Note that I'm not sure for how long we'll keep supporting Flow types in the core.
