### ISSUE TITLE
[question] Two instances of emotion on one page

### ISSUE THREAD

**Issue by piotrl88** [emotion-js/emotion#2205]
I have a project with microservices architecture. I want to use emotion in two projects that are loaded on one page. 

In my example both projects are using:
```
"@emotion/babel-plugin": "^11.0.0",
"@emotion/babel-preset-css-prop": "^11.0.0",		
"@emotion/react": "^11.0.0",
"@emotion/styled": "^11.0.0",
"emotion": "^11.0.0",
```

The problem that I have is when I'm running an app and the first project load I can see styling for all components I have, but when the second one will load some styles from the 1st one disappear.

![Screenshot 2021-01-08 152127](https://user-images.githubusercontent.com/2445345/104025671-456b5000-51c5-11eb-9835-adbad15c22c3.png)

It's probably a double emotion instance issue because when I'm not loading the 2nd project bundle everything is fine. How can I fix that?

**Comment by mabana** [comment]
I got the same problem, I tried to use createCache with the different key but it didn't help.

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

--- 

> It's probably a double emotion instance issue because when I'm not loading the 2nd project bundle everything is fine. How can I fix that?

That's probably the case but Emotion 11 shouldn't try to hijack already processed styles so seeing this problem live would help to asses why this happens.

**Comment by piotrl88** [comment]
May it be related to the fact that one of the apps is SSR? It could be hard to provide a similar setup using codesandbox or any other tool, but I'm not doing anything special and both apps are working separately, but not together. 

In my case, there is a project, which provides a header/content/footer as one project and then I render a different app in the content placeholder.

**Comment by piotrl88** [comment]
Yep, so the issue I had was related to the SSR. I didn't warp the `renderToString` method with `renderStylesToString` after that change everything starts to work.

**Comment by Andarist** [comment]
You might find [this answer](https://github.com/emotion-js/emotion/issues/2210#issuecomment-758577800) useful if you are mixing Emotion 10 and Emotion 11 on the same page.
