### ISSUE TITLE
shouldForwardProp breaks code highlighting

### ISSUE THREAD

**Issue by jukkahuuskonen** [emotion-js/emotion#2208]
I've seen emotion stuff recomending to use vscode-styled-components extension to highlight the code, saying that it should work with Emotion too. I found a problem there. Not sure if this should have been classified as bug, feature request or something else, but since it's something that doesn't work the way we are told, I thought bug is proper classification. This might a reason to fork that vscode-styled-components extension...

**Current behavior:**
Highlighting break if **shouldForwardProps** is used in Emotion style. Styled components version works fine.

**To reproduce:**
I can't show it in CodeSandBox, since it is related to using vsCode with an extension suggested by Emotion, but here is a short code that can be pasted in any .js file in a emotion project
```
import styled from 'emotion/styled';

// Styled component with shouldForwardProps written in Emotion style breaks highlighting
export const EmotionStyleWithoutSFP = styled('div', {
  shouldForwardProps: prop => !['color'].includes(prop),
})`
  display: grid;
  grid-template-columns: min-content 1fr;
  color: ${({ color = 'green' }) => color};
`;

// Styled component without shouldForwardProps written in Emotion style works fine
export const EmotionStyleWithoutSFP = styled('div')`
  display: grid;
  grid-template-columns: min-content 1fr;
  color: ${({ color = 'green' }) => color};
`;

// Styled component with shouldForwardProps written in Styled Components style works fine
export const StyledComponents = styled('div').withConfig({
  shouldForwardProps: prop => !['color'].includes(prop),
})`
  display: grid;
  grid-template-columns: min-content 1fr;
  color: ${({ color = 'green' }) => color};
`;
```
And here is a screenshot of VSCODE with that code:
![image](https://user-images.githubusercontent.com/42405685/104130813-86a56080-537b-11eb-9c2f-fcba7fea5273.png)

**Expected behavior:**
Highlighting to work correctly with **shouldForwardProp**

**Environment information:**
```
    "react": "16.14.0",
    "@emotion/react": "^11.1.4",
    "@emotion/styled": "^11.0.0",
```

**Comment by Andarist** [comment]
Since nowadays Styled Components supports `shouldForwardProp` I think it would be best to file this issue to `vscode-styled-components`

**Comment by jukkahuuskonen** [comment]
Just to add here this:
They support it, but with different format than Emotion and their vscode extension works with their format, not Emotions. I doubt they are interested in fixing their extension to work with other library. My example shows clearly that SC-style works and Emotion style does not.

I do understand if you are not interested in creating a fork that would work with Emotion too.

**Comment by Andarist** [comment]
Could you post how their format looks like?

**Comment by jukkahuuskonen** [comment]
It's up there in the first post, but they use the **.withConfig()** before backticks 

```
// Styled component with shouldForwardProps written in Styled Components style works fine
export const StyledComponents = styled('div').withConfig({
  shouldForwardProps: prop => !['color'].includes(prop),
})`
  display: grid;
  grid-template-columns: min-content 1fr;
  color: ${({ color = 'green' }) => color};
`;
```

This also works with HTML-tags without the parentheses like this:
```
// Styled component with shouldForwardProps written in Styled Components style works fine
export const StyledComponents = styled.div.withConfig({
  shouldForwardProps: prop => !['color'].includes(prop),
})`
  display: grid;
  grid-template-columns: min-content 1fr;
  color: ${({ color = 'green' }) => color};
`;
```

This was quite recent addition to Styled Components. Half a year ago they still had the same problem with highlighting.

**Comment by Andarist** [comment]
Looking in their code they also support it as part of the `options` argument - the same way we do:
https://github.com/styled-components/styled-components/blob/08390f25fa7e353107f0a30080075104cec6426f/packages/styled-components/src/models/StyledComponent.js#L183

So I would still say that it's worth reporting this to the `vscode-styled-components`.

**Comment by jukkahuuskonen** [comment]
Ok, thanks. I didn't realize they support the same format. I haven't seen that in their documentation. I'll raise the matter there. I'll return back here if Styled Components is deprecating this format.
