### ISSUE TITLE
Global styling overriding component specific style

### ISSUE THREAD

**Issue by se7entyse7en** [emotion-js/emotion#2213]
**Current behavior:**

When a global style is defined with `Global` from `'@emotion/react'` and a component styled with a `css` prop, if the CSS selector used by the global style is more specific, then the style applied to the component is not applied, but overridden.

**To reproduce:**

https://codesandbox.io/s/emotion-issue-template-forked-rrrvj

**Expected behavior:**

The style defined to the component has priority over the global one.

**Environment information:**

See codesandbox.

- `react` version: 16.8.6
- `@emotion/react` version: 11.1.4

Actually, I don't know whether this is indeed a real bug or if I misinterpret how `Global` should be used and works. Alternatively, I was thinking to achieve the same but using the `ThemeProvider` instead.

I asked about this in SO as well: https://stackoverflow.com/questions/65735748/emotionjs-react-global-styling-overriding-component-specific-style.

**Comment by oliviertassinari** [comment]
I think that it should be closed, the behavior @se7entyse7en looks expected. His global CSS selector has more specicity: https://codepen.io/oliviertassinari/pen/KKgboXe.

**Comment by Andarist** [comment]
Yep, i believe the same - only left open so he could have a chance to respond.

Going to close now though - feel free to comment at any time.

**Comment by se7entyse7en** [comment]
Thanks both for the clarifications. It was then just a misalignment on the expected behavior being the global style always having less priority despite the specificity of the rules.

**Comment by Andarist** [comment]
There is just not a way to tell CSS to treat a particular rule/style as the highest priority thing. So its actually just impossible for us to implement this other way around.
