### ISSUE TITLE
Please add "option", "fallback" properties for amp html to whitelist

### ISSUE THREAD

**Issue by ka2jun8** [emotion-js/emotion#2224]
**The problem**

When we use `styled-components` and `amp` , the needed properties for amp are not rendered, 
because `@emotion/is-prop-valid` does not allow these properties.

**Proposed solution**

I would like to add properties `option`, `fallback` in `packages/is-prop-valid/src/props.js`.

**Alternative solutions**

workaround is like this:

```
  const Parent = styled.div`
     .option {
        color: red;
      }
  `

  <Parent>
    <div className="option" option="sample">color is red</div>
  </Parent>
```
But we need a useless DOM.

**Additional context**

Almost same situations here:
- https://github.com/styled-components/styled-components/issues/2689
- https://github.com/emotion-js/emotion/pull/1584

Reference:
- https://amp.dev/documentation/components/amp-selector/
- https://amp.dev/documentation/guides-and-tutorials/learn/common_attributes/

Example:
https://codesandbox.io/s/magical-tharp-9kutn?file=/src/App.js

**Comment by Andarist** [comment]
@probablyup any objections against adding those? I personally have unpleasant sensations in my stomach when I think about adding amp-related props but we've done that in the past so 🤷‍♂️

**Comment by probablyup** [comment]
@Andarist I think it's fine; y'all should consider considering transient props in v12 so you can drop this whitelist though IMO
