### ISSUE TITLE
Getting FOUC issue with @emotion/css + Next.js when production build but dev mode is fine

### ISSUE THREAD

**Issue by jthcast** [emotion-js/emotion#2225]
**Current behavior: Getting FOUC issue with @emotion/css + Next.js when production build but dev mode is fine**

my repo: https://github.com/jthcast/techblogposts

**To reproduce:**

1. when ```yarn dev``` it doesn't cause FOUC. and styles tags are working
![image](https://user-images.githubusercontent.com/49227119/105863205-fda54f00-6033-11eb-99fc-79b6682c0ac2.png)
2. but when ```yarn build``` and ```yarn start``` it cause FOUC. and style tags are empty but css is working.
![image](https://user-images.githubusercontent.com/49227119/105863610-68568a80-6034-11eb-91aa-2747ba818950.png)
3. i'm not using @emotion/react. only using @emotion/css.

**Expected behavior: should render without FOUC issue**

**Environment information:**
```
"dependencies": {
    "@aws-sdk/client-dynamodb": "^3.2.0",
    "@emotion/css": "^11.1.3",
    "html-entities": "^2.0.2",
    "next": "10.0.5",
    "next-pwa": "^5.0.3",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "rss-parser": "^3.10.0"
  },
  "devDependencies": {
    "@types/gtag.js": "^0.0.4",
    "@types/node": "^14.14.20",
    "@types/react": "^17.0.0",
    "@vercel/node": "^1.8.5",
    "typescript": "^4.1.3"
  }
```

- `react` version: 17.0.1
- `@emotion/css` version: ^11.1.3

**Comment by vinomuse** [comment]
I have same issues. I'm using emotion.

Dev mode is fine, but production mode has FOUC issue.

* `react` version: 16.12
* `next` version: ^9.4.4
* `@emotion/core`: ^10.0.34

**Comment by vinomuse** [comment]
> **Current behavior: Getting FOUC issue with @emotion/css + Next.js when production build but dev mode is fine**
> 
> my repo: https://github.com/jthcast/techblogposts
> 
> **To reproduce:**
> 
> 1. when `yarn dev` it doesn't cause FOUC. and styles tags are working
>    ![image](https://user-images.githubusercontent.com/49227119/105863205-fda54f00-6033-11eb-99fc-79b6682c0ac2.png)
> 2. but when `yarn build` and `yarn start` it cause FOUC. and style tags are empty but css is working.
>    ![image](https://user-images.githubusercontent.com/49227119/105863610-68568a80-6034-11eb-91aa-2747ba818950.png)
> 3. i'm not using @emotion/react. only using @emotion/css.
> 
> **Expected behavior: should render without FOUC issue**
> 
> **Environment information:**
> 
> ```
> "dependencies": {
>     "@aws-sdk/client-dynamodb": "^3.2.0",
>     "@emotion/css": "^11.1.3",
>     "html-entities": "^2.0.2",
>     "next": "10.0.5",
>     "next-pwa": "^5.0.3",
>     "react": "17.0.1",
>     "react-dom": "17.0.1",
>     "rss-parser": "^3.10.0"
>   },
>   "devDependencies": {
>     "@types/gtag.js": "^0.0.4",
>     "@types/node": "^14.14.20",
>     "@types/react": "^17.0.0",
>     "@vercel/node": "^1.8.5",
>     "typescript": "^4.1.3"
>   }
> ```
> 
> * `react` version: 17.0.1
> * `@emotion/css` version: ^11.1.3

I solved the issue. FOUC is related with order of font loading.

I changed link in head tag instead of @import.

**Comment by vinomuse** [comment]
> I have same issues. I'm using emotion.
> 
> Dev mode is fine, but production mode has FOUC issue.
> 
> * `react` version: 16.12
> * `next` version: ^9.4.4
> * `@emotion/core`: ^10.0.34

I solved the issue right now. FOUC is related with order of font loading.

I changed link in head tag instead of @import.

**Comment by jthcast** [comment]
Unfortunately that's not work for me 😥

**Comment by jthcast** [comment]
Solve problem. It was SSR issue.

emotion said 
>This only applies if you’re using vanilla Emotion or a version of Emotion prior to v10. For v10 and above, SSR just works in Next.js.

**I didn't knew vanilla Emotion is @emotion/css**
i thought it was Emotion or @emotion/core 😥
and emtion linked An example of Next.js with emotion can be found in the Next.js repo to https://github.com/zeit/next.js/tree/master/examples/with-emotion
but @emotion/css need https://github.com/vercel/next.js/tree/canary/examples/with-emotion-vanilla

i tried https://github.com/vercel/next.js/tree/canary/examples/with-emotion-vanilla and it work.

should change explain Vanilla Emotion to @emotion/css. because there is nowhere about vanilla emotion in emotion.sh.
i was new to Emotion and it confuse me.
