### ISSUE TITLE
Generated class labels in dev do not match server render causing a react error

### ISSUE THREAD

**Issue by nathanmarks** [emotion-js/emotion#2226]
**EDIT:** the main reason for this happening in my case is that the components in the package are anonymous functions inside forwardRef and the name cannot be resolved for other purposes as well such as react dev tools locally (fixing that resolves the issue as the client and server both pull the correct name from the stack). While this should be fixed, I still think a way to disable the functionality below would be useful should anything similar arise again.

---

In local dev, where we get react errors for client/server mismatch, emotion is causing issues with some of our components.

We have a number of components in a separate package, and due to what I presume to be some slight differences in our server build and our client build, and how the stack traces are built on the server, we end up with a classname mismatch due to this code: https://github.com/emotion-js/emotion/blob/1ee34005a5e02c9041b36f73395700f1965388eb/packages/react/src/emotion-element.js#L42-L57

I put a breakpoint on the code linked above to see what's going on. Here's a client stacktrace example for a problem component:
![image](https://user-images.githubusercontent.com/4420103/105870316-24c53780-5fc6-11eb-82d9-dc79379c185c.png)

Here's the stack on the server:
![image](https://user-images.githubusercontent.com/4420103/105870284-1bd46600-5fc6-11eb-9d4c-614ce118687b.png)

So the server generates a class name with `-Object` at the end, and the client doesn't attach a label at all.

Until this is resolved, is there any way to disable this functionality? This is preventing us from exposing other client server render mismatch errors easily

**Comment by fracture91** [comment]
The root cause is probably covered in https://github.com/emotion-js/emotion/issues/2134 / https://github.com/emotion-js/emotion/pull/2136 - but I agree a feature toggle would be nice
