### ISSUE TITLE
IE11 -  unable to get property '__emotion_forwardProp of undefined or null reference

### ISSUE THREAD

**Issue by trickydisco78** [emotion-js/emotion#2236]
**Current behavior:**

Using Chakra UI that comes with emotion. Getting an error in IE11

```
unable to get property '__emotion_forwardProp of undefined or null reference 
```

![image](https://user-images.githubusercontent.com/3627429/106485106-27cd9580-64a8-11eb-8dc3-85e4fe4e3a7b.png)

Looks like it's here

https://github.com/emotion-js/emotion/blob/fa977675e1df05f210005ccd3461d6cdaf941b42/packages/styled/src/utils.js#L50

**Environment information:**

- ` "react": "^16.13.1",
- `@emotion/react` version:
-     "@chakra-ui/core": "^1.0.0-rc.7",

**Comment by Andarist** [comment]
This is coming from a required parameter of the `createStyled` function:
https://github.com/emotion-js/emotion/blob/fa977675e1df05f210005ccd3461d6cdaf941b42/packages/styled/src/base.js#L22
I'm honestly not sure what would you expect us to do here - it seems like an integration problem in the consuming package or just an issue with IE11 env that makes things call our function with `undefined` or `null` but this doesn't seem to be a problem with Emotion

**Comment by trickydisco78** [comment]
Hi,

Thanks for the response. 

I raised it to try and understand what is happening at this point and what the function is expecting.. Or that you might have come across this before?

I originally raised this with Chakra UI but they responded saying it's most likely an emotion (but only from seeing 'emotion in the line call)

I believe i have now tracked it down to framer motion (which is a dep of chakra) and the way they are using functions in framer motion

https://github.com/chakra-ui/chakra-ui/issues/2498

https://github.com/framer/motion/pull/781

I just wanted to understand why it was an emotion function throwing the error but perhaps it's like you say something in chakra calling the emotion APi with null or undefined

**Comment by Andarist** [comment]
> I just wanted to understand why it was an emotion function throwing the error but perhaps it's like you say something in chakra calling the emotion APi with null or undefined

Yes, it kinda has to be like that. I don't have experience with those libraries to investigate this further but I don't see anything broken on our side so far. Therefore I'm going to close this issue and I encourage you to debug this - it should give you information of what exact code is calling to Emotion incorrectly.
