### ISSUE TITLE
Restyling base component with same prop

### ISSUE THREAD

**Issue by jukkahuuskonen** [emotion-js/emotion#2237]
**Current behavior:**
Restyling a styled **Base** component still accesses **Base** component CSS. If I am redefining the **background-color** using the same **color** prop used in base component it still falls back to **Base** CSS and requires it to be functional code

**To reproduce: /sandbox below steps**
1. Define a **Base** component styled with **styled** api. 
2. Add **background-color** defined with **color**-prop, which accesses some theme with color names.
3. Define a new **StyledBase** component based on **Base**-component
4. Add a new definition overriding definition for **background-color** with using the same **color**prop
5. Add **shouldForwardProp**-to block passing **color**-prop down.

Here is the [sandbox ](https://codesandbox.io/s/emotion-issue-template-forked-c9rj6?file=/src/index.js)with working demonstration of problem. Using a color (eg, purple) in **StyledBase** still tries to access the **Base** component styled CSS code. And since `purple` cannot be found from theme object **(baseColors)** accessing any properties of undefined object crashes code.

CSS for the **Base** component can be modified to accommodate the problem, but I think it shouldn't be needed as I am overriding the **background-color** in **StyledBase** and also blocking **color** prop from being forwarded.

In any case here is a [sandbox](https://codesandbox.io/s/emotion-issue-template-forked-lr1nr?file=/src/index.js) on how this can be overcome. It is definetly not hard to fix, atleast for this particular problem, but I this shouldn't be needed.
**Expected behavior:**

If I override **Base** component **background-color** CSS like I do with **StyledBase**, it shouldn't use the **Base** component **background-color** at all. If **StyledBase** background color is not proper CSS, it still shouldn't fall back to **Base** component styles and instead use just improper not working CSS code which browsers will ignore (eg. `background-color: arthurDent;`).

**Environment information:**
![image](https://user-images.githubusercontent.com/42405685/106608835-8d378a00-656d-11eb-83c3-f1cca1502c7c.png)

**Comment by Andarist** [comment]
This is expected - filtering out base declarations would inquire a rather heavy performance penalty and also there are cases in which this wouldn't be desirable at all. Take for example this into consideration:
```js
const Base = styled("div")`
  color: white;
`;

const StyledBase = styled(Base)`
  color: ${({ danger }) => danger && 'black'};
`;
```

**Comment by jukkahuuskonen** [comment]
ok, I understand. I'll take it as a feature then :) Just wanted to make sure it wasn't a bug. Closing this myself. Thanks!
