### ISSUE TITLE
`as` prop causes TypeError when wrapping components

### ISSUE THREAD

**Issue by wolszczak96** [emotion-js/emotion#2238]
**Current behavior:**

`as` prop causes TypeError for components utilizing that prop wrapped in styled()

**To reproduce:**

https://codesandbox.io/s/quizzical-kalam-xvgve?from-embed=&file=/src/App.tsx

**Expected behavior:**

I guess `CreateStyled` shouldn't extend props with `as` prop for all cases extending components. (only for IntrinsicElements)

**Environment information:**

- `react` version: latest
- `@emotion/react` version: latest

**Comment by wolszczak96** [comment]
Shouldn't these lines just be removed? `as` prop is forwarded to components anyways, so why is it specified for them too? I think specifying it only for `IntrinsicElements` should be sufficient. Hmm... maybe not for composing components, but I guess it would be possible to create separate case for that.

https://github.com/emotion-js/emotion/blob/master/packages/styled/types/base.d.ts#L131
https://github.com/emotion-js/emotion/blob/master/packages/styled/types/base.d.ts#L145
https://github.com/emotion-js/emotion/blob/master/packages/styled/types/base.d.ts#L164
https://github.com/emotion-js/emotion/blob/master/packages/styled/types/base.d.ts#L174

**Comment by Andarist** [comment]
But `as` is actually handled by almost all styled components. Could you create a repro real-life repro case with `Link from 'next/link'`? The provided one doesn't quite showcase the real problem.

**Comment by wolszczak96** [comment]
Sure. Just updated the codesandbox from the first post.
I also have a case with ref-forwarding components using render props with typing based on React.HTMLProps, which also contains the `as` prop.

Sure, but I think you mean styled components like `styled.div`, `styled.span` (_case 1_). But for wrapping any `styled(Component)` (_case 2_), the `as` prop is not in use at all, it's just forwarded (at least by default). I think the lines I mentioned in prev comment only affect the _case 2._

Also, for wrapping like this:
```
const Div = styled.div``
const Another = styled(Div)`` // Div component already has props extended with `as` prop, so wrapping it again (which I believe, is the "case 2") doesn't need to add the `as` prop again.
```

**Comment by Andarist** [comment]
Hmm, after re-checking a bunch of stuff - you are right. Support for `as` can be only added for composite components if you provide `shouldForwardProp` that doesn't forward the `as` prop.

I would accept a PR fixing this :wink:

**Comment by wolszczak96** [comment]
Not sure what kind of fix you have in mind. 😅 
> if you provide `shouldForwardProp` that doesn't forward the `as` prop

yeah, that's the current behaviour, but I don't think it is possible to conditionally change the TypeScript typing based on passing something like `shouldForwardProp: prop => prop !== 'as'`.

I could do that utilising some additional prop, like `shouldForwardAsProp`, but it's stupid.

The only solution I can think of right now is not adding the `as` prop to the type when wrapping composite components, but that will result in wrong typing when you pass the `shouldForwardProp` as above.

But on the other hand, are there any real-life examples of needing to render composite component `as` a html tag? You lose all the functionality of the wrapped component, the typing is probably wrong in most cases, as your wrapped component is probably using some fancy props, which are not applicable to html tags.

So I suggest removing the `as` prop from type definitions for composite components completely. Any thoughts?

**Comment by Andarist** [comment]
> yeah, that's the current behaviour, but I don't think it is possible to conditionally change the TypeScript typing based on passing something like shouldForwardProp: prop => prop !== 'as'.

Yeah, this is impossible/hard. If one wants to add support for `as` prop for their wrapped custom components then they can do this manually.

> The only solution I can think of right now is not adding the as prop to the type when wrapping composite components, but that will result in wrong typing when you pass the shouldForwardProp as above.

That's fine - this should usually be a rare situation and the full relation between input props, `shouldForwardProp` and the forwarded props is not validated anyway.

> So I suggest removing the as prop from type definitions for composite components completely. Any thoughts?

That aligns with my current way of thinking about this - please only make sure to add some basic tests for the expected behavior.
