### ISSUE TITLE
&:focus not working

### ISSUE THREAD

**Issue by Emma-Jay** [emotion-js/emotion#2241]
I am following an issue &:focus not working #1114,
my case is the codesandbox project works great but on my local device, the code does not in spite of having the same dependencies.  The link to codesandbox https://codesandbox.io/s/solitary-voice-vk1m9?file=/src/App.js

**Comment by Andarist** [comment]
I can only confirm that the codesandbox you have given works fine - I can't really look into your case more if I don't know how to reproduce your issue.

**Comment by Emma-Jay** [comment]
Thank you, I have to reproduce it from my codesandbox.
