### ISSUE TITLE
@emotion/babel-plugin: Support namespace Babel config option

### ISSUE THREAD

**Issue by hantatsang** [emotion-js/emotion#2242]
**The problem**

When working with micro frontends:

1. Current class name in `dev` contains the name of the React component. With micro frontends, the generated class name doesn't tell which micro frontend app does it come from. This doesn't provide a good DX.
1. Potential class name collision between micro frontend's apps/services?

**Proposed solution**

Similar to `styled-components`, support a `namespace` option in Babel config:

```json
{
  "plugins": [
    [
      "@emotion",
      {
        "autoLabel": "dev-only",
        "namespace": "micro-frontend-app-01"
      }
    ]
  ]
}
```

The usage in a micro frontend project is that I can generate separate Emotion Babel config for each app/service with a unique `namespace` value.

The generated class name can then look something like this format (_note_: `labelFormat` is `[local]` by default)

|Before|After|
|---|---|
| `css-[id]-[labelFormat]` | `css-[id]-[namespace]-[labelFormat]` |

**Alternative solutions**

N/A

**Additional context**

`babel-plugin-styled-components` supports this feature:

- https://styled-components.com/docs/tooling#namespace

I would like to have this feature so that I can migrate to Emotion

**Comment by Andarist** [comment]
You should be able to achieve this using:
```
labelFormat: 'micro-frontend-app-[local]'
```

**Comment by hantatsang** [comment]
Nice and easy, thanks!
