### ISSUE TITLE
[@emotion/eslint-plugin] the syntax-preference rule does not account for `css` function when checking check css props

### ISSUE THREAD

**Issue by G-Rath** [emotion-js/emotion#2243]
**Current behavior:**

When using the `css` helper with the `css` prop, `@emotion/syntax-preference` doesn't think it's in object form:

```
ESLint: Styles should be written using objects.(@emotion/syntax-preference)
```

While it does work when you pass the object directly to the `css` prop, my understanding (and experience irl) is that the `css` function allows for stronger type-checking when using TypeScript.

If I set the style to `string`, then it does not error if I use `css` - I suspect this is probably the result of a fallback (i.e it checks "if is object else is string").

**To reproduce:**

```
import { css } from '@emotion/react';

function App() {
  return (
    <div css={appClassName}>
      <Title>Hello CodeSandbox</Title>
      {/* Inline CSS prop example with object notation */}
      <h2 css={css({ fontSize: 20 })}>
        Start editing to see some magic happen!
      </h2>
    </div>
  );
}
```

**Expected behavior:**

There to be no eslint warning on the `css` prop.

**Environment information:**

- `react` version: 17.0.1
- `@emotion/react` version: 11.1.5
- `@emotion/eslint-plugin` version: 11.0.0

**Comment by Andarist** [comment]
It should be fairly easy to add support for `css` helper in those 2:
https://github.com/emotion-js/emotion/blob/2fe9e0e945be8a933521a96c2a242c5b397aa846/packages/eslint-plugin/src/rules/syntax-preference.js#L6-L49

PRs are very much welcome here 😉

**Comment by hantatsang** [comment]
@G-Rath Do you have a repo to reproduce this issue?
