### ISSUE TITLE
ThemeProvider not working with nextjs?

### ISSUE THREAD

**Issue by subhendukundu** [emotion-js/emotion#2251]
**Current behavior:**
I was playing around with nextjs with emotion and I wanted to add a theme to a project. Apparently, the theme object is empty when trying to access it with

```
const theme = useTheme();
console.log(theme);
 ```
or using
```
css={theme => ({ color: theme.colors.primary })}
```

**To reproduce:**
https://codesandbox.io/s/amazing-christian-t30ko?file=/pages/index.js

**Expected behavior:**
It should get theme object.

**Comment by maddhruv** [comment]
Hey @subhendukundu I tried running your sandbox, seems fine to me 😕 
<img width="323" alt="Screenshot 2021-03-30 at 19 39 18" src="https://user-images.githubusercontent.com/18121502/113002741-b51f2480-918f-11eb-82df-cac2727d92be.png">

**Comment by subhendukundu** [comment]
Super weird! It wasn't working. Now I guess something has changed, which fixed it?

**Comment by maddhruv** [comment]
> which fixed it?

I am not sure, I just ran your sandbox 🚶🏽‍♂️

**Comment by Andarist** [comment]
Since the issue is not reproducible anymore on the provided codesandbox - I'm going to close this one. Thanks @maddhruv for checking this out!
