### ISSUE TITLE
@emotion 11 specificity with stylis-plugin-extra-scope not working currently

### ISSUE THREAD

**Issue by nelsondude** [emotion-js/emotion#2253]
**Current behavior:**

Using https://www.npmjs.com/package/stylis-plugin-extra-scope to give emotion classes a higher css specificity does not currently work on emotion 11. Original issue: https://github.com/emotion-js/emotion/issues/712

I'm trying to utilize emotion cache with some stylis plugins to give each emotion class a higher specificity by using https://www.npmjs.com/package/stylis-plugin-extra-scope . This seemed to be working on emotion 10 but on emotion 11 this is no longer working. 

**To reproduce:**

Not working with emotion 11: https://codesandbox.io/s/increase-css-specificity-forked-pzlej?file=/index.js
Working with emotion 10: https://codesandbox.io/s/increase-css-specificity-e8k5u?file=/index.js:261-286

**Expected behavior:**

The generated selectors by emotion should all have a id prepended so that the selectors are more specific than other regular class selectors.

**Environment information:**

- `react` version: Latest (see codesandbox)
- `@emotion/react` version: Latest (see codesandbox)

**Comment by Andarist** [comment]
This shouldn't be reported here - it's not Emotion's fault that some plugin doesn't work with it. Emotion 11 is using Stylis 4 and this plugin [has a warning in its README that it currently works with Stylis 3](https://github.com/Andarist/stylis-plugin-extra-scope#stylis-plugin-extra-scope). 

You might want to try out the version from this PR: https://github.com/Andarist/stylis-plugin-extra-scope/pull/11 but I haven't had a chance to test it.
