### ISSUE TITLE
Multiple instances of emotion collision

### ISSUE THREAD

**Issue by jackmoore** [emotion-js/emotion#2260]
Hi, I'm having a very similar problem as ticket #2222 where one app is wiping out the styles of another, but my use-case is different. 

In my case both widgets are using emotion 11.1.3. I'm using framework agnostic approach, so I'm not taking advantage of React-specific functionality like CacheProvider. I bundle the apps using webpack and the issue only manifests when I use production builds (e.g., `webpack --mode=production`)

**Comment by jackmoore** [comment]
For posterity, creating a unique instance of emotion for each project using `createEmotion` from `@emotion/css/create-instance` resolved my issue.

**Comment by nelsondude** [comment]
@jackmoore does this also work with @emotion/styled?

**Comment by jackmoore** [comment]
@nelsondude Sorry, I'm unsure
