### ISSUE TITLE
Append custom class names to styled component

### ISSUE THREAD

**Issue by iamturner** [emotion-js/emotion#2268]
Is it possible to have classes added via the className prop of a styled component be appended to the end of the class list instead of the start.

Take this button component as an example, which has a custom class added.
```
const Button = styled('button')(...);

<Button className="my-class">Click Me</Button>
```
Currently results in:
```
<button class="my-class css-6r523">Click Me</button>
```

I would like the `my-class` to be AFTER the `css-6r523` class, like so:
```
<button class="css-6r523 my-class">Click Me</button>
```
Is there any way to achieve this, either through React or Babel or something else?

Thanks.

**Comment by Andarist** [comment]
No, there is no way of doing that **but** it doesn't matter - both ways are semantically equivalent and there is no difference in what styles your component will get in the end.

**Comment by iamturner** [comment]
I could have a situation were css classes are being used to modify styling. The emotion css-* class will overwrite any styles added by my-class.

**Comment by Andarist** [comment]
This is a common misconception but the order in which you put your class names onto an element doesn't matter. What matters is the order in which those classes are put into a stylesheet. This means that given this CSS and the following HTML you will **always** have a red background for both elements:
```css
.blue { background-color: blue; }
.red { background-color: red; }
```
```html
<div class="blue red">I'm red</div>
<div class="red blue">and I'm red too</div>
```

Check out the live demo: https://codesandbox.io/s/dank-https-gy6v0?file=/src/index.js


This is mentioned, among other things, in one of our documentation pages: https://emotion.sh/docs/composition

**Comment by iamturner** [comment]
Thanks for the demo. That makes sense. If my-class for example was in another stylesheet, is there way to make sure emotion's style tags are placed before it

**Comment by Andarist** [comment]
Should be possible with CacheProvider and prepend option: https://emotion.sh/docs/@emotion/cache#prepend . Works pretty much similar to `@emtion/css/create-instance` (which you have mentioned by referring to create-emotion)

**Comment by iamturner** [comment]
Thank for your help @Andarist. CacheProvider looks like it does the job.
