### ISSUE TITLE
CSS is being displayed on page shortly before being hidden

### ISSUE THREAD

**Issue by Vadorequest** [emotion-js/emotion#2286]
**Current behavior:**

The CSS is being displayed within the page before being hidden. (flash)

Here's the content that's being displayed:
```html
<style data-emotion="css 1s3l8we" data-s="">.css-1s3l8we{margin:0 45px 0 45px;position:absolute;cursor:pointer;display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;-webkit-box-pack:justify;-webkit-justify-content:space-between;justify-content:space-between;}.css-1s3l8we:focus{outline:none;}.css-1s3l8we .label{cursor:default;}@media (max-width: 991.98px){.css-1s3l8we{width:100%;-webkit-box-pack:left;-ms-flex-pack:left;-webkit-justify-content:left;justify-content:left;margin:0;}.css-1s3l8we .label{margin-left:25px;}.css-1s3l8we .stamps,.css-1s3l8we .links,.css-1s3l8we .contact,.css-1s3l8we .column-divider{display:none;}}</style>
```

![image](https://user-images.githubusercontent.com/3807458/111036501-c8a45e80-841f-11eb-9b58-4a122aebe731.png)

It's been happening for months, it's not something new.

**To reproduce:**

Happens only within my private app and I don't know what's causing this, can't reproduce it.

Go to https://tfp-sc1-2l-1c-xp-37wm0wymn-unly.vercel.app/en/solutions displays the flash. Lowering the network speed (Console Network settings) makes the transition a bit slower.

**Expected behavior:**

It shouldn't display the CSS on the page

**Environment information:**

- `react` version: 17.0.1
- `@emotion/react` version: 11.1.4

**Comment by Vadorequest** [comment]
This might be related to Next.js and SSR/SSG. This issue doesn't happen when using CSR (client-side rendering).

**Comment by Andarist** [comment]
You have styles like:
```css
@media (min-width: 992px) {
  .css-128alnn > * {
    display: -webkit-box !important;
    display: -webkit-flex !important;
    display: -ms-flexbox !important;
    display: flex !important;
  }
}
```

And by default for the SSR content Emotion renders `<style>` elements "inline" - they pop up within the body, together with components that require those styles. They are later moved to the head automatically but the whole process makes selectors like yours unstable when using default SSR.

You need to either change this selector to accommodate for this - you could do it by changing the selector to  `>:not(style)` - or you our "advanced" SSR setup which includes tinkering with `extractCritical` API.

**Comment by Vadorequest** [comment]
Okay, thanks for pointing out the issue, I had completely forgotten about that.

> Warning: This approach can interfere with nth child and similar selectors as it is inserts style tags directly into your markup. You will get a warning if you use such selectors when using this approach. - https://emotion.sh/docs/ssr

I haven't seen such warnings. Where are they supposed to be displayed?

Is there an eslint mod for detecting this? Ideally, I'd prefer not to complicate the Next.js/Emotion configuration, while ensuring such edges cases are properly detected.

Also, this behavior doesn't happen locally, but only when the website is deployed, which makes it much harder to detect/debug.

**Comment by Vadorequest** [comment]
Using 

```
> div {
  display: flex;
  align-items: center;

  @media (min-width: 992px) {
    display: flex !important; // Overrides bootstrap to force using flex with desktop to center vertically elements
  }
}
```

instead of

```
> * {
  display: flex;
  align-items: center;

  @media (min-width: 992px) {
    display: flex !important; // Overrides bootstrap to force using flex with desktop to center vertically elements
  }
}
```

fixed the issue.

**Comment by Andarist** [comment]
> I haven't seen such warnings. Where are they supposed to be displayed?

Not all selectors are validated right now - the detection could definitely be improved there. The logic for it is here: https://github.com/emotion-js/emotion/blob/71ca9be3368ddb0a95ef5b2db7a97c67ab440593/packages/cache/src/stylis-plugins.js#L133
