### ISSUE TITLE
remove composes property

### ISSUE THREAD

**Issue by tkh44** [emotion-js/emotion#229]
Problem description:
We don't need this anymore because expressions work everywhere.

Suggested solution:
Remove composes and related code.

related #209

**Comment by thangngoc89** [comment]
Pure CSS is coming back to emotion

**Comment by tkh44** [comment]
I haven't moved on this because after talking to @mitchellhamilton we both think there is some unexplored power in `composes`. The internal mechanics of `composes` are very powerful and I'm hesitant to remove them right now. On the other side of this is the fact that removing composes would simplify a lot of code 😄

**Comment by tkh44** [comment]
we removed it in v8
