### ISSUE TITLE
Wrong webkit prefix for position sticky

### ISSUE THREAD

**Issue by isBatak** [emotion-js/emotion#2298]
**Current behavior:**

```
<div
      css={css`
        position: sticky;
      `}
>
      Sticky
</div>
```
this code produces incorrect CSS:
```
.css-y7a1g9-App {
    -webkit-position: sticky;
    position: sticky;
}
```

**To reproduce:**

https://codesandbox.io/s/emotion-sticky-webkit-prefix-9959g?file=/src/App.js

**Expected behavior:**

Generated CSS should look like this
```
.css-y7a1g9-App {
    position: -webkit-sticky; /* Safari */
    position: sticky;
}
```

**Environment information:**

- `react` version: 16.14.0
- `@emotion/react` version: 11.1.5

**Comment by isBatak** [comment]
I figured out it's an issue with `stylis` https://github.com/thysultan/stylis.js/issues/257

**Comment by Andarist** [comment]
Yep, let's close this here - we'll track this in the Stylis repo.
