### ISSUE TITLE
Duplicated CSS properties when using `min()` or `max()` function in dev/test mode when using `styled`.

### ISSUE THREAD

**Issue by gregaubert** [emotion-js/emotion#2306]
**Current behavior:**

When using `min()` or `max()` CSS functions in some properties (currently found: `width`, `height`, `min-width`, `min-height`, `max-width`, `max-height`), the properties are generated two times in the emotion class. It should be generated only once.
This bug is not happening in production mode, only in dev mode or in test snapshots (tested with enzyme).

**To reproduce:**
See this CodeSandbox with the reproduction: https://codesandbox.io/s/emotion-doubled-css-properties-using-maxmin-3k7fc?file=/src/App.js

You just need to inspect the red block and check the generated styling, see this screenshot:
![image](https://user-images.githubusercontent.com/1725611/112182085-4543f380-8bfd-11eb-9b68-c2d6bbcd3ab8.png)

And here is a link to the production version of the same code, we see there that with the production build the issue doesn't exist: https://csb-3k7fc.netlify.app/

**Expected behavior:**

We should have the same result in prod, in dev and in test. Which is having only one occurrence of the properties that are currently duplicated (like for the properties of the green square of the reproducer).

**Environment information:**

- `react` version: 17.0.2
- `react-dom` version: 17.0.2
- `react-scripts` version: 4.0.0
- `@emotion/react` version: 11.1.5
- `@emotion/styled` version: 11.1.5

**Comment by Andarist** [comment]
> And here is a link to the production version of the same code, we see there that with the production build the issue doesn't exist: https://csb-3k7fc.netlify.app/

The production build suffers from the same issue - it's just that `.insertRule` API prunes duplicate declarations so you don't see them.

---

I've prepared a fix here: https://github.com/thysultan/stylis.js/pull/259
