### ISSUE TITLE
[@emotion/react] None of Babel Macros or @emotion/babel-plugin or JSX Pragma or babelrc are working in CRA4.0.2+TS4

### ISSUE THREAD

**Issue by yokiijay** [emotion-js/emotion#2307]
## Here is the code, and I strictly follow the official documentation, but it just won't work, I met this problem since last year, and still.
https://codesandbox.io/s/emotion-issue-template-forked-bygp6?fontsize=14&hidenavigation=1&theme=dark

**Comment by Andarist** [comment]
I see that you are using Emotion 10 there so this is the correct way of using this:

https://codesandbox.io/s/emotion-issue-template-forked-wzwv1?file=/src/index.js

**Comment by yokiijay** [comment]
> I see that you are using Emotion 10 there so this is the correct way of using this:
> 
> https://codesandbox.io/s/emotion-issue-template-forked-wzwv1?file=/src/index.js

I was using Emotion 11 actually -- @emotion/react 11.1.5

**Comment by yokiijay** [comment]
> I see that you are using Emotion 10 there so this is the correct way of using this:
> 
> https://codesandbox.io/s/emotion-issue-template-forked-wzwv1?file=/src/index.js

My mistake, check this again please, I'm using @emotion/react/macro + @emotion/babel-plugin, still not working.

**Comment by Andarist** [comment]
It works: https://codesandbox.io/s/emotion-issue-template-forked-svzcd . You forgot to use the jsx pragma.

Additional node: CodeSandbox doesn't always make it possible to customize the runtime to the automatic one.

**Comment by yokiijay** [comment]
> It works: https://codesandbox.io/s/emotion-issue-template-forked-svzcd . You forgot to use the jsx pragma.
> 
> Additional node: CodeSandbox doesn't always make it possible to customize the runtime to the automatic one.

Thank you, it's working.
