### ISSUE TITLE
What does the label do?

### ISSUE THREAD

**Issue by MortenHofft** [emotion-js/emotion#2311]
On https://emotion.sh/docs/labels there is an example of how emotion adds a human readable postfix to classnames. 
But `css-11z9jyx` is shown instead of something along `css-11z9jyx-some-name`. I'm not sure if it is a bug or a misunderstanding on my part when reading the documentation.

**Comment by Andarist** [comment]
That can be considered a bug in Babel plugin - the optimized "opaque style objects" do not take into account that the created object can have a manual label.

It should be checked if `cssString` [here](https://github.com/emotion-js/emotion/blob/5cdbbb330256b11ee1c67d961a9733cc68e4d1c7/packages/babel-plugin/src/utils/transform-expression-with-styles.js#L75-L79) has already a label - if yes then it should always be used and it should be appended to the generated `name`, [here](https://github.com/emotion-js/emotion/blob/5cdbbb330256b11ee1c67d961a9733cc68e4d1c7/packages/babel-plugin/src/utils/transform-expression-with-styles.js#L81) and [here](https://github.com/emotion-js/emotion/blob/5cdbbb330256b11ee1c67d961a9733cc68e4d1c7/packages/babel-plugin/src/utils/transform-expression-with-styles.js#L107). My first thought was that we shouldn't append auto labels in such a case but then it would be inconsistent with places in which we can't optimize to "opaque style objects". We should ensure that the order of manual and auto labels in this scenario is the same as in other ones.

I won't have much time to work on that - especially that's it's a minor issue. Feel free to prepare a PR for this though if you want.

**Comment by iChenLei** [comment]
### If you set the label at position where isn't last index , it works as expected.

![2021-04-06 18 57 57](https://user-images.githubusercontent.com/14012511/113701081-418a9380-970a-11eb-8dc7-f1b0e5dd3440.png)

### So why we encount this problem ?

> https://github.com/emotion-js/emotion/blob/master/packages/serialize/src/index.js#L355-L367
```js
  let labelPattern = /label:\s*([^\s;\n{]+)\s*;/g

  // using a global regex with .exec is stateful so lastIndex has to be reset each time
  labelPattern.lastIndex = 0
  let identifierName = ''

  let match
  // https://esbench.com/bench/5b809c2cf2949800a0f61fb5
  while ((match = labelPattern.exec(styles)) !== null) {
    identifierName +=
      '-' +
      // $FlowFixMe we know it's not null
      match[1]
  }

  let name = hashString(styles) + identifierName 👈🏻   //  identifierName is our custom `label` name
```

### The reason is Regex not match label correctlly

```js
 // @emotion/babel-plugin
let cssString = path.node.arguments[0].value.replace(/;$/, '');
```
`@emotion/babel-plugin` will remove the tail `;`!
```js
let style = css`
  line-height: 12px;
  color: hotpink;
  label: name-at-tail;
`
// => cssString will be
cssString = 'line-height: 12px;color: hotpink;label: name-at-tail'
```
when we try to use `labelPattern` to match, it's not work as expected.

![2021-04-06 19 17 33](https://user-images.githubusercontent.com/14012511/113702942-c1196200-970c-11eb-81a3-db2f68ea9e57.png)

### To solve this problem

I am newbie to `emotion-js` source code, so can you give me some advices to solve this minor issue? @Andarist . I know you are busy and tired to maintain `emotion-js`, so I hope I can help you to resolve some issue which is not major.

### BTW

> It should be checked if cssString here has already a label - if yes then it should always be used and it should be appended to the generated name, here and here. My first thought was that we shouldn't append auto labels in such a case but then it would be inconsistent with places in which we can't optimize to "opaque style objects". We should ensure that the order of manual and auto labels in this scenario is the same as in other ones.

I think we don't need care these situation, cause it's just a simple regex problem.

In the origin custom label implemention, it's usage like this:
```js
// 1. user set custom label and not set autoLabel in .babelrc
className = [css]-[hash]-[custom-name];

// 2. user set custom label and set autoLabel in .babelrc
className = [css]-[hash]-[custom-name]-[labelFormat];

// 3. user not set custom label and set autoLabel in .babelrc
className = [css]-[hash]-[labelFormat];

// 4. set nothing
className = [css]-[hash];
```

**Comment by Andarist** [comment]
> I think we don't need care these situation, cause it's just a simple regex problem.

The described problem is a different one than yours - since in this case, the code won't even go to the regexp-related paths. It will just return here:
https://github.com/emotion-js/emotion/blob/7e303b2ad92359a7ad802d77e2658d0f0ee37c35/packages/serialize/src/index.js#L320-L313

**Comment by Andarist** [comment]
After taking a fresh look at this case and your PR - I think your fix is indeed fixing this issue and that it is actually a better fix for this (it also fixes some other minor issue when not using Babel plugin at all). Good job 👍
