### ISSUE TITLE
Transfer Component.defaultProps

### ISSUE THREAD

**Issue by MisterLuffy** [emotion-js/emotion#2316]
**The problem**

Hello guys!  I encountered a problem about the component's defaultProps.

I have a component that needs to use a certain value of props to make some judgments, so I set defaultProps for my component. However, when the component is processed by emotion, its parent component will not be able to obtain the value in defaultProps through `child.props`. 

And the value I need appears in `child.props.__EMOTION_TYPE_PLEASE_DO_NOT_USE__.defaultProps`. I think `child.props` should contain values in `defaultProps`.

**Proposed solution**

Maybe it should be something like `{ ...Component.defaultProps, ...propsUserPassedIn }` when emotion processes a component.

**Comment by Andarist** [comment]
I'm rather hesitant about including any new logic that will handle `defaultProps` in any way since `defaultProps` are supposed to be deprecated in the future: https://github.com/reactjs/rfcs/pull/107#issue-255265902
