### ISSUE TITLE
Expose utility functions on the theme object

### ISSUE THREAD

**Issue by nrakochy** [emotion-js/emotion#2322]
Thanks for the great library! Happy to contribute if there's anything I could add here.

**The problem**

Exposed shape of the theme object throughout `styled`-type of components. e.g. the `button` knows about the theme shape: 

```js
const StyledButton = styled(MyButton)`
  background: ${props => props.theme.colors.primary};
`
```

**Proposed solution**

Use [nested theme object](https://emotion.sh/docs/theming#themeprovider-reactcomponenttype) to expose utility functions. This is [similar to this issue](https://github.com/emotion-js/emotion/issues/2198) in intent, but a bit different in proposal. I would like to have a bit of flexibility in the data shape, where I can modify the object and still have the consumers unaware. 

```js
const theme = {
  backgroundColor: 'green',
  color: 'red'
}

const adjustedTheme = ancestorTheme => ({ ...ancestorTheme, getColor: (k) => ancestorTheme.colors[k] })

class Container extends React.Component {
  render() {
    return (
      <ThemeProvider theme={theme}>
        <ThemeProvider theme={adjustedTheme}>
          <Text>Boom shaka laka!</Text>
        </ThemeProvider>
      </ThemeProvider>
    )
  }
}
```

In this case, `getColor` requires a single key as the api contract. The implementation details inside that function can be updated as needed, so  long as the contract is maintained.

**Alternative solutions**

I could directly import the util function at the top-level of the page, but would like the theme abstraction to be encapsulated to a single place

**Additional context**

Perhaps this is already possible and I just don't know how to do it, but it seems the functions are filtered out.

More details on [this SO question](https://stackoverflow.com/questions/66694486/emotion-react-theme-functions)

**Comment by Andarist** [comment]
The merged theme is pretty much just passed on:
https://github.com/emotion-js/emotion/blob/7e303b2ad92359a7ad802d77e2658d0f0ee37c35/packages/react/src/theming.js#L12

So no functions values are filtered out or anything funky like that. Please prepare a runnable repro case of your problem though - I could take a look at such

**Comment by nrakochy** [comment]
Excellent 👍  I have been working out of Storybook, so based on your response, it is probably a continuation of my struggles with the [ThemeProvider in Storybook](https://github.com/storybookjs/storybook/issues/102310). Will close for now. Thanks for taking the time
