### ISSUE TITLE
"stream" import in "@emotion/server" breaks SSR in non-Node environments

### ISSUE THREAD

**Issue by Jarred-Sumner** [emotion-js/emotion#2324]
**Current behavior:**

When you import `createEmotionServer` outside of Node.js, the file throws due to missing `stream`

```bash
 > node_modules/through/index.js:1:21: error: Could not resolve "stream" (set platform to "node" when building for node)
    1 │ var Stream = require('stream')
      ╵                      ~~~~~~~~
```

**To reproduce:**

1. Run `import createEmotionServer from "@emotion/server/create-instance";` inside a non-Node environment such as a web worker or Deno or a V8 Isolate

**Expected behavior:**

It would be great if `renderStylesToString` could still be used when `stream` is unavailable.

It looks like this file is the culprit: https://github.com/emotion-js/emotion/blob/master/packages/server/src/create-instance/index.js

Perhaps there could be another file like this -- the same file, just without `createRenderStylesToStream`:
```ts
import type { EmotionCache } from '@emotion/utils'
import createExtractCritical from './extract-critical'
import createRenderStylesToString from './inline'

export default function(cache: EmotionCache) {
  if (cache.compat !== true) {
    // is this good? should we do this automatically?
    // this is only for when using the new apis (not emotion or create-emotion)
    cache.compat = true
  }
  const nonceString = cache.nonce !== undefined ? ` nonce="${cache.nonce}"` : ''
  return {
    extractCritical: createExtractCritical(cache),
    renderStylesToString: createRenderStylesToString(cache, nonceString),
  }
}
```

**Environment information:**

- `react` version: 17.0.1
- `@emotion/react` version: 11.0.0

**Comment by Andarist** [comment]
How this is handled by other packages? I imagine that this is a somewhat common problem for people wanting to use those non-node envs. I don't believe Emotion is right now usable as-is with Deno - their package system is a lot different from what we have in node so *some* tool usually convert node-specific packages to be Deno-compatible. I'm not invested in that world so I don't know the exact tools but I've seen a bunch of approaches/services for that over the months. What's the common practice?

How do you even access the existing file? Are you using npm? some CDN?

**Comment by Jarred-Sumner** [comment]
This particular setup is within a Go-based V8 Isolate (via [v8go](https://github.com/rogchap/v8go)) bundling with [esbuild](https://esbuild.github.io/) before running. V8 Isolates are the lowest level way to embed V8 -- Node.js wraps a V8 Isolate (i'm pretty sure). By default, it only has JavaScript primitives -- strings, numbers, regexes, ArrayBuffer (and typed arrays), and Math functions. I think this is the file with the list of builtins https://chromium.googlesource.com/v8/v8/+/4c7cccf9f40c063e2d6410fc35664a0efd1acb46/src/builtins/builtins.h

ESM is not supported unless a specific flag is passed into the isolate and a resolver is created. I think its reasonable to think people will use a bundler for environments like this.

To future readers of this issue: it turns out just wrapping the top-level component in `<CacheProvider value={cache}>{children}</CacheProvider>` just works, making this step unnecessary for rendering SSR'ing React. I don't understand why it works, but good job @Andarist! Would love to know why it works though -- does the client read the DOM on init to see if it needs to be hydrated? Is there a special hydration callback React exposes?

**Comment by Andarist** [comment]
> ESM is not supported unless a specific flag is passed into the isolate and a resolver is created. I think its reasonable to think people will use a bundler for environments like this.

This reflects my thinking. So for this case, you are still using npm and a bundler but you execute the final bundle in non-node env, right?

> Would love to know why it works though -- does the client read the DOM on init to see if it needs to be hydrated? Is there a special hydration callback React exposes?

Yes, we first move all styles away so React doesn't complain about hydration mismatch:
https://github.com/emotion-js/emotion/blob/7e303b2ad92359a7ad802d77e2658d0f0ee37c35/packages/cache/src/index.js#L55-L65
and for any given cache we hydrate style elements belonging to it when the cache is created:
https://github.com/emotion-js/emotion/blob/7e303b2ad92359a7ad802d77e2658d0f0ee37c35/packages/cache/src/index.js#L81-L100
