### ISSUE TITLE
Add version to Emotion "style" tags

### ISSUE THREAD

**Issue by endermctv** [emotion-js/emotion#2331]
**The problem**

I'm adding Emotion to [Wappalyzer](https://github.com/AliasIO/wappalyzer) (https://github.com/AliasIO/wappalyzer/pull/3858) and I would like to be able to view the version in the technlogies.

**Proposed solution**

Add a `data-emotion-version` attribute (or something like that) on the `style` tags of Emotion.

**Alternative solutions**

A `meta` tag is also possible:

```html
<meta name="emotion-version" content="..." />
```

**Additional context**

![](https://cdn.discordapp.com/attachments/810956850086281217/828293093069291521/Capture_decran_de_2021-04-04_17-28-49_2.png)
(This screenshot was taken from the unpackaged extension.)

As you can see, the version is not next to Emotion.

The labels are in French. Here are the translations:
- "Framework JavaScript": JavaScript Framework
- "Outil de développement": Development tool

**Comment by Andarist** [comment]
This doesn't seem like something we'd like to do.

> Add a data-emotion-version attribute (or something like that) on the style tags of Emotion.

We don't need it and this would increase the size of SSRed content.

> A meta tag is also possible:

This sounds better - but the reason against it is similar: adding this would increase the bundlesize and we don't need it.

**Comment by endermctv** [comment]
Hey, I understand this can increase the size of the bundle. So, I close this issue.
