### ISSUE TITLE
Generic parameters not persisted through styled components

### ISSUE THREAD

**Issue by tills13** [emotion-js/emotion#2342]
**Current behavior:**

TypeScript generic parameters are not accessible through the `styled` wrapper. 

**To reproduce:**

CodeSandbox example: https://codesandbox.io/s/sad-easley-bw821

1. have a generic component with generic props
2. wrap as a `styled` component
3. generic parameter not accessible on the wrapped component

**Expected behavior:**

Generic parameter is accessible on the resulting HoC. Alternatively, I'm OK with using a type assertion here -- I'm just not quite sure what I should be asserting as.

**Environment information:**

- `react` version: 16.8
- `@emotion/react` version: 10.0
- `@emotion/styled` version: 10.0

**Comment by Andarist** [comment]
Our types are quite complex - we rely on inference quite a bit and use some conditional types to create an overall better experience for users. Unfortunately, this has the effect of not working in an ideal way with things like generic type params.

In this case, you match our 4th overload:
https://github.com/emotion-js/emotion/blob/f36b946b4b1d465ff399cbe4dc518aa2e34501ac/packages/styled/types/base.d.ts#L165-L172

We can do some simple tests on the `GenericList` to learn that this limitation lies at the core of the current design:
```ts
type Test1 = React.ComponentProps<typeof GenericList>
type Test2 = PropsOf<typeof GenericList>
```

Both of those result in `Props<unknown>`. I honestly don't know what we could improve on this front - complex types are one of the reasons why we recommend using the css prop API over styles API - it just doesn't suffer from issues like this.

> Alternatively, I'm OK with using a type assertion here -- I'm just not quite sure what I should be asserting as.

There is a high chance that you don't need any styled-specific behaviors on the component that is returned. If that's the case then you can simply do this:

```ts
const GenericStyledList = styled(GenericList)`` as typeof GenericList
```

**Comment by tills13** [comment]
> complex types are one of the reasons why we recommend using the css prop API over styles API

hmm, 

> There is a high chance that you don't need any styled-specific behaviors on the component that is returned. If that's the case then you can simply do this:

unfortunately, I need to be able to use the component as a selector in `css` and other `styled` components so that won't work. 

I guess what I could do is wrap the component where it's used and narrow the generic param there e.g.

```
// can't use `typeof GenericList` here because of the issues you described in your response
const StringGenericList = styled(GenericList as React.ComponentType<Props<string>>)``
```

That seems to allow me to 

```
<StringGenericList
  items={['1', '2']}
  renderItem={(i) => {
    return <div>{i}</div>;
  }}
/>
```

and get proper typing on on `items` and `i`.

**Comment by iChenLei** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-cant-i-write-typeof-t-new-t-or-instanceof-t-in-my-generic-function
It looks like not easy to solve this problem.

**Comment by Andarist** [comment]
@tills13 you can extend your assertion with `ComponentSelector`: https://codesandbox.io/s/objective-mclaren-zv8cb?file=/src/App.tsx

**Comment by tills13** [comment]
@Andarist this works for my use case. Thanks for the replies.
