### ISSUE TITLE
css class name without component name

### ISSUE THREAD

**Issue by karesh** [emotion-js/emotion#2366]
Added css to element as below

```
/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx, css } from '@emotion/react';

    function Icon() {
      return (
          <span
              css={css`
                  color: red;
                `}>
              Icon
          </span>
      );
    }
    export default Icon;
```
Class Name generated as class="**css-1f6rj74-Icon**" for the span element.

We don't want to expose component names to public.

How can I remove the Icon- Component name from generated css classname.?

React version: 17.0.2
"@emotion/react": "^11.1.5"

**Comment by karesh** [comment]
Have tried like that also.

babel config.
```
 "plugins": [
    ["@emotion/babel-plugin",
      {
        "autoLabel": "never",
        "labelFormat": "[local]",
        "cssPropOptimization": true
      }
    ]
  ]

built code : css name has no label in both env.
```
var _ref = process.env.NODE_ENV === "production" ? {
  name: "hwfcu5",
  styles: "color:red"
} : {
  name: "hwfcu5",
  styles: "color:red",
  map: "...."
};

function Icon() {
  return (0, _react.jsx)("span", {
    css: _ref
  }, "Test CSS");
}
```
I publish this as library and used in inside CRA another project in DEV mode.
**Still class name appear**
```
import Icon from "@test123/icon";

Rendered as
<span class="css-t2vmco-Icon">Test CSS</span>
```

- css name also different in new react project after import library. ?

**Comment by iChenLei** [comment]
![2021-05-07 23 59 45](https://user-images.githubusercontent.com/14012511/117477224-50c26280-af90-11eb-9c8c-ddd6bf41b485.png)

If you are vscode user, you can create a `javascript debug terminal` and then `⌘ + click` to debug why generate the special className.

**Comment by karesh** [comment]
Thank you.
I built the new react project and run as production mode. 
Now Component render as
**<span class="css-hwfcu5">Test CSS</span>**
Which is same css name as built library.
