### ISSUE TITLE
@emotion/eslint-plugin: support @jsxImportSource

### ISSUE THREAD

**Issue by osdiab** [emotion-js/emotion#2373]
**The problem**

the ESLint `jsx-import` rule appears to always insert `/** @jsx jsx */` and an import for `jsx` on auto-fix, but with the new JSX runtimes (mentioned here: https://emotion.sh/docs/css-prop#jsx-pragma) my build says i should be using `/** @jsxImportSource @emotion/react */`. That directive present doesnt silence the error.

**Proposed solution**

Have an option that allows for the other JSX pragma to be used.

**Alternative solutions**

Dont include this lint rule and hope for the best... but that kinda sucks

**Comment by iChenLei** [comment]
Duplicate #2070 and existing PR #2353 for your issue, current lack maintainer's code review, you can add your advices on the PR comment timeline. Thanks

**Comment by osdiab** [comment]
ah my bad, thanks!
