### ISSUE TITLE
Chrome does not display `grid-row-gap` as normal in production mode

### ISSUE THREAD

**Issue by 007tom** [emotion-js/emotion#2388]
**Current behavior:**

Chrome Styles Panel not displayed `grid-row-gap` and we can not edit the panel in **production** mode.
<img width="1280" alt="Screen Shot 2021-05-24 at 19 55 20" src="https://user-images.githubusercontent.com/31362988/119344293-0ea45b00-bcca-11eb-82b3-7520ee08fe4e.png">

But in Firefox and Safari, it works well.
<img width="1264" alt="Screen Shot 2021-05-24 at 08 48 05" src="https://user-images.githubusercontent.com/31362988/119344409-372c5500-bcca-11eb-847f-6ac98a6ba522.png">
<img width="1264" alt="Screen Shot 2021-05-24 at 08 48 46" src="https://user-images.githubusercontent.com/31362988/119344426-3b587280-bcca-11eb-948b-bea102243ff0.png">

**To reproduce:**

https://github.com/zhyd1997/react-hooks-with-emotion

**Expected behavior:**

the behavior should be the same as Firefox or Safari, we can edit Chrome Styles Panel in production mode.
<img width="1264" alt="Screen Shot 2021-05-24 at 08 49 12" src="https://user-images.githubusercontent.com/31362988/119345161-19abbb00-bccb-11eb-8e9b-402e59ac6f34.png">

**Environment information:**

- `react` version: ^17.0.2
- `@emotion/react` version: ^11.4.0

**Comment by 007tom** [comment]
I noticed that `grid-row-gap` is displayed as `row-gap` in Firefox and Safari in `production` mode.

**Comment by Andarist** [comment]
I'm not super familiar with CSS grid but this is what you get in Chrome by injecting those computed rules:
```js
var s = document.createElement('style')
document.head.appendChild(s)

s.sheet.insertRule(`
div {
  display: grid;
  grid: auto-flow/0.5fr 1fr;
  grid-row-gap: var(--cx-spacing-2x);
  padding: var(--cx-spacing-4x);
}
`)

console.log(s.sheet.cssRules[0].cssText) // div { display: grid; grid-template-columns: 0.5fr 1fr; grid-template-rows: initial; grid-template-areas: initial; grid-auto-flow: row; grid-auto-columns: initial; grid-auto-rows: initial; row-gap: ; padding: var(--cx-spacing-4x); }
```

As you might notice - `row-grap` is broken. This is either because the input rules are wrong or it's a bug in Chrome (where I think the latter is more likely). 

As to those styles not being editable in production mode - this seems to be connected to that "broken" property. Styles with correct properties are editable.

**Comment by 007tom** [comment]
Nice!

Although `row-gap` is broken, it has affected the page, which means the `div` has `row-gap` with values.

Interesting!
