### ISSUE TITLE
Equivalence of statements, docs extension

### ISSUE THREAD

**Issue by tknuth** [emotion-js/emotion#2395]
**Description:**

In the global style (or in general), is

```
main h2,
main h3 {
  margin-top: 1.5em;
}
```

equivalent to

```
main {
  h2, h3 {
    margin-top: 1.5em;
  }
}
```

?

If so, I'd add an example in the docs, as there isn't any and the above code seems to work.

**Comment by iChenLei** [comment]
Yes, it's `Nested` css declaration. Less/Sass and other css-in-js library do same implemention for this feature. You can use these online playground to check it.
> less -> https://lesscss.org/less-preview
> sass -> https://www.sassmeister.com/
> emotion -> https://emotion.sh/docs/introduction#framework-agnostic

**Comment by tknuth** [comment]
Great, thank you for the quick reply. If you think the docs could use an additional example, let me know. Otherwise, just close the issue :-)
