### ISSUE TITLE
Allow to set PostCSS plugins

### ISSUE THREAD

**Issue by ai** [emotion-js/emotion#240]
Since inline mode is now default and extract doesn’t support any dynamic, how I can process CSS in other PostCSS plugins?

If we already parse CSS with PostCSS it will be good to use same AST for other plugins too.

For example, we can pass `postcss: true` option and Emotion will read default PostCSS config.

**Comment by tkh44** [comment]
All of the imported plugins would have to be synchronous, correct? Can you force plugins to be synchronous?

**Comment by ai** [comment]
For example, we can start from sync-only plugins.

BTW, why we are limited in sync plugins?

**Comment by tkh44** [comment]
Babel is synchronous

**Comment by ai** [comment]
Yeap, let's start from sync PostCSS plugins.

But it is strange to have sync-only API in 2017, because it is much slower. Do we have a issue about async API? Maybe we can force Babel to implement async API faster?

**Comment by mitchellhamilton** [comment]
AFAIK Babel has no plans to implement an async API and from the loose understanding I have, it  will never happen because it would require a completely different architecture for no real gain. The only way we could do anything async would be to use [deasync](https://github.com/abbr/deasync) or [child_process.execSync](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options).

**Comment by ai** [comment]
Ouh, it is real sad news and bad Babel maintenance 😔 performance is really important

**Comment by mitchellhamilton** [comment]
Babel is maintained really well by some really amazing people and they have their reasons for being sync. The only time performance will suffer is when people do weird things(like we do) that were never meant to be done in a babel plugin like reading from the file system.

**Comment by ai** [comment]
It is not first time when I see problem with not being able to write async plugin and it is sad that Babel team just ignores users needs.

We had same question in PostCSS and we implement async, because it is Node.js way.

**Comment by mitchellhamilton** [comment]
Plugins like emotion's aren't the primary use case for Babel. Babel is very different to PostCSS and implementing async would be incredibly complex and would not be worth it for the few people that want it.

**Comment by ai** [comment]
Can I help with this issue?

**Comment by vladnicula** [comment]
Is this ticket related maybe to an issue I'm having where extract static and webpack don't play well together and `css-loader` / `extract-text-webpack-plugin` is not finding the content?

**Comment by ai** [comment]
Nope this issue mostly for not calling PostCSS twice.

If 8.0 was moved to Stylis, we can close this issue.

**Comment by tkh44** [comment]
FWIW @ai you can write custom stylis plugins for your app so you can do custom logic at runtime if you wanted to.

We should probably expose this for the babel plugin and extract static mode.

**Comment by SilentImp** [comment]
just to make sure: emotion still not support postcss plugins, including autoprefixer?

**Comment by FezVrasta** [comment]
Emotion makes use of stylis to process CSS, you can write plugins for it, and it includes by default something similar to autoprefixer
