### ISSUE TITLE
useTheme works but theme in styled does not.

### ISSUE THREAD

**Issue by softmarshmallow** [emotion-js/emotion#2406]
```tsx
const RootContainer = styled.ul(
  ({ theme }) => ({
    color: theme.colors.theColor,
  })
);


function WierdlynotWorkingComponent(){
   const theme = useTheme();
  console.log("theme", theme);
  return <RootContainer/>
}

```

Logs: 
```json
theme {
   colors: {
       theColor: "rgba(0, 0, 0, 0)"
   }
}
````

useTheme is working but using theme in styled is not.
I'm using monorepo and this component is being imported from outside component. I've fixed this issue once by matching the @emotion version, but this one seems different.

I guess somehow styled in referencing different version of emotion/core rather than the version from emotion/react

Is this possible?

**Comment by Andarist** [comment]
> I guess somehow styled in referencing different version of emotion/core rather than the version from emotion/react

It might be one of the reasons. The other one would be that both use a different version of `@emotion/react` - or even the same version but from 2 different disk locations. Does this maybe happen in Storybook? They have a known & unsolved issue that breaks this.

**Comment by softmarshmallow** [comment]
I have a storybook dependency but this is not caused on storybook (not tested). this is happening on runtime (electron & nextjs)

**Comment by softmarshmallow** [comment]
Sorry. it was my local environment somehow misconfigured with lock files.

rm ing all node_modules & yarn.lock && yarn did the trick.

I'll reopen this issue if the solution was temporary.
