### ISSUE TITLE
Don't merge extended classes that use the styled(Component) api

### ISSUE THREAD

**Issue by raphaelbadia** [emotion-js/emotion#2419]
**The problem**

My UI engineer are telling me that it will be a problem for them to work with emotion as all classes are merged into one, even using the styled(Button) api.

For instance, take this [codesandbox](https://codesandbox.io/s/emotion-babel-plugin-class-name-duplication-forked-7b1lj). We have a regular Title, and we extend it like so :
```javascript
const BigTitle = styled(Title)`
  font-size: 60px;
`;
```

I get it all in the same class (and twice, but it's another problem) : 
![CleanShot 2021-07-05 at 15 44 14](https://user-images.githubusercontent.com/1901628/124480759-e53a1d00-dda7-11eb-9e2f-d8a6c999e9cc.png)

**Proposed solution**

What I expected was to see two classes in the dom : one class with the original style, and another one with the extended style. something like that : 
```css
.css-nd2ia6-Title {
  font-size: 30px;
}
..css-hellow212-Title-BigTitle {
  font-size: 60px;
}
```

**Alternative solutions**

I don't really know, I'm quite unused to how css-in-js works internally

**Additional context**

My concern is that it will get very hard to debug, because we don't know from which component the style comes from !

Thanks

**Comment by wuifdesign** [comment]
i'm having the same problem. my concern is, that it creates a lot of unused styles for SSR. 

if i extend a component it creates something like this
```
.css-... {
  display: block;
  widht: 50px;
  font-size: 60px;
  display: inline-block;
  widht: 20px;
  font-size: 10px;
}
``` 

This will work, but leads to twice as much code as it needs to be. doing so for 200 components it ends up in many unused kb to send to the user.

**Comment by srmagura** [comment]
The way it works now does seem suboptimal, especially for SSR. [This CodeSandbox](https://codesandbox.io/s/emotion-css-prop-duplicate-rules-rcxqx6) demonstrates that the same issue applies when using the css prop instead of `styled`.

Fixing this could require a large change to how Emotion works internally. @Andarist, what are you thoughts on this?

**Comment by Andarist** [comment]
This is how Emotion was designed - it helps us to fix the cascade problems outlined [here](https://emotion.sh/docs/composition) so the resulting styles are more **predictable**.

This is not something that we are going to fix here - every solution has some tradeoffs and this is just one of the Emotion tradeoffs. You get reliability and speed (as deduplication would come with a severe performance penalty) in exchange for some duplicated declarations.
