### ISSUE TITLE
Move BLM banner into a link / make it less intrusive/distracting

### ISSUE THREAD

**Issue by LoganDark** [emotion-js/emotion#2420]
Right now, there is a giant "Black Lives Matter" banner above the entire documentation site. I think that would be better put in a footer link, or somewhere else on the site since people visiting a site for a JS library don't expect politics pushed on them.

I'm not suggesting complete removal, I understand the importance of showing your support sometimes, but personally, I think the banner is very distracting and also very off-putting. It doesn't fit the site at all.

**Comment by icanhazpython** [comment]
Seconded. This is a major turn-off to me. I personally feel that politics should not be invading the OSS community the same way it has seemed to creep into every other aspect of our lives, regardless of one's beliefs.

**Comment by ebonow** [comment]
Agreed. I use an extension on Chrome called "Stylish" which allows me to create custom stylesheets for sites.

I have had this banner added to my custom global stylesheet called **Virtue Signaling** a long time ago.

Perhaps better to just walk around with a sticker that says "I'm not a racist" to make sure everyone know you are a loving and tolerant person/people and leave the complex and nuanced argument of racial biases in emergency and life threatening situations to the justice system. As someone who has spoken to African-American police officers, contrary to your best intentions, this "movement" has not made their lives any easier or safer.

**Comment by LoganDark** [comment]
> As someone who has spoken to African-American police officers, contrary to your best intentions, this "movement" has not made their lives any easier or safer.

That doesn't mean it shouldn't exist. I don't hate BLM or anything. I'd just prefer to not see it shoved in my face wherever I go. It's perfectly fine to show support, but not fine to annoy people with it constantly.

**Comment by ebonow** [comment]
It's very nuanced as I stated above, and to your point, it's not something that should be plastered front and center on a technical documentation.

**Comment by JoeJHoward** [comment]
Agree with this. I'd also like to add that showcasing this type of political activism on a OSS documentation site is settings a divisive precedent for the community at large.

**Comment by srmagura** [comment]
Well, we're supporting Ukraine now, so 🤷‍♀️
