### ISSUE TITLE
Why style is not applied once several selectors are used?

### ISSUE THREAD

**Issue by ekaradon** [emotion-js/emotion#2438]
**Current behavior:**

I try to customize the visual of input of type range like shown here (be wary that in order to show the issue I recommend Firefox, it seems that Chrome bits are outdated in this link):
https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/
There is a lot of common rules between every browser, so I tried to share the same set between those browsers. But once I start using comma the style is not applied anymore. Is there something I've missed?

**To reproduce:**

https://codesandbox.io/s/emotion-forked-etsz8?file=/index.js

**Expected behavior:**

Just replace the selector by just the first one (eg: `  "&::-moz-range-thumb": {`) and see on Firefox that now the css is applied.
![Screenshot_20210721_144652](https://user-images.githubusercontent.com/9439390/126490775-f67f900e-ce3a-4aeb-b326-c42c43564180.png)

VS 

![Screenshot_20210721_144732](https://user-images.githubusercontent.com/9439390/126490833-edce638e-10f7-42a1-bc85-0d86cff8e988.png)

- `react` version: 17.0.2
- `@emotion/react` version: 11.4.0
- `@emotion/styled` version: 11.3.0

**Comment by Andarist** [comment]
This matches the native behavior, see: https://jsfiddle.net/rbygpc5z/

Trying to use the `insertRule` API with the generated ruleset results in:
```
There was a problem inserting the following rule: ".css-16h0uk3::-moz-range-thumb,.css-16h0uk3::-webkit-slider-thumb,.css-16h0uk3::-ms-thumb{border:1px solid #000000;height:36px;width:16px;border-radius:3px;background:#ffffff;cursor:pointer;box-shadow:1px 1px 1px #000000,0px 0px 1px #0d0d0d;}" DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.css-16h0uk3::-moz-range-thumb,.css-16h0uk3::-webkit-slider-thumb,.css-16h0uk3::-ms-thumb{border:1px solid #000000;height:36px;width:16px;border-radius:3px;background:#ffffff;cursor:pointer;box-shadow:1px 1px 1px #000000,0px 0px 1px #0d0d0d;}'
```

**Comment by ekaradon** [comment]
Oh I see. The fact that the some part of the rule are not recognized make the whole thing to be ignored. See the relevant SO:
https://stackoverflow.com/questions/50580986/why-cant-i-combine-pseudo-element-selectors
Thanks for your answer Andarist. I was looking at the wrong place. :)
