### ISSUE TITLE
Setting up a basic React/Emotion project results in Exception: pragma and pragmaFrag cannot be set

### ISSUE THREAD

**Issue by philp** [emotion-js/emotion#2442]
**Current behavior:**

First time attempting to use Emotion with React, first created an app using Create React App, then added `@emotion/react` as a dependency. Finally, followed docs to include:

```
/** @jsx jsx */
import { jsx } from '@emotion/react'
```

Result is an exception at compile time:

```
./src/App.js
SyntaxError: <project_root>/src/App.js: pragma and pragmaFrag cannot be set when runtime is automatic.
```

Sample repo can be found here: https://github.com/feefhq/react-emotion-baseline

**To reproduce:**

1. Setup a project:

```
$ npx create-react-app react-emotion-baseline
$ cd react-emotion-baseline
$ yarn add @emotion/react
```

2. Then, add the following to the top of `src/App.js` (as per [introduction docs](https://emotion.sh/docs/introduction):

```
/** @jsx jsx */
import { css, jsx } from '@emotion/react'
```

3. Run:

```
$ yarn start
```

**Expected behavior:**

It should compile.

**Environment information:**

- `react` version: `^17.0.2`
- `@emotion/react` version: `^11.4.0`

**Comment by mverissimo** [comment]
When using CRA, you need add the JSX runtime directive to force the classic runtime.

Try this:

```jsx
/** @jsxRuntime classic */
/** @jsx jsx */
import { css, jsx } from '@emotion/react'
```

**Comment by agiledots** [comment]
Create React App 4 then `/** @jsx jsx */` pragma might not work and you should use `/** @jsxImportSource @emotion/react */ ` instead.

```
/** @jsxImportSource @emotion/react */
import { jsx, css } from "@emotion/react";
```

**Comment by Andarist** [comment]
If you are using Emotion 11 then yes - IIRC `/** @jsxImportSource @emotion/react */` is the correct way to use this. An improvement to our ESLint plugin has just been merged: https://github.com/emotion-js/emotion/pull/2353 so you could soon use it to automate this in your codebase. Note that I've been trying to improve this and related issues:
https://github.com/facebook/create-react-app/issues/9847
https://github.com/babel/babel/pull/12542

Unfortunately, those PRs/issues got stale and there is nothing happening in those directions.

**Comment by toffalori** [comment]
Is there any way to enable this line globally so you don't have to add it to each file individually? 

Something like this solution for next.js?

https://pretagteam.com/question/what-is-the-proper-way-to-enable-the-css-prop-in-emotion-11next-js-10-apps

**Comment by Andarist** [comment]
@toffalori it depends on the tools that you are using. If your tools allow customization of configs etc it should be possible to configure them to do this automatically.

**Comment by srmagura** [comment]
Closing in favor of #2662 since this issue is about configuring Emotion in Create React App. 

In the latest CRA, you just add `/** @jsxImportSource @emotion/react */`. You can see this in action in our [CodeSandbox](https://codesandbox.io/s/emotion-pk1qjqpw67?file=/index.js).

We do need to improve our documentation in this area, hence the existence of #2662.
