### ISSUE TITLE
Change context to useContext (reproduced into "@emotion/react@^11.4.0":) when used css props.

### ISSUE THREAD

**Issue by mgerasika** [emotion-js/emotion#2445]
**The problem**

Problem in image below 
![image](https://user-images.githubusercontent.com/10614750/127271028-2bab63f1-ba3a-41d6-b85d-058efdf10087.png)

**Proposed solution**

Change to useContext if possible to avoid huge tree please.

**Alternative solutions**

**Additional context**

**Comment by Andarist** [comment]
I'm afraid that this is currently not possible because elements (the ones with the css prop) can be rendered conditionally. We can't replace a wrapper component with hooks because that would mean that those hooks would be called conditionally and this would break the rules of hooks
