### ISSUE TITLE
typecheck classnames

### ISSUE THREAD

**Issue by alita-moore** [emotion-js/emotion#2461]
**The problem**

Having to write out css class name strings is brittle and not lintable

```js
const style = css`
  .class-1 {}
  .class-2 {}
`

<div css={style}>
  <div className={"class-1"}/>
  <div className={"class-2")/>
</div>
```

if `class-1` were to be changed to `class-3` or something then the class wouldn't be found but while writing this code there don't appear to be any issues / it's not caught by a linter

**Proposed solution**

Treat css classes associated with a css instance as an enum / object. This will automatically catch if a string you're using isn't available in the classname

```ts
const style = css`
  .class-1 {}
  .class-2 {}
`

<div css={style}>
  <div className={style["class-1"]}/>
  <div className={style["class-2"])/>
</div>
```

where `style["class-1"] === "class-1"` but it's equivalent to
```ts
const style: { [K in "class-1" | "class-2": string } = { "class-1": "class-1", "class-2": "class-2" }
```
so if `"class-1" -> "class-3"` then  `style["class-1"]` is not a valid type and it will be type checked

**Alternative solutions**

provide a plugin / pre-compile that checks the used classes and errors or at least warns if the class doesn't exist

**Additional context**

I program for a living and strings are awful / brittle. I adore enums and getting rid of strings altogether is a super useful thing

**Comment by alita-moore** [comment]
@srmagura I spent some time using the enum approach in my production code. It works but requires a lot of boiler plate that gets out of sync quickly. It also makes it annoying to delete things because in order to delete I have to also delete in the enum. This seems trivial but it wastes a lot of time.

In general implementing this would offer
1. Cleaner code
2. Easier to manage class name editing

Which would save a lot of time, money, and make code more readable

**Comment by alita-moore** [comment]
Also you can have a scenario where a enum had a class but the css doesn't or the strings aren't in sync and there won't be any type checking to notice that. So that'll also lead to much more time spent on debugging

**Comment by srmagura** [comment]
Closing because I believe this is out of scope for Emotion. It is a cool idea so let us know if you develop something to fit this use case.
