### ISSUE TITLE
Data Attribute Does not Match Supported Props

### ISSUE THREAD

**Issue by jvanderen1** [emotion-js/emotion#2464]
**Current behavior:**

Any [`data-*` attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) to a styled component should be supported. The motivation for this is to remove the need for `shouldForwardProp`.

**To reproduce:**

```jsx
const IconContainer = styled.div(({ dataFade }) => ({
  opacity: dataFade ? '30%' : '100%',
}))
```

**Expected behavior:**

The following error should not appear:

```
Argument types do not match parameters
```

**Environment information:**

- `react` version: ^16.13.1
- `@emotion/react` version: ^11.4.0
- `@emotion/styled` version: ^11.3.0

**Comment by jayantasamaddar** [comment]
Is this still not working?

**Comment by Andarist** [comment]
Data attributes are very much supported. You need to use a dash for them though. It matches how React handles them
