### ISSUE TITLE
injectGlobal and Global are not inserting @font-face definition

### ISSUE THREAD

**Issue by jvanderen1** [emotion-js/emotion#2466]
**Current behavior:**

When attempting to use my local font, "ProximaNova", emotion refuses to globally load the `@font-face` even though I see it in my build output.

**To reproduce:**

1) Set up global styles either by using `@emotion/react` API:

```jsx
import React from 'react'
import { css, Global } from '@emotion/react'
import ProximaNovaBlack2 from '../../../../assets/fonts/ProximaNova/ProximaNova-Black.woff2'

const proximaNovaFontStyles = css`
  @font-face {
    font-family: ProximaNova;
    src: url(${ProximaNovaBlack2}) format('woff2');
  }
`

const GlobalStyles = () => (
  <>
     <Global styles={proximaNovaFontStyles} />
  </>
)

export default GlobalStyles
```

Or through `@emotion/css` API:

```js
import { injectGlobal } from '@emotion/css'
import ProximaNovaBlack2 from '../../../../assets/fonts/ProximaNova/ProximaNova-Black.woff2'

injectGlobal`
  @font-face {
    font-family: ProximaNova;
    src: url(${ProximaNovaBlack2}) format('woff2');
  }
`
```

2) Try to use the `@font-face`:

```jsx
import React from 'react'
import styled from '@emotion/styled'

const Temp = styled.div({
  fontFamily: 'ProximaNova',
})

const LoginView () =>  {
    return (
        <Temp>TESTING</Temp>
    )
}

export default LoginView
```

**Expected behavior:**

The `@font-face` to be rendered properly.

**Environment information:**

- `react` version: ^16.13.1
- `@emotion/react` version: ^11.4.0
- `@emotion/css` version: ^11.1.3

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by MaxiSantos** [comment]
@jvanderen1 so how did you manage to fix it?

**Comment by jvanderen1** [comment]
@MaxiSantos I was not able to solve the issue. After @Andarist asked for a codesandbox, I closed this issue. Reproduction steps should be enough to demonstrate the issue, but I can't be asked to spin up a codesandbox and upload a font family.

**Comment by Andarist** [comment]
Having access to the whole code in your node_modules should be more than enough to fix the problem on your own, I can't be asked to debug **your** issues without a **runnable** reproduction case.

**Comment by jvanderen1** [comment]
@Andarist Sounds like someone's a little triggered. Hence why I closed the issue.

**Comment by Andarist** [comment]
Sounds like someone's really entitled 😉 

"I can't be asked" shouldn't ever be used by the issue reporter. Maintainers have a lot of issues to handle and usually do it in their free time - at the very least, issue reporters can save them some time by providing a repro case. A repro case ensures there is no missing context and allows maintainers to dive into the problem quicker. 

While my comment was snarky (very intentionally) - take this as advice for the future. 9 out of 10 times™ the maintainer will prioritize issues with repro cases over the ones without them. So if you care about getting help for your problem then it's in your best interest to provide a repro case (ideally, right from the start, when creating the issue).

**Comment by jvanderen1** [comment]
*Furiously typing on keyboard*

Whatever helps you man. If you want to keep your library buggy, go for it. Just trying to tell you about an issue. Do whatever you want with it 😜

**Comment by srmagura** [comment]
Works for me. https://codesandbox.io/s/ecstatic-proskuriakova-fuq725?file=/src/App.js
