### ISSUE TITLE
ESBuild support (non-Babel-builds)

### ISSUE THREAD

**Issue by 205g0** [emotion-js/emotion#2474]
**Description:**

Does emotion support ESBuilds envs such as vite.js? Looking around in the docs and issues for 10 mins and couldn't find anything. I assume not. Would be helpful to have an explicit statement right at the beginning and an outlook if this might a feature in the future and not

FWIW, Babel and stuff which come along with  Babel feels to me like legacy tech which I just try to avoid. not sure who is using that stuff for new projects.

**Comment by 205g0** [comment]
emotion _does_ support ESBuild envs, there's even some hack to make it even easier: https://dev.to/ajitsinghkamal/using-emotionjs-with-vite-2ndj

Should I keep this issue open or close? Wouldn't be too bad for emotion to promote that it works out of the box with everything and we could also integrate that hack from the above mentioned dev.to article...

**Comment by Andarist** [comment]
Emotion would work "out of the box" with ESbuild if only that project would implement support for the "modern" JSX transform. There are some open issues about this:
https://github.com/evanw/esbuild/issues/1172
https://github.com/evanw/esbuild/issues/718

**Comment by agriffis** [comment]
Looks like https://github.com/evanw/esbuild/pull/2349 will likely fix this when it's merged.

**Comment by hiddenest** [comment]
Yeah, now it is merged: https://github.com/evanw/esbuild/pull/2349
