### ISSUE TITLE
Potentially Unsafe Server-Rendering flag works on the first instance only

### ISSUE THREAD

**Issue by Saghen** [emotion-js/emotion#2478]
**Current behavior:**

When using the ignoreFlag for `nth-child` being potentially unsafe with server rendering, the first instance of the flag works while the second does not (workaround provided). 

**To reproduce:**

Create a component that includes multiple nth-child selectors and attempt to disable the warning with the appropriate ignoreFlag. The issue appears on both `@emotion/styled` and `@emotion/react`.

```ts
const Component = styled("div")`
  > *:nth-child(1)  /* emotion-disable-server-rendering-unsafe-selector-warning-please-do-not-use-this-the-warning-exists-for-a-reason */ {
    color: red;
  }

  > *:nth-child(2) /* emotion-disable-server-rendering-unsafe-selector-warning-please-do-not-use-this-the-warning-exists-for-a-reason */ {
    color: red;
  }
`
```

The workaround I found was to include the comment in the previous block. Based on some quick debugging, it seems like all the comments are getting put into the root element. I imagine this is stylis behavior. When the second block checks for the comment in the previous element, it finds the `> *:nth-child(1)` block has no comment. Putting the comment at the end of the previous element instead seems to solve the issue. The reasoning is just an educated guess 😅

```ts
const Component = styled("div")`
  > *:nth-child(1)  /* emotion-disable-server-rendering-unsafe-selector-warning-please-do-not-use-this-the-warning-exists-for-a-reason */ {
    color: red;
    /* emotion-disable-server-rendering-unsafe-selector-warning-please-do-not-use-this-the-warning-exists-for-a-reason */
  }

  > *:nth-child(2) {
    color: red;
  }
`
```

**Expected behavior:**

The error should not throw when the comment is present before the block or documentation could be provided on how to use this correctly. I couldn't find any relevant documentation about this flag in general. For reference, the positioning of the comment was based off of a comment in this issue: https://github.com/emotion-js/emotion/issues/1105#issuecomment-546299711

**Environment information:**

- `react` version: 17.0.2
- `@emotion/react` version: 11.4.1
- `@emotion/styled` version: 11.3.0

**Comment by Andarist** [comment]
>  The workaround I found was to include the comment in the previous block. Based on some quick debugging, it seems like all the comments are getting put into the root element. I imagine this is stylis behavior. When the second block checks for the comment in the previous element, it finds the > *:nth-child(1) block has no comment. Putting the comment at the end of the previous element instead seems to solve the issue. The reasoning is just an educated guess 😅

This sounds like a possible explanation of the problem - I have seen Stylis putting comment nodes in slightly off places at times.

> The error should not throw when the comment is present before the block or documentation could be provided on how to use this correctly. I couldn't find any relevant documentation about this flag in general. For reference, the positioning of the comment was based off of a comment in this issue: #1105 (comment)

I think we could improve docs around this - PRs are welcome 😉
