### ISSUE TITLE
Multiple Identical Global Tags Create Multiple Identical Stylesheets

### ISSUE THREAD

**Issue by JoeJHoward** [emotion-js/emotion#2480]
I'm not sure I understand the `Global` tag correctly.  For example if there are two components that both rely on the same global`CSS`. When using a global tag in each component, the styles are duplicated when they're appended to the document head. e.g even in `production` the code below will create two style sheets with the same `CSS`. 

**Current behavior:**

**Component 1:**
```
<div>
     <Global styles={css} />
</div>
```

**Component 2:**
```
<div>
     <Global styles={css} />
</div>
```
I would have thought by default it would automatically check if a `Global` tag with the same styles has already been mounted and so it doesn't re-create another stylesheet.

**Environment information:**

- `react` version: 17.0.2
- `@emotion/react` version: 11.4.1

**Comment by zopelee** [comment]
same issue.

**Comment by Andarist** [comment]
I don't think that this is something that we want to fix. Global styles are always treated as "unique" from our perspective.
