### ISSUE TITLE
@emotion/core upgrade issue

### ISSUE THREAD

**Issue by JustFly1984** [emotion-js/emotion#2485]
I have react project with @emotion 10, which I'm upgrading to the latest version.

I have a use-case where we have `import { css } from '@emotion/core'`, `css` function returns minified css string, and this string is used down the line.

After upgrade to `import { css } from '@emotion/react'`, I see that it returns classname string instead of css itself, and it beaks the logic. Thanx god we have jest test snapshots, which fails, and pointing to this issue.

Please point me to correct solution how to get minified css string in latest @emotion version.

PS. This is the only issue I have left after upgrading to @emotion 11

**Comment by Andarist** [comment]
Let's keep discussion contained here: https://github.com/emotion-js/emotion/discussions/2484 since I believe that you have opened both threads simultaneously
