### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:

### ISSUE THREAD

**Issue by p919533** [emotion-js/emotion#2490]
![image](https://user-images.githubusercontent.com/26241954/134887891-27733ae9-7614-4913-b1e7-44f2d03ef236.png)
![image](https://user-images.githubusercontent.com/26241954/134887942-48664083-4449-41a8-925d-fd159522a6f4.png)

{
    "compilerOptions": {
      "allowJs": true,
      "alwaysStrict": true,
      "esModuleInterop": true,
      "allowSyntheticDefaultImports": true,
      "declaration": true,
      "forceConsistentCasingInFileNames": true,
      "isolatedModules": true,
      "jsx": "react-jsx",
      "jsxImportSource": "@emotion/react",
      "module": "ES2020",
      "moduleResolution": "node",
      "noFallthroughCasesInSwitch": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true,
      "outDir": "./lib",
      "resolveJsonModule": true,
      "skipLibCheck": true,
      "strict": true,
      "target": "es2020",
      "plugins": [
        {
          "name": "typescript-styled-plugin",
          "lint": {
            "validProperties": ["label"]
          }
        }
      ]
    },
    "include": [
      "./src",
    ],
    "exclude": [
      "node_modules",
      "dist"
    ],
  }

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by plusch011** [comment]
@p919533 how did you solved this problem?
