### ISSUE TITLE
Getting type error (not assignable to type 'StylisPlugin') for rtlPlugin

### ISSUE THREAD

**Issue by omareg94** [emotion-js/emotion#2492]
## Current Behavior 😯
When I use `rtlPlugin` from `stylis-plugin-rtl`, I get **type error**:
`Type '(element: Element, index: number, children: (string | Element)[], callback: Middleware) => string | void' is not assignable to type 'StylisPlugin'.`
![image](https://user-images.githubusercontent.com/9765238/134776901-64872d91-fc1b-42fb-bc45-991133c0ff2e.png)

## Expected Behavior 🤔
Not having this type (TypeScript) error.

## To Reproduce 🕹
[Live Example (codesandbox/eager-tereshkova-lx74s)](https://codesandbox.io/s/eager-tereshkova-lx74s?file=/src/Demo.tsx)

## Context 🔦
I'm trying to use rtlPlugin in order to display mui components in rtl direction.

## Environment information 🌎
Simple React/Next.js. Also check Live Example above for more detailed.

- `react` version: 17.0.2
- `@emotion/react` version: 11.4.1
- `@emotion/styled` version: 11.3.0
- `stylis` version: 4.0.10
- `stylis-plugin-rtl` version: 2.1.0

I have previously posted this [issue at material-ui](https://github.com/mui-org/material-ui/issues/28587), but they reported that the bug is either within `@emotion/cache` or `stylis-plugin-rtl` ([comment](https://github.com/mui-org/material-ui/issues/28587#issuecomment-931147697)).
Also there's an exact [issue opened at styled-components/stylis-plugin-rtl](https://github.com/styled-components/stylis-plugin-rtl/issues/31) in case the bug is there.

**Comment by Andarist** [comment]
Yes, there seems to be a mismatch here - mainly because we are using our own definitions for a stylis plugin whereas `stylis-plugin-rtl` is using what is published from the DefinitelyTyped. When I was writing those typedefs the `@types/stylis` didn't exist.

An interesting problem is that both definitions seem to be incorrect but a further investigation has to be done to recheck them against the actual Stylis implementation.

**Comment by Andarist** [comment]
This should get fixed by https://github.com/emotion-js/emotion/pull/2493 but it also depends on changes here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56155
