### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by loganpowell** [emotion-js/emotion#2494]
Hi there. 

First, I'd just like to say that emotion is the jam. I've just been trying to create a wrapper function that combines some custom style parsing and am attempting this like so:

```js
// ./custom.tsx

export const custom= (...as: Parameters<typeof styled>) => {
    const prep = styled(...as)

    console.log({ prep })
    return function ready({ label, ...style }: CSS.Properties) {
        const parsed = parseDynamicStyles({ style, label })
        return prep({ label, ...parsed })
    }
}
```

then when I try to use it, e.g.:
```js
// ./component.tsx
const Custom = custom("p")({
    label: "tl-time",
    width: "27%",
    height: "auto",
    whiteSpace: "pre-wrap",
    wordWrap: "break-word",
    wordBreak: "break-word",
    fontWeight: 300,
    fontFamily: '"Fira Code", serif',
    color: ({ colors }) => colors.base[1],
    fontSize: ["1.6rem", "2rem", "2.5rem"],
    letterSpacing: "-0.08rem",
    paddingTop: ["0.5rem", ".9rem", "0.7rem", "1.2rem"],
    lineHeight: 1.2,
    textAlign: "right",
})
```
I get this error:

```sh
TypeError: Object(...) is not a function
Module.<anonymous>
.../component.tsx
  39 | )
> 40 | const Custom = custom ("p")({
  41 |     label: "tl-time",
  42 |     width: "27%",
  43 |     height: "auto",
```

I have no idea what I'm doing wrong, but I'm guessing it has something to do with Webpack? I'm using CRA.

Any tips/ideas/thoughts would be greatly appreciated!

🙏 

Logan

**Comment by Andarist** [comment]
It looks like some problem with webpack (or with what it receives~). It's really hard to tell without seeing the full repro case of this.

**Comment by loganpowell** [comment]
Thank you for the prompt response... what was causing this was that I had a custom hook that was involved, but not at the 'correct' level. My fault!

In the end, I transitioned to the `css` syntax, so I could just use a hook instead of trying to wrap the entire `styled` function with a HOF.

Thank you for your incredible work!
