### ISSUE TITLE
pseudo element doesn't update styles on Safari in development

### ISSUE THREAD

**Issue by quanphm** [emotion-js/emotion#2502]
Hi guys,

I had this issue with the auto size input with CSS that only happens on Safari in development env.

**To reproduce:**

Please open this codesandbox on Safari: https://codesandbox.io/s/emotion-css-input-scaling-ixpg9

When you edit value of the input which is the blue smaller box, the input should change its width automatically. It behaves correctly on Chrome and Firefox. If you try to toggle any styles of the container, the input suddenly scales correctly again.

Interestingly, I find this issue only happen with development env. If I build with production configs,  the behavior on Safari is correct again.

**Expected behavior:**

The input should auto size on Safari.

**Comment by mikunpham** [comment]
@Andarist I see that we have to do some edit to force a repaint/reflow so the element would work correctly again. The thing that bug me is that I don't see the issue if I switch to `styled-components`. Maybe I can take a look into `emotion` and see what I can do. 

I will close this issue for now and open a new one if I have something new. Thank you!
