### ISSUE TITLE
SSR - Memory Leak Problem

### ISSUE THREAD

**Issue by ahungrynoob** [emotion-js/emotion#2503]
**Current behavior:**
When I set different background-image from user avatar or music cover image to @emotion/styled, it will cause memory leak in ssr stage with createCache:
```typescript
export const DivMusicCover = styled.div<{ coverUrl?: string }>(
  {
    width: '0.54rem',
    height: '0.54rem',
    borderRadius: '50%',
    zIndex: 99,
  },
  ({ coverUrl }) =>
    coverUrl
      ? {
          backgroundImage: `url(${coverUrl})`,
          backgroundSize: 'cover',
        }
      : null,
)
```

I found the reason is that emotion use murmur2 to hash styles and get a unique name as key to set styles content to cache object here: https://github.com/emotion-js/emotion/blob/685bbec099372b6797a7d2cfb558756faeee4f19/packages/memoize/src/index.js#L4.
So these coverUrl from countless music generate countless hashed name, which make cache object get larger and larger.

**To reproduce:**

1. ...
2. ...
3. ...

**Expected behavior:**

**Environment information:**

- `react` version:
- `@emotion/react` version:

**Comment by ahungrynoob** [comment]
@Andarist This tip is quite important. It would be helpful if added in docs prominently.

**Comment by Andarist** [comment]
If you have an idea where this should be put - I'm open for suggestions (and PRs 😉 )

**Comment by LLukkke** [comment]
@ahungrynoob Did you solve this issue? I have memory leak issue like this in my nextjs app.
