### ISSUE TITLE
Nested composition need additional ".styles" selector to work properly

### ISSUE THREAD

**Issue by Nico924** [emotion-js/emotion#2505]
**Current behavior:**

The nested composition presented in the sandbox below needs to add an extra ".styles" to make it work

**To reproduce:**

Here is a sandbox presenting the issue
https://codesandbox.io/s/emotion-issue-template-forked-vpvui

As you can see, the function **warningNotWorking** produce a element without the background that is visible in **warningWorking**

**Expected behavior:**

Having the **warningNotWorking** working.

**Environment information:**

- `react` version:  17.0.2
- `@emotion/react` version: 10.0.27

**Comment by Andarist** [comment]
> Just to be sure, correct me if I am wrong, array elements can only be used with Object styles as explained here https://emotion.sh/docs/object-styles ?

Hm, not quite. Basically, both tagged templates and objects can, for the most part, handle the same inputs. Everything that we receive is just recursively flattened. So nothing stops you from writing stuff like this:
```js
css`${['padding: 10px;']}`
```
This is a tagged template literal but yet it receives an array as "argument". I was just making a somewhat general note, without going into much details and nuances.

> To summarize, when using template literals, this is how to achieve nested composition & condition ?

Looks correct. Technically, you don't **always** have to use `css` for "inner partials" (we can handle strings just OK) but it's advised to wrap your "partials" with `css` to avoid mistakes like the one you have made initially. The problem there was that you have interpolated an object (`absoluteFill`) into a string so the result of that was just a regular string, everything that got interpolated into it was just cast to a string etc. With a tagged template, there is actually some logic that is being executed for each interpolation (this is how tagged templates work) - so we can "unpack" interpolations and process them in a custom way. 

> I tried in the following sandbox to achieve the same result with object styles, is this the correct way ?

Looks OK - although you can do this also in a slightly more straightforward way:
https://codesandbox.io/s/emotion-issue-template-forked-tcrfe?file=/src/index.js
