### ISSUE TITLE
CSS is visible as text in next.js build

### ISSUE THREAD

**Issue by drosi94** [emotion-js/emotion#2507]
**Current behavior:**

CSS is visible as text until the page loads, for a brief time, in production only next.js build.

**To reproduce:**

https://github.com/drosi94/forest-restoration-ui/tree/feature/CU-1k4vbcm_Create-the-Profile-creation-modal-page

You can check it out to the staging URL: https://forest-restoration-pwa-6261grrex-forest-restoration.vercel.app/

![Screenshot 2021-10-14 at 1 53 15 AM](https://user-images.githubusercontent.com/3253526/137223804-725e7dfe-7d92-4f91-99ca-be298e915a32.png)

**Expected behavior:**

The CSS should not be displayed

**Environment information:**

- `react` version: 17.0.2
- `next.js` version: 11.1.2
- `@emotion/react` version: 11.4.1

**Comment by Andarist** [comment]
You have a rule like:
```js
css`
  > * {
    display: flex;
  }
`
```
to fix this you can change it to:
```js
css`
  > *:not(style) {
    display: flex;
  }
`
```
