### ISSUE TITLE
JSX Transform Support in Vite without using pragma

### ISSUE THREAD

**Issue by oriooctopus** [emotion-js/emotion#2523]
**The problem**

The use of babel in vite is an anti-pattern as it apparently brings "major performance hits". See https://github.com/vitejs/vite/discussions/1742 for more.

However, according to the [docs](https://emotion.sh/docs/css-prop) the only alternative to using babel is to use the pragma, which is quite inconvenient in terms of the boilerplate it adds for each usage.

**Proposed solution**

To add some sort of transformative support for vite similar to what babel does

**Comment by alexbakerdev** [comment]
Just a heads up that the first party [@vite/plugin-react](https://github.com/vitejs/vite/tree/main/packages/plugin-react) does use babel. Preconfigured to support the `jsxImportSource` pragma via `babel-plugin-transform-react-jsx`

Not sure about how this affects performance, but source maps are all good.

**Comment by srmagura** [comment]
Seems like your options are:

* Use `@vite/plugin-react`, which uses Babel
* Use `@jsx` pragma in every file
* Wait for Vite / ESBuild to natively support the `jsxImportSource` option — or something else that would achieve the same effect

While I don't think there are any code changes we can make to improve this situation, I can add a blurb about this to our documentation site.

**Comment by alextompkins** [comment]
I made a plugin for esbuild which may solve this issue for you. It works by substituting the `@jsxImportSource` pragma with the `@jsx` one which esbuild supports natively. 

https://www.npmjs.com/package/esbuild-plugin-jsximportsource

**Comment by RichiCoder1** [comment]
For anyone coming to this thread now, this is officially supported in esbuild now: https://github.com/evanw/esbuild/releases/tag/v0.14.51
