### ISSUE TITLE
Improving support for React 18 :)

### ISSUE THREAD

**Issue by SanjaiyanUnofficial** [emotion-js/emotion#2524]
## **Improving the support for new React 18**

> Hi , I am requesting this feature after viewing it on vercel's (maintainers of **Next js**) _styled jsx_ library, for more info please take a look at [their discussion about it 👍 ](https://github.com/vercel/next.js/pull/30179)

---
### We can add useInsertionEffect for better hydration & concurrent support 💯 (for more info about useInsertionEffect [click here](https://github.com/reactwg/react-18/discussions/110) )

- But this only support in React 18 so we need to implement fallback like below
  `const useInsertionEffect = React.useInsertionEffect || React.useLayoutEffect ` <br/>  (inspired by [Next Js](https://github.com/vercel/next.js/pull/30179))

---

I am extremely sorry if I told or made any mistakes 😌

**Comment by miracle2k** [comment]
Here is a repo that shows the current failure when trying to use emotion with next.js 18 / concurrent mode:

https://github.com/miracle2k/next-rsc-demo

```
TypeError: Cannot read properties of null (reading 'key')
    at insertStyles (webpack://_N_E/./node_modules/@emotion/utils/dist/emotion-utils.browser.esm.js?:19:25)
    at eval (webpack://_N_E/./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js?:194:75)
    at eval (webpack://_N_E/./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js?:56:12)
    at renderWithHooks (webpack://_N_E/./node_modules/react-dom/cjs/react-dom-server.browser.development.js?:5212:16)
    at renderForwardRef (webpack://_N_E/./node_modules/react-dom/cjs/react-dom-server.browser.development.js?:5381:18)
    at renderElement (webpack://_N_E/./node_modules/react-dom/cjs/react-dom-server.browser.development.js?:5526:11)
    at renderNodeDestructive (webpack://_N_E/./node_modules/react-dom/cjs/react-dom-server.browser.development.js?:5606:11)
    at renderNode (webpack://_N_E/./node_modules/react-dom/cjs/react-dom-server.browser.development.js?:5722:12)
    at renderHostElement (webpack://_N_E/./node_modules/react-dom/cjs/react-dom-server.browser.development.js?:5197:3)
    at renderElement (webpack://_N_E/./node_modules/react-dom/cjs/react-dom-server.browser.development.js?:5473:5)
error - unhandledRejection: TypeError: Cannot read properties of null (reading 'key')
```

**Comment by SanjaiyanUnofficial** [comment]
> Here is a repo that shows the current failure when trying to use emotion with next.js 18 / concurrent mode:
> 
> https://github.com/miracle2k/next-rsc-demo
> 
> ```
> TypeError: Cannot read properties of null (reading 'key')
>     at insertStyles (webpack://_N_E/./node_modules/@emotion/utils/dist/emotion-utils.browser.esm.js?:19:25)
>     at eval (webpack://_N_E/./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js?:194:75)
>     at eval (webpack://_N_E/./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js?:56:12)
>     at renderWithHooks (webpack://_N_E/./node_modules/react-dom/cjs/react-dom-server.browser.development.js?:5212:16)
>     at renderForwardRef (webpack://_N_E/./node_modules/react-dom/cjs/react-dom-server.browser.development.js?:5381:18)
>     at renderElement (webpack://_N_E/./node_modules/react-dom/cjs/react-dom-server.browser.development.js?:5526:11)
>     at renderNodeDestructive (webpack://_N_E/./node_modules/react-dom/cjs/react-dom-server.browser.development.js?:5606:11)
>     at renderNode (webpack://_N_E/./node_modules/react-dom/cjs/react-dom-server.browser.development.js?:5722:12)
>     at renderHostElement (webpack://_N_E/./node_modules/react-dom/cjs/react-dom-server.browser.development.js?:5197:3)
>     at renderElement (webpack://_N_E/./node_modules/react-dom/cjs/react-dom-server.browser.development.js?:5473:5)
> error - unhandledRejection: TypeError: Cannot read properties of null (reading 'key')
> ```
> 
> In addition, there is a different error if you try to use it as part of a server component.

Did you found any solution for it ? 🤔 @miracle2k

**Comment by Andarist** [comment]
@miracle2k I've tried running this repro and it doesn't seem to work. I end up with:
```
error - Error: ENOENT: no such file or directory, open '/next-rsc-demo/.next/server/middleware-build-manifest.js'
```

**Comment by SanjaiyanUnofficial** [comment]
@miracle2k  Try adding custom `_document.js` & `_app.js`  for ssr or ssg support of emotion css :)

[This is Mui v5 repo to get custom `_document.js` and `_app.js`](https://github.com/mui-org/material-ui/tree/master/examples/nextjs)
Mui v5 uses Emotion CSS (so downloading mui v5 is not compulsory)

Hope it works 👍

**Comment by miracle2k** [comment]
@SanjaiyanUnofficial I'm not sure if this would be sufficient, as next.js seems to disallow the use of `getInitialProps` on `Document` if concurrent mode is on. A related report about emotion compatibility on the next.js side is:

https://github.com/vercel/next.js/issues/31678

**Comment by Andarist** [comment]
@miracle2k thank you for bringing this to my attention. I’ve commented in the linked thread

**Comment by SanjaiyanUnofficial** [comment]
> @SanjaiyanUnofficial I'm not sure if this would be sufficient, as next.js seems to disallow the use of `getInitialProps` on `Document` if concurrent mode is on. But I will try to look into it. A related report about emotion compatibility on the next.js side is:
> 
> [vercel/next.js#31678](https://github.com/vercel/next.js/issues/31678)

Sorry :)

**Comment by SanjaiyanUnofficial** [comment]
Successfully issue solved from version 11.8.1 🔥

**Comment by chaudharykiran** [comment]
Is it working? 

Below is my packages:

@emotion/cache@11.7.1
@emotion/react@11.9.0
 @emotion/server@11.4.0
 @emotion/styled@11.8.1

All the packages are in latest version but I am still getting this error. 
TypeError: Cannot read property 'useContext' of null

Anyhelp will be great.

**Comment by Andarist** [comment]
To get help you need to provide a repro case
