### ISSUE TITLE
Upgrade Emotion website to the latest Gatsby or Next.js

### ISSUE THREAD

**Issue by srmagura** [emotion-js/emotion#2536]
**The problem**

Installing packages in the Emotion repository fails on an M1 Mac, see https://github.com/emotion-js/emotion/pull/2535.

**Proposed solution**

Upgrade the Emotion website to the latest version of Gatsby.

**Alternative solutions**

In the meantime, M1 Mac users can work around this by installing `vips` via Homebrew.

**Additional context**

I am planning to PR this eventually.

**Comment by srmagura** [comment]
@Andarist   I'll probably start on this next weekend. I am planning to use Next.js. A couple of points...

1. Could you look into merging https://github.com/emotion-js/emotion/pull/2471?
2. I want to write the new site in TypeScript, but I don't think that will work if I target the main branch since the site will need to import code written in Flow. So I'm planning on writing the new site in plain JS and then later adding types to it.
3. Should I remove the BLM banner so we can close the issues and PRs that are complaining about it? (For the record, I think it is silly that people are bothered by it.)

**Comment by Andarist** [comment]
1. Don't bother about this. I can always rebase this later. This PR got a little bit stuck cause I had some conceptual problems with it. I think I had an idea how to simplify this later on but never got back to this PR
2. Sounds OK. What code written in Flow will it import? If you refer to the sources of our packages then maybe running `preconstruct watch` in parallel (or just `preconstruct build` before Next) would do the trick and would allow you to not worry about the Flow stuff?
3. I also think this is silly but yeah - I'm in favor of removing it now, it served its purpose for now.

**Comment by srmagura** [comment]
Sounds good on all points. Yeah I just want to use `@emotion/react` like normal and I didn't realize that Next would use the compiled JS output instead of source files (since preconstruct does some kind of redirecty thing). I have it working now and it was no trouble.
