### ISSUE TITLE
dealing with renaming

### ISSUE THREAD

**Issue by dcsan** [emotion-js/emotion#2547]
So the [senseless renaming](https://emotion.sh/docs/emotion-11#package-renaming) of all the packages has broken upstream libraries that use this package, specifically chakra-ui

```
Error: `emotion-theming` has been removed and all its exports were moved to `@emotion/react` package. Please import them like this `import { useTheme, ThemeProvider, withTheme } from '@emotion/react'`.
...
Module../node_modules/@chakra-ui/core/dist/es/utils/index.js
```

since I'm not doing the import, i'm left with a point where I need to patch chakra-ui ?

I've tried importing both without success

```
    "@emotion/core": "^10.0.0",
    "@emotion/react": "^11.5.0",
    "@emotion/styled": "^10.0.0",
```

what's the workaround here?

I hope the rename wasn't for cosmetic reasons, it seems an insane breaking change. other projects that are broken
https://github.com/projectstorm/react-diagrams/issues/783

**Comment by dcsan** [comment]
a chakra component i'm not using is importing incorrectly:

```
./node_modules/@chakra-ui/core/dist/es/Accordion/index.js
Module not found: Can't resolve '@emotion/core' in '/Users/dc/dev/esclabs/stan/client/node_modules/@chakra-ui/core/dist/es/Accordion'
```

**Comment by dcsan** [comment]
so with all three at 11 still the same as the first error

```
    "@emotion/core": "^11.0.0",
    "@emotion/react": "^11.5.0",
    "@emotion/styled": "^11.3.0",
```

```
Error: The `@emotion/core` package has been renamed to `@emotion/react`. Please import it like this `import { jsx } from '@emotion/react'`.
```

but i'm not using JS so... 🤯

**Comment by dcsan** [comment]
lots of errors with gatsby too
https://stackoverflow.com/questions/64825623/dependency-is-not-renamed

seems downgrading to 10.x doesn't fix the problem either

**Comment by dcsan** [comment]
```
Error: `emotion-theming` has been removed and all its exports were moved to `@emotion/react` package. Please import them like this `import { useTheme, ThemeProvider, withTheme } from '@emotion/react'`.
./node_modules/emotion-theming/dist/emotion-theming.cjs.dev.js

Module../node_modules/@chakra-ui/core/dist/es/ThemeProvider/index.js

Module../node_modules/@chakra-ui/core/dist/es/utils/index.js

```

**Comment by dcsan** [comment]
https://github.com/chakra-ui/chakra-ui/issues/5084

**Comment by Andarist** [comment]
`emotion-theming` doesnt exist in the v11 line. Chakra UI is using Emotion 11 so you had to have some outdated deps there. I see the references Chakra issue was closed so I think it's safe to close this one too.
