### ISSUE TITLE
TypeError: Cannot read property '__reactFiber$3rntq2todqi' of null

### ISSUE THREAD

**Issue by moroine** [emotion-js/emotion#2553]
Hello,

I encounter an issue when using the latest `@emotion` package when running my unit tests.

- Not working version: https://stackblitz.com/edit/node-mqa7dt?devtoolsheight=33&file=Component.test.js
- Working version: https://stackblitz.com/edit/node-p2rm9t?devtoolsheight=33&file=Component.test.js

You can run `yarn test` in order to reproduce

**Comment by Andarist** [comment]
I don't think there is any issue with the referenced `enzyme-adapter-react-17`. We had to add a wrapper element to ensure compatibility with the upcoming React 18 and this might affect testing APIs that focus on the implementation details.

In your situation you should try to use something like this:
```js
  wrapper
    .find('ForwardRef(Component)')
    .children()
    .last()
    .children()
    .last()
    .simulate('click');
```

It ain't super pretty - but you could hide this in a helper or something.

[stackblitz](https://stackblitz.com/edit/node-xubdwl?devtoolsheight=33&file=Component.test.js)

**Comment by moroine** [comment]
@Andarist thanks for quick reply
