### ISSUE TITLE
CSS on snapshots are getting reordered on CI and different machines

### ISSUE THREAD

**Issue by TiagoSousa26** [emotion-js/emotion#2563]
**Current behavior:**

When the tests run locally the snapshots are ok but when it runs on the CI it gets differences on the snapshots. I tried locally in 3 machines, 2 equal laptops (in one of them I run in Windows and Linux) same snapshots and in a different machine, it gave different snapshots like the same behaviour of CI. The problem seems to be very similar to some problems that were already fixed in previous versions
https://github.com/emotion-js/emotion/issues/1878
https://github.com/emotion-js/emotion/pull/1880
I am not sure where is the problem or how to debug it.

Here is a couple of examples of the differences in the snapshots:
Example 1
![image](https://user-images.githubusercontent.com/18198433/143043297-acadb9a0-1d60-471f-b932-0439086f4ba3.png)
Example 2
![image](https://user-images.githubusercontent.com/18198433/143043532-f43a5096-4506-49ae-8f58-a9b7b65d0f36.png)

**To reproduce:**

I am not sure how to reproduce it on a CodeSandbox because I am using a lot of configuration and the problem is when it runs on the CI and different machines.
Some relevant configurations are: (I turned off the source maps and the auto label just to be sure)
`
{
    presets: [
        ['@babel/preset-env', { modules: isTest ? 'commonjs' : false }],
        [
            '@babel/preset-react',
            {
                runtime: 'automatic',
                development: isDev,
                importSource: '@emotion/react'
            }
        ]
    ],
    plugins: [
        isDev && 'react-hot-loader/babel',
        [
            '@emotion',
            {
                sourceMap: false,
                autoLabel: 'never',
                labelFormat: '[filename]--[local]'
            }
        ],
        '@babel/plugin-proposal-class-properties',
        '@babel/plugin-proposal-optional-chaining',
        '@babel/plugin-proposal-nullish-coalescing-operator',
        'lodash'
    ].filter(Boolean),
    env: {
        test: {
            plugins: [
                [
                    '@emotion',
                    {
                        sourceMap: false,
                        autoLabel: 'never',
                        labelFormat: '[filename]--[local]'
                    }
                ]
            ]
        }
    }
}
`

1. Run the tests in different machines

**Expected behavior:**

The snapshots should be the same in different local machines as also on the CI.

**Environment information:**

- `react` version: 17.0.2
- `@emotion/react` version: 11.6.0
- `@emotion/babel-plugin` version: 11.3.0
- `@emotion/css` version: 11.5.0
- `@emotion/jest` version: 11.6.0
- `@emotion/styled` version: 11.6.0
- `@testing-library/jest-dom` version: 4.2.4
- `@testing-library/react` version: 9.4.0

**Comment by Andarist** [comment]
I'm afraid that I cannot go on a wild goose chase - I need a repro case before i can start digging into this.

**Comment by TiagoSousa26** [comment]
Yeah I understand and it's not my intention, do you have some tips for me to try to find the problem.

**Comment by TiagoSousa26** [comment]
> I'm afraid that I cannot go on a wild goose chase - I need a repro case before i can start digging into this.

Yeah, I understand and it's not my intention. Do you have some tips for me to try to find the problem?
If I don't find the problem I will try reproduce the problem on the repro.

**Comment by Andarist** [comment]
First I would try to dump this in both scenarios:
```js
console.log(document.documentElement.innerHTML)
```
before taking the snapshot. And highlight the node that we are taking the snapshot of. Based on this **maybe** some new information could be figured out.

**Comment by TiagoSousa26** [comment]
I cloned the repo with the other problem and now I am noticing another problem. Here is the repo https://github.com/TiagoSousa26/emotion-jest-reordering-bug and it's on master. The `ParentEmotionComponent` is styling the `EmotionComponent` and it's not passing the style to the component. Doing `console.log(document.documentElement.innerHTML)` I see it putting the styles with the red background but doesn't reference that style on the HTML element making it not working.

**Comment by TiagoSousa26** [comment]
Here is the repo https://github.com/TiagoSousa26/emotion-jest-reordering-bug and it's on master. I am not getting the reordering CSS problem but I am having a new one. The `ParentEmotionComponent` is styling the `EmotionComponent` and it's not passing the style to the component. Doing `console.log(document.documentElement.innerHTML)` I see it putting the styles with the red background but doesn't reference that style on the HTML element making it not working.

**Comment by Andarist** [comment]
You forgot to forward the received `className`. Your `EmotionComponent` is a plain function and not a styled component - so it can't receive the styles "automatically". You can fix this by applying this patch:
```diff
diff --git a/src/EmotionComponent.jsx b/src/EmotionComponent.jsx
index 0d9cee4..84d28c7 100644
--- a/src/EmotionComponent.jsx
+++ b/src/EmotionComponent.jsx
@@ -11,9 +11,9 @@ const StyledTypography = styled.p`
 `
 
 // 3 different ways to use Emotion CSS-in-JS
-const EmotionComponent = ({ variant }) => {
+const EmotionComponent = ({ variant, className }) => {
   return (
-    <StyledTypography variant={variant}>Some Text {variant}</StyledTypography>
+    <StyledTypography className={className} variant={variant}>Some Text {variant}</StyledTypography>
   )
 }
 

```

**Comment by TiagoSousa26** [comment]
Ups... I was looking/debugging so under the hood stuff that I didn't look at the basic stuff. My bad and thanks.

**Comment by TiagoSousa26** [comment]
After some playing around and upgrading several dependencies I still have the problem. I upgraded the `css-loader@^5.2.7` and `style-loader@^2.0.0` because it could be a problem but no benefits from that.
The majority of the snapshots diffs seems to be related to pseudo-class like `:hover`, `:first-of-type`  `:disabled` and on media queries like `@media (min-width: 80em`.
I did a diff between what the `console.log(document.documentElement.innerHTML)` gives and it's the same for the test that I picked.
Do you have another tip for my debug?
Thanks, in advance.

**Comment by Andarist** [comment]
I would patch-package console.logs for all of those calls here:
https://github.com/emotion-js/emotion/blob/26ded6109fcd8ca9875cc2ce4564fee678a3f3c5/packages/jest/src/create-serializer.js#L199-L209

I would inspect their results, compare between runs and focus on the function that yields different results - then I would patch-package even more console.logs into its implementation. That should help you to trace when the execution starts to diverge.

**Comment by TiagoSousa26** [comment]
Unfortunately, I am not seeing any difference besides the diff that snapshots detect. The first collum is just running that specific set of tests locally, the middle one is running all tests locally and the third is running on CI.
![image](https://user-images.githubusercontent.com/18198433/145443614-6b998e7f-3c30-49b6-80a6-d72ecbd40f74.png)

**Comment by Andarist** [comment]
Please reach out to me on Twitter (my DMs are open) of through our Slack server - we could then discuss our debugging options further.

**Comment by Andarist** [comment]
Closing as it turned out to be the same problem as described [here](https://github.com/emotion-js/emotion/issues/2163#issuecomment-742994919). Node 10 has been used on CI and its `[].sort` is somewhat unreliable when it comes to the final order of the sorted elements
