### ISSUE TITLE
emotion + stylelint 14.0

### ISSUE THREAD

**Issue by alexreardon** [emotion-js/emotion#2579]
How do you go about setting up `emotion` with `stylelint@14`?

[Stylelint 14.0 migration guide](https://stylelint.io/migration-guide/to-14/)

Before version 14:

```js
module.exports = {
  extends: [
    'stylelint-config-standard',
  ],
  rules: {
    // ...
  },
};
```

After version 14:

These types of errors everywhere:

```
When linting something other than CSS, you should install an appropriate syntax, e.g. "@stylelint/postcss-css-in-js", and use the "customSyntax" option

 1:10  ✖  Unknown word  CssSyntaxError
```
I tried adding `@stylelint/postcss-css-in-js` (and it's required dependencies) but no success

```js
module.exports = {
  extends: [
    '@stylelint/postcss-css-in-js',
  ],
  rules: {
    // ...
  },
};
```

**Comment by Andarist** [comment]
Have you tried configuring `customSyntax: "@stylelint/postcss-css-in-js"` (or `customSyntax: require9"@stylelint/postcss-css-in-js")`? Could you setup a repro case?

**Comment by alexreardon** [comment]
I'll have a go tomorrow 👍

**Comment by alexreardon** [comment]
> Error: Cannot resolve custom syntax module "@stylelint/postcss-css-in-js". Check that module "@stylelint/postcss-css-in-js" is available and spelled correctly.

🤔
