### ISSUE TITLE
Mocking react with Jest throwing error

### ISSUE THREAD

**Issue by steviebaa** [emotion-js/emotion#2591]
**Current behavior:**

In an attempt to upgrade the packages for a project, this issue has happened. When using `jest.mock` to mock the react library, and I mount a component that contains an emotion styled component, I get
`TypeError: Cannot read property 'registered' of undefined. `

This is a [reproducible example](https://codesandbox.io/s/hidden-smoke-7hjx3?file=/__tests__/TestRow.spec.tsx) I’ve put on code sandbox. Notice if you remove the jest.mock block, the problem goes away. Even if you remove the `useContext: () => {}` it goes away.

An example of a similar issue being thrown in the main project is the following:
```
  Controller Notifications › Should display an Error notification

    TypeError: Cannot read properties of undefined (reading '142pt3j')

      31 |       type: 'error',
      32 |     });
    > 33 |     const wrapper = mount(<Notifications />);
         |                          ^
      34 |     wrapper.find('button').first().simulate('click');
      35 |   });
      36 |
```

**To reproduce:**

1. Mock react and override some function. 
2. Make sure the component you put in the test uses an emotion styled component. 
3. Run `npm run test`. 

See codesandbox above.

**Expected behavior:**

Not to throw an error

**Environment information:**

We've tested this on windows, mac and linux. Same issue.

    "react": "^17.0.2",
    "typescript": "^4.5.3"
    "@emotion/react": "^11.7.1",
    "@emotion/styled": "^11.6.0",
    "@emotion/core": "^11.0.0",
    "@emotion/jest": "^11.7.1",
    "enzyme": "^3.11.0",
    "ts-jest": "^26.4.4",
    "ts-auto-mock": "^3.5.0",
    "jest": "^26.6.3",
    "jest-canvas-mock": "^2.3.1",
    "jest-mock-external-components": "^3.0.1",
    "jest-svg-transformer": "^1.0.0",
    "jest-ts-auto-mock": "^2.0.0",

**Comment by Andarist** [comment]
I have a problem running this codesandbox. However, based on your description, it looks like you are trying to mock the `useContext` and we depend on this. An Emotion component won't work without the correct context - so unless you plan to provide a stub for what we need (which I don't recommend) then I would think about different testing strategies for this.

Why do you need to mock the `useContext` anyway?
