### ISSUE TITLE
Odd specificity when wrapped in styled components

### ISSUE THREAD

**Issue by rkjaer** [emotion-js/emotion#2592]
**Current behavior:**

When components are wrapped in a styled component (created by `@emotion/styled`) the style specificity is wrong. Thus overrides through styled components (wrong order) and the css prop (no change in applied classes) does not work.

**To reproduce:**

See isolated examples here: https://codesandbox.io/s/affectionate-poitras-kix11 (and [here](https://codesandbox.io/s/goofy-resonance-1nv8e) is an isolated one for the css prop) 
I tried giving a few examples. Try toggling the out-commented component and refresh the preview pane and note the difference in the specificity of the attached classes when it's not wrapped – or an instance of the component is rendered first, outside of the wrapping styled component.

**Expected behavior:**

I would expect no difference depending on whether or not it's wrapped in a styled component.
Also I would expect the css prop to be able to override the styled component – which for some reason works in the Storybook for the sample UI library I made for this demo purpose.

**Environment information:**

- `react` version: 17.0.2
- `@emotion/react` version: 11.7.1

**Comment by Andarist** [comment]
The most likely reason for this is that you are bundling some Emotion libs and thus your lib and the consuming package might not share the very same instance of the Emotion cache. The solution for that would be to fix the rollup config for your lib so it leaves those packages correctly as externals.

Btw. to make the `css` prop work in this CodeSandbox you might need to use `/** @jsxImportSource @emotion/react */` at the top of your files
