### ISSUE TITLE
TypeScript doc page needs updating

### ISSUE THREAD

**Issue by srmagura** [emotion-js/emotion#2596]
**Description:**

> To make the css prop work with pure TypeScript (without babel plugin) you need to add /** @jsx jsx */ at the top of every file that is using the css prop:

This is incorrect and contradicted later in the page. I am going to do a review of this docs page and fix this issue and any others I spot.

**Documentation links:**

https://emotion.sh/docs/typescript

**Comment by Andarist** [comment]
Yes - you are right. This is probably a leftover from pre-automatic runtime era. Thank you for wanting to improve the docs ❤️
