### ISSUE TITLE
Investigating potential Memory Leak

### ISSUE THREAD

**Issue by theluk** [emotion-js/emotion#2612]
Hello dear maintainers,

thanks for all your great work.

**Current behavior:**

After we upgraded last thursday from 11.1 to 11.7, we started experience some major memory leaks on server side. We use emotion also with SSR. We use the basics, just a ThemeProvider with some constants in the passed theme value. 

```
-    "@emotion/react": "^11.1.5",
-    "@emotion/styled": "^11.1.5",
+    "@emotion/react": "^11.7.1",
+    "@emotion/styled": "^11.6.0",
```

**To reproduce:**

It is currently very hard to reproduce as the memory leak seems to span over 2-4 days before it is noticable for us. 
I cannot imagine how to build some reproducable case, maybe rendering with Reacts rendertostring functioality couple of thousand times some basic components. 

**Expected behavior:**

no memory lear

**Environment information:**

- `react` version: 16.8.6
- `@emotion/react` version: 11.7.1
- `@emotion/styled` version: 11.6.0
- `@emotion/babel-plugin` version: 11.1.2

**Comment by theluk** [comment]
![image](https://user-images.githubusercontent.com/580946/147930611-d97b22c5-b000-4761-a8ac-afd534395295.png)

**Comment by Andarist** [comment]
Can you create a heap snapshot when this happens? 

This is the diff that should be investigated: https://github.com/emotion-js/emotion/compare/emotion-js:2fe9e0e...emotion-js:242f7d8 (mostly posting for my own convenience)

**Comment by theluk** [comment]
Hello, thanks for looking into it. We will deploy tomorrow two different versions and enable heap snapshot recordings. 

our SSR setup uses razzle, and for emotion we just really don't do anything special. we just have the babel plugin and a theme provider. We use almost 100% only `css` from emotion react and then `styled` from emotion styled. 

we do have i18n ssr and loadable components on ssr configured, if that matters in any way..? 
We also have some private packages that have some system design components that are bundled (with emotion peer dep) and then imported in the main project.

**Comment by theluk** [comment]
I am not sure if this is also relevant, we noticed that our snapshots were updated in the way, that there were some "Noop" components injected. I was looking if that is doing something but it looked just fine so we kept it updated and assumed it is what you intended to do.

**Comment by Andarist** [comment]
Well, it doesn't sound like you are using anything special in your SSR setup - so it probably shouldn't matter. Just to be sure - have you confirmed that the problem goes away after you downgrade those packages?

When downgrading libraries - please remember that the problem might be in some transitive dependency (like `@emotion/cache`), so I would double-check after downgrading the exact versions of all `@emotion/*` packages that you are using. 

Are you able to stress test your app and observe that memory leak when doing so? That could speed up the investigation greatly.

> I am not sure if this is also relevant, we noticed that our snapshots were updated in the way, that there were some "Noop" components injected. I was looking if that is doing something but it looked just fine so we kept it updated and assumed it is what you intended to do.

Those were added in preparation for React 18 but I don't see how they could create a memory leak as they are "just" components - and they just render `null`.

**Comment by theluk** [comment]
Hello, 

Unfortunately I will close this ticket for now because it seems no one else have this issue and i will mit get any resources to investigate. 😞 
I will get some resources to upgrade node which will give me some room for also add the heap dump functionality. But this will not happen before February. 

Thanks anyways for your effort.
