### ISSUE TITLE
@emotion/server - some dependencies seriously out of date

### ISSUE THREAD

**Issue by cssguy39** [emotion-js/emotion#2617]
First, many thanks for providing `@emotion/server` – great to have SSR working out of the box! 🍺 

Having trouble using the package due to outdated/dead (?) [html-tokenize](https://www.npmjs.com/package/html-tokenize) / [multipipe](https://www.npmjs.com/package/multipipe) dependencies. Getting duplicate package errors from webpack:

```
1.0.34
    ~/html-tokenize/~/readable-stream
      * Dependency graph
        @internations/ds@0.1.0 -> @emotion/server@^11.4.0 -> html-tokenize@^2.0.0 -> readable-stream@~1.0.27-1

3.6.0
    ~/duplexer2/~/readable-stream
      * Dependency graph
        @internations/ds@0.1.0 -> @emotion/server@^11.4.0 -> multipipe@^1.0.2 -> duplexer2@^0.1.2 -> readable-stream@^2.0.2
``` 

Any plans to switch the packages to the ones that are more actively maintained?

**Comment by Andarist** [comment]
Well-argumented PRs are always welcome 😉

**Comment by srmagura** [comment]
Looked into this and I am having trouble finding packages that are more up to date. For `multipipe`, we could try switching to the very similar library `pumpify`, but it was also last published 2 years ago. I can't find anything analogous to `html-tokenize`. 
 @cssguy39, if you know of packages we could use instead, that would be helpful.

Also, I believe it is pretty normal to have multiple versions of a single package in your dependency tree. Are the multiple versions of `readable-stream` actually causing runtime issues? 

And what is the Webpack plugin that is producing these warnings? [duplicate-package-checker-webpack-plugin](https://www.npmjs.com/package/duplicate-package-checker-webpack-plugin)?

**Comment by TheSonOfThomp** [comment]
I'm getting similar errors for `html-tokenize` using the latest version of `create-react-app`, which now uses webpack 5:

```
ERROR in ./node_modules/html-tokenize/node_modules/readable-stream/lib/_stream_writable.js 39:13-30
Module not found: Error: Can't resolve 'stream' in '.../node_modules/html-tokenize/node_modules/readable-stream/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
```

[This SO answer](https://stackoverflow.com/a/71205013/2200383) seems to resolve it for now, but it would be great to resolve this first-party in emotion

**Comment by srmagura** [comment]
@TheSonOfThomp  Do you have `@emotion/server` installed in a Create React App project? If the answer is "no", can you post your `package.json`?

**Comment by TheSonOfThomp** [comment]
Not directly, no, but I work on a design system that uses `@emotion/server` as a dependency of most components: https://github.com/mongodb/leafygreen-ui/tree/main/packages/emotion

**Comment by srmagura** [comment]
@TheSonOfThomp You are importing `@emotion/server` in client-side code. This is likely to cause issues because Node.js APIs are not available in the browser.

This is a separate issue from the original post. If you would like to continue the discussion, please create a GitHub discussion or post in our Slack channel. Thanks.

**Comment by Andarist** [comment]
CRA is a boilerplate that is focused on client-only applications so given the limited description of the problem I'm unsure how you are trying to use `@emotion/server` there

**Comment by srmagura** [comment]
Getting back to the issue posted by the OP:

* I don't think the duplicate / out-of-date packages are causing any issues.
* There don't seem to be any more up-to-date alternatives.

So I'm closing this issue for now. If anyone has recommendations for a way forward (e.g. up-to-date packages we could use), let us know.
