### ISSUE TITLE
Browser parsing is taking 3-5 seconds time in development mode 

### ISSUE THREAD

**Issue by Dastnbek** [emotion-js/emotion#2620]
Hi!
I'm using emotion js in my in-app application. When I inspect element to see it's related styles, console is staying in loading statefor 3-5 seconds and it is annoying. I have researched related problems but could not find similar one. 

Configured emotion based on : https://emotion.sh/docs/install 
"@emotion/react": **11.7.1**
"@emotion/styled": **11.6.0**

**Comment by Andarist** [comment]
Could you record a video of the problem?

**Comment by Dastnbek** [comment]
[video.zip](https://github.com/emotion-js/emotion/files/7930927/video.zip)

**Comment by Dastnbek** [comment]
In addition we have postcss.config.js and external css variables.

**Comment by Dastnbek** [comment]
Ok. We can close it because this problem is not related to emotion

**Comment by Dastnbek** [comment]
Test comment

**Comment by Dastnbek** [comment]
Test comment

**Comment by Dastnbek** [comment]
Test comment

**Comment by Dastnbek** [comment]
Test comment 2

**Comment by Dastnbek** [comment]
Test comment 2

**Comment by Dastnbek** [comment]
Test comment 2

**Comment by Dastnbek** [comment]
Test comment 2

**Comment by Dastnbek** [comment]
Test comment 2

**Comment by Dastnbek** [comment]
Dummy comment
