### ISSUE TITLE
auto-labelling styled() with css() class: classname differs between browser and server

### ISSUE THREAD

**Issue by gmarinov** [emotion-js/emotion#2623]
**Current behavior:**

I'm experiencing a difference between the generated classnames server-side (cjs) and client-side (esm.js) using Emotion v11, `@emotion/react`, `@emotion/styled`, `@emotion/babel-plugin` with `sourceMap` set to `always` (or dev-only) and `webpack`. 

broadly speaking this is what triggers it:

```jsx
// file.js

import React from 'react';
import styled from "@emotion/styled";
/** @jsx jsx */
import { jsx, css } from "@emotion/react";
 
const someColor = 'red';

const typ = css`
 font-size: 20px;
 color: ${someColor};
 line-height: 1;
`

const Text =  styled.p`
 margin: 5px;
`

export default () => (<Text css={[typ]}>hello</Text>)

```

... which renders a `<Text>` with a classname of `...-Text-typ-typ ...` on the client and `...-Text-typ ...` on the server, and then it complains about a className mismatch.

when i examine the arguments to the style serializer, i can see that the `css()` argument  has been split in four parts, for interpolation:
- ` font-size: 20px; color: `
- `red`
- `;line-height: 1;label:typ;/*...`
- `;label:typ;/*# sourceMappingURL=data:`

If I interpolate more times however, the `-typ-` part is not included more times, just the `;`-s in the style string generated increase in number. if I disable auto labelling, the problem goes away. if I remove the interpolation part, it comes up with the correct class name. It fails in both Chrome and Safari. Works on the server (Node16). The source maps setting doesn't change anything.

I tried recreating this in the v10 sandbox and was unable to. 
I have checked that `serializeStyles` is only called once.

I'm sorry i couldn't provide a more reproducible example. :|

**Expected behavior:**

In the generated className with a label, to see `typ` only once, not twice.

**Environment information:**

- `react`: 16.14.0
- `@emotion/react`: 11.7.1
- `@emotion/styled`: 11.6.0
- `@emotion/babel-plugin`: 11.7.2
 

Any pointers welcome, including where i can place breakpoints or logging in the `dist/` modules to check things and navigate further?

**Comment by srmagura** [comment]
Thanks for the report, I will try to create a self-contained repro of this.

**Comment by gmarinov** [comment]
thanks @srmagura  - i've fixed the `Text` declaration in the example. 🤞

**Comment by gmarinov** [comment]
one thing i've discovered is that if I do e.g.

```
<Text css={[typ, typ]}>hello</Text>
```

then `typ` ends up in my classes twice for every time i've included it, i.e. `-Text-typ-typ-typ-typ-` for the above.

shrug

**Comment by gmarinov** [comment]
couple more things i found:

in https://github.com/emotion-js/emotion/blob/f3c51e8aca287170e43110bee2e4527eacfcada4/packages/babel-plugin/src/utils/strings.js#L14-L17

i had it catch and cancel:

```
// L14
if (typeof expression === 'string') {
   if (last.value.includes(expression)) {
     console.error(`path.node last argument already includes ${expression}`);
     console.error(last);
     return;
   }
  path.node.arguments[lastIndex].value += expression 
```

and that made the problem go away, but only if i also had the babel plugin's option `sourceMap: false`.

I think the plugin gets a little carried away here: 

https://github.com/emotion-js/emotion/blob/f3c51e8aca287170e43110bee2e4527eacfcada4/packages/babel-plugin/src/utils/transform-expression-with-styles.js#L65-L118

advice welcome

**Comment by srmagura** [comment]
Thanks for the additional info. I've been trying to reproduce this in the Emotion Next.js playground on [this branch](https://github.com/srmagura/emotion/tree/issue-2623).

I experimented with your code but could not reproduce the class name mismatch between the browser and server. 

With the following code and using the Babel plugin with the default options...

```tsx
import { css } from '@emotion/react'

const typ = css`
  font-size: 20px;
  label: mylabel;
`

export default function Home() {
  return <span css={[typ, typ]}>hello</span>
}
```

The `<span>` has the class name `css-p7t719-mylabel-typ-mylabel-typ-Home`. @Andarist Is this the expected behavior?

@gmarinov 
- Would it be possible for you to submit a minimal reproduction?
- How are you doing SSR? E.g. Next.js, another framework, or a custom set up?
- What browser are you testing in?
- Can you update to the latest versions of all Babel packages and attach your Babel config?

**Comment by gmarinov** [comment]
hi. thanks for the effort, @srmagura  . 

I think `mylabel-typ-mylabel-typ` is unexpected there, and that you're seeing it doubled but not mismatched points me in the direction of sourcemaps.

SSR is a custom set up - Node 16 + webpack + `extractCritical`, render into an HTML view (Handlebars). That is then sent to the client to hydrate.

I tested in Safari and Chrome - both exhibited the problem.

The versions I use are the latest around Webpack 4 (including latest Webpack):

`@babel/core`: 7.16.12
`@babel/cli`: 7.16.8

Strangely, not every class is duplicated like that - I definitely end up with at least one that is duplicated, but as I change my React tree, which one exactly ends up being different.

I'll keep bashing it a little longer, before I try to put together a minimal repro. (🤞)

below is my .babelrc

```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [
            ">0.5%"
          ]
        },
        "debug": false,
        "modules": false,
        "corejs": 3.6,
        "useBuiltIns": "usage"
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": [
    ["@emotion/babel-plugin", {
      "autoLabel": "always",
      "labelFormat": "[local]",
      "sourceMap": false
    }],
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-syntax-dynamic-import"
  ],
  "env": {
    "test": {
      "presets": [
        [
          "@babel/preset-env",
          {
            "modules": "commonjs"
          }
        ]
      ]
    }
  }
}
```

**Comment by srmagura** [comment]
As a short term solution, you could simply remove `@emotion/babel-plugin` from your config — unless you are using component selectors which require the Babel plugin.

Does the class name mismatch still occur if you use the default options for `@emotion/babel-plugin`?

**Comment by gmarinov** [comment]
@srmagura if i remove `@emotion/babel-plugin` i don't experience the problem, however in my Jest snapshots things change to their rendered html elements. 🤷‍♂️

**Comment by gmarinov** [comment]
eventually I solved my issue by removing Emotion and moving to css-loader modules
