### ISSUE TITLE
Request: Move facepaint into emotion monorepo

### ISSUE THREAD

**Issue by Sonic12040** [emotion-js/emotion#2630]
**The problem**

Facepaint is documented (and I assume designed) for use with Emotion, but it is still currently in its own repository. Creates (admittedly small) cognitive load when looking for facepaint within emotion codebase.

**Proposed solution**

Add facepaint to packages in emotionjs/emotion

**Alternative solutions**

Build facepaint into an emotion package.
Do nothing.

**Additional context**

Current facepaint location: https://github.com/emotion-js/facepaint

If preferred, I can duplicate this issue in emotionjs/facepaint instead.

**Comment by srmagura** [comment]
IMO it is fine that facepaint is in its own repository as it is not part of Emotion, but rather a completely optional helper library. I don't think any action is required here since the relevant [documentation page](https://emotion.sh/docs/media-queries) already links to the facepaint repo.
