### ISSUE TITLE
Horizontal scrolling reduces readability of website code snippets

### ISSUE THREAD

**Issue by rahil-p** [emotion-js/emotion#2640]
**Description:**

The website docs' code examples are usually not wide enough to read without horizontal scrolling.  

Although increasing `max-width` could work, I think placing the rendered components under the code snippets (instead of beside them) would significantly improve readability.

[Example](https://emotion.sh/docs/styled#changing-based-on-props)

**Comment by srmagura** [comment]
Thanks for the feedback @rahil-p. I recently redid the website and I made it so the preview is under the code editor on small screens. PR: https://github.com/emotion-js/emotion/pull/2571
