### ISSUE TITLE
Does emotion provide multiple classname feature?

### ISSUE THREAD

**Issue by TpTTT-T** [emotion-js/emotion#2641]
**The problem**

`<div class="css-sjvi8w css-1se2ve css-dj23hs"></div>`

**Additional context**

I am trying some way to do that, but I can't.

Document only show one class example.

Maybe a element have multiple class or add class when some event happened

**Comment by srmagura** [comment]
Hello, could you elaborate on what you are trying to do? Are you using vanilla Emotion, the css prop, or `styled`?

With the css prop, you can combine multiple "chunks" of CSS using an array:

```tsx
render(
    <div css={[{ color: 'red' }, { fontSize: '1.25rem' }]} />
)
```

**Comment by TpTTT-T** [comment]
> Hello, could you elaborate on what you are trying to do? Are you using vanilla Emotion, the css prop, or `styled`?
> 
> With the css prop, you can combine multiple "chunks" of CSS using an array:
> 
> ```tsx
> render(
>     <div css={[{ color: 'red' }, { fontSize: '1.25rem' }]} />
> )
> ```

Ex1:
css 1
```
{ color: 'red' }  // css-sjvi8w
```
css 2
```
{ fontSize: '1.25rem' }  // css-1se2ve
```
The css generate two random classname
```
<div class="css-sjvi8w css-1se2ve"></div>
```

---
Ex2:
Event cause some class add to element, make some transition or animation.
```
<div class="css-sjvi8w"></div>   

<div class="css-sjvi8w css-1se2ve "></div>  // event add new css

```
---
It may like this, two props, and one of css have logic decide if css should be added.
But it can not contain two same props.
```
<div css={{}} css={added ? {}:{}}></div>
```

**Comment by srmagura** [comment]
You can do conditional CSS like this:

```tsx
const css1 = css({ color: 'red' })
const css2 = css({ backgroundColor: 'blue' })

render(
    <div css={[css1, added && css2]} />
)
```

**Comment by TpTTT-T** [comment]
> You can do conditional CSS like this:
> 
> ```tsx
> const css1 = css({ color: 'red' })
> const css2 = css({ backgroundColor: 'blue' })
> 
> render(
>     <div css={[css1, added && css2]} />
> )
> ```

I have tried this, but it will merge into one class, like this
```
<div class="css-sjvi8w"></div>   // css-sjvi8w style will be { color: 'red'; backgroundColor: 'blue'}
```
This is production https://codesandbox.io/s/eloquent-roentgen-du172b?file=/src/App.js

It only generate one classname, it  just replaced.


But
Two classname will be better, like this
```
<div class="css-sjvi8w css-1se2ve"></div>
//  style css-sjvi8w is responsible for { color: 'red' }, style css-1se2ve  is responsible { backgroundColor: 'blue' }
```

If it could generate two classname, not merge into one, not replaced it, it will be very powerful.

**Comment by Andarist** [comment]
This is out of the scope of Emotion. This library is designed to merge classes into one to fix the cascade problem described here: https://emotion.sh/docs/composition
