### ISSUE TITLE
Some sheet methods (_insertTag) are undocumented

### ISSUE THREAD

**Issue by 3x071c** [emotion-js/emotion#2676]
**Description:** I've been trying to understand and possibly simplify how to reapply styles when the `<head>` gets programmatically modified/switched out (For example, when using [Error Boundaries](https://remix.run/docs/en/v1/guides/errors) at the root level in [Remix](https://remix.run)). Based off of this [official example](https://github.com/remix-run/remix/blob/main/examples/emotion/app/root.tsx), this is the suggested approach in React Remix:
```tsx
/* Component that renders the <head> and style tags, passed from the server (initial render) or client (hydration) */
const Document = withEmotionCache(
	({ children, title }: DocumentProps, emotionCache) => {
		const serverContext = useContext(ServerContext);
		const clientContext = useContext(ClientContext);

		// Only executed on client
		useEffect(() => {
			// re-link sheet container
			emotionCache.sheet.container = document.head;

			// re-inject tags
			const { tags } = emotionCache.sheet;
			emotionCache.sheet.flush();
			tags.forEach((tag) => {
				// eslint-disable-next-line no-underscore-dangle, @typescript-eslint/no-unsafe-call -- External, Private API
				(
					emotionCache.sheet as unknown as {
						_insertTag: (
							tag: StyleSheet["tags"][number],
						) => unknown;
					}
				)._insertTag(tag);
			});

			// reset cache to re-apply global styles
			clientContext.reset();
		}, [clientContext, emotionCache.sheet]);

		return (
			<html lang="en">
				<head>
					<meta charSet="utf-8" />
					<meta
						name="viewport"
						content="width=device-width,initial-scale=1"
					/>
					{title ? <title>{title}</title> : null}
					<Meta />
					<Links />
					{serverContext?.styles.map(({ key, ids, css }) => (
						<style
							key={key}
							data-emotion={`${key} ${ids.join(" ")}`}
							// eslint-disable-next-line react/no-danger
							dangerouslySetInnerHTML={{ __html: css }}
						/>
					))}
				</head>
				<body>
					{children}
					<ScrollRestoration />
					<Scripts />
					<LiveReload />
				</body>
			</html>
		);
	},
);
```

I wasn't able to find documentation on `sheet._insertTag` and what other API to use since it's private. Manual typing isn't pretty. Should this be approached differently?

**Comment by Andarist** [comment]
Could you describe your problem in more detail though? Could you share a runnable repro case of the problem?

As to `_insertTag` - it's a private method and we intend to keep it as such, that's why there are no docs for it.

**Comment by 3x071c** [comment]
@Andarist Hi, sorry for the late reply. The problem is that it looks like emotion doesn't provide a way to re-apply all emotion styles (by reinserting them into the `Head`) for cases when the style tags get removed on the client. The code snippet above (from the linked Remix example) uses undocumented APIs as a workaround to accomplish just that - when Remix replaces the `Head`, `useEffect` triggers to restore all emotion style tags. I can share a repro later today, but it essentially boils down to the linked example.

**Comment by Andarist** [comment]
1. why does Remix replaces the whole Head? Can't they only replace what they are actually managing?
2. Can't you create a custom cache and just use a different `container` than `<head/>`?

**Comment by 3x071c** [comment]
@Andarist Turns out Remix works just fine when scoping it to a single body>child container, just like Next.js does it out of the box. I have no idea why they chose to have React control the entire `document` in all of their examples/templates as a default. Emotion works as expected now too. Thanks a lot!

**Comment by 3x071c** [comment]
> @3x071c any chance you might have a hint as to how exactly you achieved this? It does seem like Remix intentionally does do stuff like managing the meta tags and links that go into the head, hence why they would be editing that stuff. How did you manage that? Thanks!

Sorry for the necrobump, I used the tried and tested [react-helmet](https://github.com/nfl/react-helmet) on the server-side to replace Remix meddling with the entire document. API is nicer too in my opinion.
