### ISSUE TITLE
Why don't you guys pay attention to issues? 

### ISSUE THREAD

**Issue by imtheaman** [emotion-js/emotion#2693]
there're many issues piled up  in the repo and i'm getting errors installing it. error says `./node_modules/@emotion/react/_isolated-hnrs/dist/emotion-react-_isolated-hnrs.browser.esm.js:1:0Module not found: Can't resolve 'hoist-non-react-statics'` 
i added this library but nothing happened. error was still the same.

please resolve all the issues. 13 days ago you've released newer version and 25 days older issues are still not resolved. currently i'm uninstalling this library and material-ui from my project.

**Comment by urtheaman** [comment]
after reinstallation it's throwing another error.
![Screenshot 2022-03-23 151246](https://user-images.githubusercontent.com/62852336/159670355-a1ea40ef-7d72-4448-8428-1c11724bedcf.png)

**Comment by Andarist** [comment]
I'm paying attention to all the issues reported here. Daily.  

> please resolve all the issues. 13 days ago you've released newer version and 25 days older issues are still not resolved. currently i'm uninstalling this library and material-ui from my project.

What am I supposed to say in response to that? You have installed free software, didn't pay anything for it, you have some configuration problems, and you expect somebody else to investigate this for free? Even though you didn't even prepare a proper repro case for this? How am I even supposed to help you? Am I supposed to **guess** what's the answer to **your** problems?

Sorry for being somewhat harsh here but almost your entire post has a bad, entitled tone.

**Comment by srmagura** [comment]
If you can share a GitHub repro that demonstrates the issue we will happily investigate it.

**Comment by urtheaman** [comment]
@Andarist  Sir, i tried for 2 hrs to properly configure an icon library and i had become frustrated. there was darkness in front of my eyes. then i thought there's probably some issue in the @emotion.js library and threw these ugly words here. I'm sorry, i apologise for my mistake. i should've been polite. i'll keep this in mind again.
