### ISSUE TITLE
Style tags duplicating in Next SSR when importing emotion11 components from custom UI library.

### ISSUE THREAD

**Issue by Adredrs23** [emotion-js/emotion#2698]
**Current behavior:**
We have created a component library using react17 and emotion11. The components are exported using index.ts file.
We have another Nextjs project where we use the component from the library to build our website. Whenever we use any imported component from the library more than once, we see that the <style> for that particular component is duplicated in <head>.

**Things to note:**
1. Wrapping _app.tsx file with CacheProvider solves the duplication issue for emotion components created in Nextjs. For example, the StyledLink component in index.tsx.
2. If you are unable to see the preview of sandbox in the right panel, please try opening it in a new tab,

**To reproduce:**
Please visit this NextJs CodeSandbox (https://stackblitz.com/edit/nextjs-xczyqk) to view the behavior.
The Github repo for the UI Library can be found at https://github.com/Adredrs23/ui-lib

**Expected Behaviour**
 The <style> tag for the component should only be displayed once and not repeated in the head.

**Solutions tried so far:**
1. Wrapping the _app.tsx file with emotion's CacheProvider ( can be seen in the demo provided ).
2. Wrapping the repetitive components inside a parent emotion component ( eg: <Container> in index.tsx ) doesn't solve the issue.

**Environment information:**
- `react` version: 17.0.2
- `@emotion/react` version: 11.7.1

**Screenshots**
![image](https://user-images.githubusercontent.com/60308756/160608801-0ef7c17a-f669-4abe-bbe6-15f1ef7b9ea3.png)

**Comment by Andarist** [comment]
Most likely you just need to wrap your app with a `CacheProvider`. This should deduplicate those styles.

**Comment by Adredrs23** [comment]
> Most likely you just need to wrap your app with a `CacheProvider`. This should deduplicate those styles.

![image](https://user-images.githubusercontent.com/60308756/160617093-4cad86b1-dc30-45cd-a63d-4e981a3bcd5f.png)
I have wrapped it already with CacheProvider as shown in the image above.

**Comment by Andarist** [comment]
You are bundling Emotion dependencies into your library - you should configure them as external in your Rollup config. In a similar way you have already configured React to be an external library

**Comment by Adredrs23** [comment]
Hey, thanks. We are new to this and we somehow missed it.  It was the rollup config as you suggested. Thanks again.
