### ISSUE TITLE
Component selectors can only be used in conjunction with babel-plugin-emotion error while running jest test

### ISSUE THREAD

**Issue by manak1** [emotion-js/emotion#2705]
**Current behavior:**

When I run a test for the component which uses the component selectors I get an error below.
The error doesn't occur while running npm run dev/build.

```terminal
Component selectors can only be used in conjunction with @emotion/babel-plugin.
```

**To reproduce:**

This is my repo : https://github.com/manak1/emotion-jest-nextv12
1. npm i 
2. npm run test src/components/ui/Select

**Expected behavior:**

I  expect to write a test for component which uses component selectors. 

**Environment information:**

- `react` version:  "react": "17.0.2",
- `@emotion/react` version: "@emotion/react": "^11.8.2",

**Comment by markcnunes** [comment]
The version [https://github.com/vercel/next.js/releases/tag/v12.1.4](v12.1.4) has been released already but this issue hasn't been fixed yet.

Someone has already been assigned to this issue on https://github.com/vercel/next.js/issues/35661 so hopefully, it won't be too long until it is fixed.

**Comment by srmagura** [comment]
Thank you @markcnunes for the clarification! 

In the repository provided by the OP, Jest is using swc to compile the code. The `.babelrc` which specifies `@emotion/babel-plugin` is not being used when running the Jest tests. So this is an issue with the Next/swc integration with Emotion (which is managed by the Next team).

I am about to submit a PR to change the error message "Component selectors can only be used in conjunction with @emotion/babel-plugin" to reference the swc Emotion plugin.
