### ISSUE TITLE
grid-area  setting exception

### ISSUE THREAD

**Issue by fenglonghui** [emotion-js/emotion#2706]
`
// grid layout
const Container = styled.div`
  display: grid;
  grid-template-rows: 6rem 1fr 6rem;
  grid-template-columns: 20rem 1fr 20rem;
  grid-template-areas:
    "header header header"
    "nav main aside"
    "footer footer"
  ;
  height: 100vh;
`;

// grid-area 用来给grid子元素起名字
const Header = styled.header`grid-area header`;
const Main = styled.main`grid-area  main`;
const Nav = styled.nav`grid-area nav`;
const Aside = styled.aside`grid-area aside`;
const Footer = styled.footer`grid-area footer`;

`
issue： colon expectedts-styled-plugin(9999)
没有可用的快速修复

![Uploading 1648988093673.jpg…]()

**Comment by fenglonghui** [comment]
![image](https://user-images.githubusercontent.com/12456274/161428660-05468c8b-1d0e-4cd9-832a-41f43e2fecef.png)

**Comment by srmagura** [comment]
When using `styled.header`, `styled.main`, .etc, the string within the backticks must contain valid CSS. 

All CSS rules are of the form `property: value`. So change `grid-area header` to `grid-area: header`. https://developer.mozilla.org/en-US/docs/Web/CSS/grid-area
