### ISSUE TITLE
Support the label css property.

### ISSUE THREAD

**Issue by tkh44** [emotion-js/emotion#272]

**Comment by probablyup** [comment]
I can't find any info on this?

**Comment by probablyup** [comment]
Do you just mean the `label` HTML element?

**Comment by mitchellhamilton** [comment]
It refers to the label property that glamor has. https://github.com/threepointone/glamor/blob/93ea7fddede99c9a6f0b71862171c3a2550fb582/examples/sketches.js#L5

**Comment by mitchellhamilton** [comment]
Closed via #375 and #442
