### ISSUE TITLE
dtslint is unmaintained and causing issues

### ISSUE THREAD

**Issue by srmagura** [emotion-js/emotion#2735]
The [dtslint README](https://github.com/microsoft/dtslint#readme) indicates that the package is no longer being maintained. 

And, dtslint is causing problems for us on the `ts-migration` branch:

1. dtslint is testing against TypeScript 3.8 through 4.5 and `typescript@next`. It should be 3.9 to 4.6 and `typescript@next` based on the DefinitelyTyped support window. This is particularly problematic because we are getting dtslint errors that are specific to TS 3.8.
2. dtslint can produce different results on the Emotion repository depending on whether `yarn build` has been run. Somehow, dtslint is taking the `dist` folders into account when doing its analysis. This quirk can lead to unexpected failures in CI even when dtslint is passing locally.

I've opened an issue, https://github.com/microsoft/DefinitelyTyped-tools/issues/440, to ask how library authors are supposed to test against multiple TS versions. Hopefully someone will respond to that issue and give us some direction on this.

**Comment by Andarist** [comment]
Even if `@definitelytyped/dtslint` is not "intended for public consumption" - it probably isn't impossible to use it, right? For now - I would probably just try that, since the migration from `dtslint` is probably fairly easy.
