### ISSUE TITLE
jsxImportSource not working on cra

### ISSUE THREAD

**Issue by testerez** [emotion-js/emotion#2752]
**Current behavior:**

I followed the [Typescript instructions](https://emotion.sh/docs/typescript) to add emotion to a fresh create-react-app project: https://github.com/testerez/cra-ts-emotion/commit/086cc35cda04a1bb72917ccd3a5b79e81e8be1d9

But when I try to use css prop in any way:
```tsx
<div>
  <div css={{ color: "red" }}>Hello!</div>
  <div css={css({ color: "red" })}>Hello!</div>
  <div
    css={css`
      color: red;
    `}
  >
    Hello!
  </div>
</div>
```
Here is the result I get:

```html
<div>
  <div css="[object Object]">Hello!</div>
  <div
    css="You have tried to stringify object returned from `css` function. It isn't supposed to be used directly (e.g. as value of the `className` prop), but rather handed to emotion so it can handle it (e.g. as value of `css` prop)."
  >
    Hello!
  </div>
  <div
    css="You have tried to stringify object returned from `css` function. It isn't supposed to be used directly (e.g. as value of the `className` prop), but rather handed to emotion so it can handle it (e.g. as value of `css` prop)."
  >
    Hello!
  </div>
</div>
```

Did I miss something?

**To reproduce:**

1. checkout this sample project https://github.com/testerez/cra-ts-emotion
2. run `npm i && npm run start`

**Expected behavior:**

I would expect the `css` prop to work with this setup.

**Environment information:**

- `react` version: `18.1.0`
- `@emotion/react` version: `11.9.0`

**Comment by Andarist** [comment]
IIRC you need to use an explicit pragma in CRA, see this issue: https://github.com/facebook/create-react-app/issues/9847

**Comment by testerez** [comment]
Thanks you @Andarist and @srmagura , It would be nice if CRA could respect `@emotion/react` in tsconfig. It's a bit annoying to hate to remember to add this comment on each new file.
I guess, I could alternatively use `react-app-rewired` to setup the emotion babel plugin.
