### ISSUE TITLE
`ts-migration`: Port change to `@emotion/serialize` types

### ISSUE THREAD

**Issue by srmagura** [emotion-js/emotion#2756]
Port https://github.com/emotion-js/emotion/pull/2572 to the `ts-migration` branch. Waiting for other `ts-migration` stuff to get merged then will do this.

**Comment by Andarist** [comment]
That has been done in the latest merge: https://github.com/emotion-js/emotion/pull/2758/files#diff-ec2de171b3fd05a04be89b82f3a9f0beb0768838544583edc37162fcf9762c62R389
