### ISSUE TITLE
How should we reference the project in the documentation?

### ISSUE THREAD

**Issue by oliviertassinari** [emotion-js/emotion#2767]
On https://mui.com/ we make references to the projects in multiple instances. However, we are struggling to find clarity on what's the official brand. We can find two different conventions used. Which one should MUI use? Thanks

## Lower case: emotion

- <img width="588" alt="Screenshot 2022-05-31 at 17 39 37" src="https://user-images.githubusercontent.com/3165635/171213783-f5ab8fbd-2d4e-4259-93d6-0243f6bc289b.png">
https://github.com/emotion-js/emotion
- <img width="629" alt="Screenshot 2022-05-31 at 17 41 03" src="https://user-images.githubusercontent.com/3165635/171214052-8bc684e3-4aa2-494a-a3ad-274080d96dd9.png">

https://emotion.sh/docs/@emotion/cache#primary-use-cases

## Upper case: Emotion

- <img width="385" alt="Screenshot 2022-05-31 at 17 41 58" src="https://user-images.githubusercontent.com/3165635/171214247-f5bc8dbf-671e-4af8-8050-cb8175c6353b.png">
https://github.com/emotion-js/emotion
- <img width="729" alt="Screenshot 2022-05-31 at 17 41 44" src="https://user-images.githubusercontent.com/3165635/171214205-d2a44f2d-d358-4a38-8f0a-44fd5bbfe772.png">

https://emotion.sh/docs/emotion-11

**Comment by srmagura** [comment]
I prefer it with a capital E. 🙂

**Comment by oliviertassinari** [comment]
Ok thanks, we will use this.
