### ISSUE TITLE
using @emotion/server  and  @emotion/css together makes an Error - TS2304: Cannot find name 'Node' and 'ChildNode'

### ISSUE THREAD

**Issue by bumjun-kim** [emotion-js/emotion#2784]
**Current behavior:**

I am using @emotion/css and @emotion/server   two modules together.
`
"@emotion/css": "^11.9.0",
"@emotion/server": "^11.4.0",
`

Somehow, when I try to build my typescript files,
I get these error messages.
`
 node_modules/@emotion/cache/types/index.d.ts:37:15 - error TS2304: Cannot find name 'Node'.
 node_modules/@emotion/sheet/types/index.d.ts:7:14 - error TS2304: Cannot find name 'Node'.
 node_modules/@emotion/sheet/types/index.d.ts:18:14 - error TS2304: Cannot find name 'Node'. 
 node_modules/@emotion/sheet/types/index.d.ts:21:12 - error TS2304: Cannot find name 'ChildNode'.
`

Problems occur from either @emotion/cache and @emotion/sheet.

**Environment information:**

    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "@types/react": "^17.0.33",
    "@types/react-dom": "^17.0.10",
    "@emotion/css": "^11.9.0",
    "@emotion/server": "^11.4.0",
    "html-pdf": "^3.0.1",
    "htmlparser2": "^7.1.2",

Hope I put all required information for this issue.

Can anyone check this issue ?

**Comment by bumjun-kim** [comment]
I thought this is a bug,
because when I opened package-lock.json file, 
`
"node_modules/@emotion/cache": {
      "version": "11.9.3",
      "resolved": "https://registry.npmjs.org/@emotion/cache/-/cache-11.9.3.tgz",
      "integrity": "sha512-0dgkI/JKlCXa+lEXviaMtGBL0ynpx4osh7rjOXE71q9bIF8G+XhJgvi+wDu0B0IdCVx37BffiwXlN9I3UuzFvg==",
      "dependencies": {
        "@emotion/memoize": "^0.7.4",
        **"@emotion/sheet": "^1.1.1",**
        "@emotion/utils": "^1.0.0",
        "@emotion/weak-memoize": "^0.2.5",
        "stylis": "4.0.13"
      }
    },

"node_modules/@emotion/css": {
      "version": "11.9.0",
      "resolved": "https://registry.npmjs.org/@emotion/css/-/css-11.9.0.tgz",
      "integrity": "sha512-S9UjCxSrxEHawOLnWw4upTwfYKb0gVQdatHejn3W9kPyXxmKv3HmjVfJ84kDLmdX8jR20OuDQwaJ4Um24qD9vA==",
      "dependencies": {
        "@emotion/babel-plugin": "^11.7.1",
        "@emotion/cache": "^11.7.1",
        "@emotion/serialize": "^1.0.3",
        **"@emotion/sheet": "^1.0.3",**
        "@emotion/utils": "^1.0.0"
      },

    "node_modules/@emotion/sheet": {
      **"version": "1.1.1",**
      "resolved": "https://registry.npmjs.org/@emotion/sheet/-/sheet-1.1.1.tgz",
      "integrity": "sha512-J3YPccVRMiTZxYAY0IOq3kd+hUP8idY8Kz6B/Cyo+JuXq52Ek+zbPbSQUrVQp95aJ+lsAW7DPL1P2Z+U1jGkKA=="
    },
`

Some of  @emotion/sheet  was 1.0.3, but some of them were 1.1.1  .
Is it a problem because they are dependant to different version each other?

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by bumjun-kim** [comment]
@Andarist You are absolutely right. 
I made a sample repository at <https://github.com/bumjun-kim/sample-for-error|sample repository>

Can you please clone the project, and check Readme.md file to solve the problem ?

**Comment by Andarist** [comment]
Most likely you need to include DOM libs here:
https://github.com/bumjun-kim/sample-for-error/blob/fdcd7acb5ab07aad82a8ed3b1943233b4af7b67f/tsconfig.json#L14

See the docs for `tsconfig.json#compilerOptions.lib`: https://www.typescriptlang.org/tsconfig#lib

**Comment by bumjun-kim** [comment]
Omg. I do appreciate your help. Couldn't be solved on my own.

Thnx 👍
