### ISSUE TITLE
Adding custom declaration file isn't recognized

### ISSUE THREAD

**Issue by omerfaran** [emotion-js/emotion#2787]
Hello,

I'm honestly not sure that it's a bug, but I followed the docs, and researched this a bit, and it should have worked.

I'm extending the type declarations via a custom declarations file, to use a custom Theme interface in Typescript.
I'm following the docs: https://emotion.sh/docs/typescript

However the file emotion.d.ts isn't being recognized, and Theme remains an empty object. If I create a file global.d.ts, it does work.

Is it the expected behavior? 

Thanks in advance

**To reproduce:**

Create a custom declaration file, to create an interface for Theme provider.

**Expected behavior:**

Typescript will recognize Theme types, instead of an empty object

**Environment information:**

"@emotion/styled": "^11.9.3",
"react": "^18.2.0",

- `react` version:
- `@emotion/react` version:

**Comment by srmagura** [comment]
Hey @omerfaran, I followed the steps in the docs and it worked for me. [My repo](https://github.com/srmagura/emotion-2787)

Make sure your `.d.ts` file matches the `include` patterns in your `tsconfig.json`. Take a look at my repo and let me know if you get it to work.

**Comment by Andarist** [comment]
Like Sam has suggested - this file is probably ignored somehow by TS because of our config. If you don't want to touch `tsconfig.json` then you can usually also fix this by importing this file explicitly from the root of your app:
```ts
import './emotion-theme'

// or

/// <reference path="./emotion-theme.d.ts" />
```

**Comment by omerfaran** [comment]
Thanks a lot @srmagura and @Andarist I'll try that
