### ISSUE TITLE
Getting TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_5__.createContext) is not a function

### ISSUE THREAD

**Issue by praveen7557** [emotion-js/emotion#2792]
**Current behavior:**

I'm using `react-select` which uses `@emotion/react`. I'm getting the below error when I try to use the select component. I'm trying to use the component in NextJs App with TypeScript.

1. I'm not able to reproduce this in codesandbox

<img width="1136" alt="Screenshot 2022-06-23 at 10 15 24 AM" src="https://user-images.githubusercontent.com/13882201/175211270-4a867953-e27b-44d6-b324-78214efc7e12.png">

**Environment information:**

- `react` version: `18.1.0`
- `@emotion/react` version: `11.9.3`

**Comment by Andarist** [comment]
A repro case is required for issues like this - it can be a standalone github repository if you can't repro this on CodeSandbox. If you provide one I'm going to happily reopen the issue.
