### ISSUE TITLE
Unexpected "You have illegal escape sequence..."

### ISSUE THREAD

**Issue by tills13** [emotion-js/emotion#2802]
**Description**
```
Unexpected "You have illegal escape sequence..."
```
This error is showing up for styled elements that do not have any escapes in a Next 12.2 project using their Emotion SWC compiler -- just hoping to get some clarification before filing an issue with them.

What's the intended function of [these lines](https://github.com/emotion-js/emotion/blob/ce9873faabef8baf4eeebf8fab0d7b1a46ff74c7/packages/styled/src/base.js#L94-L97)? Particularly in the context of sourceMap insertion?

Let's say I have 

```
const Element = styled.span`
  display: block;
`
```

Note how there are no escapes and no interpolation. This means the anon function in the linked lines should receive `[['display: block']]` as its arguments. With sourcemaps enabled, the function receives the sourcemap as the second arg (implying interpolation).

`args.length === 2`
`args[0][1] === undefined` 

Despite there being no escaping at all, I receive the error talked about in this issue. 

My question is, then, is this NextJS inserting the sourceMaps incorrectly (perhaps trying to be clever by interpolating vs. string concatenating) or do those lines need a little extra logic to ignore the interpolated source map?

**Comment by tills13** [comment]
ok I actually don't think this has to do with what NextJS is doing at all. After some more testing, I discovered that the error only happens for templates that have been "cooked" (e.g. by TypeScript). So the input of the function is actually more like 

```
[
  [
    "display: block;",
    raw: "display: block;",
  ], 
  // source map
]
```

in this particular case, these cooked template literals are coming from an upstream component library that's outputting ES5. Given that the template has already been compiled, should it just be trusted? Or, at least, since the error branches don't throw or return, the error should be suppressed?

I've set up a minimum example of the error here: https://github.com/tills13/nextjs-emotion-escape

Let me know what you think. I can put together a PR for whatever you think the resolution should be.

**Comment by srmagura** [comment]
Thanks for providing a runnable example. This is the code causing the problem:

```tsx
const Icon = styled.span`
  &::before {
    content: "\203A";
    color: green;
  }
`;
```

The error printed by Emotion is legit, since `\203A` is not a valid escape sequence:

```tsx
const s = `\203A`; // Error: Legacy octal escape is not permitted in strict mode
```

Change your code to this and it will work:

```tsx
const Icon = styled.span`
  &::before {
    content: "\u203A";
    color: green;
  }
`;
```

**Comment by tills13** [comment]
Hm, maybe I'm missing something here but adding the `u` results in the literal "203A" being displayed rather than the right-arrow quote symbol

<img width="106" alt="Screen Shot 2022-07-03 at 11 13 41 AM" src="https://user-images.githubusercontent.com/1269421/177052215-c68dd885-4075-44a7-8d37-fa74de399767.png">

Also, just to clarify something about my code, the red symbol (the "cooked" version) is the one that seems to be triggering the error. With your solution in the codebase, the error is still present.

**Comment by srmagura** [comment]
OK, I figured out why we are seeing different things. I was testing without the swc plugin enabled, and you are testing with it enabled.

Using only this code in `index.jsx`:

```tsx
import styled from "@emotion/styled";

const Icon = styled.span`
  &::before {
    content: "\u203A";
    color: green;
  }
`;

export default function IndexPage() {
  return <Icon />;
}
```

With the swc plugin **enabled**, it displays:
![image](https://user-images.githubusercontent.com/801549/177053657-422dee45-6921-4890-a4e4-343d8cff3403.png)


With the swc plugin **disabled**, it displays:
![image](https://user-images.githubusercontent.com/801549/177053616-fe8a9073-4c8a-4ed5-8e14-f1297240bcfd.png)

I think this is a minimal repro that can be submitted to the Next.js team.

The thing with the cooked JS seems like a slightly different issue, though likely related. It only produces an error when the swc plugin is enabled, so I don't think it's a problem with Emotion.
