### ISSUE TITLE
`@emotion/primitives` README links to very old CodeSandbox

### ISSUE THREAD

**Issue by srmagura** [emotion-js/emotion#2806]
Also react-sketchapp seems almost completely unused so this example should probably just be removed. https://www.npmjs.com/package/react-sketchapp

**Comment by yoshitaka7** [comment]
@srmagura 
Hello, I'd like to contribute to this issue!
Can I just remove the react-sketchapp part in the readme?

**Comment by srmagura** [comment]
Ideally, we would also update that CodeSandbox to be on Emotion 11. Though, I saw it has a very small number of views so it could also probably just be removed.

**Comment by yoshitaka7** [comment]
@srmagura @Andarist 
Thank you both for your kindness.
I'll try the update first, but if it's too difficult, I'll remove the codesandbox link and the react-sketchapp part and create a PR.
