### ISSUE TITLE
TypeScript error when using `styled` with Mantine

### ISSUE THREAD

**Issue by Gil3co** [emotion-js/emotion#2807]
**Current behavior:**

When trying to style a component, like Button from @mantine/core, there is a TypeScript error when trying to pass children to the button, i.e. the text, and the styling doesn't work.
The error:

`const StyledButton: StyledComponent<{
    theme?: Theme | undefined;
}, {}, {}>
Type '{ children: string; }' has no properties in common with type 'IntrinsicAttributes & { theme?: Theme | undefined; }'.ts(2559)`

**To reproduce:**

1. Go to this sandbox: https://codesandbox.io/s/emotion-issue-template-forked-knhi56?file=/src/App.tsx
2. Run the example.
3. See the error on `StyledButton`.

**Expected behavior:**

The Button is styled and there is no TypeScript error.

**Environment information:**

- `react` version: 17.0.2
- `@emotion/react` version: 11.9.3

When I used only React, Mantine and Emotion in the sandbox, it worked well, as it should. When I changed the direction to RTL (my app should support this) and added some plugins to Mantine, there was no TypeScript error, but the styling didn't work. When I added the rest of my dependecies (copied and pasted my package.json), I got the error as well

**Comment by srmagura** [comment]
There is an incompatibility between the Mantine `Button` component definition and `@emotion/styled`. We've seen other issues like this.

They define the `Button` props in a complex way:

- `ButtonProps`: https://github.com/mantinedev/mantine/blob/81fdbe99a77c20e55e766480fec360f289444298/src/mantine-core/src/components/Button/Button.tsx#L69
- `PolymorphicComponentProps`: https://github.com/mantinedev/mantine/blob/81fdbe99a77c20e55e766480fec360f289444298/src/mantine-styles/src/theme/types/Polymorphic.ts#L20

One workaround would be to use [Mantine's own styling system](https://mantine.dev/theming/create-styles/):

> We recommend using createStyles to create styles for the rest of your application as it provides the most convenient way to utilize Mantine theme

**Comment by srmagura** [comment]
Found the issue. You are using `@types/react` and `@types/react-dom` version 18 alongside `react` and `react-dom` version 17. The versions need to match.

I got peer dependency issues when trying to use Mantine with React 18, so the best fix is probably to downgrade `@types/react` and `@types/react-dom` to `^17`.

**Comment by Gil3co** [comment]
Oh, thanks! I can't believe it!
I tried downgarding, but now I got other errors, regarding other props (type, radius, etc). So I guess I would just use createStyles like you and Mantine suggest, and use emotion for non-Mantine components. Thanks a lot!

**Comment by musicalmacdonald** [comment]
I know this is an old issue, but in case anyone else runs across it; Mantine has docs on how to deal with this situation starting at v5: https://v6.mantine.dev/styles/styled/#polymorphic-components
