### ISSUE TITLE
Nested selectors are not working correctly with @emotion/styled

### ISSUE THREAD

**Issue by jjuannn** [emotion-js/emotion#2820]
**Current behavior:**

Im trying to copy the following codepen: https://codepen.io/toddwebdev/pen/yWMgQX?editors=1100 with the following code:

```
const CardContainer = styled(Flex)`
  flex-direction: column;
  padding: 12px;
  width: 100%;
  max-width: 450px;
  height: auto;
  border-radius: 32px;
  overflow: hidden;
  z-index: 1;
  background: rgba(218, 228, 242);
  box-shadow: 4px 4px 12px 2px rgba(black, 0.6);
  transition: 0.2s;

  &:not(:first-child) {
    background: red;
    margin-left: -50px;
  }

  &:hover,
  &:focus-within {
    transform: translateY(-1rem);
  }

  &:hover ~ &,
  &:focus-within ~ & {
    transform: translateX(50px);
  }
`;
```

but the last statement of the styles are not being applied. The original CSS code is 
```
.card:hover ~ .card,
.card:focus-within ~ .card {
  transform: translatex(var(--distance));
}
```

**Expected behavior:**

The styles being applied to my react component

**Environment information:**

- `react` version: 18.1.0
- `@emotion/react` version: 11.9.0

Maybe it's not a bug and the syntax that i'm using is incorrect?

**Comment by srmagura** [comment]
Please always try to submit a runnable example that shows the problem.

I tried out some very similar code and it worked for me. https://codesandbox.io/s/emotion-tilde-selectors-85wtjj?file=/src/App.tsx

**Comment by jjuannn** [comment]
I'll keep it in mind for next time. I fixed it by replacing `styled(Flex)` with `styled.div`.

Thanks @srmagura
