### ISSUE TITLE
Components swallowing event props

### ISSUE THREAD

**Issue by colepeters** [emotion-js/emotion#283]
- `emotion` version: 7.2.0
- `react` version: 15.3.2

Relevant code.

```javascript
import React from 'react';
import styled from 'react-emotion';
import { css, injectGlobal } from 'emotion';
import { ThemeProvider, withTheme } from 'theming';
import { space } from 'styled-system';

…

const Button = withTheme(styled('button')`
  ${space};
  ${base};
  ${ p => p.secondary ? secondary : primary };
  ${ p => p.small && small };
`);

…

<Button mb={3} onClick={ () => alert('Test button') }>
  Primary button
</Button>
```

**What you did:**
Tried to pass an `onClick` prop to my component.

**What happened:**
The function passed to `onClick` was not executed when clicking on my component in the browser.

![onclick](https://user-images.githubusercontent.com/1713932/29663909-3b3e040a-88c5-11e7-911a-59d7b169f11d.gif)

**Problem description:**
My `onClick` function is not executed.

**Suggested solution:**
🤔 ❓

**Comment by tkh44** [comment]
Not sure on this. I can't reproduce.

**Comment by greggb** [comment]
Where is `${base};` coming from? What are the two console errors?
