### ISSUE TITLE
Add how to write animation rule in object styles in Keyframes Page.

### ISSUE THREAD

**Issue by nikeeshi** [emotion-js/emotion#2844]
**Description:** Add how to write animation rule in object styles in Keyframes Page. Writing animation rule in object styles is possible but the explanation is missing. See this comment https://github.com/emotion-js/emotion/issues/1259#issuecomment-505166776 . This comment explains how we can convert keyframes into object style.

**Documentation links:** https://emotion.sh/docs/keyframes

**Comment by srmagura** [comment]
I tested keyframes + object styles and found that the workaround shown in the comment you linked is no longer necessary.

Both of these work:

```tsx
render(
  <div
    css={{
      animation: `${bounce} 1s ease infinite`
    }}
  >
    some bouncing text!
  </div>
)

render(
  <div
    css={{
      animation: bounce,
      animationDuration: '1s',
      animationIterationCount: 'infinite'
    }}
  >
    some bouncing text!
  </div>
)
```

(`bounce` is an object produced by the `keyframes` function from `@emotion/react`.)
