### ISSUE TITLE
Enzyme tests break after update to 11.6+

### ISSUE THREAD

**Issue by orest22** [emotion-js/emotion#2852]
**Current behavior:**

After updating `@emotion/react` to any version after 11.5 tests  written with `enzyme` + `enzyme-adapter-react-16` break.  It can be caused by this update https://github.com/emotion-js/emotion/pull/2542/files#diff-8de8dbc18d92078ff203c72ffc85251af6498232e6ac5d186e8ff65baa3d1f5dR144. Enzyme adapter is not able to figure out the DOM node with `getDOMNode` plus it breaks all `simulate` calls. 

**To reproduce:**

https://codesandbox.io/s/emotion11-5-enzyme-8klodx?file=/src/__tests__/Button.test.tsx

1. Switch to the Tests tab
2. Observe error
3. If the version of emotion is switched to 11.5 the error is gone

**Expected behavior:**

No breaking change is being introduced

**Environment information:**

- `react` version: 16.14
- `@emotion/react` version: 11.9

**Comment by Andarist** [comment]
Are you saying that it has stopped working with [`@emotion/react@11.6.0`](https://github.com/emotion-js/emotion/releases/tag/%40emotion%2Freact%4011.6.0)?

**Comment by srmagura** [comment]
Thank you for linking the exact commit that caused the problem. That function changed from returning the element directly to returning the element wrapped in a React fragment. I assume the fragment is preventing Enzyme from finding the correct DOM node.

It is bad that we accidentally introduced a breaking change, but the design of Enzyme makes it hard to avoid this. I think the best solution would be to stay on Emotion 11.5 until you can move your tests off of Enzyme. Alternatively, you could use the workaround you presented (as a stepping stone until you can move off of Enzyme):

```ts
const button = wrapper.find(MuiButton)
```

Reference: [Enzyme is dead](https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl)

**Comment by Andarist** [comment]
Yeah, I don't think there is anything that we can do about this - your Enzyme tests were relying on the internal structure of our components and we just don't consider that to be part of the public API.

Related discussions:
https://github.com/emotion-js/emotion/issues/2669
https://github.com/emotion-js/emotion/issues/2553

**Comment by torressam333** [comment]
Downgrading all relevant packages to be 11.5 or lower still doesn't work for me. Using React 16.8., enzyme 11.10 and enzyme adapter 16.

```
 "@emotion/react": "11.0.0",
        "@emotion/styled": "11.0.0",
        "@emotion/server": "11.0.0",
        "@emotion/css": "11.0.0",
```
