### ISSUE TITLE
Emotion/Cache throws exeption with newest patch version (related to #2751)

### ISSUE THREAD

**Issue by swernerx** [emotion-js/emotion#2863]
**Current behavior:**

```
const isIgnoringComment = element =>
  element.type === 'comm' && element.children.indexOf(ignoreFlag) > -1
```

of `StylisPlugin` throws an exception: Cannot access `.type`; `element` is undefined.

**To reproduce:**

Code with multiple `:nth-child` in one line might produce an `undefined` element.

```js
 terminatedContract: {
    '& .contractIcon, tr:nth-child(1) td:nth-child(1), tr:nth-child(n+2) td': {
      opacity: 0.4
    }
  }
```

**Expected behavior:**

Checking whether the `element` is not null fixes the issue:

```
const isIgnoringComment = element =>
  element && element.type === 'comm' && element.children.indexOf(ignoreFlag) > -1
```

**Environment information:**

- `react` version: 18.2.0
- `@emotion/react` version: 11.10.0
- `@emotion/cache` version 11.10.2

**Comment by Andarist** [comment]
Could you share a runnable repro case? I need the full example to add a test and fix the issue.
