### ISSUE TITLE
Loading emotion without it being a part of an app/from CDN

### ISSUE THREAD

**Issue by hamza1311** [emotion-js/emotion#2866]
**The problem**

I'm using React to build web components. Each component is loaded independently of the other, however there may be more than one component one a page. When there are multiple components present on a page, this warning is logged to console

> You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.

I would like to have the ability import a component, without loading emotion alongside it. Emotion can be loaded separately, just like React.

**Proposed solution**

Allow loading from CDN, similar to React. When `react` is loaded from a CDN, it adds sets `window.React` to it's instance which can be used throughout the application by multiple components. Emotion can take a similar approach

**Additional context**

These components use [MUI](https://mui.com/), which requires emotion to be present.

My `rollup.config.js`:
```js
export default components.map(component => ({
    input: join(componentsDir, `${component}.tsx`),
    output: [
        {
            file: join(dist, `${component}.js`),
            format: "iife",
            sourcemap: !production,
            name: component,
            globals: {
                // 'emotion': ???
                react: 'React',
                'react-dom': 'ReactDOM'
            }
        },
    ],
    external: [
        // 'emotion' ?
        'react',
        'react-dom'
    ],
    plugins: [
        resolve(),
        commonjs(),
        typescript({ tsconfig: "./tsconfig.json", sourceMap: !production }),
        production && terser()
    ],
}))
```

**Comment by srmagura** [comment]
Hmm, this request makes sense but would likely take a non-trivial amount of work. It would require changes to both Emotion and MUI.

I have heard of this architectural pattern, which some call "microfrontends", but I don't believe it is super common — so I'm not sure if it's worth doing a lot of work to support it.

I would expect your microfrontends to work correctly even though the "multiple `@emotion/react`" warning is printed. Though there is still the downside that you are loading the Emotion JavaScript once for each microfrontend.

I'm guessing that you are only doing client-side rendering here... server-side rendering would likely complicate this situation even further.

I don't want to say that we will never support this, but it is unlikely in the short to medium term. I think your options for now are to either just ignore the warning (if your app still works) or stop using Emotion within a microfrontends architecture.

I'm not sure if this would help, but maybe it would be beneficial to encapsulate each web component within a shadow DOM?

**Comment by hamza1311** [comment]
The app works, although it emits the warning. However emotion is loaded as part of every component, which means it's also a part of each component's bundle, increasing the bundle size.

I'm only doing client side rendering. Hydrating from resources like that sounds like a nightmare to deal with.

It's not too big of an issue for this use-case (this is mostly for an internal tool). I don't know if my other option - `styled-components` - supports this either (I can't stop using MUI).

I haven't tried shadow DOM with this, not sure if it'll work with my application though

**Comment by Andarist** [comment]
I never have actually done this but perhaps you could just use this UMD bundle and refer to `window.emotionReact`:
https://unpkg.com/@emotion/react@11.10.0/dist/emotion-react.umd.min.js

**Comment by hamza1311** [comment]
Thanks @Andarist, UMD bundle did the job. I'll leave this issue open in case there's something that has to be done regarding this

**Comment by hamza1311** [comment]
Update on this: I tried this approach with preact but it emotion is unable to find it, resulting in error:
```
Uncaught TypeError: react.withEmotionCache is not a function
```
![image](https://user-images.githubusercontent.com/47357913/194094293-d6bb2864-89c5-419f-85b5-43c6efadd91b.png)

Any ideas?

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by Hetnon** [comment]
I have the same problem, but I'm experiencing some issues with some states not responding correctly. I have this warning and I'm trying to fix it to see if that's the problem but can't find to solve it easily.
I'm trying to load emotion conditionally only if it's not loaded yet, but can't seem to find a way to make webpack not to load it anyway based on the package.json configurations
