### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by SimenB** [emotion-js/emotion#2873]
**Description:**

https://emotion.sh is unavailable

<img width="780" alt="image" src="https://user-images.githubusercontent.com/1404810/187656975-2a2b9170-ec5f-43f5-bbbd-c38cb0dbed0e.png">

**Documentation links:**

https://emotion.sh

**Comment by Andarist** [comment]
Hm, it works for me - could you recheck? Or recheck using your mobile connection or something?

**Comment by SimenB** [comment]
Huh, works now. Glitch in the matrix? 😅
