### ISSUE TITLE
Layout shift with nextjs

### ISSUE THREAD

**Issue by ryankauk** [emotion-js/emotion#2875]
**Current behavior:**

Hey, I've been trying to debug an issue with emotion that's causing some layout shifting and affecting some benchmarks. I broke it down to the smallest reproducible example I could while keeping some implementation that's required by my use case. I've tested it both with swc and babel with same results. I'd like to know what about this is causing the layout shift and probably some follow up questions after that.

**To reproduce:**

The issue doesn't appear when running next in dev mode so to see the issue run `yarn build && yarn start`.

I've tried both with safari and chrome same results. Seems to happen on first load so you'll have to disable cache in inspector window with multiple page refreshes to see it.

https://github.com/ryankauk/emotion-cls

**Expected behavior:**

Not to cause layout shift

**Environment information:**

- `react` version: provided in repo
- `@emotion/react` version: provided in repo

**Comment by Andarist** [comment]
If you rely on our 0-config SSR (which is also the only way to leverage streaming SSR) then you should avoid the lobotomized owl selector or tweak it as follows:
```diff
diff --git a/pages/index.tsx b/pages/index.tsx
index 24dd548..1f21ce7 100644
--- a/pages/index.tsx
+++ b/pages/index.tsx
@@ -16,7 +16,7 @@ export default function CatchAll() {
             height: 200px;
             width: 100%;
           }
-          & > * + * {
+          & > *:not(style) + * {
             margin-top: 70px;
           }
         `,
```

**Comment by ryankauk** [comment]
Oh ok that makes sense, I wasn't sure if there was something I was doing wrong in my configuration that caused the style elements on node. 

Thank you!
