### ISSUE TITLE
eslint: Unknown property 'css' found react/no-unknown-property

### ISSUE THREAD

**Issue by chrisweb** [emotion-js/emotion#2878]
**Current behavior:**

eslint react plugin (eslint-plugin-react) emits error that the "css" property is unknown

the rule documentation is here: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unknown-property.md

the error appears if you use a version of eslint-plugin-react > 7.31.1

**To reproduce:**

https://codesandbox.io/s/interesting-raman-2ko96i?file=/src/App.tsx

I did not use the emotion codesandbox template but created a new codesandbox with nodejs as environment, to have a terminal and to be able to run the "npm run lint" command in that terminal (I think you need to be logged in codesanbox to run commands in the terminal)

In the App.tsx I listed the steps I did to create this example

**Expected behavior:**

no linting error "Unknown property 'css' found react/no-unknown-property"

**Environment information:**

    "@emotion/css": "11.10.0",
    "@emotion/react": "11.10.4",
    "@emotion/styled": "11.10.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "eslint": "8.23.0",
    "eslint-plugin-react": "7.31.4",

As suggested by ljharb, in the [issue 3384](https://github.com/jsx-eslint/eslint-plugin-react/issues/3384#issuecomment-1236136983) over at eslint-plugin-react, here is a ticket for emotion js

**Comment by ljharb** [comment]
Namely, that emotion should at least support, and ideally require, the attribute name to have a data- prefix, instead of just “css”.

**Comment by srmagura** [comment]
You should configure that ESLint rule to ignore the `css` prop. The rule is not smart enough to know that you are using `@emotion/react` to handle the `css` prop before it reaches the DOM element.

> Namely, that emotion should at least support, and ideally require, the attribute name to have a data- prefix, instead of just “css”.

Allowing/requiring users to write `data-css={...}` would be misleading, because the value of the `css` prop is not placed on the DOM element as a data attribute.

**Comment by ljharb** [comment]
It’s already misleading, because DOM elements can’t have a css attribute.

**Comment by chrisweb** [comment]
[ljharb](https://github.com/ljharb) suggested some solutions to the problem in his follow up comment https://github.com/jsx-eslint/eslint-plugin-react/issues/3384#issuecomment-1236258851 and then [sjarva](https://github.com/sjarva) gave an example (based on suggestions to use ignore in the edited comment https://github.com/jsx-eslint/eslint-plugin-react/issues/3384#issue-1360786232 from [diegohaz](https://github.com/diegohaz)) of how to keep the rule activ but also exclude the css attribute from the list of properties that get checked https://github.com/jsx-eslint/eslint-plugin-react/issues/3384#issuecomment-1236371796

> The rule is already configurable with ignore, so the users of emotion should add css as ignored property, when configuring this rule:

eslintrc.js version:

```js
"rules": {
    "react/no-unknown-property": ['error', { ignore: ['css'] }]
}
```

eslintrc.json version

```json
    "rules": {
        "react/no-unknown-property": ["error", { "ignore": ["css"] }]
    },
```

Also worth mentioning is probably that if you want to apply this extra rule only to a file or a group of files you can use the overrides key: [eslint overrides configuration](https://eslint.org/docs/latest/user-guide/configuring/rules#using-configuration-files-1)

I used this suggestion using "eslint-plugin-react": "7.31.5" and it fixed my linting

so this ticket probably more a request to update the emotion documentation and have an eslint section / page that explains how to add the extra configuration, similar to that emotion documentation page that explains how to configure tsconfig for typescript users!?

**Comment by chrisweb** [comment]
@srmagura I added a PR for a documentation update that you might want to consider: https://github.com/emotion-js/emotion/pull/2882
