### ISSUE TITLE
CSS variables should not be prefixed

### ISSUE THREAD

**Issue by siriwatknp** [emotion-js/emotion#2887]
**Current behavior:**

Some specific variable such as `--CircularProgress-animation` is prefixed with `--webkit`. This looks like a bug to me because this variable is not prefixed `--Circle-animation`.

**To reproduce:**

1. Open this [Code Sandbox](https://codesandbox.io/s/emotion-animation-bug-emifih?file=/index.js)
2. Inspect the box
3. You will see this: 
    <img width="410" alt="Screen Shot 2565-09-08 at 17 17 23" src="https://user-images.githubusercontent.com/18292247/189097719-5f746ed5-a562-4e89-9099-6c878a7a083f.png">
    

**Expected behavior:**

The CSS variable should not be prefixed.

**Environment information:**

- `react` version: 17.0.2
- `@emotion/react` version: 11.4.0

**Comment by Andarist** [comment]
Could you report it here: https://github.com/thysultan/stylis/ ?

**Comment by siriwatknp** [comment]
Done. https://github.com/thysultan/stylis/issues/301
