### ISSUE TITLE
Global component doesn't work with Vite + TypeScript

### ISSUE THREAD

**Issue by rodrigocfd** [emotion-js/emotion#2901]
**Current behavior:**

The `Global` component gives the following error:

> Type '{ children: Element; styles: SerializedStyles; }' is not assignable to type 'IntrinsicAttributes & GlobalProps'.
> 
> Property 'children' does not exist on type 'IntrinsicAttributes & GlobalProps'.ts(2322)

When running with `npm run dev`, a blank page is shown. No errors in the console.

Screenshot:

![emotion-global-error](https://user-images.githubusercontent.com/1283868/192013075-4172d7f2-5327-41de-b729-9fb4df694c97.png)

**To reproduce:**

Repo with a minimal reproducible example:

https://github.com/rodrigocfd/emotion-global-error

**Expected behavior:**

`Global` component to work according to the [documentation](https://emotion.sh/docs/globals).

**Environment information:**

- `react` version: 18.2.0
- `@emotion/react` version: 11.10.4

**Comment by srmagura** [comment]
As shown in the documentation, `<Global />` does not allow children.

**Comment by rodrigocfd** [comment]
Oh I completely missed that. Thank you.

As a suggestion, the docs could explicitly say something like "note that `Global` accepts no children". That would've helped me right away.
