### ISSUE TITLE
what the difference between '@emotion/css' and '@emotion/css/macro' 

### ISSUE THREAD

**Issue by AttackXiaoJinJin** [emotion-js/emotion#2904]
**Description:**

when i use jest to test cx from '@emotion/css/macro' and '@emotion/css'，i find the cx from '@emotion/css/macro' is undefined but the `@emotion/css`'s is a function：

```
"@emotion/css": "^11.10.0",
```

```
import { cx } from '@emotion/css/macro';
import { cx as goodCx } from '@emotion/css';

describe('mustache2Seg', () => {
  console.log(cx,goodCx,'goodCx8')
})

```

<img width="479" alt="image" src="https://user-images.githubusercontent.com/26433572/192952097-b43382fc-8b01-4fec-8971-9b5008b5d88b.png">

**Documentation links:**
https://emotion.sh/docs/babel-macros

I didn't see the detail of difference between use 'xx/marco' or not, please tell me what the difference between '@emotion/css' and '@emotion/css/macro' , thanks a lot !

**Comment by Andarist** [comment]
`@emotion/css/macro` is meant to be used in conjunction with `babel-plugin-macros`. It just provides some minor build-time optimizations and DX improvements (like labelling the class names)

**Comment by AttackXiaoJinJin** [comment]
ok, i understood, thanks for reply so quickly !
