### ISSUE TITLE
Support reactive frameworks like Qwik

### ISSUE THREAD

**Issue by wmertens** [emotion-js/emotion#2907]
**The problem**

[Qwik](https://qwik.builder.io/) is the new hot kid on the block, but it doesn't have CSS-in-JS support yet.

With its resumable reactivity, Qwik would only load the JS needed to calculate a given CSS if one of its inputs changes.

I verified that using `css` inside the render function just works, except for SSR support: Qwik only does streaming SSR so there would be a FoUC until the styles are appended to the document.

I prefer the `styled` approach anyway, so it would be a matter of porting that from React to Qwik, as well as the ThemeProvider.

**Proposed solution**

First, create a `styled$` helper. Qwik will make it lazy-loading, and SSR will just work thanks to the Injection component. It would be great if the existing helper code (like Injection) could be refactored to support both React and Qwik easily.

Secondly, to make reactivity even better, it would be amazing if instead of a class string, Emotion generated a classes object of `{[className: string]: true | Signal}`. Meaning, there should be a way to structure the CSS template so that an embedded function causes a subset of rules to go into a separate class, and if that function returns a Signal, it is passed into the classes object. 

The result of that will be that if the Signal becomes truthy, then the class will be applied without having to run Emotion.

(Signal support will be merged soon in Qwik)

**Additional information**

Here's the index.tsx I used for testing Emotion inside a route. The SSR doesn't give it style, and clicking then loads Emotion and sets the styles.

```js
import { component$, useStore } from "@builder.io/qwik";
import { DocumentHead } from "@builder.io/qwik-city";
import { css } from "@emotion/css";

export default component$(() => {
  const store = useStore({ hi: false });
  const color = "white";
  const classes = css`
    padding: 32px;
    background-color: ${store.hi ? "hotpink" : "grey"};
    font-size: 24px;
    border-radius: 4px;
    &:hover {
      color: ${color};
    }
  `;
  return (
    <div class={classes} onClick$={() => (store.hi = !store.hi)}>
      Click to change color.
    </div>
  );
});

export const head: DocumentHead = {
  title: "Emotion test",
};
```

**Comment by Andarist** [comment]
I'm afraid that I'm not familiar enough with Qwik to work on this. We could consider including a community-provided implementation as part of this monorepo or as part of Emotion's GitHub organization.

**Comment by wmertens** [comment]
I completely understand. I'll give it a shot :-)

I'll close this for now to keep your issues clean.
