### ISSUE TITLE
eslint-plugin: Add a "recommended" config preset

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [emotion-js/emotion#2913]
**The problem**

There's no one-line way for consumers of the ESLint plugin to enable all the rules listed in https://emotion.sh/docs/@emotion/eslint-plugin#supported-rules.

**Proposed solution**

A config consumers can extend from that enables all those nice rules:

```js
{
  "extends": ["plugin:@emotion/recommended"]
}
```

**Alternative solutions**

This is the way.

**Additional context**

Many other ESLint plugins include a config preset, including [@typescript-eslint/eslint-plugin](https://typescript-eslint.io/docs/linting/configs) and [eslint-plugin-react](https://github.com/jsx-eslint/eslint-plugin-react#configuration).

**Comment by Andarist** [comment]
Yeah, we could have such a thing. PRs are welcome 😉

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues for repos I no longer have context on. If anybody has a need for what this issue was asking about, I'd encourage them/you to file a new issue. Cheers!
