### ISSUE TITLE
Trying to use `macro` throws `default.a.div is not a function` error

### ISSUE THREAD

**Issue by Wassap124** [emotion-js/emotion#2927]
**Current behavior:**
Trying to use component selectors on CRA (with typescript)
instead of ejecting, I tried using the `macro` path.

importing emotion via
```ts
import styled from '@emotion/styled/macro';
```

and then using it like so:
```ts
const FlexedDiv = styled.div`
  display: flex;
  justify-content: space-evenly;
  visibility: hidden;
`;
```

Throws:
```
TypeError: _emotion_styled_macro__WEBPACK_IMPORTED_MODULE_14___default.a.div is not a function
```

I am also receiving some warning on my terminal which might help:
```
../node_modules/.pnpm/babel-plugin-macros@3.1.0/node_modules/babel-plugin-macros/dist/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

../node_modules/.pnpm/import-fresh@3.3.0/node_modules/import-fresh/index.js
Critical dependency: the request of a dependency is an expression
```
**To reproduce:**

Could not reproduce on a separate repo 😞 

**Expected behavior:**
For `emotion` to work normally, as if Im using the via "default" path

**Environment information:**
**Important Note**: I am using pnpm, which might affect things

-  "react": "16.14.0",
-  "@emotion/css": "^11.5.0"
-  "@emotion/react": "11.10.4",
-  "@emotion/styled": "11.3.0"
- "pnpm": "6.35.0"
- "typescript": "4.8.4",

**Comment by nicolasLuduena** [comment]
Did you find a workaround for this?

**Comment by usback** [comment]
i have same problem so did you fixed it????

**Comment by nicolasLuduena** [comment]
I haven't tried that hard really. For my usecase, I had to go with classNames
