### ISSUE TITLE
ReferenceError: defaultStyleFunctionMapping is not defined

### ISSUE THREAD

**Issue by altechzilla** [emotion-js/emotion#2930]
**Current behavior:**

When using emotion-js (i.e via MUI's library / Material UI) with Next.js 13 + Turbopack, the following error is thrown:

Here's a thread between a few devs having the same issue:
https://github.com/vercel/turbo/discussions/2312#discussioncomment-3966587

**To reproduce:**

Next.js 13 + MUI + Emotion + dev --turbo - error gets thrown on page load. Without the `app` directory in v13, just regular pages.

**Expected behavior:**

Shouldn't break.

**Environment information:**

```
{
	"name": "example",
	"version": "0.1.0",
	"private": true,
	"scripts": {
		"dev": "next dev",
		"build": "next build",
		"start": "next start",
		"lint": "next lint"
	},
	"dependencies": {
		"@emotion/react": "^11.10.5",
		"@emotion/styled": "^11.10.5",
		"@mui/material": "^5.10.11",
		"next": "13.0.0",
		"react": "18.2.0",
		"react-dom": "18.2.0"
	},
	"devDependencies": {
		"eslint": "8.26.0",
		"eslint-config-next": "13.0.0",
		"prettier": "^2.7.1",
		"typescript": "^4.8.4"
	}
}
```

**Comment by Andarist** [comment]
We do not have/use function named like this - it cant’t be a problem with Emotion

**Comment by mnajdova** [comment]
It's not related to emotion, it complains for a function on MUI's side. @Andarist feel free to close the issue on emotion's side.
