### ISSUE TITLE
Cannot import correctly under TypeScript Node 16 module resolution

### ISSUE THREAD

**Issue by Jack-Works** [emotion-js/emotion#2933]
This is not related to the runtime behavior of emotion.

![image](https://user-images.githubusercontent.com/5390719/200098008-718d20ea-2f4d-4848-8ef6-3c15e5ad1cdb.png)

Under TypeScript Node 16 module resolution (has `type: module` in the `package.json` and `moduleResolution: Node16` in `tsconfig.json`), emotion cannot be imported correctly.

```ts
import createEmotionCache, { type EmotionCache } from '@emotion/cache'
createEmotionCache()
// TS: createEmotionCache is not a function
createEmotionCache.default()
// OK, but a runtime error
```

TypeScript thinks `@emotion/cache` and `@emotion/react` is a CommonJS package and therefore provides the synthetic export for the CommonJS module.

**Comment by Andarist** [comment]
Hmm, this is related to the ESM madness and I'm not sure what's the best fix for this. Could you provide a runnable repro case? I'm especially interested in how you execute the final thing at runtime. It seems that you are using an execution environment that is not actually using the node semantics and thus `moduleResolution: Node16` might be an incorrect choice. It's hard to tell without inspecting the repro case though - the whole thing is just a maze without a clear exit >.<

**Comment by Jack-Works** [comment]
Oh, sorry I tried that again, when running in Node, it is `{ default: [Function: createCache] }`, so there is no problem with this.
