### ISSUE TITLE
Invisible Unicode Character 'FORM FEED (FF)' (U+000C) is always injected into image-set CSS rule

### ISSUE THREAD

**Issue by voronianski** [emotion-js/emotion#2943]
**Current behavior:**

After upgrading to React v18.2.0 and Emotion v11.10.5, Emotion components started to insert an invisible character inside CSS `image-set` and `-webkit-image-set` rules. It always appears in the first `url()` after first `&` character. 

Inserted character looks like some sort of invisible space and breaks CSS. Examples of broken CSS -

![image](https://user-images.githubusercontent.com/974035/202289205-6425a8db-12e6-440a-8142-15ad12310b50.png)

**To reproduce:**

Use this link - https://codesandbox.io/s/confident-water-tsbbj6?file=/src/App.js

1. Check WorkingExample in DevConsole and notice that `backround-image` CSS is correctly recognized by browser
![image](https://user-images.githubusercontent.com/974035/202288320-c81988da-0473-4734-b67c-238e3e94dc72.png)

2. Check BrokenExample in DevConsole and notice that `backround-image` CSS in invalid -

![image](https://user-images.githubusercontent.com/974035/202289795-4666388b-7d5b-4605-b66f-07246da25bc1.png)

You can copy-paste CSS from BrokenExample into some [CSS Validator](https://www.cssportal.com/css-validator/) to see this invisible char -

<img width="915" alt="image" src="https://user-images.githubusercontent.com/974035/202288939-23c75dc3-4bf6-4abd-9fc5-1051aa30a141.png">

**Expected behavior:**

`background-image` with `image-set` and `-webkit-image-set` rules work as expected.

**Environment information:**

- `react` version: 18.2.0
- `@emotion/react` version: 11.10.5
- `@emotion/styled` version: 11.10.5

**Comment by voronianski** [comment]
According to debugging the CSS string it looks like `0c` unicode char is injected -

## Unicode Character 'FORM FEED (FF)' (U+000C) https://www.fileformat.info/info/unicode/char/0c/index.htm

Found out by pasting CSS string into - https://www.soscisurvey.de/tools/view-chars.php
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/974035/202292770-1d4320df-d849-4e53-8c2d-e54341a172c4.png">

**Comment by Andarist** [comment]
This is the problem within the parser that we use. We are investigating this here: https://github.com/thysultan/stylis/pull/307

**Comment by voronianski** [comment]
@Andarist do you think there‘s a way to workaround it somehow, until it gets fixed?

**Comment by Andarist** [comment]
You could write a Stylis plugin that would replace `&\f` with `&` in declaration values and use it with `createCache`+`CacheProvider`
