### ISSUE TITLE
The styles property of compositions contains extra semicolons that break markup

### ISSUE THREAD

**Issue by Zamaletdinov** [emotion-js/emotion#2945]
**Current behavior:**
The `styles` property contains extra semicolons that break markup when it is used with composition

**To reproduce:**
1. Create several different styles
2. Create a composition of all of them
3. Inspect the `styles` property of the combination - it contains extra semicolons
4. Here is the [sandbox](https://codesandbox.io/s/emotion-issue-template-forked-brb8uk) - toggle lines of combination to the difference

**Expected behavior:**
Combined styles should not contain any extra semicolons

**Environment information:**
- `react` version: ^18.2.0 (18.0.0 sandbox)
- `@emotion/react` version: ^11.10.5 (11.9.0 sandbox)

**Comment by Andarist** [comment]
`.styles` property should not be accessed by users. It's only supposed to be handled by the Emotion itself - in the same vein, you should not try to use what we output with `<style/>` manually. 

It works just fine if you use Emotion APIs: https://codesandbox.io/s/emotion-issue-template-forked-1hs4jv

**Comment by Zamaletdinov** [comment]
@Andarist Ah, my bad, thank you for your response!
