### ISSUE TITLE
extractCritical not working under NPM 5 

### ISSUE THREAD

**Issue by srosset81** [emotion-js/emotion#295]
- `emotion` version: 7.2.0
- `emotion-server` version: 7.2.2
- `react` version:

Relevant code.

```javascript
        const Root = (
            <ThemeProvider theme={theme}>
                ... page components
            </ThemeProvider>
        );

        const { html, ids, css } = extractCritical(renderToString(Root));
```

Steps to reproduce:

When using NPM 4 (latest version 4.6.1), extractCritical works fine and returns the correct `ids` and `css`. However when I upgrade to NPM 5.2 or 5.3 (deleting the whole node_module folder and doing a new `npm install`), `ids` receives an empty array and `css` an empty value.
If I downgrade to NPM 4.6.1 (and do the whole reinstall of the packages), it works again.

Thanks for your help !

**Comment by tkh44** [comment]
What happens if you update emotion to 7.2.2?

**Comment by tizmagik** [comment]
Looks like this is still happening on emotion / emotion-server on 7.3.2 with node 6.9.2, npm 5.4.1

**Comment by rileylnapier** [comment]
im having this same problem.  its cause when doing lerna bootstrap --hoist.

should i not be hoisting my node_modules?

**Comment by tkh44** [comment]
In theory that should work @rileylnapier, but if it isn't then you could try just having a single emotion install at the highest level or try using instances in version 9 which is currently under the `next` release tag.

https://github.com/emotion-js/emotion/blob/master/docs/instances.md

```bash
npm install emotion@next
```

Be sure to update all of your emotion dependencies to the next release if you try this.

**Comment by rileylnapier** [comment]
i am also using lerna where one package imports the other and they both use emotion.  not sure if that matters.

im not sure about having dev-dependencies in top level of a lerna project.   do i add it to top level and each child who use it?

ill try emotion 9 too and see if that helps

**Comment by tkh44** [comment]
https://github.com/emotion-js/emotion/blob/master/CHANGELOG.md is going to be your best resource for tracking down the changes btw.

**Comment by rileylnapier** [comment]
looks like it parses the ids correctly, but emotion.inserted and emotion.registered are both empty when i hoist

![image](https://user-images.githubusercontent.com/7017640/34393232-e8847f52-eb05-11e7-96f9-80aee40b8ae7.png)

**Comment by mitchellhamilton** [comment]
@rileylnapier Could you try using [Yarn Workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/#integrating-with-lerna)?

**Comment by rileylnapier** [comment]
i can't get workspaces to work.  throws an error when trying to build...  also, reading through docs trying to debug lerna/workspaces.... i read that yarn workspaces are experimental.  id rather not be building on beta or experimental.

im currently trying `lerna bootstrap --hoist --nohoist=emotion*`

**Comment by mitchellhamilton** [comment]
Fixed in emotion 9
