### ISSUE TITLE
Theme is not applied to styled components props in Vitest

### ISSUE THREAD

**Issue by MrkacekVladimir** [emotion-js/emotion#2955]
**Current behavior:**

I am using latest React, Vitest, Vite, Emotion and during testing ThemeProvider does not populate theme prop in styled.div syntax. This happens only during testing.

**To reproduce:**

https://codesandbox.io/s/vitest-and-emotion-styled-o3i7jm

1. Run "npm run test-watch"
2. See in console output, that styled does not get valid theme prop.

![image](https://user-images.githubusercontent.com/20847184/206151029-9e6cf3e9-d33c-4682-aad8-756bd0bb2931.png)

3. If you run the application, styled gets populated with theme prop as it should

![image](https://user-images.githubusercontent.com/20847184/206151490-796c7d60-94fa-4370-9d18-8a1f0814daf1.png)

**Expected behavior:**

ThemeProvider should provide me correct theme prop when using styled in testing environment.

**Environment information:**

- `react` version: 18.2.0
- `@emotion/react` version: 11.10.5

**Comment by Andarist** [comment]
Please recheck if your `node_modules` don't contain more than one version of `@emotion/react` or if your test setup doesn't instantiate `@emotion/react` more than once.

**Comment by MrkacekVladimir** [comment]
None of that seems to be the case. If I switch to styled-components and do the exact same setup with typings definition, ThemeProvider, babel plugin... the styled API gets correct theme.

**Comment by MrkacekVladimir** [comment]
I got a more readable type error if that helps: 
![image](https://user-images.githubusercontent.com/20847184/206160548-08525225-1198-45a4-a05f-08b890df2d15.png)

**Comment by MrkacekVladimir** [comment]
I did some further testing and it seems like the issue in the babel plugin.
If I remove 
`      babel: {
        plugins: ['@emotion/babel-plugin'],
      },`

from vite.config.ts, theme is getting passed into styled API.

Is there a way you could confirm that this issue is on emotion side?

**Comment by MrkacekVladimir** [comment]
Thank you very much for the effort. Currently it is a blocker we cannot really remove since without the babel plugin we are not able to use component referencing in styled. Hope this gets resolved soon :)

**Comment by Andarist** [comment]
Since this isn't really our issue - I will close this one here. Let's wait on the Vite maintainers to handle my PR.

**Comment by santosh1997** [comment]
https://github.com/emotion-js/emotion/issues/2351#issuecomment-1501603963

Facing the similar issue after jest 29 upgrade.
Can you please help?
