### ISSUE TITLE
When/how/if to use @emotion/css-prettifier?

### ISSUE THREAD

**Issue by Slapbox** [emotion-js/emotion#2967]
**Description:**

What purpose does this package serve? Should end users be using it? If so, is it documented anywhere?

**Documentation links:**

There is no mention in the documentation and an empty README - so I assumed it's an internal package - but `yarn why @emotion/css-prettifier` returns nothing, so now I'm confused about this package.

**Comment by Andarist** [comment]
It's an internal package, you can check out how and where it's used here: https://github.com/emotion-js/emotion/search?q=prettifier
