### ISSUE TITLE
No styling for detached containers only in Webpack Production mode

### ISSUE THREAD

**Issue by JaroVDH** [emotion-js/emotion#2986]
This is a bit of an odd one. I created a repro as small as possible, but I'm not sure what's breaking.

**Current behavior:**
If the HTMLElement working as the Emotion container is not yet attached to the DOM, it will not include styling when rendering/attached.
But **only** when compiled with _Webpack production mode_.
It does not happen in development mode.

**To reproduce:**
https://github.com/JaroVDH/emotion-webpack-prod-repro
Repo with repro.
The index.js script creates 2 Emotion.css styled divs, one always works, one breaks in production mode.
With `webpack --mode production` the first div won't have its Emotion styling.
Both will work when run with `webpack --mode development`.

The included index.html is referencing a production build.

**Expected behavior:**
Emotion styling for detached nodes in production builds.

**Environment information:**
`Node build environment` v18+
`@emotion/css` v11.1.3 (latest at time of writing)
`webpack` v5.74.0 (latest at time of writing)

**Comment by Andarist** [comment]
You can disable the `speedy` mode using `<CacheProvider/>`: https://emotion.sh/docs/cache-provider

It is uncommon to use detached nodes and for that reason, we use the faster version of style injection in production mode.

**Comment by JaroVDH** [comment]
I'm not using the React version, so I set it as a `createEmotion` option directly and that did the trick.  👍 
I missed it in the docs because I wasn't looking at the SSR options.

Thanks for the quick response!
