### ISSUE TITLE
Is react-testing-library/shallow supported?

### ISSUE THREAD

**Issue by xinyifly** [emotion-js/emotion#3005]
**The problem**

- The snapshot keeps rendering `css="unknown styles"` .
- It renders correctly with styles under pure `react-test-renderer` .
- The current shallow solution seems only supports enzyme.

**Proposed solution**

Add a jest serializer for `react-testing-library/shallow` , similar to `enzyme-serializer` .

**Additional context**

[Shallow Renderer](https://reactjs.org/docs/shallow-renderer.html)

**Comment by Andarist** [comment]
This is the first time that this has been raised as an issue. I think that it's fair thing to say that the audience for this would be extremely small.

**Comment by xinyifly** [comment]
@Andarist Let's wait and collect thumbs after people searched this issue. It seems that enzyme isn't supporting React 17 and later. This might be more desirable in the future.
