### ISSUE TITLE
Composes with another styled component using `.classname` instead of `classname`

### ISSUE THREAD

**Issue by hemlok** [emotion-js/emotion#301]
- `emotion` version: 7.2.2 // 6.0.3
- `react` version: 15.6.1

Relevant code.

```javascript

const Text = styled.p`
  ...
`;

const StyledInput = styled.input`
  composes: ${Text};
  ...
  &:active {
    outline: none;
  }
  &:focus {
    outline: none;
  }
`;
```

When I compose `Text` which is a styled component, it injects a class with a `.` 
```class="& .css-8y95g10 css-StyledInput-4758b83 css-1vwlsfc"```

specifically: `& .css-8y95g10`

<img width="521" alt="screen shot 2017-09-11 at 2 14 55 pm" src="https://user-images.githubusercontent.com/9043345/30297143-9e47ffbc-96fb-11e7-9cfd-b41e0d258957.png">

As such the class `css-8y95g10` doesn't get applied because of the `.`, also unclear what the `&` is doing there.

(also the `&` isn't present on 6.0.3)

Is composing with styled components, rather than classes created with `css` supported? Or is this a bug.

**Comment by tkh44** [comment]
This is not supported.

As a side note, you do not need `composes` as of v7.

**Comment by hemlok** [comment]
Gotcha. Any plans on supporting that down the road? I imagine a good solution for my use case would be just to export `text` as the styles and `Text` as the component.

How is composes done on v7? looks like the docs still show `composes: ${}` ?

**Comment by tkh44** [comment]
Any expressions put into the style block will be expanded just like `composes`, but at that specific point in the source. With composes keyword, you are limited to composing only at the beginning of the style block.

**Comment by tkh44** [comment]
> I imagine a good solution for my use case would be just to export text as the styles and Text as the component.

That is exactly what I would do. Something like this maybe.

```javascript
const baseStyles = {
  text: css`
    color: aquamarine;
  `
}

const StyledInput = styled.input`
  composes: ${baseStyles.text};
  ...
  &:active {
    outline: none;
  }
  &:focus {
    outline: none;
  }
`;
```

**Comment by hemlok** [comment]
Awesome. Thanks for your help 🙏

**Comment by hemlok** [comment]
Emotion 8 actually solves this problem really well with `withComponent` Much more clear to colleagues what `Text. withComponent('input')` is.

Thanks 👌
