### ISSUE TITLE
`@emotion/weak-memoize` has disappeared from npm

### ISSUE THREAD

**Issue by vanhumbeecka** [emotion-js/emotion#3034]
As of today, I'm unable to `npm install @emotion/react` due to a transitive dependancy on `@emotion/weak-memoize`.
This library gets a 404 response from npm registry.

All our builds are failing at the moment. Not sure what's going on here.
Tried upgrading, but getting the same 404 on `@emotion/weak-memoize` everytime.

Went to the npm website directly. The `@emotion/weak-memoize` was still in their search index, but upon clicking it, received a 404 as well. https://www.npmjs.com/login?next=%2Fpackage%2F%40emotion%2Fweak-memoize

**Current behavior:**

**To reproduce:**

`npm install @emotion/weak-memoize`
or 
`npm install @emotion/react`

**Expected behavior:**

It installs.

**Environment information:**

- `react` version: `17.0.2`
- `@emotion/react` version: `11.10.5`

**Comment by vanhumbeecka** [comment]
Ok nevermind. This seemed to be a glitch at npm? It's back now.

**Comment by leokang94** [comment]
I'm experiencing the same issue. Looking at it a little bit, I think there's an npm issue.
https://status.npmjs.org/
