### ISSUE TITLE
@types/react@18.2.8 + jsxImportSource: @emotion/react = `Its return type 'ReactNode' is not a valid JSX element.`

### ISSUE THREAD

**Issue by karlhorky** [emotion-js/emotion#3049]
**Current behavior:**

Over the last months, there have been significant changes to the TypeScript `@types/react` package by @eps1lon in order to accommodate the different return types of components (one of the reasons being to avoid [the problems with async React components](https://github.com/vercel/next.js/issues/42292))

Using `"jsxImportSource": "@emotion/react"` along with the new `@types/react@18.2.8` package causes failures that look like this:

```
'Title' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.
    Type 'undefined' is not assignable to type 'Element | null'.
```

CodeSandbox: https://codesandbox.io/p/sandbox/emotion-issue-template-forked-vsng2b?file=%2Fsrc%2FApp.tsx

![Screenshot 2023-06-04 at 16 30 12](https://github.com/emotion-js/emotion/assets/1935696/b6a887bc-ed32-43a4-b930-c59bd7d99aed)

**To reproduce:**

1. Fork the sandbox reproduction: https://codesandbox.io/s/emotion-issue-template-y306ue
2. Upgrade all versions of all `dependencies` and `devDependencies`
3. TypeScript error appears

**Expected behavior:**

`"jsxImportSource": "@emotion/react"` and the `@types/react@18.2.8` package are compatible

**Environment information:**

- `react` version: 18.2.0
- `@emotion/react` version: 11.11.0

**Comment by karlhorky** [comment]
Opened a PR with a potential fix here:

- #3050

**Comment by naari3** [comment]
As a temporary workaround until #3048 is merged, I think adding this type definition will work fine.

```typescript
import { JSX } from '@emotion/react/jsx-runtime';

declare module '@emotion/react/jsx-runtime' {
  namespace JSX {
    type ElementType = React.JSX.ElementType;
  }
}
```

**Comment by rick-chou** [comment]
> Failed to compile /examples/material-next-ts mui/material-ui#37500

@naari3  I use this workaround, but I got another error 

```
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
```

**Comment by naari3** [comment]
@rick-chou Normally if you have `@types/react`, `JSX.IntrinsicElements` should be present, so perhaps you have a different problem than this issue is dealing with maybe?
Above all, I don't know what kind of environment you are in, so we can't be sure exactly what is going on.

**Comment by rick-chou** [comment]
> @rick-chou Normally if you have `@types/react`, `JSX.IntrinsicElements` should be present, so perhaps you have a different problem than this issue is dealing with maybe? Above all, I don't know what kind of environment you are in, so we can't be sure exactly what is going on.

thanks! I updated all the dependencies and used a workaround that solved the problem.

**Comment by rick-chou** [comment]
> > @rick-chou Normally if you have `@types/react`, `JSX.IntrinsicElements` should be present, so perhaps you have a different problem than this issue is dealing with maybe? Above all, I don't know what kind of environment you are in, so we can't be sure exactly what is going on.
> 
> thanks! I updated all the dependencies and used this workaround, and solved the problem.

Sorry, it's me again 😅. Everything was working fine in my development environment, but when I used tsc to package my project today, the problem came back.

![Screenshot 2023-06-07 at 11 36 04](https://github.com/emotion-js/emotion/assets/56244178/37c7ca8c-98f7-43bc-8aeb-a408ba5e0f51)

env
```
"@emotion/babel-plugin": "^11.11.0",
"@emotion/react": "^11.11.0",
"@types/react": "^18.2.8",
"react": "^18.2.0",
"typescript": "^5.1.3",
```

and ts config

```
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "jsxImportSource": "@emotion/react"
  }
}
```

**Comment by karlhorky** [comment]
Thanks for the PR #3048 , review and merge @naari3, @Andarist, @emmatown ! 🙌

Looking forward to trying this out in `@emotion/react@11.11.1` after #3051 gets merged!

**Comment by akd-io** [comment]
Works like a charm! 🎉
