### ISSUE TITLE
API changes styled.<element>``

### ISSUE THREAD

**Issue by TroutZen** [emotion-js/emotion#310]
- `emotion` version: 7.3.2
- `react` version: latest

Relevant code.

```javascript
console.log(styled('h1'));
console.log(styled.h1); --> undefined
```

Problem description:
Docs seem to suggest that styled.element`` API still exists, however, getting undefined using dot notation instead of passing in the element name as string on latest version. Curious if the API has changed and docs just need to be updated.

**Comment by mitchellhamilton** [comment]
`styled.tagname` is converted to `styled('tagname')` (it's not converted to exactly that but something like it) in the babel plugin so `styled.h1` is undefined but people can still use it as a tagged template literal or with the object syntax.

**Comment by TroutZen** [comment]
Ah i see, need to look into the babel plugin config then. Thanks for the explanation.

**Comment by tkh44** [comment]
Thanks for the issue 👍  I've updated the documentation to note that the babel plugin is required.
