### ISSUE TITLE
Getting weird css output

### ISSUE THREAD

**Issue by agarrharr** [emotion-js/emotion#312]
- `emotion` version: 7.3.2
- `react` version: 15.6.0

Relevant code.

```javascript
const backgroundColor = css`
  background-color: hotpink;
`;
```

What happened:

<img width="1062" alt="screen shot 2017-09-18 at 12 30 17 pm" src="https://user-images.githubusercontent.com/3266363/30559236-354b1f32-9c71-11e7-8a64-2a5209327175.png">

Reproduction:

I'm not sure how to reproduce this. It works fine in storybook, but in our app, we get this problem.

Problem description:

The css gets output in this weird format. Instead of getting:

```css
.css-kqugv4{background-color: hotpink;}
```

I get:

```css
.css-kqugv4{0:b;1:a;2:c;3:k;4:g;5:r;6:o;7:u;8:n;9:d;10:-;11:c;12:o;13:l;14:o;15:r;16::;17:px;18:h;19:o;20:t;21:p;22:i;23:n;24:k;25:;;}
```

If you look at the values of the above, it actually spells out `background-color:pxhotpink;`.

**Comment by tkh44** [comment]
The babel plugin for tagged template literals is running before emotion. If you post your `.babelrc` I can be more specific.

**Comment by agarrharr** [comment]
I just copied the `.babelrc` from [the emotion website](https://github.com/emotion-js/emotion/blob/master/example/.babelrc)

```
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "loose": true,
        "targets": {
          "uglify": true
        }
      }
    ],
    "stage-0",
    "react"
  ],
  "plugins": [
    ['emotion/babel'],
    "transform-class-properties"
  ]
}

```

**Comment by agarrharr** [comment]
I also tried `'emotion'` instead of `['emotion/babel']`.

**Comment by agarrharr** [comment]
Ok, we got this solved. We needed to include the `'emotion/babel'` in our webpack config.

**Comment by tkh44** [comment]
👍
