### ISSUE TITLE
How can be specific <Global> removed when component is unmount

### ISSUE THREAD

**Issue by JurajLigo** [emotion-js/emotion#3131]
**Description:**

I have <Global styles={firstForCSS} /> in my code and I would like to remove it when component is unmount. How can I handle it?

**Documentation links:**

For Global I find just this page
https://emotion.sh/docs/globals

**Comment by Andarist** [comment]
`<Global/>` is unmounted when the component in which you have rendered it is unmounted so this should work out of the box.

**Comment by JurajLigo** [comment]
even with this kind of css 
```
const headerCSS = css`
        body {
            --header-position: absolute;
        }
    `;
```

**Comment by JurajLigo** [comment]
I have 
```
const headerCSS = css`
        body {
            --header-position: absolute;
        }
    `;
```

and then in component 
`<Global styles={headerCSS} />`

and when component is unmounted there is still 
```
body {
            --header-position: absolute;
        }
```

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by JurajLigo** [comment]
sure, finally it's our problem we not correctly unmount component
