### ISSUE TITLE
Media query styles not applied in @8.0.2-0

### ISSUE THREAD

**Issue by apostolos** [emotion-js/emotion#314]
- `emotion` version: 8.0.2-0
- `react` version: 16.0.0-rc.3 (in similar code on a personal project)
- confirmed in all browsers

![media-queries](https://user-images.githubusercontent.com/41679/30667271-83c6d9e0-9e46-11e7-8443-4fb994b2cf2d.png)

The avatar should be 96px in width and height.

**Comment by mitchellhamilton** [comment]
Closed via #321, released in 8.0.2-2
