### ISSUE TITLE
Empty Style tags

### ISSUE THREAD

**Issue by dilanbopanna** [emotion-js/emotion#3142]
Empty style tags are being added in the prod build. Not sure why this is happening

<img width="517" alt="image" src="https://github.com/emotion-js/emotion/assets/40492571/f94cf3fe-1bf4-45b2-8882-c1c85cc6111b">

**Environment information:**

- `react` version: 18.2.0
- `@emotion/react` version: 11.11.1

**Comment by Andarist** [comment]
They are not empty - they just don't have **text** context. You can verify that they are not empty by checking something like:
```ts
[...styleElement.sheet.cssRules].map(rule => rule.cssText).join('\n')
```
