### ISSUE TITLE
CacheProvider ignored in UMD build/Production build

### ISSUE THREAD

**Issue by beuluis** [emotion-js/emotion#3147]
**Cross reference**
https://github.com/mui/material-ui/issues/40494

**Current behavior:**

`@emotion/cache` does not use the provided `shadowContainer` to mount styles into.

**To reproduce:**

1. Clone repo https://github.com/beuluis/MUI-Shadow-DOM-CacheProvider-Broken-Theme
2. Build app using npm start it is important to actually build it otherwise vite runs in dev mode and all works fine

**Expected behavior:**

`@emotion/cache` should mount styles in the specified shadowContainer inside the shadow DOM context.

**Environment information:**

- `react` version: 18.2.0
- `@emotion/react` version: 11.11.3
- `@emotion/styled` version: 11.11.0
- `@emotion/cache` version 11.11.0

**UMD builds used for prod build***
- https://unpkg.com/react@18.2.0/umd/react.production.min.js
- https://unpkg.com/@emotion/react@11.11.3/dist/emotion-react.umd.min.js
- https://unpkg.com/@emotion/styled@11.11.0/dist/emotion-styled.umd.min.js

**Comment by beuluis** [comment]
I found a related issue: https://github.com/mui/material-ui/issues/29568

**Comment by oliviertassinari** [comment]
This issue isn't about Emotion, it can be closed.
