### ISSUE TITLE
CacheProvider does not work with @emotion/css

### ISSUE THREAD

**Issue by andy-root** [emotion-js/emotion#3168]
**Current behavior:**

Setting up a custom cache using `CacheProvider` and `createCache` does not take affect when creating class name using `@emotion/css` but it does work for the css prop and `@emotion/styled`.

**To reproduce:**

1. open https://codesandbox.io/p/sandbox/emotion-issue-template-forked-9vpzny
2. You may have to click Refresh button in the Preview panel if there is a missing module error
3. See the rendered page, classnames do not include the key defined in the cache for elements using `css` from `@emotion/css`

**Expected behavior:**

Expect all classnames defined using the emotion library to have a prefix value that matches the key defined in the custom cache, in my case the string is `andy`

**Environment information:**

- "@emotion/css": "11.9.0",
- "@emotion/react": "11.9.0",
- "@emotion/styled": "11.8.1",
- "react": "18.0.0",
- "react-dom": "18.0.0",
- "react-scripts": "4.0.3",
- "@emotion/cache": "11.11.0",
- "@types/react-dom": "18.2.21"

**Comment by Andarist** [comment]
`@emotion/css` is our "vanilla" package - it's decoupled from React. The same thing that I've explained [here](https://github.com/emotion-js/emotion/discussions/3167#discussioncomment-8703015) applies here. It's just that in Emotion 11 we renamed packages so the old `emotion` is now `@emotion/css` and old `@emotion/core` is now `@emotion/react`

**Comment by andy-root** [comment]
Thanks for the clarification, I saw your reply.

**Comment by andy-root** [comment]
I have the same problem described in my comment in https://github.com/emotion-js/emotion/discussions/3167 for Emotion 11 too. The component library, the next version has a peer dependency on `@emotion/css 11` where they use `css()` to create the classnames. Is there a way to create a custom cache is this scenario? I'm trying to prefix the classnames for multiple instances of emotion running in a federated UI.
