### ISSUE TITLE
using Emotion Cache adds delay to styles be applied on SSR

### ISSUE THREAD

**Issue by famdude** [emotion-js/emotion#3172]
**Current behavior:**
takes a few seconds to styles be applied, when we use Emotion Cache in Next js SSR `_app`.
![current](https://github.com/emotion-js/emotion/assets/53464236/a8b37668-4024-49b7-bff5-efb20bd7a7fe)

**To reproduce:**

1. create a next js app and use pages structure
2. use emotion to add styles to components
3. create `_app` file and add emotion cache to it
here's `_app.js` code sample:
```
import * as React from "react";
import Head from "next/head";
import { ThemeProvider } from "@mui/material/styles";
import rtlPlugin from "stylis-plugin-rtl";
import { CacheProvider } from "@emotion/react";
import createCache from "@emotion/cache";
import { prefixer } from "stylis";
import theme from "../src/theme";


// Create rtl cache
const cacheRtl = createCache({
  key: "muirtl",
  stylisPlugins: [prefixer, rtlPlugin],
});

function MyApp({ Component, pageProps }) {
return (
    <CacheProvider value={cacheRtl}>
      <ThemeProvider theme={theme}>
        <Head>
        // header tags here
        </Head>
        <Component {...pageProps} />
      </ThemeProvider>
    </CacheProvider>
  );
}

export default MyApp;
```

**Expected behavior:**

![expepted](https://github.com/emotion-js/emotion/assets/53464236/de8796af-7aa2-44c2-9f52-756feb7070f8)

**Environment information:**

- `react` version: "^18.2.0"
- `@emotion/react` version: "^11.10.5"
- `next` version: "^14.1.0"

**Comment by famdude** [comment]
2 weeks passed. any suggestion?

**Comment by emmatown** [comment]
The cache must be created inside a component (inside a `useMemo`) so it's created per-request
