### ISSUE TITLE
Remove defaultProps copy

### ISSUE THREAD

**Issue by oliviertassinari** [emotion-js/emotion#3184]
**Current behavior:**

https://github.com/emotion-js/emotion/blob/73f688103c5307c90d7544508b6d935243e4299e/packages/styled/src/base.js#L183

**Expected behavior:**

No copy.

**Context**

React 19 removed the support for `defaultProps` on function components, and warned against it since 18.3.0, https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops since it was deprecated 5 years ago: https://github.com/facebook/react/pull/16210.

I think that at one point, we will want to remove this line to save bundle size and avoid confusion like in https://github.com/mui/mui-x/issues/11531 or https://github.com/react-simple-code-editor/react-simple-code-editor/pull/125#issuecomment-2204531315.

**Environment information:**

- `react` version: 18.3.1
- `@emotion/react` version: 11.11.4

**Comment by Andarist** [comment]
We have to plan to do this in the next major version that will only be compatible with React 19 (at least that's my current line of thinking about this).

**Comment by oliviertassinari** [comment]
The problem might be more widespread, just found the same issue with https://github.com/react-simple-code-editor.

**Comment by Andarist** [comment]
Is the core of the problem that you are facing that users get a warning about this from React?

**Comment by oliviertassinari** [comment]
@Andarist Correct, it's not 100% clear from the warning that the issue is with Emotion. We see styled() and emotion in the stack trace but I guess people ignore this, and just assume that it's not emotion since they don't see the error in other places:

- The first instance: https://github.com/mui/mui-x/issues/11531#issuecomment-1900992813
- The second instance: https://github.com/react-simple-code-editor/react-simple-code-editor/pull/125#issuecomment-2204531315

**Comment by Andarist** [comment]
We can't quite remove this as it would be a breaking change. I think it would be fine to make this assignment conditional though and that should largely address this issue, right? The warning could still be produced but only if the wrapped function would actually have `.defaultProps` and at that point the problem would be with that component and not Emotion (the warning wouldn't quite hint at that but I doubt we can improve that)

**Comment by oliviertassinari** [comment]
> I think it would be fine to make this assignment conditional though and that should largely address this issue, right?

Oh yeah speaking of just having a assignment conditional, I have another fun one for you 😄: #3204.

**Comment by Andarist** [comment]
I tried a bunch of components - both function and class ones - and I can't seem to get the warning about this from React. What am I doing wrong? :thinking:

**Comment by oliviertassinari** [comment]
@Andarist I can only see the issue on the server side: https://codesandbox.io/p/devbox/winter-sound-kn5qy8?file=%2Fpages%2Findex.js%3A19%2C23

<img width="684" alt="SCR-20240710-bait" src="https://github.com/emotion-js/emotion/assets/3165635/499b10c9-7389-4afc-843a-d39f3a9a3e2a">

cc @aarongarciah in case you experienced this in another way.

**Comment by aarongarciah** [comment]
@oliviertassinari Same; I don't see the error on the client side. This is the same demo but using create-react-app: https://codesandbox.io/p/sandbox/zealous-brook-dcj8f9?file=/src/App.js:12,2

**Comment by Andarist** [comment]
@oliviertassinari this repro *is* using `.defaultProps` - so it's... good that you have this warning there. It might be slightly confusing that `Styled(Button)` gets printed in the warning when the real issue is with `Button` but I'm not sure what we can do about it. To support the currently supported React versions we have to "forward" those `.defaultProps` onto the wrapper component.

**Comment by oliviertassinari** [comment]
@Andarist There are no alternatives to `defaultProps` with class components. React didn't deprecate it.

**Comment by oliviertassinari** [comment]
Yeah, I'm closing, I think this issue should be enough for developers who face this problem. It will give us a good direction.
