### ISSUE TITLE
labelFormat with a space

### ISSUE THREAD

**Issue by thany** [emotion-js/emotion#3202]
**The problem**

When passing `labelFormat` in the babel plugin, it ignores a space. We need a space to stay in there, because of E2E testing, for which adding automatic labels would be a great solution, if component names could be their own classname.

So consider for example this:
```
autoLabel: 'always',
labelFormat: ' [filename]--[local]',
```
Note the space in there. I would expect/want the generated classnames to look like this:
```
css-12345678 ComponentName--StyledDiv
```
Note the space in there, so that these are two separate classnames. But instead, the space is ignore and the classnames are concatenated:
```
css-12345678-ComponentName--StyledDiv
```
Note the dash in there - I did not ask for a dash.

**Proposed solution**

Respect spaces in the `labelFormat`. Don't trim it or replace spaces with another character.

**Alternative solutions**

I would now probably have to go through every component and *manually* add a predictable classname. Which is a right shame, because this labelFormat trick is *so close* to doing the thing we need 😞

**Additional context**

I may help to know we're on Next.js, and we're using the SWC compiler supplied with it. It has [recently added support](https://nextjs.org/docs/architecture/nextjs-compiler#emotion) for this Babel plugin so I can't be sure how well up-to-date it is. I'm expecting it's fairly well updated on their end. Just so you know I can't like install an alternate babel plugin or something. I "have to" use the official one.

**Comment by Andarist** [comment]
Labels are meant to be just labels attached for improved DX. They don't mean to be used as standalone class names. This is working very much as intended. If you want class names then please use class names. 

Technically you could still target those labels with CSS selectors but we don't recommend this:
```ts
document.querySelectorAll('[class$="-ComponentName--StyledDiv"]')
```

**Comment by Andarist** [comment]
This feature request conflicts with what labels are meant to be. They are just decorative. We don't want people to rely on them. I understand that you might want to benefit from this auto-generation and you can do that today using selectors like the ones I mentioned above.

**Comment by thany** [comment]
I get it, so in that case you may reopen this issue, converting it to a feature request:

A way to autogenerate predictable/selectable names to every component.

**Comment by Andarist** [comment]
Consider it a declined feature request. It doesn't align with Emotion's philosophy.

**Comment by thany** [comment]
Fine. So how can I achieve predictable selectors? Again, without touching every component please? You have evaded answering that question previously - perhaps you don't know how to, that's fine too.

Also what actually is Emotion's philosophy? Where could I have found it?

**Comment by Andarist** [comment]
> So how can I achieve predictable selectors?

That's the point. You are not supposed to. We find relying on stable class names to be a huge refactoring hazard.

That said, I mentioned above how you can abuse `labelFormat` to achieve your stable selectors. You can query elements that have a class attribute ending with a particular string.

> Also what actually is Emotion's philosophy? Where could I have found it?

It's probably not that well-formed in the current docs. We care about **predictable** styles and composition. Ideally, each component should only define its own styles.
