### ISSUE TITLE
Emotion.sh domain expired

### ISSUE THREAD

**Issue by Lvdwardt** [emotion-js/emotion#3203]
https://emotion.sh
<img width="1440" alt="Screenshot 2024-06-28 at 11 20 39" src="https://github.com/emotion-js/emotion/assets/87395969/bbd96ed8-6043-4de6-a4af-fc15adb87629">

**Comment by piotrszczesniak** [comment]
is this new official domain: https://next--emotion.netlify.app/docs/introduction?

**Comment by brianzhou13** [comment]
help pls

**Comment by Andarist** [comment]
> is this new official domain: https://next--emotion.netlify.app/docs/introduction?

No 😉 we are working on resolving the issue

**Comment by Andarist** [comment]
The site is up again

**Comment by Alicehhhmm** [comment]
@Andarist [emotion.sh](emotion.sh) expired again.
