### ISSUE TITLE
Verbose snapshot tests

### ISSUE THREAD

**Issue by greggb** [emotion-js/emotion#325]
- `emotion` version: 8.0.2-4
- `react` version: 15.6.1

Relevant code.

`testSetup.js`
```javascript
import serializer from 'jest-glamor-react';
import { sheet } from 'emotion';

expect.addSnapshotSerializer(serializer(sheet));
```

`package.json`
```javascript
 "jest": {
        "collectCoverage": true,
        "moduleNameMapper": {
            "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/fileMock.js",
            "\\.(css|scss)$": "<rootDir>/styleMock.js"
        },
        "setupTestFrameworkScriptFile": "<rootDir>/testSetup.js"
    },
```
test
```javascript
it('renders with styles', () => {
    const component = renderer.create(<Test />);
    const tree = component.toJSON();
    expect(tree).toMatchSnapshot();
});
```
What you did:

Trying to see more expressive snapshot feedback in jest. I followed thangngoc89's info in #263.

What happened:

Seeing only class names in the snapshot test failure. Has anything changed regarding snapshot testing in version 8?

```
Received value does not match stored snapshot 1.

    - Snapshot
    + Received

      <section
    -   className="css-4zk7jp0 css-1ghsrq5"
    +   className="css-1l7rza10 css-16mnb64"
      />
```

**Comment by tkh44** [comment]
Nothing has changed. We are using the same setup for this repo. Do you have a repo we could look at to see the whole picture?

**Comment by greggb** [comment]
I'll see if I can get a reduced test case this evening

**Comment by greggb** [comment]
You're right, I created a fresh CRA and it's working fine. Just have to debug my app. Sorry about that!
