### ISSUE TITLE
Load order of @emotion/styled and @emotion/react matters

### ISSUE THREAD

**Issue by BreakBB** [emotion-js/emotion#3264]
**Current behavior:**

When using manual chunks in the rollup config, to reduce the individual chunk size, the order in which the chunks are build matters.

We add manual chunking to improve load times. Usually we simply do so by placing every dependency in it's own chunk (check details below).
The issue is broken down with the chunking settings below. When changing the order of both entries, everything works just fine.

Broken:
```ts
        manualChunks: {
          emotionStyled: ["@emotion/styled"],
          emotionReact: ["@emotion/react"],
        }
```

Works:
```ts
        manualChunks: {
          emotionReact: ["@emotion/react"],
          emotionStyled: ["@emotion/styled"],
        }
```

In Firefox the error message is:
> Uncaught TypeError: undefined has no properties

<img width="1307" alt="image" src="https://github.com/user-attachments/assets/d3ecaaf9-18a4-46b9-a176-858f196105a1">

The built chunks differ in their size, when switching the order:

`@emotion/styled` first:
<img width="533" alt="image" src="https://github.com/user-attachments/assets/15dcfaee-3afb-40e0-af84-5e5a4f2b39a7">

`@emotion/react` first:
<img width="532" alt="image" src="https://github.com/user-attachments/assets/a69b754c-9053-406f-9bd0-4d1fa4eb588a">

**To reproduce:**

1. Checkout https://github.com/BreakBB/mui-bundle-error (This is a fresh `vite` project with `@emotion/styled` and `@emotion/react` installed).
2. `npm ci`
3. `npm run build`
4. `npx service -s dist`
5. Open `localhost:3000` and check the console output to see the error

The `vite.config.ts` file was adjusted, to contain the manual chunking described above.

**Expected behavior:**

It should not matter in which order the chunks are loaded.

**Additional information:**

I noticed this behavior when updating `@mui/material` to v6.1.0, but the curl print seems to be @emotion (details are [in this mui issue](https://github.com/mui/material-ui/issues/43817)).

Instead of configuring "manual chunking" as above, usually it is preferred to do something like this:

```ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  build: {
    minify: false, // to be readable
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes("node_modules")) {
            return id.toString().split("node_modules/")[1].split("/")[0].toString();
          }
        },
      },
    },
  },
})
```

This splits all dependencies found in the `node_modules` directory based by name. Depending on the project this might cause problems though as the order _might_ change.

**Environment information:**

- `react` version: 18.3.1
- `@emotion/react` version: 11.13.3

**Comment by emmatown** [comment]
This looks to be an issue with Vite. Vite seems to be creating a circular dependency (which Emotion itself does not have) by placing React in the `@emotion/styled` chunk.
