### ISSUE TITLE
React 19, update 

### ISSUE THREAD

**Issue by camiloguz23** [emotion-js/emotion#3271]
**React 19 RC**

Currently, Emotion does not support React 19. Given that many projects use Next.js—whose stable version is 15 and relies on React 19—updating Emotion to support the latest version of React would be beneficial. This would allow the library to stay in sync with projects upgrading to React 19 and improve compatibility across frameworks

**Comment by jy95** [comment]
React 19 is out : https://react.dev/blog/2024/12/05/react-19

**Comment by emmatown** [comment]
Emotion already supports React 19, there are some enhancements that should make setup easier when server-rendering, that is tracked by #3283
