### ISSUE TITLE
Support selector#{&} notation

### ISSUE THREAD

**Issue by brikou** [emotion-js/emotion#331]
- `emotion` version: 8.0.2-5
- `react` version: latest

## Relevant code.

```jsx
  const breakingRed = css`
    color: red;
    h2#{&} {
      color: blue;
    }
  `;
```

## What happened:

![image](https://user-images.githubusercontent.com/383212/30783197-1334f24c-a13f-11e7-9ac1-d0bb1da2539b.png)

## Problem description:

`#{&}` notation should work out of the box, but id doesn't, sadly...

## Suggested solution:

This is a hack...

```jsx
  const workingRed = css`
    color: red;
    h2& {
      color: blue;
    }
  `;

```

but works

![image](https://user-images.githubusercontent.com/383212/30783200-1f979fc6-a13f-11e7-8e51-8ff9fb8448d5.png)

**Comment by tkh44** [comment]
I've never seen this syntax before. Could you describe where it comes from?

```javascript
const workingRed = css`
  color: red;
  h2& {
    color: blue;
  }
`;
```

Is not a hack. It works exactly as intended. Any occurrence of '&' is replaced with the generated class name.

**Comment by brikou** [comment]
Using `h2&` is not a regular way, correct way is `h2#{2}` you ca check on https://www.sassmeister.com/

```scss
# fine
.hello {
    h2#{&} {
        color: red;
    }
}
```

```scss
# not so fine
.hello {
    h2& {
        color: red;
    }
}
```

> Invalid CSS after "h2": expected "{", was "&"
> "&" may only be used at the beginning of a compound selector.

I guess you use postcss-scss, so maybe the problem comes from postcss, am I right?

**Comment by hamlim** [comment]
Unless I misunderstood the recent changes, if Emotion is using Stylis to parse/prefix/etc the css, then stylis considers `h2&` to be a valid way to write the selector.

**Comment by thysultan** [comment]
`#{&}` is an Interpolation syntax – [SASS_REFERENCE.html#Interpolation(http://sass-lang.com/documentation/file.SASS_REFERENCE.html#Interpolation_____). I don't think it's specific to the use of #{&}, so if it where to be supported you'd have to consider if supporting this would carry onto all that it entails, that is the spec that defines what you can interpolate in sass i.e math `#{0.7/0.8125}em`, variables `#{$font-size}` etc.

**Comment by tkh44** [comment]
Oh, ok. Thanks for the explanation @thysultan. It has been a while since I've used SASS.

I don't have any plan for supporting this as it would balloon the bundle size.

Thank you for taking the time to make an issue. Please don't hesitate to share your ideas.
