### ISSUE TITLE
extractCritical and html stream SSR

### ISSUE THREAD

**Issue by GuillaumeCisco** [emotion-js/emotion#341]
- `emotion` version: 7.2.2
- `react` version: 15.6.1

Relevant code.

```javascript
import {extractCritical} from 'emotion-server';
import ReactDOMStream from 'react-dom-stream/server';

const {html, ids, css} = extractCritical(ReactDOMStream.renderToString(app));
```

What you did:
Trying to make emotion critical css working with SSR and streamable html.

What happened:
Snake biting his tail.

Reproduction:

Problem description:

Hey there, I wanted to make my app use html stream by using react-dom-stream : https://github.com/aickin/react-dom-stream

But the emotion critical css rendering need to first get all the rendered html from ReactDOM...
Am I right?

Do you think if there is a way to achieve critical css in emotion with dom stream?

Suggested solution:

**Comment by probablyup** [comment]
Initial thought... is it possible to do a traversal of the unrendered JSX tree and be able to form critical CSS from that? Probably not the dynamic styles, but it should be possible to include all the static stuff right?

**Comment by tkh44** [comment]
This is almost a freebie PR. It could be based on https://github.com/threepointone/glamor-stream. :) I would just include it as another export called `extractCriticalStream`.
