### ISSUE TITLE
Proposal: optionally convert props to css (a la glamorous)

### ISSUE THREAD

**Issue by hph** [emotion-js/emotion#350]
*Note: Please forgive me for opening an issue to ask a question, but I didn't find anything related to this in any of the existing issues.*

Glamorous supports optionally mapping props to css, like this:

```javascript
import { Div } from 'glamorous';

const Foo = () => (
  <Div display="flex" flexDirection="column" backgroundColor="hotpink">
    ...
  </Div>
);
```

The same can be achieved with any custom components as follows (opting into the API):

```javascript
import glamorous from 'glamorous';

const Flex = glamorous('div', {
  cssPropsAreOverrides: true,
}, {
  display: 'flex', // Any default CSS for this component can go here.
});

// And as before:
const Foo = () => (
  <Flex flexDirection="column" backgroundColor="hotpink">
    ...
  <Flex>
);
```

*Note: the above is not be a good example of why you would want to use the css prop API, just how. Arguably you would have row and column components and just use the prop API to make minor tweaks when using it (spacing, etc).*

I really like this approach for a number of reasons (and I'm happy to expand on that), but I guess my question is whether this has been considered as a feature and whether this could be supported by Emotion. The above is currently possible with the `css` prop, but I personally find that a bit unreadable (since it's just a string).

PS. great work on this library!

**Comment by tkh44** [comment]
I do not want to add the lists required to make this work, but you can make something like this yourself. I recommend looking at `styled-system` 

https://github.com/jxnblk/styled-system

It comes down to this pattern.

```javascript
const display = ({ display }) => css`display: ${display}`;

const View = styled('div)`
  ${display};
`
```

Now you can create a loop to do this for you.

```javascript
const View = styled('div')`
  ${['display', 'flex', 'color'].map(propertyName => props => ({
    [propertyName]: props[propertyName]
  }))};
`
```

You can see it work on "Hello" in the screen shot
<img height="400px" src="https://user-images.githubusercontent.com/662750/30887323-2555966c-a2d8-11e7-8e79-88354fa1cdec.png"/>

**Comment by mitchellhamilton** [comment]
Another thing to note is that the css prop also accepts objects.
