### ISSUE TITLE
Error is thrown when component has dynamic props, but is rendered without styles

### ISSUE THREAD

**Issue by smashercosmo** [emotion-js/emotion#354]
- `emotion` version: 8.0.2-8
- `react` version: 16.0.0

Relevant code.

```javascript

// Text.js
import React from 'react'
import {bool, string} from 'prop-types'
import styled from 'react-emotion'

const bold = props => {
  if (props.bold) return {fontWeight: 'bold'}
  else return null
}

const Text = styled('span')`
  ${bold};
`

Text.propTypes = {
  bold: bool,
}

export default Text

// index.js
import React from 'react'
import ReactDOM from 'react-dom'

import Text from './components/Text/Text'

ReactDOM.render(
  <div>
    <Text>Hello</Text>
  </div>, document.getElementById('app')
)
```

What happened:
I got an error 
'Uncaught TypeError: Cannot read property 'raw' of null'

Error is thrown in this block
```javascript
if (strings !== undefined && strings.raw === undefined || strings === undefined) {
    stringMode = false;
    styles = handleInterpolation(strings, false);
}
```
because 'strings' variable is null and not undefined

Suggested solution:
'strings != undefined' should fix the problem

**Comment by smashercosmo** [comment]
Ah, ok, figured out that I probably shouldn't return null in 'bold' function

**Comment by smashercosmo** [comment]
Feel free to close, but I think it's convinient if both cases (null and undefined) are handled

**Comment by tkh44** [comment]
@smashercosmo I've fixed this bug in https://github.com/emotion-js/emotion/commit/03a1b04092bdd23ebc9ef05b252098c60fa06781
