### ISSUE TITLE
npm i emotion-theming fails

### ISSUE THREAD

**Issue by sebastiandeutsch** [emotion-js/emotion#356]
Problem description:

Emotion theming fails - since it's not found in the npm registry.

Suggested solution:

Looks like the commit was 20h ago. Maybe it's not published yet or correct.

**Comment by tkh44** [comment]
Released for version 8
https://github.com/emotion-js/emotion/blob/master/CHANGELOG.md#v802-10-2017-09-29

**Comment by evan-scott-zocdoc** [comment]
Might be because of the version numbering scheme @tkh44? https://www.npmjs.com/package/emotion-theming -> `8.0.2-10`

**Comment by tkh44** [comment]
Yes, you would need to do `npm i emotion-theming@next` until version 8 is released to latest tag.
