### ISSUE TITLE
[react-emotion] Not support svg props

### ISSUE THREAD

**Issue by b2whats** [emotion-js/emotion#357]
- `emotion` version: 7.3.2
- `react` version: 16

Relevant code.

```javascript
const Svg = styled('svg')`
...
`

const SvgBox = ({ viewBox, ...props }) => (
  <Svg viewBox={viewBox}>
    {children}
  </Svg>
)
```
Problem description:
Svg arguments do not fall within the white list of the available properties of the element

Suggested solution:
expand properties https://github.com/emotion-js/emotion/blob/master/packages/react-emotion/src/props.js

**Comment by markphilpot** [comment]
Also `xmlns`, `version` and others: https://www.w3.org/TR/SVG/struct.html#SVGElement
