### ISSUE TITLE
Condition with css not working.

### ISSUE THREAD

**Issue by nontachaiwebdev** [emotion-js/emotion#365]
- `emotion` version: 7.3.2
- `react` version: 15.5.4

Relevant code.

```javascript
export const Title1 = styled('h1')`
  letter-spacing: 1px;
  color: #000000;
  font-weight: 300;
  ${props => ( props.margin && `
    margin: ${props.margin};
  `)}
  ${props => ( props.padding && `
    padding: ${props.padding};
  `)}
`
```

What you did:
I try to set css if have props send to emotion component

What happened:
It not working.

**Comment by tkh44** [comment]
Try adding `css` to your style fragments.

```javascript
export const Title1 = styled('h1')`
  letter-spacing: 1px;
  color: #000000;
  font-weight: 300;
  ${props => ( props.margin && css`
    margin: ${props.margin};
  `)}
  ${props => ( props.padding && css`
    padding: ${props.padding};
  `)}
`
```

**Comment by nontachaiwebdev** [comment]
thankyou. It work only first condition.
```
${props => ( props.margin && css`
    margin: ${props.margin};
  `)}
  ${props => ( props.padding && css`
    padding: ${props.padding};
  `)}
```
with this code margin will work only.

if swap padding to first of condition. It will work only padding.

How do you think about this ?

**Comment by mitchellhamilton** [comment]
Adding a semicolon after the margin stuff should fix it.
```jsx
export const Title1 = styled('h1')`
  letter-spacing: 1px;
  color: #000000;
  font-weight: 300;
  ${props => ( props.margin && css`
    margin: ${props.margin};
  `)};
  ${props => ( props.padding && css`
    padding: ${props.padding};
  `)}
`
```

**Comment by cameron-martin** [comment]
I ran into this exact same issue. Is there any way of making the semi-colon not required in these situations, or at least throwing an error rather than silently failing?

**Comment by mitchellhamilton** [comment]
It will work without a semicolon in emotion 8

**Comment by brunolemos** [comment]
Based on the comments this should be closed
