### ISSUE TITLE
Composing Static Styles inside of Dynamic styles does not work. 

### ISSUE THREAD

**Issue by kristenmills** [emotion-js/emotion#366]
- `emotion` version: 8.0.2-12
- `react` version: 16.0.0

With `{ extractStatic: true }` on the following code does not work

```javascript
const link = css`
  display: inline-block;
  line-height: 0;
  margin-right: 2.4rem;
`;

const More = styled(Link)`
  ${link};
  color: ${props => props.color};
`;
```

In this case none of the css from `link` is applied. I think it is because `link` is treated as a static style even when a dynamic style composes it.  I noticed that the output of the css looks something like this (assuming `props.color` is `#ffffff`;
```css
.css-1lylu6r{ css-link-1r92hdh; color: #ffffff; }
```

Also if I replace link with 
```javascript
const link = css`
  display: ${() => 'inline-block'};
  line-height: 0;
  margin-right: 2.4rem;
`;
```

it works fine as the style is now dynamic.

**Comment by tkh44** [comment]
This is a limitation to extracting. You need to manually apply `link` to the className wherever you use `More`

```javascript
<More className={link}/>
```

Another option is 
```javascript
const More = styled((props) => <Link {...props} className={`${props.className} ${link}} />)`
  color: ${props => props.color};
`;
```

**Comment by kristenmills** [comment]
Got it. Might want to make that explicit in the docs somewhere I think.

**Comment by tkh44** [comment]
Would make for a great first PR 👍

**Comment by ipedro** [comment]
@tkh44 I had that happen to me as well, but only came across this issue after losing a couple hours, so I made a PR pointing this issue. #508
