### ISSUE TITLE
Migrate website to gatsby and redesign.

### ISSUE THREAD

**Issue by tkh44** [emotion-js/emotion#367]

**Comment by tgrecojs** [comment]
@tkh44 I could definitely lend a hand here. Any specific thoughts on how you want this to be done or am I free to begin migrating?

**Comment by stereobooster** [comment]
I suppose this will be changed soon. But in current version of website I'm getting following error

```
invariant.js:42 Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
    at invariant (invariant.js:42)
    at Object.addComponentAsRefTo (ReactOwner.js:66)
    at attachRef (ReactRef.js:21)
    at Object.ReactRef.attachRefs (ReactRef.js:40)
    at ReactCompositeComponentWrapper.attachRefs (ReactReconciler.js:21)
    at CallbackQueue.notifyAll (CallbackQueue.js:74)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:78)
    at ReactReconcileTransaction.closeAll (Transaction.js:207)
    at ReactReconcileTransaction.perform (Transaction.js:154)
    at batchedMountComponentIntoNode (ReactMount.js:124)
    
react-dom.development.js:9747 The above error occurred in the <Editor> component:
    in Editor (created by ReactPlayground)
    in div
    in Styled(div) (created by ReactPlayground)
    in ReactPlayground (created by App)
    in div (created by App)
    in div
    in Styled(div) (created by App)
    in ThemeProvider (created by App)
    in App
```

**Comment by mitchellhamilton** [comment]
I don't think it's because of component-playground, I believe it's because there's multiple versions of react since the old website has react@16.0.0 in it's package.json but react@16.2.0 is in the root package.json.

**Comment by stereobooster** [comment]
site/package.json

```
"react": "^15.5.4",
"react-dom": "^15.5.4",
```

/package.json

```
"react": "^16.0.0",
"react-dom": "^16.0.0",
```

Made them same. Error still exists. Am I looking into the wrong branch? I'm using master

**Comment by mitchellhamilton** [comment]
Ooops, I was thinking about the react versions for something else. The error is because component-playground used to have react and react-dom as dependencies, it's changed to `peerDependencies` but we haven't updated.

**Comment by stereobooster** [comment]
As of now I downgraded to v8 - it is enough for me. I need any website with emotion to do experiments.

**Comment by stereobooster** [comment]
https://github.com/stereobooster/react-snap/blob/master/doc/emotion-site-optimization.md

This is why I needed emotion website, in case you are curious.
