### ISSUE TITLE
Can't Resolve 'fs' error in babel-loader

### ISSUE THREAD

**Issue by ChrisW-B** [emotion-js/emotion#369]
- `emotion` version: 7.3.2
- `react` version: 16.0.0

What you did:
When trying to compile with Webpack/Babel (after deleting/reinstalling node_modules), I get the following error:

What happened:

```
ERROR in ./node_modules/babel-plugin-emotion/lib/index.js
Module not found: Error: Can't resolve 'fs' in ./node_modules/babel-plugin-emotion/lib'
 @ ./node_modules/babel-plugin-emotion/lib/index.js 129:10-23
 @ ./node_modules/emotion/babel.js
 @ multi babel-polyfill ./react/index
```

Suggested solution:
I feel like the problem is likely with my switch to `babel-preset-env` from `babel-preset-2015`, but I'm not 100% sure. For reference, my babel options are as follows
```javascript
options: {
  presets: [
    ["env", { "targets": { "browsers": ['> 1%'] }}],
      'react'
    ],
    plugins: [
      'emotion/babel',
      'transform-object-rest-spread',
      'transform-export-extensions',
      'transform-class-properties', 
      ['transform-react-remove-prop-types', { mode: 'remove', removeImport: true }]
    ]
  }
```

**Comment by mitchellhamilton** [comment]
Could you share what's in your entry file? (from the error, I think the path is `./react/index`)

**Comment by ChrisW-B** [comment]
Alright, so I'm going to try not to write stuff at 1 am anymore- turns out I was importing from  `emotion/babel` instead of `emotion/react`, so I'm going to close this
(posting in case anyone else does something like then when half awake)

Thanks for your help!
