### ISSUE TITLE
Identifier name is missing from the class name

### ISSUE THREAD

**Issue by smashercosmo** [emotion-js/emotion#370]
Just wanted to ask if this feature (https://github.com/emotion-js/emotion/pull/253) was removed at some point? And if yes what was the reason behind it? Because currently I see just 'css-hash'-like names in the resulting markup.

- `emotion` version: 8.0.2-12
- `react` version: 16.0.0

**Comment by mitchellhamilton** [comment]
It was removed because it was a side-effect of component selectors which were removed (#334) but we added [source maps](https://emotion.sh/#source-maps) which can be much more powerful.

**Comment by smashercosmo** [comment]
Yeah, source maps are awesome, but it's really hard to inspect markup in devtools, because you can 't vissually distinguish one tag from another.'

**Comment by mitchellhamilton** [comment]
Closed via #375 

[Use the `autoLabel` option in your config for `babel-plugin-emotion`](https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion#autolabel) and the identifier name will be on the class name.

**Comment by smashercosmo** [comment]
awesome!
