### ISSUE TITLE
Version 8 blog article

### ISSUE THREAD

**Issue by tkh44** [emotion-js/emotion#373]
Any help reviewing and editing would be appreciated. Please let me know what you think and if I should cover any topics.

Draft Link
https://medium.com/@tkh44/css-in-js-has-arrived-9f892346d0af

Thanks!

**Comment by probablyup** [comment]
Is `__PURE__` still a thing? I thought that was removed in favor of the `side-effects` package.json flag

**Comment by tkh44** [comment]
It looks like `__PURE__` is actually an [Uglify feature](https://github.com/webpack/webpack/issues/2899#issuecomment-313660642). I'll clear that up. Thanks @probablyup

**Comment by utopiaio** [comment]
There should be a mention of the other _breaking_ change of `nested class selectors`. My switch from emotion 6 to 7 caused a bit of a bump (no pun intended 😁)

---

Thank you very much for emotion, an absolute joy to work with

**Comment by smashercosmo** [comment]
Worth to mention this (very upsetting) side effect of removing "component as selector" - https://github.com/emotion-js/emotion/issues/370

**Comment by richardanaya** [comment]
I think component as a selector encourages to better css component isolation. BEM offers some great suggestions of proper ways to do sub elements.

My suggestion would be to also mention the new CDN packages and a link to Jsfiddle! :)

**Comment by richardanaya** [comment]
Here's my shot at a concise BEM example:

https://codesandbox.io/s/wk2vo6zx87

```javascript
import React from "react";
import { render } from "react-dom";
import { css } from "emotion";

const cssHotDog = css`
  &--hotdog {
    background-image: url('https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Hot_dog_with_mustard.png/1200px-Hot_dog_with_mustard.png');
    background-size: 50px;;
    width: 50px;
    height: 25px;
    display: inline-block;
    margin-bottom: -9px;
  }

  &--hotdog-button, &--not-hotdog-button {
    border: solid 1px black;
    padding: 5px;
    margin-left: 5px
  }

  &--hotdog-button {
    background: red;
    color: white;    
  }

  &--not-hotdog-button {
    background: yellow;
    color: black;
  }
`;
const cssHotDog__hotdog = cssHotDog + "--hotdog";
const cssHotDog__hotdog_button = cssHotDog+"--hotdog-button";
const cssHotDog__not_hotdog_button = cssHotDog + "--not-hotdog-button";

const App = () => (
  <div className={cssHotDog}>
    <div className={cssHotDog__hotdog}/>
    <button className={cssHotDog__hotdog_button}>Hotdog</button>
    <button className={cssHotDog__not_hotdog_button}>Not Hotdog</button>
  </div>
);

render(<App />, document.getElementById("root"));
```
