### ISSUE TITLE
Support BEM style css components

### ISSUE THREAD

**Issue by richardanaya** [emotion-js/emotion#376]
http://getbem.com/introduction/

Need a way to use the hash generated to replace an part of child selectors to allow better isolation.

css('
  .%-subelement {
      color: blue;
  }
')

generates

.css-888888 {
   .css-888888-subelement {
      color: blue;
   }
}

**Comment by tkh44** [comment]
This works in emotion 8. 

https://codesandbox.io/s/j4jqqko9r5

**Comment by richardanaya** [comment]
you are awesome! @tkh44
