### ISSUE TITLE
Add phenomic example

### ISSUE THREAD

**Issue by tkh44** [emotion-js/emotion#383]
We should add an example to the phenomic repo.

https://github.com/phenomic/phenomic/tree/master/examples

https://twitter.com/moox/status/915973669578518528

**Comment by tgrecojs** [comment]
@tkh44  I just spent some time getting a repo ready. here is the commit --> [react-app-styles-with-emotion](https://github.com/phenomic/phenomic/pull/1183/commits/bbfe1eaebbaecd2926991d388fdff64e13bb0174)

**Comment by MoOx** [comment]
Thank you!

**Comment by MoOx** [comment]
Actually this example does not work correctly, but it's due to the fact that emotion-server rely on the html to extract critical styles. Phenomic does gives html to the user directly. I will digg a little if I can change something into Phenomic core but that won't be easy for us... :(

**Comment by MoOx** [comment]
Ok I made a quick change so now it's working perfectly!

https://github.com/phenomic/phenomic/tree/master/examples/react-app-styles-with-emotion

**Comment by tkh44** [comment]
Thanks @MoOx
