### ISSUE TITLE
React-Emotion override given classname (instead of appending)

### ISSUE THREAD

**Issue by brikou** [emotion-js/emotion#385]
Here is a relevant code :

```jsx
import { A, btn, btnSecondary } from "./styles/bootstrap.js"

//...

<A
    className={`${btn} ${btnSecondary}`}
    href="#"
    role="button"
>
    View details »
</A>
```

The rendered "a" tag has only a single class (from styled.a) instead of 3 classes.

This is a bug to me, isn't it?

Once this bug is fixed, I'll be able to release a new version of css-in-js-generator with event more DCE :+1:

**Comment by tkh44** [comment]
Any styles that begin with `css-` are merged from the style cache so that you get reliable and deterministic composition results.

Each generated className is going to be mapped internally to the final styles that are generated.

```javascript
const registered = {
     'css-12345': 'color:blue;'
}
```

**Comment by brikou** [comment]
@tkh44 I'm not sure to understand, I'll fork react-emotion and try to achieve what I want, then I'll explain it and open a PR.

**Comment by tkh44** [comment]
From your example.

The styles for `btn` and `btnSecondary` are already in the `registered` cache. We take all the classNames on an element and look for any styles that are already in the `registered` cache and insert them into the style block last.

Let's pretend this is the styles in your code.

```javascript
const btn = css`color: blue;`; // css-1

const btnSecondary = css`color:darkorchid;` // css-2

const A = styled.a`
   color: 'green';
`
```

So our cache looks like this.
```javascript
const registered = {
     'css-1': 'color:blue;',
     'css-2': 'color:darkorchid;'
}
```
Now when we use our A component

```javascript
<A
    className={`${btn} ${btnSecondary}`}
    href="#"
    role="button"
>
    View details »
</A>
```

`A` would see that it has 2 classNames that start with `css-` so it just appends the styles onto `A`'s style block.

```javascript
const btn = css`color: blue;`; // css-1

const btnSecondary = css`color:darkorchid;` // css-2

const A = styled.a`
   color: green;
   color: blue;
   color: darkorchid;
`
```

See now its not a matter of which styles were inserted into the stylesheet last. You get exactly what you wanted.

I hope this helps save you some time. It seems to me that you are still coming at this from a traditional css point of view. For example, `btnSecondary` should just use compose `btn`. As as user why should I have to use both classes?


```javascript
const btn = css`color: blue;`;

const btnSecondary = css`
  ${btn};
  color:darkorchid;
`
```

Something to think about.

**Comment by brikou** [comment]
Thanks @tkh44 it is very clear to me now. The behaviour is still not what I intend, but you can close this issue, and I'll try to share a codesandbox with minimal code to emphasize my problem.

**Comment by weblancaster** [comment]
@brikou I believe you can achieve what you looking for using `labelFormat` https://emotion.sh/docs/babel-plugin-emotion#labelformat
