### ISSUE TITLE
Support for ShadowDom

### ISSUE THREAD

**Issue by richardanaya** [emotion-js/emotion#388]
I was thinking about this scenario today, right now we append to document the new style. What about the ability to append to a ShadowRoot element for CSS isolation using emotion. This is normally used for web components that want to ensure their styles are protected.

**Comment by richardanaya** [comment]
@tkh44  I was looking at your CSP issue, was wondering if instead of creating styles within a shadowdom root, there might be some easier way to transfer styles from the document.head down into the shadowdom root. Any thoughts on easiest way to do that?

**Comment by tkh44** [comment]
I honestly have no idea @richardanaya. I'm not as familiar with shadow dom and its surrounding APIs as I'd like to be. I'm hoping someone else could chime in here.

**Comment by pusulurm** [comment]
Hi, I hit this situation. 
I'm using react-select and it uses emotion library to build dynamic css and adds these styles to document>head section. While I am trying to use react-select inside a shadow-dom based component and can not see any styles applied to react-select.
Any thoughts on this?

**Comment by Andarist** [comment]
You should be able to create custom emotion instance with container option passed in (https://emotion.sh/docs/@emotion/cache#container) and give it to react-select so it could inject your styles to appropriate element.

**Comment by goldmont** [comment]
> Hi, I hit this situation. I'm using react-select and it uses emotion library to build dynamic css and adds these styles to document>head section. While I am trying to use react-select inside a shadow-dom based component and can not see any styles applied to react-select. Any thoughts on this?

Hi there,

Have you solved?

**Comment by yanglee2421** [comment]
I found a method from the [MUI documentation](https://mui.com/material-ui/customization/shadow-dom/).
~~~tsx
import React from "react";
import { createRoot } from "react-dom/client";
import { App } from "./App.tsx";
import createCache from "@emotion/cache";
import { CacheProvider } from "@emotion/react";

const shadowTarget = document.querySelector("#wrap")!;
const shadowContainer = shadowTarget.attachShadow({ mode: "open" });
const shadowRoot = document.createElement("div");
shadowContainer.append(shadowRoot);
const cache = createCache({
  key: "css",
  prepend: true,
  container: shadowContainer,
});

createRoot(shadowRoot).render(
  <React.StrictMode>
    <CacheProvider value={cache}>
      <App />
    </CacheProvider>
  </React.StrictMode>,
);

~~~

**Comment by whinc** [comment]
A plain css solution based on @emotion/css.

```js
import createEmotion from '@emotion/css/create-instance';

const shadowTarget = document.querySelector("#wrap")!;
const shadowContainer = shadowTarget.attachShadow({ mode: "open" });
const { css } = createEmotion({
  key: 'my-element',
  container: shadowContainer 
});

const className = css`color: red`;
shadowContainer.innerHTML = `<div class={${className}}>hello</div>`
```
