### ISSUE TITLE
Don`t work babel loaders with emotion babel loader

### ISSUE THREAD

**Issue by Muffassa** [emotion-js/emotion#389]
- `emotion` version: 8.0.4
- `react` version: 16.0.0
- `next` version: 3.2.2

Relevant code.

.babelrc
```javascript
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    [
      "emotion",
      { "inline": true },
      "inline-import-data-uri"
    ]
  ]
}
```

What you did:

I`m adding loaders for inline svg. Have tried https://github.com/kesne/babel-plugin-inline-react-svg and https://www.npmjs.com/package/babel-plugin-inline-import-data-uri.
What happened:

In two cases i have one error `Module parse failed: You may need an appropriate loader to handle this file type`. But if i will delete `emotion` loader from `.babelrc` loader for inline svg will work good.
 
```
 error  in ./components/LTLogo/cat.svg

Module parse failed: /Users/nikita/workspace/Work/livetyping-react/components/LTLogo/cat.svg Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <?xml version="1.0" encoding="UTF-8" standalone="no"?>
| <!-- taken from https://commons.wikimedia.org/wiki/File:Cat_silhouette.svg -->
| <!-- Created with Inkscape (http://www.inkscape.org/) -->

 @ ./components/LTLogo/lt-logo.js 11:11-31
 @ ./components/index.js
 @ ./pages?entry
 @ multi ./pages?entry
```

**Comment by tkh44** [comment]
You are missing the brackets around "emotion" and `{ "inline": true }`.  You can just delete the `{ "inline": true }` as it is no longer required and is the default.

Please check the install documentation for more information.

https://github.com/emotion-js/emotion/blob/master/docs/install.md
