### ISSUE TITLE
External source maps (for SSR and production use)

### ISSUE THREAD

**Issue by frenzzy** [emotion-js/emotion#395]
What do you think about ability to use external source maps (`.map` files)?

It will allow us to use source maps in production mode because it won't increase bundle size a lot. Just one small comment for each rule: `/*# sourceMappingURL=/css/{hash}.map*/`

**Comment by mitchellhamilton** [comment]
It's unlikely this will happen because [`insertRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule), which is how we insert rules so fast in production, doesn't support adding source maps.

**Comment by frenzzy** [comment]
[Just checked](http://plnkr.co/edit/3XThfDlDgw8fJoqoJoNp?p=preview), probably you are right, is it sad. But [`insertRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule) approach also have disadvantage in ability to modify styles in DevTools. How much it faster than manipulations with `textContent` in `<style>` tag, maybe the difference is negligible? Could it be an option to choose which approach to use?

But anyway using external source maps may decrease the size of server-side rendered html in development mode, which can lead to more accurate page speed test measurements (network throttling etc)

**Comment by tkh44** [comment]
The difference between styled-components and emotion in this visual.
https://twitter.com/tkh44/status/918566727603994626

**Comment by tkh44** [comment]
The real problem is not insertRule but only using one style tag. You can only have one source map per sheet.

**Comment by frenzzy** [comment]
It is ok to have one source map per sheet, isn't it? Source map format allows to map each rule to separate files etc. But I do not see the way to apply source maps if styles were added by `insertRule`.
