### ISSUE TITLE
Add TypeScript definitions

### ISSUE THREAD

**Issue by patrick91** [emotion-js/emotion#40]
I'll do this when I have some free time (probably right after #EuroPython, I have a talk to prepare :) ).

Should be pretty straightforward to port styled-components' definitions.

What are the main API differences with it?

**Comment by marvinhagemeister** [comment]
Just made a wip PR this morning. Would you be interested in collaborating?

**Comment by patrick91** [comment]
Yup :) you can have a look at this in the meanwhile https://github.com/styled-components/styled-components/blob/master/typings/styled-components.d.ts :)

**Comment by marvinhagemeister** [comment]
@patrick91 That's awesome! Thanks for the link 👍  I managed to get the `styled` function to typecheck, with autocomplete for tags. But I'm currently facing an issue with `React.createElement`:

```bash
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
```
My guess is that this was the reason you guys went with custom component declarations for `styled-components`?

**Comment by tkh44** [comment]
@marvinhagemeister This is going to be tricky I think.

the signature for `styled` is (I don't know typescript I'm just making this syntax up as I go)

```
styled(tag: string|$ReactComponent, cls: string, vars: <Mixed>, content: () => {})
```

I think typescript is seeing a tagged template literal and expecting it to have a signature like

```
styled(strings: <String>, ...vars: <Mixed>)
```

**Comment by hawkins** [comment]
Similarly, could we get flow definitions as well? While I'm a rookie with Flow and inexperienced with TypeScript, I would greatly appreciate the definitions in flow, so I'd be happy to try my hand at contributing that side of the equation

**Comment by thangngoc89** [comment]
@hawkins tag me in when you sent the PR. Installing flow to my new project and seeing a lot of red lines :D

**Comment by goodmind** [comment]
any progress here?

**Comment by renatorib** [comment]
Hey Guys, check it out: https://github.com/emotion-js/emotion/pull/398

**Comment by renatorib** [comment]
Hey @tkh44, I think you can close this issue
