### ISSUE TITLE
Disable Vendor Prefixing?

### ISSUE THREAD

**Issue by aputinski** [emotion-js/emotion#400]
- `emotion` version: 8.0.5

https://github.com/emotion-js/emotion/blob/master/packages/emotion/src/index.js#L9

Does the current API provide a way to disable vendor prefixing? I noticed that stylis can take a `prefix: false` option, but I can't find any way to set it.

**Comment by tkh44** [comment]
This is a good idea. I've been wanting this for myself but I'm waiting on https://github.com/thysultan/stylis.js/issues/63#issuecomment-335955199 so that it can be set dynamically.

**Comment by aputinski** [comment]
Thanks!

**Comment by aputinski** [comment]
Now that prefixing can be set dynamically, what's the best way to expose this from emotion?

**Comment by greggb** [comment]
I was going to open a PR for this tonight, but work go in the way. If no one else is working on it I can get to it this weekend.

**Comment by mitchellhamilton** [comment]
I just added a `prefix` option to instances that sets Stylis's prefix option

6138036dbc7e6df1f0e31175e24cff4ae548aeab

**Comment by epeli** [comment]
So so I have to manually create the instances with `create-emotion` and `create-emotion-styled` packages just to disable vendor prefixing?

I usually prefer disable them in development as it makes the style inspector needlessly noisy.

**Comment by epeli** [comment]
Actually creating own emotion instance is not that big deal if you are willing to add some webpack magic.

Just create your react-emotion instance to `./src/emotion.js` and export it as the default export and add webpack resolve alias to it:

```
    resolve: {
        alias: {
            "react-emotion": path.resolve(
                __dirname,
                "src/emotion.js",
            ),
        },
    },
```

**Comment by Twiggeh** [comment]
I tried doing the workaround but it didn't work :(

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.
