### ISSUE TITLE
Styled shorthands don't working

### ISSUE THREAD

**Issue by renatorib** [emotion-js/emotion#401]
*Before of all: It's my first time using emotion, and I'm trying to write some emotion code on codesandbox.io.*

**I started creating a basic component:**
```jsx
import React from 'react'
import { render } from 'react-dom'
import styled from 'react-emotion'

const H2 = styled.h2`
  color: red;
`

const App = () => (
  <div>
    <H2>Red title</H2>
  </div>
)

render(<App />, document.getElementById('root'))
``` 

**But it's bugging:** (say that styled.h2 is not a function)

![image](https://user-images.githubusercontent.com/3277185/31560734-dc459268-b02b-11e7-83f1-2dedd5ac40e5.png)

When I write as `styled('h2')` it works 

**Reproduction:**

https://codesandbox.io/s/l1l1v0v29

**Versions:**

![image](https://user-images.githubusercontent.com/3277185/31561015-ee9226ec-b02c-11e7-9c91-055d2a0e1dfe.png)

**Comment by greggb** [comment]
This will work as is if you change `styled.h2` to `styled('h2')`. The former style requires the babel plugin.

**Comment by renatorib** [comment]
I know that emotion have this API. 
The title says 'shorthand'. 

I think it's a issue cause it's not well documented. When you enter the documentation the first thing you see is an exemple using a shorthand. 

Maybe it's need a attention, I think.

**Comment by tkh44** [comment]
You are absolutely correct @renatorib. 

I made https://github.com/emotion-js/emotion/issues/404 so we don't forget

**Comment by renatorib** [comment]
I've edited the comment 'cause I saw the babel section in website soon after posted. Sorry for that.

But I still agree with the 404 for a more clearer approach in the documentation.
