### ISSUE TITLE
All examples in the documentation should use styled('div') style.

### ISSUE THREAD

**Issue by tkh44** [emotion-js/emotion#404]
This is a great chance for first-time contributors.

**Comment by renatorib** [comment]
Agreed.

I think at the beginning we can show an example with `styled('div')` and right below an example using `styled.div` with a clear and visible addendum saying that "you can use shorthands installing this babel plugin"

This may give a much clearer message;

**Comment by tkh44** [comment]
I'm going to close this as we've addressed it in a few PRs and I've added a section to the `styled.md` with that error so it is easily discoverable.
