### ISSUE TITLE
Broken Links 

### ISSUE THREAD

**Issue by trainorpj** [emotion-js/emotion#411]
**Problem description**:

Some of the links in the full [documentation page](https://github.com/emotion-js/emotion/tree/master/docs) are broken.  Specifically

* [Preact](https://github.com/emotion-js/emotion/tree/master/docs/preact.md)
* [`styled.withComponent`](https://github.com/emotion-js/emotion/tree/master/docs/styled-with-component.md)
* [Using javascript object for styles](https://github.com/emotion-js/emotion/tree/master/docs/objects.md)
* [`styled` with object styles](https://github.com/emotion-js/emotion/tree/master/docs/styled-with-object.md)
* [Styling Elements Via css Prop in JSX](https://github.com/emotion-js/emotion/tree/master/docs/css#CSS-Prop.md)

**Suggested solution**:

I'm happy to work on this.  I just used emotion for the first time in a project (big fan! 👩‍🎤), so I'm familiar with it.  I figured the best approach would be to make (small) pages for each one.

**Comment by greggb** [comment]
I folded those pages into other sections. I'm no longer seeing the links in your issue on that page. If you find a 404 please let me know!

**Comment by greggb** [comment]
Ah, I see it now - should be fixed in #412

**Comment by tkh44** [comment]
Thank you @trainorpj for bringing this to our attention. Thank you @greggb for the quick fix.
