### ISSUE TITLE
Missing declaration file for module emotion-theming

### ISSUE THREAD

**Issue by bannavaj** [emotion-js/emotion#422]
- `emotion` version: 8.0.8
- `react` version: 16.0.0

Relevant code.

```typescript
// Imports

const theme = {
  baseFontSize: "5rem"
};

const App: React.SFC<{}> = () => (
  <ThemeProvider theme={theme}>
    <div id="app">
      <Text>Test content here!</Text>
      <Text ellipsis={true}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur,
        reiciendis? Ipsa praesentium ea deserunt qui expedita pariatur atque!
        Laboriosam, magnam! Odit, praesentium! Vero, nihil cum cupiditate quo
        quis numquam ratione porro sed temporibus dolor deleniti ipsum!
        Adipisci, eaque. Omnis sapiente libero autem dicta excepturi facilis,
        eligendi saepe repudiandae asperiores amet.
      </Text>
      <Text className="test">Hello</Text>
    </div>
  </ThemeProvider>
);

export default App;
```

What you did:
Tried using emotion with typescript. 

What happened:
Everything works fine until I dropped in the emotion-theming package, which complained about missing type declarations.

Check the image below for further information.

![screen shot 2017-10-19 at 3 32 10 pm](https://user-images.githubusercontent.com/32856313/31797357-c2391b9a-b4e2-11e7-8714-c13702d75381.png)

**Comment by tkh44** [comment]
Fixed in https://github.com/emotion-js/emotion/pull/419.
