### ISSUE TITLE
innerRef is missing from react-emotion typings

### ISSUE THREAD

**Issue by tkh44** [emotion-js/emotion#424]
From twitter.

https://twitter.com/rossipedia/status/921138316677976064

I don't know much about TS so I need outside help on this one.

cc @cameron-martin @renatorib

**Comment by cameron-martin** [comment]
What's innerRef?

**Comment by RafalFilipek** [comment]
`innerRef` allows you to get reference to inner component.

```
const MyEmotionComponent   = styled('div')`color:red`;
let myRef;

<MyEmotionComponent  ref={(ref) => myRef = ref} /> // myRef - MyEmotionComponent 
<MyEmotionComponent  innerRef={(ref) => myRef = ref} /> //  myRef - div element
```

**Comment by cameron-martin** [comment]
I'm doing the TypeScript definitions for them now and I'll send a PR in a sec.

> While we're talking abut extra props for components, there is also css prop.

Definitions for the `css` prop were added here: https://github.com/emotion-js/emotion/pull/416
