### ISSUE TITLE
styled.div` throwing error

### ISSUE THREAD

**Issue by rr-kalbeck** [emotion-js/emotion#433]
when using the syntax

```
const pageStyles = styled.div`
h1 {
        font-style: italic;
    }
`;
```

i get the following error in the browser..

Uncaught TypeError: Cannot read property 'withConfig' of undefined

this syntax works..
```
const pageStyles = css`
    h1 {
        font-style: italic;
    }
`;
```

btw, i'm using typescript

**Comment by greggb** [comment]
What about 
```
const pageStyles = styled('div')`
h1 {
        font-style: italic;
    }
`;
```
Do you have the babel plugin installed?

**Comment by rr-kalbeck** [comment]
same error.. yep i have the babel plugin

```
plugins: [
                        [
                            "emotion",
                            {
                                "sourceMap": true
                            },
                        ],
               ],
```

**Comment by tkh44** [comment]
Can you post your entire babel config please.

**Comment by rr-kalbeck** [comment]
i found the problem, there was a conflict with styledComponentsTransformer from typescript-plugin-styled-components that i forgot to remove. sorry for the trouble
