### ISSUE TITLE
Babel 7 compatibility for babel-plugin-emotion

### ISSUE THREAD

**Issue by mcongy** [emotion-js/emotion#437]
Hello,

- `emotion` version: latest (8.0.9)
- `babel-plugin-emotion` version:  latest (8.0.9)
- `babel` version: 7.0.0-beta3 

I'm having an issue when trying to compile using babel 7.
![image](https://user-images.githubusercontent.com/20205489/32142622-47f5eece-bc9b-11e7-884c-c218d5756ff0.png)

Here's where the error is coming from:
![image](https://user-images.githubusercontent.com/20205489/32142594-a59a1af6-bc9a-11e7-9f85-1e8b75ebc9e9.png)

After console.logging I realized that `metadata` property on `state.file` is an empty object 

The problem doesn't come from any plugin incompatibility. It doesn't work even with the simplest .babelrc / .babelrc.js file 
```
{
  "plugins": ["emotion"]
}
```

Babel 7 is still in beta, but it has a lot of benefits (most notably babel-preset-env that can include only polyfills for features that are actually used (!) by your code).

Please, look into it. Thanks!

**Comment by tkh44** [comment]
Thank you for filing an issue for this. We should get this fixed before the Babel 7 release. Would you want to give this a try @mcongy? Here is an example where they polyfill for babel/babel#6343q

https://github.com/AvokaTech/babel-plugin-lodash/commit/af423980ac61c09e84fe6c1a19281567b3c69905

**Comment by mcongy** [comment]
@tkh44 Hello, I'm sorry but I'm completely new to developing a babel-plugin. That means, I'm not a good candidate for this.
