### ISSUE TITLE
Guidance on a replacement for component selectors

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [emotion-js/emotion#446]
I was pretty bummed to see component selectors removed in v8, as there are some specific use cases internally where they were extremely useful and a necessary escape hatch.

What is the recommended path forward? It doesn't seem like `react-emotion` tags the components with a static property that's targetable, so not sure what else to do other than some sort of data attribute tag scheme, but that won't be as performant.

**Comment by mitchellhamilton** [comment]
Closed via #474
