### ISSUE TITLE
[Question] any editor plugins to write CSS in js

### ISSUE THREAD

**Issue by jiyinyiyong** [emotion-js/emotion#447]
In my case it's VS Code. Writing plain CSS is less productive in such an editor.

**Comment by greggb** [comment]
I use a combination of [vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components) and [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) which works out pretty well.

**Comment by jiyinyiyong** [comment]
So it only highlights the properties. Any solution for autocompleting of properties?

I tried https://github.com/lXSPandora/vscode-styled-components-snippets but failed to make it work at current.

**Comment by philipbjorge** [comment]
@jiyinyiyong -- You want this -- https://github.com/Microsoft/typescript-styled-plugin

**Comment by jiyinyiyong** [comment]
Took me sometime to figure it out. VS Code uses `2.5.3` by default, but the plugin only works with `2.6.1` I installed in `node_modules/`. After that it looks great!

**Comment by lsnch** [comment]
> @jiyinyiyong -- You want this -- https://github.com/Microsoft/typescript-styled-plugin

So apparently `vscode-styled-components` is now all you need. What a time to be alive.
![Screen Shot 2019-04-21 at 23 14 32](https://user-images.githubusercontent.com/20382674/56475020-3f7e8a00-648b-11e9-9cc4-b1ece986f877.png)

**Comment by jiyinyiyong** [comment]
Found myself already installed it.. are they the same?

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/89697613-dd40d700-d8d1-11ea-880c-4ea4cccbb849.png)

so many versions of this all with the same logo, but different creators...
