### ISSUE TITLE
Selector name doesn't display correctly on Storybook

### ISSUE THREAD

**Issue by nttrung91** [emotion-js/emotion#449]
**Current verstion**

- Emotion v8
- React v16.0.0

**Question**
When adding Storybook and wire the story using the Emotion Styled Component, the React element display as `<Styled(component) />` instead of `<Component />` (see attached image). Is there for Storybook just displays the Selector name?

<img width="350" alt="screen shot 2017-11-08 at 9 33 17 pm" src="https://user-images.githubusercontent.com/4307525/32590084-476fbdb0-c4cd-11e7-874f-64dd54e10efe.png">

**Comment by kici8** [comment]
Same issue here! 

- React v16.0.0
- Styled-components v3.3.3
- Storybook  v3.4.10

**Comment by jitenderchand1** [comment]
@nttrung91 How did you fix it?
