### ISSUE TITLE
`css` does not override/add-last to `className`

### ISSUE THREAD

**Issue by kirkstrobeck** [emotion-js/emotion#450]
I expect [this](https://codesandbox.io/s/1yj28q3m1l) to be red

```js
const fooStyles = css({ background: 'blue' })

<div
  className={fooStyles}
  css={{ background: 'red' }}
/>
```

**Comment by tkh44** [comment]
Thanks for the report. Looking into it now.

**Comment by kirkstrobeck** [comment]
Word. It might be invalid, but from my consumer angle it felt like it should do that thing that way 🤷‍♂️

**Comment by bsotodo** [comment]
A while ago I also notice this and used the same pattern as @kirkstrobeck 

`<div className={cx(fooStyles, css({ background: 'red' }))} />`

I think this is fine as it is right now, but it took me a while to figure this all out... Maybe we should update the docs to show this particular property of the CSS prop and the cx pattern

**Comment by Andarist** [comment]
We definitely should explain this better after we agree that current behaviour is what we want to support (https://github.com/emotion-js/emotion/issues/753), but I believe it is correct.
