### ISSUE TITLE
Want to be able to create unique class names

### ISSUE THREAD

**Issue by kirkstrobeck** [emotion-js/emotion#454]
Would like a feature where I can do something like this ...

```js
const uniqueClass = foo();

const parentStyles = {
  '&:hover': {
    [uniqueClass]: {
      background: 'red',
    },
  },
}

<ChildComponent warpperClass={uniqueClass} />

// child

<div className={cx(localStyles, warpperClass)} />
```

**Comment by tkh44** [comment]
Try this.

```javascript   
const parentStyles = {
  '&:hover': {
    [`.${uniqueClass}`]: {
      background: 'red',
    },
  },
}
```

**Comment by kirkstrobeck** [comment]
Sorry if the issue was unclear. The feature request is

```js
const uniqueClass = foo();
```

**Comment by evan-scott-zocdoc** [comment]
@kirkstrobeck 

```js
import uniqueId from 'lodash/uniqueId';

const uniqueClass = () => uniqueId('css-');
```

**Comment by kirkstrobeck** [comment]
Sure, just wanted it to be a part of this ecosystem so I was using the same engine that already produces these class names. Also, there might be some fringe benefits that could surface in the future. ie. some sort of registry or optimization, etc.

**Comment by mitchellhamilton** [comment]
[I just released a babel macro to do this and make them deterministic so they won't be different on the client for server side rendering](https://github.com/mitchellhamilton/unique.macro)

```bash
yarn add --dev babel-macros unique.macro
```

`.babelrc`
```json
{
  "plugins": ["babel-macros"]
}
```

```jsx
import unique from 'unique.macro'

const uniqueClass = unique() // css-hash
// It's prefixed with css- by default so it's replaced with
// glamor-{index} in snapshots with jest-glamor-react


```
I'm gonna close this since unique.macro solves this.
