### ISSUE TITLE
injectGlobal inserts a style tag for each style rule

### ISSUE THREAD

**Issue by orrybaram** [emotion-js/emotion#462]
- `emotion` version: 8.0.10
- `react` version: 15.6.2

Relevant code.

```javascript
injectGlobal`
  html,body{
    font-family: 'Oxygen';
  }
  h1 {
    color: blue;
  }
  h2 {
    color: red;
  }
  h3 {
    color: yellow;
  }
`;
```

What you did:
Added a global stylesheet (normalize.css) using `injectGlobal`

What happened:
Initial loadtime slowed down to a crawl. 1000's of style tags were injected into the head.

Reproduction:
https://codesandbox.io/s/pk1qjqpw67

<img width="613" alt="screen shot 2017-11-13 at 4 13 00 pm" src="https://user-images.githubusercontent.com/723579/32749725-3183e796-c88e-11e7-85b8-8ac412430c55.png">

Problem description:
For each style rule a new style tag is appended to the head.

Suggested solution:
Use a similar approach used by styled-components where the css is minified and injected into one style tag.

**Comment by tkh44** [comment]
You are experiencing emotion in development mode, and yes it is slow.

You can turn speedy mode on manually if find development mode too slow.

```javascript
import { sheet } from 'emotion'
sheet.speedy(true)
```

**Comment by orrybaram** [comment]
Thanks for the quick response. Do you think it would make more sense to just import global stylesheets using something like `style-loader`? Or are there plans to improve this at all?

**Comment by tkh44** [comment]
My decision would be based on how many global styles we're talking about. There is no harm in using the style-loader when dealing with a reset or something like that.

**Comment by orrybaram** [comment]
Alright, thanks for the help! I think for now, we'll stick with style-loader for the big global stylesheets.
