### ISSUE TITLE
(emotion-theming) do i use withTheme or not? 

### ISSUE THREAD

**Issue by rileylnapier** [emotion-js/emotion#469]
reading this article:  it says we no longer need to use withTheme.
https://medium.com/@tkh44/emotion-8-9f892346d0af

![image](https://user-images.githubusercontent.com/7017640/33098955-fe198cda-cec3-11e7-9fa7-906689e257cf.png)

But clicking into the documentation of emotion-theming, it says to use it...
https://github.com/emotion-js/emotion/blob/master/packages/emotion-theming/README.md#api

sooo, do I use it or not?

**Comment by rileylnapier** [comment]
or is that that i need to wrap components with withTheme, just not wrap styled.div``??

**Comment by probablyup** [comment]
You don't need to use `withTheme()` on components created with `react-emotion` like:

```js
const Thing = styled.div`
  color: {p => p.theme.color};
`;
```

However if you want to consume theme properties in a normal React component, that's when you use the `withTheme()` HOC.

```jsx
class MyComponent extends React.Component {
  render() {
    return <div>{this.props.theme.text}</div>
  }
}

const ThemedMyComponent = withTheme(MyComponent);
```

**Comment by kevinSuttle** [comment]
The wording [in the docs](https://emotion.sh/docs/emotion-theming#usage) is a bit confusing still. 

<img width="735" alt="Image 2019-06-04 at 10 43 43 AM" src="https://user-images.githubusercontent.com/95672/58888635-b7a8b400-86b5-11e9-9d68-dd5ed426c4bc.png">

Also, there are no examples of function components here. Is there a reason for that?

**Comment by Andarist** [comment]
> Also, there are no examples of function components here. Is there a reason for that?

No, there is not - it's just the same with class component as it is with function ones.

**Comment by kevinSuttle** [comment]
Thanks, @Andarist. Reason I ask is I was using with Flow, and it didn't pick up the Props. Can open a separate issue if you'd like. 

<img width="1673" alt="Image 2019-06-04 at 2 53 57 PM" src="https://user-images.githubusercontent.com/95672/58905990-fdc33f00-86d8-11e9-8831-59b59c20bccf.png">

**Comment by Andarist** [comment]
Better to open a new issue then
