### ISSUE TITLE
Multiline declaration doesn't work (CSS grid layout)

### ISSUE THREAD

**Issue by jgoux** [emotion-js/emotion#470]
- `react-emotion` version: 8.0.10
- `react` version: 16.1.1

Relevant code.

```javascript
const View = styled.main`
  display: grid;
  grid:
    'AppBar' auto
    'Main' 1fr
    / 1fr;
`
```

What you did:

I declared a grid ⭐️ 

What happened:

Only the first line of the declaration is taken into account : 
![image](https://user-images.githubusercontent.com/1443499/33118251-877c4286-cf6b-11e7-8425-24ddd2f2d93e.png)

**Comment by asistapl** [comment]
This is related to stylis issue https://github.com/thysultan/stylis.js/issues/74
@thysultan is suggesting to disable auto semi-colon insertion mode until this is fixed.

**Comment by tkh44** [comment]
Thanks @asistapl.

**Comment by arlaurent** [comment]
Hey there, I'm still facing this issue in @emotion/core@10.0.35. 

i have tried the following, commas between lines, encasing the lines between single quotes, tried to use a {} to encapsulate them, tried [] to encapsulate them as well.

Can someone please clarify what the right way is to make this work?

Thanks!

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given (and they were not in this case).

**Comment by arlaurent** [comment]
Will do!
ᐧ
