### ISSUE TITLE
Styles of nested css selector missing after extracted in production

### ISSUE THREAD

**Issue by chenyong** [emotion-js/emotion#471]
- `emotion` version:
- `react` version:

```js
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-router": "^4.1.1",

    "babel-plugin-emotion": "^8.0.9",
    "css-loader": "^0.28.4",
    "emotion": "^8.0.9",
```

Relevant code.

```javascript
const styleCandidates = css`
	${layout.flex} border-bottom: 1px solid #aaa;
	padding: 20px;
`;
```

```js
			{
				test: /\.css$/,
				use: ExtractTextPlugin.extract({
					fallback: "style-loader",
					use: "css-loader"
				})
			},
			{
				test: /\.tsx?$/,
				exclude: /node_modules/,
				use: [
					{
						loader: "babel-loader",
						query: {
							presets: [],
							plugins: [["emotion", { extractStatic: true }]]
						}
					},
					{
						loader: "awesome-typescript-loader"
					}
				]
			},
```
```js
		new ExtractTextPlugin("[name].[chunkhash:8].css"),
```
What you did:

Run Webpack in release mode, 

What happened:

styles for `layout.flex` is lost, which should be:

```js
export const flex = css`
	flex: 1;
`;
```

Reproduction: nil

Problem description:

For some reasons the code is just eliminated, while it works good in Webpack development mode.

I tried to look into the DOM also, there is a `<style></style>` element, but I found no content inside.

Suggested solution: nil

**Comment by dongapplyboard** [comment]
Having the same problem, has this been solved yet?

**Comment by greggb** [comment]
This might not apply in the latest case, but I notice there is a missing semicolon after `${layout.flex}` I had the same issue until I fixed all those up.

**Comment by greggb** [comment]
This might not apply in the latest case, but I notice there is a missing semicolon after `${layout.flex}` I had the same issue until I fixed all those up.

**Comment by chenyong** [comment]
@greggb didn't know we need a semicolon there. I thought just inserting styles there is just ok...

@dongapplyboard I ended up removing ExtractTextPlugin from my code and using `<style>` elements.  Works fine to me. Just lose benefit of caching plain CSS files.

**Comment by mrdivyansh** [comment]
Having the same problem. @greggb did you get any solution rather than removing `ExtractTextPlugin` plugin?
