### ISSUE TITLE
Bug on documentation for Styled

### ISSUE THREAD

**Issue by lstrrs** [emotion-js/emotion#478]
- `emotion` version: 8.0.2
- `react` version: 16.0.0

Relevant code.

```javascript
import styled from 'react-emotion'
// simple element
const H1 = styled('h1')`
  color: blue;
  font-size: 48px;
  transform: scale(${props => props.scale});
`

function Greeting ({ name }) {
  // blue, 48px, and scaled 2x text
  return <H1 scale={2}>Hello {name}</H1>
}

// Component
const H2 = styled(H1)`
  font-size: ${fontSize * 2/3}px;
  color: red;
`

function Greeting ({ name }) {
  return <H2>Hello {name}</H2> // red, 32px, and scaled 2x text
}
```

What you did: Read and followed example in documentation site https://emotion.sh/

What happened: The H2 component is not scaled 2x

Suggested solution: The example needs to either remove the `and scaled 2x text` part of the comment or add the `scale={2}` prop to the example. In addition it might be helpful to rename the `H2` to something different. The reason is that as a new comer to emotion, one could get confused and expect the Greeting component to be an `h2` and not an `h1`. 

One additional suggestion is to edit the example to have a conditional on the `props.scale`

```javascript
const H1 = styled('h1')`
  color: blue;
  font-size: 48px;
  ${props => props.scale ? `
    transform : scale(${props.scale });
  ` : ''}
`
```

What do you think? I can make a pull request and edit the `docs/styled.md`

**Comment by greggb** [comment]
I agree this example is a little confusing (and a little wrong). Looks like the comment should say `red, 32px` and drop the scaled part entirely.

As for the `const H2 = styled(H1)`,  the intent was probably to show how you could create a pseudo `h2` with an `h1` tag, but maybe `const smallerHeading` would get the point across better.

Definitely PR this so the docs make sense for everyone.

**Comment by ipedro** [comment]
I took a stab at it @greggb on PR #508
