### ISSUE TITLE
sourceMap does not work with next.js

### ISSUE THREAD

**Issue by arsen** [emotion-js/emotion#487]
- `emotion` version: 8.0.12
- `react` version: 16.1.1
- `next.js` version: 4.2.0-canary.1

When using emotion with next.js sourcemaps are not working.
.babelrc
`{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    ["emotion", { "inline": true }]
  ]
}`

To reproduce you can use an example from next.js repo:
[https://github.com/zeit/next.js/tree/canary/examples/with-emotion](https://github.com/zeit/next.js/tree/canary/examples/with-emotion)
Just update the dependencies to the latest versions.

When inspecting elements it is always pointing to `index:1`.
![screen shot 2017-12-02 at 7 46 00 pm](https://user-images.githubusercontent.com/3446647/33522119-88789b7c-d799-11e7-8aa0-86e3868768aa.png)

**Comment by greggb** [comment]
Did you add the `sourceMap` flag? 
```
{ "presets": [ "next/babel" ], "plugins": [ ["emotion", { "inline": true, "sourceMap": true }] ] }
```

**Comment by arsen** [comment]
Hi @greggb ,
Yes, I have sourceMap flag.
Here is the demo repo:
[https://github.com/arsen/next-emotion](https://github.com/arsen/next-emotion)

**Comment by greggb** [comment]
Looking at the [source](https://github.com/emotion-js/emotion/blob/master/packages/emotion-server/src/index.js) - seems like `extractcritical `only retrieves the rule itself, and none of the source map info. For source maps you could toggle off hydrate for development. But maybe someone has a better idea.

**Comment by arsen** [comment]
Yeah, looks like renderPage that is being passed to getInitialProps for _document has all sourcemaps striped out.
