### ISSUE TITLE
<style> elements being injected every time `css` is used.

### ISSUE THREAD

**Issue by SMLMRKHLMS** [emotion-js/emotion#489]
- `emotion` version: 8.0.11
- `react` version: 16.20

What happened:
<img width="334" alt="screen shot 2017-12-06 at 11 05 29 am" src="https://user-images.githubusercontent.com/5240571/33671363-6c1e92c2-da75-11e7-87b1-8a470b350df1.png">

Problem description:
Is it intended to have many style elements injected every time using the `css` method. I seem to remember that previously the same `<style>` element was reused upon each injection.

**Comment by SMLMRKHLMS** [comment]
@evan-scott-zocdoc Currently, in development. I haven't checked production yet.

**Comment by probablyup** [comment]
Ah yeah that's expected! All the batching happens in production only.
