### ISSUE TITLE
media query variable in object styles

### ISSUE THREAD

**Issue by jessehart** [emotion-js/emotion#490]
doing some testing to see if migrating from glamor to emotion would be feasible. one thing i'm missing is the media+pseudo helpers. what would be the emotion way of doing the following:

```
whatever: css(
   { height: '100%' },
    media(breakpoints.LG_MIN, {
        overflowX: 'hidden'
    })
)
```

**Comment by greggb** [comment]
Think you're looking for this: https://github.com/emotion-js/emotion/blob/master/docs/object-styles.md#media-queries

```
import { css } from 'emotion'

const className = css({
  color: 'darkorchid',
  '@media(min-width: 420px)': {
    color: 'orange'
  }
})
```
