### ISSUE TITLE
clearDynamicStyles

### ISSUE THREAD

**Issue by philholden** [emotion-js/emotion#491]
- `emotion` version: 8
- `react` version: 16

**Problem description:**

Using a color picker / color sliders to control values in a theme results in all dynamic CSS being appended to the style sheet for each pixel the slider is dragged. Moving one slider from left to right could mean unused styles account for 99% of CSS rules.

**Suggested solution:**

Provide a way to clear CSS generated by dynamic styles. Rules still in use will be regenerated on the next render the same way they are on the initial render. e.g.

```javascript
import {clearDynamicStyles} from 'react-emotion'

class ThemeState extends React.Component {
  state = { primaryColor: 'blue' };
  setTheme = theme => {
    clearDynamicStyles() // clear all dynamic styles
    this.setState(theme)  // render now generates only the styles needed
  };

  render() {
    const { setTheme, state: { theme } } = this;
    return (
      <ThemeProvider theme={theme}>
        <div style={{ '--primaryColor': theme.primaryColor }}>
          {this.props.children(setTheme)}
        </div>
      </ThemeProvider>
    );
  }
}
```
It is a housekeeping function it is the users responsibility to trigger a rerender of the app after calling this function. It is not meant for animation just for theme changes.

**Comment by mitchellhamilton** [comment]
[Extra CSS rules do not cause any performance problems.](https://github.com/emotion-js/emotion/issues/488#issuecomment-349565355) Is there a reason you think it's a problem?

If you really want to remove previously inserted styles, emotion exports a `flush` function which will remove all inserted styles but it's mainly for tests and it will cause problems with any styles that aren't defined in render.

**Comment by philholden** [comment]
Thanks `flush` may be what I need.

Re: reason I think it might be a problem:

e.g. an app that designers use to create websites from drag and drop components. They use sliders to configure colors and font sizes in a wysiwyg way. Changing the theme text color may cause styles for almost every component on the page to be appended (because each component uses isolated styles). I found with a single element just adjusting the hue with a slider yielded over 100 appended classes.

Bootstap is 8000 lines of CSS so in a more complete UI dragging one a slider might yield 80,000 lines of CSS. And that is just for hue for one theme variable. You can add saturation, lightness and 30 theme variables. These numbers multiply rather than add, so it can lead to an unbounded amount of CSS in memory. Also I currently have about 30 tabs open. So it feels something like a memory leak. I am not tiding up resources I am no long using and they can grow in an unbounded way with time spent in a web application. So I feel better if I tidy up after myself.

**Comment by probablyup** [comment]
Could you perhaps post your component? Curious to see if there are any optimizations we could suggest to how it's structured...

**Comment by tkh44** [comment]
@philholden there is no penalty for using a high number of rules with modern browsers. I would also note that the line count of CSS file is not important. It is the number of individual rules we could be concerned with. You should be fine, but you will run into performance problems in development mode where newly generated styles will create new style tags. I would debounce or throttle your slider updates as much as possible to alleviate some of the pressure.

**Comment by philholden** [comment]
Thanks Kye, sorry for delay. Here is an example (a bit contrived):

https://codesandbox.io/s/0x0jpwky9l

You can see it is pretty easy to get up to 1M of styles with just six components and two dynamic vars. I plan to have about 30 vars and 50 components.

I tried adding `flush()` on line 61. Anecdotally it gives a huge speed boost in dev not tried in prod yet (have a play see how much more responsive it feels).   

P.S. what is new in emotion 9?

**Comment by tkh44** [comment]
codesandbox can't run in production mode but you can force speedy mode like in this fork https://codesandbox.io/s/jjmrkxzp1y (see line 10). 

The best way to address this for now might be to adjust the stylesheet logic to avoid creating new dom elements when sourcemaps are not being passed in. I'm not sure when I'll be able to get to this though.

I would also debounce (https://www.npmjs.com/package/lodash.debounce) the color change handler to avoid such rapid changes.
