### ISSUE TITLE
autoLabel is not documented

### ISSUE THREAD

**Issue by chucksellick** [emotion-js/emotion#493]
I only learned of the `{ autoLabel: true }` setting after some time searching and discovered #452 where it is mentioned.

Would be great if this was described at least somewhere in the docs for the babel plugin.

**Comment by mitchellhamilton** [comment]
[It's documented in `babel-plugin-emotion`'s README](https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion#autolabel). It should probably be in the babel doc though, would you be able to submit a PR to add it there?

**Comment by chucksellick** [comment]
Ah, ok -- I didn't find that README. The emotion docs link to slightly different docs for the babel plugin. The only relevant docs you can easily get to by following links from emotion's main page are:

https://github.com/emotion-js/emotion/blob/master/docs/install.md
https://github.com/emotion-js/emotion/blob/master/docs/babel.md

Neither of these link to the other README as far as I can see. Also I found these pages a bit confusing, basically ended up going round in a circle going from one doc to the other. Would suggest:

- Move all installation instructions into install.md
- Remove babel.md
- Link to the babel-plugin-emotion README instead
- Maybe also add the recommended babel configuration to install.md for quickstart instruction without having to read a whole extra doc to find the setting

**Comment by tkh44** [comment]
@chucksellick That sounds like a great plan. It would a great help to the community and onboarding new devs.

**Comment by ChristopherBiscardi** [comment]
https://emotion.sh/docs/babel-plugin-emotion#autolabel

**Comment by ChristopherBiscardi** [comment]
actually early close. I think this can still be improved 😬
