### ISSUE TITLE
[docs] better example for babel plugin's hoist option

### ISSUE THREAD

**Issue by Andarist** [emotion-js/emotion#494]
https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion#hoist

From the given example I'm not sure from where the performance gains are coming from. I guess you mean that it can help if css/styled are used "dynamically" in functions, but in such case it seems that most commonly there would be some dynamic dependency used for object creation and thus making it impossible to hoist, like in this example:
```js
const getClass = props => css({ backgroundColor: '#fff', color: props.color })
```

**Comment by mitchellhamilton** [comment]
The main use case for hoist is with the css prop because defining static styles inline is a common pattern with it.
