### ISSUE TITLE
Support PostCSS custom syntax?

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#496]
Sorry I'm not following the template because it's not a bug report.

I was wondering if there's any way or if it is at least planned to support custom PostCSS syntaxes like Sugarss?

**Comment by tkh44** [comment]
It would have to be implemented via a stylis plugin as documented here https://github.com/emotion-js/emotion/blob/3544dd6c5234cbb62f8f26b72e6e80b89d4b9259/packages/create-emotion/README.md#stylisplugins-function--array
