### ISSUE TITLE
Draining streamed document <style>s when hydrating can cause UI flicker

### ISSUE THREAD

**Issue by staylor** [emotion-js/emotion#510]
- `emotion` version: 9.0.0-1
- `react` version: 16.2

Relevant code.

```javascript
  res.write(header);
  renderToNodeStream(app)
    .pipe(renderStylesToNodeStream())
    .pipe(
      through(
        function write(data) {
          this.queue(data);
        },
        function end() {
          this.queue(footer);
          this.queue(null);
        }
      )
    )
    .pipe(res);
```
**What you did:**

I am implementing SSR with Node streaming.

**What happened:**

When the client loads, I am seeing a flicker of styles - mainly from this rule:

Reproduction:

```css
export const StripedRow = styled.tr`
  &:nth-child(odd) {
    background: ${p => p.theme.colors.background};
  }
`;
```

**Problem description:**

When the styles load in the browser, the stripes flip - so the first row, which wasn't striped, becomes striped.

**Suggested solution:**

Is it necessary to drain the rules from the document before injecting them in the head? It is not clear what is being gained by flushing and re-injecting... maybe this just needs clarification in the docs why this is happening? If consistency is not possible on the client, it won't be possible for me to stream the response.

I am evaluating all of these pieces for the NYT, would prefer to stream response. Thank you for the awesome work so far.

**Comment by mitchellhamilton** [comment]
We have to move the styles tags otherwise React will remove them when hydrating. In this case, you should be able to fix it by changing `:nth-child` to `:nth-of-type` so that the style tags don't count.

I'm not sure there's a way to fix this in a generic way but in most cases `:nth-of-type` should work instead of `:nth-child`.
