### ISSUE TITLE
Upgrade to babel-plugin-macros

### ISSUE THREAD

**Issue by kentcdodds** [emotion-js/emotion#515]
The project was renamed from `babel-macros` to `babel-plugin-macros` to better support babel v7. No other breaking changes.

**Comment by tkh44** [comment]
Thanks for letting us know @kentcdodds

**Comment by kentcdodds** [comment]
Hopefully we'll finally get this into create-react-app! https://github.com/facebookincubator/create-react-app/pull/3675

**Comment by Haroenv** [comment]
I'll take a look now
