### ISSUE TITLE
Support for `withStyle` HOC

### ISSUE THREAD

**Issue by phyrog** [emotion-js/emotion#518]
I would like to see a `withStyle` HOC added to emotion. It's basically `styled` with switched arguments:

```javascript
const withStyle = (strings, ...values) => Component =>
  styled(Component)(strings, ...values);

withStyle`display: inline`(MyComponent)
```

What's the advantage of this? It can easily be combined with other HOCs using e.g. `compose` from Recompose:

```javascript
const MyComponent = compose(
  withStyle`display: inline`,
  withState(...),
  ...
)(MyComponentMarkup);
```

So, I guess my question is if you would be willing to accept a PR that adds this, or if you would rather concentrate on the one `styled` API and leave the HOC to the user.

**Comment by tkh44** [comment]
I don't think that the one-liner should be part of the repo until there is a popular use case for it. While neat, I don't think the vast majority of users of this library will use it.

You may also be able to use https://github.com/emotion-js/emotion/blob/master/docs/styled.md#change-the-rendered-tag-using-withcomponent in a similar manner.

**Comment by phyrog** [comment]
Fair enough :)

**Comment by ConAntonakos** [comment]
Sorry to bump an old issue, but I couldn't find anything else on it. I wonder if an implementation would be useful to use with [`recompose`](https://github.com/acdlite/recompose), or in general, composing/enhancing components leaving the component as the last argument in the list of currying.

Would you potentially accept a PR for something new like this?

**Comment by adamplabarge** [comment]
I agree this would be helpful.  I'm currently doing something like this but there is an issue.  The dynamic css className isn't being added to the consumed component unless I add className as a prop.

`import styled from '@emotion/styled'

const withStyle = (Component) => {
  return (
    styled(Component)((props) => {
      return`
        display: flex;
      `
    })
  )
}

export default withStyle`

Then in the component

`import React from 'react'
import PropTypes from 'prop-types'
import { compose } from 'ramda'
import withStyle from './Color.style.js'

const Color = ({ children, className }) => (
  <div className={className}>{children}</div>
)

Color.propTypes = {
  className: PropTypes.string,
  /** Theme Color */
  color: PropTypes.string,
  /** Color Code */
  children: PropTypes.node
}

export default compose(
  withStyle
)(Color)`

If I don't set className={className} then when the div is rendered it will not have the css- classname.

This is not necessary via the normal setup.
