### ISSUE TITLE
[Emotion Site] Link button styles not being applied

### ISSUE THREAD

**Issue by VictorCoding** [emotion-js/emotion#520]
For some reason the styles for the link buttons on the [emotion.sh](https://emotion.sh) home page are not being applied until after you do an arbitrary change in the editor.

![Alt Text](http://g.recordit.co/U9WCqKBMtZ.gif)

**Comment by tkh44** [comment]
Thanks for the report @VictorCoding. Thanks for the quick fix @mitchellhamilton
