### ISSUE TITLE
How to use with autoprefixer and set browserlist?

### ISSUE THREAD

**Issue by Tsury** [emotion-js/emotion#522]
I just started using Emotion 9. As my app runs exclusively on the latest version of Chrome, I wanted to use autoprefixer and set the browserlist as such. I couldn't figure out how to do it from searching around in the docs/issues.

**Comment by pleunv** [comment]
Emotion uses stylis which does not support browserslist and also does not seem to have plans to do so (https://github.com/thysultan/stylis.js/issues/76#issuecomment-346882924). Most of the prefixes are hardcoded in source, as you can see [here](https://github.com/thysultan/stylis.js/blob/master/stylis.js#L993).

However, if you really wanted to you could probably create an emotion instance and provide a custom prefixer function to just prefix the rules you want to support, see [this](https://emotion.sh/docs/create-emotion#prefix-boolean--function) and [this](https://github.com/thysultan/stylis.js#vendor-prefixing).

**Comment by Tsury** [comment]
Thanks, I set prefix to false.
