### ISSUE TITLE
cx has trailing whitespace

### ISSUE THREAD

**Issue by staylor** [emotion-js/emotion#523]
- `emotion` version: 9.0.0-1
- `react` version: 16.2

Relevant code.

```javascript

cx('guyFieri', {
  donkeySauce: true,
})
```

**What you did:**

I want to replace `classnames` with `cx`

**What happened:**

There is extra whitespace at the end of the class names.

**Reproduction:**

Just use cx

**Problem description:**

If you have hundreds of components, this creates unnecessary snapshot churn, and feels/smells like a code smell.

**Suggested solution:**

Trim whitespace from className or alter existing logic to not always push trailing whitespace on the `next` local var

**Comment by mitchellhamilton** [comment]
I can't seem to reproduce this. https://codesandbox.io/s/6xjk5p5n03

**Comment by staylor** [comment]
sorry about that, here is a codesandbox with examples of extra whitespace: https://codesandbox.io/s/oop6pz4w25
