### ISSUE TITLE
[Question] Any vscode plugins for auto-completing css props?

### ISSUE THREAD

**Issue by leejh3224** [emotion-js/emotion#528]
Hi, guys!

I was fascinated by this great library after using it for a while.

Anyway, I'm using emotion with css prop feature. 

It means I write react components in this way.

```
<div css={{ color: 'red' }}>red</div>
```

In this case, I don't see any intellisense support from vscode.

Is there any plugins to fix this?

**Comment by trainorpj** [comment]
Check out #447 :+1:
