### ISSUE TITLE
borderRadius is missing in style objects autocompletion

### ISSUE THREAD

**Issue by rachidaoudi** [emotion-js/emotion#537]
- `emotion` version: 8.0.12
- `react` version: 16.2.0

Relevant code.

```javascript
const ButtonCSS = styled.button(props => ({
    // CTRL + Space => no borderRadius suggestion 
}));
```

What you did:

Hit CTRL+Space

What happened:

Editor doesn't show borderRadius.

Suggested solution:

Add missing autocompletion

**Comment by tkh44** [comment]
Thank you for the issue but we have no control over autocompletion for an editor. Which editor are you using and maybe we can help point you in the right direction.

**Comment by rachidaoudi** [comment]
I'm using VS Code, it's not a bug of high priority tho I just wanted to point this out since most people rely on autocompletion in styled objects to avoid typos.
