### ISSUE TITLE
has anyone seen multiple css-HASH getting added using react-emotion?

### ISSUE THREAD

**Issue by rileylnapier** [emotion-js/emotion#541]
Hi, I just wanted to see if anyone has seen this problem before?

I noticed the other day that all my styled.div`` components seem to be getting 2 different css-HASH added as a classname.

"emotion": "^8.0.10"

![image](https://user-images.githubusercontent.com/7017640/35075654-3dfba466-fba9-11e7-8391-d1abdbeafb5a.png)

my component looks like:

![image](https://user-images.githubusercontent.com/7017640/35075696-71eb2e18-fba9-11e7-8b74-956b5153a308.png)

and defined as:

![image](https://user-images.githubusercontent.com/7017640/35075701-7a289aac-fba9-11e7-9f4d-e7f2d8d62eb6.png)

**Comment by mitchellhamilton** [comment]
The extra class is required for [component selectors](https://emotion.sh/docs/styled#targeting-another-emotion-component). This is because we don't know what the hash will be for the class with styles before the component is rendered since the styles could be based on props.
```jsx
const SomeComponent = styled.div`
  display: ${props => props.display};
`
const SomeOtherComponent = styled.main`
  background-color: hotpink;
  ${SomeComponent} {
    color: aqua;
  }
`

**Comment by mitchellhamilton** [comment]
It's expected for all components from styled, we need to have the class there so that if the component is used as a selector it has a class to target.

**Comment by Prathyusha553** [comment]
delete the nodemodules and install them again
