### ISSUE TITLE
Is there a way to omit cosmetic props?

### ISSUE THREAD

**Issue by TsuryKnox** [emotion-js/emotion#542]
I'm getting this warning:
`Warning: Received `true` for a non-boolean attribute `active`.`

Is there a built-in method of handling this and omitting cosmetic props, or should I take care of it, using something like `styled(omitProps(['active'])(Button))`?

**Comment by TrySound** [comment]
@TsuryKnox Which version of react do you use? And which props are you trying to pass? Maybe there's collision with dom attributes. In this case just use different name.

**Comment by TsuryKnox** [comment]
@TrySound I'm using React 16.2.0, and the name of the prop doesn't matter (tried to name it myProp123, same result). I do have to note that the element I'm wrapping with `styled` is [ant-design](https://github.com/ant-design/ant-design)'s Button component.

**Comment by TrySound** [comment]
@TsuryKnox Funny thing here is that react actually doesn't warn on booleans
https://codesandbox.io/s/2jw56wrxjy
Also you may do what you want like this
```js
styled(({ active, ...btn }) => <Button {...btn} />)`
  display: none;
`;
```

**Comment by TsuryKnox** [comment]
So it must be related to ant-design then.
Your solution works, though it messes up vs-code's styled-component extension syntax highlighting , but I'll live with it for now.

I wish there was some way to define a custom prefix for which props are automatically omitted, maybe as a parameter to the custom Emotion instance. I don't mind calling my prop emtnActve instead of active. Will even make things more readable.

Thanks for the help :]
