### ISSUE TITLE
[Question] Clearing / replacing globals?

### ISSUE THREAD

**Issue by Sharakai** [emotion-js/emotion#546]
- `emotion` version: 8.0.12
- `react-emotion` version: 8.0.12
- `emotion-theming` version: 8.0.12
- `babel-plugin-emotion` version: 8.012
- `react` version: 16.1.0

I'm using `injectGlobal` to style the background color of the `body` element, as such:
```javascript
const themeBody = (theme: Theme) => injectGlobal`
  body {
    background: ${theme.backgroundColor}
  }
`;
```
This works fine when called, changing the background colour as expected. If I then run the function with a 2nd theme, this then changes the background colour to the new background, as the new class has a higher specificity.
Going back to the 1st theme, however, results in nothing changing as the hash has previously been injected.

Is there a way to remove created globals (and thus from the `inserted` record) and/or override them repeatedly?

**Comment by tkh44** [comment]
This is a fun problem 😄 

We are not reinserting the style and creating a new rule because emotion knows that that exact rule has already been inserted.

```javascript
const themeBody = (theme: Theme) => injectGlobal`
  body {
    background: ${theme.backgroundColor}
  }
`;

themeBody({ backgroundColor: 'blue' }) // style inserted

themeBody({ backgroundColor: 'darkorchid' }) // style inserted

themeBody({ backgroundColor: 'blue' }) // nothing actually happens
```

This is the location of the bailout: https://github.com/emotion-js/emotion/blob/db97fe747e32f7eabb26e35b34258af4b7ff39a6/packages/create-emotion/src/index.js#L239

I think the simplest solution is to just create a component that takes the theme as a prop and then modify the inline style of the body tag directly on prop value changes.

```
//...
class BodyStyleModifier extends Component {
  componentDidUpdate(prevProps) {
    if (this.props.theme.backgroundColor !=== prevProps.theme.backgroundColor) {
      window.document.body.style.backgroundColor = this.props.theme.backgroundColor;
    }
  }
  
  render() {
     return null;
  }
}
```

Something like that.

**Comment by Sharakai** [comment]
Haha, glad you enjoyed it :p And thanks for the answer - This is certainly a simpler way to do it! I got stuck in the "anything to do with X must be done with library Y" mindset trap.

So with respect to theming, I presume it's safe to say that anything "below" the `ThemeProvider` in the React tree is okay to be styled with emotion (using `withTheme`, `styled...` or otherwise). Anything "above" will need to be styled as you've done with the `BodyStyleModifier` component. In the majority of cases, you'd put the `ThemeProvider` at the top, in the same space as React-Redux's `Provider`, etc, so this leaves very little you'd need to style above.

Many thanks again! Now to go and see how this works with React portals :)

**Comment by deadcoder0904** [comment]
@tkh44 @ghost I don't understand where to set the `componentDidMount` part so I made a [Minimal CodeSandbox](https://codesandbox.io/s/r76p996zym) to demonstrate `injectGlobal` & `background-color` part. Can you help me solve this issue?

**Comment by deadcoder0904** [comment]
I found the solution. Unfortunately, the `componentDidMount` part confused me & Idk why you said its required bcz it worked without it. Anyways thanks Kye & sorry for so many pings 🙌

I made a CodeSandBox which has the solution 👇
https://codesandbox.io/s/r76p996zym
