### ISSUE TITLE
Proposal: update browser check to look for `document`

### ISSUE THREAD

**Issue by alexlafroscia** [emotion-js/emotion#549]
I've been working on an Ember compatibility library for `emotion` ([`ember-emotion`](https://github.com/alexlafroscia/ember-emotion)) and have been trying to get server-side rendering working by integrating with [FastBoot](http://ember-fastboot.com/). However, I've been having a bit of trouble because of the way that `emotion` checks for the browser environment.

In FastBoot, `window` is defined but `document` is not. [`emotion` checks for `window`](https://github.com/emotion-js/emotion/blob/d3b55b893d190705359c507be5fadb241b8be453/packages/create-emotion/src/utils.js#L72) but then never uses it; it uses `document` in a number of places to inject the styled into the page.

Is there a reason for this? If not, would you be willing to accept a PR that checks for the presence of `document` instead, since that's the actual API that `emotion` depends on?

If you'd like to maintain the check against `window` for browser-environment detection, would you be willing to explore the ability to inject the reference to `document` so that it could be overwritten in a case like mine where `document` isn't available?

**Comment by alexlafroscia** [comment]
My progress toward supporting server-side rendering can be found in this PR:

https://github.com/alexlafroscia/ember-emotion/pull/16

Although I had to modify this line to check for `typeof window !== 'undefined' && typeof document !== 'undefined`

https://github.com/emotion-js/emotion/blob/03023bbfcc8df60e433a981b9a37d30db7765670/packages/emotion/src/sheet.js#L49

**Comment by alexlafroscia** [comment]
I've identifies two locations in the `9.0.0-2` code that I had to modify to make my SSR solution work with that version of `emotion`

https://github.com/emotion-js/emotion/blob/master/packages/create-emotion/src/index.js#L315

https://github.com/emotion-js/emotion/blob/master/packages/create-emotion/src/utils.js#L74

I think that the first one references should import the `isBrowser` util instead of defining that value a second time, and then the util should check `window` _and_ `document`.

I'm happy to make this PR myself, just want the go-ahead that you're interested in these changes and that there isn't some additional context around why checking only `window` is necessary.

**Comment by mitchellhamilton** [comment]
There's not reason we check for `window`, I think we don't need to check for `window` and `document`, we can just check for `document`.

**Comment by alexlafroscia** [comment]
Awesome! In that case, I’ll make a PR with my proposed changes.  Thanks @mitchellhamilton

**Comment by alexlafroscia** [comment]
@mitchellhamilton is there a timeline for when `emotion@9` will be released? Or the next beta, at least? I'm excited to release my next version of `ember-emotion` but need the change I landed here first.

**Comment by mitchellhamilton** [comment]
@alexlafroscia Just published `emotion@9.0.0-3`

**Comment by alexlafroscia** [comment]
woot! thank you!
