### ISSUE TITLE
css prop, css-style syntax highlighting?

### ISSUE THREAD

**Issue by alex-wilmer** [emotion-js/emotion#551]
If there such a thing? one of the great pleasures of writing css is the tooling. is there something that exists that can make, say atom kick into .css highlighting / autocompletion when writing a css prop?

**Comment by dstaley** [comment]
@alex-wilmer Check out [language-babel](https://atom.io/packages/language-babel) which has support for styled CSS template strings.

**Comment by alex-wilmer** [comment]
thanks, but I'm talking about the css prop, not the function

```
<div
   css={`
    color: blue;
   `}
/>
```

**Comment by alex-wilmer** [comment]
@mbavio doesn't look like it works for css prop

![image](https://user-images.githubusercontent.com/2880089/38061534-9789f56e-32bd-11e8-81c9-6bf0af6d711a.png)

**Comment by corysimmons** [comment]
Reopen please. I have this issue as well.

![image](https://user-images.githubusercontent.com/224636/48725559-89bcc000-ebfa-11e8-81dc-a57072ebba57.png)

This is using VSCode + the styled-components and language-babel extensions.
