### ISSUE TITLE
InnerRef for nested components

### ISSUE THREAD

**Issue by jfrolich** [emotion-js/emotion#553]
I can make this short as this is already addressed in styled components. I recently ran into this issue thinking the innerRef of nested components should peculate through the hierarchy until it reaches the dom-node. It doesn't. Might be a nice addition.

See below the pull request for styled-components.

https://github.com/styled-components/styled-components/pull/642

**Comment by mitchellhamilton** [comment]
Could you provide a reproduction? react-emotion's styled already does this https://codesandbox.io/s/7wxnk5jwv6

**Comment by tkh44** [comment]
If you can provide a reproduction I'll be happy to reopen the issue.

**Comment by jfrolich** [comment]
Ah I must have messed up while working on this! Really happy with Emotion and its blazing performance, great work 👍
