### ISSUE TITLE
Unable to set fallback styles (conflicting identical map keys)

### ISSUE THREAD

**Issue by stephenkoo** [emotion-js/emotion#555]
- `emotion` version: ^8.0.12
- `react` version: ^16.2.0

```javascript
const breakpoints = [576, 768, 992, 1200]

const mq = facepaint(
  breakpoints.map(
    bp => `@media (min-width: ${bp}px)`
  )
)

css(mq({
  'font-size': ['10px', '20px', '30px'],
 'font-size': ['10%', '20%', '30%'],
}))
```

What you did:
Attempt to set fallback styles using facepaint.

What happened:
![screen shot 2018-02-05 at 11 25 44 am](https://user-images.githubusercontent.com/18624246/35784098-592ba2e6-0a67-11e8-831a-9a298760651d.png)

Suggested solution:
Allow the use of template literals (`` css`font-size: ${array1}; font-size: ${array2}` ``) for more complex functionality, including using duplicate fallback styles.

**Comment by CanRau** [comment]
just stumbled upon this too as I'm trying to shift from glamor which supports [array values](https://github.com/threepointone/glamor/blob/667b480d31b3721a905021b26e1290ce92ca2879/docs/howto.md#fallback-values)

**Comment by mitchellhamilton** [comment]
@stephenkoo This is more of an issue for facepaint rather than emotion but anyway, you can solve this by passing an array to facepaint
```jsx
const breakpoints = [576, 768, 992, 1200];

const mq = facepaint(breakpoints.map(bp => `@media (min-width: ${bp}px)`));

css(
  mq([
    { fontSize: ["10px", "20px", "30px"] },
    { fontSize: ["10%", "20%", "30%"] }
  ])
);
```

@CanRau emotion now supports array fallback values like glamor
