### ISSUE TITLE
emotion-theming on Preact

### ISSUE THREAD

**Issue by jcperez-ch** [emotion-js/emotion#556]
- `emotion` version: `9.0.0`
- `emotion-theming` version: `9.0.0`
- `preact` version: `8.2.7`

What you did:

I installed `emotion-theming` to get the `ThemeProvider` in my `preact` project.

What happened:

Unfortunately the theme provider has a dependency to `react >-15` so I get the warning `warning "emotion-theming@9.0.0" has unmet peer dependency "react@>= 15".`

Reproduction:

I am probably missing something in the documentation to make it work, or there is something missing regarding this scenario.

Problem description:

`emotion-theming` has a peerDependency to `react@>=15`

Suggested solution:
I am not sure how is this issue supposed to be addressed, probably I just need a link to a referece I haven't read yet. But `emotion-theming` headline reads `A CSS-in-JS theming solution for React(-like) views.` but can't find references on how to set it up with `preact`.

A simple mention in the docs would be enough in case there is a need for extra steps, otherwise, not sure if we should consider any new implementation.  Thanks for addressing my problem

**Comment by taylor1791** [comment]
I ran into this too. It looks like `emotion-theming` does not support preact at all. This is based on my reading of [the source](https://github.com/emotion-js/emotion/blob/master/packages/emotion-theming/src/theme-provider.js#L5).
