### ISSUE TITLE
Should be able to exclude styles in jest-emotion serializer output

### ISSUE THREAD

**Issue by staylor** [emotion-js/emotion#557]
- `emotion` version: 9.0.0-2
- `react` version: 16.2

**Relevant code.**

```javascript
import * as emotion from 'emotion';
import { createSerializer } from './jest';

expect.addSnapshotSerializer(createSerializer(emotion));
```
**What you did:**

I forked the logic of `jest-emotion` to be able to output snapshots with stable classes, but without styles. https://github.com/staylor/reformation/blob/master/src/emotion/jest.js

**What happened:**

This allows snapshots to remain stable when logic changes OR when styles change. 

**Reproduction:**

I can simply do this in my tests with emotion components:

```
import 'emotion/serializer'
```

**Problem description:**

I fully expect styles and classNames to be constantly changing, so I would like stable classNames. Snapshots  are still expected to churn when I add more components and logic.

**Suggested solution:**

I think an `includeStyles: true` option should be added to `createSerializer`, that way, I can set it to `false` in my implementation, and get stable classnames and no styles in my snapshot output.

**Comment by mitchellhamilton** [comment]
I'd happily accept a PR that adds this as long as `includeStyles` defaults to true

**Comment by tujoworker** [comment]
@staylor Did du send in a PR on this?

**Comment by thompsongl** [comment]
Created #2709 to implement the request made here after coming to the same conclusion about wanting to exclude styles from snapshots
