### ISSUE TITLE
How to add a Stylis plugin?

### ISSUE THREAD

**Issue by FezVrasta** [emotion-js/emotion#559]
Sorry, not following the template because it's a documentation issue.

I can't find where is it described the process to add Stylis plugins to Emotion, any help would be appreciated.

Thanks.

**edit**:
I think I found `useStylisPlugin`, which is exported by Emotion, I haven't tried it yet but from my understanding with this function I'm gonna need to add the plugin to each place where I use Emotion, which is going to be quite hard to maintain. Is this the way to go?

**Comment by mitchellhamilton** [comment]
`useStylisPlugin` was for emotion 8, in emotion 9, you create an instance and pass a stylis plugin(s) as an option. https://emotion.sh/docs/create-emotion

**Comment by kyhy** [comment]
Are there more resources/examples available for `create-emotion`? I find the current documentation hard to understand.

**Comment by tkh44** [comment]
This example from the tests should help.

https://github.com/emotion-js/emotion/blob/master/packages/create-emotion/test/emotion-instance.js#L8-L23

**Comment by kyhy** [comment]
thank you!

**Comment by tkh44** [comment]
I'm going to close this. If any further help is needed please make a note.
