### ISSUE TITLE
Label format option in babel-plugin-emotion

### ISSUE THREAD

**Issue by sgal** [emotion-js/emotion#563]
- `emotion` version: 9.0.0
- `react` version: 15.6.1

**Feature description**
It would be nice to have the possibility to configure the resulting class names that are generated by emotion. Currently in `babel-plugin-emotion` there is an option `autoLabel` that does part of it. But I would like to have the option to format the class name and for example, add component name to it.

Before:
`<div class="css-fg76s-container"></div>`

After:
`<div class="css-fg76s-ComponentName-container"></div>`
or
`<div class="ComponentName-container-fg76s"></div>`

**Use case**
We recently migrated our whole project from CSS modules + Less to emotion. It's going nice so far, but one thing that makes debugging of styles not so nice is those auto-generated class names. With CSS modules we could tweak the resulting class name to include component name as part of it (through `css-loader` in webpack).

**Suggested solution**
I think adding new option `labelFormat` to `babel-plugin-emotion` would be sufficient. Ideally, that option should accept function that takes the path and label that is extracted from the style declaration and returns the new class name.

Alternatively, the option could take a template string similar to `localIdentName` from [webpack's css-loader](https://github.com/webpack-contrib/css-loader).
```
labelFormat: "my-class-[filename]-[hash:base64:5]-[local]"
```

I'm not sure exactly how the class names are generated now, but it would be nice to be able to customize them.

**Comment by tkh44** [comment]
This would be a great feature and I think your solution may work.

The code for the label transformation, if you are using the `css` function, is here

https://github.com/emotion-js/emotion/blob/master/packages/babel-plugin-emotion/src/index.js#L114-L116

You could create a utility fn that takes in `state.opts.labelFormat` with whatever other information you need and apply it to the label. Once you get the tests running locally you can isolate them to the babel plugin test and the results should be obvious. Once you figure out that location any other instances of `state.opts.autoLabel` in the code should just be copy and paste work.

Don't be afraid to put in a PR even if you get stuck. Someone will help you out 👍

**Comment by sgal** [comment]
@tkh44 Thanks for the info! I did a little digging in the codebase and figured out that hashes for class names are generated in 2 places - in `create-emotion` (for dynamic styles) and in `babel-plugin-emotion` (if extracting static styles). I guess that should not be changed, since babel plugin is optional. But that also makes `[hash:base64:5]` option in label format unnecessary cause there's no use for 2 hash strings.

I'll create PR with 2 possible vars in the label format - `[filename]` and `[local]`.

**Comment by mitchellhamilton** [comment]
Closed via #566
