### ISSUE TITLE
prop-types requirement should be optional for preact-emotion

### ISSUE THREAD

**Issue by yunyu** [emotion-js/emotion#569]
- `emotion` version: 9.0.0
- `preact` version: 8.2.7

Relevant code.

```javascript
import styled from 'preact-emotion';
```

What you did:

I set up preact-emotion in my project.

What happened:

![](https://i.imgur.com/W9rVmAZ.png)

Reproduction:

    npm i --save preact emotion preact-emotion babel-plugin-preact

Problem description:

I'm not sure what prop-types is used for, but preact doesn't have native support for it (it presumably requires preact-compat). An additional `npm i --save prop-types` is needed to make preact-emotion work.

Suggested solution:

Remove the prop-types requirement from create-emotion-styled when used from preact-emotion (which would reduce the bundle size), or make it a direct dependency of preact-emotion to save users from guessing.

**Comment by mitchellhamilton** [comment]
prop-types is listed as a `peerDependency` of create-emotion-styled so users already get a warning when they don't have it installed. We can't remove the prop-types requirement since it's needed for React and create-emotion-styled is used by react-emotion and preact-emotion
