### ISSUE TITLE
styled function doesn't pass theme down to component as a prop

### ISSUE THREAD

**Issue by DanTopping** [emotion-js/emotion#570]
- `emotion` version: 9.0.0
- `react` version: 16.2.0

Relevant code.

```javascript
   //out of class
   const Message = styled(Label)`
     display: block;
     margin: 0.5em 1em;
   `;

   //render
   <Message key={0} text={message} theme={messageTheme} />
```

What you did: Passed props to the `Styled(Label)` in my render function. Theme in my case is a string variable.

What happened: All props were passed down from the emotion component to the `Label` apart from `theme`.

Problem description: `theme` not passed down as a prop to `Component` when passed to emotion `styled(Component)`. 

Suggested solution:  Is this intentional or a bug? Could this be clearer on the docs if it is intentional, I have seen theme used in https://emotion.sh/docs/emotion-theming but I'm not using the "emotion-theming" module. Otherwise, please make it possible to pass theme as well as using it for its special "emotion-theming" use-case.

**Comment by JoshRosenstein** [comment]
Hey I was trying to debug one of my own issues, and this would have been potential cause to my issue, but i could not replicate it. See if this helps:
[![Edit Emotion Issue 570 Solution](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/14rxpwkjj7)

**Comment by DanTopping** [comment]
Sorry, I didn't explain very well. Here I have put the problem on an edited version of what you've sent.
https://codesandbox.io/embed/ql56zw0w26

**Comment by JoshRosenstein** [comment]
@DanTopping - Oh i see what youre saying, yeah theme and innerRef are blacklisted,  However this will work:
```
const StyledH1 = styled('h1')`
  color: ${({ theme }) => (theme === 'Greeting' ? 'blue' : 'black')};
`
const HelloReverse = ({
  className,
  name,
  theme,
  theme2,
  innerRef,
  innerRef2
}) => (
  <StyledH1 theme={theme} className={className}>
    Hello {name}! I have this Theme: {theme} Theme2: {theme2}, InnerRef:{
      innerRef
    }, InnerRef2:{innerRef2}
  </StyledH1>
)
```
[![Edit Emotion Issue 570 Solution](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1qr74mm6n4)

**Comment by DanTopping** [comment]
Thanks Josh! I'll close this now.
