### ISSUE TITLE
Wrong behavior of style's combining and tag's overriding

### ISSUE THREAD

**Issue by evilj0e** [emotion-js/emotion#571]
- `emotion` version: 9.0.1
- `react` version: 16.2.0

Relevant code.

```javascript
import styled from 'react-emotion';

export const Label = styled('span')`
    font-family: PT Mono, Ubuntu Mono, Consolas, monospace;
`;

export const Link = styled(Label)`
    cursor: pointer;
`.withComponent('a');
```

What you did:
Trying to add some new styles to styled component and override tag.

What happened:
Tag was overridden but in Link styles I got only `cursor: pointer`.

Reproduction:
https://codesandbox.io/s/6ymz74zkon

Problem description:
I expect that Link will have tag 'a' and combined styles font-family and cursor: pointer.

Suggested solution:

**Comment by sgal** [comment]
@evilj0e I found a test that proves that it's desired behaviour that `withComponent` should not carry styles from the flattened componets https://github.com/emotion-js/emotion/blob/master/packages/react-emotion/test/index.test.js#L1112

@mitchellhamilton Maybe it should be a bit more clear in the docs if this is intended?
