### ISSUE TITLE
Hash of keyframes is mismatch on the testing

### ISSUE THREAD

**Issue by orlov-vo** [emotion-js/emotion#572]
Tests is broken because the hash of keyframes in the snapshots is mismatch between CI server and local machine.

emotion: 9.0.0
emotion-theming: 9.0.0
react-emotion: 9.0.0
jest-emotion: 9.0.0

**Comment by sgal** [comment]
@orlov-vo Is local machine running Windows? Another question - do you use `babel-plugin-emotion`?

**Comment by f0rr0** [comment]
can confirm this. local machine running osx and I use `babel-plugin-emotion `

**Comment by sebinsua** [comment]
I ran into this a few months ago.

I've been doing this until it's fixed:

```js
const withoutAnimations = ({ test, print }) => ({
  test,
  print: (...args) =>
    print(...args).replace(
      /animation(?:\-([a-zA-Z0-9]+))(?:\-([a-zA-Z]+))/g,
      (_, hash, name) => ['animation', name].filter(p => !!p).join('-')
    )
});

expect.addSnapshotSerializer(withoutAnimations(createSerializer(emotion)));
```

**Comment by mitchellhamilton** [comment]
Could someone provide a reproduction? It's pretty hard to help without one.
