### ISSUE TITLE
Use of Array.from() prevents IE11 support

### ISSUE THREAD

**Issue by asistapl** [emotion-js/emotion#574]
- `emotion` version: 9.0.1
- `react` version: 16.2.0

Problem description:
My app stopped working in IE11 after updating emotion to v9 because it uses `Array.from()`.
After loading polyfill form `Array.from()` everything works great so it's the only thing that prevents IE11 support.

Suggested solution:
`Array.from()` could be replaced with something like:
`[].map.call(NodeList, callback)` or `[].forEach.call(NodeList, callback)`
I know it's ugly.

It's used only in two places
https://github.com/emotion-js/emotion/blob/4f392366b0e34c2495a356d073a35464dc13006a/packages/create-emotion/src/index.js#L334

https://github.com/emotion-js/emotion/blob/3544dd6c5234cbb62f8f26b72e6e80b89d4b9259/packages/emotion-server/test/util.js#L148

so I think it wouldn't be a problem to make that change.

I think I could make PR for this but I'm not sure if you want to keep IE11 support.

**Comment by tkh44** [comment]
Go ahead and make a PR for this @asistapl. This is simple enough to not worry about the semantics. Thank you for the issue and I would happily accept the PR.

**Comment by chucksellick** [comment]
When is this release coming? Blocked on this right now! Great job getting it fixed quickly though!

**Comment by tkh44** [comment]
This is up to @mitchellhamilton. If there aren't any blocks we should do a release in the next few days.

**Comment by mitchellhamilton** [comment]
@chucksellick Released in emotion@9.0.2

**Comment by chucksellick** [comment]
Fantastic, thanks! Everything else is working perfectly
