### ISSUE TITLE
Styles are ignored when extending a component using withComponent

### ISSUE THREAD

**Issue by jerelmiller** [emotion-js/emotion#587]
- `emotion` version: 9.0.2
- `react` version: 16.2.0

Relevant code.

```javascript
const FlexRow = styled.div`
  display: flex;
  width: 100%;
`

const Row = styled(FlexRow)`
  justify-content: center;
`

const Section = styled(Row.withComponent('section'))`
  &:nth-child(2n + 1) {
    background: #f5f4f9;
  }

  ${({ theme }) => css`
    padding: ${theme.spacer.sm} 0;
  `};
`
```

What you did:

This may be an extreme example, but this used to work with emotion v8. Essentially we want to be able to compose styled components together but be able to swap out the underlying DOM element being rendered (i.e. `.withComponent`).

What happened:

![screen shot 2018-03-04 at 10 12 11 am](https://user-images.githubusercontent.com/565661/36948761-8f6bbfc0-1f94-11e8-9307-b28b4cf9534e.png)

As you can see in the screenshot, the styles from `FlexRow` are completely missing. We just updated from emotion v8 to v9 and noticed these bugs introduced.

Reproduction:

The code above should be enough to show this off. Here is a codesandbox reproducing the issue.

https://codesandbox.io/s/3y485y9yo5

Any help or advice would be appreciated! If there is a better way to compose these types of components together, I'd love to hear it.

**Comment by sgal** [comment]
@jerelmiller I think this behaviour is already investigated here https://github.com/emotion-js/emotion/issues/571
