### ISSUE TITLE
Calculating values

### ISSUE THREAD

**Issue by fandy** [emotion-js/emotion#597]
It doesn't seem like Emotion.js allows you to do calculations inside `css` like so:

```
const unit = '4px'
css`
  font-size: ${unit} * 4;
`
```

Is there a helper somewhere that allows me to do something like this?

**Comment by Poltergeist** [comment]
You can do something like this:
```
const unit = '4px'
css`
  font-size: ${unit.replace(/\d+/g,(a)=>a*4)};
`
```

**Comment by fandy** [comment]
Hmm, that does seem like a lot for a simple and common thing like this. So there is no intuitive way to do calculations?

**Comment by whmountains** [comment]
I can think of two other options:

Option 1: append the unit after multiplication.
```js
const pxSize = 4
css`
  font-size: ${pxSize * 4}px;
`
```

`${}` means, "interpolate a javascript expression", so we're just doing the calculation in Javascript.  I renamed the variable "pxSize" to avoid confusion about the unit.  If you really want to keep that `px` suffix, you could write a small helper function to to evaluate expressions like that.

Option 2: do the calculation in CSS.
```js
const unit = '4px'
css`
  font-size: calc(${unit} * 4);
`
```

Emotion uses thysultan/stylus pre-processor under the hood.  I expect you could easily write a plugin that would enable this transformation.  Maybe someone has already written one such a plugin, but I've never heard of it.

**Comment by Amirjab21** [comment]
So has this not been added? I think it would be really helpful if it was
