### ISSUE TITLE
Using Pseudo selectors in object

### ISSUE THREAD

**Issue by luapaaron** [emotion-js/emotion#599]
- `emotion` version:  "^8.0.10"
- `react` version:  "^16.2.0"

Relevant code.

const RadioButton = styled('div')({
  display: 'inline-flex',
  justifyContent: 'center',
  alignItems: 'center',
  flex: '0 0 auto',
  width: 20,
  height: 20,
  borderRadius: '50%',

  '&::after': {
    display: 'block',
    content: ''
  }
});

![3](https://user-images.githubusercontent.com/9362561/37574192-23e89738-2b5a-11e8-90ce-9951e2833329.png)
```javascript

```

What you did:

I used &::after using object but the after pseudo does not add in the css. 
but when I tried to use it as string it is ok.

Here is the screenshot for object and string
**OBJECT**

![1](https://user-images.githubusercontent.com/9362561/37574025-addcdc3a-2b58-11e8-8371-38f7183d9d32.png)

**STRING**

![2](https://user-images.githubusercontent.com/9362561/37574125-88d9ebc0-2b59-11e8-8b6f-46332eb5d2ff.png)

Suggested solution:

added helper for after pseudo to retain object for the whole project.

**index.js**

import { after } from './helpers'
const RadioButton = styled('div')(
  {
    display: 'inline-flex',
    justifyContent: 'center',
    alignItems: 'center',
    flex: '0 0 auto',
    width: 20,
    height: 20,
    borderRadius: '50%'
  },
  after({
    display: 'block',
    width: 12,
    height: 12,
    borderRadius: '50%'
  })
);
![3](https://user-images.githubusercontent.com/9362561/37574192-23e89738-2b5a-11e8-90ce-9951e2833329.png)

**helpers.js**
![4](https://user-images.githubusercontent.com/9362561/37574211-50f192b6-2b5a-11e8-9ea1-451d225fd685.png)

**WHAT I OBSERVED**
Using this line of codes, i put content in the object, also in the string

![5](https://user-images.githubusercontent.com/9362561/37574259-a11dad56-2b5a-11e8-924d-84f6119a6e4d.png)

the output in CSS is this:

![6](https://user-images.githubusercontent.com/9362561/37574285-c0f2b5b8-2b5a-11e8-8b07-9fad1f0890cb.png)

There is a px on the content that came from the object

**Comment by tkh44** [comment]
`content: "''"` should work.
