### ISSUE TITLE
What's the best practice for handling generated css files from extractStatic?

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [emotion-js/emotion#601]
- `emotion` version: 9.0.2
- `react` version: 16.2.0
- `webpack` version: 4.1.1

When I use `extractStatic: true` I end up with multiple `<Javascript file name>.emotion.css` files in the source directory (which I want to keep clean).

I use webpack with the [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) plugin instead of extract-text-webpack-plugin [because of this webpack issue](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701).
mini-css-extract-plugin is able to compile all of the css files generated by emotion into a single css, but this doesn't get rid of them afterwards.

What's the best practice for handling these files? Should I be extracting them to a temporary folder and deleting them with another build step after they've been compiled (perhaps with the [clean-webpack-plugin](https://github.com/johnagan/clean-webpack-plugin))? Is there a plugin that already handles this in webpack?

**Comment by wardpeet** [comment]
`mini-css-extract-plugin` will become the defacto standard for webpack so it's a good idea to use it. I use `merge-files-webpack-plugin` for now. Cleanup I do with rimraf. I use the new added outputdir option and save it to a .tmp folder. Inside npm scripts I do

`NODE_ENV=production webpack --config build/webpack.config.js && rimraf .tmp/ `
