### ISSUE TITLE
Consider adding `cx` prop to Babel transform

### ISSUE THREAD

**Issue by jamesreggio** [emotion-js/emotion#607]
- `emotion` version: 9.1.0

Given that the output of `css()` and `cx()` are both destined for the `className` prop, how would you feel about having a `cx` prop transform akin to the `css` prop transform.

It would simplify this use case, which is common for me:

```javascript
const moduleSpecificStyles = css`
  font-size: 100px;
  color: red;
`;

// Before
<h1 className={cx('external-klass-1', moduleSpecificStyles)}>So emotional</h1>

// After
<h1 cx={['external-klass-1', moduleSpecificStyles]}>So emotional</h1>
```

I know it's a small win, but the `css` prop is similarly small.

(And if there's some way to use external CSS classnames within the `css` prop, this is unnecessary, but we should clarify the docs, because I'm not able to find it.)

**Comment by mitchellhamilton** [comment]
You can use the css prop and the className prop together.

```jsx
<h1 className="external-klass-1" css={`
  font-size: 100px;
  color: red;
`}>So emotional</h1>
```
