### ISSUE TITLE
`preact-emotion` TypeScript support

### ISSUE THREAD

**Issue by rand0me** [emotion-js/emotion#610]
- `emotion` version: `9.1.0`
- `preact` version: `8.2.7`

Relevant code.

```typescript
import styled from "preact-emotion";
```
I tried to use preact-emotion with TypeScript and got an error:

```
Could not find a declaration file for module 'preact-emotion'.
```
Then I realized, that `preact-emotion` haven't `typings` property in `package.json` and file with typings itself. It is strange, because `react-emotion` seems to have proper typings.

**Feel free to request a PR** if this feature would be valuable for `emotion`, and I will try to do my best!

**Comment by mitchellhamilton** [comment]
We'd happily accept a PR for this!

**Comment by rand0me** [comment]
Yay, #680 merged!
Waiting for release

**Comment by Ailrun** [comment]
Close this in favor of #680.
If there is any problem with current typing, please open a fresh issue.
Thank you for posting this issue!
