### ISSUE TITLE
Generated tags include superfluous metadata

### ISSUE THREAD

**Issue by karol-majewski** [emotion-js/emotion#623]
- `emotion` version: 9.0.2
- `react` version: 16.3.1

Relevant code:

https://github.com/emotion-js/emotion/blob/3544dd6c5234cbb62f8f26b72e6e80b89d4b9259/packages/create-emotion/src/sheet.js#L44-L57

What you did:

1. Used `react-emotion` in my application.
2. Validated the serialized DOM with [Nu HTML Checker](https://validator.w3.org/nu/)

What happened:

It returned dozens of warning concerning the `type` attribute that is no longer necessary in HTML5.

>Warning: The type attribute for the style element is not needed and should be omitted.
> ;}</style><style type="text/css" data-emotion="">.css-v

![image](https://user-images.githubusercontent.com/20233319/38659971-f4c0dc10-3e2b-11e8-8329-9402169e0a8f.png)

Reproduction:

Not sure if it's needed (the code doing it is right there), but if you'd like to see it in the wild, go to https://validator.w3.org/nu/ and check https://zefenify.com/about.html mentioned in the README.

Problem description:

As [W3 docs](https://www.w3schools.com/tags/att_style_type.asp) say:

> In HTML5, the type attribute is no longer required for CSS. The default value is "text/css".

Suggested solution:

Delete the line 46.

https://github.com/emotion-js/emotion/blob/3544dd6c5234cbb62f8f26b72e6e80b89d4b9259/packages/create-emotion/src/sheet.js#L46

**Comment by mitchellhamilton** [comment]
Thanks for the issue!! If you submit a PR removing that line and updating any necessary snapshots, I'd be happy to merge it.
