### ISSUE TITLE
Better class name creation

### ISSUE THREAD

**Issue by souporserious** [emotion-js/emotion#63]
I think I've seen this with most CSS-in-JS solutions except for ones that create functional class names. I've probably bugged @threepointone about this way too much, but I'm curious if there are better ways to create these class names and seperate dynamic and static styles. Take the following for instance: 

![image](https://user-images.githubusercontent.com/2762082/27756460-6f9a5ca6-5dac-11e7-95e2-e535c9aae4dc.png)
 
It creates two seperate class names with all the same properties even though only one of them is dynamic. If I were to write this by hand, I'd have a set of these static styles in one class name and then a seperate class name or whatever for each dynamic style.

I guess my first question would be, is this so fast that I just shouldn't care about it? And if it should be of concern, is there a better way to create these components that I'm just not seeing or would this be a library concern? I could see it being a better dev experience if I wanted to tweak these values in devtools, but that's a pretty small nuance.

If this isn't an issue at all, and I'm overthinking everything please feel free to close this 😇

**Comment by thangngoc89** [comment]
1 package I have in mind for pretty dynamic style is [cxs's atomic mode](https://github.com/jxnblk/cxs/blob/master/src/atomic/index.js)

**Comment by souporserious** [comment]
I love the atomic mode in CXS :) I wonder if there is some way to get the best of both worlds.

**Comment by dcalhoun** [comment]
@tkh44 I am also interested in atomic class names similar to what [`styletron`](https://github.com/rtsao/styletron) and [`react-native-web`](https://github.com/necolas/react-native-web) produce. Was there a specific reason this issue was closed?

Are atomic classes not relevant/possible with emotion or is the spirit of atomic classes (i.e. reducing duplicative style declarations) accomplished by other emotion features? Thanks!

**Comment by jessehart** [comment]
+ 1 -- also curious about this

**Comment by thangngoc89** [comment]
@dcalhoun I didn't follow this project for a while but atomic classes only take effect when you are shipping css files (which MAYBE save some spaces due to gzip). All styles in emotion is already in js so there is no need for generating atomic classes. It would mean more tasks for the runtime
