### ISSUE TITLE
Problem with SSR and externally defined CSS

### ISSUE THREAD

**Issue by goldenshun** [emotion-js/emotion#630]
- `emotion` version: 8.0.5
- `react` version: 16.2.0

Relevant code.

```javascript
import { css } from 'emotion';

export const mt4 = css`margin-top: 4rem;`;
export const mb4 = css`margin-bottom: 4rem;`;

```

What you did:
1. I setup a next.js SSR project that uses Emotion (following [this example](https://github.com/zeit/next.js/tree/canary/examples/with-emotion)).
2. I created the aforementioned file to declare reusable CSS.
3. I attempted to use the CSS in a component like so:

```
import { mt4 } from '../styles/margin';
...
<div className={mt4}>
  <h1>This should have 4rems margin above it</h1>
</div>
```

What happened:
Even though I am able to inject the server rendered styles with Emotion's `extractCritical`, the styles are being added again by Emotion on the client.

In the screenshot below, you can see the duplicate styles being applied in dev tools.

![screen shot 2018-04-16 at 1 04 02 pm](https://user-images.githubusercontent.com/2985457/38831016-5bd29fc2-417b-11e8-9c1d-af273d4284f2.png)

This is a link to my repo that demonstrates the issue: https://github.com/goldenshun/next-with-emotion

This is a live demo: https://with-emotion-gbxeilwehs.now.sh/ (It may take a moment for the instance to spin up)

Reproduction:
The issue only happens when I import the CSS declarations from a separate file.  If I add them inline above my component (e.g. `const mt4 = css`margin-top: 4rem;`;`), the styles are not reapplied on the client.

Problem description:

In this scenario, styles should only be applied once from the server.

Suggested solution:

Figure out why styles are being reapplied on the client and stop dat.

**Comment by mitchellhamilton** [comment]
This happens because the css calls happen before hydrate is called. If you move the hydrate call to a seperate file and import it before the file with the css calls then the styles won’t be reinserted 

I’m gonna close this but if the above doesn’t fix the issue, please reopen the issue.

**Comment by goldenshun** [comment]
You are correct sir, that is indeed my problem.  Thank you.
