### ISSUE TITLE
Documenting Ember add-on 

### ISSUE THREAD

**Issue by alexlafroscia** [emotion-js/emotion#638]
I've written an Ember add-on to integration Emotion into Ember apps, called [`ember-emotion`](https://www.npmjs.com/package/ember-emotion). I would love to add it to the documentation so that people in the Ember community know that it's an option when looking at Emotion's website.

Would you be interested in me adding it to the *Packages* section of the documentation site even though it isn't an "official" package that's part of your organization? Would you be interested moving the repo under your umbrella?

**Comment by tkh44** [comment]
I have no problem linking to it in the readme, put in a PR and we'll get it merged 👍 

@mitchellhamilton do you see any problems with moving ember emotion to the emotion-js org? I'm most worried about the expectation of maintenance, but it's not the biggest deal.

**Comment by alexlafroscia** [comment]
> I have no problem linking to it in the readme, put in a PR and we'll get it merged 

It's actually in the README already -- it was the docs site I was asking about.

> I'm most worried about the expectation of maintenance, but it's not the biggest deal.

Totally understandable, and I don't mind keeping it under my name. It's more that from the consumer's standpoint, it seems more "legit" if it's actually within the `emotion` Github organization.

**Comment by mitchellhamilton** [comment]
I'm not big on adding to the packages section since it could make people think it's official and make people open issues about it on this repo and etc.

What we could do though is add a Community section to the docs where there are links to ember-emotion and other projects related to emotion so those projects are more visible but it's clear that they're from the community.

**Comment by alexlafroscia** [comment]
That sounds like a good solution to me!

**Comment by Ailrun** [comment]
@alexlafroscia
Do you have markdown document about `ember-emotion` for our document? I'm now changing `Packages` into `Official Packages` and adding `Third Party Packages`.
If you have appropriate document, please share it with us. I'd really appreciate it.

**Comment by alexlafroscia** [comment]
Cool! I'd love to provide something. What kind of information are you looking for about my Ember addon?

My README has quite a bit of Markdown already, but I can distill that down as it's probably too much.

https://github.com/alexlafroscia/ember-emotion

**Comment by Ailrun** [comment]
@alexlafroscia Yes, "distilling that down" is actually what I meant. Could you do that? Thank you for your contribution for emotion community!

**Comment by alexlafroscia** [comment]
This is basically just the top few sections of the readme, and a link to the README for more information. That's probably the right amount of information for the website; just enough to install and get started:

```markdown
# ember-emotion

> Use emotion in Ember.js

[![Build Status](https://travis-ci.org/alexlafroscia/ember-emotion.svg?branch=master)](https://travis-ci.org/alexlafroscia/ember-emotion)
[![Ember Observer Score](https://emberobserver.com/badges/ember-emotion.svg)](https://emberobserver.com/addons/ember-emotion)
[![npm version](https://badge.fury.io/js/ember-emotion.svg)](https://www.npmjs.com/package/ember-emotion)

This addon

- 👩‍🎤 Exposes `emotion` as a module that can be imported in Ember
- 📦 Adds the ability to define styles scoped to a pod
- 🚀 Supports FastBoot out-of-the-box
- ⚡️ Allows for dynamically defining CSS values

## Installation

```bash
ember install ember-emotion
```

## Usage

To start using `ember-emotion`, add a `style.js` file within a `Component` or `Controller` pod. Each named export can be accessed through the `emotion-class` helper in the pod's template. The default export, for `Component` pods, is merged into the `classNames` property automatically

```javascript
// components/foo-bar/style.js
import { css } from 'emotion';

export default css`
  background: grey;
`;

export const paragraph = css`
  color: blue;
`;
```

```handlebars
{{! components/foo-bar/template.hbs }}
The component background will be grey.
<p class={{emotion-class 'paragraph'}}>
  Just this text will be blue.
</p>
```

For more information, check out the [project `README`][ember-emotion].


[ember-emotion]: https://github.com/alexlafroscia/ember-emotion
```

**Comment by alexlafroscia** [comment]
Thanks for being willing to feature third-party packages on the main website, by the way! Makes it feel more worthwhile to put the effort into it when my package feels like part of the community.

**Comment by Ailrun** [comment]
@alexlafroscia I uploaded PR #715.

**Comment by Ailrun** [comment]
@alexlafroscia, @mitchellhamilton make an awesome repository for emotion, https://github.com/emotion-js/awesome-emotion.
And he already listed your package too.

**Comment by alexlafroscia** [comment]
Awesome!
