### ISSUE TITLE
Stop using componentWillMount

### ISSUE THREAD

**Issue by luisherranz** [emotion-js/emotion#644]
- `emotion` version: 9.1.3
- `react` version: 16.3

Relevant code.

```javascript
        componentWillMount() {
          if (this.context[channel] !== undefined) {
            this.unsubscribe = this.context[channel].subscribe(
              setTheme.bind(this)
            )
          }
        }
```

What you did:
Update to React 16.3 and use `strict mode`.

What happened:
This warning appeared: `componentWillMount: Please update the following components to use componentDidMount instead: Styled(div), Styled(li), Styled(span), Styled(ul)`

Reproduction:
Just use `styled` within React `strict-mode` or [React `Async`](https://github.com/koba04/react-fiber-resources):
https://codesandbox.io/s/732mw5w53j

Problem description:
`componentWillMount` is going to be deprecated and should be avoided from now on.

Suggested solution:
This is the `componentWillMount` which is causing the warning:
https://github.com/emotion-js/emotion/blob/82fd71a8f9fda7df31b4810b17a255a75500686b/packages/create-emotion-styled/src/index.js

That logic could be moved to the `componentDidMount` or the `constructor`. Whichever is the case, let me know and I'll do a PR.

**Comment by ChrisCallanJr** [comment]
made PR [#830](https://github.com/emotion-js/emotion/pull/830) to fix this

**Comment by mitchellhamilton** [comment]
As I mentioned in #830, this is going to be fixed in emotion 10.

**Comment by FezVrasta** [comment]
Closing as fixed by Emotion 10
