### ISSUE TITLE
Add toHaveStyleRule to jest-emotion

### ISSUE THREAD

**Issue by fernandofleury** [emotion-js/emotion#645]
First of all thanks for the library! I've using and enjoying it a lot lately.

I was wondering if there are any plans to add something like `toHaveStyleRule` to `jest-emotion`, something similar to what `jest-styled-components` have: https://github.com/styled-components/jest-styled-components#usage

I'd like to be able to test the output of style generation instead of just matching it against a snapshot.

Thanks!

**Comment by mitchellhamilton** [comment]
We're not planning on adding it but we'd happily accept a PR adding it!!

**Comment by danreeves** [comment]
@fernandofleury I worked on adding this feature to `jest-glamor-react`, which `jest-emotion` is based on. This file should be helpful: https://github.com/kentcdodds/jest-glamor-react/blob/master/src/matchers.js

If you don't get around to it I'd be happy to pick this up

**Comment by fernandofleury** [comment]
Thanks @danreeves! I'm hoping to pick this during the weekend.

**Comment by fernandofleury** [comment]
hey @danreeves would you mind picking this one up? 👀

**Comment by danreeves** [comment]
Sure thing! I'll try and work it in this week

**Comment by Ailrun** [comment]
I believe this is resolved in #662.
Thank you for reporting an issue!
