### ISSUE TITLE
Server-side rendering with theming

### ISSUE THREAD

**Issue by sepehr1313** [emotion-js/emotion#649]
Hello,

I'm trying to have web application using **emotion** and **emotion-theming**. It works well on client-side but when I want to add server-side rendering to the project I see below error message after adding **withTheme(Component)** HOC. I have already added **ThemeProvider** by the way. 

_[withTheme] Please use ThemeProvider to be able to use withTheme_
 _TypeError: Cannot read property 'theme' of null_

**Comment by ChristopherBiscardi** [comment]
Can you post a simple reproduction or the serverside rendering code you're using?
