### ISSUE TITLE
Glamorous -> Emotion -- Prop filtering?

### ISSUE THREAD

**Issue by brentertz** [emotion-js/emotion#653]
Greetings!  Recent conversations about the potential deprecation of Glamorous led me to consider a migration to Emotion.  https://github.com/paypal/glamorous/issues/419

While the API's are similar, they are not quite identical.  One feature that my project relies on heavily in Glamorous is prop filtering, as described by the `rootEl`, `forwardProps`, and `filterProps` sections at https://glamorous.rocks/api

Would this be something that you might consider including in Emotion?

Thanks!

**Comment by Andarist** [comment]
There is `shouldForwardProp` feature option and you can use it like this:
```js
import isPropValid from '@emotion/is-prop-valid'

const StyledTextarea = styled(TextareaAutosize, { shouldForwardProp: isPropValid })
```

**Comment by brentertz** [comment]
@Andarist Thanks for pointing out `shouldForwardProps` option.

Are those options part of the public API?  I could find no references to them in the documentation, only in the source [here](https://github.com/emotion-js/emotion/blob/master/packages/create-emotion-styled/src/utils.js#L34-L39) and [here](https://github.com/emotion-js/emotion/blob/master/packages/create-emotion-styled/src/index.js#L28-L33).

Further, it is really Glamourous' `rootEl` API and props whitelist capability that are missing.  I suppose what I am asking is if there is any interest in adding these capabilities to Emotion.

* https://glamorous.rocks/api -- scroll down to `rootEl` for a description of how it works and why it is useful.
* https://github.com/paypal/glamorous/blob/master/src/should-forward-property.js

**Comment by Andarist** [comment]
Yeah, they are part of the public API. They might have not been documented though - this is quite a new option, implemented not that long time ago. Would be good to have a docs for it, I've created an issue about it [here](https://github.com/emotion-js/emotion/issues/655). We'd love some help with that 😉

**Comment by brentertz** [comment]
Thank you.  It appears as though the `shouldForwardProp` option will work fine for my use case with the forthcoming addition of https://github.com/emotion-js/emotion/pull/670
