### ISSUE TITLE
Component loses its default props when wrapped with styled()

### ISSUE THREAD

**Issue by gragland** [emotion-js/emotion#654]
- `emotion` version: 9.1.3
- `react` version: 16.3.2

```js
const Title = styled('h1')`
  text-align: center;
  ${props => ({
    color: props.color
  })};
`;

Title.defaultProps = {
  color: 'red'
};

const Title2 = styled(Title)`
  font-style: italic;
`;
```

What you did:

Created a new styled component by wrapping an existing styled component in `styled()`.

What happened:

The wrapped styled component lost its defaultProps. In the example above `<Title>` is displayed as red, but `<Title2>` is not.

<b>CodeSandbox: https://codesandbox.io/s/317r028k6q</b>

**Comment by ChristopherBiscardi** [comment]
https://codesandbox.io/s/q7v504x1pq

Possible workaround using default arguments:

```javascript
const Title = styled("h1")`
  text-align: center;
  ${({ color="red" }) => ({ color })};
`;
```

**Comment by MattHsiung** [comment]
@Jayphen we've been working around this using the same thing.
The problem is Emotion is "collapsing" styled components together, and therefore static properties get lost.
