### ISSUE TITLE
CSS specificity issues when used together with styled-components

### ISSUE THREAD

**Issue by niekert** [emotion-js/emotion#661]
- `emotion` version: 9.1.3
- `react` version: 16.3.2

At my company, we have a component library which was written in glamorous. We use the components from the component library in multiple frontends where we use `styled-components`. We are in the process of migrating the component library from `glamorous` to `emotion` because of the performance gain, which is already very noticeable, so we're very happy with emotion so far :)

In our React app that uses `styled-components`, we sometimes override the `emotion` components from the component library to add some additional styling, a simplified example:

```js
import emotion from 'react-emotion';
import styled from 'styled-components';

const Card = emotion('div')({
  padding: '20px',
  color: 'white',
  background: 'purple',
});

// Usually "Card" would be an import from an NPM package here
const GreenCard = styled(Card)`
  background: green;
`;
```

On development builds we are now running into issues with CSS specificity whenever we try to render `<GreenCard />`. It still has a purple background instead of a green one.  I think the issues lies in the order of injection of the `<style>` tags in the HTML document, which causes this output in the developer tools:

![image](https://user-images.githubusercontent.com/5508905/40108754-280b39e0-58fc-11e8-9579-36b994b555cb.png)

![image](https://user-images.githubusercontent.com/5508905/40108804-4b5ec592-58fc-11e8-9143-1e1ebf272d61.png)

If I move the `<style data-styled-components />` below the `<style data-emotion />` tag, the component does get the green background applied.

I tried to create a CodeSandbox to reproduce the issue but I was unable to reproduce it there. So instead of a CodeSandbox, I created a small `create-react-app` repo where the issue can be reproduced (just run `yarn start`, the bottom div is expected to have a green background).
https://github.com/niekert/emotion-styled-injection-order-issue

I am not sure if this is an issue with Emotion itself, but I am opening the issue here because we did not have any problems with this when the components from our component library were written in glamorous. 

Is what we're trying to do something that _should or could_ be supported? Or would the proposed solution be to migrate everything from `styled-components` to `emotion` as well? The only thing I am still worried about in that case is what would happen if we try to override the styles of a (3rd party) component from a package that uses `styled-components` or vice versa?

**Reproducable example:**
https://github.com/niekert/emotion-styled-injection-order-issue

**Comment by Andarist** [comment]
You can try swapping [those 2 lines](https://github.com/niekert/emotion-styled-injection-order-issue/blob/c6524278cff823260e83ab563ac7ed9be07fe717/src/App.js#L2-L3). That would make `styled-components` run first and `emotion` second, which should result in `style` tags being inserted in reversed order.

**Comment by niekert** [comment]
Thanks for the suggestion. Unfortunately it does not seem to resolve the issue.

I also tried [doing this](https://github.com/niekert/emotion-styled-injection-order-issue/blob/try-import-styled-first/src/App.js#L5) To ensure `styled-components` will run first but it also does not make difference. Also doing the above and changing the `styled-components` import to `react-emotion` (so `emotion` runs first) doesn't make a difference.

**Comment by Andarist** [comment]
The most reliable way of working around insertion order is to actually control it. Not sure though how you can do that with `styled-components`.

Technically you could use production mode for emotion when developing and that would "fix this" but you wouldn't be able to edit inserted styles in your dev tools, so it's not a great DX either.

**Comment by niekert** [comment]
Indeed, being able to control the insertion order would be the most ideal to work around the issue (that I can think of at least). Is there a way to control this with `emotion`? 

Production mode indeed impacts the DX too much to be a good solution for me personally.

**Comment by Andarist** [comment]
> Indeed, being able to control the insertion order would be the most ideal to work around the issue (that I can think of at least). Is there a way to control this with emotion?

https://github.com/emotion-js/emotion/tree/1d27e374d8df7ab3dba5f82b2f31f25a60844e65/packages/create-emotion#primary-use-cases

It is to some extent. You'd have to create custom emotion's instance - IMHO it's no biggie, I do it to prevent conflicts & namespace styles (so they are easy to distinguish) on a site that has 2 live applications in it, both of each using emotion but not sharing components/styles.

As emotion creates multiple style tags in development mode (appending them at runtime, so they will always be created as last child) I'm not sure if you can workaround it without controlling styled-components' style tag too.

**Comment by niekert** [comment]
Thanks! That makes sense. Sounds like I should dig a bit deeper into how to control this with `styled-components`. Or maybe we should switch to `emotion` completely as the APIs are almost fully compatible

**Comment by Andarist** [comment]
Latter would certainly help with this issue altogether + u'd be able to downsize your bundles as you'd be shipping only a single css-in-js library 😉

**Comment by niekert** [comment]
We ended up migrating everything to `emotion`, which ended up being really easy. We're happy now!

Feel free to close the issue unless you think it needs to remain open :)

**Comment by Andarist** [comment]
Don't think there is much to do on emotion's side for now regarding this. Closing for now, but feel free to  comment further.

**Comment by Pajn** [comment]
I have basically this problem with JSS. I cant get rid of JSS unfortunately because of material-ui.

It works in DEV where emotion creates multiple `<style>` tags but in prod emotion only creates one, which comes before all JSS tags and therefore looses the specificity game.
Is it possible to tell emotion to create multiple `<style>` tags in prod as well?

**Comment by Andarist** [comment]
There is - but it’s slower and not recommended for production mode. You can increase emotion’s specificity though - im on mobile so its hard for me to give u exact link, but u can search issues for ScopeProvider or stylis-plugin-extra-scope

**Comment by Pajn** [comment]
Thanks. It seems like I depend on some JSS rules being stronger and some emotion rules being stronger. I did work around the specific problem I discovered now with the `&&` hack and will have to go through and sort out the rest later. But it seems like ScopeProvider should be able to provide a stable specificity between dev and prod.

**Comment by mitchellhamilton** [comment]
The specificity should be stable between prod and dev in v10 btw.

**Comment by Pajn** [comment]
@mitchellhamilton That's nice, thanks for letting me know! I will prioritize upgrading then.
