### ISSUE TITLE
Error if withTheme used without ThemeProvider

### ISSUE THREAD

**Issue by gragland** [emotion-js/emotion#664]
- `emotion` version: 9.1.2
- `react` version: 16.3.2

What you did:

I'm building a library that uses the `withTheme` HOC to check if the library consumer has specified a theme via `ThemeProvider`. 

What happened:

The issue is that if the library consumer is not using `ThemeProvider` then `withTheme` throws an error: `TypeError: Cannot read property 'theme' of null`. There's no way for me to know ahead of time whether they have a theme (without re-implementing withTheme) and I'd like to be able to handle it gracefully if they do not.

Suggested solution:

If there is no theme context then I think it would make sense to have `withTheme` HOC pass an `undefined` theme to the child component (maybe just initialize state as an empty object which is what [styled-components does](https://github.com/styled-components/styled-components/blob/beed1b813a1bbe11a94f73d7aa3669392bd891eb/src/hoc/withTheme.js#L36_)). Happy to do a pull request if this sounds good or there's another solution you have in mind. Relevant line of code: https://github.com/emotion-js/emotion/blob/3544dd6c5234cbb62f8f26b72e6e80b89d4b9259/packages/emotion-theming/src/with-theme.js#L34

**Comment by Andarist** [comment]
It sounds good to me, go ahead with the PR. Keep in mind that this will need @mitchellhamilton approval.

**Comment by gragland** [comment]
Sorry didn't have time to get to this. Going to close for now.

**Comment by kacpak** [comment]
Was this fixed? I'm also experiencing this issue
