### ISSUE TITLE
Minimum supported React version?

### ISSUE THREAD

**Issue by brentertz** [emotion-js/emotion#665]
Hello.  I wonder if you can tell me what is the minimum supported React version for using Emotion in a React project?

I see the [resolutions field in the root package.json](
https://github.com/emotion-js/emotion/blob/master/package.json#L27) of the project lists it as `^16.2.0`.  I did not however see React as a [peer dependency](https://github.com/emotion-js/emotion/blob/master/packages/react-emotion/package.json#L25) in `react-emotion`.  I also did not find it elsewhere in the documentation.

I ask this question for several reasons.

* I am investigating the migration of a [library](https://github.com/mineral-ui/mineral-ui) that is currently built on Glamorous, [which may soon be deprecated](https://github.com/paypal/glamorous/issues/419).  We currently support React 15.3+.   While we are not beholden to support such old versions, I do need to communicate those that are supported.
* I have seen mention of using `forwardRef` in your issues and wonder if adopting new React API's is generally done with consideration to maintaining any compatibility with older versions or if things just move fast and you generally just support the latest version. 

Thanks so much!

**Comment by Andarist** [comment]
Supporting `forwardRef` will have to be done as major bump, so you don't have to worry about it now. I don't know exact supported range (this probably should be expressed with peer dep on `react-emotion`, cc @mitchellhamilton) - but as React's API is quite stable `emotion` should work just fine with at least `react@^15` as `emotion` doesnt use any newer APIs just yet.
