### ISSUE TITLE
react-emotion is missing react (peer)dependency

### ISSUE THREAD

**Issue by mgroenhoff** [emotion-js/emotion#684]
There is a direct dependency on react in your code but there is no reference to it in package.json

https://github.com/emotion-js/emotion/blob/d9a9e332dfbc13ea78325082393ccdd54d34afd6/packages/react-emotion/src/index.js#L2

https://github.com/emotion-js/emotion/blob/d9a9e332dfbc13ea78325082393ccdd54d34afd6/packages/react-emotion/package.json#L21-L27

This would normally not be an issue when using a package manager (NPM) that optimizes the resulting dependency tree since react will be placed at the root of the node_modules directory. Otherwise you'll get an error like me:

> Module not found: Error: Can't resolve 'react' in ...

**Comment by mgroenhoff** [comment]
Alright. What version of react would you like to put there?

**Comment by Andarist** [comment]
I **think** emotion supports react@15 just fine (maybe even 0.14? ain't sure if we want to support this one though). Ideally you'd have to prepare some codesandbox.io example and test out different versions of react to find out which one is supported and which is not.

**Comment by mgroenhoff** [comment]
I tested both react and preact in codesandbox.io and for react i chose >= 15 because I found that to be present in another package.json. For preact only version 8 or above seems to work to I chose >= 8. If you want me to change please let me know on the PR
