### ISSUE TITLE
new `stylelint` support.

### ISSUE THREAD

**Issue by gucong3000** [emotion-js/emotion#686]
I am working on `stylelint` and `postcss` that support `emotion`.
I need more testing and feedback. Can someone help me?
All you need to do is just install [postcss-jsx](https://github.com/gucong3000/postcss-jsx)

```bash
npm install --save-dev stylelint/stylelint postcss-jsx
stylelint **/*.{js,jsx,css}
```
`processors` and `syntax` must remove from `.stylelintrc` and CLI

**Comment by ai** [comment]
```js
import styled from 'emotion'

const Container = styled('div')({
  position: 'relative',
  fontSize: 13,
  fontWeight: 'bold',
  lineHeight: '30px',
  color: 'white',
  textAlign: 'center',
  cursor: 'default',
  backgroundColor: 'gray',
  borderRadius: 15,
  size: 30,
  marginTop: 10,
  margin: '0 auto'
})

const Avatar = () => {
  return h(Container)
}

export default Avatar
```

```json
{
  "extends": [
    "stylelint-config-standard"
  ]
}
```

```sh
➤ npm ls | grep stylelint
├─┬ stylelint@9.2.1
├─┬ stylelint-config-recess-order@2.0.0
│ └── stylelint-order@0.8.1 deduped
├─┬ stylelint-config-standard@18.2.0
│ └── stylelint-config-recommended@2.1.0
├── stylelint-config-styled-components@0.1.1
├─┬ stylelint-order@0.8.1
├─┬ stylelint-processor-styled-components@1.3.1

➤ npm ls | grep postcss-jsx
├─┬ postcss-jsx@0.26.0

➤ n stylelint components/avatar.js
TypeError: this[node.type] is not a function
    at Stringifier.stringify (/home/ai/Dev/amplifr-front/node_modules/postcss/lib/stringifier.js:33:24)
    at stringify (/home/ai/Dev/amplifr-front/node_modules/postcss/lib/stringify.js:14:9)
    at Obj.toString (/home/ai/Dev/amplifr-front/node_modules/postcss/lib/node.js:195:9)
    at module.exports (/home/ai/Dev/amplifr-front/node_modules/stylelint/lib/utils/rawNodeString.js:12:18)
    at module.exports (/home/ai/Dev/amplifr-front/node_modules/stylelint/lib/utils/blockString.js:22:10)
    at root.walkDecls.decl (/home/ai/Dev/amplifr-front/node_modules/stylelint/lib/rules/declaration-block-semicolon-newline-after/index.js:54:23)
    at /home/ai/Dev/amplifr-front/node_modules/postcss/lib/container.js:188:28
    at /home/ai/Dev/amplifr-front/node_modules/postcss/lib/container.js:144:26
    at Obj.each (/home/ai/Dev/amplifr-front/node_modules/postcss/lib/container.js:110:22)
    at Obj.walk (/home/ai/Dev/amplifr-front/node_modules/postcss/lib/container.js:143:21)
```

**Comment by ai** [comment]
```js
import styled from 'stylelint'

const Container = styled.div`
  position: relative;
  font-size: 13px;
  font-weight: bold;
  line-height: 30px;
  color: white;
  text-align: center;
  cursor: default;
  background-color: gray;
  border-radius: 15px;
  size: 30px;
  margin-top: 10px;
  margin: 0 auto;
`

const Avatar = () => {
  return h(Container)
}

export default Avatar
```

```
➤ n stylelint components/avatar.js
(no error, margin overriding margin-top error was missed)
```

**Comment by ai** [comment]
```js
import styled from 'stylelint'

const Container = styled.div`
  position: relative;
  font-size: 13px;
  font-weight: bold;
  line-height: 30px;
  color: white;
  text-align: center;
  cursor: default;
  background-color: gray;
  border-radius: 15px;
  size: 30px;
  margin-top: 10px;
  margin: 0 auto;
`

const Avatar = () => {
  return h(Container)
}

export default Avatar
```

```json
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-standard"
  ]
}
```

```
➤ n stylelint components/avatar.js

components/avatar.js
 15:3  ✖  Unexpected          declaration-block-no-shorthand-property-overrides
          shorthand "margin"                                                   
          after "margin-top"
```

**Comment by ai** [comment]
@Andarist what do you think?

**Comment by Andarist** [comment]
the idea is good, im totally out of the loop here though, not knowing this tool etc and cant evaluate it right now

also - what's this issue about? adding this to the docs?

**Comment by ai** [comment]
Yeap. Adding it to docs.

**Comment by Andarist** [comment]
Somebody would have to create a PR for this - preferably to some ecosystem/community-like page 😉 I think it should get merged in without much hesitation on our side.

**Comment by ai** [comment]
@gucong3000 will you send a PR?

**Comment by gucong3000** [comment]
#800

**Comment by ai** [comment]
Instead of working with issues, you created a bot which says “we don’t care” for you. Not good feedback for users and contributors.

**Comment by ai** [comment]
The PR is merged, just close the issue.

**Comment by Ailrun** [comment]
Close this by #800.

**Comment by ilias-t** [comment]
Not sure how #800 fixes this issue. It's just a reference to use stylelint. Tried adding `postcss-jsx` and also linting javascript files like @gucong3000's initial example, but it's not catching issues. There doesn't seem to be any documentation on the recommended way to lint emotion aside from the not very helpful reference to stylelint. Am I missing something?

**Comment by ilias-t** [comment]
FYI ended up getting it working with the above advice:

- In `.stylelintrc` use `"stylelint-processor-styled-components"` as processor & extend with `"stylelint-config-styled-components"` (does anyone else find it odd to use a different library's lint config?)
- Install `postcss-jsx` & run `stylelint`

HOWEVER in my case I wanted to lint both `css` and `tsx` and found that `stylelint **/*.{css,tsx}` did not work while `stylelint **/*.tsx && stylelint **/*.css` did. Not sure why that's the case... Curious if anyone else is able to repro.

**Comment by Sawtaytoes** [comment]
@ilias-t Have you tried using parens instead?
```sh
stylelint **/*.(css|tsx)
```

When running `StylelintWepackPlugin`, this is what I'm using: `'**/*.(js|jsx)'`.

**Comment by Slapbox** [comment]
Anyone able to get this working these days? We get `"Unknown word   CssSyntaxError"` all over the place unfortunately - it seems mostly due to comments, but sometimes the line/column numbers don't exactly match where I'd expected, so I'm not entirely sure.

**Comment by kelly-tock** [comment]
there should be some docs on this :)

**Comment by karlhorky** [comment]
There are more details over here: https://github.com/styled-components/styled-components/issues/3607#issuecomment-1000937952

Our config, which we use for linting CSS in `.css` files, Emotion in `.js` and `.tsx` files:

`stylelint.config.cjs`

```js
/** @type { import('stylelint').Config } */
const config = {
  extends: [
    'stylelint-config-recommended',
    'stylelint-config-styled-components',
    'stylelint-config-prettier',
  ],
  rules: {
    'no-descending-specificity': null,
  },
  overrides: [
    {
      files: [
        '**/*.js',
        '**/*.cjs',
        '**/*.mjs',
        '**/*.jsx',
        '**/*.ts',
        '**/*.tsx',
      ],
      processors: ['stylelint-processor-styled-components'],
      customSyntax: 'postcss-scss',
    },
  ],
};

module.exports = config;
```

https://github.com/upleveled/eslint-config-upleveled/blob/main/templates/stylelint.config.cjs

It mostly works - at least better than nothing.

As soon as either Emotion or Styled Components can provide an updated solution (eg. a `customSyntax`) for Stylelint v14, we will gladly switch to that.
