### ISSUE TITLE
TypeScript example is broken in documentation

### ISSUE THREAD

**Issue by smashercosmo** [emotion-js/emotion#696]
When trying to run this typescript example from documentation, I get many typescript errors
https://emotion.sh/docs/typescript#passing-props-when-styling-a-react-component

- `emotion` version: 9.1.3
- `react` version: 16.4.0
- `typescript` version: 2.8.3

What you did:
Tried to run this example

What happened:
Got many typescript errors

![screen shot 2018-05-31 at 16 55 27](https://user-images.githubusercontent.com/273283/40786355-87b80cd0-64f3-11e8-8eb4-26e89c07aef9.png)
![screen shot 2018-05-31 at 16 56 34](https://user-images.githubusercontent.com/273283/40786395-9e624554-64f3-11e8-8864-281281812e6b.png)
![screen shot 2018-05-31 at 16 57 19](https://user-images.githubusercontent.com/273283/40786453-be84c942-64f3-11e8-84ef-7c3c53d12f9d.png)
![screen shot 2018-05-31 at 16 58 18](https://user-images.githubusercontent.com/273283/40786502-db308ec8-64f3-11e8-95d3-7e7be9fec173.png)

**Comment by smashercosmo** [comment]
Ok, figured out the correct way

```jsx
import * as React from 'react'
import styled from 'react-emotion'

type ComponentProps = {
  className?: string,
  label: string
}

type StyledComponentProps = {
  bgColor: string
}

const Component: React.SFC<ComponentProps> = ({ label, className }) => (
  <div className={className}>{label}</div>
)

const StyledComponent = styled<ComponentProps, StyledComponentProps>(Component)`
  color: red;
  background: ${props => props.bgColor};
`

const App = () => (
  <StyledComponent bgColor="red" label="Oh, needs to re-type label prop =(" />
)
```

**Comment by Ailrun** [comment]
Close this issue in favor of #679.
