### ISSUE TITLE
Automated deployment process design and setup

### ISSUE THREAD

**Issue by tkh44** [emotion-js/emotion#701]
*Problem description:*

Right now it is a manual process to do a release and it can take some time to get everything just right. We're getting behind on doing minor releases. With all the new attention the number of PR's seems to be growing with no real defined release process.

*Suggested solution:*

I would like to set it up so that when deploys hit a certain branch (maybe master?) we do an auto minor release. I think @kentcdodds has this setup for glamorous so he may have some insight or pre-built solutions.

Automation goals:
1. Publish based on some flag (major/minor/patch) [based on some comment in PR comment maybe]
2. Generate changelog based on (*1*)

Documentation goals:
1. Update Contributing.md to reflect new process and make it easier for devs to contribute.
2. Update Issue & PR temlates to better reflect our current needs and processes

I would also like to remove the benchmarks from running on every build and deploy and be more selective on when we run them. This can be a seperate issue, but it might be pertanant to this conversation.

I'm really open to suggestions because, well, we don't have any particular setup at the moment other than an `npm run release` script that doesn't update the changelog automatically and is set up really only for patches.

**Comment by Ailrun** [comment]
This sounds really nice!

**Comment by tkh44** [comment]
> https://twitter.com/mkern_/status/1004455494407393282

@mkern_ on twitter suggested https://github.com/semantic-release/semantic-release which has most of the features we need but I don't think it works with Lerna.

**Comment by Ailrun** [comment]
It looks like there is a forked version of semantic-release, with Lerna support.
https://github.com/atlassian/lerna-semantic-release

**Comment by ChristopherBiscardi** [comment]
I've set up semantic release a few times and lerna-semantic-release at least once that I can remember. I think Atlassian is moving to [bolt](https://github.com/boltpkg/bolt) though, which I use on another project and I think has a publish command implemented.

**Comment by ChristopherBiscardi** [comment]
Bolt is a drop-in replacement for yarn (and we're using workspaces here), so I might be able to put together a test branch for that if it seems interesting.

**Comment by tkh44** [comment]
That sounds like a good first step @christopherbiscardi. I’m sure if we get a PR up it will move the general discussion to a more focused one at the very least.
