### ISSUE TITLE
Prevent styled components from re-rendering unnecessarily

### ISSUE THREAD

**Issue by max-barry** [emotion-js/emotion#702]
- `emotion` version: 9.1.0
- `react` version: 16.3.1

**Problem description**
There's probably a lot of people using Emotion to do the below. Styling up a bunch of low-level components shared across their application.

These low level components will re-render when their parent does, despite their children (e.g. text) never changing. 

**Example**
I had a basic card component. `onClick` a checkbox on the card updated. But when the card re-rendered all of the low level styled components (like the below) also updated. This card had a title, a deck, a strap line. It was 3 unnecessary re-renders in addition to the checkbox.

The children prop of `MyTextBox` (it's text) was not really changing, but causing a re-render. Often this is overcome with a "pure" implementation using React's `React.PureComponent` or `shouldComponentUpdate`. Personally I use `onlyUpdateForKeys` from [recompose](https://github.com/acdlite/recompose).

```javascript

// Basic styled component
const MyTextBox = styled('p')({ color: red; })

// ... and that component in use
<MyTextBox>Some text that will never change</MyTextBox>

// More performant "pure" implementation
import { onlyUpdateForKeys } from 'recompose';
const MyTextBox = onlyUpdateForKeys([])(styled('p')({ color: red; }))
```

**Suggested solution**
By making the component pure it boosts performance and I know (in this case) I'm never going to change the text in that `<p>` tag.

Could we indicate when a styled component should render pure? Then internally implement a `shouldComponentUpdate` returning false to all.

```javascript

// True indicating "pure" or "native" rendering
const MyTextBox = styled('p', true)({ color: red; })
```

**Comment by Andarist** [comment]
Wouldnt [https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-constant-elements](babel-plugin-transform-react-constant-elements) "fix" ur problem? And for wider range of elements.

**Comment by R-iskey** [comment]
I'm also have similar issue

**Comment by konstantin24121** [comment]
Same here. All the components are re-rendering constantly.

**Comment by benjamingeorge** [comment]
I'm also having this issue and it does produce a noticeable performance issue in the UI.  Switching back to just using a <span> removes the constant re-renders and fixes the problem.  So it must be a styled-component related issue.

**Comment by stbly** [comment]
I'm finding that the re-rendering is preventing css transitions from working. I tried switching to CSS animations but it still is buggy.

**Comment by met5678** [comment]
We're having this problem too, and it's extremely noticeable when trying to use GreenSock animation on a styled component.

**Comment by cburkins** [comment]
Kind of agree, seems like styled-components shouldn't re-render, and rather be extended from PureComponent ?

**Comment by sassanh** [comment]
@Andarist Can we re-open this issue as it seems to be unresolved? I don't have any performance issues but the way it is makes the `Highlight updates when components render` feature of react dev-tools useless as I can't really see which components are getting re-rendered and I need to add `console.log` in their renderer functions to make sure things are going as expected.

**Comment by bittoomania** [comment]
I am facing similar issue

**Comment by Andarist** [comment]
Please create a repro case showcasing the problem. Cant reopen without that.

**Comment by amber-pli** [comment]
I got the same issue, following it is output of the `memo` function:

```
{
  "prevProps": {
    "style": [
      {
        "marginLeft": 16
      }
    ]
  },
  "nextProps": {
    "style": [
      {
        "marginLeft": 16
      }
    ]
  }
}
```

**Comment by Andarist** [comment]
I can only repeat myself - please create a repro case showcasing the problem. Cant reopen without that. 

This is crucial for me understanding the exact nature of the problem and implementing a fix or just answering back with a recommendation or an appropriate explanation of this.
