### ISSUE TITLE
jest-emotion 9.2.0 replacing non-emotion class names

### ISSUE THREAD

**Issue by wKovacs64** [emotion-js/emotion#706]
- `emotion` version: 9.2.1 **(jest-emotion: 9.2.0)**
- `react` version: 16.4.0

Relevant code.

```javascript
import React from "react";
import { css, cx } from "emotion";
import renderer from "react-test-renderer";

const classes = cx(
  "net-42",
  "net",
  css`
    color: darkorchid;
  `
);

it("renders with correct styles", () => {
  expect(renderer.create(<div className={classes} />)).toMatchSnapshot();
});
```

What you did:

Upgraded jest-emotion from 9.1.3 to 9.2.0.

What happened:

Serialized snapshot tests failed due to incorrect classes being applied.

```css
- Snapshot
+ Received

<div
-  className="net-42 net emotion-0"
+  className="emotion-0 net emotion-1"
/>
```

Reproduction:

https://github.com/wKovacs64/jest-emotion-testing

Problem description:

CSS classes that match the [`/e[a-zA-Z0-9-]+[0-9]+/`](https://github.com/emotion-js/emotion/blob/ee71446ac21861f938f51b5696db956d75e8ce87/packages/jest-emotion/src/replace-class-names.js#L8) regex (e.g. `net-42`) are being treated as `emotion` classes.

Suggested solution:

I think this came from https://github.com/emotion-js/emotion/pull/641 and the regex just needs updating?

**Comment by mitchellhamilton** [comment]
Just published `jest-emotion@9.2.2` with this fixed.
