### ISSUE TITLE
.babelrc "emotion" => Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by CSMR-DB** [emotion-js/emotion#719]
**package.json dependencies**
```
{
    "dependencies": {
        "@babel/core": "^7.0.0-beta.46",
        "@babel/plugin-proposal-class-properties": "^7.0.0-beta.46",
        "@babel/polyfill": "^7.0.0-beta.46",
        "@babel/preset-env": "^7.0.0-beta.46",
        "@babel/preset-es2015": "^7.0.0-beta.46",
        "@babel/preset-react": "^7.0.0-beta.46",
        "@babel/runtime": "^7.0.0-beta.46",
        "babel-core": "^7.0.0-bridge.0",
        "babel-plugin-emotion": "^9.2.0",
        "emotion": "^9.2.3",
        "polished": "^1.9.2",
        "prop-types": "^15.6.1",
        "react": "^16.3.1",
        "react-addons-pure-render-mixin": "^15.6.2",
        "react-apollo": "^2.1.3",
        "react-dom": "^16.3.1",
        "react-emotion": "^9.2.3",
        "react-fontawesome": "^1.6.1",
        "react-html-id": "^0.1.2",
        "react-meteor-data": "^0.2.11",
        "react-redux": "^5.0.7",
        "react-router-dom": "^4.2.2",
        "styled-components": "^3.2.5",
        "stylus": "^0.54.5",
    }
}
```

**.babelrc**
```javascript
{
	"presets": ["@babel/es2015", "@babel/env", "@babel/react"],
	"plugins": [
		"emotion",
		"@babel/plugin-proposal-class-properties",
		"babel-plugin-inline-import"
	]
}
```

What you did:
* Add emotion to list of plugins as per documentation

What happened:
```
Uncaught TypeError: Cannot read property '0' of undefined
    at interleave (modules.js?hash=62fa846c5eef139f458a162657c1411429b09d43:50217)
    at css (modules.js?hash=62fa846c5eef139f458a162657c1411429b09d43:50226)
    at templateFunction (modules.js?hash=62fa846c5eef139f458a162657c1411429b09d43:52088)
    at NotFound.jsx (NotFound.jsx:28)
    at fileEvaluate (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:353)
    at require (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:248)
    at routes.js (routes.js:1)
    at fileEvaluate (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:353)
    at require (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:248)
    at Navi.jsx (Navi.jsx:1)
```

When not using `emotion` inside the .babelrc plugins list I'd get a working app, but no migration from the styled-components syntax. Changing the order of `emotion` in that list changes nothing. 

**Edit:** I could obviously just use the `styled( "element" )` syntax, but that shouldn't be a requirement. I don't want to be forced to rewrite all my components using styled-components' syntax, especially when I am migrating theming to `emotion`. I would also lose VSCode's styled-components plugin syntax highlighting... :(

**Comment by Ailrun** [comment]
@CSMR-DB Thank you for reporting! Could you provide a minimal reproduction?

**Comment by CSMR-DB** [comment]
I can't seem to (at least yet). Creating a new project with the exact same `package.json` and `.babelrc` results in the code just working. This new project only consists of this `main.js` file:

```
import React, {Component} from "react";
import { render } from "react-dom";
import styled from "react-emotion";

const Header = styled.h1`
  color: red;
`

const Test = props => (
  <div>
    <Header>Yeet</Header>
    <p>Yoted</p>
  </div>
);


Meteor.startup( () =>
{
	render(
    <Test />,
		document.getElementById( "root" )
	);
} );
```

At the moment styling has no priority for me, so in the main project I will at least keep using `styled-components` for the time being. I'll see if I can find some spare time to "break" this repro.

**Comment by tkh44** [comment]
I have a feeling emotion is targeting a styled-components `css` function call. There is no safety check on their css function for empty styles IIRC.

The stack trace shows these breadcrumbs from styled-components. 

> https://github.com/styled-components/styled-components/blob/cfbca01923283c2df4ff7d999a2baa2243dd0677/src/utils/flatten.js#L8

> https://github.com/styled-components/styled-components/blob/699a22b935a58ebb168b2c05050aa75d389ada40/src/constructors/constructWithOptions.js#L21

Depending on which library you are using more you can adjust this value:

https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion#importednames


I'm going to close this for now. If you feel that I've misread the issue please feel free to reopen it.
