### ISSUE TITLE
Typing of props in restyled components is broken in latest build

### ISSUE THREAD

**Issue by mvestergaard** [emotion-js/emotion#721]
Big changes were made to the typings in the last few releases.
I tried to upgrade from 9.1.3 to 9.2.3, where it appears that inference of props types is broken.

- `emotion` version: 9.2.3
- `react` version: 16.4.0
- `typescript` version: 2.9.1

Relevant code.

```typescript
import styled from 'react-emotion';
import React from 'react';

interface MyProps {
  className?: string;
  someBehavior: boolean;
}

const MyComponent: React.SFC<MyProps> = ({className}) => <div className={className} />

const MyStyledComponent = styled(MyComponent)`
  border: ${props => props.someBehavior ? 1 : 0}px;
`;
```

Results in this error:
```
Property 'someBehavior' does not exist on type '{ theme: any; }'.
```

**Comment by Ailrun** [comment]
@mvestergaard I removed that inference because of `withComponent`.
Let's suppose that you have following code.
```
interface Props0 {
  typing: number;
}
declare const Component0: React.SFC<Props0>;
interface Props1 {
  typing: { [key: string]: string };
}
declare const Component1: React.SFC<Props1>;

const StyledComponent0 = styled(Component0)`
  left: ${props => props.typing}px;
`
const StyledComponent1 = StyledComponent0.withComponent(Component1);
```
Now, what is the correct type for `StyledComponent1`? At least I cannot find the answer.

**Comment by Ailrun** [comment]
Without that inference, in other words, without _dependency on component props_, we can determine type of props deterministic way.

**Comment by mvestergaard** [comment]
So you're saying that you intend it to work this way?

Having to write this type of thing everywhere becomes tedious fast.
```typescript
const MyStyledComponent = styled(MyComponent)`
  border: ${(props: MyProps) => props.someBehavior ? 1 : 0}px;
`;
```

Isn't the code i wrote a more common use case than `.withComponent`?
Should you really make that sacrifice?

This is borderline incentive for me to move back to styled-components if you're saying this is how you intend it to work.

**Comment by Ailrun** [comment]
@mvestergaard So, what's your answer? What is the correct type for `StyledComponent1`? What you mean is just giving up to give correct type for components with `.withComponent`?

**Comment by Ailrun** [comment]
@mvestergaard Furthermore, if you use TS >= 2.9, you can extract `:MyProps` to type parameter like
```tsx
const MyStyledComponent = styled(MyComponent)<MyProps>`
  border: ${props => props.someBehavior ? 1 : 0}px;
`;
```

**Comment by mvestergaard** [comment]
My answer is that you can't infer that. At best it would be `Props0 & Props1`
But my counter-question is, should you really sacrifice inference in the normal use case, because you can't make it work for `.withComponent`?

**Comment by Ailrun** [comment]
@mvestergaard And more importantly, IMO, that's not the most frequent use case, since you usually don't need forwarding props for styling to internal component.

**Comment by Ailrun** [comment]
At least I use something like this.
```
interface MyProps {
  className?: string;
}
const MyComponent: React.SFC<MyProps> = ({className}) => <div className={className} />

interface StyledProps {
  someBehavior: boolean;
}
const MyStyledComponent = styled(MyComponent)<StyledProps>`
  border: ${(props: MyProps) => props.someBehavior ? 1 : 0}px;
`;
```

**Comment by Ailrun** [comment]
@mvestergaard But, OK. If you truly want our typings to support your use case, let me give time. I need to think about it.

**Comment by mvestergaard** [comment]
My opinion is that if possible, the code you write in typescript should not be different from what it would be in javascript. You should not need to tack on types where it can be inferred. But it seems we don't share that opinion.

The problem here is mostly that you've changed something that made existing code which worked just fine, suddenly have errors.

**Comment by mvestergaard** [comment]
This is a minor thing, not related to you, but there's also the problem that the styled-components vscode extension doesn't support this syntax:

```typescript
const MyStyledComponent = styled(MyComponent)<MyProps>`
  border: ${props => (props.someBehavior ? 1 : 0)}px;
`;
```

**Comment by Ailrun** [comment]
@mvestergaard Oh, really? Thank you for information. I didn't know that. (I don't use vscode)

**Comment by Ailrun** [comment]
@mvestergaard I cannot find a way except breaking `withComponent` type (and I use it quite lot in my project).
Let me ask about this to others.
@mitchellhamilton, @tkh44, How do you think about this?
I mean, type inferencing for `styled` case is important, or preserving `withComponent` type is important? Which one is more frequent use case of emotion users?

**Comment by Ailrun** [comment]
@mvestergaard I just opend #722.

**Comment by patrykkarny** [comment]
I have a similar issue in my codebase, previously was used react emotion 9.1.3 with typescript 2.8.3 and just typing my styled components like this:

```tsx
import styled from 'react-emotion';
import { IThemeProps } from 'consts';

export interface IProps extends IThemeProps {
  fullWidth?: boolean;
  centered?: boolean;
}

export const Button = styled<IProps, 'button'>('button')`
  background-color: ${props => props.theme.color.brandPrimary};
  color: ${props => props.theme.color.black};
  min-width: ${({ fullWidth }) => (fullWidth ? 'auto' : '250px')};
  width: ${({ fullWidth }) => (fullWidth ? '100%' : 'auto')};
  margin: ${({ centered }) => (centered ? '0 auto' : 0)};
`;
```

and it works pretty well. Now I updated to the latest version of react-motion and typescript 2.9 and every component is complaining about improper types. Also tried the new typing for template literals in TS 2.9 but as @mvestergaard wrote above this breaks syntax highlighting in vs code. Is there any other solution to fix this?

**Comment by Ailrun** [comment]
If syntax breaking is the biggest issue, I will check the highlighting package and send a PR for updating.
Is what you guys use `vscode-styled-component`?

**Comment by mvestergaard** [comment]
It isn’t the main problem. It just makes the workaround less viable.
lør. 16. jun. 2018 kl. 16.58 skrev Junyoung Clare Jang <
notifications@github.com>:

**Comment by Ailrun** [comment]
@mvestergaard Oh, sorry. I know your biggest problem is adding type parameter itself.
Who I want to ask about it was @partykkarny. It's my fault in my wording. Sorry for confusion.

**Comment by patrykkarny** [comment]
@Ailrun yep, I'm using `vscode-styled-component`, the spike of it I need to change types in almost 200 components in my codebase

**Comment by Ailrun** [comment]
@patrykkarny OK. I agreed with you that's not small change.
However, I just now notice that your problem is different from what @mvestergaard says, since what you say about is 'Emotion typings change its type parameter structure!', and what he says is 'Emotion typings now cannot infer a type parameter from its arguments!'.
Those are completely different problem in terms of typings... Could you open a new issue?

**Comment by patrykkarny** [comment]
@Ailrun your right I will open another issue for this tomorrow because it's late here

**Comment by Ailrun** [comment]
@patrykkarny However, I believe that your problem is also resolved with #722.
I know that PR is now somewhat mixed... but those changes affect each other :(

**Comment by patrykkarny** [comment]
@Ailrun [#722](https://github.com/emotion-js/emotion/pull/722) should fix my incompatibility issue :) so should I wait until this PR will be merged or create another issue as you suggested? :)

**Comment by Ailrun** [comment]
Please wait, what I said is my mistake. I thought I can resolve both things separately.

**Comment by patrykkarny** [comment]
It's ok :) Thanks for your work and quick answers 👍
