### ISSUE TITLE
autoLabel doesn't work for styles assigned to component's static properties

### ISSUE THREAD

**Issue by rskopal** [emotion-js/emotion#727]
- `emotion` version: 9.2.3
- `react` version: 16.4.0
- `TypeScript`, `babel-plugin-emotion`

If I assign class name created by css() function or component created by styled() function to React component's static properties, the auto labels are not generated for them. For example for this MyEditor component:
```
class MyEditor extends React.Component {
render() {
  const E = MyEditor;
  return (
    <E.Container>
     <div className={E.itemCss} />
    </E.Container>)
}

static Container = styled.div({
    display: "flex",
    flexDirection: "column"
    justifyContent: "center",
})

static itemCss = css({
    flex: "1 1 auto",
})
}
```
no label is appended to the itemCss class name and some internal name is appended to the Container component's class name (eg `<div class="css-h5haei ebf56m67"></div>`). It would be great if the labels were set to the respective static properties names.

The autoLabel option is set to true in my .babelrc config and the auto labeling works well in other cases.

**Comment by mherodev** [comment]
I expect this issue is related to the issue I just created: https://github.com/emotion-js/emotion/issues/728
