### ISSUE TITLE
Preferred way of writing component styles

### ISSUE THREAD

**Issue by TejasQ** [emotion-js/emotion#732]
This isn't a technical issue as much as a convention issue. My team and I are currently discussing a way that we'd like to write component styles.

Currently, emotion supports two styles: template literals and object expressions.

Is one recommended over the other? What are the drawbacks/strengths of each? Should we add a docs page with this info? Should we conventionalize a style?

**Comment by Andarist** [comment]
IMHO there is no much difference between those 2. Just go with the one you prefer. Our team tends to use template literals for static parts and we return objects from our interpolated functions.

**Comment by nitin42** [comment]
Agree with @Andarist here! Can close this issue now.
