### ISSUE TITLE
Enzyme .text() selector fails on emotion styled components

### ISSUE THREAD

**Issue by tennisgent** [emotion-js/emotion#733]
- `emotion` version: 9.2.3
- `react` version: 16.3.2

Relevant code.

```javascript
const AppContainer = styled('div')`
  font-family: sans-serif;
  text-align: center;
`;

function App() {
  return <AppContainer>Hello CodeSandbox</AppContainer>;
}

test("should contain proper text", () => {
  const wrapper = shallow(<App />);
  expect(wrapper.text()).toEqual("Hello CodeSandbox");
});
```

What you did:

I am trying to test that a given emotion styled-component has the proper text as children using Enzyme. I have written the above test and it fails with the error message below:

What happened:
```
Expected value to equal:
  "Hello CodeSandbox"
Received:
  "<Styled(div) />"
```

Reproduction:
Here is the error in CodeSandbox: https://codesandbox.io/s/5zkq790j74

Interestingly, if I call `wrapper.debug()`, it seems to output the proper markup:

```javascript
test("should contain proper text", () => {
  const wrapper = shallow(<App />);
  console.log(wrapper.debug());
  expect(wrapper.text()).toEqual("Hello CodeSandbox");
});

// Outputs:
// <Styled(div)>
//   Hello CodeSandbox
// </Styled(div)> 
```

**Comment by Ailrun** [comment]
Thank you for your report!
However, even without `styled` component, you example doesn't work.
You can check it via following code.
``` jsx
export function App() {
  return <div>Hello CodeSandbox</div>;
}

const wrapper = shallow(<App />);
console.log(wrapper.text());
```

**Comment by tennisgent** [comment]
Sorry. That example was probably a little too simplistic. This example I think better illustrates the issue: 

CodeSandbox #2: https://codesandbox.io/s/qkl68mk86w

**Comment by Ailrun** [comment]
@tennisgent If you introduce new component like
```
export function X({ className, children }) {
  return (
    <div className={className}>{children}</div>
  )
}

export function Simple() {
  return (
    <div className="container">
      Hello CodeSandbox
      <X className="nested">Blue</X>
    </div>
  );
}
```
You will see that both tests fail. It's what enzyme does, not we do.... Sorry for that, but there is nothing much we can do.

**Comment by tennisgent** [comment]
Sorry for the confusion. I apparently didn't understand how Enzyme is handling custom components. Thanks for setting me straight. 👍
