### ISSUE TITLE
Typescript: type error when styling material-ui components

### ISSUE THREAD

**Issue by stefanoferretti** [emotion-js/emotion#736]
- `emotion` version: 9.2.3
- `react` version: 16.4.1
- `material-ui` version: 1.2.2

Relevant code.

```javascript
import Button from '@material-ui/core/Button'

styled(Button)({})
```

What you did:
When styled argument is a material-ui component there's a typing error

Problem description:
Material-ui component are declared as React.ComponentType
In create-emotion-styled/types/react.d.ts, interface CreateStyledFunction has no match for the ComponentType

Suggested solution:
Add match for ComponentType in CreateStyledFunction interface

**Comment by Ailrun** [comment]
Thank you for reporting the issue!
That's really weird typing... why did they hide their component type? However, I will add those type to work in some other cases.

**Comment by stefanoferretti** [comment]
I agree with you, I don’t know why they choose such a type for their components.

Anyway, thank you for your help
