### ISSUE TITLE
Reusable emotion css in separate files

### ISSUE THREAD

**Issue by goldenshun** [emotion-js/emotion#745]
- `emotion` version: 9.2.3
- `react` version: 16.4.1

I have some reusable emotion files in my project.  They are structured like this:
```javascript
// margin.js
import { css } from 'emotion';
export const m0 = css`margin: 0 !important;`;
export const m8 = css`margin: 0.8rem !important;`;
...
etc.
```

Then I am using this in my components like so:

```javascript
import { m0 } from './margin';

const MyComponent = () => (
  <div className={m0}>This has no margins</div>
);
```

What you did:

I am also using `emotion-server` and `extractCritical` to pull out generated styles on the server and pass those back to the client.  And then use emotion's `hydrate` to let emotion know that it doesn't need to regenerate those styles.

What happened:

This results in duplicate CSS being injected.

![screen shot 2018-06-27 at 4 41 25 pm](https://user-images.githubusercontent.com/2985457/42003490-fde3cd46-7a28-11e8-8aa8-d3222d07c628.png)

Problem description:

This is a problem because sometimes, but not all the time, styles are being regenerated when they don't need to be.

The problem is the order of operations.  The `css` calls are happening before the `hydrate` and its unpredictable because it all depends on the order in which the modules are imported.

Suggested solution:

I don't think this is a problem with emotion specifically.  I think the best solution for me is to change my exports to return functions instead of the class generated by emotion so my margin.js file would change to:

```javascript
// margin.js
import { css } from 'emotion';
export const m0 = () => css`margin: 0 !important;`;
export const m8 = () => css`margin: 0.8rem !important;`;
...
etc.
```

Then I would use this in my components like so:

```javascript
import { m0 } from './margin';

const MyComponent = () => (
  <div className={m0()}>This has no margins</div>
);
```

It just seems like it would be inefficient to call that function on every render, especially if I compose some of these with `cx`:

```javascript
<div className={cx(flex(), itemsCenter(), justifyCenter())}>
```

Most of the examples in emotion's docs show the `css` declarations inline in the render function so I'm wondering if there are better ways to keep reusable emotion styles in separate files in a predictable and efficient way.

**Comment by mitchellhamilton** [comment]
You can fix this by moving the hydrate call to a separate file and making sure it’s the first import in your app

**Comment by goldenshun** [comment]
Ok, I will try to find a way to do that.  It just seemed like a potential anti-pattern to rely so much on the order of `imports/exports` to get the desired behavior.  Thanks for taking a look!
