### ISSUE TITLE
Enhance typings for ClassNameArg in cx

### ISSUE THREAD

**Issue by tomshane** [emotion-js/emotion#746]
- `emotion` version: 9.2.4
- `react` version: 16.4.1

Relevant code.

```javascript
const trueBool = true;
const undefBool: boolean | undefined;
const text = "hello";
const emptyText: string | undefined;
const customType: "value1" | "value2" | "value3" | undefined = "value1";

const classes = cx(
  { "cls1": trueBool },           // works
  { "cls2": undefBool },          // doesn't work, should ignore the class
  { "cls3": text },               // doesn't work, should apply the class
  { "cls4": emptyText }           // doesn't work, should ignore the class
  { "cls5": customType }          // doesn't work, should apply the class
);
``` 

Problem description:

Please note, _"doesn't work_" actually doesn't mean it is not working in run-time, just TS displays error, because of types definition. In run-time everything seems to work as expected.

The problem is in `ClassNameArg` type, where the "object" part is defined as` { [key: string]: boolean }`.

Suggested solution:

The easiest solution probably would be to change typing to ` { [key: string]: any }`, but I'm not sure everyone would be fine with it.

**Comment by Ailrun** [comment]
@tomshane Thank you for reporting this! Introducing `any` always comes with worries, but for this case, IMO, `{ [key: string]: any }` looks like the correct type.
Could you make a PR for this?

**Comment by tomshane** [comment]
I'm sorry, I don't have git environment up and running on my current machine. I could do it when I'm back from holiday, though.

**Comment by Kovensky** [comment]
At least DefinitedlyTyped generally prefers to keep `boolean` for things that semantically are boolean even though other falsy values are accepted for falsehood. Your code can be fixed by just prefixing your non-boolean value with `!!`.
