### ISSUE TITLE
[primitives] Failed to parse declaration margin or padding

### ISSUE THREAD

**Issue by brunolemos** [emotion-js/emotion#752]
Congrats on launching Emotion Primitives 🎉

It worked great on my very basic tests, but not with some styles like `margin` or `padding`.
Specific margin like `margin-bottom` works.

- `@emotion/primitives` version: ^9.2.5
- `react` version: 16.4.1
- `react-native` version: 0.56.0

<div>
<img width="330" src="https://user-images.githubusercontent.com/619186/42404145-2d0fa276-815d-11e8-9cd2-ebc947780b5b.png" />
<img width="330" src="https://user-images.githubusercontent.com/619186/42404183-8091e35a-815d-11e8-8fab-6e5c0af3d128.png" />
</div>

```javascript
import React, { PureComponent } from 'react'

import styled from '@emotion/primitives'

const Container = styled.View`
  flex: 1;
  justify-content: center;
  align-items: center;
  background-color: #f5fcff;
`

const Title = styled.Text`
  font-size: 20;
  text-align: center;
  margin: 10; // <- Issue here. margin-bottom works.
  color: hotpink;
`

const Description = styled.Text`
  text-align: center;
  color: #333333;
  margin-bottom: 5;
`

export default class App extends PureComponent {
  render() {
    return (
      <Container>
        <Title>Welcome to Emotion Primitives</Title>
        <Description>Style and render primitives across targets.</Description>
      </Container>
    )
  }
}
```

**Comment by mitchellhamilton** [comment]
Emotion primitives uses [styled-components/css-to-react-native](https://github.com/styled-components/css-to-react-native) which requires units for shorthands so if you make it `margin: 10px;`, it'll work.

There's some discussion about this in this issue, https://github.com/styled-components/css-to-react-native/issues/40.

It seems like the behavior shouldn't change but I definitely think that having a better error here that tells you what to do would be great here.

**Comment by brunolemos** [comment]
Makes sense. 
Yeah, very inconsistent behavior to have `margin-bottom: 10` working and `margin: 10` failing.

**Comment by nitin42** [comment]
Agree with @mitchellhamilton. We can guide a user with a better error message or something. Let me see what I can do 😄

**Comment by nitin42** [comment]
@brunolemos see #841
