### ISSUE TITLE
Getting descriptive CSS class names on all components?

### ISSUE THREAD

**Issue by johnmcdowall** [emotion-js/emotion#756]
I've enabled the `autoLabel` feature and I'm getting nice descriptive CSS class names generated when I use `css`, as per the documentation. 

Other components, or components from Rebass are still generated with base64 style random class names. Why is this? Is there any way to get descriptive class names for all components in development mode?

In the screenshot below, all of the war-garbled class names are actual Rebass `Row` components - I would expect them to have class names along the lines of `Row css-112h9ht`. Since emotion is able to generate a class name in the first place, it seems odd that it doesn't use the Display name in that process when using `autoLabel`. 

![screen shot 2018-07-08 at 4 28 04 pm](https://user-images.githubusercontent.com/237175/42425064-ecc028e2-82cb-11e8-814e-173c1e37e75a.jpg)

**Comment by Andarist** [comment]
From what I remember `autoLabel` is generates those readable classes at build time - would be harder to read `.displayName` for 3rd party components. Anyhow - algorithm certainly could be improved if possible, but you would have to share a code sample of those components which didnt get their readable names.

**Comment by johnmcdowall** [comment]
@Andarist Rebass has dozens of components in it, but here's one and they're all pretty much the same: https://github.com/jxnblk/rebass/blob/master/src/Button.js. The `DisplayName` is definitely set in the source. 

One thing I noticed is that Rebass achieved `emotion` support via a simple Babel `transform-rename-import` pass: https://github.com/jxnblk/rebass/blob/master/.babelrc#L11-L26 I don't know if that would affect the `autoLabel` but it seems to be just doing a simple rename operation.

**Comment by tkh44** [comment]
I would need to see how you coded to give you a definite answer but the fact is we can't see or infer all that much during compile time. We use a variable name if available or the name of the component being rendered in if we can't find anything else. We do not have access to the internal code structure for 3rd party components or even components you create yourself for that matter. We can only see what is in the code at the moment of compilation.

**Comment by tkh44** [comment]
Just to be clear, in order to read a displayName from a component at compile time we would need to import the component, evaluate the code, and then check its displayName. With a library like rebass there are several layers of abstraction between when the style is defined and when it used. The className that emotion creates is not generated in the same code it is being used in so we do not have any additional context to add a label.

**Comment by tkh44** [comment]
I'm going to close this issue because there is nothing we can do for it at the moment. Feel free to expand on the `autoLabel` feature and put in a PR. 

https://github.com/emotion-js/emotion/blob/master/packages/babel-plugin-emotion/src/babel-utils.js#L86 is a good starting point.

**Comment by Andarist** [comment]
What could be done though is compiling `rebass/emotion` with `autoLabel` option. Optionally they could expose dev build with it and prod one without.

**Comment by johnmcdowall** [comment]
@tkh44 Thanks for the detailed explanation, I'll look into the `label` approach.

**Comment by fandy** [comment]
Any updates on this? Would make development a lot easier with descriptive names.

**Comment by elie222** [comment]
This may help:
https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion

> Generated class names include the name of the variable or component they were defined in.

**Comment by baddox** [comment]
Hello. I know this issue is closed and hasn't been active for a while, but I just came across the problem with Rebass and I worked up a minimal example with create-react-app if that might help anyone troubleshoot: https://github.com/baddox/rebass-emotion-autolabel

I explained a bit more in this comment: https://github.com/rebassjs/rebass/issues/434#issuecomment-606805872

**Comment by conatus** [comment]
Hi all. We aren't using Emotion directly, but indirectly through `theme-ui`.

How do we set the `autoLabel` to be true, so we can have this being the case at build time?

**Comment by Andarist** [comment]
You could try to leverage `importMap` option: https://github.com/emotion-js/emotion/tree/f36b946b4b1d465ff399cbe4dc518aa2e34501ac/packages/babel-plugin#importmap

**Comment by conatus** [comment]
@Andarist 

Thanks! So what am I doing here? Adding `theme-ui` as one of these, then what?

```json
{
  "theme-ui": {
    "?????": {
      "????": ["@emotion/react", "autoLabel as an option somewhere in here?"]
    }
  }
}
```

Thanks so much!

**Comment by Andarist** [comment]
@conatus I've taken a look at the `theme-ui` API right now and it seems it's sufficiently different from ours that this won't be possible. I thought that it's closer and that this could work - sorry for that.

**Comment by conatus** [comment]
@Andarist 

Thanks for that, really appreciated. My hope was that it, as it consumes Emotion as a dependency, would work. 

I guess I could fork it, modify Babel configuration within to make the change, then just use this temporary fork for a while? It would be a one line change to the configuration.

**Comment by Andarist** [comment]
It depends on what they do under the hood - I wont have time to check right now. I assume you are interacting with `theme-ui` mainly through their `sx` prop? If yes - try to add a label property manually to the object passed to that prop and check if the label has been applied to the generated class name

**Comment by conatus** [comment]
Thanks @Andarist - I will check that out and see how it goes. Really appreciate you taking the time to take a look for me.

**Comment by hasparus** [comment]
@conatus Theme UI passes `label` along to Emotion's CSS, so you can add it manually, but we don't add it automatically (and Emotion's plugin won't do it too, because it doesn't know about `sx` prop).

This is something to do on Theme UI's side.

**Comment by Andarist** [comment]
It could be checked how do we handle adding labels for cases like this:
```js
;<div css={{ color: 'hotpink' }}/>
var identifier = { color: 'hotpink' }
;<div css={identifier}/>
```
If it works OK then maybe we could add an option to configure the "css prop name" - although we'd have to recheck what else would be influenced by this and I'm worried that this might have too quirky consequences.
