### ISSUE TITLE
How to use jest-emotion with Emotion 9.1.3

### ISSUE THREAD

**Issue by cherihung** [emotion-js/emotion#758]
- `emotion` version: 9.1.2
- `react` version: 16.3.1
- `typescript` version: 2.8.1

I am recently starting to work on a typescript react project using Emotion. Due to a constraint on an internal dependency, I can't use the new 9.2+ version. I tried to use `jest-emotion` and follow the README's instruction. 

In setupTests.ts, I added:
```javascript
expect.addSnapshotSerializer(createSerializer(emotion));
```
But then I see this Typescript error `Property 'merge' is missing in type 'typeof import(".../node_modules/emotion/types/index")'.`

After checking the type definition, Emotion 9.1.2 type file indeed doesn't have the `merge` property that jest-emotion's createSerializer expects (as defined by create-emotion). 

I am not able to find a previous version of `jest-emotion` that'd work with the older version of Emotion.
So my question is - should `jest-emotion` work with Emotion 9.1.2? Or is it a new feature only for 9.2.+? 

If that's the case, what's the suggestion to do snapshot testing? 

Thank you!

**Comment by mitchellhamilton** [comment]
Does `jest-emotion@9.1.2` not work?

**Comment by cherihung** [comment]
omg. I swear I reinstalled node modules multiple times to point all to 9.1.2 including `jest-emotion`. and the error was still persisting. :( 
well, it works now that I reinstalled everything once again. Thanks for answering.
