### ISSUE TITLE
createEmotion does not allow key to be emoji, despite the docs suggesting it

### ISSUE THREAD

**Issue by Kovensky** [emotion-js/emotion#761]
- `emotion` version: 9.2.5
- `react` version: 10.4.1

Relevant code.

```javascript
import createEmotion from 'create-emotion'
createEmotion({}, { key: '👩‍🎤' })
```

# What you did:

Tried out a suggestion in the docs to use a custom key (https://emotion.sh/docs/create-emotion)

# What happened:

`Emotion key must only contain lower case alphabetical characters and - but "👩‍🎤" was passed`

# Reproduction:

https://codesandbox.io/s/v6k3plv1w0

# Problem description:

Either misleading docs or overly restrictive validation.

# Suggested solution:

More relaxed validation.

---

That particular emoji is probably a bad idea to use anyway as at least Chrome will display it as`🙍‍♀️&zwj;🎤` instead, but I just wanted to see what happened.

**Comment by Andarist** [comment]
[test in the code](https://github.com/emotion-js/emotion/blob/a1b9a30ffdda27ac1915117142644898f4960eb4/packages/create-emotion/src/index.js#L73)

Not sure if we should really validate this - maybe only against it being a string? If one wants to use some other string from some reason he/she should be able to do it.

**Comment by Kovensky** [comment]
I assume it was added to guard against invalid css (e.g. having a `:` or whitespace, which would break the selector)

**Comment by Andarist** [comment]
Sure, but it increases complexity in the code and decreases actual correctness. One shouldn't use invalid className characters there, not sure if it's our responsibility to try to validate it.
