### ISSUE TITLE
babel-plugin-emotion imports css multiple times

### ISSUE THREAD

**Issue by aaronjensen** [emotion-js/emotion#762]
- `emotion` version: 9.2.5
- `react` version: 16.3.2
- `babel` version: 7.0.0-beta.53

Relevant code.

```jsx
import React from 'react'

const baz = { color: 'red' }
;<div css={baz} />
;<div css={baz} />
;<div css={baz} />
```

```json
{
  "presets": ["@babel/preset-react"],
  "plugins": [
    "emotion"
  ]
}
```

What you did:

Ran babel

What happened:

This was emitted, importing emotion multiple times. Furthermore, when doing something similar and running it in the browser, I end up with a different css class name for each div, which is unexpected.

```
import { css as _css3 } from "emotion";
import { css as _css2 } from "emotion";
import { css as _css } from "emotion";
import React from 'react';
const baz = {
  color: 'red'
};
React.createElement("div", {
  className: _css(baz)
});
React.createElement("div", {
  className: _css2(baz)
});
React.createElement("div", {
  className: _css3(baz)
});
```

I'll create a github to repro if this isn't the expected behavior. It's possible that webpack will merge the extra imports, but it seems odd. The different css class for each div when actually using a pattern like this in a real app caused problems for us.

One related question is, is there a perf benefit to avoiding invoking `css(...)` at eval time in modules? In other words, would it be better in the example above to just call `css` myself once and pass the generated className to each div? (yes, this is a contrived example).

**Comment by Andarist** [comment]
> I'll create a github to repro if this isn't the expected behavior.

Would help a lot to have it reproduced in separate repo 👍 

> It's possible that webpack will merge the extra imports, but it seems odd. 

Not sure about webpack - in general it should be possible bo merge those, but I don't know if webpack does it - I think it should at least when using ModuleConcatenationPlugin (on by default in prod mode in webpack@4). 

> The different css class for each div when actually using a pattern like this in a real app caused problems for us.

This is weird - all those calls should yield the same class name, subsequent calls should just retrieve generated stuff from the cache.

> One related question is, is there a perf benefit to avoiding invoking css(...) at eval time in modules?

Not sure - I guess it depends. There is obviously some cost because it has to calculate stuff, it should be negligible in most cases. For initialization perf gains you might want to explore extract critical css strategies.

**Comment by aaronjensen** [comment]
Does invoking css write the style rules to the dom at that time?

And yeah, the biggest thing we can do for init is code splitting, which kinda gives you critical css as well for an spa

**Comment by Andarist** [comment]
> Does invoking css write the style rules to the dom at that time?

If it's the first call with certain rules - subsequent calls just reads from the cache (if possible).

> And yeah, the biggest thing we can do for init is code splitting, which kinda gives you critical css as well for an spa

Not exactly, even with code splitting those critical css has to be assembled in runtime - you could setup critical extraction that would create them at build time. However in many cases code-splitting might be "just enough". Do not optimize prematurely 😉

**Comment by aaronjensen** [comment]
> If it's the first call with certain rules - subsequent calls just reads from the cache (if possible).

Yeah, it's the first call I was concerned with. Ok, I understand this better, thanks.

I tried to build a repro and found a few things:

1. `@babel/preset-env` combines the redundant imports and webpack combines them if `@babel/preset-env` has `modules: false` set, so this is probably a non-issue. The intermediate output looks funny, but it's probably not a real issue in practice.

2. I can't reproduce the css names being different at the moment, so I'll keep an eye out for it in my project and report with a repro if I see it again.

I'll close this out, thanks!

**Comment by Andarist** [comment]
IMHO we still could improve intermediate output, would you like to reopen this or create a new issue about it? Repro would also allow me to fix this faster if you could provide one.

**Comment by aaronjensen** [comment]
Sounds good, here's the repro. You can ignore the webpack stuff, that was to attempt to repro the other issue.

https://github.com/aaronjensen/emotion-repro

**Comment by tkh44** [comment]
This specific issue aside, I would consider making the css call one time up top and using the resulting className throughout the component. This would keep the number of calls to `css` down and the resulting styles can still be used to compose new styles.

```javascript
const styles = {
  redBorder: css({ border: '1px solid red' }),
  redText: css({ color: 'red' }),
  whiteText: css({ color: 'white' }),
  largeText: css({ fontSize: '2em'})
}

function Warning(props) {
  return (
     <div className={redBorder}>
       <span className={css(redText, largeText)}>Danger</span>
       <div className={css({ background: 'red' }, whiteText)>{props.children}</div>
    </div>
}
```

This is contrived but it illustrates that you can use predefined styles to create new, composed styles from existing ones.

**Comment by aaronjensen** [comment]
@tkh44 Ok, that's interesting that you suggest that. See above--I had concerns about initial eval time (we're not code splitting yet) so I didn't want a ton of top level `css` calls slowing down initial render time for things that aren't rendered yet, but if the perf is negligible it was a case of premature optimization...

**Comment by tkh44** [comment]
The overhead for css`` function calls like this is not very much in the relative scale of a React app. Of all the stuff that is being evaluated on startup, these `css` calls will be minimal. When using React emotion these calls are made on every render of a styled component. Worrying about these calls and how they relate to code splitting should be pretty far down your list as far as optimizations go 😄

**Comment by Andarist** [comment]
Also - the original example could be optimized by our babel plugin to output a single `css` call and inline its result as `className` as we know that `baz` is "pure", can be safely hoisted, and thus `css` call can be hoisted too.
