### ISSUE TITLE
Clean way to export a styled component w/o styles (for selector targeting)

### ISSUE THREAD

**Issue by erquhart** [emotion-js/emotion#766]
If I have a component that is not styled, but would like to target it from a parent styled component, I need to convert it to an emotion styled component by passing an empty string literal to the tag, which is fine, but looks like a hack.

Example:

```js
import React from 'react'
import styled from 'react-emotion'
import Component from 'some-lib'

const MyComponent = () => <Component>{/* pretend there's stuff here */}</Component>

export default styled(MyComponent)``
```

And then elsewhere I can do:

```js
styled(SomeWrapper)`
  ${MyComponent} {
    /* ... */
  }
`
```

Is there another way?

**Comment by Andarist** [comment]
You can also use call syntax - `export default styled(MyComponent)()` which might look less like a hack :P

Not sure what your use case is, how would u like to style `MyComponent` with this approach is it is not a styled component? I mean - after conversion it is styled, but I got an impression that you wanted to have non-styled component targeted by other emotion-styled component.

**Comment by tkh44** [comment]
Its just CSS so you can add a class name or any other selector (attribute, id, etc) and select on it. Using your example above.

```js
import React from 'react'
import styled from 'react-emotion'
import Component from 'some-lib'

const MyComponent = () => <Component className="my-component">{/* pretend there's stuff here */}</Component>

export default styled(MyComponent)``
```

```js
styled(SomeWrapper)`
  & .my-component {
    /* ... */
  }
`
```
