### ISSUE TITLE
Simple object check in Theme provider fails for es modules.

### ISSUE THREAD

**Issue by roguezedd** [emotion-js/emotion#769]
A theme defined in an es module fails the simple object check. Simple object check looks to match [object Object] when an es module theme object toString returns [object Module].
https://github.com/emotion-js/emotion/blob/b0758ffebc5703ecba10f073718aca0a277ec2f6/packages/emotion-theming/src/theme-provider.js#L10

**Comment by gombek** [comment]
Hey, I can do that as my first contribution.

**Comment by roguezedd** [comment]
I created a branch. I cannot seem to push the branch. I'm getting permission denied.

**Comment by Andarist** [comment]
@roguezedd You have to fork this repository, push to your fork & create a pull request

**Comment by gombek** [comment]
@Andarist I also worked on this a bit, but I didn't found convenient way of testing this. @roguezedd can you post here some code example?

**Comment by Andarist** [comment]
This check has been already relaxed in emotion@10 and this no longer should be an issue. Sorry that we couldn't get to it sooner. Thank you for your understanding.
