### ISSUE TITLE
[docs] Prerendering issues - advise disabling speedy

### ISSUE THREAD

**Issue by Andarist** [emotion-js/emotion#776]
@andrewdelprete had an issue with this ([thread](https://twitter.com/AndrewDelPrete/status/1022180246391382016)) and reached out for help, seems like we could include a note about this in some caveats/faq section - if having problems then solution is to disable speedy and ensure that happens before creating any styles (due to import hoisting it might be required to move that to other file)

**Comment by oleblaesing** [comment]
I hope this will solve the problem for all puppeteer users. :)

**Comment by Andarist** [comment]
I think it should be closed as #779 got merged in. Thanks @oleblaesing !
