### ISSUE TITLE
jest-emotion snapshots don't include injectGlobal styles (anymore)

### ISSUE THREAD

**Issue by jopdeklein** [emotion-js/emotion#784]
- `emotion` version: 9.2.6
- `jest-emotion` version: 9.2.6
- `react` version: 16.4.1

The following code printed the injected global styles in the snapshots in jest-emotion (and emotion) 9.1.3, but in version 9.2.6 the global styles get removed. 

```javascript
describe('Jest Emotion Inject Global', () => {
  it('Renders injectGlobal in the snapshots', () => {
    expect.addSnapshotSerializer(createSerializer(emotion))

    const MyComponentThatInjectsGlobalStyles = () => {
      injectGlobal`
        .foo {
          color: red;
        }
      `

      return <div className="foo">bar</div>
    }

    const tree = renderer.create(<MyComponentThatInjectsGlobalStyles />).toJSON()
    expect(tree).toMatchSnapshot()
  })
})
```

I am not sure if this is by design or not, but having the global styles in the snapshot was a nice way to determine whether you regressed in expected injected global styles.

Reproduction:
Running the above code, if I compare the snapshot generated with jest-emotion 9.1.3 against one generated with 9.2.6, I get:

```
  ● Jest Emotion Inject Global › Renders injectGlobal in the snapshots

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    - .foo {
    -   color: red;
    - }
```

The emotion version doesn't have any impact on the snapshots and emotion 9.2.6 works fine in the browser, so I expect it to be isolated to jest-emotion.

**Comment by jopdeklein** [comment]
Could someone please indicate whether this was removed by design? If this is a regression, I can take a look at a possible fix.

**Comment by mitchellhamilton** [comment]
This wasn't intentionally removed though this behavior working in the first place wasn't intentional. `injectGlobal` shouldn't be used in the way it is in the example you provided. Could you give a real world example of why you would want this?

**Comment by mitchellhamilton** [comment]
A better pattern that would already work would be something like this where you apply a class with some child selectors that have the styles. Using injectGlobal means that you can't change the styles so you might as well have the injectGlobal call outside of the component since the styles are cached whereas applying a class means you can change the styles based on props and they'll be included in snapshots.

```jsx
import { css } from "emotion";

export let StyledThirdPartyComponent = props => (
  <div
    className={css`
      ...styles, probably with child selectors
    `}
  >
    <ThirdPartyComponent />
  </div>
);
```

**Comment by jopdeklein** [comment]
@mitchellhamilton OK that makes a lot of sense and will serve my purpose. I'll close the issue as resolved.
