### ISSUE TITLE
Nested styles causes toHaveStyleRule to fail (edited)

### ISSUE THREAD

**Issue by sampalmer-se** [emotion-js/emotion#791]
- `emotion` version: 9.2.6
- `react` version: 16.4.1

Relevant code.

```javascript
// SomeComponent.jsx
const SomeComponent = styled('div')`
  height: 16px;
  width: 16px;
  border-radius: 2px;
  &:hover {
    background-color: blue;
    z-index: 20;
  }
`;

// SomeComponent.test.jsx
test('testing render', () => {
    const {
      container: { firstChild },
    } = render(<SomeComponent/>);
    expect(firstChild).toHaveStyleRule('height', '16px');
    expect(firstChild).toHaveStyleRule('width', '16px');
    expect(firstChild).toHaveStyleRule('border-radius', '2px');
  });
```

What you did:
The element has a pseudo class which is triggered on hover. We have written a test to ensure the base styles (those not in the hover section) are applied by default.

What happened:
This works in the browser but the test fails. We're getting an error like this:
<SomeComponent /> testing render
Property not found, height

If I comment this line out, I get 
Property not found, width

Oddly, if I comment out the height and width checks, the border-radius check works.

Reproduction:
https://codesandbox.io/s/zl2rnw2k1x

Problem description:
N/A

Suggested solution:
N/A

## Edit

I've done some more research on this and this isn't only happening for pseudo classes but for nested styles as well. 
In the code sandbox, if you update SomeComponent to this then you can see the issue

```javascript
const SomeComponent = styled('div')`
  height: 16px;
  width: 16px;
  border-radius: 2px;
  background-color: pink;
  svg {
    z-index: 999;
  }
`;
```

**Comment by Glazy** [comment]
I also have a similar issue to @sampalmer-se. I am passing through a `css` block with a prop called `wrapperStyle` to a span and then I want to test that this span has the styles specified. The implementation works in Storybook but I get the same error as above!

**Comment by fnpen** [comment]
I have same issue.

**Comment by mitchellhamilton** [comment]
We'd happily accept a PR to fix this!!

**Comment by nvanselow** [comment]
I've started a pull request for this as we have run into a similar issue in some of the test we want to write. However, there are a lot of edge cases here that make it complex. So far, I have a relatively simple fix that makes it better (styles don't disappear on you), but could add its own problems. For example, in my draft PR, I've included a test that currently fails because the classes are still included even if the nested class is not on the element.

https://github.com/nvanselow/emotion/pull/1

**Comment by kevinSuttle** [comment]
+1 Would love to see this fixed, as it's preventing a whole slew of style rendering from being tested.

**Comment by kevinSuttle** [comment]
Anyone able to work around this?

**Comment by Andarist** [comment]
After upgrading the linked repro case to v10 (and still using vanilla emotion) - all 3 tests have passed, so the issue seems to be fixed.
