### ISSUE TITLE
Allow function-based style mapping using withProps

### ISSUE THREAD

**Issue by Gejsi** [emotion-js/emotion#792]
- `emotion` version: ^9.2.5
- `react` version: ^16.2.0

Relevant code.

```javascript
const Title = withProps({
  style: ({ big }) => ({
    fontSize: big ? '32px' : '18px'
  })
})(styled("h1") `
  color: green;
`);
```

What you did:
I created a simple component to test if props can be added inside the `withProps` HOC.

What happened:
React threw this error:
_The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX._
I changed my code to fix the error:
```javascript
const Title = withProps({
  style: { fontSize: ({ big }) => (big ? "32px" : "18px") }
})(styled("h1")`
  color: green;
`);
```
No error is thrown however the attribute `style` is not rendered.

Reproduction:
Simply write a function inside the `withProps` HOC.
https://codesandbox.io/s/k5vrzm19v5

Problem description:
The reproduction I provided is clearly useless in a normal environment because it is just a bunch of static styles. But you can not write dynamic styles in template literals otherwise you will end up generating too many classes.
Imagine moving a component depending on the mouse position, there are two ways of doing it: 

1. Set the attribute to the component: 
```javascript
<MyComponent style={{ left: mouseX + 'px' }} />
```
2. Set the attribute using the `withProps` HOC (best method)
 ```javascript
const MyComponent = withProps({
   style: { left: ({ mouseX }) => mouseX + 'px' }
})(styled('div')`
/** styles here */
`)
```

Suggested solution:
I do not really know how to fix this problem: the HOC itself works properly.

**Comment by Andarist** [comment]
Functions as style object values are not supported atm (should they? 🤔 cc @mitchellhamilton )

If they were u could do this:
```js
const getProp = prop => props => props[prop]

const Title = withProps({
  css: { fontSize: ({ big }) => (big ? "32px" : "18px") }
})(styled("h1")`
  color: green;
  ${getProp('css')}
`);
```

**Comment by mitchellhamilton** [comment]
tbh, I think we should stop recommending `withProps` all-together since it's just another thing to learn without any real benefit over [creating a regular react component with the css prop](https://github.com/emotion-js/emotion/pull/617#issuecomment-388284739). The example above could be expressed like so.
```jsx
let Title = ({ big, ...props }) => (
  <h1
    style={{
      fontSize: big ? 32 : 18
    }}
    css={css`
      color: hotpink;
    `}
    {...props}
  />
);

```
Though, this can be achieved with `withProps` by making the argument to `withProps` a function like this.
```jsx
const Title = withProps(({ big }) => ({
  style: {
    fontSize: big ? "32px" : "18px"
  }
}))(styled("h1")`
  color: green;
`);
```

**Comment by Andarist** [comment]
I also feel this `withProps` pattern is rather obscure and convoluted. 

My main takeaway from @Gejsi's case is that we allow for this:
```js
const Title = styled("h1")`
  font-size: ${({ big }) => (big ? "32px" : "18px")};
`;
```
but we dont allow for this:
```js
const Title = styled("h1")({
  fontSize: ({ big }) => (big ? "32px" : "18px")
})
```

While I wouldn't write latter myself, it seems that parity between string & object APIs should be maintained 🤔

**Comment by Gejsi** [comment]
Thanks for helping me. I totally understand that using `withProps` can become way too complex and that it is useful only in rare occasions. I think this issue should be closed because the problem @Andarist pointed out regards the core of emotion and not this particular case.

**Comment by bradennapier** [comment]
So I am moving from styled components.  One of the big reasons to use attrs as stated to me was around props that change often, like during animations, etc.  This was due to needing to change css every prop change so if I am animating something thousands of times and using stylesheets was extremely slow.  

Does the css prop not have this issue?

**Comment by Andarist** [comment]
Css prop is about generating class names so for very fast changing styles it’s not recommended to use it - you should keep using style prop for those.
