### ISSUE TITLE
Feature: Make styled components more composable by adding extend API

### ISSUE THREAD

**Issue by msfragala** [emotion-js/emotion#796]
Since using Emotion, I've run into a particular use case several times where it would be useful to extend styled components via an `extend` method — [similar to styled-components](https://www.styled-components.com/docs/basics#extending-styles). This API would look like this:
```js
import styled from 'react-emotion';

const Button = styled.button`
  background: transparent;
  border: 2px solid black;
  border-radius: 4px;
  color: black;
  font-size: 1rem;
  margin: 30px 0;
`;

const DangerButton = Button.extend`
  border: 2px solid red;
  color: red;
  font-size: 2rem;
`;
```

**I'm happy to submit a PR for this feature myself.** I just wanted to gauge interest and check whether this fits Emotion's roadmap (maybe it wasn't implemented for a reason) before doing the work. 🙂

**Comment by Andarist** [comment]
Not sure how styled-components' `.extend` works, but isnt this equivalent?
```js
import styled from 'react-emotion';

const Button = styled.button`
  background: transparent;
  border: 2px solid black;
  border-radius: 4px;
  color: black;
  font-size: 1rem;
  margin: 30px 0;
`;

const DangerButton = styled(Button)`
  border: 2px solid red;
  color: red;
  font-size: 2rem;
`;
```

**Comment by mitchellhamilton** [comment]
Also, [styled-components is planning to remove .extend](https://github.com/styled-components/styled-components/issues/1546)

**Comment by msfragala** [comment]
Oh no, that's sad to hear! That was a bit of API sugar I liked. 😢

In my head, there should have been slight implementational differences between how `styled(Button)` and `Button.extend` worked. But if similar libraries are moving away from that API, I'll trust it's for a good reason.

So I'm gonna close this issue.
