### ISSUE TITLE
Disable autoprefixing for snapshot tests?

### ISSUE THREAD

**Issue by elliotdickison** [emotion-js/emotion#798]
I recently migrated from glamor (vanilla, not *ous) to emotion and the process has been extremely smooth. The one wrinkle is snapshot testing. My snapshot tests are working with jest-emotion, but the output `.snap` files are significantly larger and harder to read than they were with glamor because they include tons of vendor prefixes. With glamor I could disable autoprefixing using the `glamor.plugins.remove` API for clean css in my snapshots. I can't figure out how to do this with emotion though, is it possible?

P.S. Apologies for opening an issue, I couldn't find any other support channel. Thanks for your help!

**Comment by elliotdickison** [comment]
UPDATE: I did find https://github.com/emotion-js/emotion/issues/400, but the `prefix: false` option of `create-emotion` isn't working. I'm using `css` from emotion `9.2.5` with objects (not string literals). Is there a possibility objects are processed differently and the `prefix` option doesn't affect them?

**Comment by elliotdickison** [comment]
Success 🎉🎊

For anyone else trying to turn off auto-prefixing in jest snapshots, here's how to do it:

1. You can't turn off auto-prefixing on the out-of-the-box emotion instance. As I discovered from #400  you can only disable prefixing via configuration when emotion is instantiated, so you need to create your own instance. To do that use [create-emotion](https://github.com/emotion-js/emotion/tree/master/packages/create-emotion):

```javascript
// no-prefix-emotion.js
const createEmotion = require("create-emotion")

const context = typeof global !== "undefined" ? global : {}

module.exports = createEmotion(context, { prefix: false })
```

2. Next you need to make sure that all of your modules use this new instance of emotion during snapshot testing. You're probably importing the out-of-the-box instance from `"emotion"` everywhere, so the easiest way to switch to the new instance is by aliasing `"emotion"` via webpack or babel. I used `babel-plugin-module-resolver` in the babel config that I pass to `babel-jest`:

```javascript
// babel.config.js
module.exports = {
  // ...
  plugins: [
    [
      "babel-plugin-module-resolver",
      {
        alias: {
          emotion: path.resolve("./no-prefix-emotion.js"),
        },
      },
    ]
  ],
}
```

3. The last step is to add a custom snapshot serializer to jest. You can't use the default serializer from `jest-emotion/serializer` because that would pull in the out-of-the-box instance of emotion (and you wouldn't get any styles in your snapshot files). Instead you can use `createSerializer` from `jest-emotion` to create your own serializer with the new instance of emotion:

```javascript
// no-prefix-emotion-serializer.js
const { createSerializer } = require("jest-emotion")
const emotion = require("./no-prefix-emotion")

module.exports = createSerializer(emotion)
```

and then plug the serializer into your jest config:

```javascript
// jest.config.js
module.exports = {
    // ...
    snapshotSerializers: [path.resolve("./no-prefix-emotion-serializer")],
}
```

**Comment by stephenh** [comment]
For anyone coming across this now/in emotion 10, I'm ~80% sure the above no longer works (because the `emotion` module is now various `emotion/core`/etc. modules), and `create-emotion` itself seems deprecated-ish:

https://github.com/emotion-js/emotion/issues/1082#issuecomment-546298028

So the best/easiest way to do this is to wrap every `render` you do in a test suite with a `CacheProvider` with prefix set to false:

https://emotion.sh/docs/cache-provider

**Comment by Andarist** [comment]
> So the best/easiest way to do this is to wrap every render you do in a test suite with a CacheProvider with prefix set to false:

Yes, this is the current way of doing this - keep in mind that you can create a helper for rendering, no need to sprinkle `CacheProvider` in the plain sight everywhere 😉

**Comment by stephenh** [comment]
> keep in mind that you can create a helper for rendering

Yep! Just a few lines in our `setupTests.js` (adding the `CacheProvider` to a `globalWrappers`/`globalProviders` list of "use these providers for all `render`s that our `render` helper checks). :-)

**Comment by damusnet** [comment]
@stephenh Hi, would you mind sharing your Jest configuration to wrap every test in this Emotion cache provider? I'm at a loss as to how to do that! Cheers

**Comment by stephenh** [comment]
@damusnet it's somewhat project specific, but this line:

```
// Skip browser prefixes for snapshot tests
const emotionCache = createCache({ prefix: false });
globalWrappers.push({ wrap: c => <CacheProvider value={emotionCache}>{c}</CacheProvider> });
```

Where `globalWrappers` is used by our project-specific `render` that wraps react-testing-library's render, vaguely copy/pasted it looks like:

```typescript
export async function render(
  component: React.ReactElement,
  ...wrappers: Wrapper[]
): Promise<RenderResult> {
  const wrapped = wrap([...globalWrappers, ...wrappers], component);
  const result = rtlRender(wrapped);
  ...other project things...
  return result;
}

function wrap(wrappers: Wrapper[], component: ReactElement): ReactElement {
  return wrappers.reduce((current, wrapper) => wrapper.wrap(current), component);
}
```

**Comment by damusnet** [comment]
Hi @stephenh ; thank you very much for getting back to me so quickly!

Unfortunately, as I later suspected, this is specific to `react-testing-library`, whereas my project uses only `react-test-renderer`. Oh well, until/unless Emotion adds an easier option to disable prefixes, I guess we'll keep them in our snapshots!

**Comment by stephenh** [comment]
@damusnet I don't use `react-test-renderer`, but:

```
const testRenderer = TestRenderer.create(
  <CacheProvider value={emotionCache}>
    <MyComponent />
  </CacheProvider>
); 
```

I.e. if you look past all of the `wrap`/etc. stuff, you just to wrap your component with a `CacheProvider`, which is super-simple to do.

**Comment by damusnet** [comment]
@stephenh well, yeah, but then we'd have to do it in every single test, no?

(we currently have 293 `TestRenderer.create` across 114 files)

Doesn't seem worth the cost unless we can find a way to do a global setup. There's probably something that can be done with a `babel` plugin or something, but it also seems more trouble than is worth.
