### ISSUE TITLE
Typescript ThemeProvider + Props

### ISSUE THREAD

**Issue by dubcanada** [emotion-js/emotion#802]
Hello,

Does anyone know of a way to use TypeScript with ThemeProvider & Props?

I have a ThemeProvider like

```
export default {
  color: {
    blue: 'blue'
  }
}
```

And then I have a component

```
type Props = {
  outline?: boolean;
  theme?: any;
}

const Button = styled('button')((props: Props) => ({
   color: props.theme.color.blue,
   background: props.outline ? '#fff' : props.theme.color.blue
})
```

And this works but obviously `theme?: any;` won't have any typescript benefits. Is there a way to combine custom properties and the passed in themeprovider props?

I've been through https://emotion.sh/docs/typescript and none of those are what I want to do.

**Comment by Ailrun** [comment]
Following will help you.
https://emotion.sh/docs/typescript#define-a-theme
However, to use custom props, you should pass generic parameter instead of annotate type to function argument.
```ts
styled('button')<Props>((props) => /*...*/)
```
```

**Comment by cmwhiting** [comment]
In addition to the comment by @Ailrun, you can do something like

`type StyledProps<T = {}> = React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement> & Partial<T>, HTMLDivElement>;`

and

```
interface MyComponentProps {
    myprop: 'blue' | 'red';
}

const MyStyledElement = styled.div<StyledProps<MyComponentProps>>`
    color: ${ props => props.myprop };
`;
```

Then your element can take a partial of your component props

```const MyComponent: React.StatelessComponent<MyComponentProps> = (props) => (
     <div>
         <MyStyledElement { ...props } />
     </div>
);```

Just an idea.

**Comment by aloker** [comment]
I'd appreaciate solution as provided by MUI or styled-components (using module augmentation).

**Comment by Andarist** [comment]
There is a more recent discussion about this in https://github.com/emotion-js/emotion/issues/1507 . Closing this one in favor of the other one, hope you understand.
