### ISSUE TITLE
Pass css as inline styles for a styled component

### ISSUE THREAD

**Issue by harmeetjaipur** [emotion-js/emotion#806]
- `emotion` version: 9.2.4
- `react` version: 16.4.1

Consider the following React component:

```javascript

export const ListItem = styled('li')(({ ...props }) => ({
  position: 'relative',
  'p, div, h1, h2, h3, h4, h5, h6': {
    marginTop: '0em',
    fontSize: '1em',
    color: 'black',
    mark: {
      background: 'yellow',
      color: 'black',
      '*': {
        color: 'black',
      },
    },
    i: {
      color: 'orange',
    },
  },
  '> .learn__button': {
    marginTop: '0em',
    '&.hide': {
      opacity: 0,
      zIndex: -1,
    },
  },
}));

```
Is there  a way to add css as inline style on the ListItem while it being a styled component?

The reason why it's needed to be inline is that these ListItem(s) are used to create a .DOCX file. If there was a way to attach a property in some way that could then be passed to the `style` attribute of ListItem component, it'd be amazing.

If there isn't already some way to do this, then for instance, something like this for the above ListItem component:

```javascript

export const ListItem = styled('li')(({ ...props }) => ({
  position: 'relative',
  'p, div, h1, h2, h3, h4, h5, h6': {
    marginTop: '0em',
    fontSize: '1em',
    color: 'black',
    mark: {
      background: 'yellow',
      color: 'black',
      '*': {
        color: 'black',
      },
    },
    i: {
      color: 'orange',
    },
  },
  '> .learn__button': {
    marginTop: '0em',
    '&.hide': {
      opacity: 0,
      zIndex: -1,
    },
  },
'markInlineStyles': `background-color: yellow; color: black;`
}));

```

**Comment by Andarist** [comment]
This is not possible, because emotion handles things like media queries, pseudo-classes, etc and those can't be expressed with `style`. This also doesn't align with our goals and the demand for such a feature seems rather low.

Sorry for getting back to you so late and thanks for understanding.
