### ISSUE TITLE
Blacklist size and color attributes on SVG tag

### ISSUE THREAD

**Issue by pzi** [emotion-js/emotion#810]
Heya,

We just started migrating from glamorous to emotion and noticed some attributes appear in the HTML snapshots of our components such as `size` and `color`. There might be others given the white-list seems to have little to no concept of context (tag used).

Pretty new to emotion, but happy to help out if possible.

Cheers Patrik

-----------------------

- `emotion` version: 9.2.6
- `react` version: 15.6.2

## Relevant code.

```javascript
// next-packages/is-prop-valid/src/props.js
const props = {
  ...
  color: true
  ...
  size: true
  ...
}
```
SRC: https://github.com/emotion-js/emotion/blob/master/next-packages/is-prop-valid/src/props.js#L128

## What you did:

```jsx
// App.jsx
const IconStyled = styled("svg")(props => ({
  height: `${props.size}px`,
  width: `${props.size}px`,
  border: `1px solid ${props.color}`
}));

function Icon({ size, color }) {
  return <IconStyled size={size} color={color} />;
}

const App = () => <Icon size={120} color={"blue"} />;
```

## What happened:

```html
<!-- HTML output -->
<svg size="120" color="blue" class="css-15tztif"></svg>
```

## Reproduction:

https://codesandbox.io/s/8p27v2l898

## Problem description:

`is-valid-props` lists `size` and `color` as valid props (white-listing them), however they are not valid attributes for SVG elements.

## Suggested solution:

Some more distinction of what attributes should be forwarded to certain tags. Similar to what glamorous is doing (we are currently migrating from glamorous to emotion).

https://github.com/paypal/glamorous/blob/master/src/should-forward-property.js#L44-L49

**Comment by mitchellhamilton** [comment]
Firstly, [color is a valid svg property](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color).

I don't think there's a good enough advantage of making seperate prop lists for each element as it would make emotion slower and bigger since we would have to have a list of props that certain elements allow and a list of which elements accept which props rather than one list that contains everything which is smaller. Also, is it actually causing any problems other than they're unnecessarily set on the element?

**Comment by Andarist** [comment]
Also if you want them filtered out u can make this:
```js
import isPropValid from '@emotion/is-prop-valid'
// App.jsx
const IconStyled = styled("svg", {
  shouldForwardProp: prop => isPropValid(prop) && prop !== 'size' && && prop !== 'color'
})(props => ({
  height: `${props.size}px`,
  width: `${props.size}px`,
  border: `1px solid ${props.color}`
}));

function Icon({ size, color }) {
  return <IconStyled size={size} color={color} />;
}

const App = () => <Icon size={120} color={"blue"} />;
```

**Comment by pzi** [comment]
>Firstly, color is a valid svg property.

Fair point :sweat_smile: ... however, I had another element that suddenly had extra attributes in the compiled source: `color` appeared on a `label` HTML element.

>I don't think there's a good enough advantage of making seperate prop lists for each element as it would make emotion slower and bigger.

Totally understandable also. Without having fully looked into what's involved I am unsure how much bigger or slower it would be... Looks like glamorous is relying on React to figure some of it out.

A simple change may be to at least separate the [valid SVG attributes](https://github.com/emotion-js/emotion/blob/master/next-packages/is-prop-valid/src/props.js#L199-L462) from the valid HTML attributes. Kinda already happening the way the props are grouped into in the `props.js` file:

- Standard Properties
- RDFa properties
- Non-standard properties (SVG, IE, Safari, etc.)

>is it actually causing any problems other than they're unnecessarily set on the element?

It could lead to unexpected behavior I suppose. In the case of the `color` attribute on the `SVG` tag, it will be inherited by the underlying shape elements (ie. `path`, `circle`, etc.)

Apart from that, it creates invalid HTML/SVG, which, depending on the type of product people are building, would definitely be an issue.

It could also trip up software used for accessibility or bots scraping the rendered DOM (like Google's rich search results, Pocket or instapaper). Some of the prop names are so generic that they could easily be used to pass in actual data to components and then it would end up in the compiled DOM. However, the shape of the data might be invalid for the browser/tech that's trying to use it.

Having said all that though, in our particular case we will either adopt what @Andarist has posted (thanks for that) and filter out those unwanted props or just rename the React component props to not "clash" with valid HTML/SVG attributes.

Appreciate your thoughts and input.

**Comment by brentertz** [comment]
@pzi I ran into this when migrating from Glamorous to Emotion and ended up creating a version that validates props per tag.  Perhaps you'll find it useful.

https://github.com/mineral-ui/mineral-ui/blob/master/src/library/utils/isValidProp.js#L36

**Comment by Andarist** [comment]
Closed because of reasons mentioned in - https://github.com/emotion-js/emotion/issues/810#issuecomment-415664568 . Also - we recommend to use `@emotion/core` APIs and because with them everything is done inside of your component's render there is no need to filter anything because you can easily just use JavaScript to do so. If you like styled API you can also easily build your own flavor of it based on the `@emotion/core` APIs (taking `@emotion/styled-base` implementation as a base for it - as it is actually just a wrapper around `@emotion/core`).
