### ISSUE TITLE
Default Theme without ThemeProvider?

### ISSUE THREAD

**Issue by lucasterra** [emotion-js/emotion#811]
### Problem description:
I am writing a UI Framework with Emotion and I wanted to have a default theme without forcing the users to provide a theme with ThemeProvider.

i.e.:
```js
// ui-framework/Button.js
import styled from 'react-emotion'

const ButtonRoot = styled.button((props) => ({
  // This won't work, because theme would be an empty object without a default theme in ThemeProvider
  backgroundColor: props.theme.palette.primary.main,
  borderColor: props.theme.palette.primary.light,
}))

const Button = (props) => (
  <ButtonRoot>
    {props.label}
  </ButtonRoot>
)

export default Button
```

So in our code, users can use my Button component as a standalone component, without having to inject the theme with a theme provider.
```js
// UserCode.js
import Button from 'ui-framework/Button'

const MyComponent = () => (
  <div>
    …
    <Button label="This is awesome button, it works without a ThemeProvider!"/>
  </div>
);
```

### Suggested solution:
In `create-emotion-styled`, we have [this line](https://github.com/emotion-js/emotion/blob/bb99600fcfecbd1d381cdc558d885732142c3112/packages/create-emotion-styled/src/index.js#L102). It is the line that provides a theme to the styled function. Priority goes as follow:
1. Picks a theme on context, from ThemeProvider.
2. Picks the theme from the props passed by the parent.
3. Finally fallsback to an empty object: `{}`

So my solution to this is... instead of falling back to an empty object, why not give it the possibility of falling back to a defaultTheme? We could simply change the function signature of `createEmotionStyled` to:
```ts
function createEmotionStyled(emotion: Emotion, view: ReactType, defaultTheme?: Object = {}) {
  …
  theme = (state !== null && state.theme) || props.theme || defaultTheme // fallback to defaultTheme, last
  …
}
```

Then, to use it you just create your own instance of styled with your defaultTheme.

**Comment by Glazy** [comment]
Great idea @lucasterra! Will get started working on this :+1:

**Comment by lucasterra** [comment]
Probably makes sense to add it to [emotion@10](https://github.com/emotion-js/emotion/blob/91b53308568b81f3293afe321a4adb4d2336975f/next-packages/styled-base/src/index.js#L82) instead of 9.

**Comment by lucasterra** [comment]
In v10 yes, this will work. But in v9 it would return an empty object. :)
Em qui, 6 de set de 2018 às 12:23, Christopher Biscardi <
notifications@github.com> escreveu:

**Comment by ChristopherBiscardi** [comment]
ah, I thought you were familiar with the concepts so I just used your example code to illustrate the point. You can do the same thing in v9 because default args are a JS feature. Here's a working example broken out into it's pieces (and a [codesandbox](https://codesandbox.io/s/kxn8y9jw5o))

```js
import React from "react";
import ReactDOM from "react-dom";
import styled from "react-emotion";
import { ThemeProvider } from "emotion-theming";

const myalttheme = { palette: { primary: { main: "red" } } };
const mytheme = { palette: { primary: { main: "blue" } } };
const p = mytheme.palette;

function withBG({ theme: { palette = p }, theme, ...props }) {
  return palette.primary.main;
}
const Button = styled("div")`
  background-color: ${withBG};
`;

function App() {
  return (
    <ThemeProvider theme={myalttheme}>
      <div className="App">
        <h1>Hello CodeSandbox</h1>
        <h2>Start editing to see some magic happen!</h2>
        <Button>stuff</Button>
      </div>
    </ThemeProvider>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

With the `ThemeProvider`, the background is red; without the `ThemeProvider`, the background is blue.

**Comment by lucasterra** [comment]
Yea, this works. Thanks for the snippet. :)
Closing the issue, then.

**Comment by paramsinghvc** [comment]
It really sucks. Why they're initialising theme prop with an empty object. Also, there's no easy way to define defaultTheme. Using this approach
```
const ButtonRoot = styled.button(({ theme = defaultTheme, ...props }) => ({
  backgroundColor: theme.palette.primary.main,
  borderColor: theme.palette.primary.light,
}))
```
defeats the possibility of defining style properties as css properties.

**Comment by FezVrasta** [comment]
@paramsinghvc what you can do is:

```js
const ButtonRoot = styled.button(({ theme, ...props }) => ({
  backgroundColor: theme.palette.primary.main,
  borderColor: theme.palette.primary.light,
}));
ButtonRoot.defaultProps = {
  theme: defaultTheme,
}
```

**Comment by paramsinghvc** [comment]
@FezVrasta Thanks for the input. I tried it, but what I'm looking for is to write the styles in css and not in camelCasedProperties i.e `background-color` in place of `backgroundColor`. Is that possible?

**Comment by FezVrasta** [comment]
```js
const ButtonRoot = styled.button`
  background-color: ${props => props.theme.palette.primary.main};
  border-color: ${props => props.theme.palette.primary.light};
`;
ButtonRoot.defaultProps = {
  theme: defaultTheme,
}
```

**Comment by FezVrasta** [comment]
I noticed what I suggested seems to have stopped working, now the `defaultProps.theme` value is always used and never gets overridden by ThemeProvider...

**Comment by panchaldeep009** [comment]
Here, The solution to use `defaultProps` is not working in typescript.

```
import React from 'react';
import { render } from '@testing-library/react';
import { matchers } from 'jest-emotion';
import styled from '@emotion/styled';

expect.extend(matchers);

describe('Theme Component Testing', () => {
  const ThemedColorDiv = styled.div(({ theme }) => ({
    // Error Here: Property 'colors' does not exist on type 'object'.
    color: theme.colors.primary,
  }));

  ThemedColorDiv.defaultProps = {
    theme: { colors: { primary: 'red' } },
  };

  const text = 'colored Text';
  const styledComponent = <ThemedColorDiv>{text}</ThemedColorDiv>;

  it('Receives Theme color', () => {
    const { getByText } = render(styledComponent);
    expect(getByText(text)).toHaveStyleRule('color', 'red');
  });
});
```
here because of the type of theme from the props is the object, so any properties from theme says does not exist.

Also from the viewpoint of creating a component library, having extra prop for default theme helps a lot to create a component that can be used without theme providers. and where we don't need to write a default theme processor every time for every component

**Comment by enrique-ramirez** [comment]
For anyone stumbling upon this in 2022, I'm not saying this is the best way but it's working for me. I created a custom hook called `useTheme`:

```typescript
import { useTheme as emotionUseTheme } from "@emotion/react";

import type { Theme } from "../theme";
import { theme as defaultTheme } from "../theme";
import { isEmpty } from "../utils";

const useTheme = (): Theme => {
  const contextTheme = emotionUseTheme() as Theme;
  return isEmpty(contextTheme) ? defaultTheme : contextTheme;
}

export { useTheme };
```

Then on my components:

```typescript
import { useTheme } from "../../hooks/useTheme";

const Button = () => {
  const theme = useTheme();
  return (
    <MyEmotionComponent
      {...props}
      theme={theme}
    />
  );
};
```

**Comment by Andarist** [comment]
This is a great solution. In fact, perhaps you just don't need to use Emotion theme at all if you need defaults etc. You could just use your own context throughout the app - it's easier to type and control.
