### ISSUE TITLE
Emotion native will not working when comments inside.

### ISSUE THREAD

**Issue by rockmandash** [emotion-js/emotion#816]
So basically this will not work.
```javascript
const Container = styled.View`
  flex: 1;
  /* 
  justify-content: center;
  align-items: center;
  background-color: white; */
`;
```
And there will be no error, so user won't be able to find ui specific bug.
The only solution I come up is remove comments first.
Using regex like this `\/\*[^*]*\*+([^/*][^*]*\*+)*\/` will remove css comments.

**Comment by nitin42** [comment]
Hi @rockmandash! Thanks for reporting the issue. I'll review the test cases again and see if I can fix it, soon.

**Comment by rockmandash** [comment]
@nitin42 Thank you.

**Comment by nitin42** [comment]
Some progress here #840
