### ISSUE TITLE
Getting Uncaught TypeError: f.default.div is not a function in Production Build

### ISSUE THREAD

**Issue by zicodeng** [emotion-js/emotion#823]
- `emotion` version: `^9.2.6`
- `emotion-theming` version: `^9.2.6` 
- `react-emotion` version: `^9.2.6`
- `react` version: `^16.4.2`

Relevant code.

```javascript

```

What you did:

Build my app bundle in production mode

What happened:

An error occurred: `f.default.div is not a function`

Reproduction:

Problem description:

Everything works in development mode, but once I built it with webpack production mode, this error occurs

Suggested solution:

**Comment by zicodeng** [comment]
I have found a fix for this. The error is caused by my TypeScript file. It seems `babel-plugin-emotion` has some trouble understanding the `commonjs` module output by `ts-loader`. The solution is to change module to `es2015` in my `tsconfig.json`

**Comment by averyfreeman** [comment]
I was having this same issue in a nextjs project using `@emotion/styled/macro` and a CSS-in-JS file I parsed from bootstrap v5 alpha. 

I barely know anything about typescript yet, so I just copied the example `tsconfig.json` file on this page and it appears to be working:  https://basarat.gitbook.io/typescript/project/compilation-context/tsconfig

I'm guessing the operative parameter is  `"target": "es5"`
