### ISSUE TITLE
Disable Hash Generation And Just Use Label Value For Class Name

### ISSUE THREAD

**Issue by zicodeng** [emotion-js/emotion#827]
- `emotion` version:
- `react` version:

Relevant code.

```javascript

```

What you did:

What happened:

Reproduction:

Problem description:
Is there anyway to disable hash generation for class name and just use specified label instead? The goal is to achieve BEM syntax

Suggested solution:

**Comment by mitchellhamilton** [comment]
That's not possible as it would create clashes between class names. Could you explain why you want "BEM syntax"?

**Comment by zicodeng** [comment]
Thanks for your reply. I am just curious if there is such pattern using css-in-js library like emotion with BEM syntax.

**Comment by JoshRosenstein** [comment]
@zicodeng -Not sure what your use case is but check out https://github.com/Decisiv/styled-components-modifier
should work with emotion as well,

**Comment by zicodeng** [comment]
Great, thanks for your reply. I will close this issue
