### ISSUE TITLE
Move object parsing to Babel preset to reduce size and improve performance

### ISSUE THREAD

**Issue by jeremenichelli** [emotion-js/emotion#83]
In the last release **(5.1)**, `emotion` supports object styles. This increases the runtime size of the library and performance because it needs to parse the object _live_.

It would be great if we could move this to the babel preset level, turn the object into string and roll back to a state where the runtime only handle strings.

Twitter thread for reference: https://twitter.com/jeremenichelli/status/882286692278951939

@tkh44 I had not the opportunity to try this library yet. If you could provide what were the main pain points on this and some references to the codebase where this happen I can give it a try myself 😃

**Comment by tkh44** [comment]
I think this would be a good start https://github.com/tkh44/emotion/issues/92

**Comment by nishp1** [comment]
@jeremenichelli If you haven't already started on this, I am going to start working on it cont. on from https://github.com/tkh44/emotion/pull/101

**Comment by jeremenichelli** [comment]
Go for it @nishp1 🎉
