### ISSUE TITLE
Emotion 10 styled-base and passing theme

### ISSUE THREAD

**Issue by tadeuszwojcik** [emotion-js/emotion#831]
- emotion version: 10 (@emotion/core": "^0.13.0")
- react version: 16.4.2

Hi,
Would it be possible for `@emotion/styled-base` to pass `mergedProps` which include `theme` prop instead of `props` to underlying BaseComponent (https://github.com/emotion-js/emotion/blob/master/next-packages/styled-base/src/index.js#L105)?  By default it would still skip theme prop as there is `testOmitPropsOnComponent` check but if someone (like me) would have `  shouldForwardProp: () => true`  then it would forward the theme prop as well.
I need to have access to theme in my custom Base component and that change would solve it. Alternative solution would be to wrap my Base component with `withCSSContext` but that doesn't sound really efficient. What do you think?

**Comment by Andarist** [comment]
Could u describe ur use case for having theme access in the render (I suppose u are looking for that)? Seems like only styled components should be concerned with it and I'm not sure if we should encourage accessing it in other places.

**Comment by tadeuszwojcik** [comment]
Sure, my use case may be bit unusual, but maybe not that crazy :) I'd like to be able to define in theme object both styles and [react-pose](https://popmotion.io/pose/)  animation configs, I could use only css transitions but it's bit limiting. 
I have something like this for styled: `styled(AnimatedTag)` where `AnimatedTag` is react-pose component and what I could like to have is access to theme prop where my animation configs are stored inside that `AnimatedTag` component.

**Comment by tadeuszwojcik** [comment]
Cool. I've experimented with it a little and  with change proposed here (passing `mergedProps`) and change to react-pose (https://github.com/Popmotion/popmotion/issues/451) I've got that working locally, so react-pose was able to read it's config from the theme object.

**Comment by Andarist** [comment]
Sorry for getting so late back to you, hope you understand. Seems like providing a custom `shouldForwardProp` should solve this for you - if not and this is still an issue for you then please respond back.

Aside from that - with `@emotion/core` and `framer-motion` (successor of `react-pose`) you do all the things in render so this actually removes the problem entirely, because you can just use proper hooks etc and have access to whatever you can and compose this very well.
