### ISSUE TITLE
Question about theming css (without styled)

### ISSUE THREAD

**Issue by jooj123** [emotion-js/emotion#835]
Sorry this is more of a question about ideal usage than an actual issue (hope this is the right place for it)

- `emotion` version: 9.2.6
- `react` version: 16.2.0

I know I can theme with `css` and `styled` together with something like:

```javascript
const carouselCss = ({ theme }) => css`
 .. css properties etc
`;

const CarouselDiv = styled('div')`
  ${carouselCss};
`;

then jsx:

<ThemeProvider theme={{ stuff: 'blah' }}>
  <CarouselDiv>
        ..
  </CarouselDiv>
</ThemeProvider>
```

But is there any elegant way to theme with only `css` - prefer not to use componentized styles because I want to keep to semantic html elements in JSX (also have a massive code base and its easier to migrate from sass to emotion without having to use `styled`)

I know I can do something like:

```javascript
const carouselCss = (theme) => css`
 .. css properties etc
`;

then jsx:

<div className={carouselCss(this.props.theme)}>
..
</div>
```

But it means passing a theme prop all the time from the component - which is a little cumbersome 

Is there a better way to do this ? Somehow wrap `css` with something so it has theme vars injected ?

**Comment by kossel** [comment]
Do you meam `withTheme` https://emotion.sh/docs/emotion-theming#withthemecomponent-reactcomponent-function ?

**Comment by jooj123** [comment]
`withTheme` will only work with react components - not sure if there is a way for `css` to work with `withTheme`. 
It still needs to return the dynamic classname but be theme aware based on whats in context

**Comment by jooj123** [comment]
Will this be easier with the `css` prop in emotion 10?

I can see the docs here: 
https://github.com/emotion-js/emotion/pull/799/files

Not sure if I can get around prop passing without inlining the css into JSX - ideally want the css to be imported from another file

**Comment by Andarist** [comment]
From what I understand you'd have to export this
```js
export const blah = theme => `
    color: red;
    font-size: ${theme.fontSize}px;

    &:hover {
      color: red;
    }

    & .some-class {
      font-size: 20px;
    }
`;
```

**Comment by jooj123** [comment]
Ok thanks - thats basically the same as what I currently have 

Figured as much that i needed to pass prop down explicitly .. was hoping there was a nicer way :/

**Comment by Andarist** [comment]
Maybe we could pass `props` as 2nd argument here: https://github.com/emotion-js/emotion/blob/cc559129e4794e47f4b7f969af549554a6dc971b/next-packages/core/src/jsx.js#L42

cc @mitchellhamilton

**Comment by jooj123** [comment]
@Andarist should i re-open as it seems it could be improved?

**Comment by Andarist** [comment]
Sure, u can open an issue to see if we can improve this or not
