### ISSUE TITLE
[next-packages/is-prop-valid] Unknown prop on DOM element fontSize

### ISSUE THREAD

**Issue by AlahmadiQ8** [emotion-js/emotion#838]
- `emotion` version: `^9.2.8`
- `react` version: `^9.2.8`

related to https://github.com/emotion-js/emotion/issues/183

## Relevant code.

```javascript
    console.log('backgroundColor', isPropValid('backgroundColor'))  // false
    console.log('fontSize', isPropValid('fontSize'))  // true 
```

## What you did:

- when i render the following 

```
export default  () => (
    <Container fontSize="32px" backgroundColor="orange">
      The Next Generation of CSS-in-JS
    </Container>
)
```

## What happened:

- the render dom does not filter `fontSize`

```javascript
<div font-size="50px" class="css-nbjk8j">The Next Generation of CSS-in-JS</div>
```

## Reproduction:

Here is a link to [the sandbox](https://codesandbox.io/s/k31pw91o4r)

## Problem description:

The problem seems that `isPropValid('fontSize')` returns true and hence, is not remove from the dom attribute. `fontSize` is only valid for `svg` elements.

## Suggested solution:

I'm not familiar with the code base, but perhaps `isPropValid` should take into account whether the Tag is svg or not. Maybe add another boolean arg?

**Comment by Andarist** [comment]
We do not plan to differentiate the isPropValid whitelist per tag, if u want to forbid it u might want to do this:
```js
import isPropValid from '@emotion/is-prop-valid'
import styled from 'react-emotion'

const Container = styled('div', {
  shouldForwardProp: prop => isPropValid(prop) && prop !== 'fontSize'
})`
  font-size: ${p => p.fontSize};
`
```

**Comment by brentertz** [comment]
@AlahmadiQ8 I ran into this when migrating from Glamorous to Emotion and ended up creating a version that validates props per tag.  Perhaps you'll find it useful.

https://github.com/mineral-ui/mineral-ui/blob/master/src/library/utils/isValidProp.js#L36
