### ISSUE TITLE
Adding emotion-babel-plugin breaks styled-components

### ISSUE THREAD

**Issue by mattfwood** [emotion-js/emotion#842]
- `emotion` version: ^9.2.8
- `react` version: ^16.3.2

What you did:

Working on migrating from styled-components to emotion, but the `babel-emotion-plugin` removes all styled-components CSS.

What happened:

Reproduction:
https://github.com/mattfwood/styled-components-emotion-issue

Problem description:

When adding the `babel-emotion-plugin` to a project that uses styled-components, it throws the issue below and removes all styled-components CSS added to the React project.

![screen shot 2018-09-06 at 9 28 30 am](https://user-images.githubusercontent.com/22530815/45164640-821f7a80-b1b8-11e8-94fe-ad3ff704d278.png)

Suggested solution:

I realize that the "error" is coming from styled-components, but I feel like there must be a way in the `babel-emotion-plugin` to either ignore the `styled` tag from styled-components or provide an option in the config to ignore the `styled` keyword and not interfere with styled-component styles while migrating.

https://github.com/emotion-js/emotion/blob/master/packages/babel-plugin-emotion/src/macro-styled.js

I'd be glad to start looking into this myself. I think emotion is great, but I think this issue is likely to come up for a lot of people migrating from styled-components due to performance issues.

**Comment by mitchellhamilton** [comment]
This is fixed in v10.
