### ISSUE TITLE
Typescript error on import of emotion base library

### ISSUE THREAD

**Issue by mdwagner** [emotion-js/emotion#846]
- `emotion` version: 9.2.8
- `react` version: n/a

What you did:
Installed the latest version of `emotion` in a project without React.

What happened:
Typescript reported an error with how the types are defined.

Reproduction:
<img width="1036" alt="screen shot 2018-09-09 at 10 08 36 pm" src="https://user-images.githubusercontent.com/13472976/45273134-26d2de00-b47f-11e8-9f2e-eff082820261.png">
<img width="288" alt="screen shot 2018-09-09 at 10 10 01 pm" src="https://user-images.githubusercontent.com/13472976/45272937-07878100-b47e-11e8-9bea-0eaf8620e31f.png">

Problem description:
Typescript is reporting an error with how the types are defined, but it's also trying to define types on a module that does not exist in the project. This is kind of an issue for us, because we have a compile-time requirement, so we can't have any typescript errors when building our app.

Suggested solution:
I would recommend that the types it adds for React/Preact are not in the base emotion library, since this library should be framework agnostic (we are using emotion with AngularJS in our case). Instead, I think the `react-emotion` package should add the typescript types.

**Comment by alifnurbisri** [comment]
Gmn nich

**Comment by Ailrun** [comment]
Thank you for your reporting!
However, css props work if you have emotion and babel plugin for emotion, so I think there are some issues too in suggested solution.
Does that error occurs after installing `@types/react`? (This does not affect your build result)

**Comment by Andarist** [comment]
The issue has been filed against emotion@9 and I believe this is not a problem in current emotion@10. The react related typings don't live in vanilla emotion packages so this shouldn't affect anyone any longer. Sorry that we couldn't get back to you sooner - hope you understand.
