### ISSUE TITLE
Vue-Emotion compatibility?

### ISSUE THREAD

**Issue by Aaron-Pool** [emotion-js/emotion#848]
- `emotion` version: Latest
- `react` version: NA

My team is working with `Vue-Emotion`. We like it pretty well, but we're concerned we might run into problems down the road (like, for example, Babel-Plugin targeting styled-components might not work). It's difficult to tell exactly how much the emotion library depends hinges on the implementation of `styled`.

How much is using a different implementation of `styled` (such as `Vue-Emotion`) putting us at risk of running into compatibility issues with the Emotion ecosystem?

**Comment by JosephBlythe** [comment]
We are using vue-emotion and yes there is a problem with using babel-plugin-emotion it doesn't work, we are currently trying to resolve this will let you know.

**Comment by ParkerD559** [comment]
If anyone is interested, I've gone ahead and made https://github.com/ParkerD559/vue-emotion which is written specifically for vue instead of trying to bend the react version to work with vue. still a bit more to do to reach parity, but feel free to try it out

**Comment by Andarist** [comment]
We have no capacity to create official Vue bindings, but it should be fairly simple using existing APIs as many of them are not aware of React at all. We encourage the community to create such bindings.

Similarly, we don't have capacity to improve the compatibility of babel-plugin-emotion with existing custom bindings. This doesn't mean that we wouldn't merge in code improving the story around this but this has to be a community effort. PRs are welcomed.
