### ISSUE TITLE
Default import issue on Emotion 9.2.8

### ISSUE THREAD

**Issue by MaximeHeckel** [emotion-js/emotion#849]
- `emotion` version: `9.2.8`
- `react` version: `16.5.0`
- `webpack` version: `4.5.0`

Relevant code.

```
import styled, { keyframes } from 'react-emotion';
```

What you did:
With the dependencies above in my project, importing the `default` export `styled` doesn't work, I'm getting the following error:

```
Uncaught TypeError: (0 , _reactEmotion2.default) is not a function
```

<img width="1269" alt="screen shot 2018-09-11 at 5 00 45 pm" src="https://user-images.githubusercontent.com/2974412/45394210-66ffa100-b5e4-11e8-987c-756665657d4e.png">

Reproduction:

Problem description:
This is an import issue, probably due to webpack 4 handling modules differently. The `default` export is nested inside an outer default object.
Sorry in advance if this issue had already been tacked, I've looked around for quite a bit but couldn't find anything related to this particular problem.

Suggested solution:
As a quick fix for me to continue using emotion I did the following:

```
import { caches, css, flush, keyframes, injectGlobal, getRegisteredStyles, merge, sheet } from 'react-emotion';

const styled = require('react-emotion').default;

export {
  caches,
  css,
  flush,
  keyframes,
  injectGlobal,
  getRegisteredStyles,
  merge,
  sheet,
}
export default styled;
```

But I'd like to know what is clearly happening and how we could avoid this in the future.

**Comment by Andarist** [comment]
Doesn't seem like an emotion issue, but you could try to share ur repo (or a repo with the issue reproduced) so I could take a look why this happens.

**Comment by MaximeHeckel** [comment]
@Andarist you're right it's was a setup issue.
We were using a babel es2015 preset, which once removed made the import work.
Closing this.
