### ISSUE TITLE
Cannot find module '@emotion/stylis' from 'create-emotion/dist/index.cjs.js

### ISSUE THREAD

**Issue by AlexandreBourdeaudhui** [emotion-js/emotion#850]
- `emotion` version: `^9.2.8`
- `react-emotion` version: `^9.2.8`
- `react` version: `^16.5.0`

**Relevant code**.
```javascript
/*
 * Package Import
 */
import React from 'react';

/*
 * Local Import
 */
import styled from 'react-emotion';

/*
 * Style
 */
const Test = styled.div({
  color: '#ee1125',
});

/*
 * Component
 */
const App = () => <Test>Hello World !</Test>;

/*
 * Export
 */
export default App;
```

**What you did**:

**What happened**:
```shell
app.js:61 Uncaught Error: Cannot find module '@emotion/stylis' from 'create-emotion/dist/index.cjs.js'
    at require (app.js:61)
    at expanded (app.js:34)
    at app.js:148
    at index.cjs.js:12
    at index.cjs.js:529
    at initModule (app.js:42)
    at require (app.js:59)
    at expanded (app.js:34)
    at app.js:148
    at index.cjs.js:11
```

**Reproduction**:
Repository for reproduction : https://github.com/AlexandreBourdeaudhui/RepoBug

**Problem description**:
Sorry if this problem have already a patch, but i dont see anything in closed issues... Also, if i run my project with `emotion@9.1.3` ; i don't have problem and my app can run correctly 🤔

**Suggested solution**:

**Comment by Ailrun** [comment]
I think it's your bundler's fault, since it does bundle `@emotion/stylis/dist/stylis.cjs.js`, but it does not alias it as `@emotion/stylis`.

**Comment by AlexandreBourdeaudhui** [comment]
Hello @Ailrun 👋

Sorry but i don't understand... It's the `Brunch`'s fault ? Why ? Can you explain me ? 🙏

**Comment by Ailrun** [comment]
@AlexandreBourdeaudhui When you check your bundled code, you can see there is `@emotion/stylis/dist/stylis.cjs.js` but it does not create alias `@emotion/stylis`. We, as library authors, cannot control such things.

**Comment by AlexandreBourdeaudhui** [comment]
@Ailrun Thanks for clarification, i understand now.
I'm using Webpack now, and i don't have any problem. So, i can close this issue.

Best regard :wave:

**Comment by mavlikwowa** [comment]
I got a similar error when used NextJS. I solved this problem just run yarn dev again. You should do it after install npm-packages.
