### ISSUE TITLE
query- nested styled component

### ISSUE THREAD

**Issue by roshantarudkar** [emotion-js/emotion#851]
During my development i come across one instance where i had  to create nested styled component but  i couldn't find in emotions doc or anywhere. If its not there then there may be some reason not having nested styled component..I am curious to know whats the reason? if its not considered then it would be nice to have feature..may be i can start contributing.
  
Since i am talking about `Nested styled component` what i meant:

lets say This is my Link component wrapped under span..
```
const Link = styled("a")``;
<span><Link href="#" > <svg/> </a> </span>
```

Suggested solution:
i was thinking to wrap span and a together so that i dont have to have separate styled component declare it can be done using nested.

pseudo code -something like below- dont quote me on below code ..it just came up in my mind..
```
const Link =  styled("span").styled("a")``;
```

**Comment by Ailrun** [comment]
Just use `>` selector. You can use
```
const Example = styled('span')`
  color: green;
  & > a {
    color: red;
  }
`

<Example>Is <a>this</a> what you want?</Example>
```

**Comment by Andarist** [comment]
Seems like the documentation around this use case has been already added as part of https://github.com/emotion-js/emotion/pull/1360 .
