### ISSUE TITLE
Babel plugin cannot retrieve module name properly when generating stable class name

### ISSUE THREAD

**Issue by ferdaber** [emotion-js/emotion#860]
- `emotion` version: 9.2.6
- `react` version: 16.4

### Relevant code

```javascript
const StyledComponent = styled.div`...`
```

### What you did
Transpiled various styled components using babel-plugin-emotion

### What happened
Stable class names generated by styled components are colliding, because of our monorepo project structure and a lack of a unique module name adding to the hash.

For this project structure:
```
packages
|- component-a
    |- package.json (name: "component-a")
    |- index.jsx
|- component-b
    |- package.json (name: "component-b")
    |- index.jsx
```
A styled component in both `component-a` and `component-b` gets the same stable class name, because their relative paths to their roots are the same, even though their package names are different.

The problem lies in this line:
https://github.com/emotion-js/emotion/blob/d98dcd463ae2dcdd71bfb2c27675a6e9aaff1036/packages/babel-plugin-emotion/src/index.js#L172

Node `require` needs `./` in front if the module being required is a relative path (instead of absolute or inside of `node_modules`), but `rootPath` at this point is something like: `packages/component-a` (without the `./` in front)

### Reproduction
Set up an example project like the above, and verify that the generated `target` property of the `styled` constructor is the same for both components in both packages.

### Suggested solution
Unsure where the problem lies, it looks like `state.file.opts` has both a `filename` and `filenameRelative`, but I'm seeing that they are both the same value, so it may be a bug with Babel itself? If nothing else, it may be better to use `filenameRelative` and just resolve it with `process.cwd()`?
```js
var filename = path.resolve(process.cwd(), state.file.opts.filenameRelative)
```

**Comment by ferdaber** [comment]
I just confirmed that this only affects Babel <7, when reproducing with using Babel 7, it looks like the absolute path is correctly returned in `state.file.opts.filename`

**Comment by Andarist** [comment]
The issue has been reported for babel-plugin-emotion@9. If it still is a problem for you with babel-plugin-emotion@10 then, please report the issue back with full runnable repro case so we could get to it quicker. Sorry for the late response, hope you understand.
