### ISSUE TITLE
Speedy in server side rendering, would like to disable for certain NODE_ENVs

### ISSUE THREAD

**Issue by rileybracken** [emotion-js/emotion#862]
Problem description:
When we build sites we typically use 3 environments. `dev`, `beta`, and `production`. And we use NextJS for server side rendering. Right now it isn't super straight forward on how to disable `speedy` in our projects and our designers would really like us to.

Suggested solution:
Would it be possible to setup `babel-plugin-emotion` to disable speedy. I would be happy to do the work, just not sure where to start.

Something like this would be awesome:
```
[
  'emotion',
  {
    hoist: true,
    autoLabel: process.env.NODE_ENV !== 'production',
    speedy: process.env.NODE_ENV === 'production',
  },
],
```

**Comment by Andarist** [comment]
Wouldnt it be easier for u to do smth like this:
```js
import { sheet } from 'react-emotion'

const decodeQueryString = str => str.split('&').map(function (pair) {
    return pair.split('=').map(decodeURIComponent)
}).reduce(function (obj, pair) {
    obj[pair[0]] = pair[1]
    return obj
}, {})

const query = decodeQueryString(location.search.replace(/^\?/, ''))

if ('__yourUniqueParam' in query) {
    sheet.speedy(false)		
}
```

You can ofc use any other logic that u want to disable it. Keep in mind that this code has to run ASAP (before any styles are created), so it's good to create a file for this code and import it as first thing in ur app.

https://emotion.sh/docs/ssr#puppeteer
