### ISSUE TITLE
(Feature Request) create emotion theme creation helper function

### ISSUE THREAD

**Issue by awidjaja** [emotion-js/emotion#863]
- `emotion` version: 9.2.9
- `react` version: 16.5.1

Relevant code.
> New helper function, e.g. createTheme(object) to pass to ThemeProvider

```javascript
const setTheme = {
  palette: {
    primary: green,
    accent: red,
    type: 'light',
    },
  },
}

const theme = createTheme(setTheme)

class App extends React.Component {
  render() {
    return (
      <ThemeProvider theme={theme}>
        <Page />
      </ThemeProvider>
    );
  }
}
```

What you did:
> Create new theme for ThemeProvider component manually

What happened:
> First of all, great job with emotion framework, really love it!
> When creating a theme object, there are so many properties to populate for a complete app with reusable, theme-able components. 

Reproduction:
N/A

Problem description:
> - Tedious and time consuming: there are so many theme properties to populate.   
> - Difficult to maintain.
> - Difficult to change dynamically without breaking the theme harmony, might lead to trial and error iterations.

Suggested solution:
> - Reapply solution from material-ui:
> - Material-ui has a great helper function `createMuiTheme(object)` that can create a complete [theme] (https://material-ui.com/customization/themes/) object, by providing a great default base theme and by extrapolating a few given parameters using rules that conform with material design color and typography principles.  
> - Additionally, it will be even better if the function can create and use amazing CSS custom variables.
> - this will help people to port material-ui components from JSS to emotion without breaking the theming feature.

(or maybe there's already a similar solution that work on emotion that  I don't know?)

thanks!

**Comment by Andarist** [comment]
This is out of the scope of emotion, it doesn't use theme anyhow, beside ofc giving it to your code so you can use it - but other than that it doesn't specify anything about it's structure (except it being an object).

You might want to look into libraries like rebass/emotion, styled-system for inspiration.

**Comment by awidjaja** [comment]
@Andarist 

alright, I thought since emotion already provided the theme object though ThemeProvider it maybe the right place to add this little helper. Rebass also doesn't have theme creation helper, and simply dump manually created theme object the same way as emotion-theming. The only framework with this helper is material-ui theming, unfortunately it requires people to install JSS.

**Comment by Andarist** [comment]
Closing this as it's out of emotion's scope.
