### ISSUE TITLE
How to use `enzyme` to select css classname generated by `cx` function?

### ISSUE THREAD

**Issue by huchenme** [emotion-js/emotion#869]
Hi Emotion team,

`css` and `cx` is awesome, but I am facing difficulties to use `enzyme` to select element whose className is generated by `cx` function.

Since enzyme does not support regex css selector, there seems no way to select `cx` generated className?

**Comment by Andarist** [comment]
We don't believe that you should query your elements by their class names in tests - not with emotion, not without it. Please take a look at this - https://testing-library.com/docs/guide-which-query#priority

Sorry that we couldn't get back to you sooner - hope you understand.
