### ISSUE TITLE
ThemeProvider theme is unpopulated when component initially renders preventing nested theme properties. 

### ISSUE THREAD

**Issue by danvee** [emotion-js/emotion#874]
- `emotion` version:  9.2.10
- `react-native-cli:` 16.3.1
- `react-native:` 0.55.4

Relevant code.

```javascript

const myTheme:ApplicationTheme = 
{
      colors: {   
                   primary: 'red',
                   secondary: 'blue'
       }
}

...

 <ThemeProvider theme={ApplicationThemeExample}>
     <MyComponent></MyComponent>
 </ThemeProvider>
...

const MyComponent = styled.View(({theme}: { theme: ApplicationTheme }) =>
    ({
      backgroundColor: logTheme(theme),
      borderColor: theme.colors.primary
    }),
)

const logTheme = (theme: ApplicationTheme) => {
    console.log('logTheme' ,   theme  )
    return 'hotpink'
}

```
What you did:
Attempted to render a component with a theme that has nested properties.

What happened:
When the component initially renders an empty object is passed the to theme param of styled.View causing error when attempting to reference nested properties (theme.colors.primary)

Ideally i'd like to avoid flattening our theme structure or using any further logic in the component styling to test that the theme isn't empty. 

Any advice would be greatly appreciated!

**Comment by mitchellhamilton** [comment]
Could you provide a reproduction? [I can't seem to reproduce it](https://snack.expo.io/HJysEVjFm).

**Comment by iheidari** [comment]
I had a same issue, but not with react-native.
It was with react and gatsby and solution was [here](https://github.com/gatsbyjs/gatsby/issues/11494).

@Ailrun I guess we can close this one
