### ISSUE TITLE
BUG: styled method className prop is not passed down

### ISSUE THREAD

**Issue by huchenme** [emotion-js/emotion#875]
- `emotion` version: 9.2.10
- `react` version: 16.4.2

### Relevant code.

https://codesandbox.io/s/k2p1knxnov

### Problem description:

**Expected:**
The inner class should have style `text-transform: uppercase;`

**Actual:**
The inner component does not have the className passed in so it does not have expected style

In our library, we allow people to pass in className as props and set to the right component, it will be breaking if the passed in className is generated by `emotion`

### Suggested solution:

the passed in className should be one of the className in the list

**Comment by mitchellhamilton** [comment]
This is expected behavior. If emotion just appended the class name there would be issues with specificity. Using emotion class names to target elements is strongly discouraged for this exact reason.

**Comment by huchenme** [comment]
@mitchellhamilton I do not quite agree with this. If both `styled` and `css` are provided by `react-emotion` and `styled` accepts `className`, the example should work.

It is ok that this scenario have never been thought about, but in our project, we have mix of `styled`, `css` and code shown in the example. The only way I can think about to get rid of this issue is to rewrite the components using `styled` to `css`.

But since `react-emotion` provide both, they should work together, that is my point.

**Comment by Andarist** [comment]
@mitchellhamilton maybe we could warn in dev mode about this (or with eslint plugin)?

**Comment by mitchellhamilton** [comment]
@huchenme Could you show a real world of where you would want this behavior? 

> @mitchellhamilton maybe we could warn in dev mode about this (or with eslint plugin)?

Yeah, that's a good idea, it would be possible at runtime so no need for eslint.

**Comment by huchenme** [comment]
We have a large code base of CSS modules and want to convert to CSS-in-JS. Initially, we would want to convert everything to `styled` way and then we realized it is not very practical as we have lots of code which set className to the most outer div to represent `state`:

```js
<div
  className={classNames(
    styles.container,
    open ? styles.open : styles.closed,
    disabled ? styles.disabled : false
  )}
>
  <div className={styles.inner}>Hello</div>
</div>
```

and in CSS:

```css
.container {

}

.inner {
  .disabled & {
	cursor: not-allowed;
  }

  .open & {
	display: block;
  }

  .closed & {
	display: none;
  }
}
```

This works fine if both outer and inner components are styled using `css` method from `emotion`. except we need some way to generate hash for `disabled`, `open` and `closed`.

We used:

```js
const disabled = css``;
const open = css``;
const closed = css``;

const inner = css`
  .${disabled} & {
	cursor: not-allowed;
  }

  .${open} & {
	display: block;
  }

  .${closed} & {
	display: none;
  }
`

with babel config

```
autoLabel: true,
labelFormat: '[filename]--[local]'
```

if without the babel config, everything becomes `css-0` which breaks the styles

this works fine as well, except those components styled using `style` got [ugly DisplayName in snapshots](https://github.com/emotion-js/emotion/issues/880)

But there are some issues we could not get rid at all:


```js
const disabledClass = css``;
const openClass = css``;
const closedClass = css``;

const innerClass = css`
  .${disabledClass} & {
	cursor: not-allowed;
  }

  .${openClass} & {
	display: block;
  }

  .${closedClass} & {
	display: none;
  }
`

<div>
  <div>Some other things</div>
  <SomeStyledComponent className={classNames(
    open ? openClass : closedClass,
    disabled ? styles.disabledClass : false
  )}>
    <div className={innerClass}Hello</div>
  </SomeStyledComponent>
</div>
```

it won't work in this case no matter what hack we are trying. And we definitely do not want to convert `SomeStyledComponent` back from `style` to `css`

**Comment by mitchellhamilton** [comment]
Why not do something like this?

```jsx
<div>
  <div>Some other things</div>
  <SomeStyledComponent>
    <div
      className={css`
        cursor: ${disabled && "not-allowed"};
        display: ${open ? "block" : "none"};
      `}
    >
      Hello
    </div>
  </SomeStyledComponent>
</div>
```
