### ISSUE TITLE
is it possible to forward InnerRef in nested Styled component

### ISSUE THREAD

**Issue by kossel** [emotion-js/emotion#878]
Let's say I have a styled `<BaseButton/>` component that enhance the html `button` also adds some basic styles. then I have some other styledButton:
```
const RoundButton = styled(BaseButton)({...styles})
const SquareButton = styled(BaseButton)({...styles})
```

How do I get the ref of the original native html button?

doing `<RoundButton innerRef={getRef} />` . will just give me back the ref to `BaseButton`, even I spread the `innerRef` props from `RoundButton` to `BaseButton` it will not work.

Actually the `innerRef` is undefined if I log it in BaseButton. I'm not sure if this is intended design, but if it's true how do I get the innerest component Ref?

Here is a [codesandbox demo](https://codesandbox.io/s/50qyj5q094)

- `emotion` version: 9.2.5
- `react` version: 16.3

After search, this looks like similar problem [from styled-components](https://github.com/styled-components/styled-components/issues/629)

**Comment by azizhk** [comment]
I think your `innerRef` is conflicting with `emotion`'s `innerRef`
You can use a different propName like `myRef`

https://codesandbox.io/s/y79z859np1

**Comment by kossel** [comment]
yeah I know it's conflicting, but we don't want some of our components have innerRef some have getRef or myRef 😞 .  we can do something like styled-component does, can we? like check if the component is a emotion Styled one, if true just forward otherwise return the ref.

**Comment by kossel** [comment]
Thanks, that should work,  but this can be opinionated let's see what other people says

**Comment by Andarist** [comment]
IMHO your case is valid, we can't fix it without potentially breaking people relaying on current behaviour. For now you'll have to use different ref prop to pass it through to ur composite components.

The good news is that upcoming emotion@10 should solve your issue entirely, as it won't use `innerRef` at all, but rather `React.forwardRef` API
