### ISSUE TITLE
Caching className hash?

### ISSUE THREAD

**Issue by Ajackster** [emotion-js/emotion#879]
- `emotion` version: 9.2.10
- `react` version: 16.4.1
- `create-emotion` version: 9.2.6

What happened:

I noticed that the murmur hash function used to generate classNames (based off of styles, interpolation, etc.) was getting called quite often and took a while to execute. I did a little investigation and came up with a couple lines of code to cache the hashed className so that emotion doesn't create a new hash when it already has created the same one.

I used a function that gets executed every 100ms which updates the component to test against (with and without caching of hash className) and collected the CPU Profile over approximately 3 seconds. This component uses emotion for stylez.

Below shows the whole 3s flame chart **without** the cache
![pic1](https://user-images.githubusercontent.com/14223893/46168379-51d27580-c266-11e8-8453-436c6f1e6078.PNG)

Below shows a zoomed in execution **without** the cache. You can also see that the murmur hash function is being called quite often (multiple times in a single component update).
![pic2](https://user-images.githubusercontent.com/14223893/46168527-c0173800-c266-11e8-803a-f8dd98561d43.PNG)

Below shows the whole 3s flame chart **with** the cache
![pic3](https://user-images.githubusercontent.com/14223893/46168680-29974680-c267-11e8-8e6b-c8871c39c648.PNG)

Below shows a single execution **with** the cache. The murmurhash function isn't being called as often and performance of each function execution increases dramatically.
![pic4](https://user-images.githubusercontent.com/14223893/46168701-3c118000-c267-11e8-928f-ad3022fbfb00.PNG)

The performance impact positively affects everything in my application that is built using emotion (The large majority of my application) and I have not seen any negative impacts on the application by doing this. Only perf gainzz!

I've only spent a couple hours investigating this, so I'm not entirely sure if this is something that should be done, nor do I know how it would affect other people's projects. I wanted to create this issue to get some advice from the experts of the source code, and see if this is something you guys would like to go forward with, or even just bring up a potential challenge that needs solvin'.

I tested this by changing the *createStyles* function in **create-emotion/dist/index.esm.js**

```javascript
  var createStyles = function createStyles(strings) {
    var stringMode = true;
    var styles = '';
    var identifierName = '';

    if (strings == null || strings.raw === undefined) {
      stringMode = false;
      styles += handleInterpolation.call(this, strings, false);
    } else {
      styles += strings[0];
    }

    for (var _len = arguments.length, interpolations = new Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
      interpolations[_key - 1] = arguments[_key];
    }

    interpolations.forEach(function (interpolation, i) {
      styles += handleInterpolation.call(this, interpolation, styles.charCodeAt(styles.length - 1) === 46 // .
      );

      if (stringMode === true && strings[i + 1] !== undefined) {
        styles += strings[i + 1];
      }
    }, this);
    stylesWithLabel = styles;
    styles = styles.replace(labelPattern, function (match, p1) {
      identifierName += "-" + p1;
      return '';
    });
    name = createClassName(styles, identifierName);
    return styles;
  };
```

To this change **with** caching:
```javascript
  var styleInfoCache = {};
  var createStyles = function createStyles(strings) {
    var stringMode = true;
    var styles = '';
    var identifierName = '';

    if (strings == null || strings.raw === undefined) {
      stringMode = false;
      styles += handleInterpolation.call(this, strings, false);
    } else {
      styles += strings[0];
    }

    for (var _len = arguments.length, interpolations = new Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
      interpolations[_key - 1] = arguments[_key];
    }

    interpolations.forEach(function (interpolation, i) {
      styles += handleInterpolation.call(this, interpolation, styles.charCodeAt(styles.length - 1) === 46 // .
      );

      if (stringMode === true && strings[i + 1] !== undefined) {
        styles += strings[i + 1];
      }
    }, this);
    stylesWithLabel = styles;
    styles = styles.replace(labelPattern, function (match, p1) {
      identifierName += "-" + p1;
      return '';
    });

    var potentialStyleCacheItem = styleInfoCache[strings];
    if (potentialStyleCacheItem && potentialStyleCacheItem.styles === styles) {
      name = potentialStyleCacheItem.name;
      stylesWithLabel = potentialStyleCacheItem.stylesWithLabel;
      return styles;
    }

    name = createClassName(styles, identifierName);
    styleInfoCache[strings] = {
      styles: styles,
      name: name,
      stylesWithLabel: stylesWithLabel,
    };
    return styles;
  };
```

Thanks!

**Comment by probablyup** [comment]
I tested out something like this for styled-components and didn't see much of a difference in terms of benchmarks. But yeah it might holistically make a difference. It'd be nice if our benchmark was a bit more comprehensive.

**Comment by Ajackster** [comment]
The benchmarks above were taken from an application running on the Chromium Embedded Framework using an old version of chrome (I think 39). Caching of the hash noticeably improves performance when running on CEF.

I created a project and tested a similar case on the actual Chrome browser, and it looks like there was no noticeable increase in performance like there was with CEF. Not sure how to get purposeful benchmarks for the Chrome browser since the murmur function execution time isn't substantial to begin with.

**Comment by mitchellhamilton** [comment]
I don't think this is something we'd want to do since it doesn't seem to really affect performance in modern browsers and it would be really bad for memory usage.

**Comment by Ajackster** [comment]
Alrighty sounds good, thanks!
