### ISSUE TITLE
Code base does not "just work" when cloned (on Windows?)

### ISSUE THREAD

**Issue by Brondahl** [emotion-js/emotion#881]
Hi there,
I've got 8 years experience of professional software development, but only ~4 months of experience on modern JS stack, so it's very possible that this is entirely mistakes or lack of knowledge about yarn / npm on my part, but I would hope that I was capable of following basic Setup steps for an OS project.

Even if the error is with me, it seems likely that the documentation could be improved to cater to other dummies who still want to Contribute, and I'm happy to submit a PR for that ... once I know what the solution is ... :)

-----------------------------

I wanted to raise a pretty trivial code feature PR for `emotion`, so I forked and cloned the project. I expected to be able to just run it and have everything work perfectly before I made my changes, but that isn't the case - if you just follow the direct instructions you get a bunch of warnings followed by an enormous collection of errors and test failures.

Details:

Versions:
- `emotion` version: current `master` as of 29/09/2018. (looks like npm pkg version 9.2.10. Commit: `0fdabe`.)
- `react` version: (N/A: This is a bug with the library development, not its usage)
- `node` version: v10.10.1
- `npm` version: 6.4.1
- `yarn` version: 1.10.1

What you did:
`git clone`
run Yarn installer from here: https://yarnpkg.com/en/docs/install#windows-stable
run `yarn` from the root of the cloned repo.
run `yarn test` from the root of the repo.

I believe the above sequence represents the instructions as currently given on the CONTRIBUTE page and then ran `yarn` from the root of my clone.

What happened:

`yarn` (which I assume to be roughly equivalent to `npm install`?) generated the following set of 17 peer-dependency warnings:

```
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > create-emotion-styled@9.2.8" has unmet peer dependency "prop-types@15.x".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > emotion-theming@9.2.9" has unmet peer dependency "prop-types@15.x".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > @emotion/native@9.2.9" has unmet peer dependency "prop-types@15.x".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > @emotion/native@9.2.9" has unmet peer dependency "react-native@>=0.14.0 && < 1".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > @emotion/primitives-core@9.2.9" has unmet peer dependency "prop-types@15.x".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > @emotion/primitives@9.2.10" has unmet peer dependency "prop-types@15.x".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > @emotion/primitives@9.2.10" has unmet peer dependency "react-primitives@^0.5.1".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > @emotion/native > react-native@0.57.0" has incorrect peer dependency "react@16.5.0".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > emotion-site > favicons-webpack-plugin@0.0.9" has unmet peer dependency "webpack@^1.13.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > emotion-site > gatsby-remark-prismjs@3.0.0-beta.3" has unmet peer dependency "prismjs@^1.13.0".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > emotion-site > worker-loader@2.0.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > emotion-site > graphql-type-json@0.1.4" has unmet peer dependency "graphql@>=0.4.0".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > benchmarks > react-native-web@0.8.8" has unmet peer dependency "react-art@16.x.x".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > emotion-site > gatsby > babel-loader@8.0.0-beta.0" has incorrect peer dependency "webpack@2 || 3".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > emotion-site > gatsby > babel-plugin-remove-graphql-queries@2.0.2-beta.4" has incorrect peer dependency "graphql@^0.11.7".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > emotion-site > worker-loader > schema-utils@0.4.5" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "workspace-aggregator-498a386e-835c-4f6f-ac4d-c847ab622954 > @emotion/native > react-native > metro > metro-visualizer > antd > rc-editor-mention@1.1.7" has unmet peer dependency "immutable@^3.7.4".
```
`yarn test` then generated about a minute and a half of scrolling screen errors, with the final punchline:

```
Snapshot Summary
 › 166 snapshots failed from 23 test suites. Inspect your code changes or run `yarn run coverage -u` to update them.

Test Suites: 35 failed, 49 passed, 84 total
Tests:       284 failed, 17 skipped, 692 passed, 993 total
Snapshots:   166 failed, 617 passed, 783 total
Time:        97.817s
Ran all test suites.
```

To be clear, all of this is from a blank, untouched `git clone` of a fork of the emotion code base.

Reproduction:
N/A

Problem description:
The repo should JustWork when cloned for development, and/or should Document how to get it working properly.

Suggested solution:
My first guess is that to get this all working I need to install some necessary dependencies.
If that's correct then I suspect the correct solution is to declare those as dev dependencies?
Failing that, then we should be providing notes on what is necessary in the CONTRIBUTING.md file.

**Comment by Brondahl** [comment]
You're welcome :)

Running on Windows.
Windows 10 Enterprise. 64-bit. Version 1803.

I'm running the commands from the "Git for Windows" bash prompt. ([This one](https://gitforwindows.org/#bash)).

A brief attempt on Powershell, and in the VSCode Terminal also give similar behaviour (have not compared error outputs to confirm that they're identical, but certain they both give pages and pages of errors.


I've run `yarn test &> output.txt` and attached the output...
[output.txt](https://github.com/emotion-js/emotion/files/2430411/output.txt)

From a brief skim through, a bunch of the snapshot errors are "the emotion hash has changed", but there's also a lot of:
```
FAIL packages/react-emotion/test/index.test.js (17.76s)
  ● Console

    console.error node_modules/fbjs/lib/warning.js:33
      Warning: The tag <circle> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
    console.error node_modules/fbjs/lib/warning.js:33
      Warning: The tag <path> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

  ● styled › no dynamic

    You're trying to use the styled shorthand without babel-plugin-emotion.
    Please install and setup babel-plugin-emotion or use the function call syntax(`styled('h1')` instead of `styled.h1`)

      208 |           }
      209 |           default: {
    > 210 |             throw new Error(
          |                   ^
      211 |               `You're trying to use the styled shorthand without babel-plugin-emotion.` +
      212 |                 `\nPlease install and setup babel-plugin-emotion or use the function call syntax(\`styled('${property}')\` instead of \`styled.${property}\`)`
      213 |             )

      at Object.get (packages/create-emotion-styled/src/index.js:210:19)
      at Object.<anonymous> (packages/react-emotion/test/index.test.js:16:23)
```

A bunch of these:
```
FAIL packages/babel-plugin-emotion/test/macro/inject-global.test.js
  ● injectGlobal

    TypeError: (0 , _macro.injectGlobal) is not a function

      4 | 
      5 | test('injectGlobal', () => {
    > 6 |   injectGlobal`
        |   ^
      7 |     html {
      8 |       background: pink;
      9 |     }

      at Object.<anonymous> (packages/babel-plugin-emotion/test/macro/inject-global.test.js:6:3)

```
And numerous other types of errors.

**Comment by Brondahl** [comment]
Is there anything else useful I can provide?
Is it worth trying a fresh new clone or a direct clone of the main repo rather than my (pristine) fork, or doing it on another machine ... just in case? Anything of the turn-it-off-and-on-again approach :D

**Comment by Ailrun** [comment]
Oh, and what's the version of your `yarn`?

**Comment by Brondahl** [comment]
node version: v10.10.1
npm version: 6.4.1
yarn version: 1.10.1

**Comment by Ailrun** [comment]
Thank you :)

**Comment by Brondahl** [comment]
yarn was installed this morning.

node & npm were updated ~ 2 weeks ago?

**Comment by Ailrun** [comment]
@Brondahl I found the problem.
https://github.com/emotion-js/emotion/blob/0fdafbe86f9aad063260e69f30ed61bd411489b3/babel.config.js#L11-L14
https://github.com/emotion-js/emotion/blob/0fdafbe86f9aad063260e69f30ed61bd411489b3/babel.config.js#L42

Those `filename`s are written with a path separator `\\` in Windows, where the codes are written based on the assumption that `filename`s are written with a path separator `/`.

and some babel-plugin-emotion code also produce different results in Windows (because of path problem), for example,
https://github.com/emotion-js/emotion/blob/0fdafbe86f9aad063260e69f30ed61bd411489b3/packages/babel-plugin-emotion/src/index.js#L182

@mitchellhamilton Could you check this?

**Comment by Brondahl** [comment]
So we're saying that it's not (currently) possible to contribute from a Windows machine? (and that all recent contributors have been running from Linux)

I assume your point about path separators is about the direction, not the number? - that we WANT a single backslash rather than a single forwardslash, but that requires escaping the backslash into a double backslash.

**Comment by Brondahl** [comment]
Assuming I've understood correctly, then we should presumably:
a) immediately modify the CONTRIBUTING.md to declare that currently Windows doesn't quite work as a dev environment
b) I should try making the relevant hardcoded changes to my local checkout and see whether everything works.

Assuming it does work then (once @mitchellhamilton has cross-checked,) we should try out something to standardize the slashes across OSs.

This SO question has a variety of answers, including citing a node library to handle it: https://stackoverflow.com/questions/125813/how-to-determine-the-os-path-separator-in-javascript

I'm happy to raise a PR for that, before my intended one.
We'll need to test it on at least 1 Windows and 1 Linux OS. Do we need others?

**Comment by Ailrun** [comment]
Yes, what I meant is just single `\` escaped.

**Comment by Brondahl** [comment]
hmmm ... so I've changed those 2 lines in the babel.config.js
I've also applied some very crude console.logging to test the behaviour around the path.normalize in the `babel-plugin-emotion` and confirmed that the are no specific issues there (input and output were always identical.)

So this is definitely an improvement, but there are definitely also other issues :(

I'm still getting that huge block of peer dependencies, and the test summary is now: 
```
Snapshot Summary
› 108 snapshots failed from 18 test suites. Inspect your code changes or run `yarn run coverage -u` to update them.

Test Suites: 18 failed, 66 passed, 84 total
Tests:       102 failed, 17 skipped, 874 passed, 993 total
Snapshots:   108 failed, 839 passed, 947 total
Time:        50.086s
Ran all test suites.
```

[updated Output file](https://github.com/emotion-js/emotion/files/2433330/output_withChangedSlashes.txt) (7,800 lines, 312KB)

It looks like all failing tests are now snapshot failures, so that's progress.

[list of snapshot mismatches, with line numbers indexing into previous file](https://github.com/emotion-js/emotion/files/2433467/snapshotMismatches.txt) (855 lines, 31KB)

Almost all of them are "the hashed classname thing changed". e.g.
```
	Line 3458:     - <main class="css-4xq7ky e126fyao0"
	Line 3459:     + <main class="css-4xq7ky e1prcv720"
	Line 3466:     -        class="css-z382ib e126fyao1"
	Line 3467:     +        class="css-z382ib e1prcv721"
	Line 3470:     -        class="css-z382ib e126fyao1"
	Line 3471:     +        class="css-z382ib e1prcv721"
	Line 3473:     -   <img class="css-z382ib e126fyao1">
	Line 3474:     +   <img class="css-z382ib e1prcv721">
-
	Line 3502:     - ".css-jww4zs .e42j9n60 {
	Line 3503:     + ".css-y3clhl .e1y2fqfu0 {
-
	Line 3550:     -   target: "e1u6ll0g0"
	Line 3551:     +   target: "e1ed59cp0"
	Line 3556:     -   target: "e1u6ll0g1"
	Line 3557:     +   target: "e1ed59cp1"
```

but a small handful are path separators:
```
	Line 2257:     - "import { css as _css } from "../my-emotion-instance";
	Line 2258:     + "import { css as _css } from "..\\\\my-emotion-instance";
-
	Line 2281:     - "import { css as _css } from "../my-emotion-instance";
	Line 2282:     + "import { css as _css } from "..\\\\my-emotion-instance";
-
	Line 2319:     - "import "tmpdir/fs.test.emotion.css";
	Line 2320:     + "import "tmpdir\\\\fs.test.emotion.css";
-
	Line 6200:     - "import { css as _css } from "../my-emotion-instance";
	Line 6201:     + "import { css as _css } from "..\\\\my-emotion-instance";
-
	Line 6224:     - "import { css as _css } from "../my-emotion-instance";
	Line 6225:     + "import { css as _css } from "..\\\\my-emotion-instance";
-
	Line 6251:     - "import "tmpdir/fs.test.emotion.css";
	Line 6252:     + "import "tmpdir\\\\fs.test.emotion.css";
```

**Comment by Brondahl** [comment]
Also, there are a whole bunch of Console.error and console.warn lines in the test outputs, plus warnings about skipped stuff. (e.g:
```
Circular dependency: packages\babel-plugin-emotion\src\index.js -> packages\babel-plugin-emotion\src\macro-styled.js -> packages\babel-plugin-emotion\src\index.js
Using named and default exports together. Consumers of your bundle will have to use bundle['default'] to access the default export, which may not be what you want. Use `exports: 'named'` to disable this warning
```
I'm not clear on whether those are to be expected or not?

Could one of the active developers (for whom the code is known to be 'working') run `yarn test &> successfulTestRun.txt` on current master and post the output, so that I know how much of that is expected on a functioning checkout?

Ta :)

**Comment by Ailrun** [comment]
Here it is :smile:
[successful.txt](https://github.com/emotion-js/emotion/files/2433664/successful.txt)
though I had to update package.json (because of recent directory structure update)...
I sent a PR (https://github.com/emotion-js/emotion/pull/884) for fixing it.

**Comment by Brondahl** [comment]
I'm not really sure what the next steps are for this? :(

I have my actual PR ready-to-go, except for running my tests. I've added the relevant additional tests, and a first guess at what the snapshot tests will look like, so I'm probably ~20 minutes away from raising a pull request once I can run stuff, does anyone have any advice on how to progress on this?

**Comment by Ailrun** [comment]
@Brondahl Now @Andarist try to add appveyor to check error reliably on Windows CI environment.
https://github.com/emotion-js/emotion/pull/886

**Comment by Andarist** [comment]
@Brondahl Should work on Windows now :)

**Comment by Brondahl** [comment]
@Andarist , @Ailrun 
Alas not. Or at least, still not on my machine.
It seems to be doing a great deal better now, and looked like it would run to completion for a long while.
But about a minute it, it crashed with errors from what appears to be "Flow"?

It looks like it may be the same issue - paths with the wrong slash.

I'll post another output file shortly.

**Comment by Brondahl** [comment]
Hmmm... interesting.

Here's the output: 
[postFixOutput.txt, 90KB, 1148 lines](https://github.com/emotion-js/emotion/files/2467598/postFixOutput.txt)

What's interesting is that it looks like the *tests* do complete and pass:

```
Test Suites: 79 passed, 79 total
Tests:       14 skipped, 599 passed, 613 total
Snapshots:   568 passed, 568 total
Time:        77.598s
Ran all test suites.
```
and then **after** the tests have run, **then** it spits out a whole bunch of Flow errors:

```
Error ------------------------------------------ next-packages/babel-plugin-core/dist/babel-plugin-core.cjs.js.flow:2:15

Cannot resolve module `../src/index.js`.

   2| export * from '../src/index.js'
                    ^^^^^^^^^^^^^^^^^


Error ------------------------------------------ next-packages/babel-plugin-core/dist/babel-plugin-core.cjs.js.flow:3:25

Cannot resolve module `../src/index.js`.

   3| export { default } from '../src/index.js'
                              ^^^^^^^^^^^^^^^^^


Error ------------------------------------------ next-packages/babel-plugin-core/dist/babel-plugin-core.esm.js.flow:2:15

Cannot resolve module `../src/index.js`.

   2| export * from '../src/index.js'
                    ^^^^^^^^^^^^^^^^^


Error ------------------------------------------ next-packages/babel-plugin-core/dist/babel-plugin-core.esm.js.flow:3:25

Cannot resolve module `../src/index.js`.

   3| export { default } from '../src/index.js'
                              ^^^^^^^^^^^^^^^^^


Error ------------------------------------------------------ next-packages/babel-utils/dist/babel-utils.cjs.js.flow:2:15

Cannot resolve module `../src/index.js`.

   2| export * from '../src/index.js'
                    ^^^^^^^^^^^^^^^^^

etc. etc. A total of 76 errors.
```

I've never interacted with Flow, though I'm under the impression it's an alternative to Typescript?
Is this a issue in the emotion codebase? In the Flow codebase? In my machine config?

**Comment by Andarist** [comment]
Would u be able to narrow down which testing tasks spits it out? You would have to run them each one by one independently to see which one fails

**Comment by Brondahl** [comment]
So, shortly after this, my laptop froze up, required a power-cycle to use again, and in the process managed to brick the git repo (as in, it didn't know that the folder *was* a git repo, despite the presence of a `.git` folder). 

I didn't even know the latter was possible!

Once I'd recloned the repo, everything seems to be working.
So I'd chalk this one up to "Windows done some weird Sh!t".

**Comment by Andarist** [comment]
Just to confirm - every test script is working fine for you now on Windows?

**Comment by Brondahl** [comment]
Running `yarn test` runs to completion with a final output of "everything looked fine." It's still very noisy as commented above, but it is usable and gives the appearance of working.

Full output file from `yarn test &> windowsSuccessfulOutput.txt` to follow, for confirmation.

**Comment by Brondahl** [comment]
[windowsSuccessfulOutput.txt](https://github.com/emotion-js/emotion/files/2468212/windowsSuccessfulOutput.txt)

**Comment by Brondahl** [comment]
@Andarist Heya, so I had the same issue with the flow errors again today.
Restarting windows didn't immediately fix it, and after running `yarn test` a handful of times it's ended up in a weird state.
Looking through the logs, it looks like the issue is with the "Flow server" not setting itself up?

I new see 3 modes of behaviour:
#1: "fail to initialise, run out of tries before tests complete, crash the tests".
#2: "succesfully initialise, allow the tests to complete, then report loads of flow module errors" (See logs above: https://github.com/emotion-js/emotion/issues/881#issuecomment-428837609).
#3: "immediately fail with flow module errors, without starting other tests".

Behaviour pattern is:
 * Do #1 repeatedly.
 * Do #2 once.
 * Do #3 for all future runs.

The loop can be reset by closing and reopening VSCode


Throughout modes #1 and #2, I get loads of lines like this:
` Server is initializing (parsed files 55000): /`, with the number counting upwards.
The log records interspersed with all the other logs (I assume that this process is running on a separate thread)
Then I would occassionally get: `The flow server is not responding (3 retries remaining):`

It seemed like in mode #1 those 3 retries expired before all the unit tests ran and the whole thing crashed.

In mode #2, I eventually get to: `Please wait. Server is initializing (parsed files 73672): ` and then it the intialisation process sits thinking to itself, until the tests complete. After a further while it logs the flow module errors.

In mode #3 none of the above happen, we go straight into the errors:
```
PS C:\MyPath\emotionPR\emotion> yarn test
yarn run v1.10.1
$ npm-run-all -p lint:check coverage test:size test:typescript flow && npm run test:prod
$ eslint .
$ jest --coverage --no-cache --ci --runInBand
$ lerna run test:typescript --parallel
$ npm-run-all build size
$ flow
$ node scripts/build
lerna notice cli v3.4.0
lerna info versioning independent
Error ----------------------------------------------------------- packages/preact-core/dist/preact-core.cjs.js.flow:2:15

Cannot resolve module `../src/index.js`.

   2| export * from '../src/index.js'
                    ^^^^^^^^^^^^^^^^^
```

**Comment by Andarist** [comment]
Flow is a type checking system - similar to TypeScript. https://flow.org/

You can run flow by using `npm run flow`, slightly harder to run ALL tests except flow right now, can be done by running:
```
./node_modules/.bin/npm-run-all -p lint:check coverage test:size test:typescript && npm run test:prod
```
Each of the testing steps can be run on its own by using `npm run lint:check`, `npm run test:prod` etc

**Comment by Brondahl** [comment]
cool. so yes, as I suspected it's the flow stuff, and it's independant of the rest of the test stuff.

`npm run flow` run on its own demonstrates modes $2 and $3.
The other commands all run successfully, whether run before or after Flow.

Where do you want to go from here? The error message suggests that it could simply be some slashes causing problems with Flow, though, I'm unsure why it *ever* worked, in that case? Maybe I got Flow into a state where it had given up and was no longer trying?

**Comment by Ailrun** [comment]
The error of $3 looks weird, since we already removed preact-core package.

**Comment by Andarist** [comment]
Michael might still have some branch with the preact stuff as the removal of it got merged into master very recently.

**Comment by Brondahl** [comment]
How recently are we talking? I updated at the start of the weekend, to confirm that the commit-hook bug was resolved for me.

Will pull and rebase now, to check.

**Comment by Brondahl** [comment]
Nope, still getting that :)
As of `Fix peer dep versions (#929)`

**Comment by Ailrun** [comment]
Getting same error? At that commit, preact-core is already gone...

**Comment by Brondahl** [comment]
And yet, that's the output I get :)
Is this the point where I try it out on a fresh `git clone`, in case npm has cached something silly?

**Comment by Ailrun** [comment]
The errors in https://github.com/emotion-js/emotion/issues/881#issuecomment-428837609 occurs because we removed next-packages directory.
Even if we deleted all next-packages, your local dist files (those are ignored by .gitignore) are not removed, so remaining file make those errors.
These errors will be definitely gone after you remove those old files or re-clone the repo.

**Comment by Ailrun** [comment]
And I notice that your preact related errors are the same case. Even though we removed preact packages, ...

**Comment by Ailrun** [comment]
1. could be a flow problem, and I experienced that few times even in Linux (Manjaro). I'm not sure what is the exact cause of the issue, but at least it does not block other tests, does it?

**Comment by Brondahl** [comment]
A new `git clone` has fix `npm run flow` and once that's fixed, `yarn test` also runs cleanly.

So I agree, that it's probably an issue with non-git-managed files. That's still pretty disappointing though, right? (especially as it's happened twice, separately, in 2 weeks.)

Are those sort of changes going to be common, or was this stuff around preact and next-packages a weird edge case that won't come up again?

I'll try out jumping back and forth in git history, to see if I can reproduce the problem, reliably, and identify the specific files that need cleaning up, perhaps we can automate that process?
At very least we should document it.
