### ISSUE TITLE
Babel macros not working? (No contextual class names, no sourcemaps)

### ISSUE THREAD

**Issue by d3bgger** [emotion-js/emotion#894]
- `emotion` version: 9.2.12
- `react` version: 16.5.2

Relevant code.

```javascript
import { css } from 'emotion/macro';
import styled from 'react-emotion/macro';

const SomeComponent = styled.div`
  display: block;
  padding-top: 100px;
  background-color: #000;
  `
```

What you did:

I created a clean project with create react app (react-scripts 2.0.4).
I imported css and styled with /macro at the end in order to have contextual class names and source maps. 

What happened:

Project builds ok.
On browser, styles are working ok, but class names don't include the variable / component name and there are no sourcemaps. 

Shortcut styled syntax seems to be working ok though.

This is the exact same problem as in this video: https://youtu.be/1ERAJG9ILhk?t=1310

An extra question: 
When using macros instead of babel plugin, how can we disable sourcemaps in production? (and still keep contextual class names).

thanks in advance!

**Comment by jbutko** [comment]
Same problem here, can't get source maps working with macros.

**Comment by goldo** [comment]
same probleme, any news on this ?

**Comment by Andarist** [comment]
The problem has been reported against emotion@9 and, to the best of my knowledge, there are no issues like that with emotion@10. Closing this as outdated - hope you understand.
