### ISSUE TITLE
Speedy in development changes the load order of rules

### ISSUE THREAD

**Issue by jcano** [emotion-js/emotion#895]
- `emotion` version: 8.0.12
- `react` version: 16.3.0

Relevant code:
In our code
```javascript
const IconButton = styled(Button)`
  width: '40px';
  min-width: '40px';
  height: '40px';
  min-height: '40px';
  padding: 0;

  ... more rules ...
`;
```
In Webpack
```javascript
{
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('development'),
    }),
  ],
}
```

On Emotion:

```javascript
export default class StyleSheet {
  constructor() {
    this.isBrowser = typeof window !== 'undefined'
    this.isSpeedy = process.env.NODE_ENV === 'production' // the big drawback here is that the css won't be editable in devtools
    this.tags = []
    this.ctr = 0
  }

 ... more code ...
}
```

What you did:
Setting up NODE_ENV to 'development' using DefinePlugin, sets the isSpeedy variable to false, which causes rendering issues.

What happened:

The production build works as intended, the IconButton styles are applied on top of the Button styles. With the development build, the order is inverted and the Button styles are applied after the IconButton styles.

![screenshot 2018-10-05 at 13 00 44](https://user-images.githubusercontent.com/592884/46547696-98f2e300-c8c4-11e8-9402-f5973b37e734.png)

EDIT: Added some context to the Emotion code snippet

**Comment by mitchellhamilton** [comment]
Please create a reproduction in a [CodeSandbox](https://codesandbox.io) or a GitHub repo.

**Comment by jcano** [comment]
I don't know if I'll be able to replicate it on a simple project and I cannot share the actual project. At the moment, all I know is that if I manually set `speedy` to `true` on [Stylesheet](https://github.com/emotion-js/emotion/blob/03023bbfcc8df60e433a981b9a37d30db7765670/packages/emotion/src/sheet.js#L50) the styles are loaded in the right order. So it's definitely an issue with how Emotion interacts with the rest of our components. We are also using MaterialUI so there might be some issues between them.

Would you mind giving me an overview of how "speedy" works to see if I can find a workaround? Is there any known issues with MaterialUI?

**Comment by Andarist** [comment]
Speedy uses a single stylesheet and inserts rules to it, while non-speedy (development) mode creates multiple style tags - so maybe this causes an issue somehow when you have also other, non-emotion, stylesheets on your page.

**Comment by jcano** [comment]
Thanks, @Andarist! I've been playing around with this and it's going to be tricky. Upgrading to the newest version of Emotion resolves the issue and it doesn't seem to break any other styles. So for now I think that's what we'll do.

About the speedy/non-speedy mode, does it mean that if I create an `IconButton` based on a `Button` class (as on the code sample above) with speedy all style rules will be bundled together in one class while with the non-speedy mode Emotion will create a class for each object (Button, IconButton)?

**Comment by Andarist** [comment]
No, speedy doesnt change what rules are inserted but rather which browser APIs they are inserted with

**Comment by jcano** [comment]
> Speedy uses a single stylesheet and inserts rules to it, while non-speedy (development) mode creates multiple style tags

This is what I was asking about, if by single/multiple style tags you mean having one CSS class in the rendered page or multiple classes. What I'm seeing now running in `development` is that if I do

```javascript
const IconButton = styled(Button)` 
 ... styles ...
`
```

I get a single class with all the rules for `IconButton` and `Button`, instead of separate classes for each object.

This is not related to the original problem, and it's based on `v9.2.12`, so I don't know if you'd prefer I open a new ticket.
