### ISSUE TITLE
SSR renderStylesToString & css selector first-child targeting style tag

### ISSUE THREAD

**Issue by intelseb** [emotion-js/emotion#898]
- `emotion` version: 9.2.12
- `react` version: 16.5.0

Relevant code.

```javascript
@supports (display: grid) {
  .css-18gfr9p {
    margin-bottom: 0;
  }
  @media (min-width: 63.75em) {
    .css-18gfr9p:first-child {
      width: auto;
      margin-right: 0;
      grid-column-start: span 3;
    }
    .css-18gfr9p:last-child {
      width: auto;
    }
  }
}
```

Problem description:
Noticed that on SSR rendering using renderStylesToString, the style tags get inserted at the same level the other tags are used, but this poses a problem with selectors targeting the first-child. 

See image: https://imgur.com/a/q1lzJ1N

Reproduction:
SSR render via renderStylesToString, and write a selector targeting the first-child.

Workaround: 
used extractCritical for SSR rendering, where by the css was then injected into the head instead.

**Comment by JakeGinnivan** [comment]
To add to this, the `<style>` tag *becomes* the first child, and the element you actually want to target becomes the second child.

**Comment by Andarist** [comment]
This is unfortunately not that simple, because you want to target second child for a brief moment when using SSR - just till emotion move style tags into the head. And target first child as usual after that. 

This whole warning is about avoiding FOUC when doing SSR.

**Comment by intelseb** [comment]
From the looks of things it didn't move the styles into the head? Not when we were using renderStylesToString

**Comment by mpalpha** [comment]
I am very new to emotion-js but you could possibly duplicate the selector and replace `:first-child` with `>style + *:not(style)` which may work in both cases where <style> is inline or moved into <head>.

`
<style>
body:first-child span,
body>style + *:not(style) span{
  background: green;
}</style>
<style>
body:first-child span,
body>style + *:not(style) span{
  background: red;
}</style>
<p>The first paragraph<span>.</span></p>
<p>The second paragraph<span>.</span></p>
<p>The third paragraph.</p>
<p>The fourth paragraph.</p>
<p>The fifth paragraph.</p>
<p>The sixth paragraph.</p>
<p>The seventh paragraph.</p>
<p>The eight paragraph.</p>
<p>The ninth paragraph.</p>
`

**Comment by FezVrasta** [comment]
@mpalpha the issue is that `style` can actually be styled 🤐

![image](https://user-images.githubusercontent.com/5382443/60279404-44374280-9901-11e9-8777-11aef593f7f8.png)

If we went with this we should also make sure all the Emotion generated `style` tags are `<style style="display: none !important">` to make sure they can never accidentally get displayed.

Also, I think your suggested selector should be:

```css
body:first-child span,
body>style:first-child + *:not(style) span{
  background: green;
}
```

otherwise it could select other `<style>` tags in the document fragment.

**Comment by mpalpha** [comment]
> @mpalpha the issue is that `style` can actually be styled 🤐
> 
> ![image](https://user-images.githubusercontent.com/5382443/60279404-44374280-9901-11e9-8777-11aef593f7f8.png)
> 
> If we went with this we should also make sure all the Emotion generated `style` tags are `<style style="display: none !important">` to make sure they can never accidentally get displayed.
> 
> Also, I think your suggested selector should be:
> 
> ```css
> body:first-child span,
> body>style:first-child + *:not(style) span{
>   background: green;
> }
> ```
> 
> otherwise it could select other `<style>` tags in the document fragment.

just realized that, and updated the example.

**Comment by Andarist** [comment]
The more recent discussion around this is taking place here - https://github.com/emotion-js/emotion/issues/1178
