### ISSUE TITLE
Why setting className property of a styled component does not override styles ?

### ISSUE THREAD

**Issue by federico-paolillo** [emotion-js/emotion#899]
- `emotion` version: 9.2.12
- `react` version: 16.5.2

Relevant code.

```javascript

const StyledComponent = styled("div")({
  backgroundColor: "red",
  width: 64,
  height: 64
});

const App = function() {
  return (
    <StyledComponent className={css({ padding: 10 })}>
      Emotion !
    </StyledComponent>
  );
};

```
What you did:

I expected that setting `className` property of  a styled component would override all its styles.

What happened:

The styles specified using `css` got 'composed' in the styled component css class.

Reproduction: https://codesandbox.io/s/130rwlv587

Problem description:

I honestly find this behavior surprising (although very useful) because the documentation states that styles should be composed using `css` function by supplying multiple class names.

I was wondering if this behavior is has expected and if it was documented somewhere.

Suggested solution:

If what described is wanted behavior maybe it would be handy to document it, has it could be something very useful to know.
I think that an explanation of this [was given here](https://github.com/emotion-js/emotion/issues/385#issuecomment-334904063) but I was wondering if it is still relevant.

**Comment by intelseb** [comment]
I've noticed this as well, the way we got around it was creating a withClass helper which essentially just concats classnames, the same can be achieved with recompose/withProps. Emotion doesnt seem to allow you to specify custom classnames.

`import * as React from 'react'
import { cx } from 'react-emotion'

// This is a helper function to inject the classname
export function withClass(className?: string) {
    return (Component: any) => {
        const ComponentWithCustomClass = (props: any) => {
            return <Component {...props} className={cx(props.className, className)} />
        }

        return ComponentWithCustomClass
    }
}
`

const StyledComponent = withClass('customclassname')(styled("div")({
  backgroundColor: "red",
  width: 64,
  height: 64
}));

**Comment by Andarist** [comment]
This no longer is an issue with emotion@10 - https://codesandbox.io/s/emotion-question-7wwxx . Sorry we couldn't get back to you sooner, hope you understand.
