### ISSUE TITLE
Is it possible to target a primitive from unit test with Enzyme?

### ISSUE THREAD

**Issue by ekaradon** [emotion-js/emotion#902]
Hello,

- `emotion` version: 9.2.10
- `react` version: 15.6.2

Relevant code.

```javascript

const Button = styled('a')({ cursor: 'pointer', flexGrow: '1', color: '#6d6d6d' });

function MyComponent() {
    return (
        <Button />
    );
}

it('should be possible to detect a Button', () => {
    const component = shallow(<MyComponent />);
    // console.log(Button) => NO_COMPONENT_SELECTOR
    expect(component.find(Button).length).to.eql(1); // -> error, not found
});

```
I would like to be able to find with enzyme a specific primitive from a shallow or a mount rendering. It is rendered as expected from what I can see when using `component.debug()` but it seems that a primitive directly called as selector is not doing anything... 

I have seen some issues talking about babel-plugin-emotion but it does not look like the kind of things I want to do... more like a direct reference while running. Am I wrong? Is there a way to use primitive in order to inspect the rendering or is just snapshot the way to go?

Regards,

**Comment by smeijer** [comment]
Unless I'm mistaken, that will never work. Shallow rendering is all about not rendering nested components.

**Comment by ekaradon** [comment]
Well, it does work with a standard React Component. I can write this:

```javascript

function Button() {
    return <button>button</button>;
}

function MyComponent() {
    return (
        <Button />
    );
}

it('should be possible to detect a Button', () => {
    const component = shallow(<MyComponent />);
    // console.log(Button) => function
    expect(component.find(Button).length).to.eql(1); // -> ok, found
});
```

So it feels strange to me that the same thing cannot be applied to styled components...

**Comment by tpict** [comment]
Can anything be done about the name of the outer node so that it could be targeted with a prefix, something like ```js
const style = css`
color: red;
`;
const Button = props => <button css={style} {...props} />;
component.find("EmotionButton")`?
