### ISSUE TITLE
Property '__emotion_real' is missing in type ...

### ISSUE THREAD

**Issue by trusktr** [emotion-js/emotion#905]
I have a TypeScript project, and my editor (Atom) complain that

```
Argument of type '{ position: "fixed"; pointerEvents: "none"; color: string; background: string; padding: string; b...' is not assignable to parameter of type 'Interpolation'.
  Type '{ position: "fixed"; pointerEvents: "none"; color: string; background: string; padding: string; b...' is not assignable to type 'ClassInterpolation'.
    Property '__emotion_real' is missing in type '{ position: "fixed"; pointerEvents: "none"; color: string; background: string; padding: string; b...'.
```

The code is a call to `css()` which looks like this:

```tsx
            className={css({
              label: "zoomInfo",
              ...mixins.noInteraction,
              ...mixins.centerInContainingBlock,
              position: "fixed",
              pointerEvents: "none",
              color: colors.white,
              background: colors.blueishBlack,
              padding: px(40),
              borderRadius: px(10),
              opacity: 0
            })}
```

and it underlines the whole `css(...)` call in red.

Any idea what that means?

**Comment by Ailrun** [comment]
It looks like it fails to be assigned to `ObjectInterpolation`. It probably comes from `label`. I will check it.
@mitchellhamilton Is there a way to update 9 version?

**Comment by Ailrun** [comment]
@trusktr I thought it is because of `label`, but it's not the case.
I check following and it does not give any type error.
What's your `mixins` and `colors`, `px`?

**Comment by nightlyop** [comment]
I have the same error. In my case the attribute `position: 'absolute'` is the reason for it.

**Comment by Ailrun** [comment]
@nightlyop what's your full style that creates error.

**Comment by nightlyop** [comment]
@Ailrun I use different styles, e. g.

> unit: {
        position: 'absolute',
        top: '5.5rem',
        width: '100%',
        padding: '0 0.25rem',
    },

However, when I remove `position: 'absolute' `, the error disappears. When using `position: 'absolute'` only, I get the error.

I just noticed something else: The error depends also how you use `css()`
Gives the error: `className={css(styles.label)}`
No error: `className={css'styles.label'}`  <-- replace the ' with proper back ticks which are not displayed here because it causes the code mode

**Comment by Ailrun** [comment]
You can write `` ` `` by typing ``` `` ` `` ```. (Wrap code with ``` `` ```)
However, string style cannot emit any error, since TS does not support string type that checks regex or something like that.

**Comment by Ailrun** [comment]
What's the type of styles.label?

**Comment by nightlyop** [comment]
Haha stupid me. The case without error can not work. My compiler (and ma brain) seemed to have stopped working... sorry for the misinformation

**Comment by Andarist** [comment]
From what I understand the issue has been filed against emotion@9 and as we slowly get ready to v11 release. It's not practical to fix issues in previous major versions in general and especially considering our limited time resources. 

Sorry that we couldn't get back to it sooner, but I hope you understand.
