### ISSUE TITLE
Prettier and pre-commit hook are annoying and/or weirdly configured

### ISSUE THREAD

**Issue by Brondahl** [emotion-js/emotion#915]
There is a pre-commit hook that appears to run Prettier's auto-fixer (or something along those lines).

This is actively breaking things in some cases, but that's address in a separate issue: https://github.com/emotion-js/emotion/issues/914

Beyond that, it is anoying to develop with, because part of its process is to stage all local changes and commit them, rendering it impossible to perform a partial commit.

I also find the choice to remove all semicolons deeply weird? That seems counter to modern JS development styles and practises?

I can see an argument that both of these are individual preferences, so I'm happy to have this summarily closed as "Behaving as Intended". I merely wished to point it out and ask whether it really *IS* as intended, or whether it's an unintentional side effect of some other decision.

**Comment by Andarist** [comment]
> Beyond that, it is anoying to develop with, because part of its process is to stage all local changes and commit them, rendering it impossible to perform a partial commit.

You can perform a partial commit - if u want to commit only some files, but indeed you can't commit parts of the files. We use `lint-staged` (really popular tool for doing performing this kind of task) and it has an open issue about this - https://github.com/okonet/lint-staged/issues/62

> I also find the choice to remove all semicolons deeply weird? That seems counter to modern JS development styles and practises?

That's personal preference issue, I wouldnt say semicolons are that much more popular than no-semicolons in the community. I know many, modern projects which don't use semicolons.

**Comment by Brondahl** [comment]
Fair enough :) I must have only happened to interact with one side of the argument.
Like I said, I only wanted to make sure these settings were intentional.

**Comment by Brondahl** [comment]
I'm happy for this to be closed. Is that something I do, or that I let you do? (in case there's any cleanup steps you want to take.)

**Comment by Andarist** [comment]
The first issue is obviously a downside of using this solution, ideally the mentioned issue would be resolved in the underlaying tool (lint-staged). It allows us to keep code consistent & avoid styling disputes during code reviews, so it's a cost that we are "happy" to pay for the time being.

As no followup actions are required here, I'm going to just close it.
