### ISSUE TITLE
Using TypeScript and pnpm: Cannot find module 'create-emotion'

### ISSUE THREAD

**Issue by elliottsj** [emotion-js/emotion#918]
- `emotion` version: 9.2.12
- `react` version: 16.5.2

What you did:

Use TypeScript and pnpm with react-emotion, as shown here: https://github.com/elliottsj/pnpm-react-emotion-example

What happened:

This error is raised by tsc:

```
node_modules/.registry.npmjs.org/create-emotion-styled/9.2.8/node_modules/create-emotion-styled/types/common.d.ts:4:72 - error TS2307: Cannot find module 'create-emotion'.

4 import { Emotion, Interpolation as BaseInterpolation, CSSObject } from 'create-emotion';
                                                                         ~~~~~~~~~~~~~~~~
```
Reproduction:

https://github.com/elliottsj/pnpm-react-emotion-example

Problem description:

[create-emotion-styled does not declare a dependency on `create-emotion`](https://github.com/emotion-js/emotion/blob/v9.2.12/packages/create-emotion-styled/package.json#L16-L18). Due to this and the fact that pnpm provides a stricter `node_modules` structure than npm/yarn, the `create-emotion` package cannot be resolved from `create-emotion-styled`.

Suggested solution:

Add `create-emotion` in `create-emotion-styled`'s dependencies.

**Comment by Ailrun** [comment]
@elliottsj Since it takes `emotion` object, I think more appropriate way is declaring `create-emotion` as a peerDependency of `create-emotion-styled`. Will it work with pnpm? (Actually, IDK well about pnpm)
@mitchellhamilton How about your opinion?

**Comment by Ailrun** [comment]
@elliottsj 
However, one problem is `create-emotion-styled` is version@9, where now we dealt with version@10.
@mitchellhamilton Do we still manage version@9?

**Comment by Ailrun** [comment]
Emotion@10 is now released.
