### ISSUE TITLE
TypeScript typings make it hard to use functional interpolations

### ISSUE THREAD

**Issue by RoystonS** [emotion-js/emotion#930]
- `emotion` version: 9.2.12
- `react` version: 16.5.2
- `typescript` version: 3.1.3

Problem description:

There's a problem with the TS typings for the emotion packages: whilst it does eventually accept input of the correct type, it doesn't correctly infer props, making it hard to use functional interpolations.

e.g. assuming a very simple setup with a strongly-typed theme and a set of component props with just one prop:
```typescript
const styled = untypedStyled as CreateStyled<ITheme>;

interface IComponentProps {
  prop1: string;
}

interface ITheme {
  color1: string;
}

class Component extends React.Component<Themed<IComponentProps, ITheme>> {
  render() { return <div className={this.props.className} />; }
}

```
I now want to apply styling to that class.

What I'd *like* to be able to write is:
```typescript
const StyledComponentAttempt1 = styled(Component)(({prop1, theme}) => ({
  backgroundColor: prop1,
  color: theme.color1
});
```
However, this fails to compile, with TS complaining that `prop1` doesn't exist. TS has assumed that the function provided will be given a props with only a `theme` in it:
![image](https://user-images.githubusercontent.com/19773/46944263-84071400-d069-11e8-8b27-e7c8d31baae3.png)

If, however, I pull the interpolation function out and explicitly type it, it works fine:
```typescript
const interpolation: Interpolation<Themed<IComponentProps, ITheme>> = ({prop1, theme}) => ({
  backgroundColor: prop1,
  color: theme.color1
});

const StyledComponentAttempt2 = styled(Component)(interpolation);
```

This is, however, quite onerous.

**Comment by RoystonS** [comment]
In the emotion code, we have:

```typescript
export interface CreateStyledOtherComponent<InnerProps extends object, Theme extends object> {
  <Props extends object, OverridedTheme extends object = Theme>(
    ...args: Array<Interpolation<Themed<Props, OverridedTheme>>>
  ): StyledOtherComponent<Props, InnerProps, OverridedTheme>;
}
```

Should this instead be
```typescript
export interface CreateStyledOtherComponent<InnerProps extends object, Theme extends object> {
  <Props extends object, OverridedTheme extends object = Theme>(
    ...args: Array<Interpolation<Themed<Props & InnerProps, OverridedTheme>>>
  ): StyledOtherComponent<Props, InnerProps, OverridedTheme>;
}
?
```

That is, to define the `...args` array as
```typescript
    ...args: Array<Interpolation<Themed<Props & InnerProps, OverridedTheme>>>
```
instead of

```typescript
    ...args: Array<Interpolation<Themed<Props, OverridedTheme>>>
```
?

**Comment by Ailrun** [comment]
This will be fixed in emotion@10.

**Comment by Ailrun** [comment]
Emotion@10 is now released.
