### ISSUE TITLE
Emotion styles do not get loaded after bundling

### ISSUE THREAD

**Issue by RicheyRyan** [emotion-js/emotion#945]
I'm having a problem and I was hoping you might be able to at least point me in the right direction.

I have an NPM package that contains all our components. I have the following packages:
```
"create-emotion": "^9.2.12",
"emotion": "^9.2.12",
```
I'm using create-emotion to set the key attribute to something like `{companynamespace-projectnamespace}`

The code in this repo is transpiled using babel. It uses the emotion babel plugin.

The NPM package is required in our Create React App application. We are using version 1.1.5. When testing locally everything works fine. I have tested with the package linked and with it published to NPM and it works in both cases.

When I run `react-scripts build` and run the built app I start to run into an issue. The style tag with my custom key is inserted into the head as expected, but the CSS is not there. 

We use the template literal syntax but I have tried the object syntax too and that didn't make a difference.

I'm not sure how to proceed. If could advise me, I'd really appreciate it. 

Is there anywhere, in particular, I should look at?

Thanks,
Richey

**Comment by mitchellhamilton** [comment]
Could you create a reproduction?

**Comment by RicheyRyan** [comment]
Yeah sorry, I'm working on that. I had to get this live another way so I couldn't finish off the reproduction. I got it the build setup pretty much as I described above and it works. So it seems like some interaction in the legacy app I'm working on.

I'll be looking at it more today so I'll let you know if I discover the root cause.

**Comment by RicheyRyan** [comment]
Ok so I investigated a bit more and I have a pretty concrete example.

What is happening is this:
I have emotion styled components in a component library.

I use create-emotion to add a key which namespaces my components.

I import the component library into my app. Due to the nature of my app, I have to create an iframe and load my components inside.

Because create-emotion is wrapped inside my component library I cannot pass it the container param for my iframe.

The workaround I reached was taking all the CSS from the namespaced style tags inserted into the head and passing them into the iframe.

This works ok when running Create React App locally. When you run the Create React App build, the CSS is no longer put in the namespaced style tags in the head.

Because of this the styles no longer make it into the iframe.

There is a repo with repro steps here: https://github.com/RicheyRyan/emotion-test

I have an idea of how I might fix it but I'd appreciate any advice you have.

Thanks again,
Richey

**Comment by RicheyRyan** [comment]
Can I continue using create-emotion for the namespacing? I've updated to the beta but create-emotion doesn't seem to use the key anymore?

**Comment by RicheyRyan** [comment]
Our styles can be loaded in an environment that is not fully ours. To avoid conflicting with other CSS, we need to namespace our styles.

I'm going to close this now. I haven't been able to make progress and the project won't wait so I have to put it aside for now. I hope to maybe revisit emotion later once we've made some larger changes in the project.

Thanks for all your help!
