### ISSUE TITLE
Props conflicting on 10.0.0-beta.5 and plugin 0.6.9

### ISSUE THREAD

**Issue by schleumer** [emotion-js/emotion#948]
- `emotion` version:
```
"@emotion/babel-plugin-core": "^0.6.9"
"@emotion/core": "^10.0.0-beta.5"
"@emotion/styled": "^10.0.0-beta.5"
```
- `react` version: 16.5.2

Relevant code.

```javascript
<div>
  <FormattedMessage id="home.welcome" defaultMessage="Welcome, {name}" values={{ name: 'Nice name' }} />
</div>
```

What you did:

Tried to use beta version with `react-intl`

What happened:

Babel plugin have overwritten component's props with other values.

Before plugin activation
![screenshot_8](https://user-images.githubusercontent.com/2557681/47216857-bc199a00-d37c-11e8-8357-de6890c3abd9.png)

After plugin activation
![screenshot_10](https://user-images.githubusercontent.com/2557681/47216867-c89df280-d37c-11e8-98db-2727cea1ee1c.png)

I actually can figure whether it's a `react-intl` issue or `emotion` one, just reporting because it happened after activate `emotion` plugin.

**Comment by mitchellhamilton** [comment]
Use `babel-plugin-emotion@next` instead of `@emotion/babel-plugin-core`

**Comment by schleumer** [comment]
Wow, that was fast! Thank's for the great library and help.
