### ISSUE TITLE
Feature request: Disallow nesting

### ISSUE THREAD

**Issue by johnnysprinkles** [emotion-js/emotion#953]
I was directed to Emotion from a feature request in styled-components and this looks like exactly what I want. Don't want to wrap all my components just to style them, and do want to write my CSS as bareword text instead of object literals. I'm surprised I hadn't heard of Emotion before.

https://github.com/styled-components/styled-components/issues/2132

Anyway, one thing that would make it even better is taking one of Aphrodite's best features, no nesting, and making it an option in Emotion. Naturally you'd have nesting where it's essential for pseudo selectors and media queries, but other than that just classes on elements in a very direct and easy to analyze fashion.

I love CSS, well except for the Cascade part, and the Sheets part, and I'm certainly not alone there. "CSS in JS" in general fixes the Sheets-as-external-document part, and some discipline or compile time enforcement can much reduce the Cascade part.

OK:

    css`
      border: 1px solid red;
    `

Error if opt-in to no nesting:

ERROR:

    css`
       a {
         color: orange;
       }
    }

I don't know, seem like a good idea at all?

**Comment by brandonkal** [comment]
I disagree that the cascade should be avoided, as it is the best feature of CSS.

But what you are looking for is a linting rule which can be done with stylelint: https://stylelint.io/user-guide/rules/max-nesting-depth/

**Comment by FezVrasta** [comment]
Note that one of the most useful features of emotion is the ability to target other styled components.

```js
const A = styled.div();
const B = styled.div`
  ${A} { color: red;}
`;
```

Anyways, @brandonkal provided a valid solution so I'm going to close this issue. Feel free to continue here is needed.
