### ISSUE TITLE
With babel-plugin-macros not configurable

### ISSUE THREAD

**Issue by J-Kallunki** [emotion-js/emotion#965]
Cannot configure autoLabel with babel-plugin-macros. By default with ENV=development it should be true.

- `emotion` version: 10.0.0-beta.5 and 9.2.12
- `react` version: 16.6.0

```javascript
import styled from 'react-emotion/macro'
import {
  css,
  keyframes,
  injectGlobal,
  flush,
  hydrate
} from 'emotion/macro';

const className = css`
  color: hotpink;
  label: some-name;
`
const anotherClassName = css({
  color: 'lightgreen',
})
render(
  <div>
    <div className={className}>{className}</div>
    <div className={anotherClassName}>
      {anotherClassName}
    </div>
  </div>
)
```

What you did:
yarn create react-app my-app
yarn add emotion react-emotion
yarn add -D babel-plugin-macros

.babelrc:
```json
{
  "plugins": ["macros"]
}
```

What happened:
className has label but anotherClassName does not.

Reproduction:
yarn start
(by default uses ENV=development)

Suggested solution:
"To specify that your plugin is configurable, you pass a configName to createMacro:"
https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/author.md#config-experimental

**Comment by cweekly** [comment]
Hi @J-Kellunki, FWIW I'm seeing a similar issue and concur w/ your analysis. I'm not a committer here but if you create a fork that fixes this, I'd be happy to give it a whirl. If I find time to create a PR I'll let you know.

**Comment by mitchellhamilton** [comment]
I think that this isn’t really a big deal anymore now that autoLabel is enabled by default. If anyone really wants to configure the macro still then please open another issue.
