### ISSUE TITLE
Custom props create invalid html

### ISSUE THREAD

**Issue by hackhat** [emotion-js/emotion#968]
Custom props like here https://github.com/emotion-js/emotion/blob/master/docs/styled.md creates invalid html.

I have a component with `height` and creates this dom `<div height="40">...`

Any way to remove this attribute?

**Comment by Andarist** [comment]
```js
import isPropValid from 'emotion/is-prop-valid'

const Div = styled('div', {
  shouldForwardProp: prop => isPropValid(prop) && prop !== 'height'
})`
  color: green;
  height: ${props => props.height};
`
```

**Comment by Andarist** [comment]
Closed as the question has been answered.
