### ISSUE TITLE
extractStatic outputDir bug: css outside the project

### ISSUE THREAD

**Issue by eatsjobs** [emotion-js/emotion#969]
@wardpeet @tkh44  @mitchellhamilton I got a strange result with extract static. I know it's a deprecated feature but at the moment i can't switch to linaria o css-literal-loader. Please(on my knees) is it possibile to only have this fix in the babel plugin?Or a way to workaroud for now?

Problem: 
When transpiling with babel cli:

```javascript
babel src --out-dir esm --ignore 'src/**/*.spec.js,src/**/*.test.js' --copy-files
```
I got this result:
- *.css are generated but outside my folder project
- the import '*.css' in the transpiled code is somenthing like:
```javascript
import "../../Projects/src/Accordion/AccordionItem.emotion.css";
```

- OS: macOS Mojave
- node version v8.12.0

```javascript
    "@babel/cli": "^7.1.2",
    "@babel/core": "^7.0.0"
"emotion": "^9.2.8",
    "emotion-theming": "^9.2.6",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-emotion": "^9.2.8",
"babel-plugin-emotion": "^9.2.11"
```

```javascript
//.babelrc
["emotion",{
                        "autoLabel": true,
                        "hoist": true,
                        "sourceMap": false,
                        "extractStatic": true,
                        "outputDir": "esm"
                    }
                ]
```

**Comment by Andarist** [comment]
This option has been removed in emotion@10 and currently there are no plans to re-introduce it.
