### ISSUE TITLE
Need help with Typescript, Theme and createEmotionStyled combination

### ISSUE THREAD

**Issue by Tsury** [emotion-js/emotion#982]
I use `createEmotionStyled` to create my instance because I want to disable prefixing.
I also pass a theme to the `ThemeProvider`.

This is how I export my instance:

```
const styled = createEmotionStyled(emotion, React) as CreateStyled<Theme>;
export default styled;
```

Now, as far as Typescript goes, I experience 2 issues:
1. In `styled` template literals functions, `props` is of type `any`. Shouldn't it contain a `theme` property of type `Theme`?
2. I receive Typescript errors when passing custom props to my `styled` components.

What could be causing this? How to use this combination properly with Typescript?

Relevant dependencies:
```
    "create-emotion": "9.2.12",
    "create-emotion-styled": "9.2.8",
    "emotion": "9.2.12",
    "emotion-theming": "9.2.9",
    "react-emotion": "9.2.12",
    "babel-plugin-emotion": "9.2.11",
    "typescript": "3.1.3"
```

Edit: I think I managed to create an instance with my theme using `as CreateStyled<Theme>`, but now my 2 issues are:

1. In `styled` template literals functions, `props` contains only a `theme` prop. When I try to add a custom prop it is obviously missing from props type. Do I need to always explicitly merge the two types like `props: Theme & MyPropsType`? There must be a better way
2. I'm using `ant-design`, and I use `styled` on some of their components, to add style. Seems like they are using their own props types, which causes an incompatibility with `styled`. For example, when trying to style their `Spin` component, this is the error:

```
Argument of type 'typeof Spin' is not assignable to parameter of type 'ComponentType<SpinProps>'.
  Type 'typeof Spin' is not assignable to type 'ComponentClass<SpinProps, any>'.
    Types of property 'propTypes' are incompatible.
      Type '{ prefixCls: Requireable<string>; className: Requireable<string>; spinning: Requireable<boolean>; size: Requireable<string>; wrapperClassName: Requireable<string>; indicator: Requireable<...>; }' is not assignable to type 'ValidationMap<SpinProps>'.
        Property 'style' is missing in type '{ prefixCls: Requireable<string>; className: Requireable<string>; spinning: Requireable<boolean>; size: Requireable<string>; wrapperClassName: Requireable<string>; indicator: Requireable<...>; }'.
```

I can override it if I write `styled(Spin as any)` but obviously this is just a bad workaround.

**Comment by Ailrun** [comment]
@Tsury Thank you for your issue.
1. You can use type generics parameters. By passing appropriate `MyProps`, you can use both theme and you props without `: Theme & MyPropsType`.
2. It looks like their typings have some problems. `Spin` is not valid `React.ComponentClass`, which is the type used to type react components.

**Comment by Andarist** [comment]
I believe this issue has been filed against emotion@9 which is the previous major version. It's hard for me to assess if current emotion@10 suffers from the described issue as well. Additionally TS types are getting a general makeover (https://github.com/emotion-js/emotion/pull/1501). This hopefully should make it easier to type things and get rid of common problems - so stay tuned!

**Comment by JakeGinnivan** [comment]
@Tsury I am pretty sure #1501 will sort your issues out. We had a bunch of similar type inference issues before the fixes in that PR.
