### ISSUE TITLE
Docs source code not up-to-date with emotion.sh/docs URL

### ISSUE THREAD

**Issue by amitnovick** [emotion-js/emotion#986]
What you did:

Noticed this detail in the [Docs](https://emotion.sh/docs/babel-plugin-emotion) page:
> Currently every API except for the css prop is supported by the macro.

Since I must've missed this sentence, I thought I should propose emphasized revision of it as PR.

I went over to the [documentation source](https://github.com/emotion-js/emotion/edit/master/packages/babel-plugin-emotion/README.md) and see that it's not up-to-date, this is the section I got in the source code:
```markdown
## Babel Macros

Instead of using `babel-plugin-emotion`, you can use emotion with [`babel-plugin-macros`](https://github.com/kentcdodds/babel-plugin-macros). Add `babel-plugin-macros` to your babel config (which is included in Create React App 2.0) and use the imports/packages shown below.
```

While this is the version on the [Docs](https://emotion.sh/docs/babel-plugin-emotion):
```
Babel Macros

Instead of using babel-plugin-emotion, you can use emotion with babel-plugin-macros. Add babel-plugin-macros to your babel config and import whatever you want from emotion but add /macro to the end. Currently every API except for the css prop is supported by the macro.
```

## Suggested solution:
Update the URL content based on latest state of the documentation source code repo.

![babel-macro-docs-issue](https://user-images.githubusercontent.com/43674238/47941924-c7320580-def8-11e8-9c95-4c958b2b477e.png)

**Comment by Andarist** [comment]
I believe that currently the published documentation is automatically synced with master. If the problem is still there, please file a new issue.
