### ISSUE TITLE
How can I find the corresponding <style data-emotion> tag of my styles?

### ISSUE THREAD

**Issue by athrunsun** [emotion-js/emotion#990]
- `emotion` version:9.2.12
- `react` version:16.2.0

I am using emotion across my app and I have a lot of styles for my components.

Here is a snippet in one of my component,

```javascript
const myStyles = ecss({
    display: 'flex',
    '& .child': {
        alignSelf: 'center',
    },
});
```

**Problem description:**
There are so many `<style data-emotion>` tags in the `<head>` section of the webpage.

![emotion_issue](https://user-images.githubusercontent.com/1920454/47950805-75d65480-df92-11e8-81fb-66f57f58ea33.png)

When my element `<div className={myStyles}><div className="child">...</div></div>` does NOT have the expected styles, how do I find the corresponding `<style data-emotion>` tag for `myStyles` (so that I am able to locate the generated styles then find out what's wrong)?

**Comment by tkh44** [comment]
I think you are looking for source maps which can be enabled via the babel plugin. 

https://github.com/emotion-js/emotion/tree/v9.2.12/packages/babel-plugin-emotion#sourcemap (Check out the "recommended setup" on that page)

**Comment by athrunsun** [comment]
@tkh44 Thanks for your feedback.

However I was not looking for source map, which I've already been using.

Consider the generated html webpage like this:

```html
<!doctype html>
<html>

<head>
    <style data-emotion>
        ...
    </style>
    <style data-emotion>
        ...
    </style>
    <style data-emotion>
        ...
    </style>
    <style data-emotion>
        ...
    </style>
    ...
</head>

<body>
    <div class="css-10wdwfl-myStyles">
        <div class="chlid">...</div>
    </div>
</body>

</html>
```

When I opened my Chrome developer tool and located `<div class="css-10wdwfl-myStyles">`, I can see source map very clearly, sth. like this:

![emotion_issue_1](https://user-images.githubusercontent.com/1920454/47959001-49165180-e013-11e8-94ab-360b74d3fd93.png)

However, when I located `<div class="chlid">` (NOTE I wrote 'child' as 'chlid' by mistake), no styles are applied (b/c the class name is wrong).

When I didn't realize this typo at first sight, I went ahead trying to find out which of the `<style data-emotion>` tag has the generated css for `myStyles`.

Typo is only a simple case, there's more complicated ones like:

```javascript
const myStyles = ecss({
    display: 'flex',
    '& .child': {
        alignSelf: 'center',
    },
    '& .child:not(:last-child)': {...},
});
```

If I still didn't make myself clear, let me put it simple in this way:

1. Is there a REPL for emotion to see generated css on the fly (instead of actually rendering it in the webpage)?
2. Is there any way to inject the hash string `10wdwfl` into the style tag like `<style data-emotion hash="10wdwfl">...</style>` so that I can locate the generated styles according to class name (`css-10wdwfl-myStyles`) more easily?

Feel free to point out my misunderstandings if I had.

**Comment by Andarist** [comment]
This can be quickly found with:
```js
const findStyleForHash = hash => [...document.querySelectorAll('[data-emotion]')].filter(s => s.textContent.indexOf(hash) !== -1)

// example usage
findStyleForHash('4klygg')
```

While the idea to attach those hashes in development to style tags makes sense it doesn't play well with how currently code is structured. It would be doable, but a little bit hacky. Additionally, as emotion can generate quite a bit of style tags in dev mode it still would be pretty hard to locate the one you are interested in "manually" - that's why I believe this short snippet is enough for this issue to be closed, especially that it can help you find what you are looking for way quicker than if you would look for it manually.
