### ISSUE TITLE
PropsOf helper doesn't understand union prop types

### ISSUE THREAD

**Issue by ncknuna** [emotion-js/emotion#991]
- `@emotion/styled` version: 10.0.0-beta.7 
- `react` version: 16.6.0 and 16.7.0-alpha.0
- `typescript` version: 3.1.6

Relevant code.

```ts
import * as React from 'react'
import { PropsOf } from '@emotion/styled-base/types/helper'

class UnionPropComponent extends React.Component<{ prop: string } | { otherProp: number }> { }

type props = PropsOf<typeof UnionPropComponent>
```

What you did:

I was trying to get `styled` to work with a React Component with Union types (specifically, Ant Design's Button component. Doc: https://ant.design/components/button/ ; types: https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx#L65). 

What happened:

Type inference failed to infer the types correctly. I tracked it down to the `PropsOf` helper, which will infer `never` for even basic components with union PropTypes, like above ^.

Reproduction:
I tried to reproduce on codesandbox, but I couldn't manage to get the import of PropsOf to work correctly: https://codesandbox.io/s/xnrw73yow

I can reproduce pretty reliably on VSCode though.

Suggested solution:
Unfortunately, I don't think I know TypeScript well enough to suggest a solution :(

**Comment by Andarist** [comment]
Sorry for not responding back sooner. TS types are being reworked right now in https://github.com/emotion-js/emotion/pull/1501 and this helper `PropsOf` is being removed as part of this PR, so this issue won't be actionable on our side anymore. After this PR gets merged in please check if you can handle your use case OK and if not please report a new issue then. Thank you for understanding.

**Comment by JakeGinnivan** [comment]
@ncknuna @Andarist yep, pretty sure this will be fine. There is now a test for props with unions.

After it lands if that isn't the case it may be slightly different to the tests but this is the test:

```
interface PropsA {
  title: string
}
interface PropsB {
  content: string
}

type PropsAB = PropsA | PropsB
class A extends React.Component<PropsAB> {
  static getDerivedStateFromProps(props: PropsAB) {
    return null
  }

  render() {
    return null
  }
}

const B = styled(A)`
  color: red;
`
;<B title="test" />
;<B content="test" />
```
