### ISSUE TITLE
Unable to compose themed css in emotion10

### ISSUE THREAD

**Issue by piotrblasiak** [emotion-js/emotion#997]
- `emotion` version: 10.0.0-beta.8
- `react` version: 16.6.0

Relevant code.

```javascript
const css1 = theme => ({background: "black"});
const css2 = {color: "white"};

return <div css={[css1, css2]}/>
```

What you did:

Tried to compose with one of the parts being a function/themed css.

What happened:

"Functions that are interpolated in css calls will be stringified..."

Is this by design or a bug? The workaround I found is to use the spread operator and call on the css function:

````
<div css={theme => ({...css1(theme), ...css2})/>
```

But this forces me to know if css1 is a function or not.

**Comment by piotrblasiak** [comment]
It doesn´t say in the docs that it needs to be a string - and IMO it would make a lot of sense to be able to put a function or an object in there as well.

**Comment by defusioner** [comment]
Would be nice to have this feature. Actually the workaround is to make `css={theme => [css.class1(theme), css.class2]}`

**Comment by gordonmleigh** [comment]
@defusioner Composition order doesn't seem to work with this approach.

**Comment by Andarist** [comment]
@gordonmleigh what do you mean? Could you share repro case and actual/expected outcomes?

**Comment by gordonmleigh** [comment]
Turns out my problem was elsewhere, I was getting confused.

**Comment by Andarist** [comment]
This will be possible in upcoming v11, we’ve just merged in https://github.com/emotion-js/emotion/pull/1130 which implement this
